### ISSUE TITLE
In charts, show number along with percentage

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1004]
Currently in charts, we show only percentages for individual responses and the number of total responses. It will be nice to show counts of individual responses too so that users don’t have to calculate them. We already fetch that data , so it is just a matter of displaying them.

**Comment by gabemart** [comment]
My proposed implementation:

<img width="824" alt="screen shot 2015-07-16 at 15 43 29" src="https://cloud.githubusercontent.com/assets/2589977/8726345/891a21fc-2bd1-11e5-8016-f1ec29cbaf5b.png">
<img width="404" alt="screen shot 2015-07-16 at 15 43 48" src="https://cloud.githubusercontent.com/assets/2589977/8726346/891adae8-2bd1-11e5-98e5-3daa634b1afe.png">
<img width="750" alt="screen shot 2015-07-16 at 15 43 57" src="https://cloud.githubusercontent.com/assets/2589977/8726347/891d0282-2bd1-11e5-8ec5-0a071e1d2bbc.png">

**Comment by joycarpediem** [comment]
@gabemart , can we also display Total values for the bar charts like we have for the doughnut chart

**Comment by gabemart** [comment]
Added now:

<img width="419" alt="screen shot 2015-07-17 at 10 49 27" src="https://cloud.githubusercontent.com/assets/2589977/8744756/9654bcc4-2c71-11e5-8709-f2619441a9ba.png">
<img width="739" alt="screen shot 2015-07-17 at 10 49 41" src="https://cloud.githubusercontent.com/assets/2589977/8744757/966a95f8-2c71-11e5-88a7-334ae64db7ba.png">

**Comment by gabemart** [comment]
# Test Plan

1) Create a survey with a question group

2) Create an option question

3) Populate the option question with some responses

4) Navigate to the Chart Builder and select that question

5) Generate each type of chart (doughnut, vbar, hbar) for that question

6) Verify that for each chart type: i) the number of responses for each answer is shown, after the percentage for that answer, and ii) the total number of responses for the question is shown

**Comment by rumca** [comment]
test plan passes as described :+1:
