### ISSUE TITLE
Display submitter name and survey name in map

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1005]
Currently we just display the collected date for a survey instance in the map view. This makes it really difficult to find that particular record in the data tab with just the collected date. We should at least display the survey title and the Submitter name along with the collected date.

**Comment by janagombitova** [comment]
@mtwestra Is this still relevant?

The latest CartoDB changes include that only once the user selects a survey, the data points will be shown on the maps and when previewing the collected data we display the data point name, data point ID and submission date. Do you think we still need to display the submitter name as well?
