### ISSUE TITLE
Show how much data has been collected for forms

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1008]
In the survey screen, we should show how many data points have been collected for a survey. 

We don't really have this number at the moment, so it is not clear what is the best way to handle this.

**Comment by janagombitova** [comment]
This issue relates to: what information is useful for users to see in the survey overview as well as how will we show our users how much forms they have submitted in total to keep track of their usage and pricing tiers. Both questions are open in the product design repository (opportunity backlog) so I am closing this one from here for now.
