### ISSUE TITLE
Cascade resource should become unpublished on edit

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1009]
At the moment, the status of a cascade does not change when a manual edit is made

**Comment by mtwestra** [comment]
Test plan:
1. create a cascade resource and publish it
2. upon adding a level, the status should change to unpublished in the UI
3. upon adding a node, the status should change to unpublished in the UI
4. upon changing a level name, the status should change to unpublished in the UI

**Comment by rumca** [comment]
tested and works as expected on release/1.8.1
