### ISSUE TITLE
Enable 'use as data point name' on cascading questions

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1011]

**Comment by ichinaski** [comment]
**Test plan:**
* Edit a question. Selecting a `cascade` type should display the datapoint name checkbox.
* Ensure the value is saved.

*Note: the app requires no futher tests. It automatically handles any type of question with this flag*

**Comment by muloem** [comment]
@ichinaski doesn't this mean the display name will include the pipe separated list that represents a cascade response?  that may not be very readable for the user and probably also not show well on the display right?

**Comment by janagombitova** [comment]
@mtwestra Do we have use case for this? I agree with @muloem that this will not provide a readable data point name for the users on the devices.

**Comment by joycarpediem** [comment]
I think even pipe separated values will be "sufficiently readable". Users generally use the Order by Name feature so that the records are neatly stacked up.
Display names almost always are" admin regions - respondents name" and cascades are almost always used for admin regions .So without them showing up in the diaplay name I think we are missing a critical piece.

**Comment by muloem** [comment]
What if we only display the last element in the pipe separated list? After all that is the point right; to drill down to a specific value.


----- Original Message -----

**Comment by muloem** [comment]
@ichinaski had a chat with @joycarpediem @janagombitova and conclusion is that if we include this we should make it consistent with the way display names are currently displayed, i.e. pipes in the cascade should be replaced by hyphens.

**Comment by ichinaski** [comment]
@muloem That would basically break the *packed responses* format consistency, right? We use pipes for all compound responses at the moment.

Also, and this is just a personal opinion, I think it could make sense to display both pipes and hyphens, as they have a very different meaning: users are already accustomed to seeing hyphens in datapoint names, and pipes is compound responses. Additionally, note that the hyphens include leading and trailing spaces, therefore resulting cascade values with hyphens won't be as packed as they are now.

On top of this, changing the cascade responses would cause backwards compatibility issues, namely in monitoring surveys with existing cascade questions (the app would need to parse both pipes and hyphens for synced forms).

It short, it is definitely feasible, but this change arises some concerns we need to look into if we want to take it forward.

**Comment by muloem** [comment]
@ichinaski I left out an important detail which is replace the pipes *only* in the `displayName` field. So the consistency here was referring to the visual consistency. The value stored in responses remains pipe-separated.

**Comment by ichinaski** [comment]
Okay.

This also means updating the GAE test harness I presume (datapoint name recalculation).

**Comment by muloem** [comment]
Yep.

**Comment by ichinaski** [comment]
I can handle both changes. This is for the next release I understand?

**Comment by muloem** [comment]
Yeah given we would like to have the next RC this afternoon, makes sense to push it by one release.  We can go ahead and merge it into develop later this week though.

**Comment by ichinaski** [comment]
Cool, will do :+1:

**Comment by rumca** [comment]
@ichinaski just to double check, this checkbox appears to have been enabled for option and number question types too - is that intended?

**Comment by ichinaski** [comment]
@rumca that was the policy we had earlier as far as I understand. This change merely adds the cascade questions to that set.

**Comment by rumca** [comment]
roger that - my bad, didn't realise this flag was already available for other question types besides free text.

Cascade works as described in the test plan above :+1:
