### ISSUE TITLE
Implement new question type: Geographic shape

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow#1012]
# Description:
 TODO

Relevant design repo issue: https://github.com/akvo/akvo-product-design/issues/66

**Comment by mtwestra** [comment]
Test plan:
1) In a survey, create a new question
2) In the question, it is possible to select 'geographic shape' as the question type
3) As additional options, the user can select these options:
  1. Allow creation of points
  2. Allow creation of lines
  3. Allow creation of areas
  4. Disable manual editing of geo values on device
3) On a newly created survey, the first three should default to true, the last one to false
4) After publishing, the XML contains the following fields (values depending on choice):
<question order="1" type="geoshape" mandatory="true" localeNameFlag="false" id="xxxxxxxxx" allowPoints="true" allowLine="true" allowPolygon="true"><text>Geoshape question</text></question>

**Comment by rumca** [comment]
Test plan passes
