### ISSUE TITLE
The `path` property of a SurveyGroup and Survey are not updated correctly during autosave

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1019]
With the changes to fix #1016, if a user is editing a survey and/or form and then navigates away from the page via the breadcrumbs menu or another tab, the UI now executes an autosave of the users content.  The autosave does not include the correct `path` property.

**Comment by stellanl** [comment]
The path of a Survey is also not updated if the containing Survey folder is moved to another folder.

**Comment by janagombitova** [comment]
This issue links to #2505 as there we also show which data export was created for which folder > survey > form, thus we need to ensure that is is always up to date and correct for Salim to be able to easily recognise his data exports and not to get confused

**Comment by kymni** [comment]
We should consider doing away with this property altogether and always display folder/survey/form paths as a computed property

**Comment by muloem** [comment]
To add to Charles' comment, we never use that property anywhere in the backend so I agree that it is a UI element and we should therefore get rid of it from the backend.

**Comment by kymni** [comment]
Handling front-end bit under #2507
