### ISSUE TITLE
Question ID uniqueness is no longer respected

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1040]
The dashboard warns a user that the question id is not unique, however it doesn't prevent them from saving it down anyway - whereas before it used to prevent the question being saved with a non unique ID:

![screen shot 2014-12-18 at 20 20 48](https://cloud.githubusercontent.com/assets/3003031/5495215/9ce9c97c-86f3-11e4-9a6d-1eececc8ab1e.png)

**Comment by jonase** [comment]
This issue should be fixed in 1.8.1. Related issue: https://github.com/akvo/akvo-flow/issues/905
