### ISSUE TITLE
Handle Excel import/export correctly when cascading questions are present

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1041]
When a user selects to download a raw data report with question ID as the table header, we do not provide anything for the ID of the cascade resource. Perhaps we could include something like ``questionID_cascadeLevelName``

**Comment by mtwestra** [comment]
* In a raw data report, the one used for data cleaning, created from the data tab, we will use the usual combination of id and question text. The cascade column will remain a single column, with the answers concatenated by a pipe character

* In a data export file, such as created from the report tab, we will use either the question text or the questionID, depending on the choice of the user. In addition, the cascade column will be split into different columns. The name of the cascade column will QUESTION_ID_levelName, with QUESTION_ID either the question text, or the questionID

**Comment by iperdomo** [comment]
## Test plan

Using a survey that contains a _cascade_ question (and after collecting data):

### Exporting

* Export RAW DATA report __not__ using the option _Use question id as column header_:
  * All the question columns must follow the patter `keyId|question text` (except the initial ones, date, submitter, etc)
  * The _cascade_ question data __must__ be in one cell using the format `level1|level2|level3[...]`
* Export RAW DATA report __using__ the option _Use question id as column header_:
  * The question column headers must use the _question id_ if present, or fallback to the question text
  * The _cascade_ question data will be splitted in several columns, and the column headers will contain: `question_id_levelName` if the question has a _question id_ or `question text - levelName` if no _question id_ has been defined


### Importing
* A _RAW DATA_ report using _question id_ as column header is not valid for data import
* A _RAW DATA_ report using the valid pattern `keyId|question text` is allowed in the import process.
  * Changing the data of the cascade question should be reflected after a succesful import and export

**Comment by muloem** [comment]
:+1: code reviewed!

**Comment by rumca** [comment]
The above test plans all pass for exporting and importing :+1: 

One really really minor comment, perhaps we should trim whitespace on cascade names? When exporting with ``Use question id as column header`` selected with names such as ``" dsafasdf asdf sd"`` we end up with a header like ``some_id__dsafasdf_asdf_sd``
