### ISSUE TITLE
Minor UI Issue - Scroll to save button on the Devices tab > Manage Device Groups

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1042]
If the user has a small resolution or a smaller browser window opened, it is not currently possible for them to access the save button on the "Manage Device Groups" popup on the Devices tab, we need to add a scroll bar in this situation:

![screen shot 2014-12-18 at 12 51 33](https://cloud.githubusercontent.com/assets/3003031/5495310/4ef62098-86f4-11e4-952c-0f96ca94f84f.png)

**Comment by muloem** [comment]
Resolved with #1210
