### ISSUE TITLE
Enable editing of Cascade Resource names, disable editing of Cascade level names when they haven't been added yet

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1045]
As per outstanding task on #189 - we need to enable the editing of cascade resource names once they have been created.

Another really minor issue, but one that could perhaps lead to some confusion. When users are creating a cascade resource, they have the option of editing level names before the level has been added:

![screen shot 2014-12-18 at 21 43 52](https://cloud.githubusercontent.com/assets/3003031/5496449/271d9a28-86ff-11e4-8b1a-e2617f63db41.png)

For example in the above screen shot they can change the name of level 2 and 3, despite the fact that it's a 1 level cascade at the moment.

**Comment by iperdomo** [comment]
@rumca on your second observation, the way to get back to the Cascade Resource editing is by clicking the `Cancel` button. Is that user flow the one you're mentioning?

**Comment by rumca** [comment]
@iperdomo whoops! I didn't realise the cancel button would bring be back during the testing. I had been simply clicking `Import Cascade Data` to get back to the previous screen. Perhaps we can make the cancel button a bit more noticeable? Based on where it is at the moment - I thought it was to do with the file selection options.

**Comment by iperdomo** [comment]
@loicsans any input @rumca's proposal?

**Comment by iperdomo** [comment]
## Test plan

* Create a new cascade resource
  * Only the first level column should be shown
* Add new level (no. 2)
  * A new column with the possibility of editing the level name should be shown
* Add a new level (no. 3)
  * A new column with the possibilty of edting the level name should be shown
* Add a new level (no. 4)
  * Nothing should change in the column layout

**Comment by rumca** [comment]
The above test plan passes :+1:
