### ISSUE TITLE
Minor dashboard quirks relating to publishing status or publish functionality

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1046]
I've noticed the the publishing status or publish buttons do not update correctly in certain situations:
- Regular workflow for creating a survey, when the user clicks to publish a survey, we should disable the button once it has been clicked
- Any update to an already published cascade resource should change the status to unpublished, to notify the user that their changes need to be re-published.
- Minor issue, but when a Survey has been published we should colour the publishing status green like we do with the cascade resource as this makes it easier to quickly distinguish (I think this might have actually worked previously, just lost the styling at some stage)

**Comment by janagombitova** [comment]
![survey version2](https://cloud.githubusercontent.com/assets/12456965/20535895/1fc00978-b0e7-11e6-8e4e-ca22891ce3e6.gif)

In this issue we will only tackle the points related to improving the Publish button on the form page, not the issue related to cascades. That is handled in a separate issue

**Comment by janagombitova** [comment]
closing this issue are linking it to the relevant separate issues
