### ISSUE TITLE
Make publishing status easily determined from the survey overview

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1047]
This ones not an issue, but it would perhaps be nice to include publishing status along with "created", "modified", "type", and "language" on the survey overview:

![screen shot 2014-12-10 at 12 03 07](https://cloud.githubusercontent.com/assets/3003031/5375656/88b8fbde-8064-11e4-8cca-8eeba525207e.png)

**Comment by janagombitova** [comment]
Added this issue to a larger opportunity in the product design repository https://github.com/akvo/akvo-product-design/issues/180
