### ISSUE TITLE
Last remaining missing translations for both French and Spanish

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1049]
@iperdomo @loicsans I think these are the only untranslated strings we have left, but it's sort of like a game of spot the difference so I could well have missed a few.

On the Edit Survey Screen, when you scroll to the Form section both the "preview" and "delete" options don't have translations:

![screen shot 2014-12-19 at 01 06 17](https://cloud.githubusercontent.com/assets/3003031/5498799/4e192972-871c-11e4-8726-33d603ff844e.png)

On the first Cascade Resources screen you come to, the long string and button text aren't translated:

![screen shot 2014-12-19 at 01 07 20](https://cloud.githubusercontent.com/assets/3003031/5498807/721b807c-871c-11e4-9149-a59300d782ab.png)

On the selected Cascade Resource screen we need translations for "Add A Level", "code", "new item name (mandatory)", "add", "save", "cancel":

![screen shot 2014-12-19 at 01 08 06](https://cloud.githubusercontent.com/assets/3003031/5498827/af54e26c-871c-11e4-9283-b8e203c0932a.png)

**Comment by mtwestra** [comment]
partial duplicate of https://github.com/akvo/akvo-flow/issues/1055

**Comment by iperdomo** [comment]
## Test plan

* Using a different languange than English, visit the Dashboard and you should see the labels/strings translated to the selected language
* Check for:
  * Edit Survey Screen > Form > "preview" and "delete" 
  * Cascade Resources the prompt message, and button
  * When editing a Cascade Resource the buttons "Add Level"
  * The input text boxes prompts (code and item name)

**Comment by loicsans** [comment]
French translation done

**Comment by rumca** [comment]
Missing translations now present on release/1.8.1 :+1:
