### ISSUE TITLE
Wrong icon in the previous & next buttons

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#1052]
The `« Previous` and `Next »` buttons are showing a text selection icon instead of the usual _click me_ cursor.

* https://www.dropbox.com/s/2k0sj3wkun3a7fi/mouse-cursor.webm?dl=1

**Comment by mtwestra** [comment]
@iperdomo On which page do these buttons appear?

**Comment by iperdomo** [comment]
@mtwestra @joycarpediem this is the _Users_ tab, the list of users. Attached a screenshot.
![users](https://cloud.githubusercontent.com/assets/178474/8648229/3a5d38f2-295f-11e5-87b9-30030c236e0f.png)

**Comment by gabemart** [comment]
### Test Plan

1) Open the "Users" tab

2) Scroll to the bottom of the page

3) Hover the cursor over the "Next" and "Previous" buttons

4) Verify that cursor changes from the default cursor to the "pointer" cursor (a wee hand)

**Comment by rumca** [comment]
re-opening this just to remind myself to test it - will close again after

**Comment by rumca** [comment]
test plan passes as described
