### ISSUE TITLE
Fix missing Spanish and French translations 

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1055]
Keri found some missing Spanish translations:

Data Tab: Cascade Resources, Choose a defined resource, -- If you set the dashboard to Spanish there are a few things that are not translated the words: Level, Code, Add, A, New, Item, Name, Mandatory

![screen shot 2015-01-07 at 10 10 46](https://cloud.githubusercontent.com/assets/478954/5643179/7c93eb8c-9655-11e4-96c3-08f3dca5a010.png)

Giel found some missing French translations:

1. When going to the DATA section and when choosing import CASCADE-question I noticed still some text in English, even though I was on the French version of the site. I don’t know who can modify the text but here’s a translation of the text marked in the red circle: 
- Sélectionnez une cascade existante ou en créer un nouveau 
- Ajouter une nouvelle cascade

2. When going through the DATA section and then choosing the DATA CLEANING-tab I came across another small part which was not translated:

Translation of this part: 
Choisissez le fichier - Pas de fichier choisi

![adding_cascade-question_in_dashboard](https://cloud.githubusercontent.com/assets/478954/5659026/780abbe8-970b-11e4-9e67-c41d2c79673c.png)
![data_cleaning_tab](https://cloud.githubusercontent.com/assets/478954/5659027/780b7650-970b-11e4-8aa6-79757cb2e1f9.png)

**Comment by mtwestra** [comment]
partial duplcate of https://github.com/akvo/akvo-flow/issues/1049

**Comment by mtwestra** [comment]
Found some other English messages in the ‘Messages’ tab in the French version of the Dashboard. 
See screenshot below:
![screen_shot_2015-01-12_at_16 54 47](https://cloud.githubusercontent.com/assets/478954/5718160/05ad6394-9b0b-11e4-8720-9a5830bec286.png)

When creating a cascade-question I found another piece which was in English (when using the French version of our the site) 

The translation here would be: Choisissez un Fiche - Pas de Fiche choisi 
Could someone please change this? Thank you in advance.

![screen_shot_2015-01-12_at_16 01 18](https://cloud.githubusercontent.com/assets/478954/5718176/35a8a1da-9b0b-11e4-8eee-6901fe7c777d.png)

**Comment by iperdomo** [comment]
@mtwestra there is no _easy_ way of translating the messages in `Messages` tab, the reason for those are _system_ messages, we need to go through all the the available system messages, and design a way to translate them, e.g those translation key require placeholders, something that we don't support, e.g. `Successfully imported %s` -> `%s importado satisfactoriamente`

**Comment by iperdomo** [comment]
We're not going to fix the _System_ messages on this release

**Comment by rumca** [comment]
Everything bar system messages appears to be translated now
