### ISSUE TITLE
Enable deleting full datapoints and forms inside data point

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1058]
On the Monitoring tab, a user can get a list of data points, and view the contents. However, sometimes a user wants to delete a data point including all the formInstances, or delete an individual formInstance inside a datapoint. At the moment, this is not possible, and the user needs to find the forms in the inspect data tab, and delete them one by one.

Proposal: 
* Add a 'delete' action to the data point list, so a user can delete a full datapoint, including all forms
* Add a 'delete' action to the list of formInstances inside a data point, so a user can delete a single formInstance directly in the data point view

**Comment by mtw-media** [comment]
Test plan 1:
* create a monitoring survey and collect some data. Some datapoints should contain more than one filled form
* go to the monitoring subtab in the data tab, and select the survey, and click 'Find'
* select 'View details' on one of the data points. A popup should appear with filled forms contained in it
* behind each filled form, a 'delete' option is present.
* If only a single form is present, this should happen when 'delete is clicked':
    * A DELETE request is fired to the backend to delete the surveyInstance (= filled form)
    * The filled form disappears from the popup UI
    * The data point disappears from the data point list UI
* If more than one filled forms are present, the following should happen when 'delete is clicked':
    * A DELETE request is fired to the backend to delete the surveyInstance (= filled form)
    * The filled form disappears from the popup UI
    * The data point is still present in the data point list UI

**Comment by mtwestra** [comment]
Test plan for delete action on forms in data points:
* create a monitoring survey and collect some data. Some datapoints should contain more than one filled form
* go to the monitoring subtab in the data tab, and select the survey, and click 'Find'
* select 'View details' on one of the data points. A popup should appear with filled forms contained in it
* behind each filled form, a 'delete' option is present.
* If only a single form is present, this should happen when 'delete is clicked':
    * A DELETE request is fired to the backend to delete the surveyInstance (= filled form)
    * The filled form disappears from the popup UI
    * The data point disappears from the data point list UI
* If more than one filled forms are present, the following should happen when 'delete is clicked':
    * A DELETE request is fired to the backend to delete the surveyInstance (= filled form)
    * The filled form disappears from the popup UI
    * The data point is still present in the data point list UI

**Comment by mtwestra** [comment]
Test plan for delete action on forms in data points:
* create a monitoring survey and collect some data. Some datapoints should contain more than one filled form
* go to the monitoring subtab in the data tab, and select the survey, and click 'Find'
* select 'View details' on one of the data points. A popup should appear with filled forms contained in it
* behind each filled form, a 'delete' option is present.
* If only a single form is present, this should happen when 'delete is clicked':
    * A DELETE request is fired to the backend to delete the surveyInstance (= filled form)
    * The filled form disappears from the popup UI
    * The data point disappears from the data point list UI
* If more than one filled forms are present, the following should happen when 'delete is clicked':
    * A DELETE request is fired to the backend to delete the surveyInstance (= filled form)
    * The filled form disappears from the popup UI
    * The data point is still present in the data point list UI

**Comment by mtwestra** [comment]
Test plan for delete action on data point list:

* create a monitoring survey and collect some data. Some datapoints should contain more than one filled form
* go to the monitoring subtab in the data tab, and select the survey, and click 'Find'
* each data point shown has a 'delete' action
* When clicked, a confirmation dialogue is shown
* when confirmed, the data point is deleted (a DELETE request by the browser)
* in addition, the containing filled forms are deleted (by the backend DELETE rest service)

**Comment by rumca** [comment]
The above test plan seems to pass - but I'm seeing the same issue as with #1104 whereby the following error is thrown ``DELETE http://uat1.akvoflow.org/rest/survey_instances/13699115 500 (Internal Server Error)`` however the data seems to be successfully removed from the dashboard (can't retrieve via inspect data tab, monitoring tab, or by exporting raw data exports).

**Comment by iperdomo** [comment]
@rumca can you paste the error stack trace from the logs ?

**Comment by rumca** [comment]
@iperdomo sorry, I pasted it here: https://github.com/akvo/akvo-flow/issues/1104#issuecomment-71882868 - same error so wasn't sure which one to put it on

**Comment by iperdomo** [comment]
@rumca @mtwestra this is actually a bug. It seems we can't get a `surveyId` from a deleted instance, so we need to cache the value before deleting it. Yes the problem was introduced trying to fix #1104

**Comment by rumca** [comment]
The above test plan now passes - perhaps a minor enhancement we could make is to automatically close the popup when deleting the last response in the list:

![screen shot 2015-02-02 at 13 14 03](https://cloud.githubusercontent.com/assets/3003031/6001069/63309338-aadd-11e4-862b-c9c8bf673af6.png)
