### ISSUE TITLE
Identifier search not working on monitoring tab

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1059]
When a user enters an identifier in the identifier search field in the Monitoring tab, the server responds with a 500 internal server error, quoting a missing datastore index for this search.

Proposed solution: add identifier index to datastore-indexes.xml

**Comment by mtwestra** [comment]
Example: 
instance: ctbburundi
survey: BDI_BISEM_VF
a data point with identifier chqg-0r6r-g7an exists, but is not found.

Cause: the first time 'Find' is clicked, a cursor is added to the search, which makes the search fail

**Comment by mtwestra** [comment]
Test plan:
1) Go to the monitoring tab, select a survey that has a lot of data (more than a screenful), and click 'Find'
2) Copy one of the identifiers of the list in the identifier list, and click 'Find'
3) The right element should be found straight away.

**Comment by rumca** [comment]
@mtwestra the search functionality on this tab seems to have been broken. I can see Monitored data being submitted on the "Inspect Data" tab and can export a raw data report for the forms, however when I am on the "Monitoring" tab and select the survey - nothing is returned once I select search.

**Comment by rumca** [comment]
scratch that, identifier search works fine - it's the drop downs which don't work.
