### ISSUE TITLE
Allow deletion of individual questions in a survey

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1061]
At the moment, we do not allow deletion of individual questions in a survey. However, this is overly restrictive, as in many cases, it is decided after some experimentation with a survey that some questions, including the answers, need to be removed.

Proposed solution:
* Allow deletion of single questions in a survey
* When a question is deleted, all related data for this question is deleted as well
* Present a confirmation popup to the user with this message before deletion.

**Comment by janagombitova** [comment]
Adding idea to opportunity backlog
