### ISSUE TITLE
Handle deleted data in monitoring data download 

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1062]
At the moment, the way devices download data for monitoring is to do a first download, and then do incremental downloads, based on the timestamp of the last download.

However, this does not account for data that has been deleted in the mean time, as deleted data is not visible to this mechanism. This leads to data remaining on the devices that has been deleted on the dashboard.

Proposed solution:
-  introduce a mechanism to notify devices of deleted data during the data sync.

**Comment by janagombitova** [comment]
Related to this issue: https://github.com/akvo/akvo-flow-mobile/issues/877
