### ISSUE TITLE
Paging functionality on Users tab malfunctions

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1065]
The "Next" button on the users tab does not become deactivated even when the end of the users list is reached, i.e., one can go on clicking it even when the list is exhausted.

**Comment by jonase** [comment]
## Test plan

* It should not be possible to click `next` or `previous` and get an empty list of users
* The `next` button should be disabled when you reach the end of the users list
* The `previous` button should be disabled when you are on the first page

**Comment by rumca** [comment]
Tested and works as expected on release/1.8.1
