### ISSUE TITLE
GeoJSON display on dashboard

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1069]
With the implementation of issue https://github.com/akvo/akvo-flow-mobile/issues/236, the dashboard will receive GeoJSON information in questions answers. The Dashboard needs a way to meaningfully display this data. 

Proposed solution:
1) in a list of answers, when geojson data is present, a link is shown 'show on map'. When the user clicks this, a panel slides out which displays the geojson data on a small map.
2) on the map, when a user clicks on a marker, the geojson of that point, if present, is displayed.

**Comment by janagombitova** [comment]
related to https://github.com/akvo/akvo-product-design/issues/107 and to https://github.com/akvo/akvo-flow/issues/1356

**Comment by janagombitova** [comment]
Closing issue as it is handled with the above referenced issues
