### ISSUE TITLE
Check validity geoJSON with geoJSON linter and QGIS

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1070]
For the Geoshape question, we generate geoJSON. We need to check if this geoJSON is compatible with cartoDB and QGIS.

**Comment by mtwestra** [comment]
First test: http://geojsonlint.com/

**Comment by mtwestra** [comment]
Test string generated by app:
{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[34.955981858074665,5.18391374096442],[34.29096803069115,-0.8795901949768219],[39.69658076763153,-4.608226716219518],[41.84362471103668,-1.3735044449966767],[41.88162557780743,4.161316151363382],[34.955981858074665,5.18391374096442]]]},"properties":{"pointCount":"5","length":"3222047.75","area":"679916645710.55"}},{"type":"Feature","geometry":{"type":"LineString","coordinates":[[28.671350218355656,59.32554152732291],[28.365638740360737,55.96642813821991],[31.361604854464527,55.493037022891684],[32.278737276792526,52.13824815775404],[40.27307532727718,49.30398073812746],[39.371227473020554,47.41516740753058]]},"properties":{"pointCount":"6","length":"1814748.25"}},{"type":"Feature","geometry":{"type":"MultiPoint","coordinates":[[-3.073657304048538,39.91745312556732],[2.836553044617176,46.63692493882356],[10.474364161491394,51.741345355827264],[19.657871648669243,51.95666130231343],[28.405469208955765,53.752025144947474]]},"properties":{"pointCount":"5"}}]}

Result using http://geojsonlint.com/ 

![screen shot 2015-01-23 at 11 30 14](https://cloud.githubusercontent.com/assets/478954/5873098/459cc608-a2f3-11e4-8a45-60f8f60fc6c9.png)

**Comment by mtwestra** [comment]
Test with http://geojson.io:
![screen shot 2015-01-23 at 11 36 15](https://cloud.githubusercontent.com/assets/478954/5873179/1508caa4-a2f4-11e4-9925-7efd1f9a1fd7.png)

**Comment by mtwestra** [comment]
Apparently, QGIS does not support multiple types in one file: "be aware that Qgis doesn't support mixed types in the same file (point, line, poly) and it will open only the first type found."

When draging and dropping the geoJSON file above to qgis, you get a dialogue asking which layer to import:
![screen shot 2015-01-23 at 11 40 17](https://cloud.githubusercontent.com/assets/478954/5873272/ddbb5930-a2f4-11e4-8ff7-6bf0b9970bcb.png)

After importing all, the result is:

![screen shot 2015-01-23 at 11 40 41](https://cloud.githubusercontent.com/assets/478954/5873268/d565f4d4-a2f4-11e4-93c8-031a9e33136f.png)

**Comment by mtwestra** [comment]
Conclusion: the GeoJSON we create is valid.

**Comment by mtwestra** [comment]
Test plan:
1. Using the new geoshape feature, create a feature with a combination of points, lines, and shapes.
2. use http://geojsonlint.com/ to check the validity of the geoJSON by checking if the displayed shapes are correct.

**Comment by rumca** [comment]
Covered by test plan in https://github.com/akvo/akvo-flow-mobile/issues/236#issuecomment-71443865
