### ISSUE TITLE
Clarifying Administrator rights in user roles & permissions

### ISSUE THREAD

**Issue by JosjeS** [akvo/akvo-flow#1074]
Hi All, 

At the moment it is unclear (and confusing) what the "Administrator?" tickbox on the user roles page means. (see screenshot one).

Also when you have made someone administrator no role shows up on the users page (screenshot two). I am not sure if this is the right way. Maybe naming it 'dashboard administrator' or 'super admin' would be an idea?

Also when you add a new user you can only fill in name & e-mail and select 'administrator?', you cannot immediately assign user roles (see screenshot 3). After you click 'save' you go back to the userlist and you have to edit the user to give him/her a role. I think this is inefficient and it would make more sense that when you add a user you can also select the rights. 

![screenshot 1](https://cloud.githubusercontent.com/assets/4329924/5722696/c16b3fce-9b3e-11e4-92e3-4c7268839032.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/4329924/5723002/12d637f4-9b41-11e4-951e-ed6169f4e9a1.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/4329924/5723104/b0066b16-9b41-11e4-8b31-05e886404585.png)

Thanks, 
Josje

**Comment by mtwestra** [comment]
@emmanuel, this is already done, right?

**Comment by muloem** [comment]
@mtwestra yes this is already done and can be closed.
