### ISSUE TITLE
Code improvements on RemoteAPI class

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#1082]
The idea behind the class `RemoteAPI` is to avoid the boilerplate code. Getting a `DataStoreService` instance can be done in this class, and just pass the parameter. We want the classes implementing `Process` to focus in the business logic.

**Comment by iperdomo** [comment]
## Test plan

* Use the `RemoteAPI` class with the `DeleteData` process to remove data: 

````
java org.akvo.gae.remoteapi.RemoteAPI DeleteData <appid> <usr> <pwd> <surveyId>
````

**Comment by rumca** [comment]
@iperdomo can we close this one?

**Comment by iperdomo** [comment]
@rumca yeap
