### ISSUE TITLE
Implement ability to copy form from other survey into active survey

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1097]

**Comment by janagombitova** [comment]
**Copy FORMS** 

1. within the same survey (monitoring) in the same instance
2. from one survey to another in the same instance

**To be added:**
- copy button on form level
- a way to identify where to paste in the copied form (can reconsider creating a new better UX + UI for copying in general and apply it on all levels) 
- a way that shows the user that FLOW is copying (when it takes more time)

**Not to forget:**
- the new form (copied version) must be only saved and the user needs to publish again 
- dependency rule cannot be broken 
  - + when user copies entire form and then starts deleting question and groups which she does not need, there is a chance of breaking the dependency rule → we need to add a notification that will inform the user that they will break the dependency if they delete this item
     - “Are you sure you want to delete this question group with all its containing questions? This might break a dependency rule you have created. Please check before deleting. This cannot be undone.” ← something like this
- cascade resource must be copied as well
- repeatable question groups + inside dependency 
- ensure that question IDs stay unique
- look up relations do not break with copying

**Comment by janagombitova** [comment]
closing this issue for now as lives in the opportunity backlog
