### ISSUE TITLE
Always save email addresses as lowercase

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow#1098]
When creating a new user we should make sure that the email address is saved as lowercase

**Comment by stellanl** [comment]
Actually, the user part of an email address is case sensitive; a server *could* have two different users Foo@example.com and foo@example.com

**Comment by jonase** [comment]
@stellanl The authentication mechanism we use depends on email addresses being lowercase.

**Comment by jonase** [comment]
## Test plan

* Create a new user with some uppercase letters in the email address. Make sure that the email is still saved as lowercase.
* Edit an existing user and add some uppercase letters to the email address. Make sure that the email still contains only lower case letters after save.

**Comment by stellanl** [comment]
Then we cannot handle all legal email addresses, as defined by RFC 2822.

**Comment by iperdomo** [comment]
@stellanl you're right and we're not supporting. Remember that we're dealing Google email accounts here, where `Name.Lastname@gmail.com`  ~ `name.lastname@gmail.com` ~ `namelastname@gmail.com`

**Comment by rumca** [comment]
Tested and works as intended on release/1.8.1 :+1:
