### ISSUE TITLE
Cannot add a role to a user

### ISSUE THREAD

**Issue by CharlotteSoed** [akvo/akvo-flow#1101]
Dashboard: http://tiipaalga-co2logic.akvoflow.org/admin/ 
Browser: Chrome

I am in a Skype training, trying to give user 'Herman Noppen' permission to Survey folder 'TiiPaalga', but the drop down with user roles isn't showing, so I cannot make a selection to add user roles - see screenshot. 

![screen shot 2015-01-22 at 10 10 58 am](https://cloud.githubusercontent.com/assets/4288835/5853067/dd7818b2-a21f-11e4-86bd-2c57b3e8b60b.png)

**Comment by muloem** [comment]
Closing this issue.  It was a new instance with no legacy users and therefore no default roles defined.
