### ISSUE TITLE
Publishing cascade resource causes nodes to disappear from UI

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1102]
Steps to reproduce:

1. Go to `Data > Cascade Resources`

2. Define a number of cascade nodes up to three levels deep

3. Publish the cascade resource

4. Go to the Messages board to verify system confirmation 

5. Go back to `Data > Cascade Resources` and select the resource from the drop down.  The cascade nodes are not visible anymore.

Checking in the datastore the cascade nodes are visible but the call `/rest/cascade_nodes?cascadeResourceId=xxxx&parentNodeId=0` to the backend returns an empty list

**Comment by mtwestra** [comment]
This also happens like this:
1. create a new cascade with some items
2. go to a different tab and come back
3. select the cascade from the list
4. the nodes are not shown.

**Comment by mtwestra** [comment]
Test plan:
1. create a new cascade
2. add a first item in the first column
3. go to another tab (for example, surveys)
4. go back and select the cascade
5. the nodes should be there.

**Comment by rumca** [comment]
The above test plan passes :+1:
