### ISSUE TITLE
RAW DATA report improvements

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#1103]
Generating a _RAW DATA_ report on a large dataset can take several minutes (depending on the number of questions), we want to improve the situation by implementing:

* A filter `From` - `To` to limit the dataset of exported data, similar to the filters in the Data > Inspect Data tab
* When a user requests a new report, if we don't have a cached version to deliver it immediately, we notify the user that an email with the report will be delivered in some minutes

**Comment by jonase** [comment]
@loicsans Could you take a look at the from/to date styling under Reports > Export Reports

**Comment by jonase** [comment]
## Test Plan

*High level changes:*
* Reports that are not immediately ready for download (i.e. cached on flow-services) will be emailed to the user.
* Ability to add to/from collection date filter for raw data reports

### Test
* Go to `Reports > Export Reports` in the Dashboard.
* Choose a survey and do a "Raw Data Report" without to/from dates specified.
* Wait for email with link to where the report can be downloaded
* Request the same survey again, it should now be immediately downloaded in your browser
* Look at the collection dates in the downloaded report
  * Request a report with `to` date specified
  * Request a report with `from` date specified
  * Request a report with both `to` and `from` dates specified
* Check your email again and download the three reports
* Check that the date limits you specified are correct in the reports. Note that the `to` date *is inclusive*.
* Test the other kinds of reports (Export comprehensive report, Export raw text file, Export survey form) and make sure that the download link is correct for them as well.

**Comment by rumca** [comment]
Tested and works as expected :+1: 

@iperdomo one minor comment - the email I receive when I request a Spanish report has a bizarre character in the subject:

![screen shot 2015-02-18 at 11 12 20](https://cloud.githubusercontent.com/assets/3003031/6246357/fdbe6e82-b75f-11e4-9097-ddda3dd27a5c.png)

Not sure if that means it'll be more likely to get spam filtered or not.

**Comment by iperdomo** [comment]
@jonase can you make sure the `es.properties` encoding is the correct one? I think we mentioned that this `á` character could be problematic

**Comment by rumca** [comment]
Spanish characters work fine now.

Zero idea how I missed this the first time - but trying to export with with no to and from dates seems to result in an exception being thrown on FLOW services

**Comment by rumca** [comment]
Null date now handled correctly - test plans all pass :+1:
