### ISSUE TITLE
Deleting surveyInstance uses wrong id for notifying flow services

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1104]
In the SurveyInstanceRestService, we send the surveyInstanceId to the notification service. This should be the survey id.

https://github.com/akvo/akvo-flow/blob/develop/GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyInstanceRestService.java#L201

**Comment by iperdomo** [comment]
That bug was introduced trying to fix issue #265

**Comment by mtwestra** [comment]
Test plan:
1. export a raw data report from a survey containing data
1. delete a surveyInstance from the dashboard from this survey
2. export the raw data report again. The surveyInstance should not be there anymore.

**Comment by rumca** [comment]
@mtwestra the above test plan doesn't pass. The following happens instead:

* Export raw data report
* Delete response through dashboard
* Item no longer appears in the inspect data tab
* Export raw data report, item is still present (despite not being present on inspect data tab)

I thought everything was working as intended during the general regression test, but it seems there's been a regression somewhere. 

Not sure if it's related, but after opening the console window whilst deleting items I see the following ``DELETE http://uat1.akvoflow.org/rest/survey_instances/18489120 500 (Internal Server Error)``

**Comment by rumca** [comment]
From the GAE logs: 
```
Uncaught exception from servlet
javax.jdo.JDOUserException: Cannot read fields from a deleted object
FailedObject:com.google.appengine.api.datastore.Key:SurveyInstance(16519115)
	at org.datanucleus.jdo.state.PersistentDeleted.transitionReadField(PersistentDeleted.java:115)
	at org.datanucleus.state.AbstractStateManager.transitionReadField(AbstractStateManager.java:561)
	at org.datanucleus.state.JDOStateManagerImpl.isLoaded(JDOStateManagerImpl.java:1900)
	at org.waterforpeople.mapping.domain.SurveyInstance.jdoGetsurveyId(SurveyInstance.java)
	at org.waterforpeople.mapping.domain.SurveyInstance.getSurveyId(SurveyInstance.java:180)
	at org.waterforpeople.mapping.app.web.rest.SurveyInstanceRestService.deleteSurveyInstanceById(SurveyInstanceRestService.java:201)
```

**Comment by iperdomo** [comment]
See - https://github.com/akvo/akvo-flow/issues/1058#issuecomment-71910160

**Comment by rumca** [comment]
Test plan above works fine now :+1: 

The deletion task seems to still be throwing an exception though:
```
E 2015-02-02 14:02:11.501
org.waterforpeople.mapping.app.web.DataProcessorRestServlet surveyInstanceSummarizer: Couldnt find geoplace for instance. Instance id: null
```
If this doesn't have any behavioural impact (seems that it doesn't), I'll open a new issue and we can fix it in a forthcoming release.
