### ISSUE TITLE
Users unable to create sub folders when parent folder name contains trailing spaces

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow#1110]
When a user tries to create a folder within a folder to which they are assigned all the correct permissions, the `New Folder` appears and then disappears again.  The user is neither able to edit the folder name, nor save the Folder. Looking at the backend, it appears that an *Access Denied: Insufficient Permissions*  error is thrown.  On further investigation, it appears this is caused by the name of the parent folder having a trailing space.  When permissions are being validated the paths to folders are trimmed and so the trailing space does not match.

**Proposed solution:** We should trim folder, survey and form names on save and edit actions since trailing whitespace causes problems for determining permissions

**Comment by jonase** [comment]
## Test plan

* Edit existing (or create new) folder, survey and form
* Add trailing and leading whitespace and save.
* Observe the rest request made, the `name` and `code` properties should not have trailing or leading whitespace.

**Comment by rumca** [comment]
Not sure what's going on but it's still possible to create folders with leading and trailing whitespace in release/1.8.2 - perhaps we need to add the same validation from the survey/form level to the save on Folder (i.e. when a user hits enter after changing the name etc)?

**Comment by rumca** [comment]
Editing the folder name now correctly strips out leading and trailing whitespace :+1: 

However I've noticed an issue whereby when a user clicks "Add Form" instead of "Save" and they have a Survey name which contains either leading or trailing whitespace - then this is not trimmed correctly. Presumably we just need to add the same ``trim()`` calls to the add forms handler.

**Comment by rumca** [comment]
I've tried to create a survey/folder/form with trailing or leading whitespace in several different ways and haven't been able to succeed - so I think we can close this one now.
