### ISSUE TITLE
Update to latest clojurescript & om releases

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow#1117]

**Comment by jonase** [comment]
## Test plan

* Nothing should have changed from the users perspective by these changes.
* Deploying the application should work as before, and the users tab should be correctly built
  * Verify by visiting the tab and optionally checking that "users.min.css" is loaded (as opposed to "users.css" which is used while developing)

**Comment by rumca** [comment]
Tested with release/1.8.3 and the above test plan passes without issue :+1:
