### ISSUE TITLE
Trailing spaces in question options prevent display of dependent questions

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1123]
#### How to reproduce:

1. Create a survey with an option type question and define a number of options.  For some of the options add a trailing space at the end of the option text.

2. Create a number of dependent questions to each of the options

3. Publish and assign the survey to a device

4. Start responding to the questions.

Dependent questions are not shown when selecting the question options that had trailing spaces at the end does.

**Comment by muloem** [comment]
### Test Plan

1. Create a survey and add an option question. Add a list of options with extra leading and trailing spaces surrounding the option items

2. Create a second question that is dependent on two options of the previously created question.

3. Assign to a device

4. Fill out a response on the device. Select one of the options to show the dependent question. Ensure that the dependent question appears

**Comment by rumca** [comment]
Tested on release/1.8.2 and works as expected
