### ISSUE TITLE
No `Previous` button when browsing responses under the Data tab

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1125]
**Steps to reproduce:**
1. Go to the `Data > Inspect Data` tab

2. Select a survey known to have over 20 responses and select `Find`

3. Click on the `Next` button to see next batch of 20 responses.

**Observed:**
There is no `Previous` butting to look at the previous set of records.

**Comment by muloem** [comment]
### Test Plan

1. Create a survey monitoring or not with a number of questions

2. Fill in over 20 responses. (over 40 responses even better)

3. Go to  the inspect data tab and browse the responses and ensure that you are correctly able to browse back and forth between the pages using the `Next` and `Previous` buttons

**Comment by rumca** [comment]
Test plan passes as described. If it's a quick fix it might be nice to sort the styling on the ``next`` and ``previous`` links, otherwise we can address it next release I guess:

![screen shot 2015-11-25 at 17 37 28](https://cloud.githubusercontent.com/assets/3003031/11404781/a1c5f244-939b-11e5-975d-9b6ff23b97bf.png)

**Comment by rumca** [comment]
@muloem I'm not sure if it's the commits related to this or #1299 but the messages tab now throws an error on loading: 

```
Uncaught TypeError: Cannot read property 'indexOf' of undefined
DS.FLOWRESTAdapter.DS.RESTAdapter.extend.setQueryCursor	@	app.js:1
DS.FLOWRESTAdapter.DS.RESTAdapter.extend.sideload	@	app.js:1
d	@	ember-1.0.0.pre-2-36.min.js:1
DS.RESTAdapter.DS.Adapter.extend.didFindQuery	@	ember-data-rev10.min.js:2
DS.FLOWRESTAdapter.DS.RESTAdapter.extend.didFindQuery	@	app.js:1
d	@	ember-1.0.0.pre-2-36.min.js:1
ajax.success	@	ember-data-rev10.min.js:2
k	@	jquery.min.js:2
l.fireWith	@	jquery.min.js:2
y	@	jquery.min.js:2
d
```

**Comment by rumca** [comment]
both of the above comments have been addressed now :+1: 

@gabemart could you possibly add the same alignment tweaks for the ``next`` button on the Messages tab also? It currently appears the same way the inspect data one did.

**Comment by gabemart** [comment]
Currently the "Next" and "Previous" buttons don't seem to show up on the Messages tab, even though there are enough messages to trigger their appearance. The actual markup for the links isn't being injected, so I assume that `hasNextPage` is returning false in the view. I don't know what's causing this yet - nothing relevant seems to have changed in either the template or the view recently.

**Comment by gabemart** [comment]
@jonase Is it possible that the changes in https://github.com/akvo/akvo-flow/issues/855 are relevant to this? Is there something that could have made pagination for the Messages tab work for a while, then not work?

**Comment by rumca** [comment]
Slightly odd as the links were definitely appearing last night and were misaligned (unless I was hallucinating :worried: ) 

Since there's something other than styling broken here, I'll close this issue and we can address it at some other stage.

**Comment by muloem** [comment]
@rumca @gabemart the `Previous` and `Next` links on the messages tab have not been functioning for a while as far as I can tell. If we want to fix this we will have to create a separate issue as there is more to fix than just the CSS.

**Comment by rumca** [comment]
I logged it a (wee) while ago here https://github.com/akvo/akvo-flow/issues/411 however both Gabe and I have seen it intermittently working which is a bit odd.
