### ISSUE TITLE
Recover language options (or remove all together) on Data Cleaning tab

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1126]
On the export reports screen we have the option to select a language you would like to download the report in. This drop down is also present on the Data > Data Cleaning tab - however it isn't actually populated with anything, so does nothing:

![screen shot 2015-02-03 at 12 55 30](https://cloud.githubusercontent.com/assets/3003031/6020453/f53c48aa-aba3-11e4-8c87-feffa06795ee.png)

**Comment by janagombitova** [comment]
Solution (after discussing this issue with Emmanuel): remove the language support under data cleaning

**Comment by gabemart** [comment]
### Test Plan

1) Navigate to Data > Data Cleaning and select a Survey and Form

2) Verify that no language select dropdown appears after the form dropdown

**Comment by rumca** [comment]
Test plan passes as described.
