### ISSUE TITLE
Cascade editor - add ability to remove empty levels

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1127]
@iperdomo At the moment we have the ability to add levels through the editor - but no way to remove them once added (I could be missing something though). Perhaps it would be a nice feature to be able to remove empty cascade levels.

**Comment by janagombitova** [comment]
Reported by support last week, we should simply add the option to delete

**Comment by janagombitova** [comment]
<img width="1439" alt="Screenshot 2021-02-02 at 20 02 33" src="https://user-images.githubusercontent.com/12456965/106649340-b538e480-6591-11eb-9dd3-3151a512ef64.png">

Jigmy mentioned this today in a call we had.
