### ISSUE TITLE
Create a data script to get the stats public|private data

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#1131]
The program should output:

    appid,surveyId,surveyName,type,count

**Comment by iperdomo** [comment]
## Test plan

In the scripts/data folder, execute:

    java -cp bin:lib/* org.akvo.gae.remoteapi.RemoteAPI PublicPrivateInstanceCount <appid> <gae-usr> <gae-pwd> <batch-size> <appid> # yes, appid 2 times

**Comment by rumca** [comment]
Tested and works as expected (I cheated and ran from my IDE though :scream: )
