### ISSUE TITLE
Enable 'other' on last level of cascading question

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1144]
In using a cascading question, it often happens that the items on the deepest level are not very accurate, or not complete. This means that it can be difficult for enumerators to fill in such a cascade. On the other hand, simply letting enumerators fill in the deepest level as a separate question as free text leads to a lot of data cleaning.

To remedy this, the proposal is to add an option to cascade questions, which adds an 'other' option to levels of the cascade. It could work like this:
1. have an 'add other' option in a cascade question
2. If this is selected, there are two options: add 'other' only to the last level, or add other to all levels
3. In the device, 'other' is shown as an option in the list from which the user makes a selection
4. If the user selects 'other', a free text field is displayed, in which the text can be typed
5. In the dashboard, when a user exports the data, there is an option: 'indicate other', which would mark an answer that was filled in as other options, for example by prefixing it: "other: Afridev III".

**Comment by janagombitova** [comment]
DRAFT

Based on the discussion from Sep 30 and Dagmar's use case we have decided to enable 'other' only on the last level of the cascade.
- When creating a cascade the user can enable 'Other on the last level' 
- On the device 'other' will only appear in the app once the user reaches to the last level of the cascade  
- If the user selects 'other', a free text field is displayed, in which the text can be typed
- When the user exports the data, 
   - each cascade will consist of two columns: one holding the path (separated with pipes and the last level will hold the typed in text), the second column indicating 'other'

**Comment by janagombitova** [comment]
As this issue needs to go through a full Discovery process first, before we have small issues to add to this repository, I am recreating it here: https://github.com/akvo/akvo-product-design/issues/175

**Comment by janagombitova** [comment]
As this issue was moved to the product design repo that we are now closing as we do not use it anyone, I am reopening this issue so we consider its validity again.
