### ISSUE TITLE
Using surveyId for manual survey transfer should download all forms

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1146]
At the moment, manual survey transfer only works for the form id. When the surveyId is used, nothing happens. This is confusing, as the Ids look similar, and we have seen some occasions where people use the surveyId instead of the formId to download forms.

Proposed solution: when a user uses the surveyId in the device for manual download, all forms inside that survey should be downloaded.

**Comment by joycarpediem** [comment]
@mtwestra , since we do not display surveyID anymore , is this issue still relevant ?

**Comment by joycarpediem** [comment]
since we do not display surveyID anymore, closing the issue
