### ISSUE TITLE
Changing 'download app' on dashboard from old /app to new /app2

### ISSUE THREAD

**Issue by JosjeS** [akvo/akvo-flow#1149]
In the admin from the dashboard on the footer you have the link 'download app', this directs you to the old app (/app). I think this should direct to the new app (/app2) especially for new instances as /app just gives an error as the old app is not created for these instances.

**Comment by JosjeS** [comment]
Hi All, 

What is the status on this?

**Comment by rumca** [comment]
@ichinaski do we just have to update [this](https://github.com/akvo/akvo-flow/blob/develop/GAE/src/org/waterforpeople/mapping/app/web/ApkRedirectServlet.java)?

**Comment by ichinaski** [comment]
The latter change is the most sensible one to me. However, not all instances can simply replace that hyperlink, as some partners have not upgraded the app yet.

CC/ @mtwestra

**Comment by mtwestra** [comment]
@ini, we can link it to app2. Cardno don't use this way to get at the app as far as I know.

**Comment by JosjeS** [comment]
Hi All, what is the status on this? 
Think it would be a good change to make because at the moment clicking on 'download app' gives you the old app if that was made for the dashboard and an error if there is only a new app.

**Comment by iperdomo** [comment]
## Test plan

* Use the link "Download App" in the bottom of the dashboard, you should get the version 2 series of the `.apk`

**Comment by rumca** [comment]
the above test case passes as described :+1:
