### ISSUE TITLE
Error when revoking a user's API Key

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1156]
I don't think this is a new regression - but I've only just noticed it. 

When you try to revoke an API key which has already been generated for a user, the following exception is occurring:

![screen shot 2015-02-18 at 11 15 27](https://cloud.githubusercontent.com/assets/3003031/6251241/b6cc5306-b78a-11e4-9629-95548a1dc776.png)

**Comment by jonase** [comment]
## Test Plan

* Revoke an existing API key for a user. It should work.

**Comment by rumca** [comment]
tested and works fine on release/1.8.3
