### ISSUE TITLE
Disallow more than one user account with same email (including superadmin users)

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1157]
It's currently possible to create more than one user account with the same email address:

![screen shot 2015-02-18 at 16 30 28](https://cloud.githubusercontent.com/assets/3003031/6251375/8dea036a-b78b-11e4-80d8-283d972146c0.png)

I think this has occurred because one of my accounts is a superadmin account which is not visible in the dashboard. Therefore when I added the second one through the users tab there wasn't a uniqueness check performed? Perhaps we should address this as it could potentially lead to some issues with permissioning. Any permissions I set up on the second of my accounts (the only one visible in the dashboard) do not apply at all since my superadmin account is the one used instead.

**Comment by janagombitova** [comment]
This issue will need some UI input to give the information back to the user about the duplicated email. I am pushing it back to the general backlog for now as it is not a pressing change

**Comment by janagombitova** [comment]
Issue duplicated here. Will be tackled in the issue mentioned https://github.com/akvo/akvo-flow/issues/1944
