### ISSUE TITLE
Permissions behaviour when more than one role/permission assigned to the same path

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1161]
@muloem @jonase I noticed something strange whilst testing the new data cleaning permission (don't think this is related to that particularly feature though - it's probably been an issue for a while but we just haven't encountered it before).

If I assign more than one role or permission set to the same path, then we currently do not merge these together and instead one of them is ignored. For example when I have the two roles at the bottom of this list assigned against the same path:

![screen shot 2015-02-19 at 12 16 29](https://cloud.githubusercontent.com/assets/3003031/6267458/234eaad6-b83c-11e4-8fec-7c7ad621d9a9.png)

(Administrator1 has every permission bar Data Cleaning, Data Cleaner has Data Cleaning, View Folders, View Forms). Then when I log in and view the current users permissions I see the following:

![screen shot 2015-02-19 at 12 16 46](https://cloud.githubusercontent.com/assets/3003031/6267503/92e4079c-b83c-11e4-998e-51841f515408.png)

The Data Cleaning permission is therefore not present. Whenever I remove the Administrator1 permission, and re log back in then I can see the Data Cleaning one - I'm not sure what is going on, perhaps we need to add something to merge permission sets if there is more than one for a specific path?

**Comment by muloem** [comment]
#### Test Plan

1. For a given user define assign multiple roles to the same folder

2. Verify that the user is able to perform all the permissions associated with the role

**Comment by rumca** [comment]
Permissions are now merging correctly :+1:
