### ISSUE TITLE
Hide Survey ID from dashboard UI

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow#1166]
# Overview 

As we've seen over the last weeks, users often mistakenly enter the **survey id** in the app, when the **form id** is the only valid ID we support for the moment. This results in a *Form not found* warning, and subsequently in a support request, etc.

Since the **survey id** is not used the dashboard user workflow at all, a quick workaround is to simply conceal this attribute from the user.

**Comment by jonase** [comment]
@loicsans I removed the surveyId from the UI. We should either show another piece of information instead or the CSS needs tweaking.

**Comment by jonase** [comment]
## Test Plan

* Open an existing survey
* The survey id should not be visible

**Comment by rumca** [comment]
tested and works as expected on release/1.8.3
