### ISSUE TITLE
Add confirmation to delete button cascade resource

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1170]
When a user clicks the delete button on a cascade resource, there is no confirmation button. this should be added.

**Comment by mtwestra** [comment]
Test plan
1) create a new cascade resource or select an existing one
2) click on the delete button
3) a confirmation popup should be shown

**Comment by mtwestra** [comment]
Translations still need to be added. This should happen after all issues merged to develop, to avoid overwriting transifex.

**Comment by rumca** [comment]
above test plan passes as described with release/1.8.4
