### ISSUE TITLE
Adding a help tooltip in a Group/Section in the AkvoFLOW dashboard

### ISSUE THREAD

**Issue by andrewmolo** [akvo/akvo-flow#1181]
At the moment, tooltips are implemented in questions only, however in some questionnaires, a specific rule or request must be applied while answering  questions in a particular section/group.

**Comment by janagombitova** [comment]
@andrewmolo Can you be more specific? Where are you missing the tooltip? To what word + action is it related to?

**Comment by andrewmolo** [comment]
@janagombitova Just like questions in a form, they have a tooltip where one can add additional information, there were cases where questions in a specific group need a tooltip too. e.g. "In this group of questions, kindly ask & observe." This eliminates possibility of copy pasting tooltip in each question in that group.

**Comment by janagombitova** [comment]
@andrewmolo I see. Thanks for the explanation. This can be added in with the overall re-design of survey creation. Relevant for https://github.com/akvo/akvo-product-design/issues/89

**Comment by janagombitova** [comment]
closing this issue for now.
