### ISSUE TITLE
Caching of requests causes malfunction with user roles and permissions and reading surveys

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1182]
A user is assigned a particular role coupled to a particular folder. But when they access the dashboard, the folders are not visible.  The opposite also happens i.e. when a user had access to certain folders and that access is revoked, the folders still appear on the dashboard.  This is likely related to a caching issue but it is not clear where the caching happens.

**Comment by mtwestra** [comment]
@muloem, How is this being solved now? Was the idea to use a nonce, or to use https?

**Comment by muloem** [comment]
@mtwestra via https. this should eliminate the caching.

**Comment by mtwestra** [comment]
@muloem, And is this already in place for all the API endpoints?

**Comment by muloem** [comment]
@mtwestra Yep.  Once we enable it for the instance, every request that is made will be via SSL.  We should probably think of a way to make sure requests that are *not* https should be redirected to https.

**Comment by mtwestra** [comment]
@muloem, cc @janagombitova , we have found some more evidence of this.
Situation: user creates some forms and saves them, then deletes a form, and then reads the forms again.
Browser: Internet Explorer 11
Behaviour: the form is still visible, while on on other computers, the form is gone.
Observations: I used the developer tools to check what is happening. There is a 'always refresh from server' button there, which is suspect. It is likely that Internet Explorer caches the pages agressively.

possible solution:
1) Use https, as described above
2) use a nonce for calls
3) use a no-cache setting, as described in http://superuser.com/questions/81182/how-to-force-internet-explorer-ie-to-really-reload-the-page

I think this is an urgent issue, as it really breaks the user experience. What is the timeline for the https fix? If that takes too long, we should do the nonce or no-cache settings, as those should be simpler to implement.

**Comment by muloem** [comment]
We will be enabling SSL for all instances in the next release so this should be resolved.

@rumca The tests should involve regression testing the user management functions with Internet Explorer if possible to verify that the caching is no longer an issue when creating users and setting and updating their permissions

**Comment by rumca** [comment]
@muloem I can't recreate the described behaviour on any browser - although I'd imagine it was an intermittent issue to begin with, so that's no guarantee it's 100% fixed. I'll close this issue for now and we can reopen if it's spotted again in the wild.
