### ISSUE TITLE
Review data processing task failures

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow#1185]
# Overview

As seen in a recent support thread, the data processing task servlet got interrupted after 10 minutes and a CancelledException was thrown. This type of exceptions do not result in a task reschedule, therefore the data was never processed again.

We need to solve this scenarios more gracefully, in order to make sure all failures end up in a task reschedule.

**Comment by muloem** [comment]
### Test Plan

#### Test 1: No file present or file empty
1. Invoke the URL for the instance `http://[host]/processor/non-existent-file.zip`

2. Check the logs to see that the error message reflects an empty or non-existent file

#### Test 2: Unable to reach file

#### Test 3: Corrupted Zip file

**Comment by rumca** [comment]
Test 1 test plan passes as described :+1:
