### ISSUE TITLE
Disabeling creation of surveys at the first level of the survey tab

### ISSUE THREAD

**Issue by JosjeS** [akvo/akvo-flow#1190]
Hi All, 

At the moment when you are on the survey tab you can choose to create a folder or a survey. 

I think it would be better to disable the option of creating a survey. So you always need to create a folder first before being able to create a survey.
In this way you make sure that all the surveys are in a folder. This makes the dashboard look cleaner and easier to understand.
As at the moment first the folders are listed and then the surveys, which can make it difficult to find the correct survey. 

Best,
Josje

**Comment by mtwestra** [comment]
@loicsans the line with the button is here:
https://github.com/akvo/akvo-flow/blob/feature/1190-survey-in-folder/Dashboard/app/js/templates/navSurveys/nav-surveys-main.handlebars#L46

**Comment by mtwestra** [comment]
Test plan:
1) go to the root folder
2) the 'create survey' button should be greyed out
3) when hoovering over the button, a tooltip should be displayed explaining that a survey can only be created inside a folder
4) go inside a folder
5) the button should not be greyed out, and not show a tooltip when hoovered over.

**Comment by rumca** [comment]
Test plan passes with release/1.8.4
