### ISSUE TITLE
Implement instance-configuration code request to FLOW services

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow#1191]
# Overview

According to https://github.com/akvo/akvo-flow-services/issues/89, we'll use GAE to handle the last leg in the code generation process, namely the authentication of the request.

This service will receive incoming requests from dashboard (logged-in) users, and will in turn use the instance API key to issue a new, authenticated request to FLOW services. The auth mechanism will be the same one described [here](https://github.com/akvo/akvo-flow/wiki/Akvo-FLOW-API#authentication).

Once GAE receives the dashboard initial HTTP request, the servlet will immediately respond to that request, being the last part of this process an asynchronous operation. Upon code generation, FLOW services will in turn send a (secured-transmission) email to the user, with the generated code.

**Comment by mtwestra** [comment]
@ichinaski is this still relevant?

**Comment by ichinaski** [comment]
@mtwestra sorry I missed your comment. No, this is not relevant anymore, as the code generation request will be directly issued to flow-services. Closing this issue for now.
