### ISSUE TITLE
monitoring tab doesn't show data

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1193]
Instance: http://akvoflowsandbox.appspot.com/admin/
survey group: 35 KOTA MALANG
survey: Malang Verif Tahap 2

In the inspect tab, this forms shows data.
However, If I select this survey in the monitoring tab, I get no results.

**Comment by muloem** [comment]
@mtwestra can you reproduce this issue on a live production server?

**Comment by janagombitova** [comment]
test data issue
