### ISSUE TITLE
Enable `All Folders` shortcut for a normal user

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1197]
At the moment only a user designated as a `SuperAdmin` will have the short cut `All Folders` in the list of folders that couple a role to a folder.  However, for those organisations that do not require fine grained use of roles and permissions assignments, enabling this shortcut will save a lot of work for the user responsible for assigning user permissions.

**Comment by jonase** [comment]
## Test plan

* Create three users where
  * **adminuser1** has admin rights but is not a superUser (so they can see the users tab) and has some permission set to "All folders and surveys"
  * **adminuser2** has admin rights but is not a superUser and does not have any permission set to "All folders and surveys"
  * **user3** is an ordinary user
* Login as **adminuser1** and edit the user roles and permissions for **user3**
  * Check that you can select "All folders and surveys" in the "Select a folder or survey" dropdown
* Login as **adminuser2** and edit the user roles and permissions for **user3**
  * Check that you can **not** select "All folders and surveys" in the "Select a folder or survey" dropdown

**Comment by rumca** [comment]
The above test plan passes with release/1.8.4
