### ISSUE TITLE
Displaying Identifier and Display Name for non-monitoring surveys

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#1204]
Issue:
A user can configure questions to "Use as Data Point Name" for both monitoring and non-monitoring surveys .
In the RAW data report these fields are exported only for monitoring surveys.
Same is the case for the 12 digit alpha-numeric identifier.

Expected:
Both Identifier and Display name is exported for all surveys

**Comment by joycarpediem** [comment]
The device identifier (set in the app) also needs to be exported as part of the RAW data report

**Comment by jonase** [comment]
## Test plan

When generating a report the following columns should be present for both monitoring and non-monitoring surveys:

<img width="322" alt="screen shot 2015-07-16 at 09 11 28" src="https://cloud.githubusercontent.com/assets/101023/8716550/185ff0f8-2b9b-11e5-9ece-5ef34518ead6.png">

**Comment by muloem** [comment]
@jonase I guess we should include the cases you just handled in test plan as well, i.e. the import of new + old reports

**Comment by rumca** [comment]
Test plan passes as described :+1:
