### ISSUE TITLE
Manage Device Group Pop Not Showing Properly

### ISSUE THREAD

**Issue by andrewmolo** [akvo/akvo-flow#1210]
**Problem** 
After maximising the browser, when you click Manage Device Groups (Under Devices tab)  the pop up doesn't fit properly in the browser leading to poor user experience.

![screen shot 2015-03-26 at 11 48 19](https://cloud.githubusercontent.com/assets/1729842/6842982/39602186-d3af-11e4-9e95-c6c812b4285d.png)

**Expected**
The pop up to fit
 properly

**Proposed Solution**
Implement responsiveness in the manage devices pop up?

**Comment by muloem** [comment]
@loicsans can you point out to @rumca what to look out for?

**Comment by rumca** [comment]
@muloem I've seen this before, so can make sure it's fixed during testing for the release :+1:

**Comment by rumca** [comment]
guess we can close https://github.com/akvo/akvo-flow/issues/1042 with this fix also

**Comment by muloem** [comment]
Great. Infact you can probably already close it with a comment referring to this issue. :+1:

**Comment by rumca** [comment]
Pop-up now allows for scrolling when the viewport is not large enough to display everything.

@loicsans not sure if it's worth the effort but perhaps it could be good to provide some sort of visual indication that users can scroll when required (from the below screen shot it's not immediately apparent):

![screen shot 2015-07-02 at 10 30 40](https://cloud.githubusercontent.com/assets/3003031/8479209/1ddf6de2-20ce-11e5-9b15-58186bb9ca2b.png)
