### ISSUE TITLE
Show alphabetical order in dropdown surveys

### ISSUE THREAD

**Issue by Lissyvn** [akvo/akvo-flow#1212]
Show alphabetical order in dashboard at data tab > choose survey to display

![screen shot 2015-03-26 at 15 15 58](https://cloud.githubusercontent.com/assets/4972211/6848061/3e62f9b2-d3cb-11e4-836c-30a140380078.png)

**Comment by jonase** [comment]
## Test plan

Check that surveys are sorted alphabetically in hierarchical survey selection dropdowns

**Comment by rumca** [comment]
test plan passes as described
