### ISSUE TITLE
Truncate the display name if it is over 500 characters

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1213]
We have a number of device processing errors that are caused by having `surveyedLocaleDisplayName` larger than 500 characters.  This prevents the survey responses from being saved to the datastore. 

Proposed solution: Truncate the display names to 500 characters to enable storing them.

**Comment by muloem** [comment]
## Test Plan

1. Create a survey with a number of free text questions 

2. Assign the survey to a device and submit responses to these questions that are longer than 500 characters in length

3. Submit the survey

4. Check that the survey has been correctly processed without errors. and that the display name is shown truncated.

**Comment by rumca** [comment]
The above test plan passes as described :+1:
