### ISSUE TITLE
Add User Management permissions

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1216]
Related to the issue #1115.  The second phase of resolving this issue involved adding new permissions for user management.

* Create and Modify Users
* Delete Users

The _view users_ permission is implicit (but does not make sense by itself), i.e. if you are able to create, modify or delete you automatically have view rights.

**Comment by janagombitova** [comment]
#### Implementation proposal 

Splitting the current ‘Administrator - Create, Manage and Delete users’ into:
- if none of the following permissions are given then the entire Users tab is hidden from sight
* [ ] **View dashboard users, roles and permissions** 
    - only view only for Dashboard users list and Roles & Permissions list
    - no edit, create, delete action available in both sub-tabs
* [ ] **Manage roles and permissions** - create new, edit, delete
* [ ] **Manage users** - create new user, edit existing user, delete users, give users roles

**Comment by janagombitova** [comment]
Closing this issue and re-creating it in the Product design repository to go through full Opportunity-Discovery-Delivery phases and planning 

New issue: https://github.com/akvo/akvo-product-design/issues/172
