### ISSUE TITLE
Improvements to application build and deployments code

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1229]
* Cleanup unnecessary statements in the build scripts
* Remove files that are not required for system function from the deployment

**Comment by muloem** [comment]
@iperdomo @jonase @mtwestra @ichinaski 
There are some jars I am removing with this change so you will probably need to clean them out from your build path in eclipse otherwise you'll get some errors. I will post a list here.

**Comment by muloem** [comment]
For the time being this is the list.  I tried to remove the larger ones first. 

- war/WEB- INF/lib/gt- api- 2.6.5.jar
- war/WEB- INF/lib/gt- main- 2.6.5.jar
- war/WEB- INF/lib/gt- metadata- 2.6.5.jar
- war/WEB- INF/lib/xalan- 2.7.1.jar
- war/WEB- INF/lib/xerces.jar
- war/commons- logging- 1.1.1.jar
- war/gt- main- 2.6.5.jar
- war/gt- referencing- 2.6.5.jar
- war/xbean.jar

**Comment by rumca** [comment]
everything still seems to build and deploy correctly with release/1.8.5 so closing this for now
