### ISSUE TITLE
Export cascade resource codes in RAW data report

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#1230]
While creating a cascade you can define codes for individuals values.
However when this cascade in used in a form and you export the RAW data report for that form, the cascade codes are not displayed.
Ex: http://services.akvoflow.org/report/maxfoundation.akvoflow.org/ac73e6bb-de5c-46af-8d7f-f625f44e42c3/RAW_DATA-6081021.xlsx

**Comment by rumca** [comment]
closed via #1323
