### ISSUE TITLE
Publish button does not get enabled on changing translations

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#1231]
Steps:
Open a published form
Open for basics and then Manage translations
Change or add new translations.
Save translations.

Issue:
The Publish button on the form is not enabled.

**Comment by mtwestra** [comment]
Test plan:
1) create a survey and publish it
2) add some translations and save them
3) the survey should now be in 'unpublished' status again.

**Comment by rumca** [comment]
the above test plan passes as expected with release/1.8.5 :+1:
