### ISSUE TITLE
Allow overwrite cascade resource when new csv file is uploaded

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1233]
Consider the following sequence of events:
1)  a user creates a cascade resource by uploading a csv
2) the user uses this cascade in surveys
3) the user makes some corrections in the csv, and want to upload it

There is currently no way to do this, apart from deleting the cascade resource, creating a new one, and upload that.

Proposed solution:
Let users upload a csv file to replace an existing cascade.

**Comment by janagombitova** [comment]
Closing this issue for now as we have not received such a request from partners lately and I am not sure if it is still the case. We will reopen the issue once it is relevant
