### ISSUE TITLE
All request to "FLOW services" must contain application id parameter

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#1238]
The current way to identify an instance is via the s3bucket, e.g. `https://akvoflowsandbox.s3.amazonaws.com`. We want to identify the instance by _application id_, for that, all request to FLOW services must contain the instance application id.

**Comment by iperdomo** [comment]
## Test plan

* Using DevTools network panel, make sure that requests to FLOW services include `appId` parameter

* Report generation

![appid2](https://cloud.githubusercontent.com/assets/178474/7138140/a59db8b8-e2be-11e4-9d8d-21c0d065de7e.png)

* Bulk upload

![appid1](https://cloud.githubusercontent.com/assets/178474/7138146/b413e7a0-e2be-11e4-9691-71e782aa7596.png)

**Comment by rumca** [comment]
Tested the various elements of the dashboard which interact with flow services (including data cleaning and cascades) and `appId` seems to be present in all the requests :+1:
