### ISSUE TITLE
Date field for RAW data export is pre-populated

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#1248]
Steps:
Go to Data-->Inspect Data
Filter for some data based on From and To dates.
Now navigate to Reports-->Export reports

Issue:
The date fields for RAW data is pre-filled with the values entered in Inspect data

**Comment by jonase** [comment]
This issue is related to #1160

**Comment by rumca** [comment]
Issue no longer occurs :+1:
