### ISSUE TITLE
Data deletion enhancements

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow#1251]
@muloem Currently the backend does not correctly check for data deletion permission. If a user doesn't have the `DELETE_DATA` permission set they could still circumvent the permission system with a direct call to the rest api. The `delete` button is correctly handled (i.e., not visible when DELETE_DATA permission is not set)

See #1115

**Comment by muloem** [comment]
@jonase I made some tests making direct calls to the API for a normal user in one scenario with and another without permissions and it works as expected.

**Comment by joycarpediem** [comment]
@muloem , is this still an issue ?

**Comment by janagombitova** [comment]
Closing this issue based on @muloem comment above
