### ISSUE TITLE
Browser crashing/freezing when actions performed with slow connection

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1256]
@jonase @iperdomo @muloem @mtwestra not sure if there's an easy/elegant way to fix this or not.

After Tim reported some issues with freezing & crashing in core chat I've been trying to reliably reproduce them. I haven't been able to replicate the freezing scrolling that was initially experienced, but I have managed to crash the browser a few times. The below steps aren't 100% guaranteed, as it depends on the user being quicker than the request response time, but they can frequently result in the issue occurring:

* Navigate through a nested folder structure
* Click to get back to a higher level via the breadcrumb
* Click to create a new survey
* Whilst the `Saving` text is still displayed, click to edit the new survey
* Both Chrome and Firefox crash

* Navigate through a nested folder structure
* Click to get back to a higher level via the breadcrumb
* Click to add a new folder
* Whilst the `Saving` text is displayed, clicked to enter the new folder
* Both Chrome and Firefox crash

Essentially if a user is quick enough (or their connection slow enough) to try and perform some sort of navigation or editing action during a `Saving` request then the browser ends up crashing

**Comment by janagombitova** [comment]
Closing this issue for now - will need to re-investigate and break down into smaller issues
