### ISSUE TITLE
Copying a question does not set createdDateTime and lastUpdateDateTime

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow#1259]
To reproduce:

* Copy a question
* The `createdDateTime` and `lastUpdateDateTime` properties are missing (this can be checked in the datastore viewer)

Another symptom of the missing properties is that the EventLogger will fail with an `NPE`.

**Comment by jonase** [comment]
## Test plan

* Copy an existing question
* Check that the `createdDateTime` and `lastUpdateDateTime` properties are set correctly (this is probably easiest to check directly in the datastore)
* Check that the corresponding event is properly recorded in the EventQueue

**Comment by rumca** [comment]
The `createdDateTime` and `lastUpdateDateTime` properties are set correctly, not sure how to check the event is properly recorded - I don't see any errors though and the count is incremented so assuming it's OK :+1:
