### ISSUE TITLE
Save button is activated when clicking on `Show Advanced Settings`

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1266]
When looking at or setting the registration survey of a monitored survey, we click on the `Show` button next to *Survey Basics* and then `Show Advanced Settings` button.  When the latter button is clicked, `Save` button is activated.  This should **not** be the case.  Expected behaviour is to activate the `Save` button only if the value of the *registration form* is changed.

**Comment by joycarpediem** [comment]
Fixed Duplicate

**Comment by muloem** [comment]
@Joy so you verified that this was indeed fixed right?

**Comment by muloem** [comment]
### Test Plan

1. Create a new survey and enable monitoring 
2. Create at least two forms
3. Save and exit the survey
4. Reopen the survey and click on `Show Advanced Settings`
5. The `Save` button should not be activated at this point
6. Switch the selected registration form
7. The save button should be activated

**Comment by rumca** [comment]
test plan passes as described :+1:
