### ISSUE TITLE
The wrong form is shown as registration form

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1267]
Under the `Show Advanced Settings` for a monitored group, we are able to see a drop down list that should initially (i.e. before the drop down box is clicked) show the currently set registration form for a monitored group. However, the drop down instead shows the list of forms for a survey in alphabetical order and initially shows the first form (alphabetically ordered) in the list as the registration form.

**Steps to reproduce:**

1. Create a monitored survey

2. Create two new forms one named *B Form* and another named *C Form*.  Set *B Form* as the registration form for the group and save the changes.  Reload the dashboard and verify that *B Form* is still set as registration form.  

3.  Create a third form in the group *A Form* and save it.

4.  Reload the dashboard and now check on the registration form. *A Form* is now shown as the new registration form.

**Comment by muloem** [comment]
### Test Plan

1. Create a monitored survey with forms named *B Form*, and *C Form*  Set *B Form* as the registration survey

2. Save the changes

3. Add a new form named *A Form* and save changes.

4.  Check on the list of registration forms and verify that *B Form* is still the registration form

5.  Reload the dashboard and verify that *B Form* is still set as the registration form

**Comment by rumca** [comment]
The above test plan passes as described :+1: 

@muloem perhaps something to consider for a future release is changing it so that the registration form is the default selected form when entering a monitoring survey? At the moment I think the first form added when creating the survey is pre-selected.
