### ISSUE TITLE
Default language for survey is auto updated when not set to `English`

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1269]
Steps to reproduce:
1. Create a survey and edit basic information about the survey
2. Set the language to `Español` and save changes
3. Navigate away from the survey and then return to it and click on `Show` survey basics.  
4. The default language changes to `English` and the `Save` button is activated.

**Comment by janagombitova** [comment]
Related to: https://github.com/akvo/akvo-flow/issues/1571

**Comment by janagombitova** [comment]
Before we take a decision on how to deal with these smaller issues we need to understand what is the role of the default language and how users expect to use it. Therefore, I have moved it to the product design repository where we can look at it properly. https://github.com/akvo/akvo-product-design/issues/173

**Comment by muloem** [comment]
I am reopening this issue.  We have a user who created a survey and set the default language to Spanish and when they try to define English translations, the dashboard prevents them from doing so with an error that its not possible to create translations in the default language.  In addition to the fact that the default is somehow automatically converted to English.

![default-language-translation](https://user-images.githubusercontent.com/533336/71373802-b343da00-25b8-11ea-9461-afd87b09b84c.gif)
