### ISSUE TITLE
Use CartoDB for Dashboard maps

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow#1280]

**Comment by jonase** [comment]
# Test Plan

## Preparations

in order to enable cartodb integration we need the following properties in `appengine-web.xml` (for uat1):

    <property name="mapsProvider" value="cartodb"/>
    <property name="cartodbSqlApi" value="https://akvoflow-uat1.cartodb.akvotest.org/api/v2/sql”/>
    <property name="cartodbApiKey" value="...”/>
    <property name="cartodbHost" value="cartodb.akvotest.org”/>
    <property name="hereMapsAppId" value="...”/>
    <property name="hereMapsAppCode" value="...”/>

The `cartodbApiKey` can be found by logging in to [https://akvoflow-uat1.cartodb.akvotest.org/login](https://akvoflow-uat1.cartodb.akvotest.org/login)

We also need event logging enabled

    <property name="enableChangeEvents" value="true"/>
    <property name="eventNotification" value="https://unilog.test.akvo.org/event-notification"/>

* The unilog export script need to have been run in order to prepopulate the unilog (this is already done). 
* The cartodb consumer needs to be running in order to get continuous updates working correctly.

If these preparations are in order you should be able to see all data points on the map:

<img width="1186" alt="screen shot 2015-08-12 at 10 38 42" src="https://cloud.githubusercontent.com/assets/101023/9218808/6dcf6ac0-40de-11e5-9637-674e48ea578a.png">

Choosing a survey will show all data points for the selected survey:

<img width="691" alt="screen shot 2015-08-12 at 10 40 39" src="https://cloud.githubusercontent.com/assets/101023/9218831/a0274a56-40de-11e5-80ce-c7fe8d9577b3.png">

and choosing a form will filter by form:

<img width="556" alt="screen shot 2015-08-12 at 10 41 28" src="https://cloud.githubusercontent.com/assets/101023/9218844/b9dd770e-40de-11e5-82f5-0cdeac607ca0.png">

Clicking on a data point will show responses in the sidebar:

<img width="947" alt="screen shot 2015-08-12 at 10 43 13" src="https://cloud.githubusercontent.com/assets/101023/9218869/f838a406-40de-11e5-897a-742a69d800b8.png">

**Comment by rumca** [comment]
Two quick comments, is it possible to remove the point wrapping? Now that we've removed the map tile wrapping it looks a bit strange:

![screen shot 2015-08-12 at 12 23 41](https://cloud.githubusercontent.com/assets/3003031/9222884/3cfc5430-40ed-11e5-8e34-df25fce9e25a.png)

Also is it possible to re-centre the map or change the default zoom level to a slightly greater one? When the points for a survey are above are below the current level its not immediately apparent we need to move. Default:

![screen shot 2015-08-12 at 12 27 54](https://cloud.githubusercontent.com/assets/3003031/9222932/a428565e-40ed-11e5-8400-5f2a239b7ced.png)

Then after changing zoom:

![screen shot 2015-08-12 at 12 28 10](https://cloud.githubusercontent.com/assets/3003031/9222937/b3dac2c6-40ed-11e5-8943-6cc3501d3bd1.png)

The test data is in a random place - but could easily get the same behaviour for certain SE asia surveys also.

**Comment by rumca** [comment]
Test plan passes as described :+1:
