### ISSUE TITLE
Unify use of vocabulary throughout the dashboard and app

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1281]
- Create a question → question type → 2 different words used among the types of questions: “details” and ”settings”. Use Settings

- Data --> Monitoring --> The "Display Name" in the table should be "Data Point Name" (to keep a consistency in vocabulary). Same in the filter tabs.

**Comment by joycarpediem** [comment]
In the Inspect data tab, we have an ID column which displays the surveyInstance ID.
The same value is displayed in the column "Instance" in the RAW data spreadsheet.

It should be ID in both the ploces.

**Comment by janagombitova** [comment]
**To do:**

1. In: Surveys > Add a new question > Question type: **change** all to only 'Settings'   
   - Free text details > changed to 'Settings'
   - Number Settings > change to 'Settings'
  - applied on all question types 
  
![screen shot 2015-07-21 at 09 39 17](https://cloud.githubusercontent.com/assets/12456965/8795358/ccb3ba9a-2f8c-11e5-89e7-15c8e4a62d1f.png)
![screen shot 2015-07-21 at 09 39 40](https://cloud.githubusercontent.com/assets/12456965/8795360/cf67e5ea-2f8c-11e5-9e68-bd8cc6b9d3fa.png)

2. Change Display name to 'Data point name' 
   - In: Data > Monitoring > filter on Display name > **change** to Data point name in both the filter value and in the text box
   - In: Data > Monitoring > table of collected data > table header > **change** Display name to 
![screen shot 2015-07-21 at 09 54 04](https://cloud.githubusercontent.com/assets/12456965/8795675/29acf76e-2f8f-11e5-8072-8b05943cdc73.png)
Data point name

3. In: Reports > raw data report - only if it does not create issues with data upload
   - Display name **change** to Data point name
   - Instance **change** to Instance ID

**Comment by gabemart** [comment]
I have made the necessary code changes. I'm waiting for access to Transifex to submit the new strings for translation.

**Comment by gabemart** [comment]
I've uploaded the new file to transifex. Will create a PR when we have the new Spanish and French strings.

**Comment by gabemart** [comment]
### Test Plan

1) In Surveys > Add a new question > Edit, change the "Question type" and verify that for each question type, the text immediately below the question type input matches:

"Free Text" - "Settings:"
"Options" - "Settings:"
"Cascade" - No text
"Number" - "Settings:"
"Geolocation" - "Settings:"
"Photo" - "No additional settings for this type of question"
"Video" - "No additional settings for this type of question"
"Date" - "No additional settings for this type of question"
"Barcode" - "Settings:"
"Geographic shape" - "Settings:"

2) With language set to Spanish, in Surveys > Add a new question > Edit, with "TIPO DE PREGUNTA:" set to "Texto libre", verify that the text below the text immediately below the "TIPO DE PREGUNTA:" input matches "Configuración:"

3) With language set to French, in Surveys > Add a new question > Edit, with "TYPE DE QUESTION:" set to "Texte libre", verify that the text below the text immediately below the "TYPE DE QUESTION:" input matches "Options:"

4) In Data > Monitoring, verify that the filter input following "Identifier" is titled "Data point name", and has "Data point name" as the placeholder input. Further verify that this input is titled "NOMBRE DEL PUNTO DE DATOS" in Spanish and "NOM DE DONNÉE:" in French

**Comment by rumca** [comment]
Test plan passes as described :+1:
