### ISSUE TITLE
Multiple `SurveyedLocale` entities created for the same `surveyedLocaleIdentifier`

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1282]
During submission of survey responses, a new `SurveyedLocale` entity is created for every `surveyedLocaleIdentifier` that is present in the data files.  However, in cases where a device is offline during data gathering and then all data submitted in one big batch to the backend, multiple `SurveyedLocale` entities are created for the same `surveyedLocaleIdentifier`.  As a result we have multiple form responses that should be related to each other through a common `SurveyedLocale` but are not.

Proposed solutions:  For the existing data we will create a data script to correct the wrongly created surveyed locales.  We will also create a fix for the data processing to ensure this does not happen in future releases.

**Comment by ichinaski** [comment]
**Test plan:**
* Download a monitored group in the app
* Enable airplane mode in the device
* Create a bunch of datapoints, each of which containing several form instances (a reg. form plus a few regular forms)
* Disable airplane mode, and let all the data get synced into the dashboard.
* Ensure no duplicate datapoints (same identifier) are found in the dashboard

**Comment by rumca** [comment]
Test plan passes as described :tada:
