### ISSUE TITLE
Add stack trace to device file processing for old releases

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1288]
The cardno instance that has not yet been migrated to the 1.8.x dashboard still generates a lot of device file processing errors.  Cross checking the files indicates that the files have been correctly processed, however, we would like to add a stack trace to verify that the source of error is the same and is one that is negligible.

**Comment by ichinaski** [comment]
@muloem perhaps we can close this issue?

**Comment by muloem** [comment]
Yeah. Makes sense. We will probably migrate cardno soon anyway.


----- Original Message -----
