### ISSUE TITLE
Implement copying question group from one form to another or a full form from one survey to another

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1293]
In some cases, people have common sections in forms that they want to repeat. In those cases, it would be very beneficial to be able to copy a question group from one form to another.

**Comment by muloem** [comment]
@mtwestra In these cases we should think what to copy over and what not to copy over.  For example if we have one question A as a dependent question to question B which is in a group that is not being copied over as well, then we have a broken state. Would this motivation, i.e, having common questions to reuse, not fit more in the idea of a library of questions to select from to include in a survey?

**Comment by janagombitova** [comment]
I spoke with a few partners and colleagues about this request these last days and their primary motivation is that often the same questions (group of questions) are asked for a different project. But these are questions that they need to learn about a specific indicator or goal they track. Now they have to recreate these questions all the time. 

When it comes to dependencies the simplest solution would be: 
* if we allow copying a question across a form or different survey to NOT copy the dependency
* If we allow copying a question group, we copy the dependencies within the group, but any dependency outside of the group is not copied.
