### ISSUE TITLE
Layout of edit data points - screen is broken

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1294]
In the screen view the 'previous record' and the 'next record' buttons are next to each other and not on the opposite sides of the screen. Plus, the delete button is not aligned. 

![screen shot 2015-06-05 at 14 10 40](https://cloud.githubusercontent.com/assets/12456965/8005675/1074e980-0b8d-11e5-92b9-8573b579eb87.png)

**Comment by janagombitova** [comment]
@gabemart can you please take a look at this. It is a small fix, Loic already worked on it. Thanks

**Comment by gabemart** [comment]
@janagombitova I can't look at this until I get my FLOW dev environment set up. That should happen later this week. Is the end of the week soon enough to deal with this?

**Comment by rumca** [comment]
@gabemart we can probably close this issue as well once this is address https://github.com/akvo/akvo-flow/issues/809

**Comment by rumca** [comment]
`previous record`, `delete` button, and `next record` are now correctly aligned :+1: 

perhaps something for a future release - when we get to the last response the `next record` option is still available but doesn't do anything (same with the first response and `previous record`)
