### ISSUE TITLE
Fix geocells computation

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow#1295]
# Overview

For newly created surveyed locales the corresponding geocells are not being computed.
This is a regression introduced in 1.8.6

**Comment by ichinaski** [comment]
Since the latitude and longitude properties are already set in the SurveyedLocale, this conditional never holds true, therefore the `if` block is never entered https://github.com/akvo/akvo-flow/blob/release/1.8.7/GAE/src/com/gallatinsystems/surveyal/app/web/SurveyalRestServlet.java#L269-L270

The (quickest) solution is to check for geocells property status, rather than lat/lon comparisons, essentially computing the geocells for any locale that hasn't got any yet.

**Comment by ichinaski** [comment]
**Test plan:**
* Create new datapoints using the *datapoint location* flag in a geo question.
* Create new datapoints without using the *datapoint location* flag (yet having a geo question)
* Repeat previous step using 1.13.X app.

In all cases the resulting datapoints should contain the **geocells** property set (visible in the datastore viewer) and the points should be shown in the map.

**Comment by rumca** [comment]
The above test plan passes as described :+1: 

@ichinaski is there a functional difference between questions with the datapoint location flag and those without? I hadn't previously been checking this.

**Comment by ichinaski** [comment]
@rumca the main difference is that such a flag explicitly sets the location of the datapoint, whereas the lack thereof computes a response lookup, trying to get the value of the geoquestion (if any). I just wanted to make sure both scenarios were covered.

**Comment by rumca** [comment]
:+1:
