### ISSUE TITLE
`Next` button on Data > Monitoring tab does not function

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1299]
When clicking on the `Next` button on the `Data > Monitoring` tab, the only thing that happens is the page getting refreshed and the same results show up.

**Comment by muloem** [comment]
### Test Plan

1. Create a monitoring survey with a registration form and some sample questions 

2. Fill in over 20 responses (data points)

3. Check the monitoring tab on the dashboard. There should be a list of data points and clicking on the `Next` button should show the next items in the list

**Comment by rumca** [comment]
Test plan passes as described :+1:
