### ISSUE TITLE
Improve Error Feedback for data import

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1304]
When exporting or importing raw data reports, we sometimes encounter errors that are not reported clearly to the users and that eventually lead to support requests. e.g when uploading a raw report file to the wrong survey, the message returned is "Spreadsheet processed" leading the user to believe that the file has been correctly processed, which is not the case.  For these cases we need to give better feedback.
1. Uploading a raw report file against the wrong survey

**Comment by janagombitova** [comment]
We will handle error feedback for data exports here: https://github.com/akvo/akvo-flow/issues/2543 and then this issue can focus on **importing (uploading)** data via data cleaning

**Comment by janagombitova** [comment]
# Context 
 
Currently Salim downloads a Data cleaning export and then in the Data cleaning tab imports the ready sheet. He has to make sure he selects the folder > survey > form fist. Then he selects the right file and hits import. Flow checks first if the form is selects and if the file type is correct. Then Flow starts importing in the data what can take a few seconds but also 15 minutes depending on the size of the sheet.

<img width="1280" alt="screen shot 2018-06-04 at 08 37 36" src="https://user-images.githubusercontent.com/12456965/40901952-8b3c6c48-67d2-11e8-9ce3-804053cf61b1.png">

Currently all success and also all failures of the import are shown to Salim in the messages tab meaning he has to go to another page to learn he selected a wrong file (bad file type, that these was something wrong with the structure of the the sheet or that is actually worked. 

 # Goals 
How might we: 
- Ensure Salim and Petra know the workflow they need to follow. 
- Ensure Petra and Salim know when the import failed and why that may have happened 
- Create a consistent design for importing processes (bulk data import, data cleaning import) - keep in mind that the UI implementation are now linked using one style sheet 

@Kiarii can you share the designs you made a while ago and we could pick up this issue in the next weeks. Cheers

**Comment by Kiarii** [comment]
Here are the mockups for the new bulk upload workflow: https://invis.io/6ZGCNU3VSBJ. 

Error states for incompatible file types and unknown failure:
<img width="1017" alt="screen shot 2018-06-04 at 10 31 26" src="https://user-images.githubusercontent.com/12692444/40904139-7ed0cde0-67e2-11e8-9637-efd26ab4e823.png">

**Comment by janagombitova** [comment]
@Kiarii I meant the designs you had for **data cleaning import** not bulk upload. I remember you had some for cleaning too. But indeed the error logging should follow the same pattern.

**Comment by Kiarii** [comment]
Oops; here are the wireframes for the Clean data importing: https://invis.io/ZSF1QWAN3#/270245447_1-_Hit_Import
