### ISSUE TITLE
Arrange cascade nodes in alphabetical order

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1310]
When creating cascading resources (via `CSV` import or dashboard), we currently order the cascades on the dashboard by the internal `ID` assigned to the entities, whereas users are able to arrange the cascade nodes alphabetically in the mobile app.  As an improvement to user experience, we will implement functionality to sort the cascade nodes alphabetically.

**Comment by Geerts** [comment]
Requested by SNV.

**Comment by janagombitova** [comment]
Recreated the issue here https://github.com/akvo/akvo-product-design/issues/181 to go through the full discovery process and understand the problem better
