### ISSUE TITLE
Automated newsletter subscription 

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1311]
When creating users, we should automatically subscribe them to AkvoFLOW newsletter via the mail chimp API.

**Comment by janagombitova** [comment]
Connected to https://github.com/akvo/akvo-product-design/issues/49

**Comment by janagombitova** [comment]
@jonase Can you look into this issue for the next 1.9.5 release so we can start sending out the newsletter to all our users without updating this list manually? There is no UI change needed. The idea is that once a new users account is created (an email address that is not already in the mailing list), it is automatically added to the mailing list.

**Comment by janagombitova** [comment]
We will first look at the opportunity and do some discovery work in the Product design repository before creating an issue here. Closing this issue
