### ISSUE TITLE
Cardno: Find button not visible in the inspect data tab

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#1314]
Steps:
Login to indiiwatsan2.akvoflow.org and go to Data-->Inspect Data

Issue:
The FIND button is chopped off and is partially visible. This makes it particularly difficult to use on tablets
![screen shot 2015-06-22 at 5 37 15 pm](https://cloud.githubusercontent.com/assets/4419787/8281411/60d5ca22-1905-11e5-9c69-b7808983a46b.png)

**Comment by joycarpediem** [comment]
Test plan:
<h1>1.</h1> 
Step:
Open inspect data tab in Chrome and firefox.

Expected:
The find button should be clearly visible

<h2>2</h2>
Steps
Open developer tool and try it for some tablets

Expected:
The FIND button should not get cropped

**Comment by muloem** [comment]
This branch is now deployed to the card no instance so we can close this.
