### ISSUE TITLE
Restrict 'Use as data point name' and 'Use as data point location' only for registration forms in monitored surveys

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1319]
Currently the user can create a data point name based on a property in any form. However, when monitoring is enabled, with the registration form you fill in the general information that identifies the data point for later monitoring. So, the data point name should also be created from this form only.

**Comment by joycarpediem** [comment]
We need to make sure that as part of the this fix we do not strip the display name functionality from stand alone non - monitoring survey forms

**Comment by janagombitova** [comment]
As well as for data point location

**Comment by iperdomo** [comment]
@janagombitova @joycarpediem Not sure if is relevant, but the _Use as display name_  for non monitoring surveys was requested in issue #735 Initially it was not possible. The changeset: https://github.com/akvo/akvo-flow/commit/24cf4db8bbf5611cb6ca9e944155a9fcb6689592

**Comment by janagombitova** [comment]
@iperdomo For surveys which do not have Monitoring enables, this issue will not change anything. The user will be able to create a data point/display name (as Joy mentioned above)

In surveys which have Monitoring enabled, the user creates the data point via the registration survey, thus for me it makes sense that the display name/data point name and the data point location are created based on an answer to a question only from the registration form and not from the other forms. So we restrict the ability to create a data point name only in the registration form and not the other forms in a survey with enabled monitoring.

What we need to tackle is: That when creating forms in a survey with enables monitoring, first the user creates the forms, defines the question (selects which question will be used for data point name) and then decides which one is the registration form.

**Comment by janagombitova** [comment]
@iperdomo For surveys which do not have Monitoring enables, this issue will not change anything. The user will be able to create a data point/display name (as Joy mentioned above)

In surveys which have Monitoring enabled, the user creates the data point via the registration survey, thus for me it makes sense that the display name/data point name and the data point location are created based on an answer to a question only from the registration form and not from the other forms. So we restrict the ability to create a data point name only in the registration form and not the other forms in a survey with enabled monitoring.

What we need to tackle is: 

That when creating forms in a survey with enables monitoring, first the user creates the forms, defines the questions (selects which question will be used for data point name) and then decides which one is the registration form. What can happen is that the user assigned the data point name to a question in a non-registration form.  

Suggestions: 
1. Always the first form is the registration form - as a default setting
2. After creating a form, FLOW asks if this is the registration form or not, and then the user can start adding questions
3. etc.

**Comment by Kiarii** [comment]
the suggestion above might serve the purpose - i.e. by default, every survey's first form is the data point name/registration and whatever questions correspond to this form can be added freely as needed. other forms can be added below the data point registration form irrespective of whether the survey is monitoring or not

**Comment by janagombitova** [comment]
Reopening to consider under Cisco
