### ISSUE TITLE
View forms permission allows to edit it

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#1322]
Steps:
1. Create a role that only has permission to view forms.
2. Assign a user with this role for a survey

Issue:
The user can still edit the forms.

http://flowhelp.akvo.org/discussions/problems/5542-user-tab-issue_fxb-suraksha

**Comment by muloem** [comment]
Closing this one.  An issue already exists #1124

**Comment by akvotender** [comment]
Assigned to [Tender discussion #6133](http://flowhelp.akvo.org/help/discussions/problems/6133-new-permission-setting-view-only-role-needed-requested-by-lars).
