### ISSUE TITLE
Validate surveys for correctness when publishing

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1324]
~~At the moment its possible to create and publish a form with no questions and a single question group.  We should cross check that there is at least one question before a form can be published.~~

I have updated the title of this issue to a more generic validation of surveys before publishing.  There are a number of issues that need to be checked before publishing a survey to ensure that it is in working order to prevent problems during data collection.  Among the things to validate:
* [ ] Ensure that there are questions in the survey
* [x] Ensure that the dependencies are correctly setup and exist
* [x] Ensure that option questions have options defined (#362)

**Comment by janagombitova** [comment]
While doing the validation we should also check that the form name is set by the user before enabling publishing

**Comment by muloem** [comment]
Also bumped this up to Priority 1 as it is creating issues with data collection.

**Comment by janagombitova** [comment]
https://github.com/akvo/akvo-flow/issues/1520

**Comment by janagombitova** [comment]
Closing this issue as we have already implemented validation on question level when saving. The missing validations are defined in their separate issues.
