### ISSUE TITLE
Validation for cascade import

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1326]
When uploading a cascading `CSV` file, one of the UI elements to select is a checkbox specifying whether or not the file contains codes along side the cascade elements.  However, it seems this checkbox is not very clearly visible to the user and when not selected results in failed validation of the cascade file.  We need to redesign the UI part to make all elements visible

<img width="862" alt="screen shot 2015-07-03 at 13 33 10" src="https://cloud.githubusercontent.com/assets/533336/8498525/2958b308-2188-11e5-8636-32f0b2802847.png">

**Comment by janagombitova** [comment]
In addition to this issue - if a user upload anything but a csv file the 'Import cascade file' is enables and the progress bar goes to 100%. If we can add a validation already here saying that the file format is incorrect + not enabling the 'Import' button it will also get rid of confusion

**Comment by muloem** [comment]
<img width="748" alt="screen shot 2017-11-08 at 06 44 38" src="https://user-images.githubusercontent.com/533336/32533325-5b214766-c450-11e7-8b3c-3778747decb0.png">

@loicsans The alignment is resolved, however, the convention for checkboxes is to have them to the left right?
