### ISSUE TITLE
FLOW-Caddisfly: APK download link

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow#1327]
# Overview

Although the ultimate goal is to host both apps in Play Store, the existing S3-based solution can be a first step forward. The idea would be to display a *Download Caddisfly app* link in the FLOW dashboard, similar to the FLOW download link we show now.

Since the Caddisfly app doesn't chance across instances, the APK deployment script doesn't need to be modified at all, and the APK link can be just hard-coded in the dashboard, or configured through a flag in `appengine-web.xml`. Only instances with this property (or **external_sources** flag in case we don't take the extra flag route) will display such a link to the Caddisfly app.

**Comment by janagombitova** [comment]
As we are moving towards a better integration with Caddisfly test and the Caddisfly team is working on adding the app on Play Store, we can close this issue.
