### ISSUE TITLE
SurveyedLocale deletion bug

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow#1329]
# Overview

SurveyedLocale deletion happens implicitly while deleting SurveyInstances: If the removal of a SurveyInstance leaves no more instances associated with the locale, the locale gets deleted.

Or not.

Depending on the `geoCells` presence in the SurveyedLocale, the deletion step can be fully skipped: https://github.com/akvo/akvo-flow/blob/develop/GAE/src/com/gallatinsystems/gis/map/MapUtils.java#L68-L70

Since the deletion call happens later in that function, **SurveyedLocales without location information will never be deleted**.

This bug is the root cause of the issue described at https://github.com/akvo/akvo-flow-mobile/issues/310#issuecomment-119023692

**Comment by muloem** [comment]
@ichinaski one question.  I know it happened for old data, but isn't it a bug for a `SurveyedLocale` *not* to have `geocells` set?

**Comment by ichinaski** [comment]
Not necessarily. What if a survey doesn't contain any `GeoQuestion`? This is in fact the case that has triggered the issue

**Comment by muloem** [comment]
This is also true. On the other hand we have many parts of our code really pegging a `SurveyedLocale` to the existence of a geo question or geo information.  So if indeed we accept that a `SurveyedLocale` is not necessarily pegged to a place then we may have to do a thorough review of how its used all over.

**Comment by ichinaski** [comment]
**Test plan:**
* Create a survey without a `GeoQuestion`.
* Add a datapoint
* Check the *Data > Monitoring* tab, and ensure both the datapoint and survey instance are displayed.
* Delete the datapoint:
    * Re-fetching all the datapoints for this survey should not show the datapoint anymore.

**Comment by rumca** [comment]
The above test plan passes as described :+1:
