### ISSUE TITLE
Rethink datapoint name association

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow#1333]
# Overview

The JSON-encoded response format defined [recently](https://github.com/akvo/akvo-product-design/blob/master/FLOW/arch/ADR-004.md) will hinder datapoint name generation, since every value will need to look up the underlying, specific format, in order to fetch the name token.

As this feature as not been scaling well (multiple support threads related to it, need for an extra test harness to update names, etc), we should consider simplifying this property.

A possible solution is to have a manually set-up name, introduced initially by the enumerator upon datapoint creation, which can be later on modified if required in the data cleaning process.

**Comment by akvotender** [comment]
Assigned to [Tender discussion #5538](http://flowhelp.akvo.org/help/discussions/problems/5538-unnamed-data-point-in-app-after-rerunning-data-name-script).

**Comment by janagombitova** [comment]
adding this issue to the opportunity backlog and closing it for now
