### ISSUE TITLE
Email subject and file name improvements

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1334]
Currently when the user exports multiple reports at the same time, the way we send the emails does not make it easy for the user to see and distinguish which email is for which report. The current email looks like:

**Sender name:** noreply 
**Subject:** Your report is ready to download
**Email text:**
Greetings,

You can download your report from < link > 

Regards,
Akvo FLOW

**File name:** RAW_DATA_FORMID.xlsx
## Suggested change:

**Sender name:** akvoflow 
**Subject:** Report - 'form name' - 'form ID' 
**Email text:**

Greetings,

We have generated your report.

Survey: 'full survey name' 
Form: 'full form name'

You can download it from < link > 

Regards,
Akvo FLOW

**File name:** RAW_DATA_FORM_NAME_FORM_ID.xlsx
**Sheet name:** Raw_data_FormID

child #2505

**Comment by jonase** [comment]
@janagombitova @muloem Giving this a second thought I wonder if we should leave the filename as it is. There might be subtle issues with turning a form name into a valid file name. Especially if we want to support languages with no ASCII characters at all.

**Comment by janagombitova** [comment]
In a way, I think changing the file name is not the highest priority regarding the problem we are solving. We added it more as an extra cherry on the top. So if @muloem agrees with you @jonase, then keeping the file name as it is is fine with me.

**Comment by janagombitova** [comment]
@Kiarii @muloem @stellanl Here is an old issue on improving the email copy for the exports. We can use it to discuss the small changes to make the email copy more informative and friendly. 

What would you suggest? I will run this question by the MarComms team as well 

What we must change is the signature: from Akvo FLOW --> to Akvo Flow

**Comment by janagombitova** [comment]
# Current email copy

Sender name: noreply@akvoflow.org
Subject: Your report is ready to download
Email text:

Greetings,

You can download your report from < link >

Regards,
Akvo FLOW

File name: [EXPORT_TYPE]-[formID].xlsx

# Change 

As part of securing data on Flow we decided to stop sending data exports (of any kind) via emails but to have them downloadable directly in Flow. https://github.com/akvo/akvo-flow/issues/2505 We decided to keep the emails as a form of notification to let Salim know his export is ready and accessible in their Flow instance. 

With this change the email copy needs to be changed. It will no longer hold the url to download the export. What the new copy should be we have to decide on. 

Sender name: noreply@akvoflow.org
Subject: Your report is ready to download
Email text:

**to be defined**

**Comment by janagombitova** [comment]
# Context
We have made the decision to stop sending exports via emails, but create a way how users can download them via the UI. See the comment above, or this issue for more details: https://github.com/akvo/akvo-flow/issues/2505

# User research
During the user research done we learned that for some users the emails will be redundant, but for others who work with large data sets and while waiting for the file to generate they might go and do something else outside of Flow, they will find the email helpful to stay on top of the status of things.

As the feedback was not conclusive we decided we will for the next 6 months (till 1st October) send users an email once their export generation is completed on the instance as a notification outside of Flow. In October we will review this implementation and decide if we will keep or kill it. 

# Changes 
Sender name: noreply@akvoflow.org
Subject: Your export is ready
Email text:

Hi, 

Your export is ready to download. Go to your Akvo Flow instance and download your export from  the Exports page. 

If you didn't generate an, please contact us at flowsupport@akvo.org

All the best,
Akvo Flow

## To do 
- Finalise the email text
- Is branding possible?

**Comment by janagombitova** [comment]
# Changes
Two possible option depending on how personalised we can make the email 

## Simple - general option 
Sender name: noreply@akvoflow.org
Subject: Your export is ready
Email text:

Hi,

Your Flow export is ready to download. Go to your Akvo Flow instance and download your export from the Exports page.

If you didn't request an export on Akvo Flow, please contact us at flowsupport@akvo.org

All the best,
Akvo Flow

**Comment by janagombitova** [comment]
![screen shot 2018-07-04 at 11 07 16](https://user-images.githubusercontent.com/12456965/42267835-6247faea-7f7a-11e8-90b2-24c43e0b3bf1.png)

Being nitty gritty about this one, but please make the change to reflect the copy in the comment above to the subject and email text.
