### ISSUE TITLE
UX Design and CSS styling of data tab search text

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1346]
Under the `Data > Inspect Data` tab, we currently return a message *No results found*. The styling is directly in the template and needs to move to CSS.

<img width="1279" alt="no-results-found-text-message" src="https://cloud.githubusercontent.com/assets/533336/8778397/f95655e2-2efd-11e5-847d-85df89c2497e.png">

@Kiarii @gabemart @loicsans

**Comment by muloem** [comment]
@gabemart please add a test plan here indicating what to look out for.

**Comment by gabemart** [comment]
### Test Plan

1) Navigate to the Data > Inspect Data tab

2) Hit "Find"

3) Verify the "No Results" text is red and center-aligned

4) Load a survey that has some data results

5) Hit "Find"

6) Verify that text in the "Form" and "Submitter" columns is left-aligned

**Comment by rumca** [comment]
test plan passes as described :+1:
