### ISSUE TITLE
Geoshapes on dashboard - map visualization per data point

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1356]
### Overview

Currently the geographic shape feature, geoshape, is fully operational on the data collection side of FLOW, on the app. This allows users to define within a survey form a geoshape question type and on the device they create the shape in the field. However, attention is needed to visualize and automate this process on the FLOW dashboard in order to finalize this feature.

We will approach this feature in multiple phases. Our main goals are: 
   1. Visualization on the map
   2. Visualization in the Inspect data tab
   3. Exporting geoshapes
   4. Minor UX fixes and improvements on the app

As part of visualising geoshapes on the FLOW maps, this implementation will be the first step toward the later complete production. In this implementation we will work on **Visualizing geoshapes as a layer on the map**. 

#### This implementation will include
   1. Showing the geoshape as a layer on the map
      - user selects a specific data point 
      - by default the geoshape is rendered as a layer on the map
      - in the side bar a preview of the questions and answers are generated 
   2. Showing computed values related to the geoshape
      - computed values will stand as an answer to the geoshape question:
         - Total size of the geoshape:
         - Length of the geoshape:
         - Total number of points:
   3. Once the user clicks onto a second geoshape, the first geoshape layer automatically disappears from the map and the new (second) layer of geoshape is rendered. 

**Needs further attention**
   1. The size of the data point "circle" can be larger than the shape itself. This happens because the data point is out of proportion in regards to the map. If the geoshape is small and located behind the data point circle, then it may become hidden and impossible for the user to see without having to zoom in multiple times. 

   2. How will we address the situation, if a form holds more than one geoshape question? All geoshapes will appear on the map by default. We should enable the possibility to 'hide' and 'show' a geoshape. UI and UX work needed.

**Comment by janagombitova** [comment]
@jonase @kymni Here is what I have so far.

**Comment by janagombitova** [comment]
![map geo-shapes](https://cloud.githubusercontent.com/assets/12456965/9034511/83acbf42-39d0-11e5-88a0-f77c103e9374.png)

**Comment by janagombitova** [comment]
@kymni @jonase I asked Loic and Kiarii to look into the 'project on main map' button. Kiarii proposed a few solutions, which would be great if you can implement for the release. 

1. Change the way we project questions and answers in the side menu, from side by side to linear. This will also give us more space for the smaller map. 
2. Show on map/Hide from map button and location

![screen shot 2015-09-29 at 15 06 43](https://cloud.githubusercontent.com/assets/12456965/10164798/e5225cf6-66bb-11e5-9ddd-449e6c6b2413.png)

Thank you

**Comment by janagombitova** [comment]
@jonase @kymni One detail that we need to add is, when we render to computed values (Number of points:, Total size:, Length:) there is now unit shown. We need to add the unit to make it clear what the size and length is.

**Comment by jonase** [comment]
## TestPlan

@jonase TODO

**Comment by rumca** [comment]
@jonase some comments:

* Not sure if it's just my connection, but the call to `survey_groups` when you click on the map tab seems to be really really long from a usability perspective. I know it's the same as the initial loading on the surveys tab but it's consistently taking ~9 seconds to populate the drop down every time you visit the maps tab with no indication that it's actually loading anything - which I think will lead to confusion. I've also experienced the call timing out once or twice, so the drop down never appears.

* Datapoints are intermittently not being populated on the map. I've crosschecked and they're all there on the mapbox view but not the cartodb one:

![screen shot 2015-11-02 at 00 30 26](https://cloud.githubusercontent.com/assets/3003031/10872471/84406b86-80fa-11e5-91ff-4371684e58a9.png)

There should be a point in Colombia on the cartodb one, visible on the mapbox version below.

![screen shot 2015-11-02 at 00 09 44](https://cloud.githubusercontent.com/assets/3003031/10872473/91d967b6-80fa-11e5-9e16-7d34730f3889.png)

For specific examples of this check UAT1 survey `1.9.2 UAT Folder > 1.9.2 Non MF Surveys > 1.9.2 All Questions Survey > 1.9.2 All Questions Form` there are 3 response for the survey, only one of which is visualised on the cartodb maps.

* There's occasionally some weird behaviour on the drop downs. I've not figured out a concrete way of reproducing this, but I think it might be something to do with visiting the maps tab, going to a different tab, and then coming back to maps again:

![screen shot 2015-11-01 at 23 41 04](https://cloud.githubusercontent.com/assets/3003031/10872547/23ccfc86-80fc-11e5-9b96-8de95c6fb615.png)

not sure if this is any help, but the below callback seemed to be misbehaving when the dropdowns were:

![screen shot 2015-11-02 at 00 54 58](https://cloud.githubusercontent.com/assets/3003031/10872561/7a5c5880-80fc-11e5-97de-bfd798f60997.png)

* Somewhat of an edge case, but if a user has submitted an empty geoshape then there's an error thrown upon retrieving it:

![screen shot 2015-11-02 at 00 24 12](https://cloud.githubusercontent.com/assets/3003031/10872568/9c193074-80fc-11e5-8206-aa43c6d6a349.png)

**Comment by kymni** [comment]
@rumca @jonase was able to replicate the dropdowns bug, there's a jquery event being fired multiple times when the cartodb map is loaded. I am working on a fix

**Comment by rumca** [comment]
All of the above issues have been addressed :+1:
