### ISSUE TITLE
Deletion from 'Edit' pop-up on Inspect Data tab doesn't remove item from list (estimated: 6)

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1358]
When a user clicks to edit a response on the inspect data tab, then chooses to delete it (via the delete button), the response is deleted but not removed from the list of responses. Which allows us to click to edit it again, resulting in this:

![screen shot 2015-07-23 at 00 20 55](https://cloud.githubusercontent.com/assets/3003031/8839867/fd919948-30d1-11e5-99ab-0a16787a9860.png)
![screen shot 2015-07-23 at 00 21 04](https://cloud.githubusercontent.com/assets/3003031/8839868/0282bd24-30d2-11e5-81fd-518546f76520.png)

**Comment by stellanl** [comment]
I just tested this on akvoflowsandbox, and it gets deleted from the list just fine. Did someone fix it or is it data-dependent?
