### ISSUE TITLE
Can't remove a role after it's been assigned once

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1364]
On the Users > Roles & Permissions tab we have a "number of users" count. This doesn't seem to be updated when we remove that role from a Folder/path. For example in the UAT environment I currently have no users who are assigned a particular role, however the count is still set to 8. 

This means that it's not possible to delete a role after it's been assigned once (even if it's subsequently unassigned).

**Comment by akvotender** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-23509-from-pvanbussel-at-agriprofocus-dot-com
Assignee: Geert Soet

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-55115-from-wendy-dot-richardson-at-unwomen-dot-org
