### ISSUE TITLE
Moving folder onto itself (estimated: 4)

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow#1367]
It's currently possible to move a folder onto itself (or some folder further down the hierarchy). This will result in a situation where the parentId path introduces a loop and never reaches the root folder. Immediate result of this is that the folder dissappears from the dashboard.

We should make sure that this is not a possibility:
- Disable the target folder `<a>` tag so it's not possible to navigate into the target folder
- Possibly add a check on the backend

**Comment by muloem** [comment]
@rumca the script for checking for folders has been created but we also need to include a fix to prevent this from happening.  Thats why I moved it to the next release.

**Comment by rumca** [comment]
:+1:

**Comment by akvotender** [comment]
Assigned to [Tender discussion #6247](http://flowhelp.akvo.org/discussions/problems/6247-missing-folder-in-our-flow-instance).

**Comment by janagombitova** [comment]
So I tried to move the folder on itself and tried and tried and could not. But I could move it somewhere else, so all good 👍  Ready to get out there
