### ISSUE TITLE
CartoDB milestone 3: Geoshapes on dashboard - Visualization in the Inspect data & Monitoring tab

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1370]
### Overview

Currently the geographic shape feature, geoshape, is fully operational on the data collection side of FLOW, on the app. This allows users to define within a survey form a geoshape question type and on the device they create the shape in the field. However, attention is needed to visualize and automate this process on the FLOW dashboard in order to finalize this feature.

We will approach this feature in multiple phases. Our main goals are: 
   1. Visualization on the map
   2. Visualization in the Inspect data tab and Monitoring
   3. Exporting geoshapes
   4. Minor UX fixes and improvements on the app

In this implementation we will work on **Visualizing geoshapes in the Inspect data and Monitoring tab**. 

#### This implementation will include
1. In the answer field show a map box with the geoshape layer rendered on it. 
   - automatically visualize the map and geoshape as an answer
   - map is zoomed in to show the geoshape in a visible size 
   - map enables zooming in and out and the geoshape respectively grows or shrinks
2. Showing computed values related to the geoshape next to the map box
   - computed values will stand as an answer to the geoshape question:
      - Total size of the geoshape:
      - Length of the geoshape:
      - Total number of points:

**Comment by janagombitova** [comment]
![in data tab - 01](https://cloud.githubusercontent.com/assets/12456965/9004191/4b47dbb8-3774-11e5-90c2-b148de8ee24b.png)

**Comment by janagombitova** [comment]
@kymni @jonase Can we tackle in this milestone, as what Ruarcc pointed out, as to show in the Map tab not only polygons, but also lines and points collected via the geoshape question? This means expanding the current feature: open Map tab > click on point > shows geoshape polygon in the side bar + option to render on main map as well. 

**Limitation:** Cases where multiple shapes, or multiple types of shapes are collected under one question are left out of the implementation, because we will not allow this anymore.

**Comment by kymni** [comment]
@janagombitova @jonase picking up on this under branch feature/1370-geoshapes-inspect-data

**Comment by kymni** [comment]
## Test Plan
Loading a geoshape question answer in the inspect data tab loads a map
![screen shot 2015-11-11 at 15 36 01](https://cloud.githubusercontent.com/assets/1155088/11091340/9045d014-888a-11e5-8382-1e55196929b2.png)

Loading a geoshape question answer in the monitoring tab loads a map
![screen shot 2015-11-11 at 15 36 45](https://cloud.githubusercontent.com/assets/1155088/11091355/a87beefc-888a-11e5-84e3-1ec24eae5002.png)

**Comment by rumca** [comment]
Test plan passes as described.

Nice work @kymni and @jonase this looks really great :+1:
