### ISSUE TITLE
Change data view table from Question ID to question order 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1371]
**related to Repeatale question groups** 

Because the users do not use or need to see the question ID when previewing collected data, we decided to take that information out of the data preview and substitute it with the order of the question. Secondly we will add a row for each question group name. These additions derive from the changes related to repeatable question groups. 

These changes apply on the data preview in the Inspect data tab and in the Monitoring tab (when viewing details of a form submission) 

![screen shot 2015-07-31 at 11 42 04](https://cloud.githubusercontent.com/assets/12456965/9004943/8374c298-377a-11e5-83c2-d4f2b7095e5b.png)

![screen shot 2015-07-31 at 11 43 16](https://cloud.githubusercontent.com/assets/12456965/9004946/8617c91e-377a-11e5-98d8-edd3e2e5da05.png)

### Change to 

![question table](https://cloud.githubusercontent.com/assets/12456965/9004951/8a923cfe-377a-11e5-99d9-c1e70471036b.png)

**Comment by muloem** [comment]
@janagombitova we should close this issue as the fix related to this is implemented in repeat qn group #269 branch.

**Comment by janagombitova** [comment]
Yes, I created it so we do not forget about the small change. I am closing the issue.
