### ISSUE TITLE
Request for icon_cal.png returns a 404

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-flow#1376]
The file icon_cal.png is referenced in main.scss on lines [1354](https://github.com/akvo/akvo-flow/blob/389a3c6eab05d7abc458930c7e32e9167767176d/Dashboard/app/css/main.scss#L1354) and [3944](https://github.com/akvo/akvo-flow/blob/389a3c6eab05d7abc458930c7e32e9167767176d/Dashboard/app/css/main.scss#L3944)

This file was deleted in https://github.com/akvo/akvo-flow/commit/d3e883c722d4d2811326daa1ff818c7f5c901980 so requests return a 404

Fix: either remove the references to icon_cal.png from main.scss or restore the file icon_cal.png to `Dashboard/app/static/images/`

**Comment by rumca** [comment]
this 404s on the "Notifications screen" (Create Survey > Manage Notifications) not sure if it's actually used elsewhere so perhaps we can just delete the reference?

**Comment by gabemart** [comment]
I spoke with Loic, we can take it out. I will do so and commit against this issue.

**Comment by gabemart** [comment]
### Test plan

1) Open Create Survey > Manage Notifications

2) Verify there is no request for icon_cal.png and no 404 response

**Comment by rumca** [comment]
test plan passes
