### ISSUE TITLE
Data export: don't use scientific notations for large numbers

### ISSUE THREAD

**Issue by akvotender** [akvo/akvo-flow#1381]
Assigned to [Problems #5678](http://flowhelp.akvo.org/help/discussions/problems/5678-scratchcard-bulk). As reported in Tender:

<blockquote><p>Dear Emmanuel,</p>

<p>How are you? I spoke to Josje yesterday about the bulk upload for
'Scratchcardbundels' and we have seen already uploads are made. However,
when we want to extract data, the numbers are exported in scientific
notation but as text, so not to be changed to normal numbers. Could you
check this and perhaps find a way to solve it? Jean Baptiste is using it
and coming weeks we will send you an overview of what we have been doing
here.

**Comment by akvotender** [comment]
Addiotional information received from end user:

"Another issue has now come up in the file. New entries are not delimited by 
"|" as should be the case, but have a mere space between them."

**Comment by muloem** [comment]
@rumca I believe this is also resolved by #1534. Please verify. thanks!

**Comment by rumca** [comment]
scientific notation for large numbers on import no longer an issue
