### ISSUE TITLE
Broken order of questions and question groups

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1382]
Sometimes the order of questions and question groups does not render properly. The work-around is to add a new question or group, however this is a small detail we should fix. 

**Question group example:** 

![img_1333](https://cloud.githubusercontent.com/assets/12456965/9251660/a2491c28-41d4-11e5-9e03-33e241dffff4.JPG)

**Comment by akvotender** [comment]
Assigned to [Tender discussion #5688](http://flowhelp.akvo.org/discussions/problems/5688-fwd-nu-nog-vreemder).

**Comment by janagombitova** [comment]
Closing this issue as it is handled in https://github.com/akvo/akvo-flow/issues/1393
