### ISSUE TITLE
FixSurveydLocale datascript does not check all SurveyedLocales

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow#1390]
The current FixSurveyedLocale data script does not process SurveyedLocales (data points) for which for which `surveyGroupId` is missing (which is not the same as `== null`). We need to change the data script to cover missing `surveyGroupId`s as well.

**Comment by rumca** [comment]
I think this is complete, but is a datascript issue so not relevant for the testing of 1.9.1 so closing
