### ISSUE TITLE
Inserting questions triggers repositioning of surrounding questions

### ISSUE THREAD

**Issue by akvotender** [akvo/akvo-flow#1393]
Assigned to [Problems #5708](http://flowhelp.akvo.org/discussions/problems/5708-wash-alliance-dashboard-troubles-saving-questionnaire). - Sometimes when adding a new question the question number is duplicated
- This can be resolved by adding and deleting a question however this messes up the order of the questions.
# 

As reported in Tender:

<blockquote><p>Hi colleagues, </p>

<p>This week Verele from Waste has called me I think already 8 times and I’m not able to help her. But with my FLOW knowledge it’s really hard to help her. </p>

<p>In <a href="/discussions/problems/5708/r?go=aHR0cDovL2R3YS5ha3ZvZmxvdy5vcmcvYWRtaW4v" title="Link outside Support: http://dwa.akvoflow.org/admin/">http://dwa.akvoflow.org/admin/</a> &lt;<a href="/discussions/problems/5708/r?go=aHR0cDovL2R3YS5ha3ZvZmxvdy5vcmcvYWRtaW4v" title="Link outside Support: http://dwa.akvoflow.org/admin/">http://dwa.akvoflow.org/admin/</a>&gt; folder ‘DWA Outcome Measurement 2015 (draft)’ &gt; Household survey 2015: there are a few things going wrong:</p>

<p>- When she adds a new question, sometimes a question number is saved that already exists. I’ve already explained that it’s a bug and that we are working on it. She knows she can delete and add the question again. But this doesn’t help her any further. 
<br>- She has added French translations for each question and saved this. However, it seems that some translations have disappeared. 
<br>- She has got the feeling that the order of the questions is now mixed up. </p>

<p>Can someone give her a call this afternoon and help her? It’s urgent. 0642229822. 
<br>I would like to be kept in the loop. </p>

<p>Thanks, </p>

<p>Laura</p></blockquote>

**Comment by akvotender** [comment]
Additional information by Emmanuel:

I just had a Skype chat with Verele and we resolved all her issues.

the numbering of questions was resolved by adding a new question in between. While we did this, however, another issue appeared that when inserting questions in between, somehow the questions are shifted out of their expected order. We will have to follow this up with a github issue to resolve

regarding the missing translations, it was a matter of her publishing the survey before generating the SURVEY form in order for the latest translations she had added to appear in the SURVEY excel form. None of the translations were missing in the dashboard.

She also mentioned that she had been working on two computers at the same time last week, editing the same survey and I cautioned that this could give the appearance of two people editing a survey at once, and might have caused some of the instabilities she noticed last week.

**Comment by akvotender** [comment]
Remaining issue:

- Sometimes when adding a new question the question number is duplicated 
- This can be resolved by adding and deleting a question however this messes up the order of the questions.

**Comment by akvotender** [comment]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/problem-w-dependencies-dot-dot-dot
Assignee: Geert Soet

Message:
Hey Brooke - 

Just had a look and part of the reason may be that the question numbering was missing 20. so instead of the numbering going  19, 20, 21, in went 19, 21. I”m not sure why this happens, but a quick fix is to add a new question (which resets the numbering) and then delete it. Also the question order seems to be reversed - as per below. The FLOW system will only let you make questions dependent upon answers that have already been asked, so question 20 can be dependent on the answer from question 19, but question 19 can’t be dependent on the answer to question 20. 

I’ve reversed the order of Q19 and Q20 and now the dependency should be working. Sometimes the dependencies can get messed up if you are copying or moving questions around. 

Please let me know if you have any other problems or questions!
Best,
Nikki Sloan
Project Officer 
SE Asia &amp; Pacific

S sloan.18
T @nikjsloan

P (+61) 423 963 831

Latest Akvo Articles
- Why Monitoring &amp; Evaluation? http://akvo.org/blog/why-monitoring-evaluation/?pk_campaign=M&amp;E&amp;pk_kwd=M&amp;E
- End-user feedback: who do you call? http://akvo.org/blog/end-user-feedback-who-do-you-call/?pk_campaign=End%20User&amp;pk_kwd=End%20User
- Akvo RSR: what’s coming soon 
- Dutch farmers test water quality in North Holland  http://akvo.org/blog/dutch-farmers-test-water-quality-in-north-holland/?pk_campaign=Farmers%20test&amp;pk_kwd=Farmers%20test
- Akvo Foundation USA: Strategy Overview http://akvo.org/blog/akvo-foundation-usa-strategy-overview/?pk_campaign=USA%20strategy&amp;pk_kwd=USA%20strategy
- Monitoring in practice; preparation is key to success http://akvo.org/blog/monitoring-in-practice-preparation-is-key-to-success/?pk_campaign=monitoring%20in%20practice&amp;pk_kwd=monitoring
- Fiji: Education and Disaster Response http://akvo.org/blog/fiji-education-and-disaster-response/?pk_campaign=Fiji&amp;pk_kwd=Fiji

What’s new in Akvo RSR?
- Communicate-Report-Monitor http://akvo.org/products/rsr/#overview

**Comment by janagombitova** [comment]
Related https://github.com/akvo/akvo-flow/issues/1382

**Comment by janagombitova** [comment]
From speaking to @stellanl today we learned that the order of questions and groups is not only a UI element but an important value for other tasks in Flow. In the case where the order is incorrect: 19, 20, 22 for example there are no major issues related, but if we have: 19, 20, 20, 21 then the two questions with order number 20 one will not show in the app, thus not data will be collected for it. 

We need to make sure the order is always correct even if the users delete, move questions around, copy in questions or groups, etc.

**Comment by kymni** [comment]
In current implementation, once a question is moved or deleted or a new one created, the order of all questions whose order has been altered is updated by sequentially making calls to the questions end-point to update the order. This means that for 'x' affected questions, 'x' calls will be made. For surveys with many questions, this can weigh a heavy load on the browser causing some of the calls to fail. This could be the reason for this issue.

Suggestion is to set the questions end-point to accept orders in bulk, say by setting it to take an object with the structure `<{questionID: questionOrder,......}>` containing the new order of all questions whose order needs to be updated. The end-point should then output a success response code for the local data store to be updated or otherwise

**Comment by stellanl** [comment]
The reordering could also be made an implicit side-effect of the creation/move/deletion, unless it's too heavy to respond with full data for all affected questions (those ordered after the change point).

**Comment by muloem** [comment]
I am in favour of an option in the direction @stellanl suggests. Maybe we want to consider say a group as the atomic unit.. i.e. any changes in question ordering are posted at the level of question groups rather than individual questions.

**Comment by stellanl** [comment]
We could start out really simple and make all changes to a question return the list of all questions in the group, and then optimise it down from there.

**Comment by stellanl** [comment]
There is a further wrinkle in that the delete function already performs reordering of the neighboring questions. However, that is all done on a background thread because of the time it can take to delete a question with its options, translations and help media...
To me, it makes sense to lift the reordering to the foreground handler, and start doing the same for moves and insertions.

**Comment by stellanl** [comment]
We decided to go in the opposite direction and do the reordering in the browser and then inform the backend, via one extra call with a list of all the changed questions.

**Comment by janagombitova** [comment]
@stellanl and @kymni I am testing this branch on UAT2 and many things work perfectly, as copying question, groups, and moving them around and making sure all the settings behave as they should. 

But I managed to get a question with order number 0. I have a group with 4 or five questions and then deleted them one by one in a row and ended up with 1 question. This one now has order number 0. If I copy the entire question group, then the number in the copied group is ok. 

The form is on https://uat2.akvoflow.org/admin/ under 1.9.30 tests > Repeated copy > MF (7140013) 

<img width="1259" alt="screen shot 2018-03-27 at 16 06 38" src="https://user-images.githubusercontent.com/12456965/37973131-20642376-31da-11e8-8a7f-8a8b5dcf587c.png">
<img width="1266" alt="screen shot 2018-03-27 at 16 09 29" src="https://user-images.githubusercontent.com/12456965/37973132-207e1858-31da-11e8-9ead-ad8692b9b702.png">

**Comment by janagombitova** [comment]
Hi @stellanl and @kymni I tried to make the order jump to 0 again but I could not get Flow to do it. One thing that I did notice is that on low connectivity - I used the slow 3G setting on the Console - and when you do many different tasks after each other, copying and then adding another question, and another, then moving the group, after opening the group the questions do not show right away and the view jumps a bit. After a second or two the questions render. If Flow is still processing the actions then it is better to show the loading spinner or copying to inform Salim that things are still happening. Will try again tomorrow to reproduce the error from the comment above

**Comment by janagombitova** [comment]
Hi both, 
Me again. Yesterday evening I tried to reproduce the error - no luck. This morning I opened the same survey I was working on and suddenly one of my questions has 0 as an order number. 

You can find it here: https://uat2.akvoflow.org/admin/ > 1.9.30 tests > Trying to get to 0 > 2nd group named g1

**Comment by kymni** [comment]
Reproduced and investigating

**Comment by janagombitova** [comment]
@muloem @stellanl @kymni uat2 tests worked fine yesterday. Are we ready to merge and test on uat1?
