### ISSUE TITLE
Editing survey twice in same session results in blank page

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-flow#1402]
To reproduce:

1) Create a new survey

2) Add a form

3) Hit "Surveys" link to enter Surveys tab

4) Edit the form you just created

Expected result: navigate to survey editor

Actual result: Blank screen

Console reads: `Uncaught TypeError: Cannot read property 'get' of null`

caused by: `return form.get('status') === 'PUBLISHED'` in 
survey-group-views.js - [view it here](https://github.com/akvo/akvo-flow/blob/develop/Dashboard/app/js/lib/views/surveys/survey-group-views.js#L83-L86)

**Comment by rumca** [comment]
Nice! I've encountered this a few times, but could never workout the exact steps to reproduce it consistently. I think there may be a few other places that a similar issue occurs, I've seen the initial surveys tab blank screen a few times too.

**Comment by muloem** [comment]
# Test Plan

1) Create a new survey

2) Add a form

3) Hit "Surveys" link to enter Surveys tab

4) Edit the form you just created

You should be able to go to the form without hitting a blank screen

**Comment by ichinaski** [comment]
Tested on dev-2. Works as expected.

**Comment by janagombitova** [comment]
This is still a problem and it would be good to give it a second look. It is quite an annoying bug

**Comment by janagombitova** [comment]
@kymni can you prioritise this issue forward on your to do list once back from holidays?

**Comment by kymni** [comment]
To reproduce:
1. Leave the survey tab and select a survey using the survey selectors on any of the other parts of the dashboard
1. Navigate to the survey tab and select the same survey selected above
1. You should see a blank screen

Navigating away to a different part of the dashboard then back to the survey tab and selecting a different survey doesn't produce a blank screen

**Comment by janagombitova** [comment]
@kymni have you tried with selecting the **same** survey?

**Comment by kymni** [comment]
@janagombitova yes, basically selecting the same survey reproduces the the problem but selecting a different survey doesn't
