### ISSUE TITLE
Question groups are duplicated when attempting to copy between survey forms

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1404]
Steps to reproduce:

1. Create two surveys containing a single form each with a single, named question group.

2. Open the first survey and select `Copy` on the question group

3. Navigate to the second survey and select the button `Paste Group here`

4. When copying is finished, refresh the dashboard and go back to the first survey

5. The question group is now duplicated

It is should not be possible to copy question groups across surveys for the moment and therefore the `Paste Group Here` link should not even be visible in the second survey form.

**Comment by akvotender** [comment]
Assigned to [Tender discussion #5708](http://flowhelp.akvo.org/discussions/problems/5708-wash-alliance-dashboard-troubles-saving-questionnaire).

**Comment by jonase** [comment]
Closing this one because it's a subset of https://github.com/akvo/akvo-flow/issues/1510
