### ISSUE TITLE
Cartodb custom maps - implement custom maps management

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1407]
### Overview

The custom maps will enable data-driven styling of markers and custom icons on the Akvo FLOW maps. This will expand the basic map functionality to the current FLOW maps and will give the users a chance to understand their collected data better in geographic context. We will implement this feature in separate steps, starting with the most basic functionality and supporting the simplest data structure, followed by tackling more complex items (as monitoring and repeated question groups for example). The users will be able to save their created maps and publish them on their website or share with other partners.

The initial implementation will enable to base a map only on option questions per selected registration form and on a selected geographic shape question. No custom icons will be supported and the user can only save the visualisations (no publishing). We will also add a set of permissions covering this new feature.

Following implementations will tackle monitoring forms and repeated question groups.
### Links to documents

Links to the functional design document
https://github.com/akvo/akvo-product-design/blob/master/FLOW/Features/133-Custom-maps/1st%20implementation%20-%20Functional%20design%20document.md

**Comment by janagombitova** [comment]
![map visualizations](https://cloud.githubusercontent.com/assets/12456965/9680230/9c56777a-52f5-11e5-9d9c-760346f6eeec.png)

**Comment by janagombitova** [comment]
Feedback Jigmy: Can we add separate text boxes within the map?

**Comment by janagombitova** [comment]
**Mock ups:** [Custom maps.pdf](https://github.com/akvo/akvo-flow/files/35395/Custom.maps.pdf)

**Comment by janagombitova** [comment]
Mockups for this 1st implementation 
[Custom maps - 1st Implementation.pdf](https://github.com/akvo/akvo-flow/files/64147/Custom.maps.-.1st.Implementation.pdf)

**Comment by kymni** [comment]
Proposed approach is to start by creating the following templates to handle the custom maps
* Maps list template
* Map view template
* Customize map template
We then need to figure out how to tie different maps to users who create them
We should create (a) CartoDB table(s) to store the map details and metadata such as cartocss and interactivity columns
Changes will be made on a new branch based on this issue

**Comment by muloem** [comment]
I am a bit late to this party but I have one comment.  Regarding having the two buttons i.e *data maps* and *custom maps*, I believe we do not need this distinction.  The data map is like a custom map but with no filters defined.  It can be the default defined map selection, and is immediately visible if no other custom map has been defined.. and have the title *All data points* or something similar.

If there are other maps defined then we can think about whether we want to show a specific map by default when a user navigates to the maps section, or to show a list of maps from which they can select or define a new one.

What do you think?

@Kiarii @loicsans @janagombitova

**Comment by Kiarii** [comment]
@muloem, I would agree; the last sketch from my side didn't have the distinction. There must have be some reason why it was added..

**Comment by janagombitova** [comment]
@muloem and @Kiarii Yes that was part of the initial thinking in the sketches. And here is the reason for the change: 

After showing the mockups to a few akvonauts in the partner team, defining the feature requirements, looking in the public maps on FLOW as well and how to handle them more questions and un-clarities came up which were not dealt with in the initial implementation and were pushed to the 2nd phase, as: 
- we currently do not support 'All datapoints' with the CartoDB map implementation, the user always has to select a survey + form to see data on the map
- what if the user simply wants to check the submitted data for a survey (same workflow as currently) - then in Kiarii's latest mockups this was not easily possible, and too many steps were needed and it seemed illogical to have to create a new map > select the survey + form and see the points > then disregard or save that map
- how will be deal with the public map? can the user create a custom map and select it as 'show on public map'? (this closely relates to your suggestion Emmanuel)
- how to deal with monitoring surveys and repeated question groups? 
- what about multiple select options and other? 
- how will these changes fit into the coming up new FLOW dashboard design where we want to give priority to each survey and move the related actions (in this case maps) under it

So, as these questions will eventually affect the final design of custom maps and as we need to implement the most minimum set of functionality now, we decided to make the intervention as least intrusive as possible. So the 1st implementation means leaving the maps as they are and adding the custom maps to them.

**Comment by muloem** [comment]
@janagombitova so if I understand correctly the main motivation is to have the CartoDB hosted maps present similar functionality to the current maps we have right now? i.e show all data points when the map is first opened, and then navigate / filter the data as a user would like?  Perhaps this is possible without an extra navigation button? @jonase @kymni?

**Comment by janagombitova** [comment]
@muloem for now, yes. We want to maintain the functionality people are used to and add the color coding on top of that. I worry that your question will affect the design provided by Kiarii and at this point of time we do not have capacity to revise the designs again. I would leave it as it is, implement the 1st plan, get feedback and then decide how to move forward. But maybe I do not fully understand your question.

**Comment by kymni** [comment]
- User should be able to view a list of custom maps, view or edit an existing one, or create a new one.
- Experiencing an issue with the colour selector library (jquery-mini-colors) where the pallet won't let the user pick specific colors unless they type the colour code. This could be a conflict with preset styles for the input element so am currently exploring a fix

**Comment by janagombitova** [comment]
Together with Charles we use this document to track feedback on the working prototype and decisions made: https://docs.google.com/document/d/1mTKqOshhDVT47KCci2OnJBUdiho54eSXKwi6zRRSHzM/edit

**Comment by janagombitova** [comment]
After the planning poker session we agreed to keep feature descriptions in product design repository and small issue that build up the new feature in flow repository. Thus I am moving this issue to Priority 1 for now and we need to break down the implementation into small issues which Charles can handle for the 1.9.8 milestone.

**Comment by janagombitova** [comment]
@kymni and @muloem I have created a general Custom maps issue in the Product design repository as we agreed on during the planning poker. https://github.com/akvo/akvo-product-design/issues/143 It holds all the general information for this feature, as documentation, mockups, and we can move broader discussions there. In the Flow repository Charles broke down the next implementation steps into separate issues. 

I do not know what to do with this issue as some commits are referenced here. What is the best thing to do?

**Comment by janagombitova** [comment]
Following the decisions shared here https://github.com/akvo/akvo-product-design/issues/143#issuecomment-289067188 I am closing this issue as the functionality of Custom maps will not be part of Flow's feature list.
