### ISSUE TITLE
Geoshapes on dashboard - export geoshape 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1408]
#### Deliverables: (suggestion)
The ability to export geaoshapes with all the other collected data under the form in a format suitable for further GIS analysis. 
   - type of export file - shapefile - .shp or kml file - .kml 
   - technical implementation: @joycarpediem and @jonase can you see how to implement this? What are the technical requirements? Will this affect the server? 
   - proposed UI solution: add another report type under the Reports tab > Export Reports:
      - Title: Export shapefile/ kml file
      - Text: to be defined
      - Button: EXPORT SHAPEFILE/KML 

#### Limitations  
- we will not allow to import a shape back, only export possible
- we will NOT allow for a user to import and edited shape back into FLOW, too complex

**Comment by janagombitova** [comment]
@jonase @kymni @muloem. This is the last part of the geoshapes implementation. The export of shapes was one of the deliverables agreed upon with SNV and I based the definition on the requirements from their side. I would like to know your opinions. Can we look into this and see how to tackle it?

**Comment by jonase** [comment]
@janagombitova Is this part of milestone 2?

**Comment by janagombitova** [comment]
@jonase No, it is not. The deadline is by the end of this year, so December. Lets take time to research this properly and find a suitable solution.

**Comment by janagombitova** [comment]
Information received from partner: Exporting shapes: This is what I need as GIS person. Either shapefile (*.shp) or *.kml format will be good. Especially if the exported *.shp or *.kml also can bring all the attributes that has been surveyed. Based on that *.shp or *.kml, further analysis can be done.

**Comment by jonase** [comment]
## Proposed initial implementation

After discussions with @janagombitova and @joycarpediem we will approach the geoshapes export by exporting a single geoshape question into geojson files with the following structure:

```json
{
  "type": "FeatureCollection",
  "properties": {
    "surveyId": 123,
    "formId": 321,
    "questionId": 421,
    "questionText": "This is the GeoJson Question text"
  },
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [[100,200], [123,432], [421,432]]
      },
      "properties": {
        "__instanceId": 521,
        "__area": 2342,
        "__length": 234,
        "__pointCount": 2,
        "Number of Farmers": "8",
        "Name of village": "abcdef",
        "Another GeoJson": "{ ... }"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [ ... ]
      },
      "properties": { ... }
    }
  ]
}
```

* On the top level `FeatureCollection` we record the `surveyId`, `formId`, `questionId` and `questionText` as metadata under `properties`
* Each response will be a separate `Feature` containing a geometry of type `Polygon` (the geoshape). With each response we will also record *all additional answers* in the `properties` map where the `questionText` is the key (and the response is the value, as text).
* There are known limitation to this export layout
  * Repeatable questions are not supported. We will only export the first iteration
  * Risk of name clashes in the properties maps.
  * Question types are lost for the additional question answers

* When we have an example export with some real data will will evaluate the chosen export design and improve the design. This file layout has been chosen to ease the import into existing systems.
* Next step is also to transform the exported files to shape- and kml files with existing tools such as `ogr2ogr` or equivalent.

**Comment by janagombitova** [comment]
#### UI deliverables under Reports tab > Export reports sub-tab: SUGGESTIONS: 
- create new report type: 
   - Title: Export geographic shape 
   - Text: Export a geographic shape and all data from a single form in a geojson file. In order to create this report you need to select your question containing a geographic shape from the chosen survey. This file type can be then transformed into .kml or .shp (shape file) file and opened in any geographic information system (GIS). 
   - dropdown with the list of geoshape questions from the selected folder > survey > form for the user to select
   - Button: EXPORT GEOSHAPE. 
- add warning pop up message: If the user clicks on the 'export geoshape' button before selecting a question, show pop up saying: Title: Export geographic shape Text: You must select a survey and a question to run this report.

@jonase @joycarpediem What do you think?

**Comment by joycarpediem** [comment]
@janagombitova +1

**Comment by janagombitova** [comment]
Jana to do: revise the text sentence to make more clear. Otherwise it is good to go.

**Comment by jonase** [comment]
## Test Plan

* Create a survey with a geoshape question (as well as other question types)
* Create a few responses where the geoshapes are **polygons** and not points or line segments
* Go to the `Reports/Export Reports` tab and select the folder/survey/form
* In the section *Export geographic shape* choose the geoshape question
* Click *Export Geoshape*
* (if you don't specify a geo question you should get a warning)
* You should get an email with a link to the geoshape export file which should be a valid JSON file
* If you have a cartodb account: Try to upload the file to Cartodb:
  * Click "New Dataset"
  * Browse (or drag/drop) the json file
  * Click "Connect Dataset"
  * When the upload is done you should see your shapes in the "Map View"

**Comment by muloem** [comment]
@jonase can you maybe add in the test plan the cases for points and lines and what is expected?

**Comment by jonase** [comment]
@muloem sure :+1:

**Comment by rumca** [comment]
Test plan passes as described :+1:
