### ISSUE TITLE
Folder selection drop down hidden behind calendar elements

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1409]
Under the *Inspect Data* tab, in cases where there is a deep folder hierarchy, the drop down for selecting  folders gets hidden behind the calendar.  See highlighted in the screenshot below.

<img width="1042" alt="hidden-dropdown" src="https://cloud.githubusercontent.com/assets/533336/9714339/a0e3f9b6-5557-11e5-8e5c-e39bdc749f6d.png">

**Comment by akvotender** [comment]
Assigned to [Tender discussion #5794](http://flowhelp.akvo.org/discussions/problems/5794-issue-with-the-snv-kenya-dashboard).

**Comment by gabemart** [comment]
As discussed with @muloem proposed fix is to move the date input elements to the block with the other filter elements

![screen shot 2015-09-07 at 18 40 59](https://cloud.githubusercontent.com/assets/2589977/9721302/079333ce-5590-11e5-8f5c-c0dbeadaea56.png)

**Comment by gabemart** [comment]
### Test Plan

1) Create or access a survey at the bottom of a long folder tree

2) On the "Inspect Data" view for that survey, ensure the folder input elements are not obscure and are usable

3) Verify that the "collected from" and "to" date inputs appears in the grey filter bar alongside "SUBMITTER NAME:"

4) Verify that the date inputs still function correctly

**Comment by Geerts** [comment]
In which release will this one be? SNV can't see how the data collecting is going in Kenya, providing them a workaround now.

**Comment by janagombitova** [comment]
@Geerts I think we can add to it the next one (the delayed one) considering Gabe fixed it. @muloem correct me if I am wrong.

**Comment by gabemart** [comment]
@janagombitova yes that was the plan I discussed with @muloem if the fix passes muster

**Comment by rumca** [comment]
Test plan passes as described.

@gabemart the nesting still seems to be obscured/awkward to use once you go past the 8-10 nested level (depending on the folder name) - not sure if we actually have anyone using folders that are so deeply nested, but perhaps in a future release we could just wrap the selection drop downs once they go past a certain level?
