### ISSUE TITLE
Variation of total number of responses in charts - multi select

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1414]
When creating a chart out of a multiple answer option question confusion occurs, because FLOW calculates as the total number of responses the total number of chosen answers. This is likely higher than the actual total number of responses. 

<img width="1230" alt="screen shot 2015-09-25 at 11 45 41" src="https://cloud.githubusercontent.com/assets/12456965/10097674/0a9ca3e0-637b-11e5-93ec-53de248de6dc.png">
Chart out of multiple select options

<img width="1232" alt="screen shot 2015-09-25 at 11 45 56" src="https://cloud.githubusercontent.com/assets/12456965/10097870/b2e00028-637c-11e5-8ac6-a745d286bd50.png">
Chart out of another question from the same form

**Comment by janagombitova** [comment]
Suggestion: 
Add a text under the chart, which will only be displayed if the selected option question has multiple select allowed. The text will inform the user on the higher number of responses. 

'Note that on multiple answer questions, the 'Total' shows how many total answers were chosen, which is likely higher than the total number of respondents.'

@muloem Emmanuel, this is the issue Jigmy shared during team week. What do you think is the best solution?

**Comment by muloem** [comment]
@janagombitova As we discussed, for the multi option questions we should not enable generating pie charts as its misinformation.

**Comment by janagombitova** [comment]
@muloem Ok. Lets do that then: Disable pie charts for option question where multiple select is enabled. 

@gabemart Is this something you can fix?

**Comment by janagombitova** [comment]
Duplicate: https://github.com/akvo/akvo-flow/issues/682
