### ISSUE TITLE
Filter behaviour on Monitoring Tab

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1424]
This might be the intended behaviour (in which case please ignore this!)

When you fill out the data point name on the monitoring tab to filter the results, it looks like the survey selected in the drop down is completely ignored and all monitoring surveys are searched. Here you can see that I am searching for 1.9.1 MF Surveys:

![screen shot 2015-10-05 at 17 21 16](https://cloud.githubusercontent.com/assets/3003031/10286515/f900e23c-6b85-11e5-93cf-8a4df657a4fe.png)

But the results returned are from a much older survey:

![screen shot 2015-10-05 at 17 21 26](https://cloud.githubusercontent.com/assets/3003031/10286537/0e158cea-6b86-11e5-8218-241a40d9e89f.png)

**Comment by janagombitova** [comment]
As we are changing the entire data view structure with implementing Webforms, and the monitoring tab will be integrated into the Inspect data tab, we can ignore this issue and not fix it for now
