### ISSUE TITLE
Minor Issue - Numerical values stored differently on import

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1425]
When we create new data points with the spreadsheet importer theres a slight discrepancy between the format of the number in the import file, and the way we are storing them in the dashboard. Integers seem to be implicitly converted to doubles or something:

![screen shot 2015-10-05 at 17 32 02](https://cloud.githubusercontent.com/assets/3003031/10286937/502403e4-6b88-11e5-88ea-327c37e2d4d1.png)

![screen shot 2015-10-05 at 17 34 05](https://cloud.githubusercontent.com/assets/3003031/10286942/579a1366-6b88-11e5-9a6b-36b6dbca6e1c.png)

I think the only time this could be an issue is when people are using a number question as part of the data point name and then they use the importer to create points - which seems like an edge case to me, so perhaps we can ignore this.

**Comment by muloem** [comment]
@rumca can you cross check that this is resolved?  It should be handled by the changes made under #1534

**Comment by rumca** [comment]
@muloem yep this seems to have been resolved also.

I'm pretty sure this is a work in progress, but from my original comments on this issue it looks like the datapoint display name was being updated according to changes back in October and that's no longer the case. I seem to recall you mentioning that it's a known issue that it doesn't currently work? Or is this something I should log.
