### ISSUE TITLE
NPE when accessing the SurveyInstance Key before it's saved into the datastore

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow#1432]
# Overview

This exception can be thrown on [SurveyInstance.java:319](https://github.com/akvo/akvo-flow/blob/master/GAE/src/org/waterforpeople/mapping/domain/SurveyInstance.java#L319-L320), when the datapoint name is not set and the survey contains some questions flagged as datapoint name.

The fix is to first fetch the questions in the SurveyInstance itself (no datastore access), and if these have not been populated (data cleaning) attempt to read them from the datastore, first checking the nullity of the key.

**Comment by ichinaski** [comment]
**Test plan:**
a) Submit new datapoints with non-mandatory questions flagged with data point name. (NPE should be gone)
b) Ensure data cleaning (report import) keeps working as expected.

**Comment by muloem** [comment]
Hotfix in https://github.com/akvo/akvo-flow/releases/tag/v1.9.1.1
