### ISSUE TITLE
Performance improvements loading survey questions and question options (estimated: 8)

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1442]
While loading surveys we make a request to the `GET /questions?surveyId=` end point. Loading surveys that contain lots of `OPTION` type questions results in a timeout due to the deadline exceeded exceptions from GAE.  There are some straight forward improvements that can be made in the retrieval of questions and their associated components to improve on the current performance.

* [x] Retrieve the list of questions by querying based on the `surveyId` property of the question rather than querying the list of questions per question group (we have to ensure all questions have the `surveyId` property set)
* [x] Skip querying for translation objects of `QuestionOption` entities when making `GET /questions?surveyId=` requests
* [x] Eliminate the redundant `DtoMarshaller.copyToDto()` and `BeanUtils.copyProperties()` calls.  We can instead wrap the domain object with the DTO

**Comment by janagombitova** [comment]
**Decision from Planning poker session:**

For this particular issue we will only invest one day of work to tackle small fixes that will improve the loading. Larger tasks as e.x. tackling translations, will be handled in separate issues.

**Comment by janagombitova** [comment]
Loading of questions for larger surveys has became a growing issue for more dashboards in the last months. We have solved this issue temporarily by re-deploying the instances with a higher instance class. A more long term solution is needed.

@muloem will this issue already cover one of the problems or do we need to create more issues to tackle this problem? 
- issue that covers loading of translations need to be created

**Comment by stellanl** [comment]
Re the first checkbox, I have looked in the datastore of a dozen of our biggest instances and not found a single question without a surveyId.

**Comment by valllllll2000** [comment]
for the first checkbox, it is possible to query by surveyId and then order by questionGroupId column as long as the question group are in correct order. What would happen if the survey group is moved to another position?

**Comment by valllllll2000** [comment]
As for the point 3, both DtoMarshaller.copyToDto() and BeanUtils.copyProperties() actually use BeanUtils.copyProperties(). According to this article:
http://web.archive.org/web/20160404130436/http://rodrigojramirez.com/2013/10/21/beware-of-copyproperties-or-the-30-milliseconds-tale/
it does seem like BeanUtils is very slow especialy when we have large collections. We can use BeanUtils from Spring framework which is faster or write our own Mapper to map the objects. There is also this tool http://orika-mapper.github.io/orika-docs/intro.html, not sure how well it would preform.

**Comment by muloem** [comment]
So in the case of the `SurveyGroup` entities, I just did it manually, however you can try it with spring first and see how that works.

**Comment by valllllll2000** [comment]
@muloem I have created a simple project and simplified Question and QuestionDto (I removed all the complex fields that required importing other classes from the project). I used commons-beanutils version 1.9.3

Here are the results

in miliseconds
Time to do 1000 manual copies: 69
Time to do 1000 copyProperties, apache commons: 1428
Time to do 1000 copyProperties, spring framework: 398

Time to do 10000 manual copies: 286
Time to do 10000 copyProperties, apache commons: 3162
Time to do 10000 copyProperties, spring framework: 497

Time to do 100000 manual copies: 476
Time to do 100000 copyProperties, apache commons: 13130
Time to do 100000 copyProperties, spring framework: 938

**Comment by muloem** [comment]
so looks like the spring BeanUtils will do.  Its in the same order of magnitude as manual copying for the larger sizes. 👍

**Comment by muloem** [comment]
@janagombitova @stellanl @valllllll2000 i moved this to the 1.9.16 milestone because its already been merged into that release.So if the regression tests are good to go i.e. nothing else strange turns up, then we will close this as part of the release.

**Comment by valllllll2000** [comment]
@muloem ok but it seems this is unfinished as actually only the last bullet has been done. The other 2 @stellanl has done it in another task but we would still need to update QuestionRestService to use that new code from https://github.com/akvo/akvo-flow/pull/2025

**Comment by janagombitova** [comment]
I have finished the regression round and all now works well 👍 

@muloem can you please assess the checkboxes and how to proceed on this issue? Can you also share here the stats on loading and if we have achieved an improvement or not? 

Thanks

**Comment by janagombitova** [comment]
I have found no more issues in my last regression round, besides what we have already logged in the backlog 👍  Good to go

**Comment by muloem** [comment]
FYI leaving this one open for now because we still have the translations issue to incorporate into 1.9.18
