### ISSUE TITLE
`Null` values in the `QuestionAnswerStore` entities cause results to be skipped in report

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1443]
When processing survey responses during generation of a report, if the `value` for the `QuestionAnswerStore` entity is `null`, an `ArrayIndexOutOfBoundsException`  is thrown and the resulting row is skipped in the raw data report.

See this line:
https://github.com/akvo/akvo-flow/blob/v1.9.1/GAE/src/org/waterforpeople/mapping/dataexport/service/BulkDataServiceClient.java#L346

**Comment by muloem** [comment]
### Test Plan 

1. Find a survey containing responses with `null` `QuestionAnswerStore` entities.  

2. Generate a raw data report for this survey

3. Verify that the `SurveyInstance` entity connected to the `null` response is included in the list of generated rows in the report

**Comment by rumca** [comment]
I think this test plan passes - I found one QuestionAnswerStore entity with a null value on UAT, the report downloads with the expected 4 responses. Additionally I manually set a null value in the datastore and the report generated as expected.
