### ISSUE TITLE
Change font color on subtabs

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1451]
Currently the sub-tabs if not selected have a grey background and grey font. This color choice makes the tabs appear as disabled. Once hovered over the background changes to a darker grey and the font to white. A selected tab has white fonts and a black background.

![screen shot 2015-10-26 at 13 25 40](https://cloud.githubusercontent.com/assets/12456965/10728771/14d0aa1e-7be5-11e5-8e7b-bd361292c859.png)

Proposed solution is to change the font to white at all states of the tab. The different strength of grey background should be a strong enough indication to show the different states.

**Comment by janagombitova** [comment]
### Test Plan: 

1. Click on Devices - verify that the selected sub-tab is visually different than the non-selected ones. 
2. Verify that the font color of the non-selected sub-tabs has changed from grey to a different color and the non-selected tabs do not appear as if disabled. 
3. Hover over a non-selected tab and verify that the sub-tab's color changes upon hovering.
4. Select another sub-tab, verify that the color of the tab after being selected is consistent with the previously selected sub-tab. 
5. Repeat the steps for Data and Reports, and make sure the color is consistent throughout all main tabs and sub-tabs

**Comment by rumca** [comment]
Test plan passes as described.
