### ISSUE TITLE
Disable multi-select of different geoshapes under one question

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1455]
Currently when adding a geoshape question to a form, the user can decide to enable all three types of shapes. It is very rare that a partner would collect more shape types under one question, it makes the analysis of geoshapes more complicated, and with many GIS tools a question holding more shapes is impossible to import.

The solution is then to disable the option to add all three shapes to one question. When user adds a geoshape question to a form, she needs to choose which shape is to be collected. 

**Implications:** 
1. On the dashboard when defining a survey - geographic shape - change checkboxes to a radio button and a text before saying: 'Please select type of geographic shape:' 
2. On the app - There are two approaches here:
- We leave the app behaviour as it is, the user clicks on 'create shape', then he selects the shape via the top 'shape' icon (only one shape type is available) and proceeds to creating the shape. 
- Once the user clicks on the 'capture shape' button, the shape is already selected and the bottom bar with the options to add a point, delete, etc is already visible on the screen. This change means, that the user does not have to select the shape anymore - thus the function of the top 'shape' icon is un-needed and can be removed. This will leave us with only two icons in the top header: map and save.

**Comment by janagombitova** [comment]
@joycarpediem @jonase @Kiarii @ichinaski @mtwestra Can you please take a look at this proposed change? It is due to the work we are currently doing for the export geoshape functionality and I would like to know your opinion and check if we did not miss something? Thanks

**Comment by mtwestra** [comment]
@janagombitova:
1) the first (dashboard) change is fine
2) I don't think the second one is possible, because it is then impossible to add multiple shapes.

**Comment by ichinaski** [comment]
@mtwestra 

> I don't think the second one is possible, because it is then impossible to add multiple shapes.

As far as I understand, the purpose of the change is precisely to prevent more than one shape in one response.

From my point of view, the changes do make sense. Having a single shape per question seems very straightforward to me, and would get rid of some complexities currently present in this feature (selection issues, response incompatibilities across tools, etc).

**Comment by joycarpediem** [comment]
@mtwestra @janagombitova @ichinaski , yes the intention is to simplify . The ability to capture multiple shapes in one question is an edge case. If we do want to persist with it , we can just add a "Allow multiple" flag in the question description in the dashboard in which case the app user will have to use the "+" icon in the app.

**Comment by Kiarii** [comment]
I also feel that this would simplify things on both the Dashboard and app sides (i.e. if I am correct; In the Dashboard this corresponds to 'a' geoshape creation options not multiple shapes...)

**Comment by janagombitova** [comment]
So based on your comments, these are the points we need to decide on:
-  On the dashboard we change the shape type selection from checkboxes to radio buttons, which will enable the user to only define one exact shape per question.
- We need to decide - whether to provide the option 'Allow multiple shapes' - which will give the user the option to choose from all three shapes on the app and add them all (or 2 or 1) to the question.
- On the app side we change nothing - the user will always have to click on the 'add shape' icon in the top header (even if there is only one option) = same workflow as we currently have
- If we decide to allow only one shape per question (without the option to 'allow multiple shapes'), then we can consider simplifying the app, by removing the 'add shape' icon in the top header, and directly open to bottom bar (with the shape type, geoshape properties, add point, delete point, delete shape icons) 

@joycarpediem @jonase @ichinaski @mtwestra @Kiarii Can you please take a look at these points? Thanks

**Comment by joycarpediem** [comment]
@janagombitova , ^^ looks fine, but i would not show the "add shape" button in the app if allow multiple is not selected for the question.

**Comment by janagombitova** [comment]
After talking with @joycarpediem and @muloem we decided to **take out** the option to allow multiple types of shapes and multiple shapes under one question. This is due to the fact that, (1) if the shapes are nested, GIS tools will not be able to separate them out and the user needs to have sufficient expertise to separate them.  can make that work. (2) The real life usage of plotting multiple shapes in a single question is very row and have not seen it happening in FLOW yet. 

What needs to be implemented is then: 
- On the dashboard we change the shape type selection from checkboxes to radio buttons, which will enable the user to only define one exact shape per question.

**Comment by janagombitova** [comment]
Secondly, we need to see how to handle backwards compatibility regarding the app communicating with old survey definitions that still have the flag "allow multiple" on. 

We have decided tho implement this change do to the unpracticality to upload an exported geoshape to a GIS tool. If an export holds multiple shapes, the user would have to do some extra transformations to make the file compatible with a GIS tool. This change will simplify the workflow for our user, but is not urgent in essence. Thus to properly address the backwards compatibility issue and other parts of this change (on the survey level and app), we have decided to postpone its implementation to the upcoming releases.

**Comment by janagombitova** [comment]
With the current implementation of geoshapes rendering in Data tab and Map tab, if the user created 2 shapes (same type or different types) under one question, only the first shape is rendered.
- created points first and then a line - only points are shown
- created two lines - only the first line is shown

**Comment by janagombitova** [comment]
When we were thinking with @joycarpediem how to deal with multiple shapes (A+B or A+A), while also making sure in most cases the user creates only one shape per question, the complexity of the implementation grew. 

**Why do we want to limit the current possibility to allow multiple shapes?** 
- the maps do not render the shapes properly (only render the 1st created shape in that answer), so we would need to support that for the few edge cases
- export and import into a GIS tool of multiple shapes is complex and needs further changes to the file by the user after exported from FLOW, 
- when collecting shapes, the user associates them with other questions, so if they want to collect multiple shapes of the same type (A+A), so they use RQGs where for each single shape they ask a following set of questions
- if users want to collect (A+B) currently they simply add 2 questions to their form
- validation of polygons (to check if the polygon has the minimum of 3 points) is very complex to implement if we continue allowing multiple
- we want to simplify the workflows for our users 

Collecting multiple shapes of different types (A+B) is in practice an edge use case. Furthermore, there is only a low number of cases where A+A was collected as well. After discussing we decided **not** to support collecting multiple shapes, both cases A+B and A+A. Here is our proposed implementation from the users perspective: 

#### On the survey level when editing/creating a survey
- change shape type selection to radio buttons, thus only one shape can be selected for a question

#### On the maps - in Map tab and in Data tab, and in Reports 
- no change needed 

#### On the app
- the question holds the name of the selected geoshape type (as @ichinaski  proposed in https://github.com/akvo/akvo-flow-mobile/issues/366)
- once user clicks on "Create geographic shape" the geoshape screen opens
- the user has selected the shape type in the survey already, so the shape type selector icon in the top header is removed, as it does not provide any value 
- the lower bar with the shape creation icons is opened by default and the shape type is indicated on the left in the lower bar
- this change will enable polygon validation which is covered here https://github.com/akvo/akvo-flow-mobile/issues/366

#### Outstanding questions
**What about the fact that we are removing pieces of the functionality?**
At this point of time, we learned that collecting multiple shapes in relation to one question is a very edge case. If the user requests to support back multiple shapes and the current use of repeated question groups, or creating multiple questions for different shapes does not support the request, we will look into the implementation. 

**Backwards compatibility**
As our partners are just learning how to use geoshapes and collect data with them, the chances for breaking something are low. However, we do need to cover cases when multiple shapes were collected in the past.

**Points**
It seems as if the only exception to this rule are points, because now if you collect multiple, they are shown on the map now as well. Will we apply the rule to points as well? 

@joycarpediem @ichinaski @mtwestra @jonase @Kiarii @muloem What do you think?

**Comment by muloem** [comment]
The issue of backwards compatibility should not be too problematic as we can simply make sure we render the shapes correctly on the relevant parts of the dashboard and the app.  It may be an issue for exporting and reimporting the geoshapes into an external tool but that will probably not happen and if it does we will have to handle through direct support.

As for the points, the "shape" is a point cloud as far as I understood so that should definitely enable gathering multiple points. As a side note, what we now call a geolocation is infact a single point geoshape.
