### ISSUE TITLE
Add two new permissions: View data and Edit data

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1460]
Currently no permissions cover viewing data and editing data. There are many cases, where not each user should have the right to especially edit collected data. As we have a detailed permission structure on the folder and form level - view, edit, delete, create, we should follow this structure also for collected data. Currently we have a permission only to Delete data. The idea at this point is to add **View** and **Edit** as well for collected data.

More 'conceptual cleaning' for Roles and Permissions will be tackled later in time, as there are a few inconsistencies and more open issues.

**Comment by akvotender** [comment]
Assigned to [Tender discussion #6133](http://flowhelp.akvo.org/discussions/problems/6133-new-permission-setting-view-only-role-needed-requested-by-lars).

**Comment by akvotender** [comment]
Assigned to [Tender discussion #6127](http://flowhelp.akvo.org/discussions/problems/6127-view-only-access-to-akvoflow).

**Comment by muloem** [comment]
### Test Plan

#### Pre-test prep

Ensure you have at least three different test users `AdminUser`, `ReadOnlyDataUser` and `EditDataUser`.  Create a monitoring survey with one of each question type and fill in a couple of responses in the registration form

#### Test 1: Add and remove view data and edit data permissions

1. Go to the users tab and define two new roles `ViewDataRole` and `EditDataRole`.  Each role has to have the `View Folder` and `View Form` permissions set.

2. For the `ViewDataRole` select the `View Data` permission 

3. For the `EditDataRole` select the `Edit Data` permission

4. Save the role definitions and verify that the roles have been created correctly and have the permissions also set correctly

#### Test 2: View data

1. Assign the `ViewDataRole` to the `ReadOnlyDataUser` and couple it to the folder containing the survey created in the pre-test prep steps

2. In a separate browser window login as this user and navigate to the inspect data tab and view the data for the survey.  The list of responses should have a link `View` next to them.

3. Click on the `View` link. The popup window should show the list of responses but it should not be possible to edit the responses

4. Browse the data points of the same survey on the monitoring page.  Ensure that it is only possible to view the data

#### Test 3: Edit data 

1. Assign the `EditDataRole` to the `EditDatauser` and couple it to the folder containing the survey created in the pre-test prep steps

2. In a separate browser window login as this user and navigate to the inspect data tab and list the data for the survey.  The list of responses should have a link `Edit` next to them.

3. Click on the `Edit` link. The popup window should show the list of responses. Edit one of the responses and verify that the edits are correctly saved

**Comment by rumca** [comment]
Test plans pass as described.

@muloem I know we want to improve the monitoring tab at some stage, so perhaps this has already been discussed - but I've just noticed that there's no way to edit responses on the Data > Monitoring > View Details pop up (even with a super admin user). It could perhaps be an idea to add the edit functionality to that tab as well as in the Inspect Data tab?

**Comment by janagombitova** [comment]
@rumca that is a good idea but we will be combining the Inspect data tab together with the Monitoring tab into one, where editing will be possible, if the user has that role. This is planned for January, so lets leave things as they are for now.
