### ISSUE TITLE
Fix scrolling on CartoDB maps

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1475]
Proposal: Disable scrolling on the Maps page **entirely**. Thus the header and footer will always be visible and the filter options will not disappear due to scrolling. When the user scrolls with the mouse over the map, map zooms in and out (as it currently does).

Limitation: This solution does make the map smaller, especially when previewing in smaller screens. However the confusion regarding the scrolling seems as a more pressing issue.

**Comment by kymni** [comment]
@janagombitova would it make more sense if the filters stuck to the header and we disabled scrolling to zoom instead of disabling scrolling on the entire page?

**Comment by janagombitova** [comment]
@kymni After our call I found this issue - I think it is related https://github.com/akvo/akvo-flow/issues/1283

**Comment by gabemart** [comment]
@janagombitova @kymni Yes, I think this is the same issue as #1283 let's move discussion there

**Comment by rumca** [comment]
covered in other issue, closing this
