### ISSUE TITLE
Report generation always includes repeat column

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1476]
In the current report generation, we always include the `Repeat no` column that reflects the iterations in a repeat question group.  However, in some surveys that don't contain repeat question groups this is not necessary and confuses the user as they have to include an iteration number that has nothing to do with their survey.  The proposal is to remove this column from reports based on surveys that do not contain repeat groups.

**Comment by janagombitova** [comment]
Before making any more structural changes, we need to create a overarching strategy on how to deal with data exports as every change we make not only changes the way users see the sheet, but also their own set up for importing data. Moving this discussion to Product design repository as I would like us to go through a proper Discovery on how to deal with raw data reports
