### ISSUE TITLE
Change in data privacy setting is not reflected on the map

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1479]
Data points for surveys containing geotagged data are shown on the map if the survey is indicated as `PUBLIC`.  However when a user switches this setting to `PRIVATE` they expect that the data points are no longer shown on the map but this is not the case.  The same is observed if the switch is made form `PRIVATE` to `PUBLIC`.  The data points are not visible.  We need to make this switch automatic.

**Comment by stellanl** [comment]
Until we get this done, there is a script:
 akvo-flow/scripts/data/org/akvo/gae/remoteapi/HidePrivateSurveyData.java
