### ISSUE TITLE
Allow to add and specify 'unit' for number questions

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1483]
For example: the costs per l of water -> they enter 0,58 -> on the dashboard this will appear: 0,58  $/L
The Admin can indicate this unit when entering the question on the dashboard via symbols like €,$, %, but also indicators that will be measured with Caddisfly in the future like conductivity, temperature etc. The 'unit' will then be visible on the app next to the input field, on the dashboard and in the reports. 

The feature will act as another flag/setting on the question, which can or does not have to be enabled.

**Comment by akvotender** [comment]
Assigned to [Tender discussion #6187](http://flowhelp.akvo.org/discussions/problems/6187-marking-of-units-of-measurements-to-appear-on-the-dashboard).

**Comment by iperdomo** [comment]
@janagombitova some forms already have unit of measure in the question, e.g. _"How much was the production this year (Tons)?"_

**Comment by joycarpediem** [comment]
Using of the unit in the question text works quite well and is pretty widely used. This way we also bypass the issues of pre/postfix depending on the symbol. 
Also while data cleaning , some may mess with the symbols if it is at the cell level.
IMHO, what we have right now works well.

**Comment by janagombitova** [comment]
@joycarpediem  Thanks for sharing. I will share this with the users requesting it and closing this issue
