### ISSUE TITLE
Export reports tab - fix the dropdown selection so it does not disappear with scrolling

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1484]
In the Export reports tab the user has to first select a folder > survey > form before he decides which report to generate. If he scrolls down the page to the last report type, he does not see the selected survey in the dropdown anymore, and thus looses overview. 

<img width="1127" alt="screen shot 2015-11-12 at 12 33 36" src="https://cloud.githubusercontent.com/assets/12456965/11117386/a1a509ba-8939-11e5-998f-105a6421c076.png">

**Comment by gabemart** [comment]
Solution: affix the dropdown menus to the top of the container so that they are always visible

![image](https://cloud.githubusercontent.com/assets/2589977/11117945/fc3ae6fa-8935-11e5-8965-fcbaea0ab1c4.png)

**Comment by gabemart** [comment]
#Test plan

1) Navigate to Reports > Export Reports

2) Scroll to the bottom of the page

3) Verify that the dropdown menus allowing the selection of a form are still visible

4) Verify the dropdown menus are still functional

**Comment by muloem** [comment]
@gabemart could these changes have resulted in the whitespace in screenshots below?  

* Between selection menu and the gray box.
<img width="1260" alt="screen shot 2015-11-13 at 15 40 30" src="https://cloud.githubusercontent.com/assets/533336/11148457/24763114-8a1d-11e5-9eeb-24cc4dbe47f8.png">



* Between the two gray boxes.
<img width="1267" alt="screen shot 2015-11-13 at 15 40 46" src="https://cloud.githubusercontent.com/assets/533336/11148463/2e7980ee-8a1d-11e5-9f44-be7669fbf8b4.png">

**Comment by gabemart** [comment]
@muloem Nice catch :+1 should be fixed now
