### ISSUE TITLE
Handle date questions correctly in raw data imports

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow#1486]
Currently there's a regression where we send back the date formatted string instead of the timestamp

**Comment by jonase** [comment]
## Test Plan

* Create a form with some date questions and create a few responses
* Export the form for data cleaning
* Change some of the instances so they will be part of data cleaning
* Upload the report
* Check the google app engine datastore and make sure that the uploaded date question values contain timestamps and not date formatted strings.

**Comment by muloem** [comment]
@jonase I would even extend the test plan to include checking that the dates changed in the report are the correct dates shown in responses.

**Comment by jonase** [comment]
@muloem Agreed. I will add this.

**Comment by rumca** [comment]
Test plan passes as described :+1:
