### ISSUE TITLE
Change footer links to new Support page

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1493]
Related to the changes Geert made in support we need to redirect the links on the footer in the dashboard: **Support** and **Documentation and User guides**. Both need to direct the user to this page: http://flowsupport.akvo.org/

**Comment by jonase** [comment]
## Testplan

The "Support" and "Documentation and User Guides" links in the footer should point to  http://flowsupport.akvo.org/ for both the public and the admin pages.

**Comment by rumca** [comment]
test plan passes as described :+1:
