### ISSUE TITLE
Geoshape - expand the rendering to support 'line' and 'points'

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1495]
Currently we only support rendering of polygons in the new geoshape feature. This following step will involve supporting also 'lines' and 'points' when viewing the geoshapes in the Map tab and both sub-tabs of the Data tab (Inspect data and Monitoring)

**Comment by kymni** [comment]
## Test Plan
* Create a "geoshape" question and on the survey collect multi-points, lines, and polygon on a survey then submit
* Inspect the collected data on inspect data tab, monitoring tab, and cartodb map
  * Objects should be drawn on the map
* On cartodb map, click on a point with at least one "geoshape" answer then click on show on map
 * All object types should be projected on the main map

**Comment by rumca** [comment]
Test plan passes as described.

@kymni @janagombitova would it be desirable to support displaying shapes which have multiple features? For example I have submitted some responses which have lines, areas and points as part of their shape. We currently just display one part of that (the points). Please disregard if this is already on the road map or not required :+1:

**Comment by jonase** [comment]
@rumca I think this is actually easy to support in our maps but there were some concerns about exporting data to external systems which only support one kind of feature/column. @joycarpediem might know more details.

**Comment by kymni** [comment]
@rumca @jonase displaying multiple features on a map is indeed possible. Adding support for this

**Comment by janagombitova** [comment]
@rumca Indeed, as @jonase pointed out the entire discussion on if we do support multiple shapes in one answer or not is related to exporting the geoshapes. 

@joycarpediem what is your opinion on this? Do we need to change the entire workflow and not enable anymore multiple shapes in one answer (of the same type of geoshapes or different types)? Or can the GIS people when exporting our shapes to this change themselves?

**Comment by joycarpediem** [comment]
Well there are two aspects to this. One functional and one technical
Functional: The collection of multiple geoshapes against one question is an inherently complex exercise. Also usage wise there seems to be hardly any usecase where organisations may want to do so. 

Technical: In general nested shapes are difficult to work with. Some GIS tools may require additional formatting of data.

IMHO, we can do away with multi shape capture per question.
I think this is a good time to do it as geoshapes are sporadically used right now and we'll not run into too much backward compatibility issues.

**Comment by rumca** [comment]
As per discussion this morning I will open a new issue to address the change in workflow for a future release - making it so that only one feature type/shape can be used per response. We will leave the display functionality as is for now.

**Comment by janagombitova** [comment]
@rumca  We already have an issue: https://github.com/akvo/akvo-flow/issues/1455

**Comment by rumca** [comment]
excellent :+1:
