### ISSUE TITLE
Add roles/permissions for cascades and assignments

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1497]
At the moment, cascades and assignments are not covered by roles and permissions, and this has caused some problems in the field. 

The idea is to create permissions for cascades and assignments in two phases:
1) first introduce binary permissions: access / no access
2) later, introduce full detailed permissions: create / read / edit / delete

The reason is that we can first create the binary permission by simply hiding the whole tab, which is a simple operation.The second phase will need more detailed implementation, which will take longer. 

The expectation is that the second phase will be done at the same time as the general refactor.

Bij default, a new user has all the permissions.

**Comment by janagombitova** [comment]
@muloem I was thinking of how to name these new permissions. What do you think of: `Manage assignments` and `Manage cascade resources`

**Comment by muloem** [comment]
@janagombitova More or less what I was thinking of.. add something about devices to the first one perhaps?

**Comment by muloem** [comment]
### Test Plan 

#### Pre-test prep

Ensure you have at least three users `AdminUser`, `DevicesUser` and `CascadesUser`.  Also check that you have at least one cascade resource listed and a folder containing a survey with some sample forms and questions.

#### Test 1: Define roles

1. Working as the `AdminUser`, under the *Users > Roles and permissions* tab define a new role `DeviceManager` and assign the permissions `Manage Devices and Assignments`, `View Folder` and `View Survey` to this role

2. Additionally create a role `CascadeResourcesEditor` and assign the permission `Manage Cascade Resources`, `View Folder` and `View Survey` to this role

3. Ensure that these roles are correctly created and shown in the list

4. Assign the role `DeviceManager` to `DevicesUser` and the role `CascadeResourcesEditor` to the `CascadesUser`


#### Test 2: Check Devices and Assignments. 

1. Login as `DevicesUser` and ensure that you are able to see the *Devices* tab and are able to see the list of devices and assignments, as well as create an assignment but only restricted to surveys in the folder within which you have access.

2. Go to the *Data* tab and cross check that the *Cascade Resources* sub tab is **not** visible.


#### Test 3: Cascade resources

1. Login as the `CascadesUser` and verify that you are able to go to the *Data > Cascade Resources* tab.  Here you should be able to see and correctly edit the cascade resources shown

2. Verify that you can **not** see the *Devices* tab

**Comment by akvotender** [comment]
Requested by WHH today.

**Comment by rumca** [comment]
Test plan passes as described :+1: 

@muloem @janagombitova perhaps this has already been discussed - but it is it worth adding some sort of functionality to assign roles which are not linked to specific paths? For example in this case the ``Manage Cascade Resources`` is basically independent and unrelated to the folder path you assign the role to.

**Comment by janagombitova** [comment]
@rumca yes we have been talking about that and came to the conclusion that it needs a proper redesign. For now we will be just fixing up the way how things work and later with the refactor we will look into the design as well.
