### ISSUE TITLE
Date type not rendering correctly on overlay for Cartodb maps

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1512]
related to #571 except with Cartodb and not mapbox

Date question responses are currently appearing as below:

![screen shot 2015-12-01 at 09 47 34](https://cloud.githubusercontent.com/assets/3003031/11497405/b7324c94-9810-11e5-8fb2-12e3bc75ba46.png)

cc @jonase

**Comment by janagombitova** [comment]
Display the date in the same way as the Submission date is.

Once we fix the issues around displaying dates in the dashboard in general we will make it all consistent

**Comment by rumca** [comment]
@kymni there's something not quite right with the date display code, it's currently rendering blanks were there should be dates:

![screen shot 2016-01-03 at 23 58 15](https://cloud.githubusercontent.com/assets/3003031/12081630/cb5d35c8-b276-11e5-9d64-070fdee49ea9.png)

**Comment by kymni** [comment]
@rumca issue should be [fixed now](https://github.com/akvo/akvo-flow/pull/1546)

**Comment by rumca** [comment]
Date now appearing as expected :+1:
