### ISSUE TITLE
Use correct HTTP methods for data related permissions

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1516]
While introducing the new permissions in release/1.9.3, the HTTP method for respective permissions is set wrongly.  See: 
https://github.com/akvo/akvo-flow/blob/develop/GAE/src/com/gallatinsystems/user/domain/Permission.java#L43-L45

**Comment by muloem** [comment]
### Test Plan

#### Pre test prep 

Create a role with combined `View data` and `Delete Data` permissions, and assign the role to a `ViewDeleteUser`. Create an alternative role with only `Delete Data` permissions and assign this role to a `DeleteUser`.


#### Test 1: Delete Data
1. Using the `ViewDeleteUser` delete some test data on the *Inspect data* tab.  The deletion should succeed.

2. Using the `DeleteDataUser` delete some test data and cross check that the deletion succeeded.

**Comment by rumca** [comment]
Test plan passes as described.
