### ISSUE TITLE
Disable manual input of bacode

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1522]
At this moment the user can either scan in or manually input the barcode in the text field. To assure data quality and no mistakes in the barcodes, we can add a flag on the question type setting to 'Disable manual entry of barcode'. 

On the app there will be no text field available and the user will be able only to add in a scan using a device. There are no further "user facing" implications of this change.

**Comment by janagombitova** [comment]
Partner request - background information

**Comment by ichinaski** [comment]
> On the app there will be no text field available and the user will be able only to add in a scan using a device

Current approach in similar features (i.e. geo, external sources) is to *disable* the text field, but still display it, for this is where the result will be filled in after the scan.

**Comment by janagombitova** [comment]
@ichinaski I see. I did not realise that. Basically, lets reuse the patters we have in the app at this moment. This issue is however not a high priority right now.

**Comment by rumca** [comment]
assuming the test plan for this is simply the presence of the "disable manual editing" checkbox in the options for barcode questions - then this passes as expected
