### ISSUE TITLE
Geotagging in photos 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1527]
All details on the implementation of the geotag and decisions can be found here: https://github.com/akvo/akvo-product-design/issues/74

For the first implementation we will show the geotag in the Data tab.

Providing this information in reports and visualising the location of the photos in the maps, will be dealt with in the following implementations. https://github.com/akvo/akvo-product-design/issues/74

**Comment by ichinaski** [comment]
**Test plan:**

Test plan:

* Create a monitoing form containing media questions (image, video)

* Provide a response from both old and new versions of the app (i.e. v2.2.3.1 and v2.2.4)

* Ensure image/video URLs are visualized correctly in the inspect data tab. They should not be editable.

* Monitoring tab should work the same way.

* Check data exports. Format should be the same as usual, only containing the URL for now.

**Comment by rumca** [comment]
The discussed URL issues in reports seem to be fixed (for all but one response - which could just be down to something funky going on before the fix).

I'm going to redo the reports testing just to double check and then will close this issue.

**Comment by rumca** [comment]
The fixes for video URLs on monitoring & inspect data tab look good. As do the fixes for loading images on the maps tab, and displaying the URLs correctly instead of JSON strings.

**Comment by rumca** [comment]
temporarily closing this one (until we tag v1.9.6)

**Comment by janagombitova** [comment]
Based on @ichinaski discussion with Loic - https://github.com/akvo/akvo-product-design/issues/74#issuecomment-209368877 we will add the location information under the media link in the dashboard. 

This information needs to be shown in the: 
- Inspect data tab
- Monitoring tab
- Maps (current and CartoDB) 

**The outstanding questions are:**
- How to add the location information in raw data reports? (should a new issue be created to handle reports?) 
   - Inigo mentions in the above linked comment, to add the location into the same cell as the media link. 
   - after speaking with some of our users, the preferred option is to add one extra column following the media column that will hold the location information, to not change (and complicate) the way photos are access via the reports  
   - What shall we implement? 
   - Will we allow editing via data cleaning? 
- Will we allow editing in the Inspect data tab? 

@ichinaski @muloem what do you think? 

Following implementation steps will be to (1) calculate and show the distance between the media and the data point location and (2) add pins on the CartoDB maps once previewing a specific data point. These steps are not n1 priority and thus will be tackled later on in time. https://github.com/akvo/akvo-product-design/issues/141

**Comment by ichinaski** [comment]
According to the latest requirements, this is the result of adding lat/lon information to inspect data tab and reports:

![latlon_dash](https://cloud.githubusercontent.com/assets/1754343/15046200/d890a018-12de-11e6-9ed0-e485e3a5977e.png)
![latlon_reports](https://cloud.githubusercontent.com/assets/1754343/15046201/d893cd38-12de-11e6-9834-925c076c447e.png)

@janagombitova @muloem can you confirm this is what is needed?

**Comment by muloem** [comment]
@Ini regarding the inspect data tab yes this is what will be needed.  There reports presentation is not concluded so until we are clear what is the intended manner to use this data in reports, lets leave that part for a follow up release/issue.

**Comment by ichinaski** [comment]
**Test plan (v1.9.7):**

* Submit geotagged data to a form (monitoring enabled).
* Ensure lat/lon information is shown in:
    * Inspect data tab
    * Monitoring tab
* Reports are not affected (lat/lon **not** shown)

**Comment by rumca** [comment]
Test plan now passes as described
