### ISSUE TITLE
Hide Data Cleaning tab if permission is not given

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1528]
The current pattern in the FLOW dashboard is, if the permission is not given you to not see the action or the full tab. However, this does not apply for Data cleaning. If you do not have this permission assigned, you can still see the Data cleaning sub tab, but you cannot select a survey in the dropdown. Functionality with the permission works well, but from the UX point of view it is not necessary for the user to see something he cannot use. 

The solution is to hide the data cleaning sub-tab, if the permission is not given to the user.

**Comment by stellanl** [comment]
I am really bad at the dashboard frontend, so this could take a while

**Comment by stellanl** [comment]
I am really bad at the dashboard frontend, so this could take a while

**Comment by stellanl** [comment]
This tests ok now, apart from some entanglement with Caddisfly stuff.

**Comment by janagombitova** [comment]
Test plan missing. But passes expectations > no data cleaning tab showing 👍
