### ISSUE TITLE
Dual SIM devices have two IMEI numbers

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#153]
Dual SIM devices have two IMEI numbers, depending on which SIM is active. This needs to be investigated:

1) can both IMEI codes be accessed by Android?
2) if a user switches sims, the phone will potentially not be recognised. How to handle that scenario?

**Comment by janagombitova** [comment]
We now use Android ID for identification of devices. Closing issue for now and we will reopen if still relevant.
