### ISSUE TITLE
Re-ingesting a SurveyInstance sets the wrong creationDateTime

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow#1530]
Code refactor at https://github.com/akvo/akvo-flow/commit/b0c432b2b1f3e9bb4b39e57988d6e4133d88d314 introduced a subtle regression on existing SurveyInstances being re-ingested:

```java
if (existing != null) {
    si.setKey(existing.getKey());
    si.setCreatedDateTime(existing.getCollectionDate());
    isNew = false;
}
```

If the entity is successfully fetched from the data store, we need to replicate the `createdDateTime`, instead of the `collectionDate`.

**Comment by rumca** [comment]
@ichinaski is there something I can do to test this, or is the fact that the code has been updated as intended sufficient to close the issue?

**Comment by jonase** [comment]
@rumca I think this one is difficult to test from a users perspective
