### ISSUE TITLE
CartoDB maps - render cascade resources pipe separated 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1531]
When viewing the submitted data for a data point in the map tab on the instances running CartoDB, the cascade answer is shown as a string. To provide a consistent experience for the user, we need to render the cascade answers in the same way as in the Data tab - pipe separated

![screen shot 2015-12-16 at 11 27 24](https://cloud.githubusercontent.com/assets/12456965/11838764/57b68e76-a3e9-11e5-87dd-44d817debe92.png)
![screen shot 2015-12-16 at 11 28 06](https://cloud.githubusercontent.com/assets/12456965/11838765/58e4deba-a3e9-11e5-8207-95c1b198cbfe.png)

**Comment by kymni** [comment]
issue resolved on branch "issue/1531-cartodb-cascade-pipe"

**Comment by rumca** [comment]
@jonase @kymni does it make sense to do this for the options codes in this release too? Currently looks like:

![screen shot 2016-01-03 at 23 44 41](https://cloud.githubusercontent.com/assets/3003031/12081565/3cc77338-b275-11e5-8ccc-fa27936a7ed8.png)

**Comment by kymni** [comment]
@rumca issue [fixed](https://github.com/akvo/akvo-flow/pull/1546)

**Comment by rumca** [comment]
options now appearing as expected (same format as cascades)
