### ISSUE TITLE
Data cleaning NUMBER type can result in datastore values in scientific notation 

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow#1534]
If the number is large enough we currently import it in scientific notation: `1.234E+8`. We need to parse numbers correctly using [org.apache.poi.ss.usermodel.DataFormatter](https://poi.apache.org/apidocs/org/apache/poi/ss/usermodel/DataFormatter.html)

**Comment by jonase** [comment]
## Test Plan

1. Create a form of type `NUMBER`.
2. Submit a few responses with varying numeric size
3. Export a report. Some of the values will be displayed in scientific notation
4. Clear the md5 hash column in order to reimport all responses
5. Import the excel file via the `Data Cleaning` tab.
6. Check the responses in the GAE datastore (Kind: `QuestionAnswerStore`, Sort by `lastUpdateDateTime`) and make sure that none of them are in scientific notation.

**Comment by rumca** [comment]
Test plan passes as described
