### ISSUE TITLE
Migrate to using a JavaScript toolchain

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-flow#154]
To remove Ruby dependency and to leverage JS tools migrate to Grunt.js (http://gruntjs.com) instead of the Rake pipeline we currently use.

Example setups
https://github.com/trek/ember-todos-with-build-tools-tests-and-other-modern-conveniences
https://github.com/akvo/akvo-flow/tree/experiment/grunt/Public

**Comment by muloem** [comment]
We can close this as the build system will be restructured but in a new issue.
