### ISSUE TITLE
Ignore blank last cell in raw data reports

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1553]
In the raw data reports used for data cleaning, excel seems to add a blank cell in the header row of the last (*hash*) column of the report.  This results in the error `The header "" can not be imported` during raw data import. We can simply ignore this header if we know that its the hash column. So we need to modify the report import to correctly identify the hash column

**Comment by akvotender** [comment]
Linked to the Issue of Jennie (SNV)

**Comment by muloem** [comment]
### Test Plan

1. Export a raw data file with test data from a survey

2. In the header cell of the last column type in a space, then save the document and reimport it

3. The import should not fail i.e the *spreadsheet processed* message should appear

**Comment by rumca** [comment]
@muloem does this mean the header column that the hash is in, or the column to the right of that? Currently getting a ``Invalid RAW DATA file: blah.xlsx - Errors: The header " " can not be imported`` when I add blank spaces to the hash column and also the one to the right.

**Comment by muloem** [comment]
@rumca my mistake. I hadn't yet deployed the latest version to FLOW services. please recheck. thanks!

**Comment by rumca** [comment]
yep works as intended now :+1:
