### ISSUE TITLE
Displaying signature responses on cartodb point overlays

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#1560]
re: discussion on #1453 

Currently we do not display the signature responses for a survey when a user clicks on a datapoint with cartodb, instead there's a blank space where it should be. Suspected cause is currently: "hitting some cartodb sql-api size limits due to the big payload (due to the base64 encoded signature image)"

**Comment by jonase** [comment]
This can be resolved by increasing the `large_client_header_buffers` for nginx to (for example):

       large_client_header_buffers 16 32k;

**Comment by kymni** [comment]
@jonase would the fix automatically apply or would the consumer have to be re-run?

**Comment by rumca** [comment]
I saw some slightly weird behaviour were none of the fields were populating in the overlay when a signature question was present. For example:

![screen shot 2016-02-26 at 12 53 22](https://cloud.githubusercontent.com/assets/3003031/13352842/fa19346c-dc87-11e5-8221-1e73aaf50279.png)

However after re-uploading the data everything seems to work as expected (perhaps a consumer issue or something?). Will keep an eye out in case this occurs again - but closing the issue for now :+1:
