### ISSUE TITLE
Displaying drone imagery in FLOW

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#1562]
As part of the palm oil project we are collecting imagery via drones. 
We need to display this imagery superimposed on base tile layer in FLOW.

Strategy:
Map box is one of our current base tile provider.
It also allows geotiffs to be uploaded and displayed as part of the base tiles. 

We will add an additional option in the base map selector in FLOW maps which will have Drone Layers as an option.

Currently each instance will be tied to a particular drone layer via the mapid provided in the configuration.
The layer will not be displayed if the mapid  is not provided in the configuration.

**Comment by janagombitova** [comment]
@joycarpediem and @jonase Can we consider this a closed issue for now and open a new one once we scale up the use of drone imagery?

**Comment by jonase** [comment]
@janagombitova Let's wait until it's properly part of a release. Right now it's only deployed to that one instance.

**Comment by muloem** [comment]
### Test Plan 
**Pre-test prep:** Ensure the instance is deployed with drone imagery configuration enabled

1. Go to the maps tab 

2. Check that its possible to select drone layer as one of the layer options

**Comment by muloem** [comment]
@janagombitova updating this issue and merging the code into the main branch for the next release because for the last few deployments I have had to treat the drone imagery instance as a special case and it seems appropriate to include this in develop to save on that effort.

**Comment by janagombitova** [comment]
@muloem Ok, but will this still mean that the drone layer is only available for the particular instance?

**Comment by muloem** [comment]
Exactly.

**Comment by janagombitova** [comment]
@muloem do not know how to test this one, besides checking that the option to select Drone layer is not available on UAT1 maps. So it is up to you to close this one ;)

**Comment by muloem** [comment]
Closing this one. Its visible depending on configuration.
