### ISSUE TITLE
Show submissions with geoshapes but without data point location on the map tab

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1563]
Currently on the Map tab we only show form submissions that have a geolocation question as a data point location. This means that the data points are rendered on the map once the user selects the form. By clicking on one point the user sees in the side bar the submitted answers and geoshapes (are shown in a small map, with Hide and Show on main map button and with automatically calculated values). 

**Problem** 
But there are cases when you collect geoshapes, but your form does not have the data point location in it. In this case the shapes cannot be previewed in the Map tab, only in the Data tabs. 

**Situations**
- if the form holds a data point question - show the point on the map > current behaviour - OK
- if the form does not hold data point location but has one geoshape question 
- if the form does not hold the data point location question but has multiple geoshape questions 

With Joy we came up with these 3 suggestions on how to solve this is from the user point of view: 

**A. Create a point marker taken from the 1st geoshape**
- after the user selects a form that does not hold a data point location question, but has geoshapes in it, points will appear on the map
- this point will be taken from the 1st collected geoshape (first geoshape question in the form) and used as a point marker on the map
- once the user clicks on this point marker, the side bar opens and shows the answers and shapes (small map, hide + show on map button, automatically calculated info) as currently. 
  This solution recreates the same workflow as we have currently in the FLOW maps 

**B. Render 1st shape instead or points**
- if the form does not hold data point location but has one geoshape question > render the shape directly on the map and in the side bar use the current workflow (with the small map + show and hide shape on the map button, where the Hide button is on by default) 
- if the form does not hold the data point location question but has multiple geoshape question > render the first geoshape question directly on the map, in the side bar the current behaviour, thus the user can the select which geoshape question he wants to have rendered on the map
  - in this case the first geoshape question will act the an 'anchor point' for the user, as data points currently work
  - by clicking on the geoshape, the side bar opens with showing the answers in the submitted form
  - all geoshape questions have the small map, hide + show on the main map button, automatically calculated values
  - the first geoshape, which is rendered on the map as an 'anchoring point' will have the Hide from main map turned on - however, if the users clicks on Hide then there is not indication on the map anymore 

**C. Mandatory to have data point location** 
We have been talking about making some settings for data points mandatory for all forms (monitoring and non monitoring) as data point name. In relation to the above mentioned problem, we can make the data point location also a mandatory item which is collected with each submission. 

All of three options bring more questions on use cases that do not fit and how which I did not note down not to overwhelm you. I would prefer if we decide for a solution, which involves as least changes as possible. @jonase @muloem @mtwestra @joycarpediem @loicsans @Kiarii What do you think? How should we solve this? Do you have another alternative in mind? What technical changes does this imply?

**Comment by jonase** [comment]
The good thing is that Cartodb supports both geoshapes and geopoints. I.e. the "cartodbfied"[1] column can be both shapes and points. However, Cartodb does not currently support more than one "cartodbfied" column. That means that for a given form we can not map two columns. I do not think you can have different kinds of geometries in one column either. (I could be wrong here, but at least PostGIS does not support that AFAIK). That means that we can not have one `data_point` table where we collect all the data points.

In general, the concept in FLOW of a data point is quite closely tied to a geolocation (as seen by the properties `latitude` & `longitude` in GAE data store.

@iperdomo @mtwestra 
From a technical point of view my initial thought on how to achieve this would be a something like a hybrid model between what we have now (which looks like raw data reports, with it's known limitations) and https://github.com/akvo/akvo-product-design/issues/130#issuecomment-168580284. The idea would be to create dedicated cartodbfied "data point" tables for each question of type `GEO` and `GEOSHAPE` and join this with the response table when the user clicks on a point, line or shape.

[1]: A cartodbfied column is a column in cartodb that contains geo location (or geo shape)  data that can be efficiently map (think point clustering and rendering 100000+ points on the map)

**Comment by janagombitova** [comment]
Closing this issue for now and will reopen is the need arises.
