### ISSUE TITLE
Add Bahasa/Indonesian to dashboard 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1566]
Satya is adding the translations for both the dashboard and the app for Bahasa. Once he is finished and the strings are reviewed by Aulia and Anna-Marthe add them to FLOW.

**Comment by janagombitova** [comment]
Translations are ready in Transifex for both the app and dashboard

**Comment by janagombitova** [comment]
Name to be used in the language selector: "Bahasa Indonesia"

**Comment by rumca** [comment]
moving to 1.9.6, we'll add once loading issues addressed

**Comment by rumca** [comment]
### Test Plan 

1. Load dashboard
2. Select Bahasa Indonesia
3. Check all elements translated

**Comment by rumca** [comment]
test plan passes as described
