### ISSUE TITLE
Data editing issue in charts

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#1567]
Steps:
Edit an option question in the edit data popup .
Go to the Reports--> Charts and generate a chart for this question

Issue:
The changed value appears as a json string.

Example:
icco.akvoflow.org-->Cambodia-->Akvo-->1st Survey --->BaseForm--> Age

**Comment by muloem** [comment]
@joycarpediem I am not sure why this happened since chart generation was also implemented as part of the codes for options changes.  I have rerun the question summary builder and the chart looks fine.  We can leave this open for now to see whether it reoccurs and whats the cause.

**Comment by joycarpediem** [comment]
2 other cases when this was noticed while uploading data via spreadsheets

1. It it is an option question and part of data point name , then that part of the display name is shown as json in the raw data

2. If we have an option question with "allow other" and upload data against it, then a json is displayed in the data edit popup. This option question was also part of a repeat group.

**Comment by rumca** [comment]
As requested, I've went through and tried to reproduce the issues mentioned above.

The first one is definitely an issue. The chart appears fine on first submission of data, but once it's been edited via the inspect data tab, we get results such as the below:

![screen shot 2016-01-21 at 13 32 32](https://cloud.githubusercontent.com/assets/3003031/12485096/21b84494-c055-11e5-9bcf-079cc57ee09e.png)

With regards to the two spreadsheet issues. The first one, I can't replicate - when I download a raw data report for an option question as described I see the below:

![screen shot 2016-01-21 at 15 37 15](https://cloud.githubusercontent.com/assets/3003031/12485184/905a5aea-c055-11e5-90c1-a4ec9a993091.png)

(I've also performed some data cleaning with this, changing the value of "OTHER" and I can't seem to get JSON to appear in the display name field of the raw data report.)

The second mentioned issue, I can't replicate at all either. When I submit some data against an option question which has "allow other" and is part of a repeatable group, the below is what I see on the edit data popup:

![screen shot 2016-01-21 at 15 51 47](https://cloud.githubusercontent.com/assets/3003031/12485639/0cb0e2f2-c057-11e5-9815-0c48d8ec5b27.png)

**Comment by rumca** [comment]
@joycarpediem actually, I think I've replicated what you mentioned here:

>It it is an option question and part of data point name, then that part of the display name is shown as json in the raw data

![screen shot 2016-01-21 at 15 57 53](https://cloud.githubusercontent.com/assets/3003031/12485904/3b387512-c058-11e5-96f0-5c551e1ba696.png)

This only occurs when it's a repeat question group which has an option question marked as a display name. As far as I am aware we don't support RQGs being set to the display name? 

@muloem perhaps we should just exclude that field from the report if theres more than one iteration.

**Comment by janagombitova** [comment]
@muloem and @rumca and @joycarpediem If I remember properly, we agreed not to allow to create a data point name from a question within a repeated question group. Considering this is still possible, we need to remove that option once the group is set to be repeated. Would this solve the issue in the spreadsheet?

**Comment by rumca** [comment]
@janagombitova yep that was the decision, the data point name does not appear in the app - any repeatable question group questions which have the ``use as data point name`` flag selected always produce an "Unnamed data point" response. However we still see the constructed name in the raw data report. 

I think your solution makes the most sense :+1:

**Comment by janagombitova** [comment]
I am not sure if this is related or if it should be another issue, but if you have an option question and you edit the answer in the dashboard in the Data tab, the charts display a json value as well
