### ISSUE TITLE
Add 'terrain' baselayer to cartodb maps

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#1573]
Based on a partner request we decided to add the mapbox map layer to CartoDB maps as well besides the here maps layers. This map layer will be selectable and called "Terrain". The value of this layer is in its details, as it provides more data on villages, roads and towns in many remote areas of the world plus the layer is currently used on dashboards that are not integrated with CartoDB yet, thus we have the licence for it and our users are familiar with using it.

**Comment by janagombitova** [comment]
@kymni as we are aiming for the code freeze this week, can you see if you can fix this issue for this release? If not, it can be pushed to the following one as well. Thank you

**Comment by rumca** [comment]
Terrain layer present and selectable now.
