### ISSUE TITLE
Improved French translations for both the dashboard as the app

### ISSUE THREAD

**Issue by Geerts** [akvo/akvo-flow#1579]
Based on improvements delivered by Lars, file in the attachment. Added in Transifex.

[Request_for_adjustment_FLOW_french_version.docx](https://github.com/akvo/akvo-flow/files/124471/Request_for_adjustment_FLOW_french_version.docx)

**Comment by akvotender** [comment]
Linking the support request.

**Comment by rumca** [comment]
@muloem the issues that Lars raised in the doc file above still seem to be present in the release candidate, not sure if something else needs merged?

**Comment by rumca** [comment]
disregard above, redeployed with proper branch and everything looks correct :+1:
