### ISSUE TITLE
Graphical survey summary report gives a decimal in the summary sheet

### ISSUE THREAD

**Issue by Geerts** [akvo/akvo-flow#1580]
- Comprehensive report 
- Raw data tab displays no decimal at values
- Summary tab does display a decimal at the same value
- No decimals are allowed in the numbers question

Example in http://sig.akvoflow.org/admin/ , ID 20500916

**Comment by stellanl** [comment]
The answer data contains numbers both with and without a decimal point for the same question, e.g. "1" and "1.0". In the raw data any NUMBER answer gets forced to a number cell. The summary code, otoh, treats all answers as strings, so "1" and "1.0" gets tallied separately.

**Comment by stellanl** [comment]
Before, two cells were shown for the value 1:
![before](https://cloud.githubusercontent.com/assets/399534/14142865/89a71684-f688-11e5-8980-946e1bf1f90b.PNG)
and after:
![after](https://cloud.githubusercontent.com/assets/399534/14142933/d951e470-f688-11e5-8f14-ca017a85f114.PNG)

**Comment by stellanl** [comment]
## Test plan
 (you can skip steps 1-3 if the current results are still there): 
1. Assign form 42833002 of survey "akvoflowsandbox -> Stellans tests->Reporting test forms" to a device.
2. Submit one instance where the answer to "How much" is "1"
3. Submit one instance where the answer to "How much" is "1.0"
4. Order a comprehensive report.
5. Open the report in Excel/Libreoffice calc etc.
6. On the summary sheet, all answers either "1" and "1.0" should be reported as "1"

**Comment by rumca** [comment]
@stellanl do you know if the commits for this issue are part of release/1.9.6 (it looks like they are)? 

If they are, then something is going wrong with this fix. When I create a number question, submit some responses with and without .0 I see the below:

![screen shot 2016-04-07 at 22 08 48](https://cloud.githubusercontent.com/assets/3003031/14367000/8c4b7322-fd0d-11e5-91fe-15f0430200a1.png)

**Comment by stellanl** [comment]
Since that service runs in another place than the rest of FLOW, I guess we need to check that it was deployed

**Comment by stellanl** [comment]
Does not look like it was. Dated August 2015:
stellan@test2:~$ ls /var/akvo/flowexporter/jars/ -al
total 172648
drwxr-x--- 2 flowexporter root             4096 Aug 20  2015 .
drwxr-xr-x 8 flowexporter flowexporter     4096 May 27  2015 ..
lrwxrwxrwx 1 flowexporter flowexporter       58 Aug 20  2015 current.jar -> /var/akvo/flowexporter/jars/flowexporter-build292-test.j
ar
-rw-r--r-- 1 flowexporter flowexporter 88387528 Aug 20  2015 flowexporter-build291-test.jar
-rw-r--r-- 1 flowexporter flowexporter 88387547 Aug 20  2015 flowexporter-build292-test.jar

**Comment by rumca** [comment]
redeployment has indeed fixed the "issue", test plan now passes as described :+1:
