### ISSUE TITLE
An 'all folder' role overrules the permissions assigned to a specific folder

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1582]
A user has two roles assigned to him: 
1. view only role for all folders and surveys 
2. edit role for one specific folder 
However, he cannot edit in the specific folder. It seems as if the other 'read only' role in combination with all folders is overruling the edit role for a single folder. 

This issue was reported by Welthungerhilfe. As shown in the picture below, the user'e editing role did not work in the Malawi folder and he could only view. 
![image](https://cloud.githubusercontent.com/assets/12456965/13176634/03ab9a0c-d714-11e5-92c0-a60b23acf136.png)

**Comment by akvotender** [comment]
Link: https://akvoo.reamaze.com/admin/conversations/update-on-flow-roles-and-permissions-2
Assignee: Emmanuel Mulo

**Comment by janagombitova** [comment]
Link: https://akvoo.reamaze.com/admin/conversations/akvoflow-support-request-number-13838-from-jigmy-at-akvo-dot-org
Assignee: Jana Gombitova

**Comment by Nikki-Akvo** [comment]
Link: https://akvoo.reamaze.com/admin/conversations/access-dashboard
Assignee: Nikki Sloan

**Comment by kymni** [comment]
Same issue is affecting surveys, inspect data, and monitoring data tabs so fix implemented applies for them as well.

**Comment by janagombitova** [comment]
Checked the cases mentioned above in the linked support issues and they are nicely resolved. Well done 👍 

<img width="1245" alt="screen shot 2018-05-25 at 09 15 18" src="https://user-images.githubusercontent.com/12456965/40531310-480d979a-5ffc-11e8-9381-4eeab4787ce4.png">
