### ISSUE TITLE
Update device last contact time to the dashboard

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1585]
Since we disabled the location beacon (https://github.com/akvo/akvo-flow-mobile/issues/384), the device last contact date and time on the dashboard is also not updated.  We will now update this time based on the last contact of the device to check/download surveys from the dashboard

**Comment by muloem** [comment]
### Test Plan

1. Open the app on a device and cross check on the devices tab that the last contact date has been updated

2. Create and assign a survey to the device. After downloading the forms successfully verify that the last known contact date of the device has been updated

**Comment by rumca** [comment]
Test plan passes as described :+1:

**Comment by muloem** [comment]
We need to revisit this issue to handle cases for devices that are notifying or connecting to the dashboard for the first time.

**Comment by rumca** [comment]
If the test plan for this is simply loading the app on a device which hasn't previously connected to the dashboard, and checking the last contract time, then this works as intended :+1:
