### ISSUE TITLE
CartoDB maps - question order in side bar not the same as in survey definition

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1593]
When previewing data in the Maps that run CartoDB, the order of the questions in the form is not the same as they are defined in the survey. 

<img width="748" alt="screen shot 2016-03-07 at 10 20 42" src="https://cloud.githubusercontent.com/assets/12456965/13565097/4a095830-e44e-11e5-8a14-5d8ca6833762.png">

<img width="1016" alt="screen shot 2016-03-07 at 10 20 51" src="https://cloud.githubusercontent.com/assets/12456965/13565099/4ba68d7a-e44e-11e5-9316-e9fe9c5cf87a.png">

**Comment by janagombitova** [comment]
Link to issue in Reamaze: https://akvoo.reamaze.com/admin/conversations/map-display-order-of-fields

**Comment by kymni** [comment]
Questions order seems to be correct in relation to what is returned by the cartodb api. Possibility for difference highlighted in the issue could be changing the questions order after you've already published the form. 
A fix for this would be to change the questions endpoint to one that would pull the questions list directly from FLOW. That way we would always have the latest questions order

**Comment by kymni** [comment]
Questions list now pulled from dashboard and sorted based on order before being displayed on details panel. This is a temporary solution pending fixing of issue akvo/akvo-cartodb-consumer#19

**Comment by kymni** [comment]
## Test plan
Compare the order of questions in any survey with the order of question answers that appear on the CartoDB maps' details panel when a user clicks on a point. The order in both cases should be the same

**Comment by janagombitova** [comment]
@kymni Charles, is this the issue where you already have the implementation ready, just needed to fix some conflicts and needed review?

**Comment by kymni** [comment]
@janagombitova yes it is

**Comment by janagombitova** [comment]
Could not fully check this issue due to https://github.com/akvo/akvo-flow/issues/1694#issuecomment-228308449

On the map only one question group showed and not all. In that one group the question order was correct. Once we learn and enable to show all questions groups, I can continue to test out the question order

**Comment by janagombitova** [comment]
Not sure if any fixes were done to the above mentioned issue but the test plan passes as expected 👍

**Comment by kymni** [comment]
Questions in correct order but question groups not always in correct order

**Comment by janagombitova** [comment]
As far as I can tell the implementation passes the test plan 👍
