### ISSUE TITLE
Repeated question groups not properly shown in Map tab for non-CartoDB maps (estimated: 8)

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1596]
We currently display repeated question groups in the Data tab the same way as they are given to the user in the app - in sequence. We show the question group name with a '-' and the order of the repetition, example: "General information - 1". The questions and answers follow.

<img width="1000" alt="screen shot 2016-03-09 at 12 17 18" src="https://cloud.githubusercontent.com/assets/12456965/13633684/e59f1f3e-e5f0-11e5-900e-1f117bbf95cd.png">

However, we do not show these groups properly in the Map tab when user previews data as well. 
#### Current maps

In the Maps Tab, answers are listed by individual question answer, rather than in groups (i.e. all responses to 'Method of water quality testing' and then all responses to 'description of sampling point', instead of all group 1 answers and then all group 2 answers.) 
#### CartoDB map

The side bar here only shows one of the repetitions. We need to be able to show all the repetitions and in the correct order, as we do in the Inspect data tab. 

<img width="1000" alt="screen shot 2016-03-09 at 11 56 01" src="https://cloud.githubusercontent.com/assets/12456965/13633753/55e9660a-e5f1-11e5-98aa-535dfd0b168a.png">
(The repeated questions here are Text and Number and the two shown answers are the 3rd repetition for this submission)

**Comment by janagombitova** [comment]
Link: https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-11590-from-nikki-at-akvo-dot-org
     
 
  
 
 
    
 
 User email: nikki@akvo.org 
 Request Info 
Device:  Personal computer 
Browser:  Chrome 48.0.2564.116 
OS:  OS X 10.10.5 
IP Address:  121.45.193.100 
URL:  http://flowsupport.akvo.org/form 
 1- What can we help you with? 
I have a technical problem 
 2- What is the name of your dashboard? (xx.akvoflow.org) 
https://fiji-dws.akvoflow.org/admin/ 
 3- What is the name of your survey? 
EPS Water Quality Monitoring 
 4- What is the survey  ID, displayed inside the form? 
1520924 
 5- What did you expect to happen? 
in Maps tab for all repeat question groups to be displayed in group rather than by individual answers 
 6- What actually happened? 
In the Maps Tab, answers being listed by individual question answer, rather than in groups (i.e. all responses to 'Method of water quality testing' and then all responses to 'description of sampling point', instead of all group 1 answers and then all group 2 answers.) 
 Tell us more about your request 
Hi guys, is it possible to display the data in the maps tab by repeat question group rather than by answer to an individual question within the question group? So in other words to display the information in a format/same order as it comes up when individual answers are examined in the inspect data tab. 
 Download attachment 
Screenshot 2016-03-09 11.33.45.png (https://s3-eu-west-1.amazonaws.com/cdn.supporthero.io/ticket/107/screenshot-20160309-11.png) 
 
  
   
 
 
 Notification sent by Supporthero.io - 3/9/16 12:38 AM (http://www.supporthero.io)

**Comment by kymni** [comment]
CartoDB seems to only have answers from one question group per submission regardless of how many question groups were submitted from the survey. All question groups answers need to be logged before issue is resolved

**Comment by janagombitova** [comment]
This issue has gained priority because the Fiji government uses screen shots of our maps to add into their reports. They collect data also using repeated question groups and expect the data to be shown in the same way as in the Inspect data tab. They are also waiting for the CartoDB maps and custom maps, but as CartoDB implementation is not ready yet to scale this issue will solve at least one of their requests. 

If needed we can tackle this issue is two steps:
1. fix on 'regular' maps
2. fix on CartoDB maps

@muloem and @kymni What do you guys think?

**Comment by Nikki-Akvo** [comment]
Thank you Jana! You are a star and this will help DWS a lot. Thank you again!!

**Comment by janagombitova** [comment]
In the planning poker session we decided as this issue combines the current maps and the CartoDB maps, to split away the CartpDB implmentation and handle only the current maps (public and private view). The CartoDB maps will be handled in a separate issue, as it involves change the database structure which involves getting Ivan and Jonas

No design input needed as we will reuse the elements from the Inspect data tab

**Comment by janagombitova** [comment]
### The display of RQGs in 'current'  Mapbox maps

We have agreed to use the way RQGs are rendered in the Inspect data tab when viewing a submission. This view shows each repetitions grouped together (as the user submitted them in the form on the app). Here you can see how the current set up is for non-CartoDB maps. 

**Public map** 
<img width="602" alt="screen shot 2016-07-09 at 13 07 04" src="https://cloud.githubusercontent.com/assets/12456965/16707635/0cb60ba6-45d6-11e6-9fae-b487afb4dd00.png">

An example of the public map with the repeated question group. The questions are not grouped together in a group but are grouped by question (Q1s from each repetitions together) 

**Private map**
(to be added)

**Comment by kymni** [comment]
@janagombitova is this still an issue?

**Comment by janagombitova** [comment]
Just checked. No it shows as it should. The UI is not so clean, but it is ok for now and needs no further work.
