### ISSUE TITLE
Load dashboard languages on demand

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1602]
At the moment we are loading strings for all available dashboard languages even when these will not be used.  This adds a considerable fraction to the dashboard loading time.  We need to refactor to load only the language strings that the current user will need and only load another language on-demand.

**Comment by muloem** [comment]
#### Test Plan

1. Load the public page of the dashboard.  The default language appearing should be English.  Any changes to the language should results in only English being returned

2. Log in to the dashboard and switch between the different languages and verify that the correct language is shown after the page is reloaded.

**Comment by rumca** [comment]
The first part of this test plan doesn't pass - changes to language on the public page result in the language actually changing (which is the behaviour I would expect).

Second part passes.

**Comment by muloem** [comment]
@rumca true. ignore the first test please. it should only happen that way if the public page is visited when *not* logged in.
