### ISSUE TITLE
separate option questions in different columns

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1605]
For computation and display needs, their should be an option to separate option questions answers in which multiple options are possible in different columns.

Example question:
Type of school:
* primary
* secondary
* vocational

Answers now become:

Type of school
primary
primary|secondary
primary|vocational
secondary|vocational
etc.

There should be an option "separate options into columns", which gives:

Type of school (primary)   Type of school (secondary)   Type of school (vocational)
1                                         0                                            0
1                                         1                                            0
1                                         0                                            1
0                                         1                                            1

**Comment by janagombitova** [comment]
Here is a link to the document where we started the discussion on this issue https://docs.google.com/document/d/19PyUx14pxsa2YpRbw_vRMoXaWRPEpM6GZXOXznhiP1U/edit

**Comment by mtwestra** [comment]
In the first implementation we will automatically expand option data when the export type is 'for external systems'. Later, we could turn expansion into an option for this file type.

**Comment by mtwestra** [comment]
Test plan:

1) When 'use for an external system' is not checked, the behaviour of the reports should be unchanged.
2) When 'use for an external system' is checked, the following should happen:
* The first column for an option question is unchanged and contains the pipe-separated packed representation of the result
* For each option, a column is created in the order in which the options are defined in the dashboard
* The header of each option starts with the prefix '--OPTION--|', the code if it is present, and the text of the option.
* If the allowOther flag is set, at the end a column with prefix '--OTHER--' is created
* data in the new (json) and old (pipe-separated) format should be treated the same. 
* When an option is present, a 1 is put in the corresponding column. When it is not present, a 0.

**Comment by janagombitova** [comment]
#### Implementation description (from the users perspective)

With this feature we will change the way raw data reports are structured for **option question** (both single select and multiple select ones). This change will result in having 1 column holding all the selected answers in one cell (as it is set up currently) followed by separate option columns: 
- answer is indicated by 1=selected and 0=not selected
- 'Other' column comes after the option columns and holds the typed in answer (not the 1/0 indication) 
   - If the user did not type in anything for 'other' - answers will be rendered based on current other behaviour  
- change will be added for raw data reports with the flag - ‘use with external systems’: 
   - for these reports we already split cascades into separate columns 
   - data cleaning will not be possible with this report structure 
- Column header (no question ID as with ‘external sources’ we do not give those): 
   - 1st summed up column: Question text
   - Following option columns: Question text|option value 
   - Other column: Question text|OTHER
- Column headers with codes: 
   - 1st summed up column:Question text
   - Following option columns:Question text|code:option value 
   - Other column: Question text|OTHER

**To be defined** 
How will we rephrase the text under the 'Advanced settings' for raw data reports to more clearly state the report structure and use?
- current text: Export this report for use with an external system. This export format cannot be re-imported into the FLOW system.
- proposed new text: TO BE DRAFTED

**Comment by janagombitova** [comment]
Test plan passes and change works as expected

**Comment by muloem** [comment]
@janagombitova We will need to update the user manual / documentation with these changes right?

**Comment by janagombitova** [comment]
Yes. and I am on top of that. No worries. 

My thinking was: 
- for now we update the documentation and make sure the partner team communicates this properly to partners so they know where to find these reports 
- for longer term we improve the report selection design - https://github.com/akvo/akvo-flow/issues/1718

**Comment by janagombitova** [comment]
@mtwestra, @stellanl and @muloem when testing this change I tested out the behaviour when the user defines the question IDs herself and then downloads the report. My understanding was that if the user defines the question IDs herself, these will be shown in this report. If yes, then the current reports under Advanced settings do not render with the user defined question IDs

**Comment by muloem** [comment]
@janagombitova yes this is supposed to be the case. If the user specifies question IDs they should be shown in the report.

**Comment by janagombitova** [comment]
@muloem great, then I found a problem. The user specified question IDs does not show in the report anymore. @mtwestra and @stellanl can you take a look? 

On UAT1 I have a survey with question IDs to check - 1.9.9 UAT folder > Jana test > 1st round > Test survey Non MF 30 June > 30 June

**Comment by janagombitova** [comment]
👍 test plan passed

**Comment by janagombitova** [comment]
👍 changes pass regression test as well
