### ISSUE TITLE
Order cascade resources in drop-downs alphabetically 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1615]
Currently the order of cascade resources in dropdowns is not alphabetically which makes searching for the specific cascade hard in cases where the list is very long. 

![screen-shot-20160407-at-17](https://cloud.githubusercontent.com/assets/12456965/14376763/c36f573e-fd6b-11e5-9383-7e103e15b25a.png)

Please tackle all dropdowns where the cascade is selected, in the Cascade resource tab as well when creating a survey and adding in the published cascades.

**Comment by janagombitova** [comment]
Requested via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-13366-from-birna-dot-steen-at-gmail-dot-com

**Comment by rumca** [comment]
commit with wrong issue number https://github.com/akvo/akvo-flow/pull/1645/commits/193f2937864a429d98f1ff866d5223c253d38f88

**Comment by rumca** [comment]
### Test Plan 

1. Load Dashboard
2. Navigate to ``Data > Cascade`` tab
3. Confirm list of existing cascades is alphabetically ordered
4. Navigate to a survey with a cascade question
5. Confirm list of existing published cascades is alphabetically ordered

**Comment by rumca** [comment]
test plan passes as described
