### ISSUE TITLE
Repeated question groups give an empty row in raw data reports (estimated: 24)

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1619]
In specific cases - with mandatory questions - a deleted repetition from the app still shows in the raw data report as an empty row. 

Steps that I took:
1. Created a form with a 3 question groups - one was repeatable. The repeatable group has a few questions and all were mandatory
2. I filled in 5 repetitions with all the answers 
3. Deleted one repetition, so now I had only 4
4. submitted my form
5. On the dashboard all is shown fine in the Data tab, but in the downloaded raw data report I see 5 repetitions for my submission and one is empty. The users then get an empty row and this confuses them as they assume data is lost.  

<img width="1201" alt="screen shot 2016-04-12 at 15 58 10" src="https://cloud.githubusercontent.com/assets/12456965/14462447/66782f56-00c7-11e6-9410-ce23f06bdbc4.png">

@rumca already highlighted this issue during testing https://github.com/akvo/akvo-flow/issues/1421#issuecomment-144743311

**Comment by janagombitova** [comment]
Link: https://akvoo.reamaze.com/admin/conversations/2-round-of-baseline-survey-arrangement

**Comment by stellanl** [comment]
One way is for the raw data report to hide all-null repetitions. Will missing repetition numbers be confusing?

**Comment by janagombitova** [comment]
@stellanl yes, I think so. In the Inspect data tab the repetitions and answers are shown properly and so is the number order Ok. The confusion happens once the user opens the raw data reports and compares the sheet with the dashboard. 

So the ideal case would be: no empty rows and repetition numbers in order
