### ISSUE TITLE
Signature in CartoDB maps display incorrect

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1622]
In the CartoDB maps after clicking on a data point and viewing the collected data the signature does not show properly. The signature image and text 'signed by' is placed in the same line and not under each other, what causes an add display if the users screen is wider. 

The signature image and the signature text should be in two separate rows (lines), under each other and both aligned to the left.

<img width="665" alt="screen shot 2016-04-15 at 10 44 23" src="https://cloud.githubusercontent.com/assets/12456965/14556182/1e1e86e2-02f7-11e6-8d12-7cfd7862b52f.png">

**Comment by rumca** [comment]
fix looks good
