### ISSUE TITLE
Authentication issues with the email/pwd deployments

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow#1625]
Email/password based authentication seems to be working no longer (deprecated), and Oauth2 is the default and recommended approach for handling this.

The current ant script however doesn't like the interactive nature of the auth process, and the Oauth2 code (generated via browser) cannot be entered before the deployment is considered a failure.

**Comment by ichinaski** [comment]
I manged to successfully deploy the main app using `<appcfg.../>` instead of `<exec.../>` calls, which permits the Oauth token to be added to the auth process.

However, I run into some issues when trying to use the same approach with the *backends update* task. Presumably the space doesn't get along with the ant-based deployment. https://code.google.com/p/googleappengine/issues/detail?id=5315 **Note: Using the former `<exec...>` approach still works here, since the Oauth token is already stored in the machine.

**Comment by rumca** [comment]
I've deployed to a couple of instances now using these changes, looks good 👍 

@muloem presumably you'll have to update some of your deployment scripts when you get back.

**Comment by muloem** [comment]
OK will take a look into it.
