### ISSUE TITLE
In public map responses for option questions, cascades, photos, and videos are rendered as a string

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1635]
Since the introduction of codes for option questions and geotagging of media items, the collected data is shown in the public map as a string. This issue refers to https://github.com/akvo/akvo-flow/issues/1632

Question types rendered as a string:
- [x] option questions 
- [x] cascades 
- [x] photos 
- [x] videos 

<img width="928" alt="screen shot 2016-04-28 at 08 55 18" src="https://cloud.githubusercontent.com/assets/12456965/14877683/fbd62892-0d1e-11e6-9ff7-93533007ab4b.png">

<img width="1109" alt="screen shot 2016-04-28 at 09 41 46" src="https://cloud.githubusercontent.com/assets/12456965/14878700/73fecb20-0d25-11e6-983d-0697f6b0a6a6.png">

<img width="926" alt="screen shot 2016-08-12 at 13 26 10" src="https://cloud.githubusercontent.com/assets/12456965/17620996/b5b717e8-6090-11e6-9da1-bfe9529706bd.png">

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/akvoflow-support-request-number-14616-from-anatamambo-at-gmail-dot-com

**Comment by janagombitova** [comment]
Furthermore, photo or video with geotag or without is also shown as a string 

<img width="390" alt="screen shot 2016-06-07 at 08 11 03" src="https://cloud.githubusercontent.com/assets/12456965/15847604/990ec222-2c87-11e6-8cd1-99382763caaa.png">
<img width="344" alt="screen shot 2016-06-07 at 08 12 20" src="https://cloud.githubusercontent.com/assets/12456965/15847605/99153bac-2c87-11e6-936a-1ff6a0910e8f.png">

**Comment by mtwestra** [comment]
fixed as part of [#1577]

**Comment by janagombitova** [comment]
## Test plan:

1. Open Flow without logging in and on the public map select a data point (ideally one where you know all questions are represented - especially: option questions with codes, cascades, photos, videos and Caddisfly)
1. Check that the submitted answers are not rendered as a string 
1. click through multiple points to confirm

**Comment by janagombitova** [comment]
Options and cascades show not as pipe separated values - 👍 
Geoshapes show as strings but that is outside of the scope of this issue. 

There is an inconsistency in how the photo and video responses are shown. The photos render on the top of the side bar and are clickable, so that is ok. But in the answer their either show the full url or only a path. Same for videos. @mtwestra why is this and can we show the url for all cases?
 
![screen shot 2016-10-20 at 16 00 02](https://cloud.githubusercontent.com/assets/12456965/19563004/d72df0a2-96de-11e6-8c47-e9df60802cca.png)

![screen shot 2016-10-20 at 16 01 04](https://cloud.githubusercontent.com/assets/12456965/19563007/d8f4cde8-96de-11e6-80e6-5656ce91834c.png)

![screen shot 2016-10-20 at 16 01 32](https://cloud.githubusercontent.com/assets/12456965/19563013/da91942e-96de-11e6-9c01-e6a69d3b0cb9.png)

![screen shot 2016-10-20 at 16 01 37](https://cloud.githubusercontent.com/assets/12456965/19563016/dce29d0e-96de-11e6-9eb8-3210c404ed84.png)


You can check it out on https://uat1.akvoflow.org/ on data points located around Schiphol.

**Comment by mtwestra** [comment]
@janagombitova: This seems to be some legacy stuff. The path of the photo that is in the actual answer used to contain the path on the device, which is not relevant. To display the photo, the backend stripped off the image name, and the actual path to amazon was build up. From what I see here, the video path is still treated like that, while for the photo both types of paths are now shown. I am not sure where that comes from. In any case, both of these should be replaced by the reconstructed path: amazon root+image folder + filename. This value should be easy to get as it is also used to show the image.

**Comment by janagombitova** [comment]
@mtwestra that sounds like an easy fix. Can you take a look at it and try to fix it up? Thank you

**Comment by janagombitova** [comment]
Based on the discussion with @mtwestra I am creating a separate issue to deal with the diversity in displaying video and photo responses. https://github.com/akvo/akvo-flow/issues/1799

If we do not take into account the difference in displaying the photo and video answers, then this issue passes the test plan 👍
