### ISSUE TITLE
Remove scrolling on Flow public page (estimated: 3)

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1640]
(We have tackled this same issue in the private map before) 

With smaller screens there is scrolling enabled on the Flow public page, when the user opens Akvo Flow and does not log in. If the user scrolls the page down to see the 'Log in' link he looses sight of the full map and the zoom in and zoom out icons. The public page should all the time show the user the entire map as well as the page header and footer, so no scrolling is needed to simply find in the log it link and still view the entire map. The page should be responsive to change of screen size. 

If helpful, there is quite some white space between the akvoflow logo and the map, this can be decreased if needed to solve the issue.

**Comment by gabemart** [comment]
![gif mov](https://cloud.githubusercontent.com/assets/2589977/17330817/41b38606-58c0-11e6-908e-0cb453f1434d.gif)

@janagombitova like this?

**Comment by gabemart** [comment]
# Test Plan

Open the public page. Verify that it is not vertically scrollable - the contents should fit the viewport perfectly (vertically at least). Resize the viewport to a few different sizes and verify that this behaviour persists.

**Comment by janagombitova** [comment]
@gabemart yes

**Comment by janagombitova** [comment]
@muloem @gabemart The changes you made do remove the scrolling on larger screens but not if the screen is really small. It also appears that the items on the screen to not expand with the screen either as you showed last time.

**Comment by muloem** [comment]
@gabemart its possible this was caused by changes introduced while merging your css with that from the geotagged images PR here 5fd6ab1f6e296fdef7b34602f8d1af460e5049e7

**Comment by janagombitova** [comment]
With the new changes introduced to the layout, we should also take care of this one. When the user opens Flow without logging in, the layout is not very handy. There are quite some white spaces and you need to scroll down the page to see the footer, but because if you hover over the map and scroll - you zoom in, this can then be confusing to the user. 

Can we remove the white spaces and fully remove the need to scroll on the public page so the user sees the entire screen when landing on Flow? Thanks 

<img width="1279" alt="screen shot 2017-04-05 at 16 28 45" src="https://cloud.githubusercontent.com/assets/12456965/24710294/02b08e58-1a1d-11e7-9dfb-459fc54f825a.png">
<img width="1280" alt="screen shot 2017-04-05 at 16 28 55" src="https://cloud.githubusercontent.com/assets/12456965/24710302/05bd6152-1a1d-11e7-9dbc-633c7d16560e.png">

**Comment by janagombitova** [comment]
As we will be changing the Flow public page I am closing this issue
