### ISSUE TITLE
Export Caddisfly data to reports

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#1643]
We need to export the caddisfly data to reports. 
Related issue: [#1577]

Items to consider:
- format of output when using questionIds
- format of output when not using questionIds
### Format of Caddisfly result data:

JSON string with properties:
- type: always 'caddisfly'
- name: display name of test
- uuid: unique identifier of test
- image: image url (optional)
- result: array of result objects, containing a result object for each specific result returned by the test.

Result object:
- name: display name of result 
- value: numeric value of result
- unit: unit of result
- id: id of result

Example:
{
  "type":"caddisfly",
  "name":"Chlorine and Free Chlorine",
  "uuid":"bf1c19c0-9788-4e26-999e-1b5c6ca28111",
  "image":"45e61553-8568-4719-b922-7f678903e594.png",
  "result":[{
    "name":"Total Chlorine (ppm)",
    "value":10,
    "unit":"ppm",
    "id":1
  },{
    "name":"Free Chlorine (ppm)",
    "value":1.6,
    "unit":"ppm",
    "id":2
  }]
}
### Proposal:
- Caddisfly data is always split into multiple columns
- Columns created are one for each result, and one for the image URL
- Caddisfly data cannot be changed by importing excel files
- The names of the columns contain the name of the result, and the unit

**Comment by mtwestra** [comment]
Say, we have the question text = "Chlorine measurement"
Taking the above example result, this would be exported as follows:

1) using questionId
* 28772937|Chlorine measurement|TEST_TYPE
* --CADDISFLY--|Total Chlorine (ppm)
* --CADDISFLY--|Free Chlorine (ppm)
* --CADDISFLY--|image-URL

2) not using questionId
* Chlorine measurement|TEST_TYPE
* --CADDISFLY--|Total Chlorine (ppm)
* --CADDISFLY--|Free Chlorine (ppm)
* --CADDISFLY--|image-URL

The first column would then contain the test type, and brand, for example:
Chlorine and Free Chlorine (HACH 27450, 50pcs)

**Comment by mtwestra** [comment]
The above system is a bit too rigid in the case of backward compatibility. Therefore, we will change to an implementation where a measurement is spread over two columns: one which has the parameter, and one which has the value:

Say, we have the question text = "Chlorine measurement"
Taking the above example result, this would be exported as follows:

1) using questionId
28772937|Chlorine measurement|TEST_TYPE
--CADDISFLY--|PARAMETER
--CADDISFLY--|VALUE
--CADDISFLY--|PARAMETER
--CADDISFLY--|VALUE
--CADDISFLY--|image-URL
2) not using questionId

Chlorine measurement|TEST_TYPE
--CADDISFLY--|PARAMETER
--CADDISFLY--|VALUE
--CADDISFLY--|PARAMETER
--CADDISFLY--|VALUE
--CADDISFLY--|image-URL
--CADDISFLY--|image-URL

The first column would then contain the test type, and brand, for example:
Chlorine and Free Chlorine (HACH 27450, 50pcs)

**Comment by janagombitova** [comment]
## Test plan: 

### Testing different reports and data structure 
1. Collect data for a survey that holds all question types and all Caddisfly tests 
1. Export raw data report 
1. Check that each Caddisfly questions has multiple columns 
1. First column should hold the test type 
1. Following columns hold the value (multiple columns - multiple values)
1. Last column image url 
1. Collect data for a survey with repeated question groups. Make sure the Caddisfly questions are in the non repeated group as well as in the repeated group. 
1. Export the raw data report and cross check the data structure is correct also for the repeated groups 
1. Export the raw data report with Advanced settings turned on for the 1st survey 
1. Cross check the export structure 
1. Export the raw data report with Advanced stetting turned on the the 2nd survey
1. Cross check the export structure 
1. Export raw text file and check the structure for the 1st survey and then 2nd survey 
1. Export the survey form for both surveys 

### Testing data cleaning 
1. Export raw data via Data cleaning 
1. Clean the data for one Caddisfly test and for the free text question
1. Import the spread sheet via data cleaning 
1. Cross check that the Caddisfly test data was not changed but the free text question was 
1. Export the spread sheet again
1. Add 5 new submissions to the spread sheet and add data also for Caddisfly questions 
1. Import the spread sheet
1. Check that new points were added to the data set but the Caddisfly questions were not filled in and remain empty

### Testing data import from one survey to another
1. Make a copy of the 1st survey 
1. Download the raw data for the survey survey 
1. Go to the Data cleaning tab and export the data for the new copied survey
1. Copy in the data from the 1st survey into your data export sheet from the copied survey (follow the rules for importing new data)
1. Import the data via data cleaning 
1. Cross check that the data import was successful in the Messages tab 
1. Cross check that there is new data in the Inspect data tab but the Caddisfly test questions do not hold answers 
1. Cross check the data in Monitoring tab, on the map tab
1. Enable Monitoring on the copied survey, create an assignment and get the survey on your phone 
1. Sync the data to your phone and make sure all points are synced properly and so is the History of the points

**Comment by janagombitova** [comment]
👍  passes test plan and works as expected. I have some suggestions for improvement when it comes to the header structure as I find it inconsistent now, but will create a separate issue for it that can be handled later
