### ISSUE TITLE
Handle geotagged media in raw data reports (estimated: 12) 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1652]
We are now capturing location information for all media questions. The information is shown in the dashboard but we need to provide this information in reports as well. Once we receive feedback on how to best handle this information in reports, this issue will be further specified.

**Comment by janagombitova** [comment]
Based on the feedback we received from a few users and data analysts internally and with who we work externally, the proposal is to show the geolocation information for a media question (photo and video) - if captured - in separate columns. 

The first column holding the question text will hold the media url, as currently in raw data reports. The geotagging information will be added to separate columns following the media column (photo or video). If the photo or video is not geotagged, the columns are not shown in the report and the user only sees the column with the url (as currently). If the photo or video is geotagged, then we add 3 extra columns, for latitude, longitude and accuracy. The geolocation information is not editable with data cleaning.

#### Proposal

**For photo questions**
Example question text: Take a photo of the school

Export column headers: 

1) using question ID
* 80810008|Take a photo of the school
* --PHOTO--|Latitude
* --PHOTO--|Longitude
* --PHOTO--|Accuracy (m)

2) not using question ID

* Take a photo of the school 
* --PHOTO--|Latitude
* --PHOTO--|Longitude
* --PHOTO--|Accuracy (m)

**For video questions**
Example question text: Short interview 

Export column headers: 

1) using question ID
* 80810008|Short interview  
* --VIDEO--|Latitude
* --VIDEO--|Longitude
* --VIDEO--|Accuracy (m)

2) not using question ID
* Short interview 
* --VIDEO--|Latitude
* --VIDEO--|Longitude
* --VIDEO--|Accuracy (m)

#### To be resolved:
We have not discussed on how to handle a situation when a user uses data cleaning to import new data to registration forms to create new data points. 

**Situation A** 
- the created survey holds a photo question, but has no data collected to it at all and the user is importing a fully new set of data using data cleaning to create data points 
- he downloads a raw data report which is empty, only showing the question IDs and text
- the raw data report should in this case only show 1 column for photo question, the one where the url should be added

**Situation B**
- the created survey holds a photo question and has one data point created via the app and the photo is geotagged
- he downloads the raw data report which shows the 1 submission 
- the photo question has 4 columns (url, lat, long, accuracy)

**Questions:** @ichinaski @muloem @rumca and @stellanl 
- how will we deal with these two situations if the user wants to upload raw data against this new survey, the data was captured with Flow and thus the photos have the url and geotagging information? 
(Example: CWSA in Ghana has collected a baseline survey for an entire region and then realised that the data load is too heavy to do monitoring in districts, as the district officer would sync data for the entire region. He only needs the data points for his district. What has been done is that we created a copy of the baseline survey for each district. We downloaded the regional raw data, and uploaded only the district data against each new survey, creating new district data points which are now monitored. All the baseline data had a photo in it, so the url was copied as well.) 
- I just want to check that accuracy captured in meters, right?

**Comment by stellanl** [comment]
Current implementation always shows the geolocation columns. Also, VIDEO data will have geolocation columns saying --PHOTO--... Should that be --VIDEO-- ?

**Comment by janagombitova** [comment]
@stellanl based on my understand of what Inigo shared, videos are not being geotagged at this moment, so we can leave them for now and only add this raw data report change for photo questions

**Comment by stellanl** [comment]
Ok, I'll revert that. I still wonder if having the number of columns depend on the current answers is a good idea. A single answer arriving with a geotagged photo could change the format at any time, and prevent the report from being imported to another system. Do we do that for any other kind of question or report?

**Comment by stellanl** [comment]
Test plan:
Go to uat1, export raw data reports for form 75439117 (1.9.8 UAT Folder > Jana 1.9.8 > 2nd round of testing > 1.9.8 Non MF Surveys (jana 2nd) > 1.9.8 all questions (2nd round) > all questions form (2nd round)). One with the "Export this report for use with an external system" checkbox checked, one without.
The report with the box checked should have 3 geoposition columns (Long,Lat, Precision) after the URL column for the photo question.

**Comment by janagombitova** [comment]
**Just to sum up the discussion we had yesterday (it is reflected in Stellan's test plan as well):** 
- data cleaning will not be possible on the geotagged columns thus we decided to move the implementation away from the 'general' raw data reports and add it under the 'advanced settings' for raw data reports 
- the initial idea was to validate whether the submissions have a geotagged photo or not, and if yes add the 3 extra columns. As this implementation would require extra validation in the report set up and does not simplify the experience we decided to add the 3 columns for all photo questions regardless the availability of geolocation information
- as the report change will affect only reports with the advanced settings we will not create extra implications who have our reporting structure implemented in other tools they use

**Comment by janagombitova** [comment]
👍 tests plan passed

**Comment by janagombitova** [comment]
Tested during regression tests cases where photos were in repeated questions groups, behaviour with data cleaning and uploading of new data. All works fine - fix passes 👍 

@muloem and @stellanl I just want to confirm (for my own understanding) that with data cleaning used for uploading new data it is expected that you cannot upload photos, videos and signatures. If yes, then all is fine and the issue can be closed.

**Comment by janagombitova** [comment]
👍 all works fine now
