### ISSUE TITLE
Change forms endpoint on CartoDB maps from cartodb storage to dashboard storage

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#1655]
The current end point pulls surveys (forms) from the form table in cartodb. At the moment if a survey is deleted from the dashboard, the event is not executed on cartodb so users will see surveys that they already deleted on the form selector.
Quick fix is to change the end point to use the dashboard's surveys endpoint and pass the surveyGroupId. 
@muloem any additional thoughts on this?

**Comment by muloem** [comment]
Deleted surveys no longer appear in the list under the maps tab. 👍
