### ISSUE TITLE
Implement data approval workflow management (MVP) (estimated: 40)

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1659]
For all the background information on this feature and the decisions around the MVP please check: akvo/akvo-product-design#82

Under the new Workflow tab implement the ability to create, edit, save, delete and view a workflow (as proposed in the mockups) reusing the way we create option questions and/or cascade questions.

**Details:** 

The workflow feature will live under the main Data tab in a subtab = Workflow located next to the Cascade resources. This is the place where the user will create, edit, view and delete workflows that can be used throughout surveys. A Manage workflow permission will be attached to this tab.

Situation A: No existing workflows yet
- page title 'Workflow'
- 'New workflow' button in the top left
- in the middle of the page 'No workflows yet' 

Situation B: Already a few existing workflows: 
- 'Select an existing workflow' + dropdown 'Select workflow' -> same as with cascades
- 'New workflow' button in the top left

Creating, Editing and Viewing a workflow:
- shown once the user selects a workflow from the dropdown, or hits 'New workflow' button  
- follow the mock ups and functional design provided and for UI lets try to reuse cascade as a reference 
- elements: 
  - Name, 
  - Workflow type: ordered and unordered radio buttons 
  - Steps - order, NO code text box, value box with text Step 1 and once clicked on user can type directly, no move functionality only Add step and delete (reuse option questions UX), input counter, cancel and save

**Comment by muloem** [comment]
Notes on things to complete

* [ ] Add the *used in* column

**Comment by janagombitova** [comment]
### Test plan

1. Go to Data tab in dashboard - check new subtab is shown - Data approval 
2. Click on Data approval subtab - check that you see a list of existing workflows (or an empty list if none are created yet) with 3 columns (Name, Type, two action links - edit and delete) and that you have the button Add approval group available 
3. Click on Add approval group and the editing window should open with Name, Approval type, Steps, + Add step, cancel and save
4. Add name "cancel test" and hit Cancel > you are brought back to the list of existing approval groups and the Cancel test approval group does NOT exist
5. Create a new approval group - Name: release version-ordered; type: ordered with 5 steps and save > you are brought back to the list and the new group is shown on top of the list 
6. Click on edit of the new group and check all settings are still the same, all 5 steps are shown and in the proper order; click cancel that will bring you back to the list
7. Create a new group - Name: release version-unordered; type: unordered with 3 steps and save
8. Repeat step 6 for the unordered group
9. Create a third new approval group - Name: to delete, type - ordered with 2 steps > save
10. In the list click on delete for the 'to delete' group > group is deleted and not in the list anymore 
11. refresh Flow dashboard and cross check that the deleted group is still deleted, that the ordered and unordered groups have all settings still properly set

Repeat all steps using different browsers

**Comment by janagombitova** [comment]
### Comments from testing 

@muloem before we take any action we need to decide which of these issues need to happen now and which can be tackled in the following sprint. I have created smaller issues for some of the notes already to break down the work into smaller pieces

#### Order of created steps changes
- I created an 'unordered' approval group - "Test 1 Jana - unordered"
- saved it and Flow brought me back to the list
- opened the approval group by clicking on the 'edit' link
- steps were in to correct order
- I have added two more steps and saved the changes 
- opened the approval group again and the order of the step was not correct anymore (order indicated by numbers in the step names)
- for both unordered and ordered (especially for ordered) approval groups the order of the steps needs to be how the user creates it
- this issue happens for both approval group types 

#### Steps get duplicated 
- I created an 'ordered' approval group - "Test 1 Jana - ordered" 
- saved it and opened it again via the edit link
- every step is shown twice 
- have experienced this problem so far only on ordered approval groups and it does not happen all the time (not easily replicated)

#### Vocabulary change 
- change 'Add new approval flow' to 'Add new approval group' for consistency of naming things as we have Add a approval group button

#### Minor UX improvements 
- when a user clicks on App approval group to create a new group have one step text box already open by default as you will most likely create a group with steps
- In Name text box "New approval group" can you make it behave as we have it with options for option questions - I see the text in the box but once I click on the text field the text is gone and I can start typing right away
- when deleting a approval group a confirmation window should be triggered before we delete the group - we need a consistent way to handle deletion on Flow dashboard and how Flow communicates to the user

**Comment by janagombitova** [comment]
## Comments from 2nd test round

### Saving new group
- when I create a new approval group with three steps and save it it shows ok in the list
- when I open the new group it does not show any steps (the type is set correctly) 
- I add three new steps again and save

### Editing an existing group
- then I open the same group again and want to add another extra steps but I cannot anymore as the '+ Add step' does not react anymore
I click on Save and I get an info box: Cannot save. The title of an approval step cannot be blank and I am brought back to the list of groups 
- this happens for other existing groups as well 
- after refreshing the dashboard it works again

### UX for cannot save info message
- this info box should be shown if the name of a group is not there but it should not bring me back to the list of groups, I should stay in the edit group window >> creating a new issue to tackle this later

**Comment by janagombitova** [comment]
@muloem two things that are broken and we need to get solved for this 1st release: 
* [ ] saving the groups 
* [ ] editing afterwards 

Both are not working well anymore - see above comment that explain what I did. Besides that all other parts work fine. Once these two are done we can consider the issue solved for this implementation and can tackle the other details in the later sprint.

**Comment by janagombitova** [comment]
👍  passes test plan beautifully

**Comment by janagombitova** [comment]
## Test plan

For UAT testing follow test plan above https://github.com/akvo/akvo-flow/issues/1659#issuecomment-249524341

**Comment by janagombitova** [comment]
## Notes from testing 

👍  passes test plan
