### ISSUE TITLE
Assign a data approval workflow to a survey definition - MVP (estimated: 48)

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1660]
For all the background information on this feature and the decisions around the MVP please check: akvo/akvo-product-design#82
#### Assign approval workflow to survey

**Details:** 
The user will select which workflow he wants to use when defining the survey following the monitoring pattern. 
- In the survey definition in 'Advanced settings' section, add a checkbox 'Enable data approval workflow features' in the same way as monitoring is enabled. 
- Once selected the user will see: 
  - a dropdown with the list of existing data approval workflows 
  - a link 'Show data approval workflow', which is not enabled. 
- He selects the approval workflow from the list and it is show as selected in the dropdown and the 'Show data approval workflow' is activated. 
- Once clicking on 'Show data approval workflow' the workflow is shown in its title, type and steps in a in page pop-up

**Questions:**
Will the user need to re-publish a survey after making this change? 
#### Assign responsible user to an approval workflow

In the survey definition after the user selects a workflow here is also the place where the user will define which dashboard user is responsible in implementing the workflow step. We have decided not to add this user permission in the general Users tab because: 
- one workflow can be used in multiple surveys what makes the user selection complex
- a particular user John is responsible to implement one step is survey A but not in survey B
- the user adds a workflow to a survey in the survey definition and we expect him to make the decision on who is responsible at this point of time as well

**Details:** (draft)
- please follow the mock ups and functional design doc
- when viewing selected workflow in the survey definition each step holds a clickable link 'Responsible user'
- after selected a list of users is rendered - only users with 'View data' permission for this survey
- users are selected and assigned -> only the user who is selected for implementing a step will have the power to implement the workflow step on the datapoint in the Monitoring tab

**Comment by muloem** [comment]
We will possibly need to have multiple users to be able to approve an approval

**Comment by janagombitova** [comment]
**Assigning responsible users to an approval workflow**

Expected behaviour: (please follow the mock ups and functional design doc)
- the user adds an existing data approval workflow to a survey in the Advanced setting 
- when viewing selected workflow and its steps in the survey definition each step holds a clickable link 'Responsible user'
- after clicking on it a list of users is rendered - only users with 'View data' permission for this survey
- a user is selected and assigned for each workflow step -> only the user who is selected for a step will have the power to implement the workflow step on the datapoint in the Monitoring tab
- one user (user John) can be added to step 1 and also step 2 of the workflow for this particular survey A
- John can also be the responsible user for step 3 of this same workflow which is added to survey B
- John can be responsible for all 5 steps of the workflow in survey C (in this case the user has to add John one by one to each step) 

The question that came up today in the planning poker meeting was whether multiple user can be assigned to one workflow step and how will it work. Is it ok to limit and have only one user responsible for one step and not multiple users? If we made John and Peter responsible for step 1 in the workflow this would mean that the data point will have the status approved on step 1 if **either** John or Peter approve it. Not if both John and Peter had to approve it, then John would have one approval step and Peter another one. 

The proposal was to limit this to only be able to assign one user in the MVP to one step to not overcomplicate this feature for the users. @joycarpediem What is your take on this? 

@muloem @loicsans @LarsSjogreen Do you have any remarks?

**Comment by joycarpediem** [comment]
@janagombitova , John or Peter approving is going to be the most frequent usecase. If John and Peter has to approve , then that will be distinct approval steps.

The workaround for now will be to create a common user for Peter and John and assign it to the approval step. Doing this, we will loose visibility of whether John or Peter approved but i think we can live with that for now.

**Comment by muloem** [comment]
To Do:

* [ ] Spontaneous saving when assigned approval is edited

**Comment by janagombitova** [comment]
## Test plan 

1. Open a survey on the dashboard 
2. Go to Survey basics > Advanced Settings - you should see two unchecked boxes, one for enabling monitoring and one for enabling data approval
3. Check the Save button is now enabled as well - is blue again and not grey
4. Select Enable data approval > a dropdown with the list of existing approval groups show, with the new ones you have created
5. Select release version - ordered group and click on Show approval 
6. All step are shown in proper order, the type is indicated correctly as well 
7. Click on the user icon for a step 
8.
9.
10. 
11. Save changes for the survey 
12. refresh the dashboard, open the survey again and cross check all changes are saved properly
13. Open another survey and repeat steps 2 - 12 but add the unordered data approval group  
12. Repeat all steps using different browsers

**Comment by janagombitova** [comment]
### Notes from testing Assigning an approval group to a survey 

@muloem before taking action we need to decide what is urgent to get fixed before the 1st public release and what can wait for the following sprints and later improvements 

#### Missing info text 
- I need to draft a short text to add to the little information "?" next to the Enable data approval check box 
- https://github.com/akvo/akvo-flow/issues/1771

#### Dropdown to select approval improvement 
- when I open a survey and the advanced setting I select the Enable data approval 
- the dropdown shows well but it opens on a selected approval already
- could the dropdown open on "Choose data approval group" as we have with other dropdown in the dashboard? 
- https://github.com/akvo/akvo-flow/issues/1770

**Comment by janagombitova** [comment]
@muloem I am splitting this issue to have the assign responsible user part in a separate one.

**Comment by janagombitova** [comment]
# 2nd round of testing 

For this review we can consider the implementation good enough and any comments (from the previous tests) will be handled in the following sprints 

👍 assigning an approval group to a survey passes the test

**Comment by janagombitova** [comment]
👍  passes 3rd test round as well

**Comment by janagombitova** [comment]
## Test plan

For UAT testing follow test plan above https://github.com/akvo/akvo-flow/issues/1660#issuecomment-249529472

**Comment by janagombitova** [comment]
## Notes from another round of testing 

👍  passes test plan (besides assigning users which is handled in another issue)
