### ISSUE TITLE
Workflow MVP - in Monitoring tab add 'Workflow' column for surveys with workflow

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1663]
For all the background information on this feature and the decisions around the MVP please check: akvo/akvo-product-design#82

**Details:**
In current Monitoring tab add new column Workflow status. The new column is located between Last update and Action, called 'Workflow'. This column in only shown for surveys (selected in the dropdown) that have a workflow added to them in the survey definition. Surveys that do not have the workflow added do not get the extra column.

**Questions**
With this implementation of the MVP we are limiting Workflow. Because we are adding the feature to the Monitoring tab, it results in the fact that surveys that do not have monitoring enabled, are not shown in the monitoring tab (you cannot select them in the dropdown) and thus you cannot apply the workflow.

**Comment by muloem** [comment]
Merging this with #1664
