### ISSUE TITLE
Cartodb custom maps - display legend title text field only when "Title" toggle is checked

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#1669]

**Comment by janagombitova** [comment]
@kymni I assume this one is fixed as well already right?

**Comment by kymni** [comment]
@janagombitova it's fixed

**Comment by janagombitova** [comment]
Issue is fixed, however I found another item I do not find so intuitive related to the legend and legend title. When you type in the title you need to hit enter for the title to be shown. I would expect that as typing the letters appear in the legend as well. @kymni What do you think? 

Secondly, during the user testing there was quite some confusion on the role of a legend title as many people assumed it is the name of the map. They also said that if the maps are shareable it will be desired to have the map name (and description) in the map. @loic and @kiarii What is your take on this one?

**Comment by janagombitova** [comment]
Following the decisions shared here akvo/akvo-product-design#143 (comment) I am closing this issue as the functionality of Custom maps will not be part of Flow's feature list.
