### ISSUE TITLE
Video responses url on cartodb maps point to the collecting device's internal storage

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#1674]
![screen shot 2016-05-16 at 15 18 05](https://cloud.githubusercontent.com/assets/1155088/15289259/afbf8ffc-1b79-11e6-919f-a68a3be611c9.png)

@janagombitova @muloem should we replace this with a hyperlink to the video's location on aws?

**Comment by janagombitova** [comment]
@kymni the link to the video should be shown there - same as in the Inspect data tab

**Comment by muloem** [comment]
Video URL displayed as expected  + Link works correctly 👍
