### ISSUE TITLE
Cartodb custom maps - when viewing or editing a custom map, the custom maps tab should be highlighted

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#1677]

**Comment by janagombitova** [comment]
@kymni is this still an issue? I could not reproduce it anymore when testing on UAT1

**Comment by kymni** [comment]
@janagombitova already fixed it

**Comment by janagombitova** [comment]
Following the decisions shared here akvo/akvo-product-design#143 (comment) I am closing this issue as the functionality of Custom maps will not be part of Flow's feature list.
