### ISSUE TITLE
Invalid empty repeat question group error (estimated: 8)

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1684]
When importing data for spreadsheets, in some cases there are empty phantom rows after the last valid row of data.  In these cases the raw data importer is throwing the error of an empty repeat question group column, and preventing valid reports from being imported.  We need to fix the check to ensure that phantom row are ignored.

**Comment by stellanl** [comment]
Test plan:
1. export a survey for data cleaning.
2. Open the spreadsheet and create some content in a cell below the last row with content.
3. Delete the cell again.
4. Save the spreadsheet and import it.

**Comment by janagombitova** [comment]
👍  passed test plan

**Comment by muloem** [comment]
@janagombitova can you also update the test plan to include a repeat question group set of responses with an empty row in between? i.e with even the number in the repeat column missing. thanks!

**Comment by janagombitova** [comment]
@muloem yes sir!

**Comment by janagombitova** [comment]
passes 2nd round of regressions as well (with all the odd possible things people can do with RQGs) 👍

**Comment by stellanl** [comment]
The RawDataSpreadsheetImporter.validate() function still does not cope with phantom rows at the end. It ierates ove allr rows and expects to find a repeat number on all of them.

**Comment by janagombitova** [comment]
👍 implementation passes test plan successfully and the validation is the repeated column is truly empty still works as well as with empty repeated group rows
