### ISSUE TITLE
Changing question type from free text to geolocation does not reflect on settings for data point names 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1692]
By changing the question type the selected flag (use as data point name) is not updated 

**Steps taken** 
I created a survey with 2 questions (Form ID: 72769116 on UAT1) where both questions were free text with the flag 'use as data point name' turned on. After creating an assignment and sending the form to the phone, I realised that the 2nd question was supposed to be a geolocation question. So I went back to the dashboard and changed the 2nd question from 'free text' to geolocation and enabled 'use as data point location'. In the app I received the new form version and submitted a few points. The data point names were created out of the geolocation question as well, which should not be possible as that setting is not allowed on geolocation questions. 

![screen shot 2016-06-06 at 15 20 03](https://cloud.githubusercontent.com/assets/12456965/15823237/28eea04e-2bfa-11e6-9044-c3136c93ecb5.png)
<img width="360" alt="screen shot 2016-06-06 at 15 21 10" src="https://cloud.githubusercontent.com/assets/12456965/15823281/56837bec-2bfa-11e6-9d11-b8b0142cb2e5.png">
(data point name being built from geolocation question type)

**Comment by janagombitova** [comment]
The same happened after following these steps: 
- created a new question that is always by default free text 
- selected use as data point name 
- changed the question type to geolocation and has use as data point location selected by default 
- published 
- collected data 

My data points now have the geolocation info in their data point name.

**Comment by muloem** [comment]
Will be handled in #3412
