### ISSUE TITLE
Multiple geoshapes not rendering properly in Map tab (CartoDB) 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1694]
When a form holds more than one geoshape question the shapes are not shown properly in the Map tab. One answer is shown in both questions when the user clicks on 'show on map' and in the side bar only one map is shown and it is under the wrong question. 

**Example:** Form holds two geoshape questions, one where manual editing was enabled and the user could choose the shape and the second where only points were enable without manual editing. Both shapes were properly collected and are rendered well in the Inspect data tab.  In the Map tab, after clicking on the point, only one shape in shown in the side bar and they are mixed up, for the question where you could chose any shape type, the point answer was shown. And for the second question also the point question was shown. 

The extra values as number of points, length and area size are rendered properly. 

<img width="962" alt="screen shot 2016-06-07 at 07 38 22" src="https://cloud.githubusercontent.com/assets/12456965/15847629/e000a8d0-2c87-11e6-93a4-6a1bf04ee5ae.png">

<img width="844" alt="screen shot 2016-06-07 at 07 39 54" src="https://cloud.githubusercontent.com/assets/12456965/15847630/e01c5594-2c87-11e6-8702-90c50837f58a.png">

(Example: uat1 dashboard > 1.9.8 UAT folder > Jana 1.9.8 > Jana 1.9.8 Non MF surveys > 1.9.8 All questions survey)

**Comment by kymni** [comment]
## Test plan
* Select survey with multiple geoshape questions
* Click on a point on the map
* Each geoshape should be loaded on its own map in the details panel

**Comment by janagombitova** [comment]
Tested the case, geoshapes load properly on the side bar and the 'show on map' and 'hide from map' functionality works as expected as well. 

Fix passes the test plan

**Comment by janagombitova** [comment]
When testing this issue with a heavy load survey I noticed a problem. (not sure to which issue it belongs specifically, but it is visible with geoshapes) 

**Steps taken**
1. Created a survey with all question types, with 3 questions groups and 45 questions 
2. Created a survey with all question types, 7 question groups and 105 questions. 
3. Submitted one data point per survey
4. In the Data tab selected the 45 question form > only one question group is loaded (out of the 3) and 'loading' freezes. The error in Console is: "Uncaught TypeError: Cannot read property 'length' of undefined. The geoshapes are not shown properly in the preview either 
5. Reloaded the dashboard and went back to Data tab to check a survey submitted before the latests commits (with all question types) >  Same error 
6. Selected another older survey with geoshapes > same error 

7. Went to the Maps tab > selected an older survey with one geoshape question only > everything worked fine > geoshape was rendered in the side bar and also properly on the map 
8. in the Map tab selected a survey with multiple geoshape questions > also both shapes rendered fine in the side bar and also on the map
9. In the Map tab  selected the new heavy load survey with 45 questions and 3 groups > geoshapes worked fine BUT only one question group was shown

**Comment by janagombitova** [comment]
@muloem and @kymni have you guys made any changes to this issue? I cannot reproduce the error anymore and on forms collected before today the test plan passes as defined 👍 

However, the data submitted today is not showing on the CartoDB maps at all but the Data tab and reports are working as expected. Any ideas on what can be happening here?

**Comment by janagombitova** [comment]
Tested on old data as newly submitted data does not show on the maps. All works as expected also for the 2nd round of regression tests
