### ISSUE TITLE
'Show' and 'Hide' in CartoDB maps not translated - estimated: 2

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1695]
In the Map tab for dashboards running CartoDB maps there is a 'show' and 'hide' link that opens and closes the side bar for a data point holding the answers. These two are not translated in any of the languages we have and always appear in English

**Comment by stellanl** [comment]
All the ??.properties files have translations for "Show" and "Hide", so it is more complicated than that.

**Comment by muloem** [comment]
The placeholders in the UI are correctly set?

**Comment by janagombitova** [comment]
Tested this fix for all existing languages, all are translated > can consider the test plan as passed :+1:
