### ISSUE TITLE
Import: Geocode not created, point not showing on the map - estimated: 8

### ISSUE THREAD

**Issue by Geerts** [akvo/akvo-flow#1700]
Geocode not created, point not showing on the map.
- https://uat1.akvoflow.org/admin/
-  1.9.8 UAT Folder 
- 1.9.8 MF Surveys 
- 1.9.8 MF Survey
- Form ID 69939115
- Instance: 67359126

File is attaced.
[RAW_DATA-69939115 (8).xlsx](https://github.com/akvo/akvo-flow/files/302948/RAW_DATA-69939115.8.xlsx)

**Comment by janagombitova** [comment]
I have tested this today and here is my take:
 
**For importing a new point via data cleaning**
- on the public map (after recomputing the clusters) the new points are shown, but geocode is not part of the answer
- on the private map, non CartoDB (after recomputing clusters) the new points are shown and geocode is not part of the answer
- on the private CartoDB map the new points are shown and geocode is not part of the answers
 
**For changing the location of an existing data point** (change lat and long and delete geocode in raw data report)
- on the public map (after recomputing clusters) changed points do not show
- on the private map, non CartoDB (after recomputing clusters) changed points remain in original spot
- on the private CartoDB map changed points remain in the original spot

**Comment by janagombitova** [comment]
From the planning poker meeting: 
- We allow data cleaning for data point location questions 
- No updates to the location question are reflected on the map - points remain in the same place
- This issues does not deal with issues around clustering 
- Need to make sure the updated location information is also updated in the survey locale

**Comment by janagombitova** [comment]
no longer an issue
