### ISSUE TITLE
Cartodb custom maps - only allow single select option questions when editing a custom map 

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#1711]

**Comment by janagombitova** [comment]
Here is a case I tested: 

1. Create a survey with a question group with a geolocation question and 2 option questions: 1) single select and 2) multiple selected enabled - and make sure the type of option question is indicated in the question name to make validation easier 
2. Add another question group with one option question and make this group repeatable. Also indicate in the question name
3. Collect data 
4. Go to custom maps tab > create new map
5. Select survey in dropdown and make sure you only get the single select option question in the question dropdown. The multi select option question and the option question in the repeated group are not shown in the dropdown. 

Following these steps - the fix passes.

**Comment by janagombitova** [comment]
Following the decisions shared here akvo/akvo-product-design#143 (comment) I am closing this issue as the functionality of Custom maps will not be part of Flow's feature list.
