### ISSUE TITLE
New Dashboard: UNDP Pacific 

### ISSUE THREAD

**Issue by Nikki-Akvo** [akvo/akvo-flow#1720]
**URL name**: undp-pacific.akvoflow.org 
**Application title:** UNDP Pacific Environmental Monitoring, Evaluation and Management  
**Primary contact**: Dale Young (dale.alexander.young@gmail.com) 

Can I also please be assigned Administrator rights to the new dashboard (nikki@akvo.org) 

Thank you!

**Comment by janagombitova** [comment]
moved the issue to https://github.com/akvo/akvo-infrastructure
