### ISSUE TITLE
Add Vietnamese translations to dashboard - estimated: 3

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#1728]
The partners in Vietnam want to use the dashboard in Vietnamese.
The english literals have been sent to them for translation.

We also the language dropdown for surveys just shows English/French/Spanish and does not include the  other  languages the dashboard is available in.
This causes confusion as in the app, the language for the survey in shown as "English" even though the survey is created with say "Bahasa Indonesia" as the base language

**Comment by janagombitova** [comment]
@joycarpediem I have added Vietnamese to Transifex and regarding the issue around the master/default language not showing properly, we already have a few issues for it https://github.com/akvo/akvo-flow/issues/1269 so lets deal with this one under those issues and only handle adding Vietnamese to the dashboard for this issue

**Comment by janagombitova** [comment]
From planning poker meeting: Need to add the language file to the build and also add the language to the dropdowns where the user selects the dashboard language

**Comment by janagombitova** [comment]
As @joycarpediem updated and cross check, the Vietnamese translations are 100% ready and can be added to the dashboard

**Comment by janagombitova** [comment]
passes 2nd regression round 👍
