### ISSUE TITLE
Device ID not showing directly in list 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1731]
After installing/opening the app, in the Device list on the dashboard the devices do not show with the ID but only with the IMEI number and/or phone number. We require each app to have an identifier when the app is installed so the user expect to be able to identify the phones with this ID. Many times when creating the assignment the users have the check 'phone number' number of the phone to be able to add them to a group or an an assignment. 

### What happens:
**Case 1**
During a training session for example multiple phones are connected in the same time to the dashboard. You see many devices appearing in the list, but without the Device ID. If you need to add one survey to a specific device it is impossible to find the device you need without knowing the MAC ID or IMEI.

**Case 2**
An enumerator group works collected data for a survey. Now they need to go to the field again and the dashboard administrator needs to assign the new survey to specific phones from this group. She cannot see which phones she needs as the Device ID is missing. She asks them to open the app again, the phones appear on the top of the list but the Device ID is still not there for all phones.

![screen shot 2016-07-08 at 11 44 33](https://cloud.githubusercontent.com/assets/12456965/16683787/e279b132-4501-11e6-83f4-e318ebeaeefe.png)
*with new app versions*

![screen shot 2016-07-08 at 11 57 22](https://cloud.githubusercontent.com/assets/12456965/16684061/37cd0426-4503-11e6-8212-c16d064e25a0.png)
*with old app versions*

### What is the expectation? 
Once a device is shown in the list, the Device ID is also shown right away to make it easy for users to identify the phones. 

### Potentially related issues 
https://github.com/akvo/akvo-flow/issues/1691
https://github.com/akvo/akvo-flow/issues/297

**Comment by stellanl** [comment]
I guess this could be happening in one of several different places:
1. The app could be sending the first beacon before the dev id is set.
2. The device id might not always be written to the db.
3. The dashboard might be caching things improperly.

**Comment by stellanl** [comment]
This was wholly an app issue and has been fixed there.

**Comment by janagombitova** [comment]
@stellanl wonderful, lets follow it in the mobile repository then - closing this issue
