### ISSUE TITLE
The client wrongly includes Google Maps library even if is not going to be used

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#1732]
The dashboard supports 3 maps libraries: Google Maps, Mapbox, CartoDB
If an instance doesn't define a `mapsProvider` setting the default is Mapbox, but **always** include the Google Maps library. The second problem is that this library is using a deprecated version and a missing `key` parameter.

![2016-07-08-172606_1366x768_scrot](https://cloud.githubusercontent.com/assets/178474/16692504/60833916-4531-11e6-8799-13e1759eeb7f.png)
![2016-07-08-172723_1366x768_scrot](https://cloud.githubusercontent.com/assets/178474/16692508/65d7580c-4531-11e6-86ee-7cbaa8e91b4e.png)

Changes introduced in:

https://github.com/akvo/akvo-flow/commit/0f230d4fccd9f6857e73c95a593188320dda86e1#diff-c093c46f3d3487e360605710095296e4R82

At some point we were using our `key` for including the library:
https://github.com/akvo/akvo-flow/blob/efff25cddc756f3b4e47f5a854c660a582e7afd7/Dashboard/app/dashboard.html#L41

**Comment by kymni** [comment]
According to the [google maps api documentation](https://developers.google.com/maps/documentation/javascript/error-messages) the `<sensor=false>` parameter is no longer required to be specified when including the library so I'll be removing it in the issue fix

**Comment by kymni** [comment]
## Test plan
* Reload the dashboard and confirm in the developers console that the Google maps library is not loaded unless when specified
* Confirm that warnings in @iperdomo's screen shot no longer appear

**Comment by janagombitova** [comment]
<img width="1216" alt="screen shot 2017-02-01 at 13 07 55" src="https://cloud.githubusercontent.com/assets/12456965/22506209/7c85eb26-e87f-11e6-8d6a-24ddb181df15.png">

This is what I see when opening UAT1. I assume we can confirm the implementation is ready for release

**Comment by muloem** [comment]
@janagombitova yep. good to go! 👍
