### ISSUE TITLE
Optimise retrieval of questions for report exports

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1736]
When generating reports to be used in external systems, Flow services retrieves a set of questions without options in a first call and in some cases goes on to retrieve the same set of questions with options, thus retrieving the same set of data twice.  Ideally we should merge these calls to save on the amount of reads from GAE and to keep the report generation time to a minimum.

**Comment by stellanl** [comment]
In GraphicalDataSummaryExporter.export(), we always call loadAllQuestions() [l 337] and then conditionally loadFullQuestions() [l 353]

**Comment by stellanl** [comment]
I cannot find a place where loadFullQuestions() refetches the question list.
Or did you mean somewhere else, @muloem ?

**Comment by stellanl** [comment]
Ok, apparently we parse lots of redundant info in loadFUllQuestions(); we could use BulkDataService.fetchOptionNodes() to avoid any duplication.

**Comment by janagombitova** [comment]
Test plan is missing, please make sure in the next changes there is one. I assume here the expectation is that exports are retrieved and built as they should. All export types work perfectly 👍
