### ISSUE TITLE
Devices w no Phone No are matched with wrong assignments

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#1741]
When looking for an assignment the legacy-handling code tries to find a match for the devicePhoneNo even if it is the empty string. Only null is handled.
This results in devices downloading extra surveys.
It has been exposed recently by Android 6 not allowing MAC address access and the App hotfix akvo/akvo-flow-mobile#448 which reports phoneNo as empty string also on Android 5.1

**Comment by stellanl** [comment]
Test plan: Using an (emulated) Android 6 phone, run the App against an instance where legacy assignments with empty phoneNo exist, such as  dnhmali.akvoflow.org
Check that no surveys are downloaded before an asssignment is made.

**Comment by janagombitova** [comment]
Created an assignment on UAT1 for Kasper's Android 6 phone and then asked Geert to install the app on his Android 6 phone and see if Kasper's assigned survey was downloaded to his phone and it wasn't.

👍  fix passes test

**Comment by janagombitova** [comment]
passes 2nd round of regression tests 👍
