### ISSUE TITLE
Change position of show/hide link on CartoDB maps for geoshapes

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1744]
To render a geoshape on the main map the user has to click on the Show/Hide link located above the shape. With the implementation of also rendering the location of a geotagged photo we have also introduced to Show/Hide link. 

To unify the location of the Show/Hide link with the position for both geoshapes and photos we have decided with @kymni and @Kiarii  to move the link under the geoshape map, under the geoshape information (in this case under "Points")

<img width="1209" alt="screen shot 2016-07-27 at 15 50 35" src="https://cloud.githubusercontent.com/assets/12456965/17177667/cf28f820-5412-11e6-9c75-c3b12209a50d.png">

Secondly we agreed to specify the sentence more "Show shape on map" and "Hide shape from map"

**Pending questions** 
The remaining question that came out of our discussion was if the sentence to "Hide shape from map" is linguistically correct. We will run this question by the Comms team and share the decision in a comment below.

**Comment by janagombitova** [comment]
From the discussion with Comms team the correct sentence structure should be:

Show shape on map. 
Hide shape on map.

**Comment by muloem** [comment]
@janagombitova Given the current questions around CartoDB should we put this off for later?

**Comment by janagombitova** [comment]
@muloem sure, it is a small cosmetic fix that @kymni said he can get done quickly, but as he will be off the next weeks in the field, this can easily wait.

**Comment by janagombitova** [comment]
@kymni in the spirit of healthy dev habits, can you please write a test plan for this issue? Thank you

**Comment by janagombitova** [comment]
@kymni I took a quick look at the implementation as I was curious and have two comments that you need to address before this can go out: 
- I am still missing a Test plan 
- please change the text for both hide and show geoshapes as defined in the above comment on this issue https://github.com/akvo/akvo-flow/issues/1744#issuecomment-235604388 The implementation does not follow the defined text strings

Thank you

**Comment by kymni** [comment]
@janagombitova on it. Noticed the last branch has already been merged so will create a new one to address this

**Comment by janagombitova** [comment]
@kymni still missing test plan for this issue, so for next time please make sure you add one. 

For this issue, the link is located on the correct spot and language used is as defined as well. 👍  ready for release
