### ISSUE TITLE
Upgrade GPS app to more recent version

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1749]
@joycarpediem can you please add here a description and possibly screenshot of the issue you saw.

**Comment by joycarpediem** [comment]
Most new android phones do not have the menu button anymore.
It has been replaced by the recents [square]. 
<img width="661" alt="screen shot 2016-08-03 at 8 50 39 pm" src="https://cloud.githubusercontent.com/assets/4419787/17361556/dc55df9a-59bc-11e6-8a23-69a6a4902397.png">
So all apps now has the overview built into the app (3 dots on the top right)
The version of GPS status that we are using does not have the overview button, so things like units and other GPS settings cannot be changed.

We need to upgrade the version of GPS status app that we upload to the dashboard

**Comment by janagombitova** [comment]
## Overview

Currently as part of Flow training we advise our new Flow users to install also a GPS calibration app - GPS Status. We add the apk to each new dashboard and thus is the app available to be downloaded via the dashboard xxx.akvoflow.org/gps besides via the Play Store. 

The reason why we advise to instal this app is to create the habit across our users to calibrate their GPS when being in the field. 

## Current need 

As Joy explained above the GPS Status app does not work well anymore with all Android devices. If we want to continue promoting an open source calibration app, we need to find one that can be used across new devices as well or we need to take the decision to not promote any calibration app anymore.

**Comment by janagombitova** [comment]
*work in progress* 

I have cross check with some more Akvonauts on their experience with the GPS app and here are their comments: 

- Yes this feature/application is highlighted well in the training and is used in the field a lot. This is a very helpful application for many trainees to understand how GPS works technically, and why it can be slow in the field sometimes. If a device is giving trouble getting a fix, we usually recommend clearing the agps state and downloading it again from this app.
- We recommend our partners to download and use the app
