### ISSUE TITLE
Caddisfly answers show as json string in maps

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1750]
In the Maps (public and private) in the side bar the Caddisfly answer is shown as a json string. For all from maps we should show the same answer (image and value) as provided in the Inspect data tab for consistency purposes. 

<img width="1248" alt="screen shot 2016-08-03 at 15 23 08" src="https://cloud.githubusercontent.com/assets/12456965/17392915/b4dddcb0-5a20-11e6-8758-cf67b4ac59c9.png">

![screen shot 2016-08-04 at 08 55 29](https://cloud.githubusercontent.com/assets/12456965/17393014/3c6c8974-5a21-11e6-9174-ac258640e730.png)

In this issue we need to ensure that, all Flow maps are tackled: 
- [ ] public map
- [ ] private mapbox map
- [ ] CartoDB map

**Comment by janagombitova** [comment]
in the 1.9.25 release for Carto maps the strip tests look well now, but it is still the EC tests that show the answers as a string

![screen shot 2017-11-24 at 11 39 28](https://user-images.githubusercontent.com/12456965/33207093-a8d1a0e6-d10c-11e7-9dc1-7de165f42bc8.png)

**Comment by janagombitova** [comment]
I believe this issue will be handled here: https://github.com/akvo/akvo-flow/issues/2680 as with the new maps we take the same way of showing data in the maps as in the Inspect data tab. Closing this issue and can reopen if we find the case still persisting.

**Comment by janagombitova** [comment]
Re-opening this issue as with the 1.9.38 release the problem was not resolved. In the gif below you can see the same data point in the Inspect data tab and in the Maps tab where some Caddisfly answers are rendered as a string. 

![map caddisfly](https://user-images.githubusercontent.com/12456965/46715495-81b74b00-cc60-11e8-9d38-2ba17ac8b61e.gif)

**Comment by kymni** [comment]
## Test plan
* Click on a point with EC readings caddisfly response
* Response should be rendered properly on details panel

**Comment by valllllll2000** [comment]
so most tests seem to show correctly but I have found the e-colli test still shows the old way, see screenshot:
![screenshot from 2018-10-23 16-45-58](https://user-images.githubusercontent.com/923280/47369109-434f7080-d6e3-11e8-99ae-728d9e1de826.png)

**Comment by valllllll2000** [comment]
all works now
