### ISSUE TITLE
Capture and show accuracy of data point location

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1761]
- capture the accuracy of geolocation 
- show on the app
- show on inspect data tab, monitoring and maps
- add to reports
- ? What is the value of showing geocode? Keep?

**Comment by janagombitova** [comment]
# Why 
Capturing geolocation is vital to many data collection projects as they usually focus on a household, location of a water point, farm, plantation, school etc. If Alphonso needs to go back to the place to monitor the change he relies heavily of the location of the data point. But sometimes the location is not accurate enough and he is not 100% sure if the point is only a bit off or really far away from where it is indicated. Knowing the accuracy is also helpful when analysing the data as for the person looking at the points, Petra, it is then easier to evaluate patters based on location. 

# Where changes need to happen 
- in the app when capturing data for geolocation questions - we show the accuracy but do not save it as part of the answer 
- in the app show accuracy when viewing a submitted form (submitted from the device, or synced in from another device, if accuracy is available) 
- in Inspect data tab, Monitoring tab, public map and internal map when viewing the data if accuracy is available (as with photos) 
- add as separate cell to all export types

**Comment by janagombitova** [comment]
I am reopening this issue as we are making changes to the app that weaken the accuracy rule we have and thus it is handy to know when analysing the data how accurate each point is. The value should also be sent to Lumen and shown as a new separate column. 

App issue https://github.com/akvo/akvo-flow-mobile/issues/1680
