### ISSUE TITLE
Forms of copied survey does not show to users

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1765]
### Description

If a user has permissions in a specific folder and someone makes of copy of a suvrey with multiple forms into that folder the user does not see the forms, only the survey. The workaround currently in place is to rename the forms and save the changes. The user will be able to see and work on the forms after reloading the dashboard. 
### Steps to take to recreate issue
1. Have a test user with access to folder B 
2. Copy a monitored survey (with multiple forms) from folder A to folder B
3. Log into the dashboard with the test user
4. Open the copied survey in folder B
5. You should be able to see the survey but as if it had no forms created 
### Support tickets with this issue:
- https://akvoo.reamaze.com/admin/conversations/copied-surveys-not-visible-to-certain-users
- private email from ICCO from 27 September: ... A strange issue: recently I have copied a survey into the icco instance Ethiopia folder. When my colleague in Ethiopia opens the folder and survey the survey forms (and hence the groups and questions) do not appear...

**Comment by janagombitova** [comment]
Actually, the survey does not necessarily need to be monitored (changed the name of the issue). Simply the forms do not show

The workaround is to rename the survey and forms, save the changes and then for the user to reload Flow and all works again.

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/support-for-ushhd-project

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-89344-from-kwandolowski-at-waterforpeople-dot-org

**Comment by kymni** [comment]
@janagombitova on it

**Comment by stellanl** [comment]
Does the access check depend on the path field? Because that is not reliable...

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/user-unable-to-see-all-forms-of-survey

**Comment by kymni** [comment]
PR with fix ready

**Comment by janagombitova** [comment]
All seems to work well. We will know for sure if we do not receive any support tickets with this issue. Ready for release 👍
