### ISSUE TITLE
Very large query results (>>1000) when fetching device files, gives GAE warnings about performance

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#1766]
For the /devicenotification?phoneNumber=
endpoint we get a lot of warnings like this:

com.google.appengine.api.datastore.BaseQueryResultsSource logChunkSizeWarning: This query does not have a chunk size set in FetchOptions and has returned over 1000 results.  If result sets of this size are common for this query, consider setting a chunk size to improve performance. (BaseQueryResultsSource.java:283)
  To disable this warning set the following system property in appengine-web.xml (the value of the property doesn't matter): 'appengine.datastore.disableChunkSizeWarning'

**Comment by janagombitova** [comment]
@stellan after talking with @muloem about our invoice situation, he mentioned you both identified this issue as a potential cause. Can you take a look at it as well and see if you can get a fix in? Thank you

**Comment by stellanl** [comment]
First question is which query is that big.
In DeviceNotificationRestServlet, we call two methods:
a. DeviceFileJobQueueDAO.jobDao.listByDeviceId(device);
b. DeviceFileJobQueueDAO.jobDao.listByUnknownDevice();

There are 1012 Devices, 63687 DeviceFiles and 	 	
(right now) 9224 DeviceFileJobQueue entities in the db, so >1000 returns for a query is quite possible.
A quick look indicates that more than half the DeviceFileJobQueue has a null deviceID, and are .jpg files.
So, quite possibly >5000 pictures to be synched to the devices. This problem is not transient...

b. eventually calls BaseDAO.listByProperty("deviceId",null,"long",null,null,"==","DeviceFileJobQueue")
where the query is executed.
Setting a large chunk size for all queries feels like a bad idea, so we will need lots of parameters or a method to set it for a particular use in a BaseDAO subclass.

**Comment by stellanl** [comment]
The title is a bit misleading, this does not cause timeouts; we just get a warning in the log that we are doing something inefficient. The only way I see to avoid the warning is to fetch the result in chunks of <1000 at a time, and append them to the long list, before we return it, but it will still take a long time.

An optimised solution would be to only tell the app things it does not already know. This could be implemented by the app asking for "all device files added or modified since time t" and if the fetch succeeds it remembers the server time until next fetch.
