### ISSUE TITLE
Deleting approval group happens without confirmation

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1769]
Currently if a user deletes an approval group it gets removed right away without any confirmation. This can cause accidental deletes. When deleting a approval group a confirmation window should be triggered before we delete the group to ask the user whether we really wants to delete it or not. 

@loic and @kiarii I think we need a consistent way across Flow dashboard when it comes to handling deletion, how the icon looks like and what does clicking on delete trigger further. Can you look into it please? Thanks

**Comment by Kiarii** [comment]
Our suggestion is to use a confirmation dialog, to keep it simple for now, and rethink about it globally for the refactor given the complexity of the deleting context;

some contexts can use the icon alone, with no confirmation, others need the confirmation, the contexts are more than 20 - for all the entities that can be created in flow (users, devices, questions, surveys, forms ...) its that complicated
