### ISSUE TITLE
Assign responsible users to an approval group in a survey

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1774]
#### Assign responsible user to an approval workflow

In the survey definition after the user selects a workflow here is also the place where the user will define which dashboard user is responsible in implementing the workflow step. We have decided not to add this user permission in the general Users tab because: 
- one workflow can be used in multiple surveys what makes the user selection complex
- a particular user John is responsible to implement one step is survey A but not in survey B
- the user adds a workflow to a survey in the survey definition and we expect him to make the decision on who is responsible at this point of time as well

**Details:** 
- please follow the mock ups and functional design doc
- when viewing selected workflow in the survey definition each step holds a clickable link 'Responsible user'
- after selected a list of users is rendered - only users with 'View data' permission for this survey
- users are selected and assigned -> only the user who is selected for implementing a step will have the power to implement the workflow step on the datapoint in the Monitoring tab 
- you can only assign one user for an approval step 
- if one user is assigned to be responsible for one step, then all steps have to have a user assigned 
- one user can be responsible for more steps in one group per one surveys
- an approval group does not have to have responsible users > then all dashboard users with View data permissions can verify the data in the Monitoring tab

https://github.com/akvo/akvo-product-design/issues/82

**Comment by janagombitova** [comment]
@muloem this is one of the items we need to focus on first (have for next week)

**Comment by janagombitova** [comment]
## Notes from test round 1

Tests done on https://akvoflow-dev3.appspot.com/admin/ v1.9.10-213-g1023882 

### 1) User list blank after navigating away from page
Hi Mulo, I think something broke. I was creating a few users to see how the interaction goes when selecting responsible users for an approval step. So I wanted to create users who do not have access to the survey I was working on and check they do not show in the list. 
After creating the users, I needed to create the permission. I came back to the user list to give these users the permission I wanted and the user page was blank. However, once I logged in with one of the emails, my user worked fine and could access the dashboard. 

![users](https://cloud.githubusercontent.com/assets/12456965/19641648/e29a9dfe-99e1-11e6-9b80-3207cc2839d8.gif)

### 2) Cannot add responsible users 

Mulo, I could not add responsible users at all...  Once I clicked on the little user icon next to a step, the Loading icon showed for a second and nothing happened. But Flow did not crash with this action as it did up till now

### 3) No Manage data approval permission 

I am not sure if I was supposed to test this one already or not, but if so, then I just wanted to let you know that there was not such option to work with in the permissions list

**Comment by janagombitova** [comment]
## Notes from test round 2

### 1) User list blank after navigating away from page
- solved 👍 

### 2) Cannot add responsible users
- can see the list of current users now when clicking on the user icon. After saving the changes all is saved properly and even after reloading Flow full all is saved as wanted - that is all good. We can think of design improvements later in the future 👍 
- I can now select more than one user per step. Is this intentional? 
- I can select from all the users on the dashboard, regardless of the fact that they do not have view data rights to this survey. Ideally I should only see users who can view the collected data for this particular survey

### 3) No Manage data approval permission
- not relevant for this issue - ignore me here 

### 4) No data loading in Monitoring tab
- I had a case where data was loading Ok. Then I wanted to recheck something so I opened an Incognito window and tried to load the data again without luck. this time I received this error 
<img width="1269" alt="screen shot 2016-10-24 at 17 36 32" src="https://cloud.githubusercontent.com/assets/12456965/19652291/8b2256be-9a10-11e6-9a38-9ed8c5c62457.png">
- Then i tried again after loading data for another survey and it worked fine. Odd 

### 5) Approving data as a responsible user 
- still trying to get data to show... will update in a next comment

**Comment by janagombitova** [comment]
### 4) No data loading in Monitoring tab 
![monitoring](https://cloud.githubusercontent.com/assets/12456965/19652755/47f771ec-9a12-11e6-9164-dbb5376de9e5.gif)

**Comment by janagombitova** [comment]
### 5) Approving data as a responsible user 
- if I can only approve one step - all works smoothly (being able to approve what I can, and not being able to approve what I cannot)

### 6) Adding responsible users to another survey 
- If I have 3 surveys where I use one approval group > I add the group to survey 1 and add users for those steps 
- I open another survey and add the same group, what happens is that the users are already selected in the same way as in the 1st survey > they should not be as it then

**Comment by janagombitova** [comment]
## Notes from test round 3 

### 2) Cannot add responsible users
- I can still select users who do not have permissions to the surveys I am working on, so this still needs to be resolved 

### 4) No data loading in Monitoring tab
- seems to be fixed - or at least I cannot reproduce the problem anymore 👍 

### 6) Adding responsible users to another survey
- skipped for tonight, but will need to be resolved for later 

### 7) Changing already saved responsible users
- fixed - works like a charm 👍 

So we still will need to go through the remaining on 2 and 6

**Comment by janagombitova** [comment]
## Notes from test round 4

(new list based on above comments and latests experience) 

### 1) Can add all users to approval step 
I would only want to see those users in the list who have view data rights to the survey I am working on.  The contrast between the black font and dark grey background makes it hard to read the user names. @loicsans would you have time to look at the design of this latest addition to the approval family? Thanks 

### 2) Super users cannot approve steps
If you are a super user in our backend user list, you cannot approve, reject, or make a data point pending. It feels as if, because I did not give myself the right to approve data - I cannot do so, what makes sense considering all our users who will use the feature will be part of the user list. But for support purposes it might be helpful if we super admins can make changes to approval steps regardless of being a responsible user or not. 

### 3) if not user was assigned as responsible, no one can approve a step 
If you have added an approval group to a survey and did not assign any responsible users, you go to the monitoring tab and no one can approve the steps. Is this intentional to force users to assign those responsible? 

If so, I will note down the question: if no user is given the responsibility, should anyone be able to approve step? and add it to the information we need to verify from SNV once they start fully using the feature.

### 4) user could not approve steps
We had a case with the SNV call, where I followed these steps: 
- created and approval group of Steps A to Step D and experienced this problem https://github.com/akvo/akvo-flow/issues/1797 (So ended up with Step A, Step B, Step C, Step B, Step D in the survey)
- added the approval group to a demo survey
- added a few users to approval steps 
- created a new user on the dashboard and gave her full admin rights to all dashboards 
- added her as responsible for Step B (the one where the deletion problem happened) 
- user on Step A approved a few data points for Step A
- she logged into the dashboard via an incognito window, opened the monitoring tab, selected the survey and saw the data points 
- once she found a data point that was approved on Step A and now she should be able to approved on the Step B - she did not have the option and it appeared as if she was not responsible at all

### 5) Adding responsible users to another survey
If I have 3 surveys where I use one approval group > I add the group to survey 1 and add users for those steps. I open another survey and add the same group, what happens is that the users are already selected in the same way as in the 1st survey > they should not be as it then

**Comment by muloem** [comment]
> 1) Can add all users to approval step
> 2) Super users cannot approve steps

I will create separate issues to handle the above.


> 3) if no user was assigned as responsible, no one can approve a step
>> If you have added an approval group to a survey and did not assign any responsible users, you go to the monitoring tab and no one can approve the steps. Is this intentional to force users to assign those responsible? 
>> If so, I will note down the question: if no user is given the responsibility, should anyone be able to approve step? and add it to the information we need to verify from SNV once they start fully using the feature.

Yes.  The fact that no user is able to approve is intentional indeed we should go back to SNV with the question. Otherwise the security of having an approval is redundant if everyone can approve at the moment the approval is assigned.


> 4) user could not approve steps

We will have to retest this but I believe that after having resolved the issue https://github.com/akvo/akvo-flow/issues/1797, this should not happen.


> 5) Adding responsible users to another survey

I have created another issue to resolve this https://github.com/akvo/akvo-flow/issues/1858

**Comment by janagombitova** [comment]
@mulo ok. sounds like a plan and yes, lets wait and see what feedback we get from SNV after the 1st months.

**Comment by janagombitova** [comment]
@muloem Adding the responsible users works fine. I could not test out the actual approving of steps and if the user is truly limited to only the steps he is responsible for due to this issue: https://github.com/akvo/akvo-flow/issues/1880

**Comment by janagombitova** [comment]
After successfully testing with 3 different users and having separate issues for the above points, we can say this implementation is ready to go 👍
