### ISSUE TITLE
Export crashes w NPE if option question has no options

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#1779]
Related to #362.
If an OptionQuestion has no defined options at the time of a data export (with QuestionIds enabled) this is not handled and an NPE is thrown at GraphicalSummaryExporter.createRawDataHeader (L1143).

I suggest outputting a header for the (empty) column that indicates the problem (it could be happening in several places), but we might return a helpful error message instead.

**Comment by stellanl** [comment]
Test plan:
Create a question without options. Order a raw data report (importable format).
Report should be generated & notification email sent.

**Comment by janagombitova** [comment]
After testing this seems to still not work, as I am not getting an export for a form where I created an option-less question

**Comment by janagombitova** [comment]
👍  works

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/akvoflow-support-request-number-145364-from-geert-at-akvo-dot-org
