### ISSUE TITLE
Exports fail silently

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#1780]
As was the case for #1779, if a bug or corrupted data causes the export to fail, nothing is returned to the user. They then have to wait, retry and finally give up and report it before we are made aware of it.
It would be better to send an email informing them that it had failed and where to report this.
And/or we could send to flowerrors@akvo.org, like we do for failed device file imports.
See also #1304

**Comment by janagombitova** [comment]
Closing this issue as we will handle it in the new UI: https://github.com/akvo/akvo-flow/issues/2543
