### ISSUE TITLE
Confusion when deleting form with questions and data 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1781]
When deleting questions, question groups, forms and surveys where data collection has already taken place we have an inconsistency in the UX and the interaction causes confusion. The rule that we have in place is that you cannot delete anything if there is data collected for it, but in the UI you can delete a form (you get the deletion confirmation message) but after reloading the dashboard the form is still there and fully available. What is good, because we should not allow to delete a form that has data but the UX is confusing. 

**Steps taken** 
1. Open a survey that has data collected 
2. Try to delete one question > you receive a message that it is not possible 
3. Try to delete a question group > you receive a message that it is not possible 
4. Try to delete a form > you receive a confirmation that this is done, the form is not shown on the UI anymore 
5. Go back to the survey and the trashcan icon is shown > delete the survey > you receive a empty confirmation message and survey is removed from the list 
6. Reload the dashboard and the survey is still in the list, so is the form and all questions 

**Example case**  
![deleting form](https://cloud.githubusercontent.com/assets/12456965/19145122/b81380ba-8bad-11e6-8743-874f606039cb.gif)

**Proposal**
- I think we need to disable the form delete button if there are questions and question groups added to the form in the 1st place 
- currently is you even have a form with no data but with question groups and you do not remove those first, but you delete the form - it will still come back after reloading the dashboard. By disabling the delete icon, and only having it enabled if the form contains nothing, we will avoid confusion
- considering the user cannot delete a question group or question if there is data, and if he cannot delete the form because there are still questions and the delete icon is not enabled we will deal with 2 confusions at one shot

@Kiarii and @muloem What do you think?

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-28243-from-pvanbussel-at-agriprofocus-dot-com

**Comment by Kiarii** [comment]
This is indeed a tricky one; my opinion would be to allow the deletion of a form with content but with a clear confirmation that the content will be lost as well. I am just thinking that if a user really needs to delete a form, then they should be able to do it simply without having to first delete all its content first.. 

The use case I suspect might differ if data has been collected with the form, or does that matter?
