### ISSUE TITLE
Timeout while retrieving the devices list

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1803]
Retrieval of the devices list times out on instances where there are a large number of devices.. e.g. 1,600 devices as an example.  We need to optimise the devices retrieval.

**Comment by muloem** [comment]
# Test Plan

1. Access an instance that has a large number of devices and ensure the device list loads

**Comment by janagombitova** [comment]
The list of devices on UAT loaded much faster that I am used to so I take this as a sign the implementation passes the test plan 👍

**Comment by janagombitova** [comment]
@muloem I think I found a bug. my Device lists loads super fast but only shows me one device in all the rows. I have 2 phones connected to the dashboard at the moment and there were more before. 

![screen shot 2016-11-01 at 16 01 53](https://cloud.githubusercontent.com/assets/12456965/19894263/a2790dac-a04c-11e6-8cef-ea04a08be09b.png)

**Comment by janagombitova** [comment]
@muloem issue is still present in testing - there is still just one device showing in the full list. Secondly I have been trying to reconnect 3 different phones to the dashboard and the list does not show any of these phones (on in the current case one phone a lot of times) as if it does not recognise they connect (cannot see them in the device list dropdown when creating an assignment) 

Using manual download of a form works fine though as well as uploading data. Even after downloading a form the device list does not show the most recent device.

**Comment by janagombitova** [comment]
List loads, also show the latests connected device and I am getting a list of different devices 👍
