### ISSUE TITLE
Several instances missing email configuration

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#1807]
These instances cannot send email and must be configured:
- [x] akvoflow-104
- [x] akvoflow-105
- [x] akvoflow-106
- [x] akvoflow-107
- [x] akvoflow-108
- [x] akvoflow-109

This involves creating a reports@akvoflow.org user and logging in with it to add the address to the "authorized email senders" setting.

**Comment by stellanl** [comment]
Test plan:
From the (page previously known as the) dashboard, **DEVICES** tab, **MANUAL SURVEY TRANSFER** subtab, pick a survey and select a form. Fill in your email address. Press SEND FILE. You should get an email within a minute,

**Comment by janagombitova** [comment]
Checked all dashboards and bootstrap files are sent out properly. Issue closed 👍
