### ISSUE TITLE
Validate that Caddisfly test type is selected 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1808]
![caddisfly](https://user-images.githubusercontent.com/12456965/38922460-818989d2-42f8-11e8-9f4e-6742b7a6917c.gif)

At this moment if a user creates a survey and adds the Caddisfly question to it, she can save the question without specifying which test type she wants to measure. This however breaks the experience when in the app, as the Caddisfly app does not know which test to open and then says the question is not supported.

To avoid the user seeing when in the field that she cannot test the water quality we should enforce her to select the test type before saving the question. So the Caddisfly question type can only be saved if a test type is also selected 

We should use the same pattern as here: https://github.com/akvo/akvo-flow/issues/2221

**Comment by kymni** [comment]
Tackled under #2959

**Comment by kymni** [comment]
## Test plan
* Create caddisfly question type.
* Confirm you can't save question until you've selected a question type

**Comment by kymni** [comment]
Works
