### ISSUE TITLE
Caddisfly dropdown remains in changed question

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1809]
Once a user creates a survey and decides he wants to use it as a Caddisfly test. He sets it all up and saves the question. Then he changes his mind and realises he would go better with just taking an image of the water sample at this stage. One way would be to delete the question and create a new one instead. But he can also just change the question name and question type. If he does so, the Caddisfly test dropdown will remain in the screen. 

![screen shot 2016-11-02 at 14 15 57](https://cloud.githubusercontent.com/assets/12456965/19930074/01e23fc4-a107-11e6-815f-c3821ed858d2.png)

After saving the question (still with the Caddisfly dropdown in there) the user publishes the survey and receives it on his phone.  On the phone the question type is set up properly without any Caddisfly interruptions.

**Comment by bogere** [comment]
##test plan
**  first select caddisfly question type and you will see caddisfly test dropdown.
**  then later change  to another question type such as free text or photo or video.
** the caddisfly test dropdown  will not show up
** it has disappeared

**Comment by janagombitova** [comment]
@muloem is this also part of the latest UAT1 build?

**Comment by janagombitova** [comment]
I guess yes at is was merged and it seems to we working ok on the online workspace
