### ISSUE TITLE
Remove obstructive dependency from appletBuild.xml class path

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1812]
The `appletBuild.xml` file defines the build of the `exporterapplet.jar`, which containing all classes needed for building the reporting component of Flow services.  In the class path of this file we include `war/WEB-INF/classes` which are build classes from the `akvo-flow/GAE` build process. However, this results in the exclusion of some necessary dependencies from the `exporterapplet.jar` if the GAE build has been run prior to running the `exporterapplet` build.

We also do not need the exporterarpplet.jar binary itself  in the repo as this can be rebuilt whenever required.

**Comment by osg74** [comment]
The rest of the dashboard components build as expected after removing the exporterapplet.jar.

**Comment by janagombitova** [comment]
@muloem still cannot get reports from Flow services

**Comment by janagombitova** [comment]
after speaking with @osg74 who explained this is a build issue and not related to the data exports, I assume we can consider it ready for release as done above.
