### ISSUE TITLE
Missing app version number in Device list

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1819]
Currently once a device connects for the 1st time with the dashboard we do not show the version info (app version) right away in the Devices list. Once the app is closed and re-opened again the version number is shown in the dashboard. 

![screen shot 2016-11-03 at 17 47 47](https://cloud.githubusercontent.com/assets/12456965/19975939/1e3fb010-a1ee-11e6-9398-89f1aab0a994.png)

Many partners who manage the data collection check the version number to see which phones have updated to the new app and the version can be useful in support cases as well (if a fix has beed released in a particular version, but the user is still running a older version of the app). It would be more handy if the version number is shown consistently. 
 
More research needed to understand in what cases the version number is shown and when not.

**Comment by stellanl** [comment]
I did a little digging into where this could happen.

The app starts 7 services
* SurveyDownloadService (delayed until username obtained)
* LocationService (defaults to off these days)
* BootstrapService
* ExceptionReportingService
* DataSyncService
* ApkUpdateService
* TimeCheckService

 of which only 3 sends the app version to the back end:
* SurveyDownloadService (both when checking for surveys and when fetching info about a specific survey)
* LocationService (always)
* DataSyncService (both when getting notifications and after successfully uploading a file)

**Comment by stellanl** [comment]
While investigating this I also noticed that a second cause of the problem in #1731 is still around. The DtaSyncService still starts before deviceId is set, so it gets set to empty for a while.

**Comment by stellanl** [comment]
Test plan:
Install app on a device. It should never show up in the list without an app version.

**Comment by janagombitova** [comment]
👍  Implementation works like a charm for both new devices and also old timer dinosaurs :)
