### ISSUE TITLE
/remoteexception calls failing

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#1823]
Logs are full of /remoteexception calls returning 500.
Either the backends are rejecting ok calls or (/and?) the apps are making broken calls.
Interestingly I found a single successful call in akvoflow-37, which was from an Android 4 phone, all others were from Android 5 phones and failed.
It could also be possible that there are a few phones with a corrupt/unacceptable-in-http stacktrace file that keep nagging the servers, since that stacktrace is not deleted until a POST succeeds

**Comment by muloem** [comment]
@stellanl could you confirm that all the calls to this endpoint have the parameter `action=saveTrace`

**Comment by stellanl** [comment]
It cannot be seen in the logs, since the parameters are in the body, not the URL.

In the app code, that part of RemoteExceptionService is unchanges since (at least) 2014, and defines:
private static final String ACTION_PARAM = "action";
private static final String ACTION_VALUE = "saveTrace";
This pair is added as the first post parameter.

**Comment by stellanl** [comment]
I have successfully uploaded "stacktrace" files from an Andoid 4.3.3 phone and an A5 emulator to akvoflowsandbox.
I see two avenues for further research:
 * Get the stacktrace file from one of the failing devices by asking the user to send it to us.
 * Test with a real Android 5 phone to see if it could be a problem with (say) some released version of the  http(s) library. I don't currently own one to try with.

**Comment by stellanl** [comment]
Got a "failing" stacktrace from Valeria. Nothing weird about the file.
Only suspicious thing I have found so far is that the SimpleDateFormat objects that create *and* parse the 'date' parameter both use default locale.

**Comment by stellanl** [comment]
Have added logging of all parameters and deployed to akvoflow-dev2.

**Comment by stellanl** [comment]
Ok, this is yet another Android 5 (privacy) consequance.
The phoneNumber parameter is sent as blank, and the backend cannnot handle that.

**Comment by stellanl** [comment]
Additionally, the device now always sends an androidId parameter, but we do not save that info

**Comment by stellanl** [comment]
Test plan:
On an Android 6 phone or emulator, place a text file in the stacktrace directory. It should be be deleted after it has been uploaded to the backend.

**Comment by janagombitova** [comment]
released in hot fix
