### ISSUE TITLE
Multiple translations do not show in survey export 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1828]
Currently you can translate a survey form into an unlimited number of languages. These are then shown to the enumerators in the app, where he can select in which language he wants to see the questions (or in multiple). Secondly, the user also sometimes downloads the survey form via the **Export survey form** feature. Then he receives the form in a excel sheet and he usually uses this feature to cross check the survey structure or to do a few test data collection rounds paper based.

For both cases the user wants to not only see the survey structure but also the available translations. Currently, if you have a translation to the survey and you download the survey via Export survey form, you see  both the original text and translation in one cell as `original text / translation` (example: `What is your name / Ako sa voláš?`) 

However, if you have a form translated in multiple languages (more than one), you cannot currently export those. You see the translation of only the 1st language. There is no way for the user to download all the translations to the survey and/or there is no way for the user to decide which language he wants to see downloaded. 

![screen shot 2016-11-07 at 15 38 23](https://cloud.githubusercontent.com/assets/12456965/20063276/d16d203a-a506-11e6-9ff6-8afce831311a.png)

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/akvoflow-support-request-number-31482-from-tobias-dot-brehm-at-welthungerhilfe-dot-de

**Comment by stellanl** [comment]
Tested ok on standalone exporter. Does not seem to work on -uat1

**Comment by stellanl** [comment]
After 1.9.34 deployment, tested ok on -uat1

**Comment by janagombitova** [comment]
Confirmed 👍 works well
