### ISSUE TITLE
Enable clicking on the question text to edit a question

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1831]
When editing questions in the survey editing window, the user has to click on the *Edit* link in order to edit the text of a question.  From observing a number of users, they seem to try to edit the question by clicking on the question text.  In terms of user experience, it may be better to make it possible to click on the question text.  ~~Similar changes could be realised with editing question groups as well.~~

**Comment by janagombitova** [comment]
@kymni missing a test plan here. Please make sure you to not forget this next time. For now I have created on myself

## Test plan 
1. open an existing survey and click on the question name, it should open for editing 
1. make sure the editing icon still works as well 
1. see if above rules apply also for new questions 

## Test
👍  implementation passes. I would like us to make one more improvement. Maybe @kymni you can align with @loicsans on this. I have created a separate issue for it here: https://github.com/akvo/akvo-flow/issues/1996

This change is ready to go out into the world.
