### ISSUE TITLE
Change the word "dashboard" 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1842]
In the beginning of 2017 we will move away from using the word "dashboard" in the context of Flow. The main reason is that the meaning of the word "dashboard" does not fit properly with what is done on the web app. Secondly, with Akvo Lumen taking shape the end product of Lumen will be dashboards with data visualisations. To avoid confusion in documentation, sales, and users we will select a different word in Flow context. 

The aim of this issue is to find all places on the Flow web interface where the word "dashboard" is user visible, and then change it to the new word or even remove it if not needed. 

## New word to use: 
Online workspace

## Locations that need to be changed (plus items to cross check in testing)
* [x] In the browser tab heading for Chrome - only have Akvo Flow 
* [x] in Safari's Favourites list - only have Akvo Flow
* [x] in the Users tab, 1st sub tab states Dashboard users - change to Users  

## See images below for more detail: 

<img width="596" alt="screen shot 2016-11-24 at 12 32 33" src="https://cloud.githubusercontent.com/assets/12456965/20597386/9e0e805e-b243-11e6-8577-d598d2088a02.png">

*Chrome's browser tab* 

<img width="346" alt="screen shot 2016-11-24 at 12 44 33" src="https://cloud.githubusercontent.com/assets/12456965/20597468/1f3ce544-b244-11e6-9192-6eec1017d3af.png">

*Safari's Favourites*

<img width="284" alt="screen shot 2016-11-24 at 15 18 14" src="https://cloud.githubusercontent.com/assets/12456965/20601515/523024a6-b259-11e6-9277-0a148f9afdae.png">

*Users tab*

**Comment by bogere** [comment]
hey @janagombitova  or @muloem , in windows we do not have Favourite lists like Mac computer, so i think bookmark is the same

**Comment by bogere** [comment]
The develop branch does not   have the users tab.
![akvo](https://user-images.githubusercontent.com/7900382/32595656-c532c28c-c541-11e7-969d-d278d658a2d0.PNG)

 so i cannot  make this change in the Users tab, 1st sub tab states Dashboard users - change to Users

**Comment by bogere** [comment]
## test plan
* look at the title in  the browser tab heading for Chrome
* The word "dashboard" has been removed from browser tab heading

**Comment by janagombitova** [comment]
All good. Even is Safari the changes are reflected 👍  ready to go
