### ISSUE TITLE
Syncing imported data points error

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#1843]
When on mobile clients you attempt to sync a monitored survey right after importing manually created data (with the data cleaning tool) then the imported datapoints are corrupted.

Here is the issue on mobile https://github.com/akvo/akvo-flow-mobile/issues/526

After some testing I saw that what the API returns is an empty datapoint without any answers, example:

`{"surveyedLocaleData":[{"id":"e57u-g3hq-m79d","displayName":"","identifier":null,"lat":null,"lon":null,"surveyInstances":[],"surveyGroupId":98729115,"lastUpdateDateTime":1479985176732,"keyId":null}],"message":null,"offset":0,"code":"200","resultCount":1}`

**Comment by janagombitova** [comment]
I have tested this issue again as you mentioned here https://github.com/akvo/akvo-flow/issues/2229 that it might be resolved with the changed in the linked issue, and I am not getting the problem anymore. All the data points and answers sync in properly.

Thus closing this issue for now and will reopen if we meet the problem again
