### ISSUE TITLE
Improve UX around Log in/Log out link

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1846]
Currently the Log in/Log out button is located in the footer of the dashboard, hidden with links to download the Flow app and support, etc. The need is to find a more straightforward location for this link, so the user can find it easily and intuitively.  

![screen shot 2016-11-28 at 15 19 53](https://cloud.githubusercontent.com/assets/12456965/20671585/2c365e14-b57e-11e6-8f48-c2af1e8f12ae.png)

**Comment by loicsans** [comment]
Swap language dropdown with logout call to action and move login to header on public page

**Comment by janagombitova** [comment]
I like the swap, but there is one thing that you need to change. Now the language dropdown in visible when the user is not logged in. This should not be shown, as the public page is only in English and language option are only available after logging in. 

I am a bit uncomfortable that we now have documentations, terms and conditions and language all packed in the footer together and I agree with your idea for a "admin" page in the future. For now, could we somehow divide the footer (in a separate issue)?

**Comment by janagombitova** [comment]
I love the new location of the log in/log out. ready to roll 👍
