### ISSUE TITLE
Support link double in footer

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1847]
Currently the footer holds these items: 
- app link
- release notes 
- contact for support 
- support documentation 
- terms of service 
- logo, version, copyright 
- log in

There are two links pointing to the Flow support page: **Support** and **Documentation and user guides**. We should find a way how to point to the support page using one link only. Two are not needed. 

![screen shot 2016-11-28 at 15 27 37](https://cloud.githubusercontent.com/assets/12456965/20671833/36cba3d8-b57f-11e6-8a60-d1cc12916d39.png)

We can remove on of the link for **Documentation...** and rename **Support** to `Help & Support` as we have it on akvo.org

**Comment by loicsans** [comment]
Unify these 2 to read: "Help and support"

**Comment by janagombitova** [comment]
Can you also change Download FLOW app to `Download Flow app`

**Comment by janagombitova** [comment]
Another item: can we shorten "News and software updates"? It points the users to our release notes.  Can we use only `Software updates` ?

**Comment by janagombitova** [comment]
@loicsans I was looking at Flow's footer (the location of the language dropdown change which you showed me a few weeks ago was still bugging me) and RSR's footer and realised we first of all are not in sync with how the footers look and what is shared there and secondly, that we have a combination of technical and user information in one centred in space. 

Current Flow's footer (with the changes we agreed upon above) holds there items: 
- Download Flow app - user action
- Software updates - technical info
- Help and support - technical info 
- Terms of service - technical info
- akvo.org - general Akvo
- language dropdown - user action
- version + copyright - technical info

I have two questions:
1. Have you considered finding a unified structure for Flow, RSR webpage and eventually Lumen for how to footer looks like and is arranged?
1. Can we somehow divide these different buckets of information in the footer to have more clarity and visual distinction? 
   - now to footer is on two lines taking up quite some space on the bottom of the page 
   - the links are all centred with no clear distinction between the items 

![screen shot 2017-01-25 at 10 21 20](https://cloud.githubusercontent.com/assets/12456965/22284532/0b120ba6-e2e8-11e6-95a9-382c22282c29.png)

**Comment by janagombitova** [comment]
## Test plan

1. Make sure only 1 support link in footer 
1. New names given to the links as suggested above 
1. Cross check all links work 

The location of the language dropdown in dealt with in this issue https://github.com/akvo/akvo-flow/issues/1920

👍  Have I said already that I love the new footer. Implementation passes test plan
