### ISSUE TITLE
Remove duplicated elements across dashboard

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1850]
Currently there are a few elements across the dashboard that do not have any purpose, provide no new information to the user or guidance, and are duplicated. With this issue, we will identify these elements and remove them all at once. Simplify. Declutter. Simplify. 

![screen shot 2016-11-28 at 16 51 09](https://cloud.githubusercontent.com/assets/12456965/20674980/14650cb0-b58b-11e6-9135-042ab6020834.png)
*(example of a duplicated submenu and page title)

**Comment by janagombitova** [comment]
## List of duplicated page titles and submenus 

* [ ] Manual survey transfer 
* [ ] Bulk upload data 
* [ ] Data cleaning 
* [ ] Charts vs Chart Builder
* [ ] Export reports vs Export Data 
* [ ] Messages

**Comment by muloem** [comment]
@janagombitova most of this is done except the duplication of form names.. However in this case I am not sure whether we should remove it, given that longer form names are cut off in the upper tab.

**Comment by janagombitova** [comment]
@muloem thanks for the heads up. Maybe lets deal with the form names in a separate issue, to see what the best approach would be regarding those tabs

@loicsans do you agree?

**Comment by muloem** [comment]
I took the four screen shots below. Just wondering whether we want to maintain some kind of consistency in the subtitles in the different tabs.

<img width="771" alt="screen shot 2017-02-27 at 11 08 57" src="https://cloud.githubusercontent.com/assets/533336/23357399/e1f10b68-fcdd-11e6-9950-9c7ae2ea417d.png">

---

<img width="747" alt="screen shot 2017-02-27 at 11 10 30" src="https://cloud.githubusercontent.com/assets/533336/23357417/f35b32a2-fcdd-11e6-90a8-0b49e8d47121.png">

---

<img width="632" alt="screen shot 2017-02-27 at 11 09 23" src="https://cloud.githubusercontent.com/assets/533336/23357409/e87a38d8-fcdd-11e6-953a-124f6fca411b.png">

---

<img width="760" alt="screen shot 2017-02-27 at 11 09 35" src="https://cloud.githubusercontent.com/assets/533336/23357413/ee3030f2-fcdd-11e6-950b-906ed1c579d9.png">

**Comment by janagombitova** [comment]
@muloem the dropdown headers are going to be handled in this issue: https://github.com/akvo/akvo-flow/issues/1851 as we tried to break down the tasks as much as possible

**Comment by muloem** [comment]
@loicsans @janagombitova not so much the dropdowns but the subtitles... e.g. _Choose survey data to display_ Its different font and size on different tabs.

**Comment by janagombitova** [comment]
@muloem yes indeed, but @loicsans needs to see if the subtitles are even needed there as they are a duplicate of the message in the dropdown itself. Let's handle it in the issue mentioned above.

**Comment by janagombitova** [comment]
I find this a subtle and good improvement but it also reveals quite some issues on the general layout of the pages. This must be tackled for the release as well. I have added my comments to the issue here: https://github.com/akvo/akvo-flow/issues/1852#issuecomment-284018388
