### ISSUE TITLE
Improve overall grid/layout of dashboard UI

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1852]
Grid / Layout: fix general problems of misalignment and spacing as well as responsiveness to different devices.  Investigate if using an existing css based framework would be beneficial.

**Comment by janagombitova** [comment]
Here is one for the layout that needs attention. In the Export reports there seems to be an empty space... 

![layout](https://cloud.githubusercontent.com/assets/12456965/22503138/a648505c-e870-11e6-9dbc-5a4034348793.gif)

**Comment by janagombitova** [comment]
Another item to improve - in the Assignments page the is a large white space 

<img width="1260" alt="screen shot 2017-02-21 at 17 22 24" src="https://cloud.githubusercontent.com/assets/12456965/23173742/71101f60-f85a-11e6-83da-c60a1bec3db0.png">

**Comment by janagombitova** [comment]
Not sure this issue belongs here or should be a separate issue @loicsans but I found a problem when the survey name is very long it breaks the layout in the Assignment page. See below: 

![a](https://cloud.githubusercontent.com/assets/12456965/23174191/dd1b4666-f85b-11e6-8ef8-c1680946b43a.gif)

**Comment by janagombitova** [comment]
Another layout problem
In the Inspect data tab, when the dropdowns are drilled down the 2nd line overlaps with the filters 
<img width="1206" alt="screen shot 2017-03-03 at 16 39 06" src="https://cloud.githubusercontent.com/assets/12456965/23557378/2aa1aa84-0030-11e7-8a91-5f0bbe4a84ca.png">

**Comment by janagombitova** [comment]
And here are some places where there is unnecessary white space now, also do to the removal of duplicated elements 

<img width="1039" alt="screen shot 2017-03-03 at 18 20 23" src="https://cloud.githubusercontent.com/assets/12456965/23561600/33dfb5f0-003f-11e7-98df-eb696d263cbc.png">

<img width="1037" alt="screen shot 2017-03-03 at 18 21 45" src="https://cloud.githubusercontent.com/assets/12456965/23561609/3ef9afb8-003f-11e7-9a94-ff39b87a9302.png">

<img width="1072" alt="screen shot 2017-03-03 at 18 27 07" src="https://cloud.githubusercontent.com/assets/12456965/23561614/472509ee-003f-11e7-892f-6f964f6a3f2d.png">

**Comment by janagombitova** [comment]
@loicsans what was the motivation to make the location of the footer set on each page? I feel as a lost quite some workspace with this change (also because of the multiple levels of headers we have) 

Here is a list of issue I found so far when looking at the layout on **beta1** 

### 1) Survey breadcrumb
If the folder/survey breadcrumb reaches two levels it overlaps the 1st item in the list, making it hard to select, open or use
<img width="1253" alt="screen shot 2017-03-10 at 14 01 08" src="https://cloud.githubusercontent.com/assets/12456965/23796224/2a5e4b80-059a-11e7-9746-db89cf7bbb7b.png">

<img width="1074" alt="screen shot 2017-03-10 at 14 02 27" src="https://cloud.githubusercontent.com/assets/12456965/23796238/390b3b0c-059a-11e7-8166-d8f34e02aa1f.png">

### 2) White space survey - form 
I personally find the white space between the survey and the forms unnecessarily to wide. 

<img width="1259" alt="screen shot 2017-03-10 at 14 03 32" src="https://cloud.githubusercontent.com/assets/12456965/23796286/7692596a-059a-11e7-871c-7ee5430c0b08.png">

### 3) Buttons not aligned 

The log out button and save button are not well aligned to the right 
<img width="256" alt="screen shot 2017-03-10 at 14 04 27" src="https://cloud.githubusercontent.com/assets/12456965/23796313/9848b446-059a-11e7-9e8a-eb50b5f3ce20.png">

### 4) Survey preview - scrolling 

I found a super tiny space in the survey preview window that when you scroll through the questions, you can see them move behind the white header. 

<img width="1091" alt="screen shot 2017-03-10 at 14 08 53" src="https://cloud.githubusercontent.com/assets/12456965/23796443/40c44ac2-059b-11e7-803b-7cc2ee8535fd.png">

![2](https://cloud.githubusercontent.com/assets/12456965/23796470/5f0dfd2a-059b-11e7-84d4-f1a0fb43db93.gif)

### 5) Survey preview - white space

Between the Survey preview title and the first group of questions there is a lot of white space. Plus you can see the borders of the Survey preview box. 

<img width="975" alt="screen shot 2017-03-10 at 14 11 11" src="https://cloud.githubusercontent.com/assets/12456965/23796509/976a5b3c-059b-11e7-83da-459721b22813.png">

### 6) Layout of assignment/manual survey transfer breaks if too many subfolders 
If there are many subfolders in a folder and the user is selecting the to put the survey in the assignment, the layout breaks. This happens also for Manual survey transfer.  I personally liked that you had the survey you are selecting and the ones you selected in two columns next to each other to see what you are working with and what you have.  

<img width="1243" alt="screen shot 2017-03-10 at 14 14 05" src="https://cloud.githubusercontent.com/assets/12456965/23796592/ff27a464-059b-11e7-9bc7-100afbb9f398.png">
 
### 7) Footer blocking buttons
The footer overlays the save button at the end of the page when creating an Assignment, in Manual survey transfer. 

<img width="1222" alt="screen shot 2017-03-10 at 14 16 55" src="https://cloud.githubusercontent.com/assets/12456965/23796643/56b86cd6-059c-11e7-87db-84ecca16e52b.png">

<img width="1264" alt="screen shot 2017-03-10 at 13 44 38" src="https://cloud.githubusercontent.com/assets/12456965/23795827/daa6c114-0597-11e7-8e62-5b83bfddc556.png">

### 8) Dropdown menus not aligned properly on the left 
If the dropdown goes to two rows then the 1st dropdown menus for each row are not in line. This is the case for all dropdowns 

<img width="573" alt="screen shot 2017-03-10 at 14 19 57" src="https://cloud.githubusercontent.com/assets/12456965/23796722/c974b04a-059c-11e7-8950-ee0dbabffb4b.png">

<img width="981" alt="screen shot 2017-03-10 at 14 34 27" src="https://cloud.githubusercontent.com/assets/12456965/23797152/b6d3f0ca-059e-11e7-9a63-305a6380ffb0.png">

### 9) Multiple dropdown menus do not fit in screen

If there are too many dropdown menus, then at one point they do not fit into the width of the screen anymore, but the user cannot use them as he cannot select the further items. 
<img width="1254" alt="screen shot 2017-03-10 at 14 23 39" src="https://cloud.githubusercontent.com/assets/12456965/23796867/675412f6-059d-11e7-9dae-7dbb14cb5364.png">

### 10) Cascase top level not visible 
The top level of the cascades part is not visible fully. 
<img width="1255" alt="screen shot 2017-03-10 at 14 30 58" src="https://cloud.githubusercontent.com/assets/12456965/23797058/5104deda-059e-11e7-8af3-e7d899f6261a.png">

### 11) Reports > Export reports - scrolling
There is still the scrolling issue and unneeded white space shown 

![1](https://cloud.githubusercontent.com/assets/12456965/23795918/524e32a6-0598-11e7-95e9-2d04c8513632.gif)

### 12) Reports > Export reports - footer 
The footer overlays the bottom of the Export survey form group 

<img width="1213" alt="screen shot 2017-03-10 at 13 49 11" src="https://cloud.githubusercontent.com/assets/12456965/23795969/93843108-0598-11e7-96cd-c6d675d266d6.png">

**Comment by muloem** [comment]
The space is present under the export reports tab.

<img width="1240" alt="screen shot 2017-03-10 at 15 54 56" src="https://cloud.githubusercontent.com/assets/533336/23799781/122ede66-05aa-11e7-9add-43a06421a90d.png">

**Comment by janagombitova** [comment]
# 2nd round of beta1 testing 

* [ ] 1) Survey breadcrumb
* [x] 2) White space survey - form 
* [x] 3) Buttons not aligned 
* [ ] 6) Layout of assignment/manual survey transfer breaks if too many subfolders 
* [x] 7) Footer blocking buttons
* [ ] 8) Dropdown menus not aligned properly on the left 

Still not fully aligned to the left 
<img width="1265" alt="screen shot 2017-03-10 at 16 35 41" src="https://cloud.githubusercontent.com/assets/12456965/23801213/a1d3dd1e-05af-11e7-9b69-af4e7205b0f1.png">

* [ ] 9) Multiple dropdown menus do not fit in screen

The particular issue is solved, but now it looks like this. 
<img width="1269" alt="screen shot 2017-03-10 at 16 32 30" src="https://cloud.githubusercontent.com/assets/12456965/23801120/3aef71c6-05af-11e7-8168-d5909a679d07.png">

So the rule is that the form level dropdown is on a new row and in the case on a long path of folders, it looks kind of funky. 

* [x] 10) Cascase top level not visible 
SOLVED 
* [x] 11) Reports > Export reports - scrolling 
SOLVED
* [x] 12) Reports > Export reports - footer 
SOLVED

**Comment by janagombitova** [comment]
## 3rd round of beta1 testing 

point 8 and footer is now fixed 👍 

We agreed with @loicsans to create separate issues for points below, and handle them in separate issues in another iteration. 
- 1
- 6
- 9

**Comment by janagombitova** [comment]
👍  ready for release, all other issues we will tackled in separate smaller issues
