### ISSUE TITLE
Disable request to `/rest/metrics` end point if feature flag is not enabled

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1855]
We are making a request to the `/rest/metrics` end point even in cases where the feature flag is not enabled. This causes unnecessary delay in the dashboard loading.  We can eliminate this request for dashboards that do not have the flag enabled.

**Comment by kymni** [comment]
### Test plan
Confirm that metrics end point loads when showStatisticsFeature flag is enabled and vice versa

**Comment by janagombitova** [comment]
<img width="1239" alt="screen shot 2017-02-06 at 14 46 47" src="https://cloud.githubusercontent.com/assets/12456965/22649432/24e10dba-ec7b-11e6-8584-3a4dcaefeb09.png">

This is what I see when I load UAT1. Nothing resembling metrics as far as I can tell. Do we need to confirm that the metrics actually do load if enabled? @muloem and @kymni what do you think?

**Comment by muloem** [comment]
@janagombitova yep. We should confirm that as well.

**Comment by janagombitova** [comment]
👍  metrics show and I assume they work from as far as I can tell as I am not familiar with this feature at all. Ready for release
