### ISSUE TITLE
Remove 'show' and 'hide' from Flow public page

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1859]
Currently when the user is not logged into the dashboard he see a map with the data collected that are set as public. (extra note: we need to rethink the function and value for this landing page.) The user can click on a data point that then opens a side bar with the the answers. To hide the side bar she can either click on the map, or on the 'hide' link. Currently the 'show' and 'hide' bar is shown at all times even when a point is not selected. 

Can we change the landing page, so the 'show' and 'hide' are only shown when a point is opened? 
![screen shot 2016-12-02 at 09 34 35](https://cloud.githubusercontent.com/assets/12456965/20827505/ace46582-b872-11e6-993f-c226d29f0887.png)

**Comment by janagombitova** [comment]
@mulo and @loicsans was this issue not handled in the last release? I can confirm the implementation on the user facing side is completed and deployed

**Comment by loicsans** [comment]
Actually there was an tiny fix to make that @kymni must have fixed after we talked about it? I am though not sure if if made it to last release??

**Comment by muloem** [comment]
Confirmed. It was part of the release.  I think its missing because we never labeled the issue as part of the milestone.

**Comment by janagombitova** [comment]
Ok. Closing the issue then
