### ISSUE TITLE
Remove 'Form description'

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1860]
When a user creates a form, he gives it a name and can add a description. Later on he can add translations and create a set of notifications. All these settings play a role besides the **description**. 

![screen shot 2016-12-02 at 10 07 06](https://cloud.githubusercontent.com/assets/12456965/20828307/35bf55c0-b877-11e6-957d-7f50f33f081d.png)

This one has no function. It is not shown anywhere, if the form is not opened. You can not see it in the list of surveys, it is not shown on the app or in any other parts of the dashboard. When exporting the survey form the description is not shown their either. 

![screen shot 2016-12-02 at 09 52 22](https://cloud.githubusercontent.com/assets/12456965/20828249/ef535d7a-b876-11e6-8b7f-b4bd16571c09.png)

The only place where it is shown is in **Translations**. Here the user can translate the form description, but again it is not shown in the app or anywhere else. So the user is urged to translate the description but it is a waste of effort. 

![screen shot 2016-12-02 at 10 08 09](https://cloud.githubusercontent.com/assets/12456965/20828336/52e13a92-b877-11e6-8b43-6e0bf97ed6d8.png)

If we have forms that do have the description added and also the translation of this description we can remove those properties as they play no role. We will inform the users about this change in the end year bulletin. 

Before releasing this we need to make sure it is: 
* [x] removed in the form settings and in the translations as well
* [ ] communicated via a bulletin in December edition
* [ ] added in support documentation

**Comment by muloem** [comment]
@loicsans @janagombitova I have switched the descriptions and titles of this with #1861 because of switched commits

**Comment by muloem** [comment]
@loicsans is it possible to clean up the white space that appears between the _form title_ and the `Save Translations` button?

<img width="1241" alt="screen shot 2017-01-20 at 18 19 26" src="https://cloud.githubusercontent.com/assets/533336/22158669/8cacc5e2-df3d-11e6-858e-fc48fa0c75f4.png">

**Comment by janagombitova** [comment]
## Test plan

1. Open a new survey form - form description is not shown and layout is good 
1. Open an existing survey form and form description is not shown and layout is good 

👍  implementation passes test plan, ready to go
