### ISSUE TITLE
Allow direct typing in text input fields

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1864]
The user needs to customise a lot of elements in the dashboard, especially when creating surveys. This means he has to type in a lot of things. In multiple spots on the dashboard we show the text input fields with an explanation text in there to guide the user. Ideally the user wants to click on the field and start typing right away. Many times he has to first delete the explanation text and then add his own text. 

![screen shot 2016-12-02 at 11 03 19](https://cloud.githubusercontent.com/assets/12456965/20830071/2985dc0e-b87f-11e6-8742-3601f6bb1d0f.png)

We have it well implemented when creating options and adding codes to options; when editing the assignment name; when filtering data in Inspect data tab; working on cascades, or creating new users. 

![screen shot 2016-12-02 at 11 57 05](https://cloud.githubusercontent.com/assets/12456965/20831678/766898fc-b886-11e6-96b4-e57cf7ff4405.png)

Here is a list of the text fields where we have this situation happening when editing: 
- folder name 
- survey title 
- form title 
- question group name 
- question text (name)
- data approval name

**Comment by loicsans** [comment]
We need to look error management.

**Comment by janagombitova** [comment]
Al the above mentioned element are in place to avoid having forms, questions nameless. The placeholder is there to ensure that this does not happen and as Loic mentioned we would need to look at error management. The placeholder solution suffices for now. I was not aware of this when creating the issue so I am closing it now.
