### ISSUE TITLE
Approval group not saved after page refresh

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1866]
@muloem when testing the latest changes to the approval feature I found an problem. When you add an approval group to a survey > save it > approve data and then refresh the entire browser page, things go wrong. 

I checked the survey and my selected and saved approval group was not saved anymore. Nothing was saved. 

![saving approval groups to surveys](https://cloud.githubusercontent.com/assets/12456965/20839594/85493990-b8ad-11e6-8189-f7eb60390198.gif)

Then I went to the monitoring tab and the statuses on the data points were correct but after opening some I could make changes all over again. 

![saving approval groups to surveys 2](https://cloud.githubusercontent.com/assets/12456965/20839601/8989e676-b8ad-11e6-992b-dc85265a0a4b.gif)

Once I save the correct approval group to the survey again, then all is ok also in the monitoring tab.

**Comment by janagombitova** [comment]
@muloem did you fix this one already and merged the commits? I cannot reproduce the problem?

**Comment by muloem** [comment]
### Test Plan

1. Create an approval group and assign it to a survey

2. Refresh the dashboard and ensure the approval group is still correctly set

**Comment by janagombitova** [comment]
👍  No further problems found! Almost done.. This issue passes test plan
