### ISSUE TITLE
Add "No results found" in Monitoring tab

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1868]
When the user selects which data for which form he has to view in Inspect data tab, he clicks on "Find" to trigger the action. If there are no data collected for that form we show **"No results found"** under the button. In the Monitoring tab we show nothing if there are no data points. 

If there are no data points to show for the selected survey in the Monitoring tab, show **"No results"** found under the Find button as in the Inspect data tab. 

![screen shot 2016-12-02 at 17 41 07](https://cloud.githubusercontent.com/assets/12456965/20842156/d04f9ade-b8b6-11e6-8563-30c7f822aeec.png)

**Comment by Maseline** [comment]
Test Plan
Navigate to the monitoring tab
Select find without choosing any folder or survey, 'No results found' should be displayed and appear just as it does under the inspect data tab.

**Comment by janagombitova** [comment]
👍  no results found shows when it needs to and not when it should not. There is one cosmetic detail that needs fixing for next release: https://github.com/akvo/akvo-flow/issues/2452 but this can go
