### ISSUE TITLE
Approval type not shown properly in survey screen 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1879]
We have two types of data approval groups the user can choose from: 
- ordered 
- unordered 

This information is shown in the survey definition when looking at the approval steps. Right now regardless of the type we only show unordered, and not ordered, if the group is ordered. If the user uses in the future both types, this information will be vital. 

<img width="275" alt="screen shot 2016-12-12 at 15 26 07" src="https://cloud.githubusercontent.com/assets/12456965/21102727/a835b594-c07f-11e6-8951-d9fbe6ee468b.png">

I was actually thinking, as in the entire feature we only properly support the ordered type, can we simply remove the unordered for now? @muloem what do you think?

**Comment by muloem** [comment]
Its a pretty small change so we may as well include it in there for now. In fact I noticed this while working on the issue #1866 and was going to resolve it there.  So maybe we can close this one?

**Comment by janagombitova** [comment]
I rather we keep the issue open, so I have a reference point to when testing the implementation. How you connect the commits is more up to you
