### ISSUE TITLE
Cannot load data for Monitoring tab

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1880]
When testing this issue https://github.com/akvo/akvo-flow/issues/1774 I noticed that I can not load data in the Monitoring tab. This is for surveys with approval groups added and also for surveys which do not have an approval group added. The Error message is: 

<img width="1045" alt="screen shot 2016-12-12 at 15 56 02" src="https://cloud.githubusercontent.com/assets/12456965/21103684/b91c1d2c-c083-11e6-9dc5-cef17cfab028.png">

Here is an example case: 

![monitoring tab](https://cloud.githubusercontent.com/assets/12456965/21103690/c0ff3aba-c083-11e6-9b87-75b55f8942d3.gif)

**Comment by muloem** [comment]
### Test Plan 

1. Visit the `Data > Monitoring data` tab and ensure that data points are visible

**Comment by janagombitova** [comment]
👍  works perfectly again
