### ISSUE TITLE
Replace current phosphate test with Quantofix phosphate

### ISSUE THREAD

**Issue by nhternup** [akvo/akvo-flow#1894]
The current phosphate test to be replaced with Quantofix phosphate test as it seems to give better results.

More info: https://github.com/akvo/akvo-caddisfly/issues/49

**Comment by nhternup** [comment]
In:
https://github.com/akvo/akvo-flow/blob/develop/GAE/src/resources/caddisfly/caddisfly-tests.json

Replace the following:
```json
{
    "subtype": "striptest",
    "uuid": "f4c57d34-dd17-4750-9fcd-fe26af2621a7",
    "tags": ["water quality"],
    "name": "Phosphorus",
    "brand": "HACH 27571, 50 pcs",
    "description": "Phosphorus, orthophosphate (reactive). 0 - 50 ppm.",
    "numResults": 1,
    "hasImage":true,
    "results": [{
        "name": "Phosphorus",
        "id": 1,
        "unit": "ppm"
    }]
}, 
```

with:

```json
{
    "subtype": "striptest",
    "uuid": "39e7ea7e-9884-407d-a99a-ac3b4d9c9599",
    "tags": ["water quality"],
    "name": "Phosphate",
    "brand": "Quantofix 91320",
    "description": "Phosphate, 0 - 100 ppm.",
    "numResults": 1,
    "hasImage":true,
    "results": [{
        "name": "Phosphate",
        "id": 1,
        "unit": "ppm"
    }]
},
```

**Comment by janagombitova** [comment]
@nhternup does this mean that we will no longer support the current HACH test? Does this change have any implications on current running pilots (even those using the coded question) - do we have anyone using the HACH tests?

**Comment by nhternup** [comment]
@janagombitova, yes we no longer support the HACH phosphate test. Just got confirmation that the phosphate test is currently not part of any pilot.

**Comment by valllllll2000** [comment]
For now both tests are visible after this fix #1915

**Comment by janagombitova** [comment]
in the latests UAT build there is only one Phosphate test type now, as expected. Can be considered ready to go 👍

**Comment by janagombitova** [comment]
@nhternup and @muloem I just spoke with Hans and they did not realise they have a pilot using the Phosphate HACH tests. Thus we cannot remove it from the available list of tests. Can we please bring it back on both sides for this release? 

I am sorry for the miscommunication about this test type. I just spoke with Hans and he confirmed that the list we will have now, including the phosphate HACH one will be the final list for a few months. 

Thanks

**Comment by nhternup** [comment]
@muloem, The HACH Phosphate has been added back to the tests.json file and can be copied into Flow.

**Comment by valllllll2000** [comment]
@muloem I will take care of this

**Comment by valllllll2000** [comment]
## Test plan:
In dashboards, create a survey, form and group. When creating a question select type caddisfly and make sure both Phosphate tests are displayed.

**Comment by janagombitova** [comment]
👍  and the test type is back - all good
