### ISSUE TITLE
Public map - answers not shown due to Caddisfly related error

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1903]
When wanting to open a data point on the public map on Flow's dashboard and this data point has a Caddisfly question in it, the answers do not load on the map and this error is shown in the console: 

![screen shot 2017-01-16 at 15 38 20](https://cloud.githubusercontent.com/assets/12456965/21987110/6c305d58-dc02-11e6-8d0d-0a0f1dbca1b4.png)

To see go to https://uat1.akvoflow.org/ and select a data point in Iceland

**Comment by janagombitova** [comment]
Actually after clicking through, none of the data points that I select render any results, so I only get a while blank side bar and no explicit error in the console (as far as I can tell) 

![screen shot 2017-01-16 at 15 49 23](https://cloud.githubusercontent.com/assets/12456965/21987381/93dd6e9e-dc03-11e6-9005-afc2b9a55e67.png)
![screen shot 2017-01-16 at 15 50 01](https://cloud.githubusercontent.com/assets/12456965/21987386/96314cec-dc03-11e6-9dff-0711bea1daf2.png)

**Comment by kymni** [comment]
Points not displaying might be tied to [this commit](https://github.com/akvo/akvo-flow/commit/621a5d58b232cdd0c07357f2e27f29e6ccf36b26) specifically on [this line](https://github.com/akvo/akvo-flow/blob/05f02dca77e5938aa6950a0bf26b7c5c33ec199f/Dashboard/app/css/main.scss#L4681). @loicsans would it affect your implementation if we removed the line?

**Comment by janagombitova** [comment]
👍  EC Caddsifly tests (for water and soil) shown as a string, but that can be tackled in a different issue. Ready for relase
