### ISSUE TITLE
Add Ammonium strip tests

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1907]
We will add another test to the Akvo Caddisfly question type - Ammonium which belongs under the strip tests group. 

@nhternup can you please take care of the implementation on the Caddisfly app side and share the details for @valllllll2000 to pick it up on our side? Thank you

**Comment by valllllll2000** [comment]
This should be handled by this issue #1915

**Comment by muloem** [comment]
All handled under #1915
