### ISSUE TITLE
Add Total Alkalinity and Total Hardness test type

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1909]
We will add another test to the Akvo Caddisfly question type - Total Alkalinity and Total Hardness which belongs under the strip tests group. This is one test combining two paramenters

@nhternup can you please take care of the implementation on the Caddisfly app side and share the details for @valllllll2000 to pick it up on our side? Thank you

**Comment by valllllll2000** [comment]
This should be handled by this issue #1915

**Comment by muloem** [comment]
Handled under #1915
