### ISSUE TITLE
Add Residual Chlorine (Akvo Caddisfly) colorimetric test

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1910]
We will add another test to the Akvo Caddisfly question type - Residual Chlorine (Akvo Caddisfly) which belongs under the colorimetric tests. As far as I understand this test is done by using the hardware we have in place for testing Fluoride. 

@nhternup can you please take care of the implementation on the Caddisfly app side and share the details for @valllllll2000 to pick it up on our side? Thank you

**Comment by muloem** [comment]
Handled under #1915
