### ISSUE TITLE
Change Electrical conductivity test to Water Electrical Conductivity

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1912]
When the user is selecting an Akvo Caddisfly question type he has multiple options and we even have two different electrical conductivity tests: for water and for soil. We name the soil one: `Soil Electrical Conductivity (Akvo Caddisfly)` and the water one is `Electrical Conductivity (Akvo Caddisfly)`

For consistency and clarity, can we please rename in the dropdown the Electrical conductivity one for water testing: `Water Electrical Conductivity (Akvo Caddisfly)`

Thanks

**Comment by valllllll2000** [comment]
This should be handled by this issue #1915
