### ISSUE TITLE
Paste all the caddisfly tests to Flow

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#1915]
After talking with @muloem, we have decided the fastest option would be just to paste the contents of:
https://github.com/akvo/akvo-caddisfly/blob/develop/caddisfly-app/app/src/main/assets/tests.json

into 

https://github.com/akvo/akvo-flow/blob/develop/GAE/src/resources/caddisfly/caddisfly-tests.json

and test everything and make sure it works for the Dashboard.

Later we will create a script to automatically load the file from the caddisfly repository at build time.

**Comment by valllllll2000** [comment]
## Test plan

Go to the dashboard, select a survey and try adding all the possible Caddisfly questions.

**Comment by valllllll2000** [comment]
Here are the tests that are still pending to be added to caddisfly tests:
- [ ] Ammonium strip test
- [ ] Chloride strip test
- [ ] Total Alkalinity
- [ ] Total Hardness
- [ ] Residual Chlorine (Akvo Caddisfly) colorimetric

**Comment by nhternup** [comment]
@muloem, @valllllll2000 The tests.json file has been updated with new tests and test name prefixes. Please copy the file over again.

**Comment by janagombitova** [comment]
*[ ] Ammonium strip test
*[ ] Chloride strip test
*[ ] Total Alkalinity
*[ ] Total Hardness
*[ ] Residual Chlorine (Akvo Caddisfly) colorimetric

**Comment by janagombitova** [comment]
👍  all expected tests are shown in the dropdown and can be added to the survey without troubles. Once we collect data and confirm the view of data and export works fine, will consider this all ready for release.

**Comment by janagombitova** [comment]
Preview of all collected data and reporting as well as cleaning work as expected. Issue is ready to go out into the world 👍
