### ISSUE TITLE
Sort caddisfly tests in alphabetical order

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1916]
The list of caddisfly tests when selecting a caddisfly question are currently randomly ordered. For easier browsing, we should sort in alphabetical order.

**Comment by janagombitova** [comment]
## Test plan
1. Open a survey and cross check all Caddisfly tests types are ordered alphabetically 
1. Open an old survey with Caddisfly questions and cross check all works as expected

👍  passes test plan
