### ISSUE TITLE
Loading of survey details on home page

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1926]
This is an issue to look at after we release 1.9.13 to cross check if it really happens. This issues does not need to postpone the release as users are not allowed to have surveys outside of a folder on the initial survey list after logging in. But it does need investigation and resolving for the longer run. 

Once I log in to UAT1 I see a list of folders and surveys. If I scroll down to the surveys, I see their name but miss all the meta data as actions. They only appear once I hover over them with my mouse. This does not happen once I open a folder with surveys. There all shows right away. @loicsans Any ideas what is going on? 

![1](https://cloud.githubusercontent.com/assets/12456965/22644719/edb41e7a-ec63-11e6-8e02-6a21cf769772.gif)

**Comment by janagombitova** [comment]
Issue still present, can we get this fixed @loicsans? Thanks

**Comment by kymni** [comment]
Tested on Chrome, Firefox, and Edge. Could not reproduce issue

**Comment by janagombitova** [comment]
Hey @kymni I just opened up UAT1 on Chrome and the problem is still present. Once you scroll to the bottom of the initial survey list the surveys show only name and the other details show up after mouseover.

**Comment by janagombitova** [comment]
Closing the issue as I cannot reproduce it anymore
