### ISSUE TITLE
Pressing Enter key in survey title or form title fields causes page refresh

### ISSUE THREAD

**Issue by osg74** [akvo/akvo-flow#1929]
**Defect:**
When the Enter key is pressed while entering the survey title or form title this triggers a full page refresh and the user is dropped out of any folders s/he was working in and taken back to the top level list of survey folders.

**Expected behaviour:**
Pressing the Enter key should instead trigger a Save action and keep the user on the same UI level.

**Reproduction:**
* Environment: uat1.akvoflow.org
* Build: 1.9.13 RC from 7 Feb
* Browser: Chrome 56.0.2924.76 (64-bit)
* OS: macOS Sierra 10.12.3

**Comment by muloem** [comment]
Comments from @stellanl #2117 

> In FF, while renaming a Survey Group, editing of the string just ends, which is confusing to the user, as the new name is shown, but is not sent to the server.
Tested on Windows 7, Firefox 53.0.3 (works on Chrome 58)
>
> Also, when renaming a Survey in FF 53 or Chrome 58, pressing enter reloads the entire dashboard, instead of saving the new name.

**Comment by kymni** [comment]
## Test plan
* Change survey/form title and hit enter key
* Confirm that it does not trigger a page reload
* Confirm that new survey/form title is saved

**Comment by janagombitova** [comment]
What a wonderful improvement. Works like a charm 👍  Ready to roll
