### ISSUE TITLE
Standardise the logging library

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1933]
In some cases we are using the `log4j` library and in others `java.util.logging`.  We need to check which of the libraries can be removed and use the same logging application and configuration throughout the code base.

**Comment by stellanl** [comment]
There are 149 classes using java.util.logging.
Only 16 classes using log4j, mostly export/import (which used to run in the server) and:
GAE/src/org/akvo/flow/domain/DataUtils.java
GAE/src/org/waterforpeople/mapping/app/gwt/server/surveyinstance/SurveyInstanceServiceImpl.java
GAE/src/org/waterforpeople/mapping/app/web/SurveyAssemblyServlet.java
