### ISSUE TITLE
Data point name not updated for already collected data

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1934]
When you user sets a survey she defines what builds that data point name. When collecting the data the name is built properly and shown well on the app, dashboard and reports. However, if she changes something in the name settings (adds another question that should build the name), then two things happen: 
1) the new submissions follow the new name structure properly on the app, dashboard and reports 
2) the old submissions do **not** get their name updated based on the new structure in the app, dashboard and reports 

This issue was found on UAT1 when testing 1.9.13

**Comment by muloem** [comment]
The issue is a regression caused by this commit 3a70e36b0a50cc2aee620adfa22a51407dc60fcb

**Comment by janagombitova** [comment]
All works again 👍
