### ISSUE TITLE
registrationSurvey is "null" when there is a cascade and survey is monitored

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#1940]
This seems to happen with monitored surveys the xml is like this:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><survey name="New form" defaultLanguageCode="en" version='2.0' app="akvoflow-uat1" registrationSurvey="null" surveyGroupId="116869116" surveyGroupName="test 614"><questionGroup><heading>New group - please change name</heading><question order="1" type="free" mandatory="true" localeNameFlag="false" id="120569115"><text>New question - please change name</text></question><question order="2" type="cascade" cascadeResource="cascade-20169121-v1.sqlite" mandatory="true" localeNameFlag="false" id="115029115"><levels><level><text>Level 1</text></level><level><text>Level 2</text></level><level><text>Level 3</text></level><level><text>Level 4</text></level><level><text>Level 5</text></level><level><text>Level 6</text></level></levels><text>New question - please change name</text></question></questionGroup></survey>`

The problem is in that case the app displays the survey as disabled. This needs more investigation.

**Comment by valllllll2000** [comment]
Update: I have disabled monitoring on my survey and now I do get the resitrationSurvey correct:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><survey name="Folder/New form" defaultLanguageCode="en" version='1.0' app="akvoflow-uat1" registrationSurvey="112149115" surveyGroupId="116869117" surveyGroupName="test 614 monitored no cascade/Survey1"><questionGroup><heading>New group - please change name</heading><question order="1" type="free" mandatory="true" localeNameFlag="false" id="114309117"><text>New question - please change name</text></question></questionGroup></survey>

**Comment by janagombitova** [comment]
On the bootstrap, I just checked using 2.2.10. 

It all works on my side: 
- if the monitoring survey has multiple forms and you send them all in one bootstrap files - all fine; 
- if you have a monitoring survey with only one form - all fine;
- if you have a monitoring survey with more forms but you only send the registration form – all fine;
- if you have a monitoring survey with more forms, but you send only the monitoring form – all fine but then the user cannot work with the form as he is missing the registration form (this is what happened with the file I sent you yesterday – that was my mistake)

@valllllll2000 Do you have a case where you tried it out and it did not work? I can try to reproduce your steps.

**Comment by valllllll2000** [comment]
@janagombitova this is so strange it still does not work for me. Here is the steps I follow:
Use the uat1 Valeria Test -> test 614 survey, which has only one form
send the bootstrap file to myself and put it on the device
put the device in flight mode
open the app. Everything seems to work fine but when you try to add a datapoint, the form appears greyed out (disabled).

**Comment by janagombitova** [comment]
@valllllll2000 checked the survey you mention above and indeed had the same problem. So I disabled monitoring and republished the survey and then the bootstrap worked. 

Here is the not working bootstrap file 
[1487156659983-bs.zip](https://github.com/akvo/akvo-flow/files/776827/1487156659983-bs.zip)

Here is the working one: 
[1487156946229-bs.zip](https://github.com/akvo/akvo-flow/files/776825/1487156946229-bs.zip)

I tried to recreate the problem you encountered but I could not
