### ISSUE TITLE
Multiple scroll bars

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1943]
@loicsans Ivan noticed that we have multiple scroll bars across the dashboard. He mentioned that Mac hides scroll bars by default but Windows and Linux do not, therefore we did not find the issue. I will start using https://www.browserstack.com/list-of-browsers-and-platforms?product=live to better test different browsers and machine types for next time, but can you please take a look at this issue? Thanks 

![scrollbars-2](https://cloud.githubusercontent.com/assets/12456965/22967452/d364baca-f366-11e6-8067-f25114cc8ade.png)
![scrollbars-1](https://cloud.githubusercontent.com/assets/12456965/22967454/d5d7dc7e-f366-11e6-8f78-b5c8def011b8.png)

**Comment by muloem** [comment]
@janagombitova @loicsans i just found another occurrence of scroll bars...  to the extreme right of the folder box

<img width="1229" alt="screen shot 2017-02-24 at 16 11 37" src="https://cloud.githubusercontent.com/assets/533336/23309122/c55479f4-faad-11e6-84d8-1a5e5f69e4fc.png">

**Comment by janagombitova** [comment]
@stellanl found another double scroll bar case in Messages: https://github.com/akvo/akvo-flow/issues/2062#issuecomment-298914810

**Comment by janagombitova** [comment]
<img width="1246" alt="screen shot 2018-01-25 at 09 40 02" src="https://user-images.githubusercontent.com/12456965/35378695-fc603010-01b3-11e8-871f-85c34aca1885.png">

And here is how they look on an Opera browser
