### ISSUE TITLE
DeviceSurveyJobQueue entries not always created when survey changes

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#195]
I have noticed, on several occasions, that DeviceSurveyJobQueue entries were not created when adding a new device to an old assignment.
Possibly this happened when the old assignment was alreay expired, but if I then extended the expiration date into the future, no entries were created.

**Comment by muloem** [comment]
This was handled in https://github.com/akvo/akvo-flow/issues/3108.
