### ISSUE TITLE
Load d3 javascript library only when user navigates to reports tab

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#1952]
D3 library currently loaded when dashboard is first loaded. It should only be loaded when needed in the reports tab

**Comment by kymni** [comment]
## Test plan
*Load the dashboard
*Confirm that d3 library is missing from automatically loaded libraries
*Navigate to reports tab
*Confirm that d3 library is now loaded

**Comment by janagombitova** [comment]
https://github.com/akvo/akvo-flow/pull/1953#issuecomment-291405973 see this comment that explains why the issues were not merged but only closed
