### ISSUE TITLE
White space between the main menu and other elements

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1955]
@loicsans I am not sure how to describe this issue, so we might need to talk in person but I noticed that theere is this white space between the main menu and the submenu or breadcrumb. It looks as if the area with the main menu and with the sub menu have the same background colour that is not fully white and between the two areas there is a white space. Can this go? Thanks 

<img width="1242" alt="screen shot 2017-02-21 at 14 05 12" src="https://cloud.githubusercontent.com/assets/12456965/23166023/37b74b14-f83f-11e6-9f37-b80e06f204af.png">

<img width="1248" alt="screen shot 2017-02-21 at 14 05 24" src="https://cloud.githubusercontent.com/assets/12456965/23166030/3b4f94fc-f83f-11e6-9c05-486471e323b1.png">

<img width="1245" alt="screen shot 2017-02-21 at 14 05 38" src="https://cloud.githubusercontent.com/assets/12456965/23166034/3cc23966-f83f-11e6-9ac2-6c31570e6793.png">

It is in the space where currently if you scroll the items will roll behind - the bug we found and you are solving with the layout issue. https://github.com/akvo/akvo-flow/issues/1852#issuecomment-276622048 This "white space" is on every page. 
<img width="1242" alt="screen shot 2017-02-21 at 14 09 24" src="https://cloud.githubusercontent.com/assets/12456965/23166123/94430ba2-f83f-11e6-855f-ee86ee4feddf.png">

**Comment by muloem** [comment]
This is also occurring on the tab with cascades.

<img width="1251" alt="screen shot 2017-02-27 at 10 30 48" src="https://cloud.githubusercontent.com/assets/533336/23355897/18e9bef4-fcd8-11e6-8de8-27c04b85c820.png">

**Comment by janagombitova** [comment]
## Test plan: 

1. check each page of the dashboard to make sure the white space does not occur 
1. make sure you scroll items to the top

**Comment by janagombitova** [comment]
@loicsans I checked the implementation and found that the problem still happens on some spots: 

- on the Devices tab between the submenu and the area with all action buttons as Manage devices, etc
- on the Assignments tab between the submenu and Create new assignments 
- Cascades 
- Reports 

![1](https://cloud.githubusercontent.com/assets/12456965/23557132/4b0ebad8-002f-11e7-938a-6d05fba0baea.gif)

![2](https://cloud.githubusercontent.com/assets/12456965/23557494/892d1886-0030-11e7-84da-303d4163cdee.gif)

![3](https://cloud.githubusercontent.com/assets/12456965/23557484/7fcbf01e-0030-11e7-86d0-7a5f6dc36282.gif)

![4](https://cloud.githubusercontent.com/assets/12456965/23557586/d122767c-0030-11e7-85e4-2e06ebb238c5.gif)

**Comment by janagombitova** [comment]
@loicsans and I found another very unexpected on as well :) When in a survey, between the end of the survey and the footer - the list of surveys and folders creeps in the view 

![6](https://cloud.githubusercontent.com/assets/12456965/23558082/999af6d2-0032-11e7-9b8b-c9bee8403b0b.gif)

**Comment by janagombitova** [comment]
Most of the issues are solved so this implementation can be released. I have created a follow up issue to bring this to its final end https://github.com/akvo/akvo-flow/issues/1998

👍 ready for release
