### ISSUE TITLE
Fix NPE that prevents users tab from loading

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1959]
In some cases, a user has been added directly to the dashboard through the GAE console and is missing the `superAdmin` property.  This prevents the dashboard users tab from loading because it causes a NPE.

**Comment by muloem** [comment]
# Test Plan

1. Edit a user in the GAE console and delete the `superAdmin` property

2. Load the dashboard and verify that you are still able to see the list of users in the users tab

**Comment by janagombitova** [comment]
👍  works like a charm
