### ISSUE TITLE
Point details not displaying for a clicked point on Carto maps when only survey is selected

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#1963]
Current setup has it that when a survey is selected, the details that are displayed on the map when a point is clicked are from the first available form. This is not ideal because in the case of monitoring enabled surveys, not all forms are guaranteed to have submissions and hence the issue. 

Proposed fix will:
* for monitoring enabled surveys, display registration form data when no specific form is selected 
* display form specific data when a form is selected (already the case)

Thoughts @janagombitova, @muloem?

**Comment by kymni** [comment]
### Test plan
* Select any survey, on the map tab, that has data 
* Click on any of the points overlayed on the map
* If it's a monitoring enabled survey and no form is selected, the registration form details for the point should appear on the details panel. Otherwise the default form's details appear on the panel

**Comment by muloem** [comment]
@kymni I agree. this should be the way to go. If no form is selected then we should take the registration form details. 👍

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/from-vietnam-biogas-project-90962a6654deadb3

**Comment by kymni** [comment]
Issue being addresses in the maps refactor branch [#2144]

**Comment by kymni** [comment]
## Test plan
* In a CartoDB enabled instance, select a survey in the filters
* Notice points are not displayed on the map until you select a specific form
* Click point on map, details for specific form selected should appear in the details panel

**Comment by janagombitova** [comment]
Ohh nice. Good simplification choice 👍
