### ISSUE TITLE
Optimise loading of cascade resources

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1966]
Loading of cascading resources currently uses a bean copying pattern that may create a performance issue when there are a large number of cascading resources defined. 

Proposed improvement:  In order to optimise the loading, we should eliminate the redundant copying of the bean properties and instead wrap the bean in the DTO.

In addition, we should only load the cascade resources when a survey is selected.

**Comment by stellanl** [comment]
Not entirely sure how you want it wrapped. Make the CascadeResource a member of the CascadeResourceDto, or make the CascadeResourceDto a subclass of CascadeResource?
