### ISSUE TITLE
Exports with rollup sheets break on JSON data

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#1968]
The logic for creating geographical rollup sheets does not handle JSON responses well.
They also expose a bug in GraphicalSurveySummaryExporter.
The try-again loop at L1426 is broken, since it tests for existence of a different sheet name than it then uses to create a new one with...

**Comment by stellanl** [comment]
Test plan: From akvoflow-17, run a report on 
OXFAM WASH > Post Ebola Public Health Units > Post Ebola Public Health Units RNA -> form ID: 170300001
You should a: get a report, and b: see that the Spreadsheet sheets have JSON-less names

**Comment by janagombitova** [comment]
Implementation passes test plan 👍

**Comment by janagombitova** [comment]
Checked also on the original survey that cause the problem (made a copy of it in uat) and all works fine now 👍 👍
