### ISSUE TITLE
Refactor BaseDAO to be able to receive the userId as parameter

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#1970]
The current filtering capabilities of the `BaseDAO` expect that the user/principal is in a `SecurityContext`. In order to reuse the ACL capabilities we want to be able to explicit pass the `userId` as parameter.

Requested changes:

- [x] Be able to pass `userId` as parameter
- [x] Refactor code to avoid `@SupressWarnings` related to raw data types

**Comment by janagombitova** [comment]
I assume as there is no Test plan here, there is nothing to manually test and as the changes have been merged, we can consider this ready for release
