### ISSUE TITLE
Fix the header in Messages tab table

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1972]
Currently the entire Messages page is scrollable and if the user looks at things that happen in the bottom of the table she looses sight of the headers and then it is hard to orientate what she is looking at. Would it be possible to fix the header of the table? 

![5](https://cloud.githubusercontent.com/assets/12456965/23557705/338a8502-0031-11e7-9121-48ac30bbe70a.gif)

**Comment by janagombitova** [comment]
@loicsans on the changes to the header, I think they are great. I have a few questions though? Is the column width now fixed? If yes, can we make it that the Form ID column is not on two lines? And can you enlarge the Survey column (perhaps to even up with the Message column)? The reason is that sometimes the survey name can be long and it needs some space 

<img width="1260" alt="screen shot 2017-04-07 at 12 40 16" src="https://cloud.githubusercontent.com/assets/12456965/24796992/b0ed04d8-1b8f-11e7-8b80-34e728f54c99.png">

**Comment by iperdomo** [comment]
Make sure you  test the changes on lower resolutions on Windows (and/or Linux), since Mac hides scrollbars _automagically_.
![multiple-scrollbars](https://cloud.githubusercontent.com/assets/178474/24797777/19bbcce4-1b93-11e7-9175-b5bd3fd6a69f.png)

**Comment by janagombitova** [comment]
@iperdomo yes will do, and we have a separate issue to handle the multiple scroll bars. Thanks for pointing it out

**Comment by janagombitova** [comment]
@loicsans here is an example of how the items in the Survey column can get long and currently the column width adjusts, but perhaps we could fix the column width so you do not end up with this type of view of the Messages page

The longest items are in the Survey and Message columns

<img width="1263" alt="screen shot 2017-04-11 at 14 18 38" src="https://cloud.githubusercontent.com/assets/12456965/24908847/090f27e2-1ec2-11e7-9f11-80127ad4411d.png">

**Comment by loicsans** [comment]
![apr-26-2017 14-48-05](https://cloud.githubusercontent.com/assets/1717219/25433010/84449db0-2a8f-11e7-8ed6-7f14572c1f13.gif)

**Comment by stellanl** [comment]
I probably should not mention this, but in Firefox, the header still scrolls away (like I want it to)...

**Comment by janagombitova** [comment]
And besides Stellan's point, now there is this odd white filed on the bottom of the page 
![1](https://cloud.githubusercontent.com/assets/12456965/25480675/09ba9822-2b4a-11e7-9ed9-16e1f7a686cb.gif)

These changes will have to wait to be released before completely addressed

**Comment by loicsans** [comment]
![apr-27-2017 14-58-02](https://cloud.githubusercontent.com/assets/1717219/25482491/c2ed9a96-2b5a-11e7-9826-fdd2c3ef121c.gif)

**Comment by janagombitova** [comment]
👍  issues addressed in a separate issue and here all is good enough for this iteration
