### ISSUE TITLE
Survey loading spinner doesn't stop when publishing a recently copied form

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1973]
#### Steps to reproduce

1. Create a survey with a form and a few questions

2. Copy the survey 

3.  The loading spinner doesn't stop because there is an NPE in the copying class

**Comment by janagombitova** [comment]
Maybe this is a different case and needs a separate issue. Not sure. But here are the steps I have done: 
1. Select an existing survey and copy it
1. Select the folder and confirm

The user gets the confirmation message, but does not see that the survey is in and the loading spinner keeps on spinning. In the console I get a 500 error

<img width="1251" alt="screen shot 2017-03-03 at 17 20 09" src="https://cloud.githubusercontent.com/assets/12456965/23558925/b53bb59a-0035-11e7-8b72-c46faa76ecb3.png">

Once the user goes to another tab and then back to the newly copied survey, all is fine again

**Comment by muloem** [comment]
@janagombitova actually that was the issue.  The publishing is something else!  👍

**Comment by janagombitova** [comment]
I have marked this one as performance, even though it may not be directly a performance problem, but to the user the loading keeps on going on and on and is annoying and appearing as a performance problem. You can un-label it if you want
