### ISSUE TITLE
Remove User column in table in Messages tab

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1976]
Currently in the Messages tab we have these columns in the table: 
- Date 
- Survey ID 
- Survey 
- Type 
- Message 
- User 

All columns show content besides User. The User column can thus be removed

![screen shot 2017-03-06 at 10 49 08](https://cloud.githubusercontent.com/assets/12456965/23604820/95c0691e-025a-11e7-9c0f-f59aadd5fc80.png)

**Comment by janagombitova** [comment]
Second change: 

Please change the text: Survey ID to Form ID 

Thanks

**Comment by kymni** [comment]
### Test plan
* Load messages tab
* Confirm that the previously labeled "Survey ID" column now reads "Form ID"
* User column should no longer appear

**Comment by janagombitova** [comment]
👍 wonderful!
