### ISSUE TITLE
Creating new forms should open the new form 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1981]
Salim can create multiple forms in his survey. This happens usually for monitoring cases. However, every time he clicks on `Add form` he does not land on the new form right away, but he either stays on the form he was working on first, or if he was working on a monitoring form, Flow opens the registration form.

An easy thing would be, that if Salim clicks on `Add form` we open up the new form for him to directly start editing.

![1](https://cloud.githubusercontent.com/assets/12456965/23787319/cb81e838-0571-11e7-9507-c896e06883b1.gif)

**Comment by kymni** [comment]
## Test plan
* Navigate to survey editing tab
* Enable monitoring feature on survey
* Click "Add new form" button
* Newly created form should be opened

**Comment by janagombitova** [comment]
@muloem comment from the PR: closing this PR without merging as this issue will be addressed under a wider refactor.

**Comment by janagombitova** [comment]
Tested on uat2. Fix works well and I see forms are now ordered by creation date rather than alphabetically. Let's see what users feedback us on that change. But there is this odd behaviour happening when creating a new form. It first shows a 1st in the rom and then jumps to the end. 

![newform](https://user-images.githubusercontent.com/12456965/48346092-5ae29f00-e67a-11e8-955f-7257dbd1fadc.gif)

**Comment by kymni** [comment]
Reason could be that `createDateTime` property is server generated therefore is initially `null` then assigned a value. Possible fix is to assign the property a future date that will be auto replaced with a real date by the server

**Comment by kymni** [comment]
Possible to handle in this issue for this release but fix PR will go into release branch

**Comment by janagombitova** [comment]
Lets move our suggestion to the next release. Created a separate issue for it here: https://github.com/akvo/akvo-flow/issues/2923

This change is ok for now.
