### ISSUE TITLE
How should forms be organised in the UI? 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1982]
Currently, we organise the forms in the form tabs alphabetically. The registration form is marked with a little colour indication on the top of the form tab. 

<img width="756" alt="screen shot 2017-03-10 at 09 18 37" src="https://cloud.githubusercontent.com/assets/12456965/23787481/a21c6f9e-0572-11e7-9717-a26d7f8daa07.png">

The aim of this issue is to think if we should: 
- keep the alphabetical order of forms? 
- place the registration form always on the 1st position and then order the other forms alphabetically? 
- not deal with this right now and think about it once we go for a larger re-design? 

@loicsans @Kiarii and @muloem What are your thoughts?

**Comment by Kiarii** [comment]
right off the bat, i think the forms should, by default, be presented in the order in which they were created: 
- Registration form 
- Monitoring form 1 
- .., 
- Monitoring form n

A sorting mechanism can then be used to list them as desired; which would require a vertical listing of the form names [accommodating long form names] for text scanning.. 

Would also be of interest to see how people jump from form to form while creating or editing a survey to determine the best sort/viewing mechanism.. [I have also heard that in some cases, the survey structure - form name, question groups, questions - is used to locate respective data when exported to .xls for instance, so having a consistent order by default might help in such cases]
