### ISSUE TITLE
Naming of CSS elements

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1994]
The naming of CSS elements needs to be revised in order to relate the CSS to the section to which it applies.  Some examples are listed below

* [x] Under the `cascade-resources.handlebars` template, we have a section named `deviceControls` that shares CSS with the devices tab and assignments list tab.

Look for similar instances and share the CSS but rename the sections so they are related to the content of the template. 

Following up from #1852

**Comment by janagombitova** [comment]
I do not know how to test this to confirm it is ready for release. @muloem and @loicsans any help? thanks

**Comment by muloem** [comment]
Not really.  As long as the cascade resources tab loads fine, then this works.

**Comment by janagombitova** [comment]
ok. then the cascades load fine so this one can also be part of the release 👍
