### ISSUE TITLE
Make max zoom on mapbox map 5000km

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2001]
On mapbox maps (public and private) the map opens on the zoom range of 5000km. Salim can zoom in and out of this range as he wishes. Can we make the maximum zoom 5000km? More than 5000km makes the map "repeat" by showing the continents twice what is not needed. Secondly, by zooming out we get this odd white space and, thirdly, in the Carto implementation we have this range set as well. 

<img width="1274" alt="screen shot 2017-03-14 at 12 35 17" src="https://cloud.githubusercontent.com/assets/12456965/23898785/ba443b22-08b2-11e7-892c-c7d30cff6aaf.png">

This needs to be implemented for both **public** and **private** maps.

**Comment by kymni** [comment]
### Test plan
* Load maps tab with mapbox enabled
* Try zooming out
* Confirm map does not zoom out past a scale of 5000km
* Repeat test for public maps

**Comment by janagombitova** [comment]
👍  well done. Simple but less annoying :)
