### ISSUE TITLE
Monitoring window showing not more than 20 submissions per point 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2004]
In the Monitoring tab we show submissions based on data points. Once the user selects the data point a window opens with all the submissions for this data point. Currently we show up to 20 submissions. If there are more than 20 submissions to this data point, the user has no way of seeing them in the screen. 

We need to either expand the list of submissions we show in that window to show all, or allow the user to move the the other submissions. I would prefer an infinite scrolling option. 

![1](https://cloud.githubusercontent.com/assets/12456965/23986351/f6602f9a-0a23-11e7-991b-71e18f00e1da.gif)

**Comment by kymni** [comment]
We should at least consider introducing pagination for cases where responses are > 20

**Comment by muloem** [comment]
What if we have a complete redesign where we first of all do not have a pop-up window and secondly where we have an infinite scroll even if it updates itself in batches of 20?
