### ISSUE TITLE
Dependency drop down omitting full question group  

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2020]
When creating dependencies the user can select from a question that is in the question group she is working on, or from another question group. The dropdown shows her all the option questions that are located above the question she is currently editing. 

We have received a case in support, where the dependency dropdown works perfectly for most of all questions in the initial question groups but from one question group onwards there is one group fully omitted. I was thinking it could be if the group was pasted or moved around in the form, but the partner did not confirm.

**Here is the case** 
From question group 6 onwards (so for questions in groups 6, 7, 8 and 9) in the dropdown for creating a dependency the all questions from group 5 do not show.

- pacificwash.akvoflow.org
- Original survey: UNICEF Health: RMI --> Templates --> RMI: Household Survey_MASTER --> 3. Mother of Children (0 - 59 months) (Survey ID: 106111071)
- **A copy of the survey I made to do some testing:** same instance, Akvo Training Evaluation > RMI: Household Survey_MASTER --> 3. Mother of Children (0 - 59 months) (Survey ID: 113811085)

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-49322-from-nikki-at-akvo-dot-org

**Comment by janagombitova** [comment]
@stellanl and @muloem I have made a copy of the problematic survey on uat1.akvoflow.org to see what the issue can be. I tried to add in a new question, new question group, move the groups around, but nothing triggered the questions from group 5 to show in the dependency dropdown in group 6 and later. 

Can you please take a look at what might be going on? 

This is an isolated incident so far. But it make reoccur. 

You can find the survey here: 
https://uat1.akvoflow.org/admin/ > 1.9.18 UAT folder > Issue testing > RMI: Household survey_MASTER > 3. Mother of Children (0-59months) - form ID 139039138

**Comment by stellanl** [comment]
I believe it is because group 5 is repeatable. It is less straightforward to have questions in other groups depend on them, as they generally have several answers.

**Comment by janagombitova** [comment]
@stellanl that is so true and also the expected behaviour. I totally did not realise that. Thank you very much. Case solved. Will cross check the documentation to make sure this rule is clearly stated

Thank you Stellan
