### ISSUE TITLE
Tweak spring framework configuration to improve on performance of backend

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2022]
* [x] Define controller beans in rest-servlet.xml beans definition
* [ ] ~Set controller beans as singletons~
* [ ] Define controller beans dependencies (avoid auto wiring)
* [ ] ~Define DAO beans as singletons~
* [ ] what to do with static resources like `/favicon.ico`?

**Comment by muloem** [comment]
# Test Plan

Regression testing should catch any issues caused by these changes.

**Comment by janagombitova** [comment]
Nothing found in the regression round. We are good to go 👍
