### ISSUE TITLE
Improve loading time of device list

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2035]
I noticed on a partner dashboard that the Device list is loading all the devices ever connected to the dashboard (with some being last connected in 2013) 

<img width="1184" alt="screen shot 2017-04-11 at 16 20 56" src="https://cloud.githubusercontent.com/assets/12456965/24913898/e50c0ab6-1ed2-11e7-878d-5e172c466dca.png">

Considering the user can organise the Device list based on all the header items, I think we need to reconsider how many entries we show in the list. Secondly, are we showing only the last time device connected to the instance or are we showing every time a device connected to the instance?

**Comment by stellanl** [comment]
We show only the last time it connected, but it can still be a long list with all the phones that were ever used with that instance.
I think there are a few ways to implement this:

1 By default show just the devices seen in the last week/month/year, Then there is a button to push to "Show all".
2 Show a first page of, say, 30 devices, and then have the classic "Next page", "Prev page" controls.
3 Show a first page of 30 devices, and add to the bottom of the list as the user scrolls down.

I don't (yet) know how hard it is to implement any of them.

**Comment by loicsans** [comment]
There are several considerations on the subject (randomly in no particular order)
Should devices have a lapsing date? (ie. If a device has not connected to the instance for more than 6 months, it should automatically disappear from the list or get archived (somewhere) ).
This brings the question of device status: Active, inactive, deleted...
Maybe each devices should have a log of every time they connected but we should only show the last time it has connected in the table.

**Comment by janagombitova** [comment]
@loicsans those are interesting points. But they complicate things. Currently once an app is installed on a device the device is in the list (user facing - not sure how we handle things internally). We cannot delete a device from the dashboard, or enforce it to not collect data. The interaction is super simplistic - these are the devices connected to this instance > put them in an assignment.  These (and more) questions should be considered once we get to improving device management, groups, etc. 

With this issue we are trying to solve the problem that the list takes up to 45s to load what is too long and once it loads it shows all the devices ever connected to the instance, organising the list by the most recently connected device. The user indeed does not need to see the entire thing.

**Comment by Kiarii** [comment]
do we need the phone number col, how are these used? most appear 'encrypted'..

**Comment by janagombitova** [comment]
What we show in the table is another point to talk about. Ideally we would only need to Device ID, that the user sets to be able to recognise the device and assign it some forms. But having it and showing it is compulsory only in the recent app versions, so if the user did not update yet we would miss this information. User can decide if he updates or not. When assigning we show besides the ID the phone number or IMEI. So we need to unify what is used internally for identification, what is shown and how it all interacts. 

Once you start diving into the device list and groups you will definitely find a lot of improvement points. I think once we get to it, we need to look at the overall interaction: user - phone + app - assignment - manager assigning forms and managing devices. But again (and I know this is not the best practice - ignoring problems) we are not aiming to change how to devices interact or what we show in the table. We just need to find a way to load the list in faster.

**Comment by Kiarii** [comment]
I see. 

One option would be to paginate the device list so that only a handful devices are loaded on each page - maybe that improves the speed. (i just noted it takes some time to load the 109 devices in the sandbox instance) The list may by default be sorted by last contact/modified (added, edited)

Pagination may take two forms: 
- putting devices on separate pages and showing a specific page per view with page controls to go traverse the pages
- loading a 'page' below the other; e.g. by default showing a list of n devices, and a [Show more] button which loads another batch of n devices onto the list, and so on, so all devices end up in the same page but the list is loaded in batches. This might make it easier to do bulk actions as all devices are in the same view - but thats another thing..

**Comment by janagombitova** [comment]
Thanks @Kiarii And which would you recommend to take looking at how we list things in Flow currently?

**Comment by muloem** [comment]
@janagombitova Quick question, if the loading time of the device list was fast enough, regardless of the size of the list could we close this issue at that. And then handle the pagination etc in a different issue?

**Comment by janagombitova** [comment]
@muloem pagination was an idea to solve the loading time - how we solve it I am open to options. If you take a look at icco.akvoflow.org (highest instance class) the loading there is bad and the devices are super old.

**Comment by stellanl** [comment]
Re the phone numbers, modern SIM cards almost never have one stored (and Wifi-only tablets don't have one), so the device tries to send something else that is unique, usually the Wifi MAC address. From Android 6 that is not accessible to every app either, for privacy reasons.

**Comment by Kiarii** [comment]
@stellanl good to know. @muloem if we can work magic without paginating, it would later give us room to consider the optimal pagination option depending on what Salim / Petra does in/with the list..

**Comment by stellanl** [comment]
The /rest/devices endpoint is relatively straightforward. All devices and all devicegroups are loaded from the datastore, but with little conversion or copying (deviceDto wraps a Device), until the final conversion to JSON that the spring framework does. A hashmap is used to put the names of devicegroups into each deviceDao. 
From an optimisation POV, there are about a dozen data items for each device, at least 3 of which are not used in the dashboard (lastKnownLat, lastKkownLon, lastKnownAcc) and could be dropped.

**Comment by stellanl** [comment]
Some load times from akvoflow-23/Welhhungerhilfe with 1956 devices
When first selecting the Devices tab:
/rest/device_groups 3.4 s
/rest/devices 3.4 s
/rest/survey_assignments 10.6 s
(elapsed time was approx 19 s)

So the assignments dominate. They could be delayed until their subtab is selected.

**Comment by muloem** [comment]
# Test Plan

* Select the devices list and ensure it loads correctly. 

* Load the survey assignments list and also ensure that it loads correctly

**Comment by janagombitova** [comment]
👍  do not have any stats form UAT but on feeling it does seem to be faster
