### ISSUE TITLE
Minor UI improvements for Export reports

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2046]
# Export raw data report
![screen shot 2017-04-19 at 14 25 24](https://cloud.githubusercontent.com/assets/12456965/25179897/1c163574-250c-11e7-8f74-9b2153aca789.png)

* [ ] make the text for the two checkbox items the same font size as the "Export all submitted..." sentence 
* [ ] align that the two checkboxes are located before the sentence and not under it 
* [ ] text changes (see below) 
* [ ] remove advance settings button > show the options to export the sheet differently right from the start (under export last collection, if shown) 

**Please change text** 

**FROM:** Exports all submitted raw data for a single form to an Excel spreadsheet. This report will contain all responses submitted for the form. Please immediately make a local copy of this file before you make any changes. (same as raw data report)

**TO:** Exports all submitted raw data for a single form to an excel spreadsheet. 

**FROM:** Export this report for use with an external system. This export format cannot be re-imported into the FLOW system.

**TO:** This export format splits question options and cascade levels into separate columns and adds question IDs (if defined) in column headers instead of question texts. It cannot be re-imported into Akvo Flow. 

# Export comprehensive report 

* [ ] text changes (see below)

**FROM:** Exports all raw data along with optional summarized survey data including geographic areas and charts. must be saved as an .xls or .xlsx. this may take a long time and generate a large report.

**TO:** Export all raw data for the selected form with optional charts and summary sheets for geographic areas. 

# Export geographic shape 

* [ ] add space between question dropdown and Export button
![screen shot 2017-04-19 at 14 47 06](https://cloud.githubusercontent.com/assets/12456965/25180663/1ad6671c-250f-11e7-8025-39dd5418ef73.png)

# Export survey form 

* [ ] text changes (see below)

**FROM:** Generates a printable survey form in excel that can be used to conduct a paper-based survey. must be saved as an .xls or .xlsx

**TO:** Exports form questions in an Excel sheet that can be used to conduct a paper-based survey.

**Comment by kymni** [comment]
## Test plan
* Navigate to the Export reports tab
* Note the text changes as in issue definition
* Note alignment changes for checkboxes (should appear on same line as label) and question selection for geographic shapes

**Comment by muloem** [comment]
There is something strange about the way this appears now. First the option to export last selection should probably be closer to the dates. and it should probably have a note somewhere that its only valid for monitoring surveys.  Perhaps its even an idea to blur/disable the text instead of hiding it.

Second, the text about the export could easily invite a user to select the option because the warning about it not being reimported is only at the end of a long paragraph.

<img width="1178" alt="screen shot 2017-06-06 at 08 33 12" src="https://cloud.githubusercontent.com/assets/533336/26816630/e5ac6cd6-4a92-11e7-9544-e4138939fb3a.png">

**Comment by kymni** [comment]
Does appear a bit odd. We should consider prepending "Export for use with external systems" before the descriptive text. @janagombitova any thoughts?

**Comment by janagombitova** [comment]
Well spotted both of you

I agree. This is not clear, plus as Mulo pointed out in our call just now, we are combining two different export formats: 
1) one with all internal IDs in it and with options, cascades combined in one cell > the format we use for data cleaning 
2) one where options and cascades are split, defined IDs are shown > the format that should make analysis easier and using the data somewhere else as well 

For a bit of background: eventually in the future we want to make a clear division between the data cleaning export and the actual data export to: 
- make implementation easier for us and changes  
- not have internal IDs in users' data that they do not understand or use  
- to provide a structure that is easy to analyse and puts the answers in such a way that users can use it without having to do some manual preparation work of the data (splitting cascades into columns)

But this is a larger change that we need to think through properly

Coming back to these changes and next steps.  

The changes aim to make the format with split columns more visible and easily accessible to users. Let's push this for the later release and think of creating a separate export format for this data export (no checkbox but a separate field in the page) 

I agree, we need to state clearly that the export last collection is for monitoring forms.

Let's talk this through after the regression testing. Will give it some more thought as well

**Comment by janagombitova** [comment]
@kymni and @muloem with the changes to how we export repeated question groups, we will also change the UI for the Export reports tab fully. Kiarri is working on designs that will resolve also the problem we tried to quickly fix here. I am sorry for the extra work caused. 

There will be more changes needed on this topic. I was thinking of closing this issue and opening a new one so you can start fresh.
