### ISSUE TITLE
NPE in reporting data approval test

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2047]
GraphicalSurveySummaryExporter.hasRequireDataApproval() is not protected against some null values.
Boolean objects are a pain...

**Comment by janagombitova** [comment]
Testing on a monitored survey with a free text, number, location, signature, date and photo question on https://akvoflow-dev1.appspot.com/admin/ I have tested these cases: 
- all export types 
- importing new data 
- cleaning existing data 

Everything worked as expected. 

Is there a targeted test I can run?

**Comment by stellanl** [comment]
I made your latest test survey on dev1 into a test of the fix, and it passed.
