### ISSUE TITLE
Remove validation property for free text question types

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2053]
We currently have a property `isName` set for `Question` entities that corresponds to a validation rule for free text question types that correspond to people's names.  However, this validation is never executed since the validation rule is never generated in the survey output.  We therefore remove this property.

**Comment by janagombitova** [comment]
@muloem how should I test this one?

**Comment by muloem** [comment]
### Test Plan 

1. this issue should be adequately covered under the regression testing.  Questions (specifically free text type) should continue to behave as expected. i.e. creation, copying, saving etc.

**Comment by stellanl** [comment]
SurveySpreadsheetImporter.java still mentions the NAME type in an error message:
https://github.com/akvo/akvo-flow/blob/release/1.9.17/GAE/src/org/waterforpeople/mapping/dataexport/SurveySpreadsheetImporter.java#L439

**Comment by janagombitova** [comment]
@muloem have you addressed @stellanl comment? From the user side the free question type works as expected when creating, editing, using, filling in, cleaning and importing. So from my point of view it is good to go 👍  but we need a confirmation on Stellan's point

**Comment by stellanl** [comment]
It's just an error message that is slightly misleading. It's only shown when a user is trying to import bad data, so it's unlikely to cause problems for a real user.

**Comment by muloem** [comment]
Good catch @stellanl . After taking a look at the class, we currently do not call this code so infact the real solution here is to clear out the entire validate method.  But thats for another cleanup issue.  So @janagombitova we are good to go with this one
