### ISSUE TITLE
Follow up fix for UI on Messages tab

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2062]
<img width="1280" alt="screen shot 2017-04-27 at 13 42 50" src="https://cloud.githubusercontent.com/assets/12456965/25482784/82cc8e10-2b53-11e7-94bb-883ac10dfd52.png">

The while space that should hold previous and next buttons, appears on the Messages list giving the impression that the list is shorter than it truly is

**Comment by loicsans** [comment]
See below, fixed: Message popup appearing below breadcrumb, and fixed the white space appearing at the bottom of the messages tab
![apr-27-2017 14-58-02](https://cloud.githubusercontent.com/assets/1717219/25483044/e25cdb06-2b5c-11e7-862a-60acd11ff134.gif)
![screen shot 2017-04-27 at 15 18 38](https://cloud.githubusercontent.com/assets/1717219/25483045/e25d2f98-2b5c-11e7-8339-36420b773839.png)

**Comment by janagombitova** [comment]
fixed, ready to go

**Comment by stellanl** [comment]
Not sure if this fix is where it happened, but the messages page in 1.9.17 has two vertical scroll bars. (Probably only visible on Windows, as I believe Macs like to hide them.)

**Comment by janagombitova** [comment]
Nice catch @stellanl. I will add it to the existing issue https://github.com/akvo/akvo-flow/issues/1943 and lets handle it there
