### ISSUE TITLE
Validate email for Manual survey transfer 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2073]
Salim needs to fill in two items when he wants to get the survey files via email to manually put on his phone: he needs to select and add the survey forms and type in his email. 

If he does not select and **add** the survey forms and hits Send, we validate and tell him via a dialogue to do so. 

<img width="1270" alt="screen shot 2017-04-28 at 14 06 00" src="https://cloud.githubusercontent.com/assets/12456965/25528016/d71e6038-2c1b-11e7-8e98-cfc8374dd0e8.png">

On the other hand, we do not cross check if his email is correct. We do not cross check if there is an "@" or a "." in the email address that he types in. He can easily make a mistake in his email, but regardless of the wrong email format, or no email at all, we tell him that the surveys will be sent to his inbox. 

<img width="1255" alt="screen shot 2017-04-28 at 14 07 46" src="https://cloud.githubusercontent.com/assets/12456965/25528076/263c5d00-2c1c-11e7-9296-483302710c74.png">

We need to see how to tell Salim: 
- email is missing 
- his email is wrong

**Comment by muloem** [comment]
I am even wondering whether we should not eliminate the email address altogether and send it to the address of the currently logged in user.

**Comment by janagombitova** [comment]
That is a good point @muloem 

The only reason why I would imagine I want to send the file to a different email, is when someone in one location is setting up the surveys and someone in a different location setting up the devices. But this is just a guess, I am not sure if it actually happens in practice. 

I am talking with 4 different partners tomorrow and can ask them specifically about this, so we can even simplify based on your suggestion.

**Comment by janagombitova** [comment]
With the manual survey transfer we validate two things: if the survey form is selected and if the email is added (not the actual quality of the email). For both cases we show a modal dialogue if one or both are missing and the user hits send. 

I think it is easier to show the user directly that the she did not select her survey and form and is missing or has wrongly added the email (if we do not go for skipping this step fully) using in page validation. 

So with this issue we can consider: 
- remove email input and inform the user that the file will be sent to her email address
- validate that a survey form is selected and show in the page directly if not 
- reconsider the modal dialogue for once all is set and the user hits send
