### ISSUE TITLE
Fix null pointer exception when copying non monitoring forms

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2074]
When copying non-monitoring forms, we have a null pointer exception error thrown because the non monitoring forms do not have a registration form set.

Once consequence of this is that the loading spinner on the dashboard keeps spinning even after the copying is done.  We need to refresh the dashboard for it to disappear

**Comment by janagombitova** [comment]
After copying a non monitoring survey, the loading spinner did not keep on spinning, the message appeared correctly and once I went back to the survey list my copied version was there. So this fix is ready to go 👍 

Ideally we should not have to force the user to go to Messages and then back to see the copied new survey, but lets handle that separately.
