### ISSUE TITLE
Improve Assignments UI 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2075]
<img width="1257" alt="screen shot 2017-04-27 at 15 32 25" src="https://cloud.githubusercontent.com/assets/12456965/25534320/b47491fc-2c33-11e7-9126-7d148018ca9a.png">

The top part of the screen when users are creating an assignments is odd. We have Edit assignment title of the page there and the Go back button as well. It is taking up a lot of space and does not look aesthetic.

We have removed all page titles, so we should do that here for consistency reasons, plus it is clear to the user she is editing an assignment from what she sees on the screen. The Back button should be moved to the right side of the screen as that is where it is place in the Users tab. So lets go for consistency before we figure out a better spot for it, or a better UX. 

So to do: 
* [x] remove Edit assignment page header 
* [x] place Back button to the right side of the page

**Comment by Maseline** [comment]
Test plan
Navigate to Assignments list under devices
Select the option to edit any assignment
Note that the heading Edit assignment has been removed and the button to go back to the assignments list is on the right side of the page

**Comment by janagombitova** [comment]
All removed as it should be, but can we make one more cosmetic improvement? Now there is quite some extra unneeded white space between the subtabs and the first header "1. Assignment.."

Can you remove the white space? 

<img width="1214" alt="screen shot 2017-11-14 at 11 46 06" src="https://user-images.githubusercontent.com/12456965/32776071-af6176da-c931-11e7-8093-6bbfc7cf89a3.png">
