### ISSUE TITLE
Show copied survey right away

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2082]
Currently when a user copies a full survey, she takes these steps: 
1. clicks on Copy for the survey
2. selects the location for the copied survey
3. confirm the copying 
4. she sees the loading spinning and then the dialogue to cross check the success or failure in the messages tab, and does not see the copied version in the folder she selected yet
5. goes to messages tab to see if copied was finished
6. goes back to the selected folder and sees the copied survey 

These are a lot of steps to take for a simple operation as copying. We should think of how we can show her her copied survey right away while indicating that it is still in progress (perhaps)

This issue is a followup of this one: https://github.com/akvo/akvo-flow/issues/2074

**Comment by muloem** [comment]
Agree with this one.  It should be possible but requires some changes deeper in the guts of the system that will enable this to be added "for free".
