### ISSUE TITLE
Fix help text for repeated question groups 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2091]
We have had a support ticket with a partner asking why questions from a repeated group cannot be made dependent on? This is the expected behaviour of this feature: you cannot make a question outside of the repeated group dependent on a question in the repeated group. But this was unclear to the partner even though it is in our support documentation. 

Next to the repeat check box we have a help text explaining what it means and what the implications are. As @stellanl noted, we should more clearly state what happens if you make a group repeatable. 

<img width="661" alt="screen shot 2017-05-08 at 10 51 30" src="https://cloud.githubusercontent.com/assets/12456965/25802906/c9d2ca3c-33f4-11e7-92b0-2a08c1c604a1.png">

This is the current text: 
Often a number of questions need to be asked multiple times, e.g. when you want to ask the same questions to each member of a household. This function lets you specify that a question group is repeated a number of times during the collection of data. 

Proposed new text: 
By repeating this question group you can ask questions in this group multiple times, e.g. when you want to ask the same questions to each member of a household. You will decide on the number of repetitions when capturing the answers in the Akvo Flow app. You cannot make a question outside of this group dependent on a question inside the group. 

@stellanl and @muloem what do you think?

**Comment by bogere** [comment]
## test plan
* click show questions 
* click on Repeat question group help tooltip
* The help text is changed and more clear

**Comment by janagombitova** [comment]
Looks good to me
