### ISSUE TITLE
Sorting of questions vulnerable to db corruption

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2096]
#1442 and #1736 sorting code introduced vulnerability to db problems: questions that are organised in the wrong survey (surveyId not same as the surveyId of their Question Group) cause an NPE.

**Comment by stellanl** [comment]
Test plan:
Create two questions in the same group.
Go into the GAE datastore manager and set the questionGroupId field of one of them to null
Go back to the Flow UI, redisplay the form; the other question should still be shown.

**Comment by janagombitova** [comment]
@stellanl confirmed all works as expected 👍  so we are read to go
