### ISSUE TITLE
Pressing enter while renaming things is confusing

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2117]
In FF, while renaming a Survey Group, editing of the string just ends, which is confusing to the user, as the new name is shown, but is not sent to the server.
Tested on Windows 7,  Firefox 53.0.3 (works on Chrome 58)

Also, when renaming a Survey in FF 53 or Chrome 58, pressing enter reloads the entire dashboard, instead of saving the new name.

**Comment by muloem** [comment]
This is the same as #1929.  I'll close this one and copy comments over
