### ISSUE TITLE
Geoshape map in Inspect data tab

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2120]
When viewing submissions in the Inspect data tab, the user can see a small map with the geoshape rendered on it. She can zoom in and out of the map and change the map layer. This is the normal expected behaviour. 

However, when testing the current UAT build: v1.9.17-44-ge980b3d76 I noticed that the map is so zoomed in that you cannot see the tiles anymore. 

<img width="1233" alt="screen shot 2017-06-06 at 14 49 32" src="https://cloud.githubusercontent.com/assets/12456965/26829905/6ca66118-4ac7-11e7-9cdc-9ea6cdfa121e.png">

Can we restrict this that on the map you do have the zoom level that shows the tiles and the shape is in the image?

**Comment by janagombitova** [comment]
<img width="1231" alt="screen shot 2017-06-06 at 15 03 25" src="https://cloud.githubusercontent.com/assets/12456965/26830487/514bc92e-4ac9-11e7-8f8b-29049ae90355.png">
Another example of a way too much zoomed in goeshape map, where the zoom level is the default after opening the submission

**Comment by kymni** [comment]
Fix included in maps refactor branch

**Comment by janagombitova** [comment]
Tested on flowaglimmerofhope and looks and works as expected. Well done 👍

**Comment by janagombitova** [comment]
Also ready to roll as part of the refactor work 👍
