### ISSUE TITLE
Question IDs - simplify validation

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2143]
# Current implementation 
When creating a question ID we validate two things: the format, uniqueness. 

If the input does not pass the validation we show in red the info above the text field. The user can hit Save, to save the question, but he will receive a modal dialogue telling him the same info as the red error message. He needs to confirm, what brings him back to the question. He cannot save the question until he makes adjustments to the ID

<img width="1196" alt="screen shot 2017-06-06 at 12 29 37" src="https://user-images.githubusercontent.com/12456965/26837607-27cfb9d8-4ade-11e7-85c4-227b55dead82.png">

<img width="1216" alt="screen shot 2017-06-06 at 12 29 46" src="https://user-images.githubusercontent.com/12456965/26837619-335293e8-4ade-11e7-9377-4af4b068e788.png">

**Validation error messages**

<img width="1221" alt="screen shot 2017-06-06 at 12 29 26" src="https://user-images.githubusercontent.com/12456965/26837646-433519b6-4ade-11e7-8e9b-82503c13f254.png">

<img width="1081" alt="screen shot 2017-06-06 at 12 29 56" src="https://user-images.githubusercontent.com/12456965/26837661-4be4b648-4ade-11e7-8cf3-a20a0863a66a.png">

 **Modal dialogues after trying to save the question** 

If the user hits Cancel, then the ID is not saved. 

# Improvement 
Would it be possible to instead of showing that the ID format is not correct, being able to click on save and getting the pop up message, to simply validate the field (as we do) and disable the save button, removing the modal dialogues? 

Secondly, the text for the uniqueness validation needs to be improved: 
Current text: the question id is not unique 
New text: 
- option A: Question ID is not unique 
- option B: Question ID already exists 
- option C: ... to be defined ...

@muloem and @kymni what are your thoughts?

**Comment by janagombitova** [comment]
Before we make any improvements to the validation of the question IDs we need to agree on if we change how we call this feature: https://github.com/akvo/akvo-flow/issues/2170

**Comment by kymni** [comment]
#2170 remains open, what's the way forward for this?

**Comment by janagombitova** [comment]
My suggestion would be to 1st handle #2170 so move away from Question ID and implement Variable name throughout all Flow components and then handle this issue by disabling Save is the Variable name is not correct and simplify the validation notes.

**Comment by janagombitova** [comment]
@kymni I have noticed one small detail that need to be improved before this can go live:  if the variable name is not unique, the current error message says: `Variable name not unique`. Can you please change it to: `Variable name is not unique`

<img width="511" alt="screen shot 2018-02-06 at 10 02 37" src="https://user-images.githubusercontent.com/12456965/35850587-a5152038-0b25-11e8-9fe9-819ae10d708e.png">

**Comment by kymni** [comment]
Slightly related but current in current implementation, the error message is hard-coded. I'll create a separate issue to change this so that error message is pulled from transifex while at the same time implementing your change request

**Comment by janagombitova** [comment]
Perfect, thanks @kymni. This one is then ready to roll 👍
