### ISSUE TITLE
Change order of tabs under Reports 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2151]
Currently once the user lands on **Reports** she sees the Charts subtab first, that is not used so much, buggy and eventually we want to move this to Lumen (somehow). To get to the data exports she needs to navigate to the Export reports tab. 

<img width="1164" alt="screen shot 2017-06-09 at 10 52 01" src="https://user-images.githubusercontent.com/12456965/26968267-b0ee376a-4d01-11e7-8b16-37ddb97b7ed0.png">

Lets switch the two. The Export reports should be the first tab, the one you land on after clicking on Reports. The second tab should be Charts.

**Comment by stellanl** [comment]
Totally agree. I often navigate 5 levels down before I realise I'm on charts, not reports, and have to do it all over again...

**Comment by janagombitova** [comment]
Missing Test plan... but this is quite straightforward: the tabs open as expected and in the new order on different browsers and for all languages. Ready to go 👍 

One small change for Flow, but a big change for our users ;)
