### ISSUE TITLE
Remove Maps tab from WHH instance 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2153]
Welthungerhilfe has requested us to remove the Maps tab from their dashboard for now as any user can open any data point, regardless of their roles and permission, and see the data. This is not in compliance with their data security policy they have to comply to. 

The Maps should be not accessible form the instance when logged in. The public map can remain as it is. Once we have the new Akvo Maps implementation in place with filtering based on folder>survey>form we can bring the maps back to this instance. 

The instance is: akvoflow-23

**Comment by janagombitova** [comment]
The problem we are trying to solve here is the fact that you see all the data on the map, regardless of what permissions you have (view data linked to particular folders, surveys, forms). The user cannot define which survey > form data he wants to see, but sees all the data points and answers on the Map. 

For the partner fully removing the Map is a good option for now. My question is: what is the difference in effort: removing the entire tab vs adding the folder>survey>filter to the current maps? 

The issues around clustering, data points that are deleted still showing, showing answers as json, will be resolved with the implementation of Akvo Maps. I am just wondering how to best address particular issue quickly. We need the change to go out with the next release. 

@muloem what are your thoughts?

**Comment by janagombitova** [comment]
We have agreed with @muloem that he will change the Maps feature (maps after user is logged in) to be based on a feature flag. Once we receive the confirmation from WHH we will simply redeploy their instance only with the flag turned off.

**Comment by muloem** [comment]
# Test Plan

* We need to set the feature flag `showMapsTab` to `false` in order to hide the maps button.  If we set it to any other value or leave it unset, the maps button will be shown by default.

**Comment by janagombitova** [comment]
@muloem when testing maps on UAT1 version v1.9.19-36-g56525b3 for the Carto implementation I got this error. I tried to check data for a survey created yesterday, that worked on the map without troubles and today the points did not lead and the loading spinner just kept on spinning. 

It is happening for multiple different surveys I try 

![Screen Shot 2017-06-28 at 12.50.14.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555c896361fa0e150055f235/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256456fb6b7191a379ed0c2e51415e4abe5d4a1f06a3a3dc78e2a436628f5b5debd0395a22cf3f18afb1874bbb01ba71884985e3bf9850d2aa6c7bb3d4d216744b470a83ed5f33aa984fc150f04fe64d56a2103262f43b.png)

**Comment by janagombitova** [comment]
👍  all good now
