### ISSUE TITLE
Help with the HOST_GID

### ISSUE THREAD

**Issue by sgatibaru** [akvo/akvo-flow#2159]
I am getting a 
> `./startup.sh: 21: ./startup.sh: HOST_GID: parameter not set`
error when i run `docker/startup.sh` and i cant continue from there..

Ultimately, my main challenge is getting the whole system to work. I've been at it for the last three weeks now and its really frustrating. Do i run `./bootstrap-build.sh`? which resulted in a console error..:
`/usr/local/bin/build.sh: line 29: cd: /app/src/Dashboard: No such file or directory
`

**Comment by muloem** [comment]
Hi @sgatibaru quick question.  Are you trying to run the tool to evaluate it? If its to run a demo we can arrange for that without having to run it. cheers!

**Comment by sgatibaru** [comment]
Hi @muloem Hope you are well. I am not trying to run an evaluation version. I would like to install it and use it on a live server on a project I'm involved in.
When i run `sudo docker run 5a76561f7372`
i still get 
`usr/local/bin/startup.sh: HOST_GID: parameter not set`

**Comment by iperdomo** [comment]
@sgatibaru the `docker` folder and scripts are just for building in a [CI environment](https://travis-ci.org/akvo/akvo-flow/builds), not for setup a local dev/test environment.

**Comment by iperdomo** [comment]
@sgatibaru if you have Docker installed, you could try:

    docker pull akvo/flow-build
    ./docker/bootstrap-build.sh

That will give you a built code that should be usable.
