### ISSUE TITLE
Bug in survey structure fix script

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2165]
The version finally checked in has a bug.
(The version that was run on all the instances did not.)
The questions fixes look at the wrong booleans.

**Comment by janagombitova** [comment]
Is this fully done for the release and is there anything I can test?

**Comment by stellanl** [comment]
No, you'd have to dig deep in the datastore so set up a test.
And it will only be run by a developer anyway.

**Comment by janagombitova** [comment]
Ok. But all is ready for this release, right?
