### ISSUE TITLE
Investigate orphaned questions and question groups

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2167]
We have a number of situations that seem to be causing question groups and their related questions to be orphaned or misconfigured.  By orphaned, we mean question groups and questions with a property `surveyId` that refers to a form that no longer exists.  By misconfigured, we refer to a situation where the question groups and the questions do not point to the same `surveyId`.

There are a number of possibilities of what causes these issues that have to be investigated and correctly reproduced before attempting to fix
* [ ] Tasks that are related to survey creation e.g. tasks for question copying, survey copying, question deletion - tasks are run in a different request from the one that originally made the request and perhaps in some cases, due to an exception that occurs while copying, they are retried and therefore we and up with duplicate or incomplete entities in the datastore

* [ ] Dashboard UI state -  in the dashboard UI, we implement a controller `FLOW.selectedControl` that manages state of entities that are currently selected. This could go out of sync and end up causing issues such as misconfigured question groups and questions

**Comment by stellanl** [comment]
There is also a group of orphans that have null for their "parent pointer".
