### ISSUE TITLE
Update translation strings

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2168]
Update to the most recent translation strings

**Comment by janagombitova** [comment]
Found a few small issues with the French translation: 
- Data in the main navigation menu starts with a lower case - should be capital 
- is Messages in the main navigation menu translated? 
- is Message in the Messages table translated?

<img width="893" alt="screen shot 2017-06-28 at 12 59 44" src="https://user-images.githubusercontent.com/12456965/27634007-da1147cc-5c01-11e7-9ed1-8a78dd6b6242.png">
<img width="1186" alt="screen shot 2017-06-28 at 13 00 24" src="https://user-images.githubusercontent.com/12456965/27634013-db1f0ece-5c01-11e7-80bd-c9d74c5bd540.png">

**Comment by valllllll2000** [comment]
@janagombitova your first point yes it needs to be fixed. As for Messages it is written the same in French and yes it is translated

**Comment by janagombitova** [comment]
👍 all looks good now. Ready to go
