### ISSUE TITLE
Question IDs confusion 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2170]
Most of our users do not know what the question IDs can be used for. 

Even though the explanation says what the functionality is for; the location of the feature (defining it when defining the question) is good and the validation to ensure all IDs are unique is also well implemented, we have heard during few interviews around data exports that it is a shame you cannot define the value name to not have to deal with the long question names. Thus, users realise this is important to have but either they: 
- do not know at all that this is possible via the question IDs
- do not know what the question ID stands for 
- do not know how to get it out in the exports (handled in a separate issue) 

<img width="672" alt="screen shot 2017-06-27 at 07 39 44" src="https://user-images.githubusercontent.com/12456965/27572360-d15a0246-5b0b-11e7-8276-6cd6fb4c332c.png">

The idea of the question ID is to act as a value name in data export, so the analyst does not have to deal with long column headers (normally question names) 

With this issue we want to answer the question: How can we make the value of question IDs more clear to our users?

**Comment by stellanl** [comment]
One way to make their function clearer is generating a default id automatically. It could be as simple as q001, q002, q003. The user can then either improve it or keep a usable default value. Either way someting shows up in the reports...

**Comment by janagombitova** [comment]
I disagree on that one Stellan. The ID is considered a variable name that users need to be aware of as they based on it know what to search for in the data. If we generate another ID for them, they will have no use of it as they won't know where the information came from and what it means. Secondly, from the case we have in Ghana, the link Flow data in their national database based on these IDs, that were first created in the database. So then they would have to go into each form and not only create their own IDs but also delete ours.

**Comment by stellanl** [comment]
Oh, I did not mean to generate it hidden, silently. I mean when you create a q it gets a default ID so that you see that this is an expected thing. But it's right there to be edited from the start.

**Comment by muloem** [comment]
Perhaps we should consider renaming the field. First because it already causes confusion internally.  question Id currently refers to two completely different things.  Second because it perhaps doesn't mean anything to a user who is an analyst.  Something like _question code_ might be more appropriate to the users

**Comment by janagombitova** [comment]
@stellanl I still think we should not generate the IDs for users, visibly. It is not something everyone uses (as many of our users identify the data based on the question and do not import Flow data to other tools).

I agree with you @muloem. Maybe a new name will make it more understandable and some newsletter communication and a good support example can do the trick. Making it more clear in exports, is a different discussion. 

Options: 
- question code
- variable name (mentioned by CDC) 
- column title - called like this in Lumen (we should go for consistency across our tools)

**Comment by janagombitova** [comment]
After looking at tools our users import their Flow data into, talking with Karolina (our data analyst), asking our users who have been asking for the feature (even though it is in Flow already) and some intensive googling the option `variable name` seems to be most widely used not only for the purpose identical to Flow's question ID but also the rules of it being unique and which characters are not allowed are commonly applied for variable names. 

To conclude let's stop using question ID, but `variable name`.

We need to make sure we are consistent in: 
* [ ] survey editor (no changes to behaviour, only field name changes)
* [ ] improve help text in survey editor 
* [ ] for data exports with advance settings
* [ ] in the code to avoid confusion with Flow's question IDs
* [ ] API 
* [ ] support documentation (Jana)
* [ ] external comms piece (Jana)

@stellanl and @muloem have I missed anything? Do you agree or disagree?

**Comment by stellanl** [comment]
Always in favor of reducing the internal/external name mess.
In the code, it's easy to rename methods and the API's that are only used by us (Dashboard and reporting engine). 
Much less easy are the object fields that become data store column names. We have avoided changing those in the past, to get out of migrating existing data.
(The device reported app version still in a field called gallatinSoftwareManifest...)

**Comment by iperdomo** [comment]
I'm joining a bit late to the conversation but I would suggest to _not_ use the term: `variable name`, that's a _programming_ concept, not a _data_ related one. Since we're dealing with _data_, we should aim for something like: `unique question identifier` (if we like long names). 

Since this feature is an _advanced_ one, we shouldn't try to hide or ease the complexity of dealing with data synchronization across systems. https://en.wikipedia.org/wiki/Column_(database)

**Comment by stellanl** [comment]
OTOH, the reported problem was that those generating reports did not know this existed...

**Comment by janagombitova** [comment]
Not each Flow user will use it, that is true as for many identifying and working with columns based on question text is a common practice. However, the identified problem that this issue is trying to solve is, that users who do not want to work with long question names when working with data, who know that value of what is currently called in Flow question ID, did not know that Flow's feature is what they are looking for. W

e have spoken with multiple Flow users, with advance skills in data science, who work in statistical tools and/or who import Flow data into other databases. Thus the users of this feature and they used the word `variable` when referring to answers in one columns. The combination variable name, variable label and variable ID were used by different users we spoke with. After cross checking with the tools commonly used by these users, variable name was most common and recognisable for the target audience of this feature.

As mentioned above, how we allow users to export data with the variable name or with question text is dealt with in a different issue.

**Comment by iperdomo** [comment]
I think there is a misconception of the problem this property is trying to solve. The main purpose is not for _"users who do not want to work with long question names"_ but for _"data integration"_ between systems. In my company database and I call a column `first_name` while the exported dataset has a "First Name" as question text. I can use a `unique question identifier` (or `question id`) for mapping: `furst_name` and make easier the [ETL](https://en.wikipedia.org/wiki/Extract,_transform,_load) process
It turns out that this _can_ be used for other purposes like the one you mention, but was not the main purpose.

**Comment by janagombitova** [comment]
As we have seen with more Flow features, our users expand their implementation outside of the use case they were originally designed for. What I personally think is a good thing. We should not, however, avoid improvements just because they do not fit the original purpose. The current main cases are, as you mention, integration and analysis. By changing the field in the UI to variable name we do not take away the value for the original use case. How the feature works will not change. 

@iperdomo do you have specific concerns this name change can bring to our users?

**Comment by janagombitova** [comment]
@kymni I just realised we will also need to update the help text in the survey editor for the variable names. I will draft the copy with the MarComms team and create a separate issue to handle the change. Thus this is just a reminder for me to not forget about this task.

**Comment by janagombitova** [comment]
Looks good 👍
