### ISSUE TITLE
Find bad ancestorIds fields

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2174]
The survey structure checker dies if it encounters a question with a null surveyId.
Also, it should find/fix any problems in the ancestorIds fields of Surveys and SurveyGroups. To finally get rid of the path we want to be able to rely on ancestorIds.

**Comment by muloem** [comment]
Have you encountered some issues with the ancestorIds?  There was a script that was for checking and correcting this. https://github.com/akvo/akvo-flow/blob/022eb3980581c07456ee9404079dfcdb6e62454f/scripts/data/src/org/akvo/gae/remoteapi/PathToIdMigration.java
