### ISSUE TITLE
Exclude static files from security filter

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2183]
A number of requests for static files that we serve from the application are passed through the security filter chain.  These requests do not need any security validation and should therefore be excluded from the security filter chain.

**Comment by muloem** [comment]
## Test Plan

1. During regression testing pay particular attention that assets like images and styling behave as expected in addition to other functionality.

2. Attempt to access the application when not logged in and verify that you are redirected to login before gaining access.

**Comment by janagombitova** [comment]
From a first brief regression round all looks ok. Will take a better look at the full regression round, but I believe this is good to go
