### ISSUE TITLE
Add macOS dev environment script for Dashboard builds

### ISSUE THREAD

**Issue by osg74** [akvo/akvo-flow#2188]

**Comment by janagombitova** [comment]
Can we consider this Done Done? @valllllll2000, @muloem or @stellanl

**Comment by valllllll2000** [comment]
I think ideally this should be tested with a MacOs, ideally with an environment which has not been setup/not updated. @muloem or @stellanl maybe one of you can do this with the next deploy of the dashboard

**Comment by stellanl** [comment]
Sorry, I don't have access to any Apple devices

**Comment by janagombitova** [comment]
@muloem How do you suggest to proceed regarding this issue?

**Comment by janagombitova** [comment]
@muloem Bump
