### ISSUE TITLE
Bad filename in css (or missing png)

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2198]
main.css has a reference to /admin/images/addbtfullWidthn.png as a background image. It does not exist.
There is an /admin/images/addbtn.png, so probably a "fullWidth" was pasted into the middle of the ref by mistake.

**Comment by stellanl** [comment]
@janagombitova , should i fix this one? It is simple enough, but the image has not been shown for a long time...

**Comment by janagombitova** [comment]
@stellanl sure, go for it

**Comment by stellanl** [comment]
Possibly the "fullWidth" that was in the middle of the filename was supposed to be paste in somewhere else in the file. We may want to look for that.

**Comment by janagombitova** [comment]
@stellanl is there something to test here?

**Comment by stellanl** [comment]
I am guessing that some/all "Add" buttons now have an icon that was missing before.

**Comment by janagombitova** [comment]
All "add" buttons look good to me
