### ISSUE TITLE
JSON in rollup titles make reporting engine loop forever

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2206]
Something we missed in #1968. The name-testing loop never terminates when it gets JSON to eat.

**Comment by stellanl** [comment]
This started with a WHH support request, where they could not get comprehensive reports out. And that report ended up hanging the entire flowservices server.

**Comment by stellanl** [comment]
Problem is primarily caused by the faulty #1968 assumption that all JSON responses are OPTION answers. 
See Datautils.jsonResponsesToPipeSeparated().
The WHH survey has Cascade answers that are not parsed correctly.

Also, it is demonstrably dangerous to loop until a sheet name is acceptable to the Excel otput library. We should give up at some point, like after 1000 tries.

**Comment by janagombitova** [comment]
👍 looks good and works good as far as I can tell
