### ISSUE TITLE
Update deployments to use new Google Cloud SDK

### ISSUE THREAD

**Issue by osg74** [akvo/akvo-flow#2207]
- See https://cloud.google.com/appengine/docs/flexible/java/download
- Also update builds to use Java 8 as needed

**Comment by muloem** [comment]
The current app engine SDK that we are using will be deprecated end of July 2020.  We should upgrade to using the gcloud tooling. See: https://cloud.google.com/appengine/docs/standard/java/sdk-gcloud-migration

**Comment by iperdomo** [comment]
Close in favor of #3377
