### ISSUE TITLE
Validate number type question based on previous question

### ISSUE THREAD

**Issue by smaloda** [akvo/akvo-flow#2210]
I do not see option for akvo flow to validate number type question by using value of previous question. Example having Question A and Question B, on which value of Question B should be less or equal to value of Question A. Please help.

**Comment by janagombitova** [comment]
Hi @smaloda,

That option is not currently available in Flow. 

Cheers, 
Jana

**Comment by smaloda** [comment]
Thanks so much Jana for prompt response, is there any any plan for this to
be implemented soonest?

Regards,
Sylvester

**Comment by janagombitova** [comment]
Hi Sylvester,

We definitely want to add such a functionality in Flow to enhance the survey editor, but it will not be happening in the nearby or close future. You can check our roadmap to see what areas we are focusing on in Flow's development here: https://app.productplan.com/p/1vITLiNZkRWNCIiBI51KFQesKxnwe3TB

All the best,
Jana

**Comment by janagombitova** [comment]
We will first discover this opportunity here https://github.com/akvo/akvo-product-design/issues/275 before moving the detailed solution ideas to this repo
