### ISSUE TITLE
NPE creating report header for Caddisfly questions

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2216]
In createRawDataHeader L1305, the caddisflyUuid field is assumed to be non-null for a caddisfly question.
Bad assumption.

**Comment by stellanl** [comment]
Test plan:
Run a report on akvoflow-60 form 44980913.
You should get one.

**Comment by janagombitova** [comment]
Not sure this falls under this issue, but here I go: I have tested out a form on UAT1 with Caddisfly data collected to it and when I export, I only get the submission where the Caddisfly data was **not** submitted. 

I should have three submissions in my export where one has no Caddisfly data and two do. I only get the one without the Caddisfly answers in my export. 

You can download your report from https://flowdev1.akvoflow.org/report/uat1.akvoflow.org/88855b0b-2f72-47c2-8630-91387620b8fc/RAW_DATA-90889115.xlsx

![screen shot 2017-08-30 at 09 45 17](https://user-images.githubusercontent.com/12456965/29860991-11b7f512-8d68-11e7-9e39-380451ac7061.png)

**Comment by janagombitova** [comment]
Ignore my message above, my mistake. All works fine when downloading data with Caddisfly answers in there too
