### ISSUE TITLE
Data import geolocation errors in SurveyedLocales service

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#2218]
The following issue has been reported on mobile:
https://github.com/akvo/akvo-flow-mobile/issues/823

If a user imports submissions via data cleaning, creating new submissions and then syncs them to the app, sometimes some answers miss. 

In the example below, I have created a form with some basic questions and a repeated group. In the app for points "Test -J-10", "Test-K-11" (examples of a few) the location answers as not displayed in the History. However, they do show on the map. For points "Test-I-9", "Test-H-8",  (examples of a few) the repeat question group answers miss.  For other points no answers miss in the History view. It is quite random. 

[Example - RAW_DATA-175119141 (1).xlsx](https://github.com/akvo/akvo-flow-mobile/files/1196988/Example.-.RAW_DATA-175119141.1.xlsx)
The survey used is: https://uat1.akvoflow.org/admin/ > _1.9.22 and 2.4.0 UAT tests > Data only imported

**Steps to reproduce** 
- create a new form (monitored survey so you can sync the data points to the phone, but one form is enough) 
- export the form via data cleaning 
- fill in answers in the sheet and import the data (basically you do not create submissions via the app but misusing the import) - see things to keep in mind here: http://flowsupport.akvo.org/article/show/can-i-import-data-into-a-registration-form
- check in messages that the import was successful and the sheet is processed 
- check in inspect data tab that the answers show properly 
- add the form to an assignment to your phone 
- get the form to your phone 
- sync in the data points 
- check a data point in its History is all answers show

After investigating on the device, it appears that the "corrputed" datapoints have a duplicated entry for GEO question:
`{"surveyInstances":[{"qasList":[{"q":"179759148","a":"1.3828|1.103686|1|","t":"GEO"},{"q":"179759148","a":"|||","t":"GEO"},{"q":"179759147","a":"J","t":"FREE_TEXT"},{"q":"177559136","a":"bla nlo","t":"FREE_TEXT"},{"q":"177559136","a":"bla","t":"FREE_TEXT"},{"q":"180639139","a":"10","t":"NUMBER"},{"q":"179749152","a":"Test","t":"FREE_TEXT"},{"q":"178739132","a":"yes","t":"OPTION"},{"q":"178739132","a":"yes","t":"OPTION"}],"uuid":"13af7619-2003-4631-9a1d-af64d8babfd5","collectionDate":1501756568090,"surveyId":175119141,"submitter":null}],"surveyGroupId":176199148,"lastUpdateDateTime":1501756706762,"lat":1.3828,"lon":1.103686,"displayName":"Test - J - 10","id":"h603-uwds-gx5x","identifier":null,"keyId":null}`

Looking closely at the data we can see that in the qaList first we get:
{"q":"179759148","a":"1.3828|1.103686|1|","t":"GEO"}
and then:
{"q":"179759148","a":"|||","t":"GEO"}

After looking in the datastore QuestionAnswer does contain 2 entries for the same SurveyInstance and question Id:
- The correct answer
- The corrupted answer with the answer value as |||

**Comment by janagombitova** [comment]
I have tested this issue again as you mentioned here https://github.com/akvo/akvo-flow/issues/2229 that it might be resolved with the changed in the linked issue, and I am not getting the problem anymore. All the answers from the imported submissions show in the History tab. 

Thus closing this issue for now and will reopen if we meet the problem again
