### ISSUE TITLE
Update configuration files to include instanceUrl field

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#2219]
After the changes done to survey.properties files for the app to display the "user friendly" dashboard url for each partner https://github.com/akvo/akvo-flow-mobile/issues/804, we need to also update the configuration file https://github.com/akvo/akvo-flow/blob/develop/Config/instanceConfigurator/src/org/akvo/flow/InstanceConfigurator.java#L211 for future instance config files to be generated with that field included as well by adding:
`apkData.put("instanceUrl", "https://" + bucketName + ".akvoflow.org");`

**Comment by janagombitova** [comment]
@valllllll2000 is this issue still relevant?

**Comment by valllllll2000** [comment]
@janagombitova yes still relevant, has not been done yet

**Comment by valllllll2000** [comment]
## Test plan
Nothing to test here, only config files changes
