### ISSUE TITLE
Validate against nameless questions

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2221]
# Context and problem
Currently if the user removes a text in the question text field, she can still save a question without a name. This is not a good practice, as we cannot allow users to save nameless questions. Once the form is in the app, how is the enumerator supposed to deal with a question with no name Furthermore, the exports reports give a NPE. 

<img width="1072" alt="screen shot 2017-08-22 at 07 24 55" src="https://user-images.githubusercontent.com/12456965/29549881-07b3c194-870b-11e7-9dbd-aae1973c4c57.png">

When a user creates a new question, we by default name it: New question - please change name. Once the user starts editing the question, she removed the default name and then types in her own, chooses the question type and other settings and saves. However, now she can remove the default name and make other changes to the question settings and still save. 

# Ideas and next steps 
The question text should be a mandatory field without which the user cannot save the question. An option can be to not enable save only once there is at least one character given for the question text. 

@loicsans and @Kiarii How would you propose to ensure that there is always a text defined for a question?

**Comment by loicsans** [comment]
There is a very simple way to reinforce that text input are filled in upon saving. HTML5 provides a handy "required" attribute that returns an error if the input is empty.

**Comment by loicsans** [comment]
Added support for required attribute, which is not supported natively
in ember. Added the required attribute to the textField, however this
doesn’t work. @muloem any idea?

**Comment by Kiarii** [comment]
one option would be that on clicking save the, flow shd bring the empty field into view with a guide text e.g. "This field is mandatory", maybe also highlighting the field border with red.. (not sure if the framework supports such interactions - perhaps we shd clarify what ember can do inorder to design accordingly)

**Comment by muloem** [comment]
@loicsans the problem as I see it, seems to be that the `required` HTML attribute also needs to work in conjunction with a `Submit` button for the form.  But the `Save` button isn't a `Submit` one.  So either we need to update the HTML so that `Save` is a submit button, or a bit more work in javascript to handle the validation.

**Comment by janagombitova** [comment]
Works like a charm! Well done @kymni 👍
