### ISSUE TITLE
Improve SurveyedLocale loading part 2

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#2229]
After making the changes https://github.com/akvo/akvo-flow/issues/2220 @muloem suggested it would be better to make 2 further improvements to this code:
* Replace SurveyalValues by the object QuestionAnswerStore
* Instead of querying the SurveyalValues using surveyedLocales ids, first request SurveyInstances and use surveyInstances ids to query QuestionAnswerStore 

As a result we may even solve the following issues:
https://github.com/akvo/akvo-flow/issues/2218
https://github.com/akvo/akvo-flow/issues/1843
https://github.com/akvo/akvo-flow/issues/1839
https://github.com/akvo/akvo-flow/issues/1830

**Comment by valllllll2000** [comment]
## Test plan
Please test datapoint sync on device with large surveys

**Comment by janagombitova** [comment]
👍  all seems to be working well. The above linked issues. I will check once done with the main testing and comment on them individually to see if they are solved as well
