### ISSUE TITLE
Caddisfly test definitions file environment variable

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2250]
After a caddisfly refactor in #1825 we have the URL of the caddisfly tests definition file hard coded to be loaded in the dashboard.  However, we need to be able to change this URL to have environment specific test definition files.  e.g. one for a test and one for production environment.  We would therefore like to introduce an environment variable that can allow overwriting the default tests file URL.

**Comment by muloem** [comment]
## Test Plan 

1. Update the configuration file of an instance to include a different caddisfly URL

2. With the browser in dev mode ensure that when opening a survey, that URL is the one requested for caddisfly test definitions

**Comment by janagombitova** [comment]
Tested out on UAT 1 to ensure all works as it should in the production state. 👍  and all does work and the url is loading upon opening a survey

`jquery.min.js:2 XHR finished loading: GET "https://akvoflow-public.s3.amazonaws.com/caddisfly-tests.json".`
