### ISSUE TITLE
Survey publishing process silently skips groups and questions with bad order values.

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2251]
If there are duplicated "order" values for groups in a survey or questions in a group, only one of those groups/questions will appear in the published XML file.
This is because the lists of groups/questions are kept as TreeMaps with order keys, so later items overwrite earlier ones with identical order values.

I see some options:
 * To make for more correct surveys, the publishing process should fail, and then notify the user (as it does if S3 is unavailable). This is means they will have to ask support to fix it,  and/or we could run structure checks automatically to alert us to these problems.
 * To make a more fail-tolerant process, the publishing could go ahead and send everything with the bad order values to the app. This will look a bit bad, and may confuse data collectors.
 * Publishing could start by reordering things if necessary.
 * We could check for and flag order problems in the UI, so that  they are noticed sooner.

Changes probably belong in org.waterforpeople.mapping.app.web.SurveyAssemblyServlet.assembleSurveyOnePass(Long)

**Comment by janagombitova** [comment]
Related issue regarding wrong order of questions and question groups https://github.com/akvo/akvo-flow/issues/1393

**Comment by kymni** [comment]
Should be fixed by #2556

**Comment by janagombitova** [comment]
@kymni in that case I will add the issue to the milestone to make sure to test it and confirm all works well

**Comment by janagombitova** [comment]
@stellanl and @kymni We do not get bad order values anymore. So this part of the issue is resolved. 

I cannot test on UAT1 as I cannot find a survey with such bad values. I could test on UAT2, as there we have a survey matching the criteria. But then the expectation should be that the publishing skips the bad ordered questions, right? 

The question is, what about surveys with bad order values? Is there anything automagical we can do for them? Should we?

**Comment by stellanl** [comment]
A datascript could be written (in about an hour) to repair the order fields. Or we might make it a regular cleanup operation. The chances of messed-up order fields have been reduced, probably significantly, but are not zero.

**Comment by stellanl** [comment]
I can also mess up the order in a survey on uat1 from the datastore manager.

**Comment by janagombitova** [comment]
@stellanl I think it is a good idea to clean up all survey forms on all instances to ensure that the order is correct. Then publishing won't fail and the fix from 1.9.30 will prevent most cases to happen again. 

Scheduling the clean up regularly sounds also reasonable. How often would you propose?

**Comment by stellanl** [comment]
Actually, the recent form-export flap revealed that some (non-time-critical backend) calls to list questions in a group already does an order fixup. I propose to inventory this and any similar things for question groups.

**Comment by muloem** [comment]
> I see some options:
>  * To make for more correct surveys, the publishing process should fail, and then notify the user (as it does if S3 is unavailable). This is means they will have to ask support to fix it,  and/or we could run structure checks automatically to alert us to these problems.

I am definitely in favour of some kind of validation of the survey structure before publishing to prevent the problems from going further down the line to the app for instance.  In fact I believe there is an issue for it #1324 that we had proposed to work on this kind of validation.
 
>  * To make a more fail-tolerant process, the publishing could go ahead and send everything with the bad order values to the app. This will look a bit bad, and may confuse data collectors.

If we allow bad data to go this far cleaning up will be that much harder so I prefer avoiding this option.

**Comment by janagombitova** [comment]
So I see two problems here: 

1. What should we do with forms created before the last release that have broken order? - could be handled in this issue
2. How to strengthen validation when editing a survey to make sure that only a good survey is publishable? - could be handled in issue #1324

**Comment by kymni** [comment]
@janagombitova, @stellanl, @muloem given that we handled the issue causing the bad ordering in #2556, should we close this or keep it open to handle potential cases of old questions and questions groups with bad orders?

**Comment by stellanl** [comment]
While #2556 lessened the risk of bad ordering, it did not _completely_ eliminate it. The creation of a new question and the reordering of the others are still 2 separate http calls, and one of them can fail while the other succeeds.

**Comment by muloem** [comment]
@kymni I think we should keep this open for now.  There is lots of other validation that needs to be handled.
