### ISSUE TITLE
SurveyedLocale locale retrieval skips items

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#2252]
The recently changed logic is error prone and turns out skips items, hence the support request.

**Comment by janagombitova** [comment]
Here is a list of a few surveys I tried to sync in
- submissions in export: 2646 and synced to device: 2646 and after reopening the app: 2646
- submissions in export: 4 and synced to device: 4 and after reopening the app: 4
- submissions in export: 133 and synced to device: 133 and after reopening the app: 133

That is as far as I can test on UAT1. So from my perspective all works as it should. We will fully confirm with the partner once the release it out

**Comment by janagombitova** [comment]
Just tested the fixes on the akvoflow-89 instance where the problems were first reported and all seems to work well now. Points sync in correctly and remain on the device. Well done everyone
