### ISSUE TITLE
Remove link to old support documentation in form preview

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2258]
### Context
If the user has a cascade question in her form and she previews the form, the cascade question we show the different levels as input fields and below them we include a text explaining how the cascades appear on devices, along with a link to the documentation.

### Problem or opportunity
The text is lengthy, and to necessary and neither is the link.  We can remove both from the preview window.

**Comment by bogere** [comment]
### test 
*  create cascade type questions in the survey form
* then click on the form preview and look at it
* the link to the documentation in the form preview is no longer there

**Comment by janagombitova** [comment]
All removed and the UI is a bit more simpler and cleaner. Well done. Ready to go.
