### ISSUE TITLE
Use 'form' consistently in the code 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2260]
# Context
We spoke today about the inconsistencies on how we name things in Flow and the different ways how we refer to forms and surveys in the UI and in the code. In the code we do not call 'form' what refers to a form and this inconsistency is across different parts of Flow code (from UI to the deep dark levels of the code base). We do not use the same language in the code and in the UI. 

# Problem
The inconsistency not only makes it confusing when we talk about fixes and improvements but also makes it hard to change things in the code. Talking in "two different languages" is in general not a useful practice. 

# Next steps 
With this issue we want to note down where 'form' is not referred to as 'form' in the code. 

We realise that this is a large endeavour but with this issue we want to start at brining more consistency into Flow.

**Comment by stellanl** [comment]
Might as well start with the two most painful places; the GAE datastore and the API.
In the datastore, entities are stored with a "kind" which is the same as the name of the class you are storing. You cannot rename the stored data all at once like you would rename a table in SQL.
The migration would require several steps.
 * Copy the Survey class to a new Form class. Also copy the Survey APIs to new Form APIs.
 * Run a script to copy all Survey entities to Forms.
 * Rename all references to Survey class to instead use the Form class. 
Repeat similarly for surveyInstance -> formInstance and surveyAssignment -> formAssignment.
Backend ugliness gone? No. Many other entities still have "somethingSurveySomething" fields that now point to a form or formInstance. How many? Here is a partial list:
 * SurveyGroup.newLocaleSurveyId (Which form is the registration form)
 * QuestionGroup.surveyId
 * Question.surveyId
 * QuestionAnswerStore.surveyId
 * QuestionAnswerStore.surveyInstanceId
 * SurveyedLocale.surveyInstanceContrib

**Comment by stellanl** [comment]
The other place we could start is in the API and UI. The UI is the place with the most confusion.
We could 
 * Rename the /surveys REST endpoint to /forms. 5 minutes.
 * Rename the legacy stuff in the UI to Form. More work but probably less than a day.
 * Change the other APIs so they rename all surveyId fields into formId. A few hours of work.
