### ISSUE TITLE
Cannot delete data point via Monitoring tab 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2261]
# Context 
Users sometimes need to delete submissions made. Usually they do this via the Inspect data tab. But for monitoring surveys users preview the data in the Monitoring tab and here we also provide the option to delete the entire data point and all the submissions made to it. Or at least it appears so. 

# Problem 
When the user hits Delete, nothing happens. It is confusing as you expect you can delete everything submitted to the data point and the full data point itself, but actually nothing happens

![1](https://user-images.githubusercontent.com/12456965/30693213-d927a68e-9ece-11e7-9600-9246a0bc6c8d.gif)

This is the error I get in the console when trying to delete in the Monitoring tab
<img width="1212" alt="screen shot 2017-09-21 at 13 15 17" src="https://user-images.githubusercontent.com/12456965/30693250-fa49063c-9ece-11e7-9007-43a271a6c632.png"> 

# Next step 
We need to answer the question: Do we want to allow users to be able to delete a full data point, with all the forms submitted to it in one go? 
- if yes, we need to make it work
- if not, we should remove the delete option from the Monitoring tab and make it easier to search for a data point in the Inspect data tab (adding a filter on data point ID and data point name) so users can easily find for example all monitoring form submissions for a data point and remove them only in the Inspect data tab

**Comment by janagombitova** [comment]
As we are still revising the rules around deletion and the role of viewing data in the Monitoring tab, I propose to remove the **delete** action for now. This will avoid the confusion that users have currently as they think they can delete a full data point with all its submissions, but actually that is not possible at the moment. 

@muloem what do you think?

**Comment by Maseline** [comment]
Test plan
Navigate to the monitoring tab
Note that the delete option had been removed under the action header when data points are loaded.Only the view details option is left.

**Comment by janagombitova** [comment]
I see on the current UAT1 build (v1.9.27-45-gb8dedb4) that this issue is also resolved and merged into the build. So I confirm it works as should and am adding it to ready for release. 

If there is still work needed and this is not meant to go out yet, please comment and change label.
