### ISSUE TITLE
Spaces after email prevent user from accessing Flow 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2265]
# Context 
To create a new user in Flow you need to add the user's name and email. The email has to be a Google connected email address. Existing users with user creation permission create new users. They either know the new users email by heart and type it in. However, in most cases they do not know the email and end up copying it from another source and pasting it in. 

# Problem or opportunity 
When adding the email for a user, it **cannot** contain spaces - spaces before the email or after - otherwise the new user is not able to log into Flow as the spaces are considered characters of the email address. 

Spaces usually occur after the email, when the admin user copies over the email into Flow. Spaces before the email do not occur so often as you can visually see that they are there. Spaces after the email are impossible for the user to see with the naked eye.  

# Next step 

Spaces should not be causing issues for user to log in.

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/akvoflow-you-got-a-feedback-on-an-article-from-billtwyman49-at-gmail-dot-com

**Comment by Kiarii** [comment]
status for this from design side: a go.. I am assuming this is a technical issue where the front-end may try to see how to drop spaces in a provided email or so..

**Comment by Reza-Rajabi** [comment]
I tried to log in with adding spaces before/after the email, and I didn't see any problem. Also in here:
[https://github.com/akvo/akvo-flow/blob/ae2613cfde5704a32819e01cda9edcd56a54236a/Dashboard/app/js/lib/views/users/user-view.js#L33](url)
the given email address is trimed:
```javaScript
      emailAddress: Ember.$.trim(FLOW.editControl.get('newEmailAddress').toLowerCase()),
```
I am wondering if that was the problem this issue address?

**Comment by janagombitova** [comment]
@Reza-Rajabi I just tested it out on one of our test production instances and the issue still remains. Once I add a space after the user email Flow does not recognize this user and claims she/he has no access to the instance

**Comment by muloem** [comment]
@Reza-Rajabi the user addition is now done here https://github.com/akvo/akvo-flow/blob/ae2613cfde5704a32819e01cda9edcd56a54236a/Dashboard/app/cljs/src/org/akvo/flow/dashboard/users/user_details.cljs

Thats where the space should be trimmed
