### ISSUE TITLE
Add level button in cascade UI has different design 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2268]
Since the design improvements introduced in this issue: https://github.com/akvo/akvo-flow/issues/2033 some already existing cascade UI issues resurfaced. Here is one of them: 

We have multiple add buttons in the cascade UI: 
- add new cascade 
- add level
- add (for options in a level) 

Two out of the three have a design on a button and one - add level - is as a clickable link. This particular one is not standing out in the UI as the other two. Can we bring consistency to the add buttons in this UI? 

<img width="1262" alt="screen shot 2017-09-26 at 12 16 56" src="https://user-images.githubusercontent.com/12456965/30859171-d54a39e4-a2c2-11e7-8943-d1d556e8aa4e.png">

**Comment by Maseline** [comment]
![issue2268](https://user-images.githubusercontent.com/3306929/33650845-b59e616c-da74-11e7-8b7a-87836358df68.png)
@janagombitova ,something like this?

**Comment by janagombitova** [comment]
Yes, that is much better 👍

**Comment by Maseline** [comment]
@janagombitova @muloem could push this if it is satisfactory

**Comment by janagombitova** [comment]
The Add level button looks good from my point of view. If everything else remained the same, also in different parts of Flow, then you should be ready to go

**Comment by Maseline** [comment]
Test plan
Navigate to Cascade resources under the Data tab.
Select an existing cascade
Notice the Add level design has changed to a button style design.

**Comment by janagombitova** [comment]
👍  button looks good a is now better visible as well as aligned with other "add" buttons
