### ISSUE TITLE
use "extend" intead of "create" for the maps ArrayController

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#2275]
The current implementation creates a new instance of the ArrayController class. It should however extend ArrayController so it inherits the parent class implementation while allowing to override the methods

Issue tied to [#2144]

**Comment by janagombitova** [comment]
@kymni anything in particular to test?

**Comment by kymni** [comment]
@janagombitova not really because this was more of a code change that affects nothing functionally

**Comment by janagombitova** [comment]
Ok. Maps work well 👍  We are ready to roll.
