### ISSUE TITLE
Layout off for Manual survey transfer 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2276]
I just noticed that in the Manual survey transfer tab the layout is not 100% and I think it is connected to the fixes here: https://github.com/akvo/akvo-flow/issues/1992

<img width="1264" alt="screen shot 2017-10-10 at 16 52 01" src="https://user-images.githubusercontent.com/12456965/31393267-a52f39ac-addb-11e7-932a-2403fdb0e738.png">

The Preview survey section is not centred 

@loicsans can you please take a look? Thanks

**Comment by Maseline** [comment]
@janagombitova , so in the image shared i see that sort of faded dotted line/division in the sections, is that where the preview text should be placed, like right after that dotted line

**Comment by janagombitova** [comment]
Hi @Maseline yes. It should look similar to the Assignments page (even though there we also have some alignment issues) 

<img width="1252" alt="screen shot 2018-03-09 at 08 54 22" src="https://user-images.githubusercontent.com/12456965/37196550-8be2bb7e-2377-11e8-860f-c2a301c6edb1.png">

**Comment by Maseline** [comment]
Test plan
Navigate to the Manual Survey Transfer page under the Devices tab
The Preview Survey Selection section should appear in line with and just to the right of the Select survey section

**Comment by janagombitova** [comment]
@Maseline I have just been going through the issue you fixed and need to get in and this one stroke me, as I do not see the issue anymore. Can you cross check? Did the fix get in?

**Comment by janagombitova** [comment]
Well that slipped through the cracks :) Ok. then the issue is resovled
