### ISSUE TITLE
Split RQG answers into separate sheets

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2278]

**Comment by janagombitova** [comment]
# Context 

Based on the research and discussions noted here: https://github.com/akvo/akvo-product-design/issues/227 we have agreed to change how RQGs are exported currently - in separate rows per repetition and all in one sheet. 

We have tested a prototype of the new export form structure and validated that by changing the structure of raw data exports, but not the ones under work name "transformed data" (current exports when user clicks on Advance settings) we will give the users two useful formats on how RQGs are exported. This issue deals with changes for raw data exports and splitting to sheets. 

# Opportunity 

When the user downloads a raw data export where group 2 and 4 are repeatable (out of 6 question groups), she will get: 
- 1st sheet with all the meta data columns, **no** Repeat no column, and all the questions and answers for groups 1, 3, 5, 6
- 1st sheet will follow thus the rule - one submission = one row
- 2nd sheet with all the meta data columns, Repeat no column, and questions and answers to group 2
- 3rd sheet with all the meta data columns, Repeat no column, and questions and answers to group 4

When she downloads a raw data export where out of the 3 existing question groups none are repeatable, she will get: 
- one sheet with all the meta data columns, **no** Repeat no column, and all the questions and answers for all the groups 

The Raw data exports are used for data cleaning, so the question IDs, hash and meta data still remain as part of the exports. 

# To further clarify: 

**How should be name the sheets** 
Stellan proposed for the sheets with the repeated groups - `Group #`. I would suggest Group # - Name... (till it gets cut off based on the character count) 

But how shall we call the 1st sheet with all the other non repeat group answers? 

** How will this work for importing new data using data cleaning?** 
If the user wants to import new data to Flow using data cleaning, usually you export the empty raw data export, fill in the data without the different IDs (identifier, instance ID, etc) and import the file in. For RQGs the user will simply add the correct number in the Repeat no column and the answers. How will this work if we have separate sheets? How will the user be able to link the answers to the RQG sheet to the other data as she does not have the instance numbers yet? 

@stellanl @muloem and @Kiarii what are your thoughts?

**Comment by janagombitova** [comment]
Note to myself for testing: Cross check all works as expected also with the data approval column.

**Comment by janagombitova** [comment]
Tried exporting: 
- form data with no repeated groups 
- form data with multiple repeated groups 
- form data with only repeated groups 
- form data with approval column and repeated groups 
- form data with approval column and no repeated groups 
- form data with no data 
- form data with a lot of data 

And all worked fine and as expected. Found one small issue, but that can be tackled next time: https://github.com/akvo/akvo-flow/issues/2343

I will test data cleaning and importing as part of the other issue, as well as the other export types.
