### ISSUE TITLE
Implement new UI for exports 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2282]
# Context

Based on the research and discussions noted here: akvo/akvo-product-design#227 and here: akvo/akvo-product-design#273 we have agreed to change the UI for the entire Reports - Export reports tab. 

The UI ideas have been tested with 5 partners and validated. Here are the mockups used in the test:  https://invis.io/2XDVONWNV#/257373554_1-a_Raw_ES

<img width="1267" alt="screen shot 2017-10-19 at 16 11 19" src="https://user-images.githubusercontent.com/12456965/31775186-2d14b5c8-b4e8-11e7-87bb-efec8e4492b8.png">

# To be defined 
- names of the different report types 
- more in detail designs for the page
- will we add icons to make the report types more recognisable? 
- copy for once the user hits the download button

**Comment by muloem** [comment]
In addition to removing the language selection options, we can address any backend code that handles language translations in this issue.

**Comment by muloem** [comment]
@loicsans FYI there are some placeholders defined in #2300 that can be reused here in order to unify the texts.

**Comment by janagombitova** [comment]
# First round of testing 

Tested the UI without the link to the exports service in Safari, Firefox and Chrome. 

<img width="1236" alt="screen shot 2017-11-22 at 08 50 35" src="https://user-images.githubusercontent.com/12456965/33115739-6d653b36-cf62-11e7-9518-ce906fb102a4.png">

<img width="1259" alt="screen shot 2017-11-22 at 08 58 27" src="https://user-images.githubusercontent.com/12456965/33115994-55782730-cf63-11e7-9959-50e2a064afe6.png">


* [ ] Flow in the descriptions needs to start with capital F
* [ ] subtitle for Comprehensive report was not provided in the designs we tested and I think we do not need to have it there - the not_importable_back subtitle 
* [ ] Description for Data cleaning exports change 'level' to 'levels'
* [ ] Can you put margins on the side of the page? Now the different export options go to full page width and it looks off. 
* [ ] Icons seem small in comparison to the text
* [ ] Collection period filters looks odd 
* [ ] is it possible to remove the need to scroll on the page? 
* [ ] do we need to large Select survey and Select export headers ? We removed the Select survey header from the other tabs, not sure if the Select export header also brings value. What do you think?

**Comment by janagombitova** [comment]
# Second round of testing 

* [ ] when selecting the collection date for Data analysis export I do not get the calendar selector as in Data cleaning exports 
* [ ] For the description in the Comprehensive report I do not like the (Min, Max, Frequency, ...) part especially due to the "...". Can you change it to "(min, max, frequency and more)" and after "Contains raw data" add a full stop at the end of the sentence.
* [ ] Collection date in Firefox is not visible properly (see screen shot) 

<img width="461" alt="screen shot 2017-11-22 at 13 38 26" src="https://user-images.githubusercontent.com/12456965/33127847-87f7c0d6-cf8a-11e7-9d65-518703439abe.png">

**Comment by janagombitova** [comment]
👍  looking good!

**Comment by janagombitova** [comment]
Ready for release
