### ISSUE TITLE
Remove translations in Reports 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2286]
# Context 
With the new UI changes coming up and with the no value provided in the Laguage dropdown in the reports tab we agreed to remove this functionality fully. 

If the user selected a language and exported data the meta data field would be translated but that is all. We can keep the meta data fields in English for all our users and not confuse them with another extra dropdown. 

![screen shot 2017-10-20 at 16 30 21](https://user-images.githubusercontent.com/12456965/31825942-fe9d4c56-b5b3-11e7-9329-8ccd967f4dd4.png)

# Change 
Remove language dropdown from UI and all related code to the translations of all exports.

**Comment by muloem** [comment]
For a first step, I think its ok to remove the UI element.  As a follow up we can handle the code cleanup in the different backend, view components

**Comment by janagombitova** [comment]
@muloem will the UI component not be removed as part of the overall UI Exports tab change? https://github.com/akvo/akvo-flow/issues/2282

**Comment by bogere** [comment]
##  Test plan
*  click on export report widget 
* choose the folder  that you want to generate a report
* choose the survey under the folder that you want to generate a report
* option for selecting the language no longer exists

**Comment by janagombitova** [comment]
👍  Wonderful!
