### ISSUE TITLE
Add updated translations of online workspace

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2287]
On Transifex the Vietnamese and French translations are now up to date and ready to be added.

**Comment by janagombitova** [comment]
Changing this issue as we need to update all translations again. @valllllll2000 would you have time to update the strings for French, Spanish and Portuguese? I will ask our colleagues for Indonesian and partners for Vietnamese.

**Comment by janagombitova** [comment]
Translate missing language strings in Flow and update translations: 
* [ ] French 
* [ ] Spanish
* [ ] Portuguese 
* [ ] Vietnamese 
* [ ] Indonesian 

@valllllll2000 can you translate French, Spanish and Portuguese strings in transifex and I will take care of the rest? Thanks

**Comment by valllllll2000** [comment]
I have found an error in the strings:
Import\ will\ override\ the\ existing\ dat**a.T**he\ file\ must\ be\ in\ .xlsx\ or\ .xls\ format.

**Comment by janagombitova** [comment]
As we have a release next week and I have not received a reply from the translators yet, let's go ahead and update what is 100% translated and leave the Vietnamese and Indonesian to another release.

**Comment by janagombitova** [comment]
All looks translated. The next round and currently missing strings for some other translations will be handled in another round in a different issue 👍 this can go
