### ISSUE TITLE
Have "other, please specify" always in a separate column 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2290]
# Context 

Option questions are one of the most popular question types used. The user specifies a list of option the respondent can select from. However, in many cases when creating the form you cannot think of all options possible thus you ca select in Flow to add "other, please specify". In the app is the responded goes for "other, please specify", she write down her own answer. 

In the data exports, data cleaning exports, the "other, please specify" is treated as the form defined options and added to the answer cell. 

# Idea 
The idea is to create a separate column for "other, please specify" if selected for an option question for all export types. 

# Why 
It is confusing for the Salim or Petra analysing the data, as s/he does not know if the option selected was defined in the survey form or written by the user when answering the question. "Other, please specify" is sometimes in data analysis treated as one variable, regardless of what the users answer. Currently it is complicated to divide the give form options from the user specified ones.

**Comment by janagombitova** [comment]
This change should apply on both export types, Data cleaning and Data analysis.

**Comment by stellanl** [comment]
I'll assume also for comprehensive reports.

**Comment by stellanl** [comment]
In the same way as #2315, the current "other" columns have a non-unique header: "--OTHER--". I propose we add that to the id or variable name to make it unique.

**Comment by muloem** [comment]
> In the same way as #2315, the current "other" columns have a non-unique header: "--OTHER--". I propose we add that to the id or variable name to make it unique.

@stellanl this is for the data analysis report, right?

**Comment by stellanl** [comment]
Since I have to change the import logic anyway, I was going to do it for both.

**Comment by stellanl** [comment]
@janagombitova With ID I meant the numerical question id, which is put in the data cleaning headers so that the can be linked to the orrect quesiton on import.

**Comment by stellanl** [comment]
One question: the usual for an option is to be put into a spreadsheet cell as code:text (if there is a code). Modern answers seem to set code OTHER for all such answers. It will look a bit repetitive with a lot of OTHER:Foo and OTHER:Bar in the "other" column. I suggest we strip those, and add them when importing.

**Comment by stellanl** [comment]
Test plan:

 * Order reports in all 3 formats. They should all have a separate "other" column.
 * Make changes to the "other" column in the data cleaning report and import it. Data should change.
 * Order an analysis report on a form with two option questions that both allow other and with no variable names set; the "other" column headers should be unique.

**Comment by janagombitova** [comment]
👍 works like a charm. Well done.
