### ISSUE TITLE
16-digit numbers get rounded in report cells

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2291]
The changes in #267 did not fully take very large numbers into account.
Users have been collecting 16-digit ID numbers that then misbehave in the exported Excel sheets. They expect them to not be rounded or shown in "scientific" format.
Luckily, in most of Flow, a NUMBER answer is just like a TEXT answer but with different value checking. So no data has been lost.
The answer is not quite clear-cut. We can put any large number in text cells during the export, but users that collect large numbers where not every digit is significant presumably still want them in number cells.

We *could* add a comment to cells that were changed to string to make it more obvious that they need to be changed back if the user needs to do math on them.

https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-80157-from-aulia-at-akvo-dot-org

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-80157-from-aulia-at-akvo-dot-org

**Comment by janagombitova** [comment]
@stellanl I checked the file you shared this morning and it is a bit odd when I open it. I think there should be a comment there, but I see just a little line. 

<img width="1280" alt="screen shot 2017-11-14 at 12 08 30" src="https://user-images.githubusercontent.com/12456965/32776976-b9ebac80-c934-11e7-8438-f23653a11408.png">

**Comment by janagombitova** [comment]
Why did you close the issue @stellanl ?

**Comment by stellanl** [comment]
Oops, I may have gotten a little too enthusiastic moving it around in waffle...

**Comment by janagombitova** [comment]
<img width="763" alt="screen shot 2017-12-12 at 14 51 49" src="https://user-images.githubusercontent.com/12456965/33892922-60325914-df5a-11e7-94f1-e65bade020d9.png">

Long numbers show fully. All good
