### ISSUE TITLE
Flow to send data points to new Unilog

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-flow#2292]
For the new Unilog, we have chosen Kafka as our implementation. 

Kafka comes with a [REST proxy](https://docs.confluent.io/current/kafka-rest/docs/intro.html) that Flow can use to push messages into Unilog.

This work is to make sure that Flow can push messages in [Avro format](http://avro.apache.org) to that REST proxy and that those messages can be consumed by the Flow-Maps consumer.

[Documentation regarding Rest Proxy and Avro](https://docs.confluent.io/current/kafka-rest/docs/intro.html#produce-and-consume-avro-messages)

REST Proxy in TEST is running at http://kafka-rest-proxy.akvotest.org. 

The expected Kafka topic name should contain the word "datapoint", like "flow-maps.datapoint"

There is already a Flow-Maps consumer running in the TEST environment, which expects Avro messages with the following schema:

```
{
  "namespace": "org.akvo.flow",
  "type": "record",
  "name": "DataPoint",
  "fields": [
    {
      "name": "identifier",
      "type": "string"
    },
    {
      "name": "survey_id",
      "type": [
        "null",
        "long"
      ]
    },
    {
      "name": "longitude",
      "type": [
        "null",
        "double"
      ]
    },
    {
      "name": "latitude",
      "type": [
        "null",
        "double"
      ]
    },
    {
      "name": "created_date_time",
      "type": "long"
    },
    {
      "name": "last_update_date_time",
      "type": "long"
    }
  ]
}
```

Note that this schema is in no way the final or even correct schema for Data Points. 

In scope for this task:
1. Push new Data Points to Unilog
1. Feature flag per tenant to enable/disable the push. Disabled by default.
1. Avro format

Outside the scope of this task:
1. Create a final version of the DataPoint schema.
1. Validate the backwards/forwards compatibility of the schemas at build time.
1. Multi-tenant correctness
1. Import of existing data in GAE
1. Push of FormInstances or any other Flow entity
1. Security

**Comment by muloem** [comment]
@dlebrero So far this schema definition is for datapoint creation.  Do we also want to have a separate one for datapoint deletion?

**Comment by dlebrero** [comment]
Deletes in Kafka are usually represented by sending a null payload in the message. 

We should follow this convention unless we want to record additional data in the delete message, like who/how/when, but we could also use message headers for those and keep the convention of sending a null payload.

Also:

1. Kafka messages have a timestamp of creation, which we could use as the "when" metadata
2. Kafka-avro just allows one schema per topic, so if we decide to have full "delete" messages, both the create/update/delete should be represented as one schema.

**Comment by dlebrero** [comment]
Not going to happen anytime soon. Closing.
