### ISSUE TITLE
Flow to use new Windshaft based Maps

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-flow#2293]
This work is to do an initial integration with the new Flow-Maps, based in Windshaft.

The new Flow-Maps Windshaft is available in the test environment with two urls:
1. https://flowmaps.akvotest.org/create-map: to create a new map and obtain a new map token (layerGroupId)
1. https://flowmaps.akvotest.org/layergroup/: to obtain the tiles for the map.

To understand better the expected interface, there is an example at https://github.com/akvo/akvo-flow-maps/blob/master/viewer/index.html that works against those endpoints.

In scope: 
1. Show a map where the data comes from Windshaft
1. Feature flag to enable the new maps in a tenant

Outside the scope:
1. Any filter
1. Flow Backend to do authorisation

**Comment by dlebrero** [comment]
We implemented last week the authz/authn for the create-map endpoint.

The method used is [Client Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.4)

See http://www.keycloak.org/docs/latest/server_admin/index.html#_service_accounts for the keycloak documentation.

We have an integration test that demonstrates the feature at https://github.com/akvo/akvo-flow-maps/blob/master/test/akvo/flow/maps/end_to_end_test.clj#L116. Configuration is at https://github.com/akvo/akvo-flow-maps/blob/master/test/akvo/flow/maps/k8s_end_to_end_test.clj#L40

**Comment by muloem** [comment]
We will keep using our current maps till further notice. See #2650 and related issues.
