### ISSUE TITLE
Maps not loading tiles sometimes 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2294]
<img width="927" alt="screen shot 2017-10-31 at 15 00 00" src="https://user-images.githubusercontent.com/12456965/32232870-53cf9c94-be59-11e7-93e5-c8bbf36a9dfc.png">

<img width="923" alt="screen shot 2017-10-31 at 15 00 29" src="https://user-images.githubusercontent.com/12456965/32232945-7f7d7ae6-be59-11e7-8b4e-a7fca30b4287.png">

Sometimes the browser is not able to download the map tiles and we get this error see above. We need to make sure the map is always properly loaded. After fully reloading the instance the issue persisted. Once I opened it up in an incognito browser the tiles loaded ok. 

This is for the Carto maps

**Comment by janagombitova** [comment]
This morning @kymni pointed out that the maps not showing may be connected to having an add blocker on the browser. 

<img width="1269" alt="screen shot 2017-11-20 at 10 09 16" src="https://user-images.githubusercontent.com/12456965/33010531-1a0c3828-cddb-11e7-8a16-bff0aa28da0b.png">

**Comment by janagombitova** [comment]
@Kiarii We need your expertise. 

**Problem:** 
If a user has a ad blocker running on their browser, sometimes the map tiles will not show on Flow. Either they need to open Flow in an incognito window or turn off the plug in. The user assumes the maps are not working, but it is actually because of a plug in they have installed. 

**How might we...**
How might we let the user know that the maps are working, but the privacy plug in they have installed is preventing the map to show properly?

**Comment by Kiarii** [comment]
a question: is it that the maps are rendered with a piece of an ad code or with a code that is mistakenly recognized as an ad?

Typically on the interface section, a request to disable adblocker to view content is shown (where an object is to be rendered). This 'feature' however is used as a counter-adblocking tactic by sites to deny access to content if users block ads. Consequently in our case it might imply to the user that we are running ads on flow, and perhaps we dont want to make that impression...

**Comment by janagombitova** [comment]
No we definitely do not want to make that impression as we are not running ads on Flow. 

@kymni mentioned the maps are proprietary, so it is possible that they might be running trackers on their map tiles, but I do not think ads. Charles, can you take Kiarii's question?  

We could start simply by explaining in an FAQ in support.

**Comment by kymni** [comment]
The idea behind using Here maps was that they provided regularly updated map tiles as well as high resolution satellite imagery. Here maps are however a proprietary map tiles provider and could therefore be tracking their tiles' usage hence the flagging down by some privacy enhancement plugins such as ad blockers. If we were to prompt the user to disable their ad blocker to experience the full features of the dashboard then it could create the impression that we're running ads on Flow which is not the case.
In current implementation of Carto maps, we've set the default base layer provider to Here maps with Mapbox tiles provided as an optional "Terrain" layer. Safest option (also easiest fix) would therefore be to switch the layers setting the terrain layer as the default layer and have the Here maps layer as the option which would include the warning about map tiles sometimes not loading when the user selects it. 
We could also altogether do away with Here maps

**Comment by muloem** [comment]
If the Here maps are causing this issue, I would be in favour of doing away with them altogether.  Do we have an idea how widespread this problem is?  If its urgent a temporary fix would be what Charles mentions. If its not a huge problem right now, then we are going to switch to windshaft maps soon and that will solve this.

**Comment by janagombitova** [comment]
So far we have not received and support requests around this issue and we know what it causing it, so it is not urgent.

**Comment by kymni** [comment]
> Do we have an idea how widespread this problem is?

Not sure. @janagombitova have you encountered this issue on instances using Mapbox and Google maps tiles? Because these providers should also be tracking their respective tiles' usage via the browser keys they've provided

**Comment by janagombitova** [comment]
Issue no longer exists, everything loads for me even with my add blockers turned on 👍
