### ISSUE TITLE
Importing new data 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2295]
# Update

This issue allows users to import in new data using the "old" Raw data report files, not the new ones yet. 

Importing in new data using the Data cleaning export format (as described below) will be handled in the next release in this issue: #2368

# Context

Users capture data with Flow. But sometimes they already have data stored somewhere else and they either want to have it stored in Flow with their other data, or they want to use the data for further monitoring in Flow. Simply speaking they want to have their data in Flow. 

Currently what is possible is using data cleaning import to import new data into Flow. How: 
1. User creates a survey form with questions matching their data
2. Exports the Raw data report 
3. Fill in her new data into the sheet
4. Does not fill in the Identifier, Instance, Device
5. Imports the file using Data cleaning to the survey form 

There is one limitation: you cannot import new data into a monitoring form.   

With the changes to the Data cleaning export (previously known as raw data report), we need to consider how to support importing new data into Flow as this is a frequently used and quite valuable feature in Flow. 

# Opportunity

With the new export structure using data cleaning for import is ok, if there are no repeated question groups in the survey form. However, if there are any, we need to figure out how to make this import possible as the user currently has no way to link that data in the separate sheets (the Flow identifier is not generated yet as they data is to be imported as new data).

Do we want to have this possibility hidden under that name of data cleaning? 
How can we make importing new data to Flow possible?  

@stellanl @muloem @Kiarii let's see what we can think of

**Comment by stellanl** [comment]
My idea for handling split sheets is as follows:
The user will have to put a special value like new-1, new-2 in the "Identifier" column on both the base and RQG sheet, and when they have been collected into the same instance this value is blanked out.
When uploaded with a blank identifier, they will get a new identifier assigned.

**Comment by janagombitova** [comment]
Hey @stellanl so I tried importing in new data after your last fixes and here is what I found: 

**Importing in new data without RQGa** - works fine and as expected 
**Importing in new data with RQGs** 
- I imported one submission with 10 repetitions
- The import worked 
- When I exported the data out of Flow (after the import) using the Data cleaning export, the imported repeated group showed fine, but in the raw data my submission is duplicated (highlighted yellow in the Result sheet) 

[DATA_CLEANING-208769115-RESULT.xlsx](https://github.com/akvo/akvo-flow/files/1508929/DATA_CLEANING-208769115-RESULT.xlsx)
[DATA_CLEANING-208769115-Import MEMEME-new2.xlsx](https://github.com/akvo/akvo-flow/files/1508930/DATA_CLEANING-208769115-Import.MEMEME-new2.xlsx)

**Comment by janagombitova** [comment]
Just to keep all communication in one place: 
- Importing in new data now works fine 
   - users needs to use the "old" export structure (Raw data reports) 
   - works fine for importing in submissions with no RQGs 
   - works fine for importing in submissions with RQGs 
- Data cleaning - does not work yet 
   - data cleaning with the new export structure (Data cleaning exports) does not import in 
   - The message I received after trying to import in a cleaned file: Invalid RAW DATA file: import me.xlsx - Errors: Repeat column must contain a numeric value in row: 21

**Comment by janagombitova** [comment]
All works as expected 👍 YaaY! What a ride and a thrill!

**Comment by janagombitova** [comment]
Just as a note for the Release notes > this issue allows users to import in new data using the "old" Raw data report files, not the new ones yet. Importing in new data using the Data cleaning export format will be handled in the next release in this issue: https://github.com/akvo/akvo-flow/issues/2368
