### ISSUE TITLE
Deleting submission dialogue

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2297]
# Context

In line with trying to simplify the interactions users have when working on the Flow online workspace we are simplifying modal dialogues to ensure the important message is clearly communicated and the actions are understandable to the users. 

Current dialogue when the users hits 'delete' when previewing form submissions in Inspect data tab: 
- Title: Delete this record? 
- Text: Are you sure you want to delete this data record? This cannot be undone. 
- Action buttons: OK and Cancel 

<img width="766" alt="screen shot 2017-11-06 at 11 58 27" src="https://user-images.githubusercontent.com/12456965/32438194-e280ceb0-c2e9-11e7-8f4a-0b9ae0206ca3.png">

# Change 
There are a few principles I think we should follow: 
- use the language are users use when talking about and working with Flow 
- name elements in the same way across the online workspace and app 
- limit text as much as possible 
- use the same structure of messages for the same actions

For deleting we are moving towards asking 'Delete + element' combined with Delete and Cancel as action buttons. As discussing with @Kiarii he pointed out that as this is a serious action that is not irreversible, we need to make sure the user understands that the data will be fully gone. 

**Here is the proposal for change:** 
- title: Permanently delete form submission? --> as we do not use the word record across Flow 
- buttons: Delete, Cancel
- no text

**Comment by muloem** [comment]
I believe that with the changes in #2119, @Maseline has converted all the dialog boxes where a delete confirmation is requested.

However, the other elements like the title and the no text can still be handled.

**Comment by bogere** [comment]
It seems the <OK> and <cancel> in the confirm dialog for deleting form submission is hard code in the application.handlebars , so changing the button text will affect all the confirm dialogs across the application. same issue as Mary's issue for simplifying dialog for deleting assignments

**Comment by bogere** [comment]
### test plan
* click on the inspect data tab under data menu 
*choose the survey folder and surveys and then click <Find> button to retrieve records
* click on the action on the table for specific record
* dialog for deleting the submission form has changed header text and no background

**Comment by janagombitova** [comment]
<img width="794" alt="screen shot 2017-11-14 at 11 55 09" src="https://user-images.githubusercontent.com/12456965/32776393-adf9b5fe-c932-11e7-803c-8dba25f50ae0.png">

Button still shows "Ok" instead of "Delete".  Can you please make the needed adjustments? @bogere and @muloem

**Comment by muloem** [comment]
@janagombitova note the comments from @bogere that the changes to the button would result in changing other dialogue boxes where the `OK` is appropriate. Just like in #2075, we need to see a way to sort this out without affecting those dialogues. The header text should have changed though.

**Comment by janagombitova** [comment]
So then we have the title changed but not the buttons. Then I suggest we take the merged code to the release, but leave the issue open as it is not fully completed yet, if you agree @muloem? And is @loicsans the person to ask to style up the pop up message, as we have a lot of white space there now due to the removed text?

**Comment by janagombitova** [comment]
Code can go into the release, issue remains open to tackle the issues around: 
* [ ] style of the message 
* [ ] action buttons

**Comment by janagombitova** [comment]
Actually I decide that we close this issue and create a new one to have our work better organised. Here is the issue: https://github.com/akvo/akvo-flow/issues/2352 This one can be closed with the release
