### ISSUE TITLE
Remove phone number from Device list 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2299]
# Context 
We need to be smart of what private data we saved and if we really need it. When it comes to device identification we use multiple IDs (IMEA; Android ID, phone number) to identify a device. Unifying and simplifying the device identification is a problem we will **not** solve with this issue but will deal with in a larger streak of changes - https://github.com/akvo/akvo-product-design/issues/282

Thus we use the phone number to identify devices between Flow's backend and the app. This however does not mean we need to show the phone number in the device list in the online workspace. The phone number is not used by our users when assigning devices and thus is of no value to show in the list and to have the private information accessing to those with Device management permissions.

<img width="1264" alt="screen shot 2017-11-07 at 09 24 04 copy" src="https://user-images.githubusercontent.com/12456965/32484115-050da646-c39f-11e7-8b27-c802bc5f1c45.png">

# Change 
With this issue we will remove the Phone number column from the Device list and from the UI. After refactoring how we identify devices we will later in a separate issue remove the phone numbers from Flow fully. 

@muloem what are your thoughts?

**Comment by Maseline** [comment]
Test plan
Select Devices from the main navigation bar
Devices are listed under the Devices list tab
Note that phone number has been removed from the headings and the list all together

**Comment by janagombitova** [comment]
All is gone as wanted. So these fixes are ready for release

We have one more place where the phone number shows. I have created a separate issue for it here: https://github.com/akvo/akvo-flow/issues/new
