### ISSUE TITLE
Simplify Data cleaning UI to match export changes 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2300]
# Context 

We have started a larger project on improving how users export data, how we divide export types, call them and structure the UI. In this issue you can find all details: https://github.com/akvo/akvo-product-design/issues/273 Because exporting data is in Flow closely linked to importing data and data cleaning, we need to make sure the Data cleaning tab matches with the changes coming. 

We recognised that Data cleaning needs larger improvements in regards to the UI, but mostly around notifying the user if import or export went wrong and why. As these changes are not defined nor tested yet, we will only change the current UI with some lipstick improvements to bring consistency. 

# Current UI 
<img width="1269" alt="screen shot 2017-11-07 at 09 16 49" src="https://user-images.githubusercontent.com/12456965/32484374-d6d56ad8-c39f-11e7-9fa1-2b8141aca7a2.png">

# Changes 
- change ‘Export raw data report’ title to ‘Data cleaning export’
- shorten the description and only keep: ‘Please make a copy of this file before you make any changes.’
- change button from 'Raw data report' to 'Download'
- change: ‘Import cleaned survey data’ to ‘Import data’
- shorten description to only ‘Import will overwrite the existing data. The file must be in .xlsx or .xls format.
- change button from 'Import clean data' to 'Import'

**Comment by Maseline** [comment]
@janagombitova Export raw data report and and the length description are present under Reports as well, should i implement a change that works to change the text for both Data Cleaning and Reports or just for this case of Data Cleaning

**Comment by janagombitova** [comment]
@Maseline Good catch! Only on the Data cleaning page as we are implementing a fully new UI (Loic is currently working on that with Stellan) for the Reports. Here you can see what is coming up: https://github.com/akvo/akvo-flow/issues/2282

**Comment by Maseline** [comment]
Test plan
Select Data from the main navigation 
Under Data select Data Cleaning
Note that the headings, descriptions and button text have changed
Note that these changes have not affected what was under Reports

**Comment by janagombitova** [comment]
Note sure if what I see is due to these changes, but something broke on the Data cleaning tab and needs fixing. The folder/survey/form dropdowns are gone:

![screen shot 2017-11-24 at 10 27 06](https://user-images.githubusercontent.com/12456965/33203974-337b64e4-d102-11e7-8757-a71ebb1bc348.png)
![screen shot 2017-11-24 at 10 27 17](https://user-images.githubusercontent.com/12456965/33203976-35efafc8-d102-11e7-8bc1-69d55d976ecb.png)
<img width="1156" alt="screen shot 2017-11-24 at 10 26 51" src="https://user-images.githubusercontent.com/12456965/33203977-374208b2-d102-11e7-9015-3ea887243347.png">

Secondly, when selecting the date in Collected from and to I do not get the date selector anymore: 

![screen shot 2017-11-24 at 10 29 09](https://user-images.githubusercontent.com/12456965/33204008-5505ab2e-d102-11e7-823c-8863bdbbccfc.png)

**Comment by Maseline** [comment]
Seems unlikely since only changes made were to placeholders text but let me look into it

**Comment by janagombitova** [comment]
Thank you and please do not forget the date selector that should be showing. 

<img width="1144" alt="screen shot 2017-11-24 at 12 10 51" src="https://user-images.githubusercontent.com/12456965/33208099-8881daa0-d110-11e7-9462-4c2fbd9e0f3b.png">

**Comment by muloem** [comment]
The issue with the inspect data tab not loading is connected to changes in #2282.  Specifically the changes in `views.js` under a962f534e37f181b08106f2a22e8b5fbc6d1cf8c

**Comment by janagombitova** [comment]
All resolved 👍
