### ISSUE TITLE
Remove localised header code from report engine

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2309]
Since we are removing the UI for translated report headers in #2286, we can clean up the report engine code.

**Comment by stellanl** [comment]
One question: translated options etc. are still exported that way. Keep or remove?

**Comment by janagombitova** [comment]
@stellanl do you mean when a form is translated to one language, if we still want to add the translations to the export (to show the original language and then the translation)? Like in this issue: https://github.com/akvo/akvo-flow/issues/1828

**Comment by stellanl** [comment]
Well, right now I think we do not so much add as replace. We output only the translated text.

**Comment by janagombitova** [comment]
With @stellanl we agreed everything related to translations can be removed from the exports code.

**Comment by janagombitova** [comment]
@stellanl anything in particular I need to test or to keep in mind when testing?

**Comment by stellanl** [comment]
No, there is no way (any longer) to provoke the report engine by asking for Spanish/whatever from the UI.

**Comment by janagombitova** [comment]
Ok. Then this one is also good for releasing
