### ISSUE TITLE
Show statistics on questions which have a metric

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#231]
In many cases it is useful for users to see basic statistics on a number of questions. A simple form of this can be accomplished by making use of the surveyQuestionSummary objects, and show these numbers of those questions of a survey which have a metric.

This has been implemented for the Cardno instance.
At the moment, the totals number which is displayed is fudged: it consists of the maximum of the sum of any of the statistics. This needs to be replaced by a real surveyInstanceSummary object.

**Comment by janagombitova** [comment]
Issue recreated in product design repository https://github.com/akvo/akvo-product-design/issues/179 as we need to properly investigate how to move forward with this functionality
