### ISSUE TITLE
Remove phone number from Assignments 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2316]
# Context 

This issue is a follow up to the work done here: https://github.com/akvo/akvo-flow/issues/2299

When the user creates an assignment she needs to also select the devices for the assignment. When she looks at the available devices, she chooses them based on the device ID given to the device in the app. But we also show with the device ID some other internal information. For some devices where we had the phone number available we show the phone number in the UI. Other devices show a different number. 

<img width="1261" alt="screen shot 2017-11-14 at 09 31 23" src="https://user-images.githubusercontent.com/12456965/32774033-55c4ea54-c92b-11e7-9594-7c7b987da843.png">

# Changes 
- we should not show the phone number with the device ID

# Questions
- should we fully move towards only showing the Device ID? 
   - If yes, what about possible extreme cases where we do not have the device ID? What do we show then? Do we have many of these cases? 
   - I remember with one of the releases we made sure all devices must have and must show the device ID in the UI, but there might be a small chance there are older versions out there.
   - my personal preference as we 1) declutter the UI and 2) are more responsible in handling personal data (android IDs and IMEIs are also considered personal data) by not showing them in the UI
- if the first option is too risky, should we show one internal ID, if yes which and how can we unify it? 

@muloem and @valllllll2000 what are your thoughts? 

# Future improvements 
Unifying and simplifying the device identification is a problem we will **not** solve with this issue but will deal with in a larger streak of changes - akvo/akvo-product-design#282 As we need to make sure we not only have a consistency in how we identify app devices but also fully remove all phone numbers from our database.

**Comment by valllllll2000** [comment]
To my knowledge you cannot start filling forms in the app without having created a device id and user (going through the login screen). For existing devices, in Android we check if device has gone through setup (login) but we do not check specifically if the device id exists, maybe that would be time to add that check.

**Comment by janagombitova** [comment]
That does sound good. I also feel that you much have the device ID set up to use the app. I remember the issue was that the device had the ID specified but it not always showed on the workspace, but that should be resolved now.

**Comment by muloem** [comment]
I believe our idea has always been to move towards having (clearly identified) users on the devices and as long as data is uploaded from an online device it should be associated with a user rather than a device ID.  If data is in some way (we have to think carefully about this one) uploaded from an offline device, it should probably be associated with the uploading user rather than the presumed offline user.  Such changes would obviously not be covered by the scope of this single issue but this issue could be a part of them.

Perhaps for the time being we can leave in place information that is currently helping the users with orientation and identification and when we have the users in place we can start replacing this info.

**Comment by janagombitova** [comment]
@muloem I fully agree with the case to move towards app users rather than having devices and indeed that it a larger change and we need a different issue for it. 

For this one, we removed phone numbers from the Device list with this change: https://github.com/akvo/akvo-flow/issues/2299 because phone numbers are considered private information and we have other data we use to identify devices, thus we do not need to also store the phone numbers. As we need to become more responsible in how we handle personal data I thought we can start with stopping using phone numbers to identify devices and thus remove them from where they show in the UI (larger issue here akvo/akvo-product-design#282)

**Comment by janagombitova** [comment]
With the new assignment UI we no longer show extra info on the devices, only the device name.
