### ISSUE TITLE
Remove "No additional settings for this question type" 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2319]
# Context

In the survey editor once the user selects the question type, she has some more options to choose from that we call Settings. Some questions however do not have any more settings to work with. The we show a grey space with the sentence that there are no additional settings for the question type.

<img width="1219" alt="screen shot 2017-11-15 at 09 01 12" src="https://user-images.githubusercontent.com/12456965/32825097-ea1b167a-c9e3-11e7-9435-9d46ffdc5eb6.png">

The questions are: 
- photo 
- video 
- date 
- signature 

# Opportunity 
As there are so Settings for the above mentioned question types, the grey space with the text "No additional settings for this type of question" does not really tell anything to the user extra. It takes up space. Could we remove the entire grey box and the text and thus declutter the screen?

**Comment by Maseline** [comment]
Test Plan
- Open any survey
-Try adding a new question and keep changing the question type before saving
-Additional settings text box should show up for only questions that have additional settings

**Comment by janagombitova** [comment]
Nicely done, all works as expected on Firefox, Chrome and Safari
