### ISSUE TITLE
Remove images desplayed on top of the details panel

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#2321]
Currently, images from a data point are displayed at the top of the details panel when a point is clicked on the map
![screen shot 2017-11-15 at 14 09 37](https://user-images.githubusercontent.com/1155088/32833210-2da5ca54-ca0f-11e7-872b-dac984d95c50.png)

This is unnecessary because with the refactor, image will also be displayed on the responses section of the details panel
![screen shot 2017-11-15 at 14 10 04](https://user-images.githubusercontent.com/1155088/32833234-3e3e9b52-ca0f-11e7-8e4e-6e9030db222d.png)

**Comment by janagombitova** [comment]
Tested on flowaglimmerofhope and it looks good.

**Comment by kymni** [comment]
Issue was addressed in the #2144 merge
