### ISSUE TITLE
Remove datatype from Geoshape export

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2322]
# Context 

The issues is related to what we currently call Geoshape export and the structure of the file. 

Issue description for @joycarpediem: 

The responses which form the properties of the of the json contain the responses as key-value. Currently in the value it displays the datatype along with the value. It should not display the data type. This causes issues with using the json file.

![screen_shot_2017-11-13_at_4 41 15_pm](https://user-images.githubusercontent.com/12456965/32847252-c2a676e8-ca29-11e7-8fb7-6140e9e156eb.png)

The issues happens for option and cascade questions and most likely is due to the code - text set up. For now to be able to use the file for colour coding (for example) you need to remove the datatype form the json.

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/geojson-export

**Comment by stellanl** [comment]
This probably needs to be handled in akvo-flow-services/src/akvo/flow_services/geoshape_export.clj but I'm just guessing as I'm not a Clojure person.

**Comment by janagombitova** [comment]
@iperdomo and @dlebrero this is one of the smaller issues we spoke about yesterday

**Comment by dlebrero** [comment]
@joycarpediem 

For the example highlighted in the image above, the correct value is "[ \"liter\" ]" or "\"liter\"" or "liter"? 

For the example in the image just below, do we need to unwrap any of the content inside the "point"?

![screen shot 2018-05-24 at 19 07 25](https://user-images.githubusercontent.com/2147539/40500735-f877a89a-5f85-11e8-9adc-e181f60b1430.png)

**Comment by dlebrero** [comment]
@joycarpediem any chance to get some feedback on this issue?

**Comment by joycarpediem** [comment]
@dlebrero , Sorry about the late response. It needs to be 
"Unit":"litre"

**Comment by dlebrero** [comment]
and for the for the example in the image just above, do we need to unwrap any of the content inside the "point"?

**Comment by janagombitova** [comment]
As the issue in Flow services is closed and changes released, I assume we can consider this one closed too. If not @joycarpediem can you check after the Flow release and let me know if the issue is still present?
