### ISSUE TITLE
Clean up location beacon data from datastore 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2326]
# Context 

Since the 2.2.10 app release in January 2017 we have removed the location beacon feature from the app and this information is no longer sent to Flow from the devices. However, we still have the data stored in the data store. As this info is not used, there is no reason for us to store this data. 

# Changes 

Clean up datastore for each instance and remove the location beacon data 

# Questions and concerns 
- How can we remove the data from each instance effectively? 
- How can we make sure we just ignore the new data and not store it but also make sure nothing crashes in the app for cases where old app version still might be sending the data? as @valllllll2000 mentioned

**Comment by stellanl** [comment]
I suggest
 * A datascript.
 * Retaining the beacon endpoint ( /locationBeacon in org.waterforpeople.mapping.app.web.LocationBeaconServlet), but removing the data-saving code.
