### ISSUE TITLE
Sort reports on collection date

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2327]
All the reports or just the data cleaning one?

**Comment by janagombitova** [comment]
All.

**Comment by janagombitova** [comment]
Works for Data cleaning exports, still need to check Data analysis and Comprehensive once the structural issues are fixed. But we can consider it ready to go

**Comment by stellanl** [comment]
I looked a little at the performance: my machine takes 2ms to sort a short report...
