### ISSUE TITLE
Longer titles for RQG sheets?

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2328]
The RQG sheets are now named like "Group 7". They could be decorated with the group name just like the group header: "Group 3 - Details on commuting". However, sheet names have length restrictions, so we'd need to handle that as well. Worth it?

**Comment by janagombitova** [comment]
Is this also part of the release?

**Comment by muloem** [comment]
Nope. This will go in the next round.

**Comment by janagombitova** [comment]
I personally do not think we need to expand on the sheet title. The "Group 7" indicates well the order of the group and in the 1st row users can see fully the group name to make sure what they are dealing with. 

I think we can close off this issue for now and see if in the next rounds of feedback this comes up. Will make sure to add it as a validation point for the user research. 

@stellanl and @muloem do you agree?

**Comment by stellanl** [comment]
Totally.
