### ISSUE TITLE
Loading spinner spins after saving Assignment 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2329]
After creating a new assignment or saving changes to an existing one the loading spinner keeps on going. The error in the console is this one: 

<img width="1274" alt="screen shot 2017-11-20 at 15 28 01" src="https://user-images.githubusercontent.com/12456965/33023110-6c3a08d8-ce07-11e7-9458-3f959e2ea60a.png">

However, the changes do save properly and are well reflected on the app.

**Comment by Maseline** [comment]
@janagombitova , noticed a new issue when you try to create a new assignment and navigate away without saving r filling in any details, a blank assignment is created and added to the assignments list and it cannot be deleted. An error is shown in the console.
![newissue](https://user-images.githubusercontent.com/3306929/35214831-845333b6-ff73-11e7-9a9a-bb84ef45eb49.png)

**Comment by janagombitova** [comment]
@Maseline I tried to reproduce the issue you found and this is what I found: 
- if I open a new assignment and hit save without filling in anything, I get the message saying I need at least a name -> so this works ok
- if I open a new one and do not fill in anything and hit the Go back button, I do not get an empty assignment in the list 
- if I open a new one and navigate away by for example selecting surveys in the top menu, then I indeed get the same case I you have and the deleting does not work. 

I think it might be easier to create a separate issue with this particular problem, and handle the loading spinner issue in this one - if the implementation of the solution is not related. What do you think? 

But indeed both issues are worth solving. Well caught!

**Comment by Maseline** [comment]
@janagombitova i agree, think it should be a separate issue

**Comment by janagombitova** [comment]
@Maseline I found an older issue that I think is about the problem of empty assignments being created: https://github.com/akvo/akvo-flow/issues/1223

**Comment by janagombitova** [comment]
Closing this issue as this page is being fully re-worked
