### ISSUE TITLE
Remove old-format data cleaning import code

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2330]
When we the users are happy with the new data cleaning imports, as handled in issue #2295 and have no old data to upload, we can remove the parseSingleSheet() method of RawDataSpreadsheetImporter.java

**Comment by stellanl** [comment]
Test plan:
Try to import a spreadsheet in the old format (or the analysis format) - should fail.

**Comment by janagombitova** [comment]
It fails as it should fall. Well done @stellanl. Plus I like the error you added: Invalid RAW DATA file: DATA_CLEANING-238329118 (2).xlsx - Errors: First header cell must contain 'Metadata'. It is a good touch to inform the user what is going wrong. 👍
