### ISSUE TITLE
Remove Last data only filter from Data cleaning export

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2339]
![screen shot 2017-11-23 at 14 49 52](https://user-images.githubusercontent.com/12456965/33178808-a1fd5526-d067-11e7-80c4-3b4b1aebe072.png)

In the Data cleaning export we have now the filter: Last data only. This is currently always shown in the UI. 

It only works (makes changes to the export) for monitored surveys - for data out of monitoring forms. What it does is that for monitoring forms only gives you the latests submission to a data point. So if I have three submissions for one monitoring form to a data point, it gives me the most recent one only. 

It is a good feature but it should only show once the user selects a monitoring form and not when she selects a non monitoring one. Secondly the name is not descriptive enough (as we first thought that this filter will give you all the data to the form that was submitted since the last time you did a data export) 

For this release we will remove the filter and then in the next release (new issue) bring it back with the improvements mentioned above.

**Comment by muloem** [comment]
## Test Plan 

* Select the data cleaning report on the reports tab
* Verify that the report generates correctly but the option to select last collected data is now shown

**Comment by janagombitova** [comment]
All gone, let's not forget to bring it back again ;) but this is ready to roll
