### ISSUE TITLE
Add filter to export only latest submission of monitoring form to data point 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2340]
In this issue https://github.com/akvo/akvo-flow/issues/2339 we removed the so called **Latest data only** filter from the UI. This filter allows users for monitoring forms to only export the latest submissions to a monitoring form for each data point. 

# Changes to discuss: 
- The filter should show for Data cleaning export and for Data analysis export 
- Rename the filter to make it clear what it filters out 
- Show the filter only once a monitoring survey is selected or only once a monitoring form to a monitoring survey is selected (and not the registration from)

**Comment by janagombitova** [comment]
# Context 
With monitoring our partners submit one monitoring form to a data point multiple times. Data collection when monitoring can happen constantly or in rounds (once a year all the data points are visited to capture data on the current status). 

Once users export the data, they select the monitoring form and hit export. In this case they get all the data submitted to the monitoring form and thus some submissions point to one data point. If data was collected in rounds, Salim is only interested in the newest data for each data point as he has already cleaned and analysed the older data from the previous round.

# Changes 
- once a user selects a monitoring form from a monitoring survey (not the registration form) show the option the export only the last submission for each data point 
- add this option to Data cleaning exports and to Data analysis export

**Comment by stellanl** [comment]
The code for this filter is still present in the report engine, and should just need the "lastCollection" flag to be passed in from the UI.

**Comment by janagombitova** [comment]
@stellanl just to confirm - what the code that is currently in the report engine does, it it exports for every data point the last submission made to the selected monitoring form, right? 

So we need a way to allow Salim to decide in the UI that we wants this "lasCollection" for Data Cleaning and Data Analysis and ensure it only shows if Salim selects a monitoring form in the dropdown.

**Comment by janagombitova** [comment]
Here is the revised design provided by @Kiarii https://projects.invisionapp.com/share/HMG8IDOVCX7#/screens/283709674

We still need to decide on how to name the last submission (in designs as Recent submission) to the data points filter. 

The expected behaviour is: 
- submission date and Recent submission (or how we call it) are available filters for both Data cleaning and Data analysis exports 
- the Recent submission is disabled if the user has selected a non monitoring survey or a registration form to a monitoring survey 
- the Recent submission is only enabled for monitoring forms of a monitoring survey 
- the user can either filter the export on submission date or on recent submission, not on both

**Comment by loicsans** [comment]
@stellanl I've added the radio buttons.

**Comment by janagombitova** [comment]
@stellanl if working with radio buttons is not possible, can you and Loic figure out another way? 

The requirement - and reason why we went for radio buttons - is that Salim can either filter the data export on a set time filter or on the Recent submission. Not on both. Radio buttons make this clean to Salim. 

Further expectations are: 
* [ ] submission date and Recent submission (or how we call it) are available filters for both Data cleaning and Data analysis exports
* [ ] the Recent submission is disabled if the user has selected a non monitoring survey or a registration form to a monitoring survey
* [ ] the Recent submission is only enabled for monitoring forms of a monitoring survey
* [ ] Salim can either filter the export on submission date or on recent submission, not on both

**Comment by stellanl** [comment]
"Recent submissions" is a little cryptic. A user might ask herself: How recent? Last day? Last week?
It might be clearer with something like "Only most recent submission for each data point". Or is that too long?

**Comment by janagombitova** [comment]
Good point @stellanl. I just asked Georgia (Comms) and she said 'Most recent submission'

**Comment by janagombitova** [comment]
This change has been pushed to the 1.9.34 release (June) as the implementation did not fully reflect the expected user experience we aimed to introduce and needed some small improvements. For more info see here: https://github.com/akvo/akvo-flow/pull/2585#issuecomment-390923099
