### ISSUE TITLE
Comprehensive reports not generating with new UI 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2344]
No comprehensive reports being generated after the changes to exports and the new UI. Found a bug while testing

**Comment by stellanl** [comment]
The reportMode parameter is not sent to the server.

**Comment by janagombitova** [comment]
The comprehensive report gets generated now, but there are issues in the Raw data sheet. The structure is off. 

Here is an example of a fake data set:

[DATA_CLEANING-214449116 (1).xlsx](https://github.com/akvo/akvo-flow/files/1501206/DATA_CLEANING-214449116.1.xlsx)
[COMPREHENSIVE-214449116.xlsx](https://github.com/akvo/akvo-flow/files/1501207/COMPREHENSIVE-214449116.xlsx)

**Comment by janagombitova** [comment]
works again 👍
