### ISSUE TITLE
Error in console after hitting Download for exports 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2349]
# Context

Every time I hit Download on the Export reports page in Console I see this error: 

![screen shot 2017-11-24 at 10 52 18](https://user-images.githubusercontent.com/12456965/33204981-915e58ca-d105-11e7-8bd6-b9aeb0a5aa83.png)

So I select the folder > survey > form and then the export type and hit Download. I get the notification message that my report is on its way and I also get it in my inbox, so all works fine. But the error shows with each download hit for any export type.

**Comment by muloem** [comment]
As best as I can tell this is supposed to activate the dialogue box but that is done elsewhere.  So for now we'll get rid of the function and introduce it when there is a proper implementation behind it.

**Comment by muloem** [comment]
#Test Plan

1. Try to generate a report form the _Exports_ tab while having the dev console open.  Ensure that the error reported above does not appear.

**Comment by janagombitova** [comment]
No more errors showing 👍
