### ISSUE TITLE
After user selects new form/survey zoom out the map

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2351]
# Context 

For Carto maps 

You start by selecting the form and you zoom into the area where the points are located to see where they are placed. Then you might select another form to look at, the points are removed form the map, but the map stays were you zoomed into. You might have first been in Iceland and now the new points are in Kenya, then you need to zoom out and then zoom in again. 

# Opportunity
Can we - once the user selects a new form or new survey - zoom out of the map and possibly zoom to the new location of the points? 

@kymni what do you think?

**Comment by kymni** [comment]
This makes sense. It can be done by first getting the bounds of the loaded layer (data points in the form) then using the `fitBounds()` method to fit the map to the layer
