### ISSUE TITLE
Survey dropdown acting off 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2353]
# Context

The survey dropdown acts a bit off every now and then but I cannot find a pattern yet: it does not want to load the next level, or does not unselect the lowest level if I select a different folder for example.  I get this error, but it is random. Sometimes a full refresh helps, sometimes not.  

![screen shot 2017-11-24 at 12 29 32](https://user-images.githubusercontent.com/12456965/33208771-29036a0a-d113-11e7-8362-8cd7fad4cd80.png)
 
Another thing I noticed when trying to figure out what is happening is this: 
The steps I took: 
1. Select a folder > survey > form 
2. Deselect survey and folder - in the first dropdown select "Choose a folder or a survey" 
3. The initially selected form remains in view 

This happens in all the pages across Flow.  And I get the same error as shown above. And then I need to fully refresh Flow, as once I get the error then the dropdowns stop working properly

**Comment by muloem** [comment]
The survey dropdown issue seems to be connected to the changes introduced under #2282.

**Comment by janagombitova** [comment]
Yay! Back to normal again
