### ISSUE TITLE
Collection date filter also applies on Comprehensive report

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2362]
# Context 

In the new Exports page we have a filter **Collection date** for the Data cleaning export and for the Data analysis export. What this filter does it in only exports out the data that has been submitted in the specified time period. 

This is especially handy for large scale data collection exercises when Petra is only interested in the data that came in, lets say, last month, as she already analysed the older data. Or if in a project some results are linked to a specific time frame Salim might only need to see the data from that period to understand what the project achieved. 

# Opportunity 
There are two issues with the current Collection date filter - one handled here and another one in this issue: https://github.com/akvo/akvo-flow/issues/2363

The issue is: Data cleaning and Data analysis exports both have the filter. If the user selects a date in one of the filters but decided to export a Comprehensive report, the filter is still "active" and in the Comprehensive report the export only contains the submissions from the specified date range. 

**The question is:** Do we see the value in users also filtering out the Comprehensive reports? If yes, is it ok to have the filter separately in the three export options? 

![exports](https://user-images.githubusercontent.com/12456965/33309892-0e626344-d420-11e7-9bd7-dc1bdbe854a4.gif)

**Comment by muloem** [comment]
The question that comes to my mind is to review whats the main use of the comprehensive report.  So far we are using it or aggregating data and in that sense, aggregating data only over a specified period of time may be useful but may also confuse users who want to make a report over all the data collected.  My interpretation is that comprehensive is something that is complete. So I would say it makes sense that it includes _all_ the data.

**Comment by janagombitova** [comment]
To be honest the use I know: is to get a quick view of your data before we dive into specific analysis. The date filter was never possible on this export type and the option never came up in any user feedback so I think it is more up to us to make the decision. 

I can see the value is seeing quick summaries also for specific time periods when the data was captured, but also like the rule of keeping things simple thus keeping this one with **all** data at all times. 

We can take this road for now and thus make sure the collection date filter does not apply on the Comprehensive report and if we get feedback from users on having the filter, we can always reconsider the implementation later on.

**Comment by janagombitova** [comment]
The fixes in this issue: https://github.com/akvo/akvo-flow/issues/2363 seemed to resolve the problem we also have here.
