### ISSUE TITLE
Single-sheet import accepts repeats for non-repeated questions

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2365]
Questions outside of an RQG are still accepting >1 repeat responses.

Small fix; about an hour, but unnecessary if/when we remove import of single-sheet reports.

**Comment by janagombitova** [comment]
Links to this issue: https://github.com/akvo/akvo-flow/issues/2330 correct?

**Comment by janagombitova** [comment]
Related to issue above mentioned that also holds a fix to it.
