### ISSUE TITLE
 Importing in new data using the Data cleaning export format

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2368]
# Context

Users capture data with Flow. But sometimes they already have data stored somewhere else and they either want to have it stored in Flow with their other data, or they want to use the data for further monitoring in Flow. Simply speaking they want to have their data in Flow.

Currently what is possible is using data cleaning import to import new data into Flow. How:

- User creates a survey form with questions matching their data
- Exports the Raw data report
- Fill in her new data into the sheet
- Does not fill in the Identifier, Instance, Device
- Imports the file using Data cleaning to the survey form
- There is one limitation: you cannot import new data into a monitoring form.

# How it works since 1.9.25 release 
In the 1.9.25 release we released new export structures and **Data cleaning export** is the one users get when cleaning data. The "old" raw data report is not longer downloadable from Flow. 

However, to import in new data users can use the structure of raw data reports. 

# Opportunity

We need to make it possible to import in new data using a data export structure we currently offer in Flow, to not have a third structure hidden in the shadows. 

With the new export structure using data cleaning for import is ok, if there are no repeated question groups in the survey form. However, if there are any, we need to figure out how to make this import possible as the user currently has no way to link that data in the separate sheets (the Flow identifier is not generated yet as they data is to be imported as new data).

Do we want to have this possibility hidden under that name of data cleaning?
How can we make importing new data to Flow possible?

@stellanl can you share your ideas here?

**Comment by stellanl** [comment]
The new RQG responses need to be linked to the new instance (on the base sheet) somehow.
I propose that we link them with a special flavour of unique values in the Identifier (or prerhaps the Instance) column, like this:
"new-1", "new-2"... etc.
That way those values are then easy to recognise and strip out just before the upload to the database.  And with those columns empty they will be treated as new.

**Comment by janagombitova** [comment]
Great! Stellan, once ready to test can you explain here how I should go about importing in new data with repeated groups? The steps and what I need to add and a test plan? Cheers

**Comment by janagombitova** [comment]
@stellanl I tested importing in new data with the Data cleaning export structure for submissions with no repeated questions groups and that worked perfectly. 

Can you tell me how to do the ones that might have a repeated question group? How am I supposed to link the submissions in the main sheet and what should I put in where?

**Comment by stellanl** [comment]
Just like I outlined above. Put new-1, new-2 etc in the first column. They work just like an empty cell, but can be referred to on the repeat sheets.

**Comment by janagombitova** [comment]
# Test result
👍  works like a charm. 

# Tested cases  
I have tried out some extreme cases and here are the outcomes: (will make sure support has them all shared with users) 
- What happens if I add different submission date in main sheet and in repeated sheet? >> the meta data in the repeated sheet is ignored. >> no need to fill in meta data in the repeated sheet besides the ID and the Repeat no 
- What happens if I forget to add Repeat no? The entire sheet is ignored >> Rule: Make sure you fill in the Repeat no column. 
- What happens if I put an ID in the main sheet but not in the repeated sheet? > Flow thinks there are no data to the repeated group, all ok.
- What happens if I have an ID in the repeated group sheet but not in the main sheet? > Flow ignores the repeated group data and does not save them. >> Rule: make sure you put the IDs in properly 
- What happens if I put the right IDs in the repeated group sheet, but I do not group the repetitions? (So if a submission has two repetitions but I put submissions one repetition one in row two, submission two repetition one in row three and submission one repetition two in the fourth row) > Flow thinks there is only one repetition as the rows are not grouped. >> Rule: if s submission has more repetition in the repetition sheet they have to be put together in following rows 
- What happens if I remove the first row? > The import fails and I get an error that does not fit - created an issue for it - https://github.com/akvo/akvo-flow/issues/2390

# Question
With this change does this mean we will stop supporting the import of the old raw data report structure?
