### ISSUE TITLE
Submission list remains on Inspect data after navigating away and back

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2372]
# Context 

To I select data to view in Inspect data tab, I select my survey > form and press Find to generate the list of submissions. After I am done I might navigate to another page in Flow. Then I may come back to the Inspect data page and I still see the list of submissions in the page even thought the survey > form are not selected anymore. Because I left the page, I do not want to see the list of submissions anymore. 

![inspect](https://user-images.githubusercontent.com/12456965/33438432-1e54b87a-d5eb-11e7-9c53-835c53ab2171.gif)

# Change 
Make sure that once the user navigates to another page in Flow, the list of submissions does not show if she comes back to the Inspect data tab.

**Comment by bogere** [comment]
### Test plan
*  navigate to the inspect-data-tab
* select the survey forms whose submission lists you want to see and click the Find button
*  Submission lists for a specific survey form are shown
* Navigate to another page like clicking on survey tab or message tab or any other navigation  tab
* when you come back to inspect-data-tab, you wont see the submission lists
