### ISSUE TITLE
Remove unused data members sublevel[n] and approximateLocation

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2379]
This is part of the general cleanup issue #555
These items take up space in the data store and its management UI for no good reason.

**Comment by janagombitova** [comment]
@stellanl anything in particular I need to test or to keep in mind when testing?

**Comment by stellanl** [comment]
No, there is no way to positively check that this worked, since they have been unused for years. 
(If I messed up badly and removed too much, something else may conceivably have stopped working.)

**Comment by janagombitova** [comment]
ok. then this one is ready to roll
