### ISSUE TITLE
Indicate form must be selected in Exports page 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2380]
# Context 

Once a user decided she wants to export data she goes to the Export tab. She first has to select the folder > survey > form she wants to get the data out of and then she selects which export option is the best for her. 

However, if she goes directly to the export option and hits download without selecting the form, there is no indiction in the page telling her she skipped a step. 
![export](https://user-images.githubusercontent.com/12456965/33768456-64de5fd0-dc26-11e7-9477-cd0d23a61b70.gif)

# Change 

Do we need to indicate in the UI that the folder > survey > form were not selected? 

How might we indicate to the user that she needs to select a form (folder > survey > form) from the drop downs first, before she can download any export option? 

@loicsans and @Kiarii What are your thoughts?

**Side note**: if we decide to do a UI indication of some sort, then we should apply it also in the Inspect data tab, Data cleaning tab, Monitoring tab

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/issues-data-export

**Comment by Kiarii** [comment]
- the Data Cleaning has a pop-up notification: "you must select a survey to run a report"
- Inspect data has an in-page message: "No results found"
- Monitoring tab has no indication

Aligning these will depend on the resources we have with potential solutions ranging (effortwise) from  
- a pop-up,
- an error indication for a required field; as in a form
- to a clear progressive (workflow), emphasizing the relation and flow of actions.. 
- we could also consider holding-in-place the survey within which a user tends to work from as a (changeable) default to reduce the need for always having to pick the survey..

**Comment by janagombitova** [comment]
After a talk today with @Maseline and @Kiarii we agreed to create an error indication of the dropdown menu in this tab to show users that they must select the form before being able to export data. 

The error should appear if the user hits "Download" button in any of the provided export options but did not select in the dropdown menus a form. 

As in the dropdown we already tell the user to "Choose a ..." we will not display an error message to not duplicate the text and test out if this indication is enough or not. 
 
![image](https://user-images.githubusercontent.com/12456965/35323835-3bf18910-00ef-11e8-9d54-5e16d66507d2.png)

**Comment by Maseline** [comment]
@janagombitova check this out,  you mentioned testing out if the change in color is enough for indication, this is what either of the solutions could look like
![sln1](https://user-images.githubusercontent.com/3306929/35503389-0b249254-04f1-11e8-91fc-9a4608dfa019.png)
![sln2](https://user-images.githubusercontent.com/3306929/35503398-11b8fe70-04f1-11e8-98d6-110a22351757.png)

**Comment by janagombitova** [comment]
Hey @Maseline thank you for posting both options. I personally prefer the 1st option. @Kiarii what would you recommend?

**Comment by Maseline** [comment]
@janagombitova , a discussion with Emmanuel revealed another scenario, say someone had to select a couple of options, be it folders or surveys and they stopped before selecting everything and selected download, which section gets the red border to indicate the error, all of the select inputs or just the missing one
![borderissue](https://user-images.githubusercontent.com/3306929/35727090-0202aaba-0818-11e8-805c-10956039f28e.png)

**Comment by Kiarii** [comment]
we could cover all bases by having the error msg in its place and simply saying sth like "no form selected, or please select a form, .."

**Comment by janagombitova** [comment]
Is it possible to highlight not the dropdown itself but the area around it (so you take the full width into consideration? Or is that a silly idea? 

I am asking because in the Inspect data tab for example the form dropdown is put on a 2nd row. 

<img width="1173" alt="screen shot 2018-02-02 at 16 42 33" src="https://user-images.githubusercontent.com/12456965/35741433-22376ea4-0838-11e8-9f01-3530f84e9946.png">

**Comment by Maseline** [comment]
@janagombitova , do you mean something like this
![designissue](https://user-images.githubusercontent.com/3306929/35792849-274260aa-0a60-11e8-8465-fbde73fcb288.png)

**Comment by Maseline** [comment]
@janagombitova , so this is what it could look like in the inspect data and monitoring tab, requires changing the space (padding) a bit 
![designissue2](https://user-images.githubusercontent.com/3306929/35793536-0e13d2be-0a63-11e8-9052-29fd059b419a.png)

**Comment by janagombitova** [comment]
@Maseline I think this is a good 1st implementation, not the most elegant one - but we do not repeat the text already in the page and highlight what needs to be highlighted for our users to see that they do indeed need to select up till the form level before they hit Download or Find. 👍

**Comment by Maseline** [comment]
![dessignissue3](https://user-images.githubusercontent.com/3306929/35794474-eaf32ee8-0a66-11e8-9ca2-a44de0c8e5c6.png)

**Comment by Maseline** [comment]
so @janagombitova @Kiarii , do i have the green light to begin implementation

**Comment by janagombitova** [comment]
@Maseline Yes from me 👍 if you ensure the red outline ends on the screen, now it is cut off on the right, but I assume that is due to the screen shot.

**Comment by Kiarii** [comment]
:) I second that..

**Comment by Maseline** [comment]
@janagombitova , just want to confirm that this implementation is for just the Data Cleaning export. The other report sections have pop up dialog boxes with different messages.

**Comment by janagombitova** [comment]
@Maseline I am not sure I understand you correctly. Do you mean that in the Reports page, in Export reports tab the highlighting of the folder/survey/form selection area is only applied for Data cleaning exports? If yes, can you please expand the implementation to all the export options on that page?

**Comment by Maseline** [comment]
@janagombitova , was meaning the export reports tab, was asking because you'd only highlighted the Data cleaing export in the issue, I'll expand the implementation to all then

**Comment by janagombitova** [comment]
@Maseline I was not explicit enough in the description then, will do better next time. Please indeed expand to all. Thanks

**Comment by Maseline** [comment]
Test plan
Navigate to the export reports tab
For all the reports options, try downloading without selecting a survey or completing the survey selection
Notice the survey selection area is highlighted with a red border when a survey is not selected and this is removed when all surveys are selected and the download option is selected.

**Comment by kymni** [comment]
@bogere we should consider scrolling the user back to the top of the tab so that the filters are visible because as it currently is, the filters are highlighted but in case the user clicked on the generate button while scrolled down, they will not see the highlighting

**Comment by janagombitova** [comment]
Released with 1.9.38
