### ISSUE TITLE
In Monitoring tab data point order shows as NaN 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2386]
# Context 

Once the user selects her survey and form in the Monitoring tab, she sees a list of data points. The first column in the list show the order/count of data points. This now shows as Not A Number. 

<img width="1252" alt="screen shot 2017-12-13 at 10 47 00" src="https://user-images.githubusercontent.com/12456965/33932338-0364fc98-dff3-11e7-9a3f-1e362896f47d.png">

# Change 
Make sure that a order number shows in the list of data points in the Monitoring tab.

**Comment by bogere** [comment]
## Test plan
* select the  survey and form in the Monitoring tab and press find button
* you will  see a list of data points. 
* The first column in the list show the  correct order/count of data points not NaN

**Comment by janagombitova** [comment]
What was not a number is a now a number. Well done, ready for the release 👍
