### ISSUE TITLE
In Monitoring tab add question group to submission view 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2387]
# Context 

Users view data in the Inspect data tab (where you view data per form - so all submissions per a form) or in the Monitoring tab (where you view data per data point - so all submissions made for a data point). 

Both views are however quite inconsistent in how we show a form submission. In the Inspect data tab we show question groups and the questions that belong in them. In Monitoring tab we do not and the questions seem to appear in a random order. 

<img width="1267" alt="screen shot 2017-12-13 at 11 03 47" src="https://user-images.githubusercontent.com/12456965/33933486-27457c70-dff6-11e7-90f7-0030311075d7.png">

<img width="1265" alt="screen shot 2017-12-13 at 11 03 16" src="https://user-images.githubusercontent.com/12456965/33933487-291a27bc-dff6-11e7-966f-2f2d509a084e.png">

# Changes 

In the future we will reconsider how users view data on Flow, but this will not happen anytime soon. We however need to tackle these small UI issues to simplify what users have on their screen and to bring a consistency in how we show data even though in many different tabs. 

Once the user selects her data point and then submission we should show the question group in the view as we do in the inspect data tab. We should also then show the order of the questions in the groups in the view. 

We need to make sure that **repeated question groups** are also shown properly with the repetition number. 

<img width="1207" alt="screen shot 2017-12-13 at 11 06 45" src="https://user-images.githubusercontent.com/12456965/33933392-d80cc80c-dff5-11e7-8fdd-15a9eba8088b.png">

**Comment by bogere** [comment]
## Test plan
* click on the monitoring data tab and select the survey forms that you want to analyse.
* Click the view details of the specific data point in the submission lists.
* Click the view details of the data point in the details dialog until it shows the detailed information.
* you will see the repeated questions having a group names

**Comment by janagombitova** [comment]
@bogere Moses, well done. I have one nitty-gritty change I would like you to make for this issue and the release. Currently the answers are aligned in center. Can you align them to the left? 

<img width="1268" alt="screen shot 2018-03-06 at 08 53 00" src="https://user-images.githubusercontent.com/12456965/37020407-ea5d41aa-211b-11e8-9377-581801cb7688.png">

**Comment by janagombitova** [comment]
It is perfect now 👍  Ready to roll!
