### ISSUE TITLE
Wrong error with data import with no meta data row

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2390]
# Context

When I try to import in new data using the Data cleaning export structure with repeated question groups and I remove the 1st row from all sheets (the row with meta data and groups) the import fails.  In the messages tab I get an error, that my Repat columns is missing what is not true. 

File I tired importing with sample data: [import with rqgs 5.xlsx](https://github.com/akvo/akvo-flow/files/1555973/import.with.rqgs.5.xlsx)

<img width="1195" alt="screen shot 2017-12-13 at 16 18 30" src="https://user-images.githubusercontent.com/12456965/33946277-ab0130a6-e021-11e7-98a1-00d4a84702e9.png">

# Changes 

## Option 1
We make the import fail, but we show an error saying that the 1st row with Meta data and groups is missing. 

## Option 2
We ignore the first row and have the import succeed. 

@stellanl and @muloem What are your thoughts?

**Comment by stellanl** [comment]
The error is almost correct. If there is no first "Metadata" row it assumes an old-format report. And those must have  a repeat column. So it looks for a repeat count in the 2:nd column. Which is blank.

**Comment by janagombitova** [comment]
Ah, I see. Then we need to make a few decisions: 
- Are we still going to support the old raw data report format?
- Are we going to enforce having the 1st row with import?
