### ISSUE TITLE
Remove API keys from UI

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2394]
# Context

With the v2 API users no longer need to generate an API key to use the API. Thus these fields are not needed anymore in the UI in the users tab. 

<img width="1249" alt="screen shot 2017-12-15 at 09 30 13" src="https://user-images.githubusercontent.com/12456965/34035005-e51222a4-e180-11e7-8a28-d32170b5a743.png">
<img width="1249" alt="screen shot 2017-12-15 at 09 30 30" src="https://user-images.githubusercontent.com/12456965/34035011-e5d75cae-e180-11e7-9098-ec522dfb58aa.png">

# Changes 

- remove the API key column from the users lists 
- remove the entire Manage API keys section in each user page 

# Questions
@muloem what are your thoughts on the following questions: 
- Can we remove the API keys even though we are still in the sunset period of v1 API? 
- Is there more that needs to be removed besides the UI views?

**Comment by dlebrero** [comment]
@muloem what are your thoughts on the following questions:

Can we remove the API keys even though we are still in the sunset period of v1 API?
Is there more that needs to be removed besides the UI views?
