### ISSUE TITLE
Migrate flow backend to Java 8 runtime

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2395]
We are currently running our apps on java7 runtime environment that has been deprecated.  We need to migrate our apps to java8. Some instructions on the migration are here https://cloud.google.com/appengine/docs/standard/java/migrating-to-java8

**Comment by valllllll2000** [comment]
@iperdomo anything to test here? if not just move it to release ready, please

**Comment by muloem** [comment]
This should be covered by regression testing as its a change in the java runtime environment and the servlet specification.
