### ISSUE TITLE
Remove metrics

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2397]
# Context 

We have a functionality on Flow called metrics that has not been enabled to all instance, was used only on one as a custom build feature. The partner has not used the feature and now is not using Flow anymore either. 

In the future, the problem this functionality was aiming to solve and value it provided will be re-researched and re-discovered so we can see if it is something valuable for all Flow users. 

# Opportunity 
Remove functionality and everything related. Make sure nothing else breaks.

**Comment by stellanl** [comment]
We could resurrect the "Statistics" tab for everyone but use it to show per-instance stats, like number of forms submitted etc.

**Comment by janagombitova** [comment]
@stellanl we definitely need to find a way to show usage stats, but let's finish up the work we have planned out first for the exports and then we can pick up this one. We have an issue here: https://github.com/akvo/akvo-product-design/issues/265 and can pick up the discussion again once we close the work on exports

**Comment by stellanl** [comment]
In the backend org.waterforpeople.mapping.app.web.rest.MetricRestService implements the /metrics endpoint.
I am removing that and the domain and dao classes for Metrics and SurveyMetricMapping.

Question also had metrics-related field, and SurveyalRestServlet would include metric info.

**Comment by janagombitova** [comment]
Not sure how to test this out considering it was only enabled on akvoflow-12 and that is closed for a while now. I guess just regression testing to ensure all works well? @stellanl what are your thoughts?

**Comment by stellanl** [comment]
Yep. Typical case of trying to prove a negative...

**Comment by janagombitova** [comment]
Regression testing going well. Ready for release 👍
