### ISSUE TITLE
Error in original string

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#2398]
I have found an error in the strings:
`Import\ will\ override\ the\ existing\ data.The\ file\ must\ be\ in\ .xlsx\ or\ .xls\ format.`
a space is missing between data and The

**Comment by stellanl** [comment]
Are you sure it is not a newline that is missing?
They *could* be two messages...

**Comment by valllllll2000** [comment]
@stellanl No idea, it appears as one string in transifex. I have created a PR and assigned it to @muloem because he worked on translations but if you want to have a look, feel free.

**Comment by janagombitova** [comment]
I assume it is just to check that the line shows ok on the UI, which it does - ready to go
