### ISSUE TITLE
Remove unused Authentication servlets 

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2412]
With the introduction of spring-security, the `AuthenticationSubscriptionServlet` is no longer used for user authorisation.   We therefore clean this up as part of the code cleanup in #555

**Comment by muloem** [comment]
#Test Plan 

1. Regression testing ensures that authentication is handled correctly

**Comment by janagombitova** [comment]
Tried logging in with multiple different users. All works fine 👍
