### ISSUE TITLE
Exception when listing questions

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2421]
There is an exception caused when attempting to list questions

     [java] Caused by: 
     [java] org.springframework.beans.FatalBeanException: Failed to obtain BeanInfo for class [com.gallatinsystems.survey.domain.Question]; nested exception is java.beans.IntrospectionException: type mismatch between read and write methods
     [java] 	at org.springframework.beans.CachedIntrospectionResults.<init>(CachedIntrospectionResults.java:262)
     [java] 	at org.springframework.beans.CachedIntrospectionResults.forClass(CachedIntrospectionResults.java:149)
     [java] 	at org.springframework.beans.BeanUtils.getPropertyDescriptor(BeanUtils.java:375)
     [java] 	at org.springframework.beans.BeanUtils.copyProperties(BeanUtils.java:605)
     [java] 	at org.springframework.beans.BeanUtils.copyProperties(BeanUtils.java:570)
     [java] 	at org.akvo.flow.domain.mapper.QuestionDtoMapper.transform(QuestionDtoMapper.java:49)
     [java] 	at org.waterforpeople.mapping.app.web.rest.QuestionRestService.listQuestions(QuestionRestService.java:124)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by muloem** [comment]
So the culprit is here: 

We have two set methods for the translationMap property and this causes an exception in the code that ignores properties.

https://github.com/akvo/akvo-flow/blob/099a50d1dcfe6bea4b846b6058c8da6db016e386/GAE/src/com/gallatinsystems/survey/domain/Question.java#L178-L190

**Comment by muloem** [comment]
# Test Plan 

1. Test the behaviour of translations especially ordering and grouping

**Comment by janagombitova** [comment]
👍 looks good to me

**Comment by janagombitova** [comment]
Ok. I am not sure this is related, but adding it here as it is about showing questions. I found a weird thing going on in Monitoring tab: When viewing submissions to data points, the questions for the monitoring forms do not load and thus also answers, but for the registration form they do. I thought this might be just with one data point, but all I click through I get the same problem. 

Try uat1 > _1.9.30... > 1.9.30 - 1.9.20 dep...

**Comment by janagombitova** [comment]
@muloem nothing changes in the Console, no exceptions. 
![questions](https://user-images.githubusercontent.com/12456965/38031309-3319502e-329b-11e8-9e4b-72ac6f7eb059.gif)

**Comment by muloem** [comment]
This seems to be connected to the changes from #2387 when the group is a repeat question group.

**Comment by janagombitova** [comment]
@muloem so I took a look again and noticed that the entries that should be of the monitoring form submissions show me the question groups from the registration form. 

For example: UAT1 > _1.9.29 and... > 1.9.29 all questions example survey has two forms: 
- registration form: has 4 question groups called G1, G2, G3 and G4 
- monitoring form has 1 group called New group -p lease change name 

In the Monitoring tab, if I select this survey and look at data point xhxhxvx - 06899 - B that has one submission to the RF and one to the MF and I select the MF (the 1st one in the view list) I see the groups of the RF and then no questions. 

![screen shot 2018-03-29 at 17 14 59](https://user-images.githubusercontent.com/12456965/38097146-e1b369ec-3374-11e8-926e-ee1469dad155.png)

**Comment by janagombitova** [comment]
as the issue mentioned above is a different problem, I created a new issue here: https://github.com/akvo/akvo-flow/issues/2567 and this one is ready to roll
