### ISSUE TITLE
Remove unused classes for data export packages

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2431]
A number of classes are not used under the `*.dataexport.*` packages and should be removed as part of cleanup #555 

- [ ] `src/com/gallatinsystems/framework/dataexport/applet/AbstractDataImportExportApplet.java`
- [ ] `src/com/gallatinsystems/framework/dataexport/applet/DataExportAppletImpl.java`
- [ ] `src/com/gallatinsystems/framework/dataexport/applet/DataImportAppletImpl.java`
- [ ] `src/org/waterforpeople/mapping/dataexport/DataBackoutApplet.java`
- [ ] `src/org/waterforpeople/mapping/dataexport/DeviceFilesReplicationImporter.java`
- [ ] `src/org/waterforpeople/mapping/dataexport/KMLApplet.java`

**Comment by janagombitova** [comment]
@muloem anything in particular to test?

**Comment by muloem** [comment]
Regression tests should cover this one as well. Its mostly about removing unused classes

**Comment by janagombitova** [comment]
Regressions going well, ready for release 👍
