### ISSUE TITLE
Export fails if question has no title

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#2433]
#### How to reproduce
* Create a survey in which one of the questions doesn't have a title (the question text).
* Publish and collect some data with the survey
* Try to export the raw data report
* The export fails to be send, silently.

A possible cause could be a null pointer exception in the export code, when it tries to access the question text, which will be null in that case.

Possible mitigation: in addition to error checking in the export code, perhaps also not allow saving of a question with an empty text?

**Comment by janagombitova** [comment]
If we resolve this issue: https://github.com/akvo/akvo-flow/issues/2221 we will then also prevent the one mentioned above

**Comment by janagombitova** [comment]
Issues resolved in the linked one. Closing this one
