### ISSUE TITLE
WaterForPeopleMappingGoogleServlet appears unused

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2447]
I cannot find any reference to it. If it is removed, then org.waterforpeople.mapping.app.web.KMLGenerator.generateDocument() is also unused.

Just some #555 cleanup.

**Comment by stellanl** [comment]
Test plan: regression testing will be enough.

**Comment by janagombitova** [comment]
After a quick regression round all seems to work ok, will note if otherwise if I find something with the full regression testing. 👍
