### ISSUE TITLE
Remove geocode from when viewing data 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2451]
# Context 

With this issue: https://github.com/akvo/akvo-flow/issues/2367 we removed **geocode** from exports. But the geocode still appears in Flow's online workspace when viewing data in the Inspect data tab, Monitoring tab and maps. 

Considering this item is no longer part of the data exports, it may confuse Petra or Salim on what this item is and why it is there. 

<img width="1247" alt="screen shot 2018-01-23 at 16 27 49" src="https://user-images.githubusercontent.com/12456965/35284285-a7f62e4e-005a-11e8-938c-04aa203defd4.png">

<img width="1242" alt="screen shot 2018-01-23 at 16 31 04" src="https://user-images.githubusercontent.com/12456965/35284435-1b0a3920-005b-11e8-8a91-139c9479f26b.png">

<img width="1267" alt="screen shot 2018-01-24 at 09 40 19" src="https://user-images.githubusercontent.com/12456965/35322467-bbd7faba-00ea-11e8-9dea-7161544fc300.png">

# Change 
The overall goal of removing geocode was to remove confusion, thus we need to make sure that it also does not show in the online workspace.

**Comment by stellanl** [comment]
I'm tempted to make a data script that cleans the geocode out of all the responses in the db. That way we do not have to make the UI more complicated by having to filter it out

**Comment by stellanl** [comment]
Also, if we later add accuracy to the geo answers it will just start to show up in the UI without any code changes. (Reports will have to change again.)

**Comment by stellanl** [comment]
Of course, running such a cleanup before the app stops submitting geocodes wuld not be clever.

**Comment by janagombitova** [comment]
@stellanl Do you mean we also need to make a change in the Flow app? If yes, can you create and explain the issue in the repo?

**Comment by Kiarii** [comment]
design status: a go
