### ISSUE TITLE
Remove line above 'No results found' 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2452]
If user selects a form to preview in the Inspect data tab or a survey to view in the Monitoring tab that is empty, we show in red 'No results found'. Once this is loaded it also shows a line across the screen for Chrome, Safari and Firefox (did not check IE) 

<img width="1246" alt="screen shot 2018-01-23 at 16 35 14" src="https://user-images.githubusercontent.com/12456965/35284627-8ff3ef60-005b-11e8-997c-d84ddcd73289.png">

Please remove the line in both Inspect data and Monitoring tabs, it unnecessarily clutters the screen

**Comment by Maseline** [comment]
Test plan
Navigate to Inspect data tab and Monitoring tab
Select the Find option without specifying any survey. Notice that the line that used to appear above 'No results Found ' has been removed

**Comment by janagombitova** [comment]
👍  looking good and cleaner, thank you
