### ISSUE TITLE
Indicate form must be selected in Inspect data tab 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2454]
# Context
Based on the discussion here: https://github.com/akvo/akvo-flow/issues/2380#issuecomment-360069140 we have agreed to streamline how we show users that they need to select a survey/form before completing an action. 

In the Inspect data tab the user must select a form to be able to see the data. Currently if she does not select anything and hits 'Find' we show 'No results found'. This error message should apply to when there is no data for a form and not when a form is not selected. 

<img width="1270" alt="screen shot 2018-01-24 at 10 27 15" src="https://user-images.githubusercontent.com/12456965/35324504-2fa359c0-00f1-11e8-96b4-21db169765ea.png">

# Changes 
According to the comment linked above: 
- highlight the dropdown when the user hits Find but did not select a form 
- ensure that No results found only shows when a form is selected that is empty, has no data submitted to it

**Comment by Maseline** [comment]
Test plan
Navigate to inspect data tab
Select the find option without setting any survey, notice a red border added tothe area around the select field
Next, select all the required surveys/form and select Find, notice that results are returned and the red border is removed
In another scenario, try selecting only some of the surveys but not all, notice the red border is still added.

**Comment by janagombitova** [comment]
Handled in #2455
