### ISSUE TITLE
Indicate form must be selected in Data cleaning tab

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2456]
# Context
Based on the discussion here: https://github.com/akvo/akvo-flow/issues/2380#issuecomment-360069140 we have agreed to streamline how we show users that they need to select a survey/form before completing an action. 

In the Data cleaning tab tab the user must select a form to be able to export data or import data. Currently if she does not select anything and hits 'Download' we do not show anything. If she hits 'Import' without selecting a form we show her a pop up message. 

<img width="1116" alt="screen shot 2018-01-24 at 10 33 19" src="https://user-images.githubusercontent.com/12456965/35324767-06f3d094-00f2-11e8-826e-de9098209cf9.png">

# Changes 
According to the comment linked above: 
- highlight the dropdown when the user hits Download or Import but did not select a form 
- remove the pop up message currently in place

**Comment by Maseline** [comment]
Test plan
Navigate to the data cleaning tab under Data.
Hit the Download option without selecting the surveys. 
A red border should appear around the survey selection area.
Select all the required surveys and form and hit the download option, the red border should be removed

**Comment by muloem** [comment]
@bogere This issue is not actually handled in https://github.com/akvo/akvo-flow/pull/2871 so we have to reopen and resolve the conflicts in https://github.com/akvo/akvo-flow/pull/2859 before merging

**Comment by valllllll2000** [comment]
works as described!
