### ISSUE TITLE
Improve copy on Bulk Upload page

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2462]
# Context 

## How things work currently
Once data collection happens offline, Flow users use Bulk upload to get the data out of the devices and into Flow. A simple workflow is outlined below. Salim takes the entire data file from the app and puts it into Flow. Flow then checks to which form the data belongs and which data is already synced in (part of the data set).  

## Who
Even though data collection offline is done by Alphonso, it is Salim actually getting the data out of the device and into Flow using Bulk upload.

## Workflow
1. Alphonso captures data offline on his device 
2. Once data collection completed he comes to the HQ where usually Salim takes the phone as he has access to Flow's instance
3. Salim plugs the phone to the computer not turning the phone online and sees the public files > akvoflow > data
4. Salim copies the data file to his PC and makes a zip file out of it
5. Salim in the Bulk upload page on Flow's instance drops the zip file
6. He sees a progress bar and then gets a message to check messages 
7. Salim checks in Messages the status 
8. Salim checks via Inspect data or exports if the data (captured offline) is now part of the data set  
 
![bulk](https://user-images.githubusercontent.com/12456965/35435375-bf86bbe6-028a-11e8-8424-f2d567465c87.gif)

# App file storage changes 
As explained in these two issues https://github.com/akvo/akvo-flow-mobile/issues/977 and https://github.com/akvo/akvo-product-design/issues/287 we are changing how data is stored on devices, moving the files from a public folder to a private one. Salim will now have to trigger in the app to make the files available in the public folder to be able to bulk upload them into Flow. 

# Opportunity 
Because we are changing how Salim can get the files out of the app and into Flow, we decided to communicate this change in two spots. On the app once Alphonso updates the app, so he knows about the change, with a simple and brief walkthrough page. Secondly, on the Bulk upload page, so Salim (who is actually doing the task) also knows about the change. 
  
# How might we convey the message  
We want Salim to: 
- understand where he needs to get the files from on the app 
- understand what he needs to do

**Comment by janagombitova** [comment]
As a first step we will clean up the current UI and the second step will be to add a walkthrough to the page, once the implementation is ready. 

The 1st step can happen already now as it does not depend on the work on the app and is only related to simplifying the content on this page. 

<img width="1267" alt="screen shot 2018-01-31 at 15 50 47" src="https://user-images.githubusercontent.com/12456965/35629302-8c273f6a-069e-11e8-91a3-28f34f9b6f1f.png">

# Changes 
* [ ] change the copy in the middle of the page to `Drag and drop here to upload or Browse` 
* [ ] `Browse` is the clickable link that opens the computers file system 
* [ ] Remove the "Do not navigate away from this page while the upload is in progress" from the page fully 
* [ ] Add  zip file icon above the text as according to the designs below. 

<img width="858" alt="screen shot 2018-01-31 at 15 55 36" src="https://user-images.githubusercontent.com/12456965/35629551-35eeaac4-069f-11e8-98b1-f374bb01d971.png">


The bulk upload page has a few more improvements it needs, as file validation etc and these will be handled in other issues.

**Comment by Kiarii** [comment]
there is one behaviour to add to the drag and drop section: when the file is dragged onto it, the border should turn blue (Flow's primary color) momentarily to show its acceptance of the action - if static at all times, it looks like an inactive element..

**Comment by kymni** [comment]
To add on this, in the previous implementation hovering a file on the drop area before dropping would trigger a style change in the area to highlight where to drop. The style would however not revert when you hover the file away from the drop area which I suppose was a bug. Should this be replicated with the new styling and the bug fixed?

The drop area also accepts files of any type which should probably not be the case. If the dropped file is not a zip file, the browser throws a type error. We should be at least notifying the user via an error message on the dashboard if they've dropped the wrong file. If you however drop a random zip file, it is accepted for processing and the message tab outputs a message saying the file has been processed. Given that invalid zip files should fail, the message tab should output a descriptive error message. 

We ought to handle the above in separate new issues

**Comment by janagombitova** [comment]
@muloem What do you think of me testing out these changes on UAT2 while you continue with the review in the mean time?

**Comment by janagombitova** [comment]
Tested on UAT2 and all looks and behaves correctly and as expected. Well done @bogere with the drag and drop work. Can be reviewed and prepared for the E.. E.. release

**Comment by janagombitova** [comment]
Partially completed and the rest will go with the big bulk upload GDPR changes. This is ready to roll 👍
