### ISSUE TITLE
Do not allow moving or copying survey to root folder

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#2464]
Currently it is possible to move a survey to the root folder. This should not be the case. Copying a survey also allows you to paste on the root folder but throws an error 500. 
Disable ability to move or copy a survey to root folder

**Comment by janagombitova** [comment]
The fix works, however, I find the user experience odd and confusing and would like to get @Kiarii and @loicsans option on this: 

![copy](https://user-images.githubusercontent.com/12456965/36678331-bde8c75e-1b10-11e8-960c-93002b6414dc.gif)

# Context
It was possible to copy a survey or move a survey to the root folder (home) what should not be possible as user roles are always linked to a folder and having surveys living outside of folders may result in a user not seeing the survey until it is moved to a folder. 

# Issue 
@kymni made a fix to not allow the user to move a survey from one folder to the "home" folder or copy a survey and the paste it in the "home" folder. However this change resulted in an odd user experience in my option. 

Salim decides to copy a survey and paste it in another folder he has access to:
1. He hits Copy and sees in the top of his screen a window indicating what he is copying with the action buttons
2. To navigate to another folder he hits the "home" button in the folder path and suddenly the copying window disappears 
3. He selects the next folder where he wants to paste the survey and the copying window shows again. 

@Kiarii and @loicsans what do you think?

**Comment by janagombitova** [comment]
I was thinking about this one (as it needs to go into next weeks release) and how about keeping the copying/moving window visible at all times, but when in the root (home) folder disable the copy/move button. Would this be possible?

**Comment by kymni** [comment]
With some css I, I believe it should be possible. Same way the create survey button is disabled while in the root folder.  Looking into it

**Comment by janagombitova** [comment]
Wonderful. works like a charm now and is not confusing! 👍 ready to release
