### ISSUE TITLE
Move Monitoring tab after Inspect data tab 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2467]
# Context

Despite the large redesign idea we have for Flow we can make a slight change in the layout of the pages already now, to have them a bit better organised. 

Under the Data tab we have: 
- Inspect data and Monitoring tab - for viewing data 
- Bulk upload and Data cleaning tab - for importing in data 
- Cascade resources 

# Change 
Move monitoring tab after Inspect data, to we have the two viewing tabs next to each other and the two importing ones next to each other.

**Comment by Maseline** [comment]
![issue2467](https://user-images.githubusercontent.com/3306929/35723983-3e3e9b20-080d-11e8-8db6-179407ad8c26.png)

**Comment by Maseline** [comment]
Test plan
Navigate to Data tab.
Notice Monitoring is right after Inspect data in the sub navigation

**Comment by janagombitova** [comment]
SImple, small but powerful 👍
