### ISSUE TITLE
Empty questions cannot be changed in data preview

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#247]
The data preview tab shows the questionAnswer objects of a surveyInstance. If a questionAnswer object is empty, it cannot be selected to edit it.

**Comment by janagombitova** [comment]
Is dealt with in https://github.com/akvo/akvo-flow/issues/247 Closing this issue

**Comment by muloem** [comment]
@janagombitova I guess you meant will be dealt with in #1526

**Comment by janagombitova** [comment]
haha, yes! something went wrong in my copying.
