### ISSUE TITLE
Validate file type for Bulk upload, bring import to the page and change UI

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2471]
# Context 
With GDPR we are changing how we handle files in the app and this has some consequences to the UI on Flow's web. With designing the changes we realised that Flow does not currently validate the file type, the success of the upload is shown in the Messages tab even though the process is relatively quick and the UI is unnecessarily complicated. 

Here is a mockup of the changes proposed (all of them in one): https://projects.invisionapp.com/share/ZJFL5Q4VQUG#/screens/276279057

# Opportunities 
<img width="1170" alt="screen shot 2018-02-02 at 14 13 19" src="https://user-images.githubusercontent.com/12456965/35809608-874a1e38-0a89-11e8-8c73-2bdd0e13dd7d.png">

There are a few things we aim to achieve with these changes: 

## Simplify what is shown
The current UI has a lot of elements in it that duplicate the message. The information Salim needs to see is: where to drop the file, which file he used, if it is ok, if the bulk upload is progressing and the result of the task. We currently have a progress bar showing progress but also a text explaining progress, and uploading written under the bar. The UI can be simplified. 

## Show everything in the page
We want to keep the user on this page till all is done, to reduce the times he needs to switch through pages on Flow and also because the task is done quickly (a few seconds only) and we should inform him about everything he needs to know at that moment. 

## Show what is happening 
Bulk upload is not a frequently done task. We need to ensure Salim knows what he needs to do to be successful, but also that he understands what Flow is doing and what the status of things is. 

## Decrease noise in Messages tab
The idea is to stop sending the end result to the Messages tab, but show the success or failure directly in this page. We can then reduce the number of times the user has to go from one page to another to see the result of his action. This way we move towards showing results where they happen is the waiting time is small.  

# Changes

UI designs here: https://projects.invisionapp.com/share/ZJFL5Q4VQUG#/screens/276279060

Some of the changes already have their smaller issues (for the new UI where the user drops the file: https://github.com/akvo/akvo-flow/issues/2462 and for the new walkthrough: https://github.com/akvo/akvo-flow/issues/2466) 

This issue should: 
* [x] Add file validation to the process. Once the user drops the file check if it is a zip file. 
* [x] Redesign how the upload of the file and the checking looks like according to the mock up (file name on the side and a loading spinner with the text `Checking file...`, no large progress bar)
* [x] If the user drops in a pdf, jpg, docs, basically anything that is not .zip we should stop the process of uploading the file and show `Unsupported file format. You can only upload .zip files.` and the exclamation mark error icon.
* [x] Once file is checked and uploaded show the next step of the process, actually getting the data out of the file and saving it - in the UI this is shown with a progress bar and the text `Uploading...` This should be sufficient for Salim to remain in the page and not navigate away. 
* [x] Once the full bulk upload is done, show the green tick
* [x] If more than one file is added make sure the status of each is shown correctly and in sequence so Salim understands that while one file is checked and being uploaded the 2nd one is being checked now
* [x] Do not send a message to the Messages page about the success of the upload, as we show it in the UI to Salim already. 

![image-4](https://user-images.githubusercontent.com/12456965/35804496-645e5274-0a78-11e8-9238-052968aac2bf.png)

# Order of work: 
As some of the changes are dependent on changes in the app, not all need to be implemented at once. This change and the change for the new UI where the user drops the file: https://github.com/akvo/akvo-flow/issues/2462 can happen now. 

The new walkthrough: https://github.com/akvo/akvo-flow/issues/2466 will be release together with the app changes.

**Comment by janagombitova** [comment]
There is one UI change that we want to make based on the user testing: Once the file is completely and successfully uploaded besides showing the green tick we also state `Uploaded` to make is clear that everything is now completed and the data upload is fully done. When testing this option was considered more persuasive and informative by the testers. 

![screen shot 2018-03-16 at 14 36 54](https://user-images.githubusercontent.com/12456965/37523595-b6e3e874-2927-11e8-9d2a-b5bfc88a8498.png)

**Comment by bogere** [comment]
## Test plan
** Click on the data tab and then click on bulk upload data tab.
** Add a file by dragging and dropping it  on the drop zone or browsing through your computer to pick the files.
** if the file is not of zip file format, you will see the red text of "Unsupported file format. You can only upload .zip files." which shows file validation process
**  Immediately after dropping the file, you will see the progress bar length moving witnessed by green color covering the yellow color.
** You will also see the uploading... text with percentage of the current file upload progress.
** After progress bar has moved completely to the end, you will see  green tick icon with uploaded text that shows that file upload has completed.

**Comment by janagombitova** [comment]
@muloem What do you think of me testing out these changes on UAT2 while you continue with the review in the mean time?

**Comment by janagombitova** [comment]
# Notes from testing on uat2

Here are some pointers to what needs to be improved: 

## General UI elements
- in the mock ups you can see that the file name (or the unsupported message) is supposed to be aligned to the left and the status (uploading, exclamation mark, check mark and uploaded) on the right, now everything is centred on the screen 
- 'Do not navigate away from this page while the upload is in progress' should not be on the screen at all anymore - fully remove this element 
- the progress bar belongs to the file - it should show in the box  with the file - now it seems as a separate element above the files. So if I upload one zip file after another I will see two progress bars depending on the file
 
## Uploading when correct file type 
- I drop in one zip file, in the UI I see two entires, where one says Uploaded and the other is frozen in Uploading 100% --> there should be only one entry if I drop one zip file

![screen shot 2018-03-29 at 16 07 19](https://user-images.githubusercontent.com/12456965/38093450-4a552ad0-336b-11e8-823d-d374cbadd4f6.png)

## Validation of the file type 
- after trying to upload a wrong file format I should still see the file name and type and under that the message that it is unsupported (all aligned to the left) and the exclamation mark should be on the right of the screen - please refer to the mock ups 

![screen shot 2018-03-29 at 16 13 24](https://user-images.githubusercontent.com/12456965/38093806-5475abe2-336c-11e8-95ef-bbc38e12a38b.png)

- if I first upload a correct file and then a wrong file (a pdf) uploaded for the correct file turns red, it should remain green 

![screen shot 2018-03-29 at 16 12 16](https://user-images.githubusercontent.com/12456965/38093712-10bc4960-336c-11e8-89a1-59d8a11efc06.png)

# Messages 
- these should be fully removed, but they keep on showing in the list

**Comment by janagombitova** [comment]
File validation works like a charm the the UI is also improved. In other issue we will remove the messages. This is ready for release 👍 

<img width="1009" alt="screen shot 2018-04-18 at 14 02 29" src="https://user-images.githubusercontent.com/12456965/38930796-685dab96-4311-11e8-91cd-bc94345c7e0b.png">

**Comment by janagombitova** [comment]
In the regression testing it seems that these changes affected Data cleaning import. Data cleaning import should have remained untouched. 

<img width="1028" alt="screen shot 2018-04-18 at 14 24 24" src="https://user-images.githubusercontent.com/12456965/38931659-39107924-4314-11e8-8c83-990095a48337.png">

**Comment by kymni** [comment]
File type validation should now be restricted to the bulk upload tab only. Note however that the uploader is global so the uploader styling changes reflect on both the cascade resources and data cleaning

**Comment by janagombitova** [comment]
Works well now. 👍
