### ISSUE TITLE
Change how variable name validation error message is displayed

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#2474]
Currently the variable name validation error message is hard-coded on the end-point. Change this so that the displayed message is pulled from transifex

**Comment by kymni** [comment]
### Test plan
* Confirm that a string '_variable_name_validation_failure_reason' for handling variable name validation error message exists
* Confirm that all instances of question ID on the dashboard are now replaced by variable name

**Comment by stellanl** [comment]
# More test plan:
The variable name occurs at many places. We need to make sure it still works everywhere, both old and newly set variable names.

- Test setting some and check that displaying a mix of them in the UI still works.
- Test that copying a survey copies the variable names correctly.
- Test that both old and new variable names are shown correctly in report headers.

**Comment by janagombitova** [comment]
Found a problem: 

Before we had two variable name error messages:
- not unique 
- containing characters we do not support 

Now the not unique message is showing also when it should show that the variable name contains characters that we do not support.

<img width="470" alt="screen shot 2018-03-06 at 09 12 39" src="https://user-images.githubusercontent.com/12456965/37021086-9497dade-211e-11e8-92ba-738c7a95b389.png">

**Comment by janagombitova** [comment]
All good now 👍
