### ISSUE TITLE
Indicate geoshape question must be selected in Export reports tab

### ISSUE THREAD

**Issue by Maseline** [akvo/akvo-flow#2479]
Currently under the Export reports tab, the last step to download Geoshape data is to select a geoshape question.
When a user hits the download option without first selecting a Geoshape question, a pop up notification with a message to select a form or question is displayed.

**Changes**
In relation to issue #2380 comments:

- a red border should highlight the select question drop down when a user hits Download but did not select a question

**Comment by Maseline** [comment]
Test plan
Navigate to Export reports tab, select surveys and form for Geoshape data.
Hit the download button without selecting a question.
Notice that the border color changes to red.
Select a question and hit download again.
Notice that the border color now returns to the original color

**Comment by janagombitova** [comment]
Released with 1.9.38
