### ISSUE TITLE
How and where do we show folder > survey > form paths in the UI 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2507]
# Context

We currently show the folder > survey > form path of a submission in multiple places in Flow's UI. The problem is that this path does not reflect change. If the user renames the form, the survey, the folder or if he moves the survey to a different folder, these changes are not shown. 

For Salim in some cases this is useful information to quickly see what belongs where or to distinguish between submissions. 

# Opportunity

With this issue we want to: 
1) look at cases where we show the folder > survey > form path in the UI, see if showing this info there is valuable or not - keep it or remove it 
2) create a solution where the path is showed in a unified way and stays up to date reflecting changes made to its components 

## Current places in UI with folder > survey > form path

- In the Inspect data tab when Salim views a specific submission we show the path in the top of the pop up box. 
- In the Monitoring tab when Salim view all the submissions made to a data point (list of submissions to the different forms of the monitoring survey) 
- In the User list under Roles, where Salim sees which Role the user has on which folder, survey and or form 
- When viewing details of a specific user, when Salim adds a role to a particular folder, survey and or form, he sees the path in the table under Resources. 
- In Messages tab
- in the new page where we will show generated data exports to make it easy for Salim to see which export was based on which form

## Usefulness of showing the path in these places 

place | useful? | why?
--- | --- | --- 
Inspect data tab | no | Salim already selected for which survey and form he wants to see the submissions, there is no need to show him this information twice 
Monitoring tab | yes, partially | As the submissions to the data point can be from different forms of the survey, Salim needs to be able to see which form the submission in for. Showing the entire path is not useful though. It is enough to only show the form name.
User list | yes | In this table Salim can easily and quickly see which role a user has on which folder, survey and/or form. 
Individual user page | yes | When assigning roles Salim needs to see to which folder, survey, and/or form he has given the user a particular role. 
New Exports page | yes | As Salim will see in this list all the exports he has made in the last year, he needs to easily see to which folder > survey > form the export is made from. The whole path is needed as sometimes users copy a survey to use in their region (folder) but do not change the name. So he needs to know which survey form the export is from specifically.   

# Existing related issues
- The `path` property of a SurveyGroup and Survey are not updated correctly during autosave - https://github.com/akvo/akvo-flow/issues/1019
- In Monitoring tab cannot see difference between monitoring form and registration form - https://github.com/akvo/akvo-flow/issues/2388
- Data instance edit box shows path - https://github.com/akvo/akvo-flow/issues/2103

**Comment by kymni** [comment]
@janagombitova in the inspect data tab, we currently display the selected submission path as `<path>/<formId>/<submitter>`. Do we remove the `<formId>/<submitter>` part as well?

**Comment by janagombitova** [comment]
@kymni do you mean here (see image below with the red box)? If yes, then in my opinion that entire path is not needed to show. 

![screen shot 2018-10-16 at 14 57 53](https://user-images.githubusercontent.com/12456965/47017983-f2280580-d153-11e8-80e3-69269d1ccfdc.png)

**Comment by valllllll2000** [comment]
there is no longer a path in the inspect data tab, not sure if that is the only place to test @kymni

**Comment by kymni** [comment]
@valllllll2000 that and on monitoring tab under the `Form` column which should only have the form name instead of a path

**Comment by valllllll2000** [comment]
All ready
