### ISSUE TITLE
Geoshapes not showing in Inspect data tab

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2512]
When I submit a geoshape and then want to view it in the Inspect data tab I get an error in console, the shape does not load neither the map and the loading spinner keeps on loading. 

On UAT1 you can find an example under _1.9.29 and 2.4.6 > 1.9.29 All questions (no monitoring) > 1.9.29

<img width="1268" alt="screen shot 2018-02-26 at 15 15 48" src="https://user-images.githubusercontent.com/12456965/36674995-0b423a2a-1b08-11e8-841b-0d0b2694b271.png">
<img width="1268" alt="screen shot 2018-02-26 at 15 16 01" src="https://user-images.githubusercontent.com/12456965/36674996-0b6a0082-1b08-11e8-8b30-8a9238293dbe.png">

**Comment by janagombitova** [comment]
Maybe related, maybe not, but on UAT1 I am not getting any Carto maps: 
<img width="1265" alt="screen shot 2018-02-26 at 15 19 49" src="https://user-images.githubusercontent.com/12456965/36675174-927a2f34-1b08-11e8-9450-c95832b29911.png">
<img width="1273" alt="screen shot 2018-02-26 at 15 19 42" src="https://user-images.githubusercontent.com/12456965/36675179-943a02b8-1b08-11e8-8e1c-5a237a92b425.png">

**Comment by kymni** [comment]
Issue should be fixed after merging hotfix

**Comment by janagombitova** [comment]
👍  all works as it should again. thank you
