### ISSUE TITLE
Use as data point location flag does not change with saving

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2517]
# Steps to reproduce: 

1. Create a geolocation question and Use as data point location is by default turned on
2. Save the question 
3. Open the question again and change the Use as data point location to **not** be selected. Save 
4. Publish 
5. Reload survey form and check question - use as data point location is turned on. 

This happens for any form (monitoring or registration) 

See example on UAT1 > _1.9.29.. folder > 1.9.29 All questions (now monitoring)

# Change

Ensure that if a user changes the setting Use a data point location, that is is properly saved and published. 

# Extra notes 
- This issue is only about the Use as data point location flag, as changes to Use as data point name work correctly.
- This issue might bring up the discussion around the current confusion, that you can set data point location on also in monitoring forms. This is not to be resolved with this issue but later once we start tackling monitoring as a topic.

**Comment by stellanl** [comment]
Seems to be this helpful code is a little too helpful: question-view.js L156

  // when we change the question type to GEO, we turn on the
  // localeLocationFLag by default. If we change to something else, we
  // turn the flag of.
  enableLocaleLocation: function() {
    this.set('localeLocationFlag', this.type.get('value') == 'GEO');
  }.observes('this.type'),

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-93665-from-bridget-dot-kelly-at-charitywater-dot-org

**Comment by kymni** [comment]
The locale flag is currently set to turn on by default when a question is set to type geolocation. To fix the issue, we'll change this so the user has to toggle the option themselves and also stop auto-checking this option in case of a disabled flag

**Comment by janagombitova** [comment]
Use as data point location is not set by default anymore and making changes is now well reflected also in the UI. All good 👍
