### ISSUE TITLE
Datapoint location can only come from registration form

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#2518]
## Steps to reproduce

Create a survey with 2 forms, each has location question and "use as datapoint location" is enabled in both.

**On the app**
Create a datapoint with registration form located in Spain, submit. 
Check that the datapoint is displayed in Spain. 
Answer the monitoring form and the location is in France and submit.
Check the map again and the datapoint should still show in Spain. 
Used the setting "delete collected data".
 
Sync the datapoints again. 
Now the datapoint shows in France 

**json data**
The response we get from backend, places the whole datapoint in France (the location of the monitoring submission)

## Expected
Json response should place the datapoint using location from the registration form only. Monitoring form location should be ignored for the datapoint location.

**Comment by valllllll2000** [comment]
## Test plan
Use the survey from uat1 which has 2 forms and both have a location question with "use as datapoint location" checked.
Create a datapoint with registration form located in Spain, submit.
Check that the datapoint is displayed in Spain.
Answer the monitoring form and the location is in France and submit.
Check the map again and the datapoint should still show in Spain.
Used the setting "delete collected data".

Sync the datapoints again.
Now the datapoint should show in Spain.

**Comment by janagombitova** [comment]
Newly created points show correctly where they need to show. If I have in the RF two questions with use as location set then we take the 1st question, what is good. So this is ready to roll 👍
