### ISSUE TITLE
Create a script to fix the datapoint location 

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#2520]
As explained here #2518, if a survey contains 2 forms or more and the forms that are not the registration form contain geo location data (even if the "use as datapoint location" flag is not set), the datapoint location data is overriden by the GEO question answer from a monitoring form. We need to fix this issue with a script.

if possible can we have it with a dry-run option so that we are aware what is the scale of changes that will be made

**Comment by valllllll2000** [comment]
## Test plan
Nothing to test here, just a script

**Comment by janagombitova** [comment]
@valllllll2000 as we have already used the script can we close the issue?
