### ISSUE TITLE
Handling captured photos' and videos' urls

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2522]
This issue possibly holds multiple changes. I have put it here so we do not need to switch repositories. If needed please break down the implementation to smaller separate issues. 

# Context 

With GDPR coming in force in May 2018 we started auditing how we treat personal data. We are looking closely on how we handle data of our users in our tools and how to handle the data our users capture in our tools, in Flow. 

We agreed that access to data must fully comply with one's given roles and permissions. 

## Why
Users capture photos to have a visual support of their data. They capture photos of the participant, of the subject of their data collection as the well, school, farm, of documents, etc. 

Afterwards the photos are used to validate the data, to add to their visualisations of the data to make the insights more attractive or the photos are added to reports and other outputs. 

## Issue 1 - viewing photos/videos in Flow
Currently in Flow, once a photo or a video is submitted to a form, the Flow users can see the item either on the app directly, or on the online workspace by clicking the link pointing to the photo/video. This link is also exported with the data set when a user exports data. Then anyone, regardless of their access to Flow, can copy the url, paste it in her browser and see the photo/video.

This situation then means, that anyone who gets the link, can see a photo/video captured with Flow without having access to Flow.

![34485165-62deee50-efc9-11e7-9ef2-9ad2313e581b](https://user-images.githubusercontent.com/12456965/36971007-b13aeee2-206a-11e8-8f64-11528b805e40.png)

## Issue 2 - using photos/videos outside of Flow 

Secondly, users have no way currently to get the captured photos/videos out of Flow and on to their machines for further use. 

Some partners open the photo one by one and then download the image from the browser. I also have the feeling our Technical account managers have a script to get all the photos submitted to a question out of Flow and into a file on the computer.   

# Opportunity

## Opportunity for issue 1 
We must ensure data captured with Flow is only accessible when logged in to Flow and following user's roles and permissions. 

How might we ensure we do not use the image urls but actually show the photos videos in the UI? How will we then handle the photo/video columns in the data exports to the image urls are not easily openly shared? 

## Opportunity for issue 2
Users want to be able to see the photos/videos they have captured with Flow without having to be connected to a network and want to store their photos/videos separately on their own devices. They want to be able to get a photo out of Flow and add it to a report or presentation.

How might we enable users to download all photos in a simple way?

# Other older related issues:  
https://github.com/akvo/akvo-flow/issues/1459
https://github.com/akvo/akvo-flow/issues/683

**Comment by stellanl** [comment]
Some approaches to issue one: 

1. Make an endpoint in GAE to act as a proxy for the S3 images. It already has libraries and keys for picking up the rest of the submissions.
2. Hand out some sort of (time-limited?) session token for S3 to the user's browser.
3. Stop storing the images on S3 at all. Keep them in some kind of GAE storage bucket or the database itself.

**Comment by janagombitova** [comment]
Today we spoke with @stellanl @muloem @Kiarii about how users use photos and videos and what we can do and how we can secure these files. We agreed to do the following: 
- first start with securing the files 
- then handle downloading them 

Here are some follow up actions: 
* [ ] Jana check what the oldest app version are out there 
* [ ] Mulo and Stellan will bring in Valeria to agree on a strategy on how to secure photos and videos so they are still accessible to view in the app and then create separate issues 
* [ ] change implementation to show photos and videos in Flow when viewing the data (Inspect and Monitoring tabs - as maps already show the image preview) so user does not have to click on the links
* [ ] Jana and Kiarii research how photos are used outside of Flow so we can better understand how to go about allowing to download them (especially keeping the size constraint in mind)

**Comment by janagombitova** [comment]
# Status update on the research 

## Flow app version active in 2018 
I used data from 18 January 2018. We have some v1 apps out there, as well as newer. Below you can find the overview of the v1, and in the linked sheet the entire breakdown: https://docs.google.com/spreadsheets/d/109KWRNr4iCBzrp-SyA5qAklkah60QHoLTW6vx_heZJQ/edit#gid=683173039

Flow app version | number of devices 
-- | --
1.10.0 | 1
1.10.5 | 4
1.12.0 | 1
1.12.1 | 2
1.13.2 | 1
1.13.3 | 4
1.13.6 | 1
1.13.7 | 3
1.13.8 | 5
1.15.10 | 1

# How are photos and videos used outside of Flow 
We will start with an internal research talking to support and partnership team members in direct contact with partners. All the information will be gathered here https://docs.google.com/document/d/1G088KysnI1H7RBsL9YRSQojfhdvg_neLJhz8WgcBL4g/edit and main findings summarised in this issue once completed.

**Comment by stellanl** [comment]
For solution option 2. I believe this function should be helpful:
com.gallatinsystems.common.util.S3Util.getBrowserLink(String, String)

**Comment by stellanl** [comment]
What is a reasonable lifetime for an image URL?
When you get it you are logged in, but how long do you expect it to work after you view the picture? If we set it too long, then sharing the URL to other people appears to work, only to stop suddenly. I guess the UI could make a call to the backend saying "get me a 1/5/60-minute URL for this image" instead of caching it.
