### ISSUE TITLE
We could store *who* changed a datastore entity

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2525]
Currently we store time of creation and time of last modification for most entities. We could add a field for which user (last) did it.
For developers, this would help with investigating support issues.
For users, displaying this would help when more than are working on a survey.

**Comment by muloem** [comment]
@stellanl this field actually exists but was not actively used.  I think its a great idea indeed to store that
https://github.com/akvo/akvo-flow/blob/04d156aa376ac138e6ed833ed21fece8ae9c8159/GAE/src/com/gallatinsystems/framework/domain/BaseDomain.java#L49

**Comment by janagombitova** [comment]
@stellanl I guess there is nothing here to test from the users perspective. Correct? Anything I should check elsewhere?

**Comment by stellanl** [comment]
If you want to , you can see them being added to the entities in the datastore, but no, no user-visible part (yet).

**Comment by janagombitova** [comment]
Hey Stellan, I checked in the data store randomly around some entities but the Create User ID has entires to it for the most recent things. However the user ID is a number. Is this expected? Is there a difference in how users (visible in the UI) are logged and in how us super users are logged? 

<img width="706" alt="screen shot 2018-03-29 at 09 06 29" src="https://user-images.githubusercontent.com/12456965/38074839-85ea7950-3330-11e8-953a-58114d3adff1.png">

**Comment by stellanl** [comment]
Yes, the userIds are references into the user "table", for all kinds of users.
That's not a change, the fields have been around for years, but were not filled in.

**Comment by janagombitova** [comment]
Ohh ok. Now it makes sense. Then I assume all is at it should be and we are ready to release this.
