### ISSUE TITLE
Submission lists remains on Monitoring tab after navigating away and back

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2531]
Similar to this issue: https://github.com/akvo/akvo-flow/issues/2372 the same happens for the Monitoring tab. The expectation is that once I go away from the Monitoring tab and then come back I will have no data points listed in the screen as I have not selected my survey yet and hit find. 

<img width="1255" alt="screen shot 2018-03-07 at 10 09 34" src="https://user-images.githubusercontent.com/12456965/37083390-a279e3c8-21ef-11e8-8592-9f8ab4e3de82.png">

**Comment by bogere** [comment]
### Test plan
*  navigate to the monitoring-data-tab
* select the survey forms whose submission lists you want to see and click the Find button
*  Submission lists for a specific survey form are shown
* Navigate to another page like clicking on survey tab or message tab or any other navigation  tab
* when you come back to monitoring-data-tab, you wont see the submission lists

**Comment by janagombitova** [comment]
@bogere I found one odd case when the lists still comes back. Here are the steps to follow: 

1. go to monitoring tab and select a survey with data 
2. open up one data point to view 
3. close the window with the submissions 
4. go to inspect data tab --> here you will see a list of one or more submissions.

**Comment by janagombitova** [comment]
👍 lists do not show anymore. Ready to roll
