### ISSUE TITLE
Make a datascript to check and trim DeviceFileJobQueue

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2536]
The "/devicenotification" endpoint can hit the 60s ceiling if the DeviceFileJobQueue table gets big enough. One solution is to discard devices (and their associated DeviceFile entries) that have not contributed in a long time.

**Comment by stellanl** [comment]
The problem was simplified by splitting the fix into two parts:

1. A script to fix the bad filenames in DFJQ entities.
2. A script to check/retire old/bad DFJQ entries, to be run *after* script 1.

Running of these should ideally wait until the #2539 fix has been released, or there may be bad data left.
An exception was made for the WfP instance, since the 150k-long DFJQ table was killing performance.

**Comment by janagombitova** [comment]
@stellanl and @muloem is this one also completed and ready for the release?

**Comment by muloem** [comment]
@stellanl if you could clean up the code to remove commented out code that is not used then we are good to go. 👍

**Comment by janagombitova** [comment]
Are we good to go?

**Comment by stellanl** [comment]
Now we are

**Comment by janagombitova** [comment]
Perfect!
