### ISSUE TITLE
Make a tree overview of the survey structure for debugging

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2537]
As an experiment, I want to make a very simple endpoint that returns the survey structure as a tree view. It could also include "lost" items to make finding them easy with out having to run a datascript. I intend to restrict it to superadmins only.

**Comment by muloem** [comment]
Just as a comment, if its for debugging purposes, I would rather we create it outside of the application space so as to avoid having any issues that may be related to this endpoint affecting the application.  I recall we already had a datascript for this that you made right?
