### ISSUE TITLE
Research and implement a tool/alerting mechanism to GAE logging

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2538]
# Context 

Currently we have no way of knowing if an error happens in Flow (not Flow app where we have Sentry). We can only go into an instance and search through the logs to find if something is going wrong. This is a painful process and does not help us to be preventive and more proactive. 

# Idea 

We should research what kind of tools/alerting mechanisms are available (inside or outside of GAE) to help us keep an eye on system health.

What are your thoughts? @muloem @stellanl @valllllll2000 @kymni @Maseline @bogere

**Comment by valllllll2000** [comment]
Just to clarify: my suggestion was to use the sentry api for the errors we get on devices and somehow integrate a special notification when lots of devices start sending this kind of error, and in any case I would have to do a little trick on the devices as for now the exceptions are mixed 500 and other 400s as we do not distinguish between them and sentry counts it as the same error. We could add this not only device notifications but other api calls done by the app.

**Comment by janagombitova** [comment]
I briefly spoke with @dlebrero about error reporting for GAE and he suggested to use what GAE provides rather than adding another tool. So I decided to test and turned on **Stackdriver's Error Reporting** notifications for my email. 

https://cloud.google.com/error-reporting/docs/notifications

# To turn on the notifications
You can either go through each instance and turn on notifications for your email or  from the GCP Console's User Preferences page or from the GCP Console app's Settings > New error notifications page. 

# Error notification emails
Stackdriver Error Reporting sends a notification in two cases:
- When an error occurs in a project and it cannot be grouped with previous errors. Note: Error Reporting only sends notifications for the first occurrence of an error.
- If an error that was marked as Resolved reoccurs.

# Next steps 
I would like to suggest we give Stackdriver's Error Reporting a try for a few months. After that we evaluate if we feel more informed on errors happening on the instances or not and consider next steps. 

Everyone who wants to receive the notifications on errors need to turn them on themselves. 

@muloem @stellanl @valllllll2000 @kymni @Maseline @bogere What are your thoughts? Do you agree?

**Comment by janagombitova** [comment]
We use Stackdriver now.
