### ISSUE TITLE
Bad filenames being entered into DeviceFileJobQueue

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2539]
In org.waterforpeople.mapping.dao.SurveyInstanceDAO.save() the filenames added to the DeviceFileJobQueue are not extracted from the JSON package they nowadays come in; they end up looking like:

> 630e1777-d6c9-45c7-8b96-50ba17456408.jpg","location":{"accuracy":11.5,"altitude":120.5,"latitude":-16.35772,"longitude":34.6957768}}

**Comment by stellanl** [comment]
This is probably contributin gto the #2636 problem, as the devices will get

1. Very long filenames that
2. Will not match any (image) files, so
3. The DeviceFileJobQueue will just grow and grow.

**Comment by stellanl** [comment]
Test plan:

1. Submit a survey with an image.
2. Use the GAE console to look in the QuestionAnswerStore "table" and check that the filename is valid.

**Comment by janagombitova** [comment]
@stellanl I just followed your steps in the Test plan and this is what I see in Console. Oddly the last entry is from yesterday. Is that ok? I am new to this part of Console. 

<img width="1259" alt="screen shot 2018-03-28 at 14 38 21" src="https://user-images.githubusercontent.com/12456965/38029277-b879be26-3295-11e8-8cd3-b7d7417f92d2.png">

**Comment by stellanl** [comment]
No, that is a broken filename (See the "} at the end?) It's supposed to be "naked".
An image filename is checked for 3 times, at 5-minute intervals, before giving up and creating a DFJQ entry.
So it will be at least 15 mins after the upload until a DFJQ entry shows up.

**Comment by janagombitova** [comment]
@stellanl I checked again this morning and my entry from yesterday does not show up in the table.

**Comment by janagombitova** [comment]
@stellanl can you please do a 2nd test for me - just to be sure it works as it should? Thanks
