### ISSUE TITLE
Shorten the list of Devices 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2542]
# Context 

Currently in Flow's Devices list we should the devices connected to the instance with the latests connected one on the top. This list goes all the way back to when the 1st device was connected to Flow. 

# Issue 

The users managing the devices do not need to know who connected to the instance in the long past. 

# Idea 

We can consider to only show entries in the list that go up to 2 years or even a year. 
Would this decrease pressure on the performance? Speed up things?

**Comment by stellanl** [comment]
I see two main strategies:

1. Show only the most recently seen devices in the UI, at least for a first page.
2. Retire devices after a suitable time elapses without them having been seen. 

For both solutions we need to make sure that the criterion for "seen" is good enough. The location beacon used to be that, but is now off by default.
We may want to also bump the lastLocationBeaconTime field of devices for other signs of life, like submission of a survey, calling /deviceinfo and synching data.

If we retire devices, that lets/forces us to also retire other data connected to them, such as survey assignments and DeviceFileJobQueue entities.

**Comment by muloem** [comment]
@janagombitova @stellanl Since we are intending to move to users anyway can we save this effort and then just get rid of the devices altogether?

**Comment by janagombitova** [comment]
Yes, that is also an option. This issue was a quick reaction to the /deviceNotification performance issue. 

If the fixes @stellanl has made resolve the problem and this issue will not have any major beneficial effects, then we can drop it.

**Comment by janagombitova** [comment]
closing this issue as we have implemented the change where we only show devices connected in the last year
