### ISSUE TITLE
New design for failure to generate an export 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2543]
# Context 

With #2505 we are introducing a page where Salim will be able to download his generated data exports from, instead of the emails. This change will help us: 
- be GDPR compliant; 
- stimulate more responsible data handling as data is not so easily shareable (not already in your email); 
- enable Salim to re-download the data export if he just wants the same file again 
- support a cleaner UI where information (status updates) are shared with Salim directly in the page he is in, without having to navigate to different parts of Flow or his email 

# Opportunity 

With these changes we also want to improve how we communicate to Salim that Flow cannot generate the data file, for one reason or the other. Currently we only say when file generation fails immediately using a pop up message right after Salim hits the Generate button. We do not tell Salim that the generation has stopped because of something "wrong" with the form structure, for example. 

# When can export generation fail and how quickly does Flow know

Generating a data file can fail for multiple reasons: 
- Flow services is down - we know right away 
- A question in the form does not have the question text - after a while: https://github.com/akvo/akvo-flow/issues/2433
- A bug in the report engine (that we did not find in testing) causes a crash.  
- if the Caddisfly test type was not selected (i think) 
- other.. 

# ~General failure~

~If Flow services is down for some reason, or generating the file fails right away we should show the message directly in the UI, where Salim is. This shows right away after hitting Generate.~ 

<img width="927" alt="screen shot 2018-03-16 at 16 47 19" src="https://user-images.githubusercontent.com/12456965/37530382-b0ce8c66-2939-11e8-83e3-25ccf48c985d.png">

## Failure to generate for specific form 

If generating the file fails after a few seconds for a specific form related reason, we bring Salim to the Generated exports page and then show a form specific error message. This should hold the form name and reason for failure for Salim knows what he needs to change or adjust to make the export work. 

<img width="957" alt="screen shot 2018-03-16 at 16 50 09" src="https://user-images.githubusercontent.com/12456965/37530568-29508da6-293a-11e8-985f-c271f2776781.png">

# Next steps 
What are the reasons for an export to fail?

**Comment by muloem** [comment]
From our discussion during the task planning session, we figured that since the architecture for report generation is changing (see #2544) we will not be sending report generation requests directly to Flow services so generic errors e.g. involving Flow services not being up and running, will not occur.  

However, that doesn't mean the GAE platform will always be reachable.  So we still need to include error notification, to be implemented as part of a wider pattern to stop using popups and instead have an error notification area within the workspace. (we will handle this in a separate issue #2708)

Regarding the errors that occur when generating a report, we agreed its cleaner to have each error report highlighted within the list rather than above the list as in the mockup above, possibly with a retry button to enable the user to simply request the failed report again.

@janagombitova @Kiarii @stellanl @kymni

**Comment by janagombitova** [comment]
If we can be very specific on what caused the error, so Salim knows if he needs to change something in the survey definition or just wait, (could also be in a later iteration) then I think this is a good idea.

**Comment by janagombitova** [comment]
@Kiarii can you revise the design based on the discussion we had here above so we can push this issue to implementation? Thanks

**Comment by Kiarii** [comment]
me sees the point, however me point of view here was that an error is not a generated report; it is more of a notification if anything. Bunching it up with the reports introduces some confusion incl. the misconception with the timestamp, e.g. does it stand for when an error occurred or when a report was generated and when does it change between the two.. The RETRY we could do on the rhs of the notification as with material Snackbars

**Comment by janagombitova** [comment]
Today we released changes where we show an error message in the place of the URL to download the export. I am reopening this issue as it contains further improvements we can and should consider, from UI improvements to what type of errors we can have and how should we show them. 

However, Flow poses some limitations (notes from a Zulip conversation): 
* we don't have messages that can be dismissed in Flow Dashboard
* the error message can't be translated, similar to the Messages tab .. those are system messages that users can't read in their preferred language
* in the Reports tab, you get a full history of your exports, meaning that you'll get there also all the failed reports
