### ISSUE TITLE
Delete export files that are older than a year

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2546]
# Context and why
In Flow services we currently store all data exports (downloads) and reply of GAE for backups. Storing everything from the beginning of time takes up space and these files are not used. 

Currently Salim downloads his data via the url sent to him via email. From the user research we learned that Salim does not re-download data exports because: 
- they are hard to find back in his email log 
- the naming convention in the email makes it hard for him to know which export is for which form 
- if he wants the data export for a form, he usually wants all the data, thus he prefers to generate a new file to be sure he gets everything. 

We have however also learned that sometimes, if the data collection is done (end of project) and Salim just wants to cross check something, it would be easier for him just to re-download the file, rather than have to wait for the new file to be generated. But rarely will he come back to files older than a year and if so, he can always generate the file again.    

# Opportunity 
In the new UI where Salim can download data exports directly from Flow, we will show a list of exports he generated. This list should only show exports that are max a year old. Reports that are older than a year are automatically deleted by a task that checks every week for older reports (implemented in #2638).

However in addition to deleting the report items from the list, we also want to delete the actual report file that has been generated and stored on the flow services hard disk, or S3.  We will implement logic to delete these files when a request is made to delete an item from the reports list.

**Comment by janagombitova** [comment]
@muloem and @stellanl is this handled already? If yes, can you close the issue?

**Comment by janagombitova** [comment]
@stellanl this is part of the implementation, right? Can we close the issue or does this still need to be done?

**Comment by stellanl** [comment]
No, this has not been implemented yet. Only the report entry as seen in the report tab is deleted. Not the file in S3.
