### ISSUE TITLE
Add regular automatic cleaning of DeviceFileJobQueue

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2550]
While #2539 will stop the creation of DeviceFileJobQueue entries with bad filenames, there seems to be no mechanism to retire entries after they become useless. This can happen in at least three ways:

1. The missing file is uploaded and stops being missing. (Yay!)
2. The device that an entry points to is removed from the database.
3. The entry grows old enough that there is practically no hope for the file to be uploaded.

**Comment by janagombitova** [comment]
@stellanl I assume nothing user visible to test here, right?

**Comment by stellanl** [comment]
No, We'll have to look in the log files and the datastore to see that it ran ok.
