### ISSUE TITLE
variableName could return old values if set to null

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2551]
I can see a potential problem if someone changes an old variable name to nothing.
The old one might be output instead of nothing.

**Comment by stellanl** [comment]
Test plan:
Depending on the UI this might only be a problem in the API.
To test it in the UI, change the (previously set) variable name of an old (before Cosmic Coconut) question to nothing and reload the UI. It should be empty.

**Comment by janagombitova** [comment]
Variable name does not show after deleting and then fully reloading Flow. 👍
