### ISSUE TITLE
Show photos in UI directly 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2557]
# Context

For the background information please check this issue: child #2522 

From the user research and interviews we learned that photos are used to capture a visual representation of the topic of data collection (a photo of the beneficiary, of a stove, of a well, or a WASH facility) or to validate answers to a question (if there really soap next to the sink, are the toilets really well marked, is the garden well fenced, etc). When inspecting the submissions Salim tends to click around the submissions and check all is going well with the data collection and that the data coming in is as expected. 

# Current situation

Currently when viewing data we show in the Inspect data tab and in the Monitoring tab the photo  url. To see the image the user has to click on the 'Open photo' link. The photo is then opened in a separate tab. 

![34485165-62deee50-efc9-11e7-9ef2-9ad2313e581b](https://user-images.githubusercontent.com/12456965/36971007-b13aeee2-206a-11e8-8f64-11528b805e40.png)

In Maps we show the photo directly with the other answers. By clicking on the photo the user is brought to the new tab. 

![screen shot 2018-03-27 at 10 13 12](https://user-images.githubusercontent.com/12456965/37955018-a9389368-31a7-11e8-95fd-29182da89c8d.png)

In Maps vertical (portrait) photos are shown horizontally, as landscape photos.  

![screen shot 2018-03-27 at 10 25 16](https://user-images.githubusercontent.com/12456965/37955610-5755c79e-31a9-11e8-93b3-2033b695f352.png)

# Changes 

This issue is only handing **photos** NOT videos. If needed please break down this issue into smaller ones. 

## Show photos directly

We will stop showing the url in the UI and **show the image directly**, as we do in the Maps. This change will save Salim one click so he can faster go through the submissions when monitoring the data collection and checking the submissions. Secondly, it will ensure the photo urls are not shown in the UI thus easily shared with someone who does not have access to Flow. This change needs to be on the Inspect data tab and Monitoring tab.

## Click to enlarge
Secondly, when viewing the data (in Inspect data, Monitoring and all maps) the image shown is quite small. Salim might want **to click on it to see it larger in his screen**. 

Do we need to make this possible, is a way that we ensure we do not expose the url? @Kiarii and @muloem what are your thoughts on this one? Can we keep showing the url at enlarging (then we do not need to change the implementation)? If yes, how do we ensure that if Petra shares the url with someone not logged into Flow, they cannot access the image? 

## Handle vertical (portait) photos
We need to make sure photos are shown based on their orientation, landscape or portrait. This needs to apply on Inspect data, Monitoring and all maps and also when enlarging the photo.

**Comment by Kiarii** [comment]
quick response on viewing an enlarged image; we could pop the image so it is viewable in an enlarged size without creating a new page and exposing its url..

**Comment by janagombitova** [comment]
@Kiarii could you create a mock up for enlarging the photos to get an impression on who it can look and feel? Thanks

**Comment by Kiarii** [comment]
here is the mockup: https://invis.io/CAIHKGC4KBV#/296566779_Img-0

**Comment by janagombitova** [comment]
Released with 1.9.38
