### ISSUE TITLE
Remove Flow landing/log in page

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2559]
# Context 

We create separate Flow instances for each of our partners. This means they get their own Flow url. Once you open it up you see this: 
- Flow logo, 
- a small log in button, 
- a public facing map with data marked as public if any 
- a footer with: 
   - Software updates linking to the GH release notes, 
   - Help & support link  
   - Terms of services link. 
- Copyright and link to akvo.org

This is not the most informative nor inviting landing page.

The users go to this page primarily to log into Flow's online workspace. 

The idea behind the map was to showcase data set as public, but that is not used in this way in practice. The map takes up most of the screen once one opens the url. If we look at the current Flow instances and their public facing maps we have out of the 105 active partner instances only 43 showing data (of any kind) publicly on the Flow public map. For the partners who do not show data, this results in their Flow landing page to show a blank map. 

![screen shot 2017-11-16 at 12 23 41](https://user-images.githubusercontent.com/12456965/32888873-0f5cff26-cac9-11e7-9bce-ae73b2b9b3c7.png)

# Problems 

## Security risk

Currently users set surveys as private or public. The default setting is private but some surveys may be set as public. Data captured to these survey forms will show on this map. But the data can contain private data and if our partners are not fully aware of what data is publicly available, then they are facing a data security risk. 

## What is the value of the map? 

The map takes up most of the screen once one opens the url. If we look at the current Flow instances and their public facing maps we have out of the 105 active partner instances only 43 showing data (of any kind) publicly on the Flow public map. For the partners who do not show data, this results in their Flow landing page to show a blank map. 

Our users do not use Flow as a platform to share the data they have set as public. Not so many partners have their data set as public, mostly because of data privacy reasons and the granularity of the setting is missing (you want to share answers to some questions but not to all).

When one opens the Flow url and sees the map (with or without data) many users asks: Why is the map here? or they do not understand what Flow is from looking at the page or the linkage between Flow and Akvo and other Akvo tools and services. 

# Currently 

Salim enters his organisation's Flow url in the browser. Hits log in. Logs in with his Google account. Accesses Flow if he has an account. If he does not have a user account he gets a page telling him so. 

## Salim is a Flow user 
![log in1](https://user-images.githubusercontent.com/12456965/37969813-0748133c-31d2-11e8-98ca-b93ed79ddedb.gif)

## Salim is not a Flow user 
![log in 2](https://user-images.githubusercontent.com/12456965/37969816-09d6e7ae-31d2-11e8-9ece-a7d94586df01.gif)

# Opportunity 

The landing page is the first thing a Flow user sees before accessing the online workspace and we should take the opportunity to make it more exciting, visual, valuable, informative and actionable.

This is how Lumen's log in/landing page looks like (keycloak user log in page): 
![screen shot 2018-03-27 at 11 56 28](https://user-images.githubusercontent.com/12456965/37969502-36f8e314-31d1-11e8-8ec8-0ba4fd2b64a8.png)

## Questions: 
- What role does the map then play currently? 
- How does Flow's landing/log in page reflect Lumen's? 
- What role do we want the page the play?

**Comment by janagombitova** [comment]
# Internal research

Here are some points from internal research: 
- in general the map is not used 
- the public - private setting is a security risk (we realised that sensitive user data was available on the map and had to quickly go in a change everything to private) 
- Flow is not used as a open data platform 
- our partners do not share the map to showcase data 
- our partners sometimes go there to see the extend of the project efforts without having to log in, but the trick here is that not all their data is public, so they get the wrong picture

**Comment by janagombitova** [comment]
Considering we are moving to Auth0 to use as a shared Login provider for Flow and Lumen, we should revise the role of the current Flow landing page and consider removing it completely. If we do so: 
* going to the Flow url will bring you to the login page #3130
* the initial page will be the same for Flow and Lumen, creating a more unified experience 
* we can remove this nothing-telling map
* we can remove the pubic/private setting fully from Flow

**Comment by Kiarii** [comment]
I am very much for this, it would simplify the login workflow for the user and reduce encounter with information that maybe unnecessary to the user. Its a pity really that we still have that map :(

**Comment by janagombitova** [comment]
Ok. So then we agree that with the move to Auth0 we should also get rid of this page and have users land directly on the log in page: https://github.com/akvo/akvo-platform/issues/153

**Comment by janagombitova** [comment]
@loicsans as part of the Auth0 work, can you handle this issue too? The idea is the once a user goes to Flow she lands directly on the login page rather than this map one.

**Comment by Kiarii** [comment]
design status: a go

**Comment by janagombitova** [comment]
I might have jumped the gun here by already checking UAT2 after seeing the PR was merged. So if there is still more work to be done, please let me know and ignore this comment. 

Right now uat2 acts odd. After going to the URL you still see the map and a loading icon and then Flow automatically jumps to the current Google login page. 

![uat2](https://user-images.githubusercontent.com/12456965/66050957-622ec780-e52e-11e9-9e41-1044bfc0a6e7.gif)

As mentioned in the comment, the idea was that Salim no longer sees the map, but lands directly on the Auth0 log in page.

**Comment by janagombitova** [comment]
Map landing page no longer shows and the user is brought directly to the login page 👍
