### ISSUE TITLE
Variable name validation of special characters does not work on new variable names

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2563]
We have two validation rules in place when Salim creates variable names for questions: 
- must be unique for the survey 
- cannot have special characters 

If Salim adds a new variable name to a question, for the 1st time, and adds a special character to the value, as @ or $ or anything that we do not allow, he sees the error message but can save the question (the save button is not disabled). If he opens the question to edit again and if he then makes changes to the variable name still keeping the special characters, he cannot save it. 

![validation](https://user-images.githubusercontent.com/12456965/38028055-ff8b2b5a-3291-11e8-965e-7527675be19a.gif)

This is in production and only applies for the rule of special characters. Unique validation works well. 
I did not catch this use case when testing this issue for the pervious release: https://github.com/akvo/akvo-flow/issues/2474

**Comment by kymni** [comment]
Happening when a special character is appended before the validity check for valid variable name completes which then overrides the special characters error. Fix is to check for special characters again after validity check

**Comment by janagombitova** [comment]
Perfect fix! Ready to release
