### ISSUE TITLE
Improve Ember Radio button 

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#2578]
The Ember version we're currently on doesn't support radio buttons. A custom solution was implemented but doesn't seem to be in use anywhere and seems to have some hard-coded elements. Plan is to improve on this solution

**Comment by kymni** [comment]
@muloem would this be compatible with the ember version we're currently on?

**Comment by muloem** [comment]
Not the one we are on. But unless otherwise, I would like to avoid double effort. Doing it and then having to redo it later on.

**Comment by kymni** [comment]
The need to improve the current implementation is tied to #2340 which is currently in progress unless an alternative is approach is taken there

**Comment by stellanl** [comment]
Yes, Loic wants radio buttons.

**Comment by kymni** [comment]
### Test Plan
Create radio button using `{{view Ember.RadioButton selectionBinding="<property>" value=<button value>}}`

**Comment by janagombitova** [comment]
@kymni Is there anything user visible to test here?

**Comment by kymni** [comment]
@janagombitova not really. It is however the implementation that has been used in #2585 so can be tested when that's merged

**Comment by janagombitova** [comment]
Ok. if something comes up, lets handle it there. This one is then ready to go 👍

**Comment by kymni** [comment]
This implementation breaks radio buttons when previewing survey option questions. Reverting to older implementation for the sake of this release before finding a balance between the two

**Comment by janagombitova** [comment]
Will keep this issue open, as we reverted the implementation and move it to the next milestone.

**Comment by kymni** [comment]
Closing this because old implementation was used in #2585
