### ISSUE TITLE
Duplicated file

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2593]
The file
Dashboard/app/static/images/infolnc.svg
also exists as 
Dashboard/app/static/images/ infolnc.svg (note the leading space).

This causes warnings in deployment. The file also cannot be checked-out at all on a Windows file system,

**Comment by janagombitova** [comment]
I guess there is nothing for me to test here extra, right? Just the regular regression round?

**Comment by stellanl** [comment]
Correct.
