### ISSUE TITLE
Device latest version should check android version

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#2603]
Some older devices will no longer be supported. 
In order to do the process smoother, the app will now send the android api code:
https://github.com/akvo/akvo-flow-mobile/issues/1091
the param is:
`&androidBuildVersion=27`
We need to check for this value and
if missing param -> latest version is 2.4.8 or empty if missing from datastore
if androidBuildVersion < 15 -> latest version is 2.4.8 or empty if missing from datastore
otherwise -> get the latest version from the datastore

**Comment by janagombitova** [comment]
my dinosaur does not update the app anymore, it tells me with Elma that it cannot update as I am running an old Android version. Check for updates also does not show in the About page anymore Ready for release 👍
