### ISSUE TITLE
Importing cascades does not show the level

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2606]
Noting down this issue as it might come up in the future. This is an issue I found on the uat1 version 1.9.31. All previous versions on live production instances everything works correctly.  No one else could reproduce the issue.

# Steps to take
1. Create a new cascade 
2. Select to import the file 
3. Import a file with more than one level (the one attached here has 11: https://drive.google.com/drive/u/1/folders/1nVfYu2C_g04oY_ri5B0R9FJoTN44wPd-) 
4. Make sure you set correctly the number of levels 
5. Import
6. Wait for the confirmation message in the Messages tab 
7. Go back to Cascade and select the one you just created 
8. You should see all the levels but to me it showed just one level and then I had to add a new level to "reveal the hidden ones"

![cas](https://user-images.githubusercontent.com/12456965/39047277-9bcebac2-4499-11e8-857e-81402b75a703.gif)

**Comment by muloem** [comment]
Among the changes introduced in #2406, we upgraded the datanucleus version from v1 to v2 which depends on datanucleus JDO 3.0 implementation.  However, the caching in this version is turned on by default and was causing the cached cascade resource entity to be loaded instead of the updated one in the datastore.  The solution is to disable caching for now.

**Comment by stellanl** [comment]
Emmanuel suggested that this particularly affects objects with complex (List/Map?) data types. So I did a partial inventory among the persistenceCapable .model classes:

BaseDomain
	List<Long> ancestorIds;

Geometry
	ArrayList<Coordinate> coordinates = null;

LevelOfServiceScore
	ArrayList<String> scoreDetails = null;

Standard
	ArrayList<String> positiveValues = null;

ApprovalStep
	List<Long> approverUserList;

CascadeResource
	List<String> levelNames;

SurveyedLocale
	Set<Long> surveyInstanceContrib;
	List<String> geocells;

SurveyedLocaleCluster
	List<String> geocells;

User
	List<UserConfig> config;

UserRole
	Set<Permission> permissions;

SurveyAssignment
	List<Long> surveyIds;
	List<Long> deviceIds;
