### ISSUE TITLE
Show/export Flow instance usage

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2612]
# Context
Our SaaS pricing model is based on the number of submitted forms. For the partnership team to be able to track their accounts and for partners to know how much they have spent, they need to be able to know their usage status. Furthermore, sometimes a Flow instance is owned by a partner, who shares it with other organisations. These then contribute to the SaaS payment but the owner organisation then needs to know how many submissions these partners made. 

So for Petra, it is important to understand their usage in the context of the contract and how they capture data in general. She also is interested to see the uptake of the product per project. Salim is interested in seeing which forms are being used and how heavily. 

# Problem or idea 
Today Salim and Petra have no easy way to know: 
* total submissions on the Flow instance 
* submissions per form
* for a specific period of time or since the beginning of time

Currently, @stellanl has a script he can run per instance that gives a csv file with the survey path, form name, form ID and number of submissions. This however needs to be requested creating an unnecessary communication pipeline and Stellan needs to run it causing Stellan more work and breaking his flow and deep focus.  

## Opportunity 1 - download sheet with usage breakdown
The idea is to improve Stellan's sheet and create an option to export the file in the UI through which any user can export the usage per form per a specific period of time. 

In the Sheet we should:
* remove the 1st column, as the user knows which Flow instance she is on
* remove the privacy column
* rename Instance count to 'Number of submissions'
![Screen Shot 2019-08-08 at 12 22 08](https://user-images.githubusercontent.com/12456965/62695723-2a484f80-b9d7-11e9-84d7-c58c8925210f.png)

User experience: 
* define where to create the export option - it does not need to be perfect, this is the 1st iteration (the possibility is to create another export option under Data > Exports)
* make sure this is active without having to select a folder>survey>form
* enable to define the date range (optional)
* define the name of the export so it is clean in the UI list of exports 
* perhaps we can move the Survey form export and this usage export into a 2nd row under the data exports (just an idea) 

## Opportunity 2 - UI overview + download option 
Later we should consider to create a way to see usage in the UI and from this page to be able to download the breakdown overview. 
- total forms submitted on the instance + when the number was updated 
- possible other stats that can be interesting: total data points; total devices, total surveys, total users 
- usage trend - showing number of submissions over a time period 
- be able to filter on date - submission date 
- option to download the breakdown sheet from this place

## Far future
In the future, how might we take it further and bring their usage in relation to their pricing plan? How can Petra, as a Flow user know how many forms I have left from my contract period without having to contact Akvo?

**Comment by stellanl** [comment]
Is the current simple CSV format ok, or should it be an Excel file?

**Comment by janagombitova** [comment]
CSV file is fine, if we make the changes mentioned above to the data. This is a first iteration, so it does not need to be shiny-fancy.

**Comment by stellanl** [comment]
Do we want to filter the list to only contain the forms the user has access to? Or should this entire report be restricted to certain users?

**Comment by janagombitova** [comment]
I would keep it simple for now and push all forms in the file. 

Can we restrict it to users who are admin's (user management)? Then we follow the pattern Lumen has where admins only see the usage stats

**Comment by Kiarii** [comment]
since we are looking for a quick turnaround, could we just add a "Stats" page on the top menu just after "Messages"?

**Comment by janagombitova** [comment]
@stellanl if we agree to link the export to the user admin role, how much extra effort is it to add the logic to hide the new 'Stats' tab if the user does not have that permission? If it is too much effort, could we add a subtab 'Stats' under the main 'Users' tab, then the permission will be respected?

**Comment by stellanl** [comment]
Does not sound very hard to me. Should be able to cut-and-paste the code that hides the user page.
To make it secure, the POST /rest/reports endpoint must also enforce the only-admins for this type.
The interesting part is if we could make flow-services able to use the /rest API. That would let us remove some export/import-only stuff. Maybe auth0 can help with this?

**Comment by janagombitova** [comment]
Sounds good @stellanl. Let's keep this issue to the minimum and create a new one for your suggestion on using the /rest API

**Comment by stellanl** [comment]
Here is a report on the dev datastore:
[STATISTICS-146532016.xlsx](https://github.com/akvo/akvo-flow/files/3726699/STATISTICS-146532016.xlsx)

**Comment by stellanl** [comment]
As agreed w Emmanuel, I will not make a copy-pasted UI in Ember, but make that part a separate issue.

**Comment by stellanl** [comment]
Any privacy issues with counts from the uat1 datastore? If not I can put an example of the slightly enhanced report here.

**Comment by janagombitova** [comment]
Can you drop the file in the Akvo team Google drive somewhere and share the link? Just to be sure

**Comment by stellanl** [comment]
https://drive.google.com/open?id=1lryU8KghOq_Pdud-uVH6cZDxH65UKU16

**Comment by janagombitova** [comment]
@stellanl I took a look at the file shared and have a few remarks. Good initiative on adding the extra stats. Let's see if users find them useful and request more ;) : 
* Can you change the sheet name from 'Form instance count' to 'Form submissions'
* Can remove the 1st row with the 'Form instances' header? If we name the column headers and sheets clearly this row is then redundant. 
* Can you change 'Instance count' to 'Submissions'
* In the file the Instance count column is empty. But I know many of the forms there do have submissions. (Or did you export the file based on a specific date range?)
* In the 2nd sheet we have the item - Survey groups. Is this what we call Folders? If so, can we change the name to the user known one?

**Comment by stellanl** [comment]
The first line of the sheet also contains the date range (if selected). I could put that somewhere else, of course.
The instance count column is empty because uat1 is not running this branch yet, and so can't count instances.

**Comment by janagombitova** [comment]
I see. Then leave the 1st row as it is. Users can always delete it themselves, just instead on Form instance' let's use 'Form submissions'.

**Comment by muloem** [comment]
So one comment I also made on the UI side of things, currently when you load the Stats page of the UI, it retrieves all reports including the comprehensive, raw data and statistics reports. I think it makes sense to update the reports endpoint slightly and only be able to query for reports of a specific type.  e.g. `/reports?type=statistics` so as to avoid retrieving unnecessary reports for the user every time when they want to see the stats.

**Comment by muloem** [comment]
All done here! 👍
