### ISSUE TITLE
New datatype and endpoint for reports

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2617]
As mentioned in #2505, we need a new entity class and REST endpoint: /reports that will be used by

 1.  The UI to find out which reports have been created, their state and where to download the result from. (optionally?) filtered by user.
 2. The report engine to create and update the state as the generation proceeds.
 3. A (cron) background cleanup job that removes the reports when they get too old.

Child of #2505

**Comment by janagombitova** [comment]
child #2505

**Comment by stellanl** [comment]
The initial proposed architecture was something like this:
```
UI                 GAE                            FlowServices

Button-----------------------------------------------> /?

              /rest/reports <--POST new report state-- Clojure
                                  report state, with id ->
JS---GET--->  /rest/reports           
<- state list
              /surveyrestapi <--GET questions-------------- Java

              /databackout   <--GET answers--------------- Java

              /rest/reports/nnn  <--PUT finished report state-- Clojure
 
JS---GET--->  /rest/reports           
<- state list

JS---GET-------------------------------------------->  /.../report.xsl           
<- file
```

**Comment by stellanl** [comment]
The main problem here is that FlowServices is not logged into GAE, and so uses an API key for the /surveyrestapi and /databackout endpoints.

**Comment by stellanl** [comment]
General shape of the POST/PUT body:
{"report":{
"state:"IN_PROGRESS", //or FINISHED_SUCCESS or FINISHED_ERROR
 "user":"foo@example.com",
 "id":12345678, // not for POST
 "reportType":"DATA_CLEANING",
 "message": null //mostly for errors
}}

**Comment by stellanl** [comment]
![sequence](https://user-images.githubusercontent.com/399534/40486341-4dbf8fc2-5f61-11e8-8b36-455ad82fe28c.png)
