### ISSUE TITLE
Combine Data analysis and Comprehensive exports 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2626]
# Context 

With the large export changes we created separate Data cleaning export, Data analysis export and Comprehensive report. The Cleaning and Analysis one export data in a different structure (multiple sheets or rows for repeated groups, options in one or multiple columns). 

In the further research we learned that Salim prefers the Comprehensive one as it holds the data and the summary sheet. The data in the Comprehensive report is of the same structure as Analysis. 

Then we fixed the submission date filter on Cleaning and Analysis resulting in the Comprehensive report not being filterable by date anymore (was actually a bug rather than a decided functionality). A partner shared how they used the date filter bug on the Comprehensive report:  

"For us being able to download comprehensive reports according to period specific is very important. We collect data cumulatively and previously this feature worked so good. Some of my colleagues in the country programmes use the summary report so once I download data and simply filter according to when it was collected I will only have a raw data report and miss out on the summary report for that period." Link:https://flowhelp.reamaze.com/admin/conversations/re-akvo-report-downloads

![screen shot 2018-04-30 at 12 39 36](https://user-images.githubusercontent.com/12456965/39423741-97bb1ba6-4c73-11e8-8cde-ead13a0ca6a6.png)

# Opportunity

We can consider "combining" the Analysis export and Comprehensive report into one, by removing the Analysis one fully. The Comprehensive report already holds the data structure of the Analysis one. We can then allow to filter out based on submission date on the Comprehensive report. To make it clear that we actually did not remove the Analysis export, just combined it - we can rename the Comprehensive report to Comprehensive Analysis report (for example) and change the description to make it clear what the export contains. 

This change can help us: 
- **simplify**: We can remove the Data analysis export as it is a piece of the Comprehensive report 
- **enhance the value of Comprehensive**: By adding the submission date filter to the Comprehensive report we will make this most commonly used export option even more valuable. 

# Next steps 
What do you think? @muloem @stellanl @Kiarii and @loicsans  
Make Go - No Go decision

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/akvoflow-support-request-number-124092-from-nikki-at-akvo-dot-org
Assignee: Jana Gombitova

**Comment by stellanl** [comment]
Most of this is in the UI. The data page of the comprehensive report will already be filtered by data if it is specified. What needs to be changed in the reporting engine are the statistics.
They should be computed only on the selected submissions. Also, I think the selection start and end should be in the report.
