### ISSUE TITLE
Move survey form export to survey editor UI

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2627]
# Context 
Salim downloads the survey form export to: 
- check the structure of the form (the question text and options, etc) 
- share the form with others who do not have access to Flow but are working on the design of the form 
- for data cleaning to see why some columns are empty by checking for dependencies or mandatory settings 

With the move of Reports tab under Data, being able to download your survey form in this page does not really make sense as you are not downloading data with this export, you are downloading the survey form.  

![screen shot 2018-04-30 at 12 44 53](https://user-images.githubusercontent.com/12456965/39424131-6d6c3bb2-4c75-11e8-8756-cda5f525c869.png)

# Why
The driver behind the design changes that we make is to simplify Flow by moving things around and Petra's and Salim's workflow. We want to remove the repetitive steps they have to do. We want to eventually bring all actions around the survey. So Petra and Salim can first select the survey they are working on, and then view it, edit, work with the data it has, etc. We want to  move from the current set up that is based around actions (now I view different data, now I check things on the map, now I edit surveys) to a set up where Petra and Salim do everything with a survey, as this is the workflow we learned they have. 

# Opportunity
An idea is to move the survey form download to the survey editor page, possible as another action button next to Publish, Preview, Delete (to limit large design changes).

![screen shot 2018-04-30 at 12 45 28](https://user-images.githubusercontent.com/12456965/39424179-a2ae3604-4c75-11e8-81dd-b0b3cd04f42f.png)

If Petra downloads the form export to see it's structure she is usually in the survey editor 1st working on the form structure. We do not know what exact steps she takes when downloading the form for data cleaning. So this change 

# Next steps 
With the upcoming changes to exports (#2505) I thought this idea might have implications to the implementation. What do you guys think? @muloem, @stellanl, @Kiarii and @loicsans Is this an idea that can be beneficial to Flow and Salim's UX? Do we need to research more? If we make the change after #2505 what implications will that have? How will it work? 

Make Go - No Go decision

**Comment by Kiarii** [comment]
Moving the survey printout export to the survey itself seems logical, the move would also leave the Export page decluttered with one item less.. 

A question that comes to mind however is how survey printouts are used, for instance when trying to understand the responses; since we now provide a log for data exports, would there be a scenario where the survey structure has changed, in which cases there would be 2 and the 2 would be necessary to understand previously and recently exported data - or can we assume that a single single structure will suffice (i.e. no major changes are made to survey as soon as data collection commences) to understand all data exports?

For the first 2 use cases listed by Jana, I think the change would support those and maybe in a location closer to home; the user would not have to navigate to exports to printout a survey they are designing

**Comment by janagombitova** [comment]
Reopening this issue. 

We bring the task *closer to home* as Kiarii states. Having it under Data exports is confusing. 

Furthermore, a while back we added the Form version to data exports. This means that with each submission users can see based on which form version the submission was made. They can then easily see why there are discrepancies in columns as perhaps v27 was different than v28. Ideally, Salim has a way to download each form version to be able to better understand his data. Why am I saying this here, in this issue? 

When exporting data we said it is good to have a list of past exports are you can compare the data from a few months back with the dataset from today. But with survey forms, comparisons happen among form versions. Salim looks at v27 versus v28. Each form version is stored in Flow. Today we can download the XML file using a script. Ideally, we want to give Salim the option to Export any survey form version. (see this issue). 

This means that he goes to the form > clicks to export > clicks which version he wants (with the most recent one autoselected regardless if it is in draft or published) and can select any of the past versions > clicks to export > file downloads to his browser. He does not need to have a list of his previous form exports and he can always just export the version he wants from Flow as they are independent of each other.

**Comment by Kiarii** [comment]
First ideas; how to export select form version, going all the way to the big bang
<img width="1301" alt="Screen Shot 2021-06-17 at 11 31 38" src="https://user-images.githubusercontent.com/12692444/122361066-972bb980-cf5f-11eb-843b-beb22efe13db.png">
