### ISSUE TITLE
Load latest cron jobs definition for deployments via admin API

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2628]
For deployments that are executed via the admin API (see #2562) it appears that the latest cron job definitions file is not loaded.

**Comment by janagombitova** [comment]
Is there anything user facing that I need to keep an eye one here when testing?

**Comment by iperdomo** [comment]
Since cron jobs are usually _internal_ processes, their visibility to the user is limited. 
I think we can close this issue when a developer verifies that the latest cron definition was updated properly after a deployment.
