### ISSUE TITLE
Remove server side clustering

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2631]
The current implementation of maps that runs off of mapbox, handles clustering of datapoints by creating and storing clustering entities on the backend.  We are removing this clustering functionality because it has been prone to problems of inaccurate data as a result of the eventual consistency model of data update used by GAE.

**Comment by muloem** [comment]
# Test Plan 


* Delete the registration form of a datapoint.  The datapoint should be deleted

**Comment by janagombitova** [comment]
Clusters are gone, but so is the functionality to view the submissions. The points show empty on the map.

**Comment by janagombitova** [comment]
All fixed and works well. Remaining issues are documented
