### ISSUE TITLE
Make a Cron job for retiring old reports

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2638]
Building on #2617.
Reports should stay in the table for a year after generation. A cron job will check them regularly and remove those that get too old.
A possible additional function is to clean up after crashes in the report engine. If that happens entries may remain in IN_PROGRESS state forever. The cron job could look for entries that have been in that state for more than, say, a day and change them to FINISHED_ERROR with an appropriate message.

**Comment by janagombitova** [comment]
Child of #2505

**Comment by stellanl** [comment]
Test plan:
1. Wait a year and look for any reports that are older than a year.
2. There should be none.

**Comment by valllllll2000** [comment]
Given the test plan, moving it to Release Ready. Will check in one year!
