### ISSUE TITLE
Show full form structure in export 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2639]
This issue is a recreation of the old issue here: https://github.com/akvo/akvo-product-design/issues/238

# Opportunity 

## Who

Salim, responsible for the survey structure, preparing it for the data collection exercise. 
Petra, analysing the data but was not involved in the survey creation. She receives the data export from the implementing organisation via email, as well with the form export. 

### What is form export used for currently: 
- **for paper based data collection** 
   - this was the original reason for the form export implementation. We do not know if users use the export for this particular reason. 
   - the export structure also reflects this use case, but not the following ones with one bug, that it does not show all translations available to the form
- **for cross checking the form structure** 
   - users want to see the entire form structure, how questions are defined, linked together and what their settings are
   - they share the file with others involved in the survey definition process, who are not Flow users (external advisors, consultants, colleagues from other projects)

- **as a "code book" for analysing data** 
   - to understand which values were predefined, put in as free text, if there was the chance to select more, if there was a dependency and that is why cells are empty
   - to be able to understand the data, the analyst needs to understand the survey in order to be able to extract information out of the data 
   - analysis happens offline in the Flow world, so being able to have detailed meta data on the columns Petra is looking at will help her better understand the data

#### For all questions 
- question group
- order in their group
- overall order in the entire form (as in some exports we do not show question groups)
- if in a repeated question group
- question type 
- question text
- mandatory
- used as data point name (for some question types) 
- variable name
- dependent on another question - which question and which option

#### Per question type 
- free text - double entry 
- number - double entry, special signs, max and min
- geolocation - manual entry enabled, use as data point location 
- date 
- option - list of defined options, "other", single select, multiple select
- cascade
- photo
- video
- barcode - manual entry enabled, multiple scans
- signature
- Caddisfly - test type 

We also need to answer, if all these settings need to be shown in the export, or not. 

## Why

- current form export is incomplete - was created to support paper based data collection, but this is the use case we want our partners to move away from. The research also showed that the survey form exports are not used for this reason, but to understand and see the form structure.
- current form export is used but can be more valuable 
- to make data analysis easier 
- to make it possible to better have a full overview of the form 
- to ease cross checking forms before data collection exercises 

Why not solve the problem of seeing the full survey in the instance? We need to solve that as well, but improving the form export, we would still support cases when users outside of Flow cross check the form structure, as well as for data analysts who analyse the data outside of Flow, so then they do not need to be in Flow looking at the form and in their analysis tool. 

# Ideas 
Example from partner  
https://drive.google.com/drive/u/1/folders/0B4BNcLtl6pHrdU9tTFpscjVPalU
Example based on test data
https://drive.google.com/open?id=0B4BNcLtl6pHrcWlmY3g3amtydGs

# Support tickets 
Link: https://flowhelp.reamaze.com/admin/conversations/r-program-to-extract-the-labels-of-variables-and-codes-from-akvo-flow-dashboard
Link: https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-96245

Who will be using this feature?
Project coordinator / team leader / manager of the data collection

How do you want to use it?
Easily reference the questions in the Flow app, to those in the dashboard / survey print out.

Why do you need to have it?
When an enumerator reports an issue in the field with ‘question 7’ I can easily locate it in the survey and data set.

Tell us more about your request
Hey guys - recording this here re: Survey exports. UN women use them a bit to help with referencing data cleaning /survey structural issues. However they have had some problems with the survey question numbers not matching across the App version, online workspace and the print out of the survey. Not urgent, just recording here for future feature development.

**Comment by stellanl** [comment]
Here is the output from a prototype: Options list and translations still not implemented.
[FullForm-101490920-b.xlsx](https://github.com/akvo/akvo-flow/files/2208976/FullForm-101490920-b.xlsx)

**Comment by janagombitova** [comment]
Nice! :) 

Some ideas and questions: 
- how about simplifying `Use for DP name` to `Data point name`? 
- Why did you combine the text and number questions? 
- you can remove Allow external sources as that is a feature we can fully remove 
- change `confirmation required` to `double entry` so we use the same words as in the UI 
- for options can you change `allow several` to `allow multiple` so we use the same words 
- for geolocation we also need to indicate if it is used as data point location 
- are we only going to show the detail columns if that question type is in the form, or just have the standard structure? I am asking because I miss seeing Caddisfly and the selected test type as another detail we should show, and barcode and geoshapes.

**Comment by stellanl** [comment]
The question types are currently shown in their internal form:
FREE_TEXT, OPTION, NUMBER, GEO, PHOTO, VIDEO, SCAN, TRACK, STRENGTH, DATE, CASCADE, GEOSHAPE, SIGNATURE, CADDISFLY
Should we prettify this? SCAN is a barcode scan; perhaps not entirely obvious.

**Comment by janagombitova** [comment]
@stellanl we definitely should. They should reflect the names the user selects in the UI in the survey editor when selecting the question type.

**Comment by stellanl** [comment]
Here is another prototype. Question types now mapped to strings like those in the dashboard dropdown.
[FullForm-101490920-dual6.xlsx](https://github.com/akvo/akvo-flow/files/2278385/FullForm-101490920-dual6.xlsx)
Two questions:
1. Dependency can be set on all questions. Should it come before any type-specific columns?
2. Barcodes have a multiple-scan option, but it is stored in the same field as that of the Option q's.
Should we output that into two columns?

**Comment by janagombitova** [comment]
Hi @stellanl I took a look at the latest prototype and here are my comments: 
- no clear distinction for Free text settings, the user for data point name. I miss seeing the Free text in the same row as you have the other questions types 
- please change 'Use for DP name' to 'Data point name'
- if 'sign' in column F is Signature question type, then this should be in the same row as the other question types (one row higher than now), same for Caddisfly. So one row hold the question type and the row below the possible settings 
- I would move the dependency either all the way to the end of the sheet, or as the last generic setting (before the settings per question types start) - up to you 
- For option question you call the options 'selections', I would use just options to not introduce a new word. 
- For Caddisfly you have in all cells of the column 'null'. You should leave it empty, if none of the questions are Caddisfly, as in the other question types 
- Barcodes should be shown in their separate columns

**Comment by stellanl** [comment]
- There are no settings that apply only to Free Text.
- Now "Data point name".
- This is the "Allow sign" column for numbers. (Like -17) I could use the longer term.
- Dependency moving left.
- Now "Options".
- Old bug made Caddisfly uuid show as null. Fixed.
- Adding barcode column.
- This version does not handle translations yet.

**Comment by janagombitova** [comment]
> 'There are no settings that apply only to Free Text. 

Do I understand it then correctly that the Free text and number questions share some settings, thus you bundled them? If yes, can you then change the title when you now have 'Numbers' to 'Free text and Numbers'? 

> This is the "Allow sign" column for numbers. (Like -17) I could use the longer term.

Yes, please use the long term 

> This version does not handle translations yet.

Curious to see how that will look like. 

We are almost there @stellanl. This will be very helpful for the survey editors but also for those cleaning the data. Looking forward to it

**Comment by stellanl** [comment]
@Jana, no, I meant that free text has *no* limits etc. like the other types have; just dependency. And nothing it shares w only numbers either.

**Comment by muloem** [comment]
@stellanl There is something off with the report as far as generating the info related to Geoshape questions.  Looking at the screenshot of the report, it appears that even for none geoshape questions, the fields about whether lines, areas or points are allowed are marked as _Yes_ and only question 15 in the geoshapes is correctly indicated.

<img width="490" alt="screen shot 2018-10-03 at 06 25 37" src="https://user-images.githubusercontent.com/533336/46389938-6a62e580-c6d5-11e8-93c8-603917c57259.png">

**Comment by muloem** [comment]
But shouldn't they be off until the geoshape question type is selected and they are checked, no?

**Comment by muloem** [comment]
After talking to @stellanl turns out that the issue with the geoshape settings marked as yes on other non-geoshape questions is due to a bug that sets this value to true by default.  Creating a separate issue for that. https://github.com/akvo/akvo-flow/issues/2877

**Comment by muloem** [comment]
👍 everything else works as expected!

**Comment by janagombitova** [comment]
Are we waiting for the geoshape question to be resolved to release these changes? They have not been released with 1.9.38

**Comment by stellanl** [comment]
No, we don't need to wait for that. But these changes live inside flow-services, and it's been a while since it had a release.

**Comment by muloem** [comment]
Flow services released so we can close off this one.
