### ISSUE TITLE
After importing in new data, they do not show on the map or app map

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2643]
# On the map in the app 
I have a survey with a location question that has Use as data point location enabled. After creating new submissions via the app they show properly on the map in the app. But if I import new data using data cleaning, the new imported data do sync in properly to the app, I see the location info in the History but the points do not show on the map. If I open one of the imported points and hit View map, the point does not show there on the map either. 

# On the Carto map
I could not confirm as none of my data points show on the Carto map, even after the 15 min wait

On uat1 > _1.9.31 1.9.32 and... > testing location > Location RF

# On the Mapbox map 
I tried to confirm on uat2, but my data import does not work there and the points I created regularly also do not show. They should be in the North of Norway, but nothing. 

On uat2 > Jana tests > testing location

**Comment by janagombitova** [comment]
@muloem as part of the maps changes you are working on, can you take a look at this one too? Thanks

**Comment by valllllll2000** [comment]
I have tested it on the app and here is what I get for these datapoints:
Datapoint that shows correctly:
```json
{"identifier":null,"lastUpdateDateTime":1526563073733,"lon":22.99426,"surveyGroupId":257559115,"surveyInstances":[{"uuid":"37d25a78-8816-4510-ac61-685efcd3974b","collectionDate":1526367667750,"surveyId":262479115,"submitter":"jana","qasList":[{"a":"uffvb","t":"VALUE","q":"255149116"},{"a":"22.38455|22.99426|5|skbyg5iu","t":"GEO","q":"258639115"},{"a":"22","t":"VALUE","q":"262529115"}]}],"lat":22.38455,"id":"cm7m-ag1b-qj1f","displayName":"uffvb - 22","keyId":null}
```
Datapoint that shows incorrect (you can see that lat and lon values are null):
```json
{"identifier":null,"lastUpdateDateTime":1526369392397,"lon":null,"surveyGroupId":257559115,"surveyInstances":[{"uuid":"6100aea8-765d-4d45-9ee7-6a413090baec","collectionDate":1526369389537,"surveyId":262479115,"submitter":"my alter ego","qasList":[{"a":"33","t":"VALUE","q":"262529115"},{"a":"33.38455|33.99426|5","t":"GEO","q":"258639115"},{"a":"import 3","t":"VALUE","q":"255149116"}]}],"lat":null,"id":"hhwy-f098-1k73","displayName":"import 3 - 33","keyId":null}
```

**Comment by stellanl** [comment]
I have found that import in the logs, and for some of the instances we get this error:
2018-05-15 09:29:56.255 CEST
org.waterforpeople.mapping.app.web.DataProcessorRestServlet surveyInstanceSummarizer: Couldnt find geoplace for instance. Instance id: 261539116 (DataProcessorRestServlet.java:1006)

which I think means that it cannot get a country code from the lat/lon.
Could it be that the country database was not loaded (at the time)?

**Comment by valllllll2000** [comment]
Strangely today I imported a datapoint and it showed on the map of the app correctly

**Comment by muloem** [comment]
@valllllll2000 for the new submissions import?

**Comment by valllllll2000** [comment]
> @valllllll2000 for the new submissions import? And what about on the dashboard maps?

I am using the 1.9.49 MF Survey which currently has 7 datapoints on the app map, called 1, 2, 3, 4, 5, 6, 7. They all show in the app correctly. In the dashboard however, I can see only 5: 2, 3, 4, 5, 7 so 1 and 6 are missing.
1 was edited via data cleaning in the spreadsheet
6 was added via the spreadsheet

**Comment by valllllll2000** [comment]
After comparing the 2 datapoints 3 (shown) and 8 (not shown) I have seen that in the datastore, 3 has some geocells but 8 does not, the geocells field is Null. I have copied the geocells array from 3 to 8 and now the datapoint 8 shows on the map at the correct place.
