### ISSUE TITLE
Remove dependency with maven repo ebi.ac.uk

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-flow#2658]
This repo is failing right now, which is causing the flow-services and flow-api builds to fail and will cause the flow build to fail if the TravisCI cache is cleared.

It seems that the functionality imported from that repo is either not used or can be replaced with other more popular libraries

**Comment by iperdomo** [comment]
Related to #555

**Comment by janagombitova** [comment]
I assume there are no user facing changes to test here.
