### ISSUE TITLE
Filter datapoints on the maps tab based on a selected survey

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2661]
Currently when one accesses the maps tab _all_ datapoints are retrieved from the backend.  We now intend to filter these datapoints in order to only show those for a selected survey.

**Comment by janagombitova** [comment]
We allow users to filter to survey level. For monitoring surveys the data points show answers to registration forms. 

# From testing 
Filtering data points on both maps works correctly. Carto maps work correctly, also to view data submissions - the issue with clicking on the point and the points disappeared is resolved. Mapbox maps work correctly too. 

We have an issue with showing answers to new data points on the maps, but this will be handled separately.
