### ISSUE TITLE
Survey data value doesn't conform CASCADE type

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-flow#2667]
Hi flow guys :) 
akvo-lumen found https://github.com/akvo/akvo-lumen/issues/1374 that the following survey `WAI Bangladesh WASH SDG->Bangladesh Baseline 2018->Household Survey Final ` 
has an incorrect value for expected `CASCADE` type
Specifically the result of `https://api.akvotest.org/flow/orgs/wai/form_instances?survey_id=674184002&form_id=669404002&page_size=300`

``` clojure
(def data ...) ;; data retrieved from previous url
(= 19 (get-in data ["responses" "665994009" 0 "666054007"]))
```
Thanks!

**Comment by tangrammer** [comment]
data details can we found here https://docs.google.com/document/d/1EcXYuFtALHcpGBNyN0m3_t1MiPe1jZwGEH0nd5XBcpw/edit

**Comment by tangrammer** [comment]
@janagombitova don't know about where the issue comes from, maybe @nadiagorchakova could help on that

**Comment by nadiagorchakova** [comment]
Hi Jana and Juan, yes, the issue came from support. Here's a link to the ticket: https://flowhelp.reamaze.com/admin/conversations/akvolumen-support-request-number-103682-from-andrew-at-akvo-dot-org

**Comment by muloem** [comment]
@nadiagorchakova @tangrammer so did data cleaning resolve the issue or do we still need to pursue this?

**Comment by janagombitova** [comment]
It was resolved by cleaning. We can close for now and reopen if needed.
