### ISSUE TITLE
Do not show in data view dropdowns if I do not have permission to view 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2674]
# Context

In this issue: https://github.com/akvo/akvo-flow/issues/1558 we fixed the bug that caused if you had **view form** permission you could also see the folder>survey>form in the data related tabs (Inspect, Monitoring, Charts, Export, Maps) and view the data. 

Now when you only have form permissions (view/edit form, not view data) on a folder or survey and you go to data related tabs, you see the folder in the dropdown, you can select the survey but you do not see the forms listed. 

# Issue 

The current bug fix is in essence good as I am not allowed to see the data for the form. But it can be confusing for Salim that in the data related tabs he can select the survey and then not the form. He can get the impression that he can see the data, as he sees the folder and survey, but then he cannot get to the form. He might assume something is wrong with the form.

# Change 
I think it is less confusing for Salim if he does not see in the dropdown what he does not have access to see the data for. So if I have **no view data rights** on an entire folder, I do not get the folder in the dropdown. If I do not have data access to a survey, then I do see the folder in the dropdown but not the survey. (Same as we have with data cleaning)

This should be addressed on all tabs in the same way.

**Comment by kymni** [comment]
Same as we are doing for forms, we will not list surveys for which the logged in user has no `DATA_READ` permissions. This way a user won't be able to select a survey only to be presented with an empty forms list

**Comment by janagombitova** [comment]
@kymni does this mean that if there is folder A with survey A and B on my instance and I have data view for survey A only, I will see a dropdown with folder A - select it. Then in the next dropdown I will only see survey A? And if I do not have any view data permission on folder B, I will not even see it in my 1st dropdown? If I have no view data permissions at all, my 1st folder dropdown is empty?

**Comment by kymni** [comment]
That should be the eventual result though first we'll target the surveys as it's easier to get their permissions than it is for a folder that's, say, in the middle of a nested structure
