### ISSUE TITLE
Show date filter on new exports page

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2675]
# Context 

Child of #2505 where we agreed that we will add to the new page, where data exports are listed also the indication if the data export was filtered out by the submission dates or by the 'most recent submissions' filter. 

For more details see: https://github.com/akvo/akvo-flow/issues/2505#issuecomment-385364313

# Goal
Data comes in regularly for forms and Salim sometimes exports only the data for this month, as he needs to clean it or analyse the latest data. In the new page he will see a list of exports for one form and needs to be able to recognise which export was made for when.

@Kiarii and @loicsans can you please share the revised designs for this change? 
@loicsans and @kymni can you please make sure this change is put in place? 
Cheers

**Comment by Kiarii** [comment]
here is the revised design with the filter labelling:
![image](https://user-images.githubusercontent.com/12692444/40905046-616e1e3a-67e5-11e8-95ac-6eab201be9f0.png)

**Comment by muloem** [comment]
@stellanl please confirm that the changes are addressed in #2617

**Comment by stellanl** [comment]
Yes, they are.
