### ISSUE TITLE
When creating a new form, I cannot edit right away

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2677]
Related to the changes for the 1.9.33 release. 

**Steps to reproduce**
1. Log in with a user with full permissions 
2. Create a new survey - works ok
3. Add a form to it 

Now you should be able to edit the form, add groups and questions. But there is no action button in view and you can only Preview the form. 

After reopening the survey again, you can edit the form. 

![new form](https://user-images.githubusercontent.com/12456965/40911445-0ead0fda-67ef-11e8-97c9-223bf382b1e3.gif)

**Comment by kymni** [comment]
### Test plan
* Create a new survey
* Create a new form under the survey
* Confirm option to add a question group is there and works
* Confirm option to publish and delete newly created form is there and works

**Comment by valllllll2000** [comment]
Tested on uat1, creating new survey, adding new form:
* adding group and question works and is available
* deleting is available and works
* publishing works
