### ISSUE TITLE
Building dependancies based off number question types

### ISSUE THREAD

**Issue by henryjewell** [akvo/akvo-flow#268]
As a FLOW user, I want to be able to build dependancies based on number type questions, i.e.  for the question how many miles did you run today? If the answer is >26.2 then a follow up question will be displayed, such as; are you crazy? It will be great if this can be done will all mathematical functions (<,>,=, etc). This will help when building a survey by providing more flexibility.

**Comment by janagombitova** [comment]
Adding this issue into Product design repository as we need to understand the problem and value more and properly tackle the Discovery part as well. New issue exists here: https://github.com/akvo/akvo-product-design/issues/176
