### ISSUE TITLE
New data does not show on the map

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2680]
Data captured after April 25th do not show properly on the map. The points load but when clicking to view the answers, the side panel is empty. 

<img width="1259" alt="screen shot 2018-06-04 at 16 16 57" src="https://user-images.githubusercontent.com/12456965/40922537-ba7060d8-6812-11e8-9f37-9a432337ee5f.png">

**Comment by janagombitova** [comment]
@muloem  I tested the release candidate on uat1 and my new data points show in full glory with all their data. Issues created before this release candidate was pushed to uat1 do not show, on the other hand. 

So assume this is not fully resolved.

**Comment by muloem** [comment]
When browsing non-monitoring surveys, the datapoints are shown on the map but when clicking on a datapoint, no question responses are loaded.  Only the datapoint details are shown

**Comment by janagombitova** [comment]
Released with 1.9.38
