### ISSUE TITLE
Stop using backends on GAE

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2694]
[Backends](https://cloud.google.com/appengine/docs/standard/java/backends/) is a deprecated feature that we currently use as a second copy of our application with a different scaling configuration.  However, we use it in  a few select cases that can be optimised such that we do not need an instance with more processing power and longer execution times.

Parent of #2968 
Parent of #2969
Parent of #2970 
Parent of #2971
Parent of #2972

**Comment by stellanl** [comment]
Backends are mentioned in build.xml for update and rollback targets.

It is configured in WEB-INF/backends.xml :
<backends>
	<backend name="dataprocessor">
		<class>B2</class>
		<instances>1</instances>
		<options>
			<dynamic>true</dynamic>
		</options>
	</backend>
</backends>

**Comment by stellanl** [comment]
Backends are called from a number of classes.
The URLs are:
com.gallatinsystems.survey.dao.CascadeNodeDao.deleteRecursive(Long, Long)  and
com.gallatinsystems.survey.dao.CascadeResourceDao.delete(CascadeResource) :
 /app_worker/dataprocessor?action=deleteCascadeNodes

com.gallatinsystems.survey.dao.SurveyUtils.copySurvey(Survey, SurveyDto) :
 /app_worker/dataprocessor?action=copySurvey

org.waterforpeople.mapping.app.web.rest.QuestionGroupRestService.copyGroup(QuestionGroupDto)
 /app_worker/dataprocessor?action=copyGroup

org.waterforpeople.mapping.app.web.RawDataRestServlet.handleRequest(RestRequest) L375
 /app_worker/dataprocessor?action=rebuildQuestionSummary (IF backendpublish property set)

org.waterforpeople.mapping.app.web.SurveyAssemblyServlet.handleRequest(RestRequest)
  /app_worker/dataprocessor?action=assembleSurvey (IF backendpublish property set AND >80 questions)

**Comment by stellanl** [comment]
Interestingly, the importRemoteSurvey action takes a very long time (I find several examples very near the 600s/10 minutes allowed on a task queue on uat1)  but is not sent to a backend by 
org.waterforpeople.mapping.app.web.TestHarnessServlet.doGet(), just to the default task queue.

**Comment by stellanl** [comment]
To eat this elephant we will divide it into smaller piece; creating separate issues for them.
