### ISSUE TITLE
Investigate Hindi and Bengali compatibility for Field Survey app

### ISSUE THREAD

**Issue by caetie** [akvo/akvo-flow#270]
For Joy:

In order to achieve greater scale and better service in SE Asia, we should improve compatibility with Hindi and Bengali for the Field Survey app, since enumerators have minimal English speaking and writing skills.

The priority is at the point of data collection -- the apk should support downloading and displaying surveys in Hindi and Bengali, as well as inputting these languages into available entry fields on the app.

Unicode support is available on slightly higher end androids, so getting a survey on a phone in Nepali or Bengali is not proving difficult (see attachment) but we do not have input capability in the same language.

The questions to answer are:

1. Can surveys be created on the dashboard in hindi and bengali and exported to the app, with no problems in the encoding?

2. Once created and downloaded to the app, can surveys be displayed correctly on the apk?

3. What is needed to input bengali and hindi on smartphones, in terms of both software and hardware?

4. Can data be uploaded and received correctly by the backend in Hindi and Bengali?

5. Can data be exported and displayed correctly in Excel?

- talk with @stellanl about what he looked into in this area (UTF 8, encoding, etc) 

![screenshot_2013-06-27-22-43-56](https://f.cloud.github.com/assets/1315528/730482/f4654806-e254-11e2-9731-110ed4f898b7.png)

![screenshot_2013-02-28-23-34-56](https://f.cloud.github.com/assets/1315528/730483/f461a598-e254-11e2-80b1-8dec7f820d70.png)

**Comment by joycarpediem** [comment]
Closing this as translations are already implemented
