### ISSUE TITLE
Save the form version used to collect data

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2707]
With akvo/akvo-flow-mobile#1133 the version of a form that was used to collect data will be submitted in the data. We need to store it in the SurveyInstance entity.

**Comment by stellanl** [comment]
Currently useful only for manual investigations of support issues.

**Comment by janagombitova** [comment]
And for partners to see which data is being submitted to which form version to better understand if there is some inconsistencies in the data. Having this information can also alert them that an enumerator does not have the last survey form version and to ensure he updates.

**Comment by stellanl** [comment]
Certainly, but to do that we need to also propagate it to the UI and perhaps into the reports.

**Comment by janagombitova** [comment]
Good point. Iteration version n2 to add to meta data columns in exports and then we can also see if it is useful to add the the UI, somewhere and somehow.

**Comment by valllllll2000** [comment]
@stellanl anything to test here? if not just move it to release ready

**Comment by muloem** [comment]
@valllllll2000 if you confirmed that the value is stored that should be enough
