### ISSUE TITLE
Carto maps not working 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2721]
Our partners using the Flow instances running the Carto maps have reported that the maps are not working and the support team confirmed the issue. 

<img width="1280" alt="screen shot 2018-06-21 at 08 14 16" src="https://user-images.githubusercontent.com/12456965/41701133-8e49abe2-752b-11e8-82fd-ddcf1aad4698.png">

We should consider if we are ready to move these instances to Mapbox or we are not ready and need to fix this issue.

**Comment by muloem** [comment]
<img width="1255" alt="screen shot 2018-06-21 at 08 18 39" src="https://user-images.githubusercontent.com/533336/41701192-cc7c4f1e-752b-11e8-99cd-38838f263911.png">

Its probably connected to this issue.

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/maps-function-of-akvo-dashboard

**Comment by muloem** [comment]
We can fix this as its a small thing but over this or the next cycle we should switch them anyway.
