### ISSUE TITLE
Sufficiently huge question group cannot be renumbered safely

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2726]
Once upon a time in akvoflow-35, there was a QG with 500 questions (193950913). When the user started moving them into other groups they started near the front. That meant that for each move ~500 questions had to be renumbered. This made the PUT to _/rest/questions/bulk_ run over 60 seconds, get aborted, and only partially executed. Soon the user tried to move the questions again. This made it worse. After a while, all the kings horses and all the kings men couldn't get the questions in order again, without a datascript: #2734

**Comment by stellanl** [comment]
There are some ways to prevent this from happening again:

1. Limits: prohibiting more than, say, 100 questions per group. Annoying to users that don't plan ahead, but very simple.
2. Elephant catering: The UI could make the bulk update in several bites of, say, 100 questions each. May require some ugly Ember hacks. 
3. Punting: Forking to a task that can run longer. Will leave the UI and the db different longer, possibly confusing another user that works on the same survey.

**Comment by muloem** [comment]
So I am in favour of your elephant catering option.  I think we can update a huge batch of questions at a go and try not to make the hacks look too ugly.
