### ISSUE TITLE
Feature request: survey title on exported survey forms

### ISSUE THREAD

**Issue by JosjeS** [akvo/akvo-flow#273]
Kathelyne downloaded three different surveys in exel, and noticed that the title of the survey was not on the exported survey form in exel. It would be useful to have the title on there so when you export and print different surveys you know which survey is which.

**Comment by jonase** [comment]
## Test plan

* Pick a survey and do a "Survey form export"
* In the generated excel file make sure that the first row is of the form "`name` (v. `version`)". For example "Export test form (v. 3.0)"

**Comment by rumca** [comment]
@jonase I'm not sure this is working correctly. On the exported survey from I see the following:

![screen shot 2015-01-28 at 15 18 13](https://cloud.githubusercontent.com/assets/3003031/5940162/e955dc2e-a700-11e4-877e-67faec1120fb.png)

**Comment by jonase** [comment]
This code runs on flow-services. Is this test run against a recent enough version?

**Comment by iperdomo** [comment]
@jonase if you change some of the `exporterapplet` code, you need to make sure you update `flowdev1`

**Comment by muloem** [comment]
From what I see, the `flowdev1` is running a version of `exporterapplet` code from Jan 26th. But @jonase better verify that.

**Comment by rumca** [comment]
UAT is pointing at http://flowdev1.akvo.org, not sure if that has the latest code or if we need to redeploy?

**Comment by jonase** [comment]
@rumca flowdev1 runs the latest version of flow-services now so you can rerun the testplan.

**Comment by rumca** [comment]
tested and works as expected :+1:
