### ISSUE TITLE
Handling option and cascade codes and values in data exports 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2742]
# Context 
When exporting data we provide Salim with different data export options. One is **Data cleaning one** that is human readable and in a structure that allows Flow to import the data. The 2nd one is the **Data analysis export** that was meant for the data to be imported into another tool and used there. 

Secondly, the Salim has the option to define codes for options or cascades, meaning an option in an option question consist of code + value, for example 1:yes, 0:no. If Salim created the codes for options in option questions or for a cascade, then at data exports in both export formats he gets the code and value in one cell. 

# Problem 
We have received feedback that when importing data into SPSS Salim has to go through each column and split the text to column to divide the code from the value. Thus making our intention to make this format machine readable not fulfilled. 

## Partner feedback 

"The excel still gives the value codes and the value labels in 1 cell together. It would really help and save a lot of time for the importing of excel data into SPSS, if the value codes and the value labels would be in different cells. Otherwise we have to do column by column “text to column” in Excel to prepare the data. SPSS works with numbers, and not well with text in a cell. As you can imagine, this prep takes a lot of time – especially if you have a large questionnaire. I remember that for the baseline data for my project it took me about 5 hours to prepare the excel to be able to export it to SPSS properly, because I needed to do text to column for about 100 columns, and excel only allows you to do 1 column at a time." 

"Data analysis exports require manual deletion or replacement of text into codes to inject data into statistical package e.g. SPSS. Would prefer 2 analysis exports: pure code & pure pure text." 

# Opportunity 
We should consider: 
- either providing the option for Salim to decide before generating the file is he wants codes or values
- or by default, if you export data with Data analysis structure you only get the codes (same principle as we do with variable names vs question text) 

# Extra 
This is a different topic, but I thought might be handy to mention. Another feedback we received for the Data analysis export is if Salim can decide if he gets repeated question groups in row, sheets, or columns. 

@stellanl and @muloem thoughts?

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/data-analysis-export

**Comment by janagombitova** [comment]
@stellanl this is the issue we discussed in our planning session about handling how we export option and cascade codes and to apply the same rules on how we handle variable names and question text

**Comment by stellanl** [comment]
Estimate for these two cases: 
1. In Data analysis format, show only code if defined, otherwise show only value. Keep current handling for other formats. An hour's work for me.
2. Let user choose between current state and 1. Adds UI and parameter handling to the above. At least half a day for Charles and me.

**Comment by janagombitova** [comment]
I would go for option 1 for now as we follow the same rule for the users as with questions and variable names and do not give them another decision to make. If we add the option to choose we could say: choose how you want questions to show, codes to show, repeatable question groups to show. I would start small and we take it further once we know more

**Comment by muloem** [comment]
If option 1 avoids creating yet another thing to choose for the user (without leading to more confusion of course), then I say we go for it.

**Comment by stellanl** [comment]
Since comprehensive format is identical to analysis format (except for the stats-and-graph page), should it also output codes multiple-choice answers?

**Comment by janagombitova** [comment]
For the sake of maintaining consistency, I would say yes.

**Comment by janagombitova** [comment]
Perfecto!
