### ISSUE TITLE
Pre-load surveys when the dashboard loads

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#2754]
At the moment we're only pre-loading surveyGroups and cascade resources when the dashboard loads. After #2505, we realised the needs to also pre-load surveys in order to be able to generate a report's path without making additional calls

**Comment by kymni** [comment]
##Test plan
* Inspect the XHR requests that are executed when dashboard is first loaded
* Confirm that call to surveys end-point is one of the requests executed

**Comment by valllllll2000** [comment]
All works as expected!
