### ISSUE TITLE
Copy stripped off jar file to staging folder

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2756]
During the CI build of flow, a staging folder is created that is eventually zipped up and later used by the deploy scripts to install a specific version of the application.  The command to generate this staging folder strips off a file `appengine-api-1.0-sdk-<x>.jar` that is not provided in the GAE runtime for backend instances and causes the backends to fail.  We will eventually remove backends (see #2694) but for the time being we copy this file for the deployment of backends.

**Comment by kymni** [comment]
Nothing to test on client side
