### ISSUE TITLE
Bulk upload page UI weird

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2762]
There seems to be some odd stuff happening on the bulk upload page. There is a large white space between the footer and the page items taking away space where the page items could be. Plus when scrolling up, the bulk upload items do not seem to go behind the tabs and subtabs. 

<img width="1261" alt="screen shot 2018-07-04 at 11 29 54" src="https://user-images.githubusercontent.com/12456965/42269128-9c8c9a64-7f7d-11e8-858d-2d8502c70500.png">
<img width="1258" alt="screen shot 2018-07-04 at 11 30 03" src="https://user-images.githubusercontent.com/12456965/42269129-9ca66606-7f7d-11e8-9cb3-db1a34c68595.png">

**Comment by kymni** [comment]
Addressed in #2764
