### ISSUE TITLE
Upgrade mapbox.js library

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2769]
We are currently using mapbox v1.6.1 that is based on leaflet.js 0.7.2.  The latest version of mapbox is v3.1.1 that includes improved features provided by leaflet.js and other new leaflet plugins, e.g. clustering plugins, placemarker plugins, and vector maps.  We could build a simple prototype to see whether it takes a lot of effort to upgrade the library.

**Comment by muloem** [comment]
## Test Plan

Should be covered under regression testing with the map

**Comment by janagombitova** [comment]
![screen shot 2018-08-21 at 15 14 18](https://user-images.githubusercontent.com/12456965/44403509-f3262780-a554-11e8-9011-a94eaa833387.png)

On the private map all works well. But the public map has a funky behaviour. It's zoom level is set to default at 20km/10mi so I cannot see the entire world. Both default zoom level should be the same. The internal one is set for 5000km/3000mi. The public map should be the same 

@bogere can you fix this for the release?

**Comment by janagombitova** [comment]
Fixed.
