### ISSUE TITLE
Rename "Export reports" tab to "Exports"

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-flow#2773]
Rename "Export reports" tab to "Exports"

This implies that the "Generated exports" shd also be changed to "Exports" to keep some consistency (in actuality the list handles both generated and generating exports..)

**Comment by Kiarii** [comment]
## Rename "Export reports" tab to "Exports"

**Comment by Kiarii** [comment]
### 'Enable' export types

<img width="1085" alt="screen shot 2018-07-09 at 15 33 49" src="https://user-images.githubusercontent.com/12692444/42450815-0e8e5350-838e-11e8-8d71-c78932135ae2.png">


report types look disabled by default until a mouseover reveals otherwise; these need to have an 'activated look' the selected one can have its border or background change to blue to indicate the selection..

**Comment by Kiarii** [comment]
### Unify loading/progress indicators

We have two different progress indicators in flow;
<img width="256" alt="screen shot 2018-07-09 at 17 00 54" src="https://user-images.githubusercontent.com/12692444/42500546-44eeaed4-843a-11e8-9980-b1ecc7a9b31b.png">
<img width="214" alt="screen shot 2018-07-10 at 12 09 41" src="https://user-images.githubusercontent.com/12692444/42500549-4548ad9e-843a-11e8-9800-d9eb2f034b77.png">

Besides using yellow for these may be seen as some kind of warning so it may be best to result to a neutral color e.g. black

**Comment by Kiarii** [comment]
### simplify export name

An export need not have its type as its first part of the name if the filename also includes it in addition to the form id

<img width="509" alt="screen shot 2018-07-10 at 12 26 05" src="https://user-images.githubusercontent.com/12692444/42501549-9ce7c042-843c-11e8-8e6b-4f488b8ba457.png">

It is enough to have the "type-id.format" as an export type

**Comment by muloem** [comment]
@kiarii each of these comments can be split into a separate issue to make them more concrete to work on. Can you split them please?  The exports comment already has an issue and @kymni is working on it.

**Comment by janagombitova** [comment]
Duplicated and handled here: https://github.com/akvo/akvo-flow/issues/2731
