### ISSUE TITLE
Allow to use barcodes as data point names 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2776]
# Context 

When creating a form Petra can set a question to be used as data point name. This means that the answer to the question will be added to the name of the data point. The name is used to identify the data point, especially for monitoring cases. 

Currently free text, number, option, cascade questions can be used as data point name. 

# Opportunity 

Often barcodes or QR codes are captured as part of a data set. The barcodes that are scanned are sometimes attached to the subject of the data collection, like a water pump and then used to ensure the enumerator is updating the correct data point. When in the field Alphonso would have his list of data points, scan the barcode and see then search for it in his list, find the Flow ID and search for that in Flow. 

The idea is to be able to add use answers to barcode questions for the data point name, to make it easy for Alphonso to find the right data point. Eventually we can consider how you can find a data point in the list by scanning the barcode - another iteration, once we understand more the update of barcode identification. 

# Next steps 

Enable the setting Use as data point name for Petra with the barcode question. 
Ensure the barcodes show properly in the data point name. 
If there is more than one barcode scanned for the question, handle it in the same way as we do with cascades.

**Comment by kymni** [comment]
## Test Plan
* Create/edit a survey
* Create/edit a question of type bar-code
* Confirm that option to use the question as data point name is available

**Comment by valllllll2000** [comment]
Works perfectly!
