### ISSUE TITLE
Handle option questions without options on export

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2777]
Same as akvo/akvo-flow-services#221. We will try to outlaw option questions without any options in #2118, but some are/will be around, causing an NPE at line 1130 of GraphicalSurveySummaryExporter.

https://github.com/akvo/akvo-flow/blob/f38df5b06bf1422ad6e21d57125a908b5a639e70/GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java#L1118-L1131

**Comment by stellanl** [comment]
Test plan:
1. remove all options from an option question in a form with some answers.
2. run a report, it should work.

**Comment by valllllll2000** [comment]
Tested it with a survey of mine, see last 2 entries on the screenshot:
![screenshot from 2018-07-31 16-56-09](https://user-images.githubusercontent.com/923280/43468128-7b9e64ba-94e3-11e8-9925-482d3f6a9b98.png)
As you can see the last report failed, I cannot open it and it's title is diferent from all the others. The report right below it was done before deleting all options from the multioption question number 1. This question is mandatory not sure if this is the issue. This survey also contains another empty question option, the question 2 and it is not mandatory. The empty question 2 did not pose any problems for the reports. I tried searching for logs and did not find anything at all.

**Comment by stellanl** [comment]
No, I cannot find anything in the services logs for that time. Mystery. The error message is so short it is almost useless...

**Comment by valllllll2000** [comment]
Ok, after services redeploy, all works as expected
