### ISSUE TITLE
Have a timeout for report generation

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2779]
If report generation fails for some reason, the report will stay in the list as IN_PROGRESS until deleted. A timeout of, say, an hour or a day that will set them to FINISHED_ERROR state could be implemented, perhaps as part of the cron job that deletes them after a year (#2638).

**Comment by muloem** [comment]
We have the report generation task that kicks off the report generation and requeues the report if the initial generation returns any other codes besides 4xx.  Maybe we can add a limit to the retries here and say after 5 retries we consider this a completely failed report and set to `FINISHED_ERROR` state.

**Comment by stellanl** [comment]
Test plan:
1. Run the local server, standard docker-compose.yml (with dummy flow-services).
2. Start an export.
3. The logs should show that the task tried to start the report 5 times, roughly 30s apart and then gave up.
4. The report list should show it as failed.
