### ISSUE TITLE
Importer should verify all other-column headers

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2780]
It seems an Excel file straddled the addition of the other-column while out for data cleaning. On import, a question in group 1 had no other-column but a question in group 4 did. This made the importer think that all option questions would have an other-column, and grabbed unrelated stuff for those that did not. This particular case should not happen again, but if someone were to add the option of other to an existing question while the data is outside Flow for cleaning, this will happen again. So the importer should become smarter. Also, making the export+import use only published form versions would reduce these sorts of problems in general. See #2285.

**Comment by muloem** [comment]
> It seems an Excel file straddled the addition of the other-column while out for data cleaning

I don't understand what you mean here. So the `Other` column was added or was deleted during data cleaning?

**Comment by stellanl** [comment]
What I *think* happened:

1. User exported data.
2. We released a new version of the importer, where the existence of *any* other-column indicates that all option questions than can have other will have an other-column.
3. User added an other-column for a question where there was such data.
4. User imported data; the importer assumed there were other-columns wherever other was allowed, and read them.

**Comment by stellanl** [comment]
What can still happen is that a user changes a question to allow other between the export and the import of cleaned data. So the importer should check the header before assuming that a column is an other-column.

**Comment by muloem** [comment]
ok. So we need to correctly identify whether a column is really an `OTHER` column before importing its data as part of OTHER?

**Comment by stellanl** [comment]
Yes

**Comment by stellanl** [comment]
Of course, believing that the current survey state is identical to the one(s) published/collected/exported/whatever is a bad idea. Which is why #2285

**Comment by janagombitova** [comment]
Considering this is merged I assume it is also released and the issue can be closed. @stellanl and @valllllll2000 is that correct?

**Comment by valllllll2000** [comment]
I would say yes
