### ISSUE TITLE
Fix reports path

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#2782]
We're currently using the surveyList property of survey groups to generate the path of the form that a report is based on. This is not reliable as the property does not always hold all survey's forms. With #2754, we'll have the surveys in the client store so we can use that to generate a more reliable path.

**Comment by kymni** [comment]
## Test Plan
* Generate different report types
* Confirm that all reports on the list have an absolute path from the top folder to the form name

**Comment by valllllll2000** [comment]
Works as expected!
