### ISSUE TITLE
Requesting multiple exports after each other results in same export 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2785]
Geert reported an issue via reamaze that after requesting an export and then another one right after that for a different form he got to exports for the same form, the 1st he requested. 

I was not able to reproduce the problem. 

![reportbug 2](https://user-images.githubusercontent.com/12456965/43001871-30d497b6-8c27-11e8-898b-b7495ff4f133.gif)

**Comment by kymni** [comment]
Still not able to reproduce so suggestion is to close this

**Comment by janagombitova** [comment]
Ok. If it happens again we can always reopen the issue
