### ISSUE TITLE
simplify export name

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-flow#2793]
An export need not have its type as its first part of the name if the filename also includes it in addition to the form id

<img width="509" alt="screen shot 2018-07-10 at 12 26 05" src="https://user-images.githubusercontent.com/12692444/42501549-9ce7c042-843c-11e8-8e6b-4f488b8ba457.png">

- It is enough to have the "type-id.format" as an export type
- In addition, the double coding: bold + all caps can also dropped for normal type; first cap + small letters

**Comment by janagombitova** [comment]
The current title (as users call it) contains the export type and then the file name that holds again the export type-form id. 

Can we simplify things by having in this top row (title) only the file name, that holds the export type-form name-form ID? This will resolve the issue of having export type double and having the double coding.

Furthermore some users complain that after downloading the file the their computer, they find it hard to recognise what data it is by having only the form name in the file title and thus are requesting the add the form name there too. If this will make the file title too long, we can consider: 
- dropping the ID - but then we risk if the form name changes how will you be sure this is the form. The question is if this is a relevant concern? 
- making the form name shorter
