### ISSUE TITLE
Enhance error messages when publishing cascade resources

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#2794]
The current approach to notify a user of a cascade resource publishing error is just to add a new `Message` with the string: `Failed to publish cascade resource <cascade-resource-id>`.

See: [akvo-flow](https://github.com/akvo/akvo-flow/blob/v1.9.34/GAE/src/org/waterforpeople/mapping/app/web/ProcessorServlet.java#L166-L167)

Becasue Flow services knows a bit more on the broken data, we can add a _hint_ to the user to help her/him fix the cascade resource. 

Example: We don't allow 2 different nodes to have the same `name` and the same `parent` _but with different codes_.  e.g.
```
01,First,011,Secondone
01,First,012,Secondone
01,First,013,Third
01,First,014,Fourth
```
But we can't have this constraint in the Datastore, so the symptom of the broken data happens when publishing the cascade. In Flow services: `SQLException [SQLITE_CONSTRAINT]  Abort due to constraint violation (columns name, parent are not unique)  org.sqlite.DB.newSQLException (DB.java:383)`

Since we insert the nodes sequentially we can notify the user of the failure when publishing but also adding which `node` is the broken one.

Related to: https://github.com/akvo/akvo-flow-services/issues/222

**Comment by valllllll2000** [comment]
Not sure what to test here. I have tried to add a cascade with a duplicate name and code and nothing happens, node is not added but also no error message.

**Comment by valllllll2000** [comment]
Tried importing the cascade 
`Cataluña,Barcelona
Cataluña,Lleida
Cataluña,Cataluña
Cataluña,Tarragona
Cataluña,Tarragona
Madrid,Madrid
Madrid,Guadalajara
Valencia,Valencia
Valencia,Alicante
Valencia,Castellón
Aragon,Zaragoza
Aragon,Huesca
Aragon,Teruel`
did not get any error message. Please describe what is supposed to happen.

**Comment by valllllll2000** [comment]
tried again after services redeploy, still no error message when importing cascades with duplicated nodes. Duplicated node just gets silently ignored
