### ISSUE TITLE
Group copy never ends dialog

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#2802]
Copying a group the "copying" dialog stays on forever. If we leave the screen and come back the dialog is gone and copy completes successfully. This is more of a cosmetic issue.

**Comment by valllllll2000** [comment]
![screenshot from 2018-08-02 11-24-05](https://user-images.githubusercontent.com/923280/43575862-2abc7756-9648-11e8-893b-d2e51f84b049.png)

**Comment by valllllll2000** [comment]
Also happens in production

**Comment by kymni** [comment]
## Test plan
* Copy a questions group
* Checks for change of state from `COPYING` to `READY` should run every 5s during which a `Copying` animation on the copied question group should display then disappear when the questions group is ready

**Comment by kymni** [comment]
Status never seems to change from `COPYING` to `READY` and inspecting logs reveals that request never completes

**Comment by kymni** [comment]
Querying a copied qg by its ID to identify if its status has changed always returns status as `COPYING` so will have to query all qgs in survey and pull individual qg's status from that

**Comment by kymni** [comment]
Guess this is done
