### ISSUE TITLE
Datapoint delete randomly fails

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#2806]
When running regression tests https://github.com/akvo/akvo-flow/wiki/Basic-Regression-Testing#inspect-data--monitoring, deleting datapoints sometimes is just silently ignored. Looking at the logs, DELETE is not called for some reason and the datapoint remains in the list.

**Comment by valllllll2000** [comment]
I have just tested with akvoflow-dev2 with v1.9.32-84-g305f6b5 and delete did not fail.

**Comment by muloem** [comment]
To test on the pilot instance to see if it behaves the same.

**Comment by valllllll2000** [comment]
I have tested on pilot and delete works well. Now tested again on uat1 and it seems to work...

**Comment by valllllll2000** [comment]
Closing for now as seems to working fine today
