### ISSUE TITLE
Deployment from Docker container may be missing a jar

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2816]
I did a deployment to akvoflow-61 from the v1.9.35 tag, as described in the README.md. (I needed a temporarily higher instance class.)

./switch_tenant.sh akvoflow-61
docker-compose up --build -d
docker-compose exec -u akvo akvo-flow ./dev-deploy.sh

I had to authorize (once) and it seemed successful.
But looking in the logs the dataprocessor backend did not start, because of a missing class:
java.lang.NoClassDefFoundError: com/google/appengine/api/utils/SystemProperty

According to SO, this can be due to a missing jar: appengine-api-1.0-sdk.jar

**Comment by muloem** [comment]
The issue copying the jars was handled in #2759 but only for the normal deployment process.  We probably need to unify the two so that the dev deploy also uses the same code

**Comment by valllllll2000** [comment]
@muloem is there a way I can test that?

**Comment by valllllll2000** [comment]
deployed to local dev server as per readme. All works fine
