### ISSUE TITLE
Feauture request: Non-concatenated Multiple Option Results

### ISSUE THREAD

**Issue by JosjeS** [akvo/akvo-flow#282]
Feature request submitted by Ben Mann on Tender:

When exporting data from survey questions that allow multiple responses, all selected responses for a question are concatenated into a single field. For example:

Question: When do you wash your hands?
Response: Before eating | After using the bathroom | After handling trash | Before feeding a baby

This is helpful for combining all answers into a single variable field for data storage, but it makes analysis very difficult. It requires a good bit of work to separate out the responses into separate fields using text-to-column in Excel (or other similar features in other programs) and manipulating the data so each possible response has its own field for each instance. Is there a way to store these responses as a binary response or export as individual variables? See my screen shots for more info. The final manipulated sheet took a couple hours of cleaning to concatenate and sort responses into correct columns for 300 surveys.

**Comment by janagombitova** [comment]
https://github.com/akvo/akvo-flow/issues/1605 duplicate
