### ISSUE TITLE
New reports page not loading for big tenants

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-flow#2823]
The new reports page is making a call to /rest/surveys that is timing out for big instances, as it takes more than 60 to build the response for **1.6k** surveys.

Possible causes a possible cause is that for each survey, Flow [tries to retrieve](https://github.com/akvo/akvo-flow/blob/e02b8134b95f2a664f965f8d81712e2371aa26a6/GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyRestService.java#L79) a [SurveySummaryInstance](https://github.com/akvo/akvo-flow/blob/91485e66f757eb3c13dd528fdc8627c7637628b9/GAE/src/org/waterforpeople/mapping/analytics/domain/SurveyInstanceSummary.java#L32), causing more than a thousand calls to the GAE storage. This is a typical n+1 problem.

The only piece of data returned to the Dashboard is the [instanceCount](https://github.com/akvo/akvo-flow/blob/de487f485c45b8c54bfff0087eae6902ac0b82ac/Dashboard/app/js/lib/models/models.js#L154), which is not used at all.

Digging a little bit deeper, it looks like SurveySummaryInstance is just read in this REST endpoint, so the proposal would be to delete the SurveySummaryInstance and all the code around it.

### Additional work

1. Do not call /rest/surveys until the data is actually needed. 
2. Review the performance of the [dto conversion](https://github.com/akvo/akvo-flow/blob/e02b8134b95f2a664f965f8d81712e2371aa26a6/GAE/src/org/waterforpeople/mapping/app/web/rest/SurveyRestService.java#L76)

**Comment by kymni** [comment]
Client-side issue was addressed under hotfix 1.9.36.2. Back-end issue should be fixed by #2841

**Comment by kymni** [comment]
Surveys loading slightly faster. Loaded >900 surveys in 25s
