### ISSUE TITLE
Loading in submissions in Inspect data and Monitoring 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2827]
When you select the survey and form you want to view data for in the Inspect data tab and hit Find, Flow starts getting the submissions. You see the loading spinner for a second or two. Getting the submissions is relatively fast but sometimes once you hit Find, you see the spinner, then it disappears and the list does not show right away giving the impression that you "did not hit Find properly". 

![loading](https://user-images.githubusercontent.com/12456965/44399479-08e12000-a548-11e8-94f0-e1858a6fc8eb.gif)

While the list is loading we should also show the loading spinner in the screen until loading the survey list is fully finished and visible in the screen to give the user an indication that something is happening.

**Comment by kymni** [comment]
**Issue** - when fetching multiple records, we're switching the flag that detects completion before saving the result to the client data store instead of the other way round
**Fix** - switched the order

**Comment by janagombitova** [comment]
I checked uat1 and the issue is still present on inspect data tab. I do not see this as a showstopper for the release but we should not forget to tackle it.

**Comment by kymni** [comment]
## Test plan
* Select a form in the inspect data tab then click "Find"
* If form has submissions, they should be listed immediately after the loading animation disappears

**Comment by valllllll2000** [comment]
works as expected
