### ISSUE TITLE
Remove Notifications functionality

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2831]
# Context 

# Why
We have not been supporting this feature for at least three years now. In this period we only received a message from one partner asking why it stopped working and never fully fixed the functionality

## Possible benefits 
The notifications were meant for the project managers to see if data is coming in by sending regular data exports, or informing about submissions. I am not sure what survey approval did. We do know that users are keen on seeing data coming in or getting data out on a regular basis but there are more questions here to research and understand to provide a better solution. 

## Current situation
Currently the feature is not being used and if users open it they are confused on what is should do. We should aim to simplify the user experience and remove what we do not need or support. 

# Next steps 
- see if we can check if anyone is using the feature 
- if yes, contact partner about the removal of the functionality
- remove from UI 
- remove fully the functionality

**Comment by stellanl** [comment]
Some of our older instances have hundreds of subscriptions in the DS. Which does not say if anyone would read them...
WFP: 275
Lifewater: 281
WHH: 16
SSH4A: 15

**Comment by janagombitova** [comment]
Reopening as we should simply do this. The feature has not been supported and is not used.
