### ISSUE TITLE
Selecting Caddisfly tests in forms 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2842]
# Context

Original issue is here: https://github.com/akvo/akvo-product-design/issues/266

Currently we have in Flow quite the long list of Caddisfly test types. We organised it by Water and Soil type, but as the list and diversity of tests will grow, we need to make the selection more clear and understandable to users.

# Problem

Salim first selects Caddisfly as a question type and then he selects the test type. 
![caddisfly](https://user-images.githubusercontent.com/12456965/44836901-73751880-ac38-11e8-8648-f944751d4f16.gif)

The select test dropdown list is super long and hard to work with. 

# Opportunity 
How might we break down the long list to make it easier for users to select which test they want? The implementation should also ensure that anytime a new test is added to the Caddisfly json file and follows the agreed structure that it well shows in this UI.

**Comment by janagombitova** [comment]
The current naming convention holds a few parts that we can use to break the one dropdown to cascades as @stellanl suggested. Here is our current list

<img width="1242" alt="screen shot 2018-08-31 at 08 59 39" src="https://user-images.githubusercontent.com/12456965/44897600-851ff400-acfc-11e8-96e1-7c71ea78ac3e.png">
<img width="1276" alt="screen shot 2018-08-31 at 09 00 02" src="https://user-images.githubusercontent.com/12456965/44897603-86512100-acfc-11e8-8d58-3c6906726538.png">
<img width="1278" alt="screen shot 2018-08-31 at 09 00 16" src="https://user-images.githubusercontent.com/12456965/44897607-87824e00-acfc-11e8-8007-4df1ad3c607e.png">

The naming holds these 4 categories: 
- what the testing is for: water or soil 
- what testing method is used: Sensors, Test strips, Colorimetry, Miscrobiology
- brand 
- parameter

**Comment by janagombitova** [comment]
@muloem Who from Flow team will handle this issue and can you connect with @nhternup who is prepping the Caddisfly side of things: https://github.com/akvo/akvo-caddisfly/issues/204?

**Comment by janagombitova** [comment]
After a few rounds of iterations with Hans, Mert, @nhternup and @muloem we decided to make the following changes: 
- the one currently dropdown should be split to a cascade with 5 levels (example on uat1 as a cascade _Option 3 Caddisfly): 
   1. Category 
   2. Single or multiple parameters 
   3. Parameter 
   4. Test type 
   5. Details 
- the cascade will filter out the options for the following level based on the option selected in the level before
- the flexibility we have today, where the Caddisfly team can add any tests to the json file without needing any changes or redeployment on Flow side, must remain 
- Nischal ensured all the tests have the following categories in the Caddisfly json file: https://github.com/akvo/akvo-caddisfly/issues/204#issuecomment-437261198

https://user-images.githubusercontent.com/12456965/48193508-e5f62900-e34a-11e8-860a-502ea6976bb3.png

**Comment by kymni** [comment]
@janagombitova what property should we use for the Details?

**Comment by kymni** [comment]
That would mean concatenating `name`, `chemical`, `unit`, and `range` sub-properties under the `results` array property

**Comment by janagombitova** [comment]
After taking a look at the implementation on flowaglimmerofhope, Mert and Nischal cleaned up the names of the tests, which updated automatically - Perfect! 

They also suggested that the one item that is unique per test and can help users confirm they made the right selection is the reagent code. This is not available for all tests and other tests might have two numbers. Nischal added this to the json v2 file as 'reagents'. 

Can we add this to the Details dropdown - so to show the reagent code with the other properties that we show now in that dropdown, if the code is defined?
![screen shot 2019-01-30 at 11 26 34](https://user-images.githubusercontent.com/12456965/51975450-88bdcf80-2482-11e9-95e5-a423ff18a1eb.png)

**Comment by kymni** [comment]
## Test plan
* Create a caddisfly question type
* Confirm that selecting a test type no longer presents you a long list of tests to choose from but instead allows you to filter by sample > name > brand > details

**Comment by kymni** [comment]
Works as described

**Comment by kymni** [comment]
Reopening to address `reagents` code not displaying

**Comment by muloem** [comment]
Works as expected! 👍
