### ISSUE TITLE
Assignment page scroll

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2845]
# Issue 
You have a long list of assignments (organised alphabetically) and you scroll down to find yours. You click to open the assignment, Flow opens the assignment in the bottom of the screen rather than on top of the page again. 

![assignment](https://user-images.githubusercontent.com/12456965/45086953-b2a5dc80-b104-11e8-94c1-f5826d31088e.gif)

Created via Reamaze:

Link: /admin/conversations/akvoflow-support-request-number-142764-from-thomas-at-akvo-dot-org

# Change 
When navigating between pages make sure we always start on the top of the page

**Comment by Kiarii** [comment]
design status: a go.
An assignment page should present its content from the top

**Comment by Reza-Rajabi** [comment]
I just set up the environment and added some fake stuff to the Assignment List, and now I can see the issue. Please let me work on this.

**Comment by janagombitova** [comment]
Hi @Reza-Rajabi,

We are excited to hear you want to contribute to our open source tool. Please go ahead. Once you have the fix ready, just make a pull request and we will take care of the review.

**Comment by Reza-Rajabi** [comment]
I have been working on this issue for a while, and unfortunately, I was not successful to solve it. I was trying to add a mixin similar to [https://guides.emberjs.com/v1.10.0/cookbook/user_interface_and_interaction/resetting_scroll_on_route_changes/](url) like this:

```javaScript
//    mixins/resetScroll.js

FLOW.ResetScroll = Ember.Mixin.create({
    activate: function () {
        this._super();
        window.scrollTo(0,0);
    },
});
```

and then apply the mixin in the related root like this:

```javaScript
// router.js line 28:

root: Ember.Route.extend(FLOW.ResetScroll, {
//...



//or router.js line 224:

editSurveysAssignment: Ember.Route.extend(FLOW.ResetScroll, {
//...


```

which didn't work. I even tried to install npm package [https://www.npmjs.com/package/ember-reset-scroll](url) for this issue and then do something similar as above, yet didn't work.

So, I am wondering if I am out of the picture?

**Comment by janagombitova** [comment]
Hi @Reza-Rajabi, sorry for the later reply. We were in the middle of a larger release. I will ask my colleague @muloem to take a look and see if he can point you in the right direction. Mulo can you check Reza's question? Thanks
