### ISSUE TITLE
No Users tab on local enviroment

### ISSUE THREAD

**Issue by nickmorss** [akvo/akvo-flow#2846]
Have pulled the code and run the app via docker, super simple. However when i run the application and login with the provided default user, and checked the 'login as Admin' checkbox, i seem to be missing the User Tab. Am i missing a configuration setting or something? 

Gif below
![no-user-tab-akvok-2](https://user-images.githubusercontent.com/1162886/45091439-5e9df680-b10a-11e8-9aaa-e25188a121e8.gif)

**Comment by janagombitova** [comment]
User on the API confirmed he is all set with the user tab.
