### ISSUE TITLE
Remove public/private status for data from backend

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2856]
# Context 
As part of the research done around user authentication, we also learned about the current concept of public/private status of submissions (https://github.com/akvo/akvo-flow/issues/2559#issuecomment-376512791).

Currently a survey can be set to public or private. This means that all submissions made to the forms in the survey are shown on Flow's public map (the one showing if you are not logged in) if they are set to public. By default all surveys are set to private. 

In the linked issue we learned that Flow's public map is not used as a data sharing platform and we also do not want to pursue this value further. We rather look at connecting with established data sharing platforms, as we have done with WPDx. This decision then makes the public/private setting obsolete. Furthermore, with moving the mapbox maps and adding survey filters to the private map, we no longer show any data on the public map.

# Opportunity 
All these changes and research gives us good ground to stand on to remove this functionality from Flow. 

# Next steps 
Remove everything related to public/private status around data everywhere.

**Comment by muloem** [comment]
@janagombitova Should we consider moving forward the landing page issue?

**Comment by janagombitova** [comment]
We have it like that currently on some instances as they have all their surveys private. 

My thinking was to 1st move the user authentication and with that our landing/log in page will change too and then we remove the entire concept of the public map and the public/private setting. What do you think?

**Comment by Kiarii** [comment]
design status: a go. it makes sense to remove that setting given that its value has diminished. this further reduces the number of survey settings that a user has to pay attention to :)

**Comment by stellanl** [comment]
There is a design issue with the /placemarks endpoint. It currently shows the list differently depending on if the user is logged in or not. If not, only the public data points are listed.
When we remove the distinction, what should we return when the user is not logged in? Nothing? We could completely protect the endpoint.  Or everything?

**Comment by stellanl** [comment]
Since the landing page map was removed and the /placemarks endpoint is protected like other /rest/ endpoints, /placemarks now lists all.

**Comment by janagombitova** [comment]
The status no longer shows in the UI on UAT1. Is there more that needs to be done to **fully* remove the status to close this issue?

**Comment by janagombitova** [comment]
@muloem why did you reopen this issue? Can we close it?

**Comment by janagombitova** [comment]
@muloem bump

**Comment by muloem** [comment]
We still have some data about private/public status in the backend but I guess we can handle that separately. 👍

**Comment by janagombitova** [comment]
In that case, I am reopening it and moving to the backlog. The issue is to remove the data also from the backend so all trace of the private/public status is gone
