### ISSUE TITLE
Track changes on the instance

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2860]
# Context
Flow is used by large organisations and many users. What users can do is restricted by their roles and permissions but because the work around data is still a collaborative effort, especially survey design, it happens that more than one person has access to a survey or a dataset. 

We are target large organisations and aim to make using Flow simple in their project data tasks. This also means understanding what has happened to a survey or data and what has changed. Having a log of changes helps Salim and Petra collaborate and avoids extra efforts in trying to figure out what has happened to a survey, user role or dataset. 

# Problem
- impossible to know if someone has edited a form, deleted a submission, changed a user permission, etc
- impossible to tell if something is a user action or a technical problem (why does this monitoring data point not show the registration form but does show the monitoring ones)

# Next steps
Research user and technical needs

**Comment by muloem** [comment]
Currently we have an `EventQueue` entity that is a sort of tracker for changes that happen on the instances.  It is not designed with the tracking described here in mind but may be something we can build upon to create such a log.
