### ISSUE TITLE
Remove CartoDB maps

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#2867]
Since introduction of filtering on Mapbox maps, having CartoDB has become redundant hence the need to remove

**Comment by janagombitova** [comment]
@iperdomo pointied out that once we stop fully supporting Carto maps we can also remove the servers from Cloud VPS. This comment is to note that down so we do not forget

**Comment by muloem** [comment]
On the code side this is more a cleanup but on the servers side, @oriol and @dlebrero already partially cleaned up.. I am not sure about cartodb servers but the unilog was shutdown I believe.

**Comment by dlebrero** [comment]
@muloem Can you please confirm that we can remove the CartoDB servers?

**Comment by muloem** [comment]
Confirmed. Yes, we can remove them. 👍

**Comment by kymni** [comment]
Will pick up the code cleanup

**Comment by kymni** [comment]
## Test plan
Not testable on client side. ctrl+f "carto" maybe? ¯\\_(ツ)_/¯
