### ISSUE TITLE
Geoshape attributes are by default set to `true` on non-geoshape questions

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2877]
On questions that are not selected as geoshape type questions, the geoshape attributes are set to true by default.  This should not be the case since these properties would only be applicable to geoshape questions and more over setting them to true is misleading e.g. when looking at the form export.  During question creation, it is expected that the relevant geoshape related attributes are set to false. 

<img width="490" alt="screen shot 2018-10-03 at 06 25 37" src="https://user-images.githubusercontent.com/533336/46389938-6a62e580-c6d5-11e8-93c8-603917c57259.png">

**Comment by stellanl** [comment]
This is where it happens: models.js L256

FLOW.Question = FLOW.BaseModel.extend({
.
.
.
  // Geoshape question type options
  allowPoints: DS.attr('boolean', {
    defaultValue: true
  }),
  allowLine: DS.attr('boolean', {
    defaultValue: true
  }),
  allowPolygon: DS.attr('boolean', {
    defaultValue: true
  })
});

**Comment by stellanl** [comment]
So how do we want this to work?

- Off by default - user has to set one or more of them if he makes it a geoshape.
- Off until geoshape - they are all set if the user switches the type to geoshape, and he can turn some off.

**Comment by janagombitova** [comment]
Ideally, you must select only one type per question. But I have a feeling that is out of scope here. So if we need to handle this in the current set up (you can have more than one type per question) then I would say: 
1. Salim selects question type - Geoshape 
2. No types selected by default - Salim has to decide which he wants (one or more)

**Comment by valllllll2000** [comment]
@janagombitova @stellanl I have been reviewing the PR and one thing worries me: if Salim quickly selects geoshapes, he thinks all shapes are allowed and does not pay attention, then he saves the question and publishes. When in the app, Enumerators will realise they cannot submit any geoshapes and if the question is mandatory they will not be able to submit the survey at all. Not sure if this is a good idea but maybe we can leave one of them on by default, the most frequently used?

**Comment by stellanl** [comment]
Then we need some JS code that triggers when they switch the type to geoshape. A better solution is to validate the question so Salim cannot save until it make sense.

**Comment by janagombitova** [comment]
I agree with Stellan that we should not allow saving a question if **no** type is selected.

**Comment by janagombitova** [comment]
The goeshape exports however still show 'Yesy' in the cells indicating geoshape is selected even thought it is not. See this example: [SURVEY_FORM-4130052.xlsx](https://github.com/akvo/akvo-flow/files/2514799/SURVEY_FORM-4130052.xlsx)

Shall we leave this issue open or create a new one to handle the exports?

**Comment by muloem** [comment]
This is for questions that existed already or even for those which have been newly created.  The ones that existed already will still have the setting as "true" which will be generated as "yes" otherwise any newly created ones should have blank cells.

**Comment by stellanl** [comment]
I could write a datascript to clear those flags in old data where the type is not geoshape. Would take about an hour.

**Comment by muloem** [comment]
That would resolve things but first confirm whether indeed newly created geoshape questions do not have that problem.  And then you can create an issue for the script but we will leave it for the next release cycle not this one.
