### ISSUE TITLE
Hide details panel and clear map tab question answer fields

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#2881]
Following #2680, when a point is selected, details panel is displayed and question answers loaded on it. When you select a different survey however, the details panel is not cleared until you select a different point whose details are loaded.

We should clear and hide the details panel when filtering folders/surveys/forms

**Comment by janagombitova** [comment]
Related issue: https://github.com/akvo/akvo-flow/issues/2351

**Comment by kymni** [comment]
## Test plan
* Select a survey on the maps tab then click on a point on the map
* The clicked point's details should show on the details panel
* Select a different folder/survey while still on the maps tab
* Details panel should clear and hide until you click on a new point

**Comment by valllllll2000** [comment]
works well
