### ISSUE TITLE
Geoshapes do not render correctly on maps

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2884]
With the 1.9.38 release we improved how data shows on Maps, however we did not handle correctly how we render geoshapes. These now show as string.

<img width="1257" alt="screen shot 2018-10-10 at 07 52 46" src="https://user-images.githubusercontent.com/12456965/46715725-8e886e80-cc61-11e8-8355-c4c8a840aab4.png">

The implementation should show them on a small map and showing the shape as well as the meta data on the shape with the option the preview the shape on the main map, as it was before. 

<img width="763" alt="screen shot 2018-10-10 at 07 54 41" src="https://user-images.githubusercontent.com/12456965/46715785-c42d5780-cc61-11e8-95b5-89173041527d.png">

**Comment by kymni** [comment]
We are doing a way with Carto maps [#2867] so it's just a matter of redeploying the affected instances with Mapbox maps

**Comment by kymni** [comment]
## Test plan
* Click on a point with a geoshape response
* Shape should be rendered on a map on the details panel

**Comment by valllllll2000** [comment]
Geoshapes now render as expected
