### ISSUE TITLE
Upgrade spring libraries

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2896]
We need to upgrade the spring-framework libraries to address reported security vulnerabilities in the ones we are currently using.

https://github.com/akvo/akvo-flow/network/alert/GAE/pom.xml/org.springframework:spring-core/open

**Comment by muloem** [comment]
The upgrade guide gives a list of changes that should be made.

* [Upgrading spring-security 3.x to 4.x](https://docs.spring.io/spring-security/site/migrate/current/3-to-4/html5/migrate-3-to-4-xml.html)
  * [ ] Change initialization for `accessDecisionManager`
  * [ ]

**Comment by janagombitova** [comment]
@muloem I guess we have keep this one open for the remaining part of the implementation, right? Or do you want to create a new issue?

**Comment by muloem** [comment]
We can keep it open for this round.
