### ISSUE TITLE
Question order incorrect

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2897]
# Issue 
The order number of questions is duplicated. You can have a form with two questions with the order number the same, 13 for example. After the form is published on the app only one of these two questions show resulting in incomplete data being collected. 

We tried to address this issue a while back but is seemed to have either resurfaced or is still there. 

Below are two cases. We first thought the issue is connected to long forms being created on unstance internet but the most recent example is a form of only 40 questions.

![screen shot 2018-10-22 at 14 03 24](https://user-images.githubusercontent.com/12456965/47291469-0eb8b780-d604-11e8-8bc9-11cc3c4accf9.png)

# Support tickets on Reamaze 

One case :
https://flowhelp.reamaze.com/admin/conversations/akvoflow-support-request-number-157473-from-deden-at-akvo-dot-org

Second case: https://flowhelp.reamaze.com/admin/conversations/akvoflow-fr-requete-de-support-number-157-841-de-leon-dot-jander-at-welthungerhilfe-dot-de

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/akvoflow-support-request-number-157473-from-deden-at-akvo-dot-org

**Comment by stellanl** [comment]
Hopefully the fix in #2911 will further reduce the problem.
It is not zero with the current strategy, however. Before the big change, when you added a question that renumbered N questions there were roughly N http calls, any of which might fail. Now there are only two, but the risk of just one succeeding is still there.

**Comment by janagombitova** [comment]
Thank you @stellanl. Let's close the issue then and reopen if it appears again
