### ISSUE TITLE
Question order fixup in publishing broken

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2911]
For instance, it cannot handle if question #1 is missing.

**Comment by muloem** [comment]
@stellanl Is there a way to fix or validate this also in the UI end? i.e. we should avoid sending questions with wrong or missing order values.

**Comment by stellanl** [comment]
It is fairly easy to test; add a question first in a group, let's call it "Redshirt". Use Cloud console (or locallly data store viewer) to find and delete it, which will not update the order values - they should now start at 2. Publish the form and check that the questions were renumbered correctly.

**Comment by janagombitova** [comment]
@stellanl can you test this one for me? And is this issue completed or are their follow up issues for it?

**Comment by stellanl** [comment]
Tested ok on akvoflow-uat1.
