### ISSUE TITLE
Shorten the time we keep asking for device files.

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2913]
Currently we stop (delete the DFJQ entry) after two years (or when the file arrives, of course). The /devicenotification calls use quite a bit of resources, especially on akvoflow-37, so we decided to shorten it to 1 year.

**Comment by janagombitova** [comment]
I assume this is also finalised and released with 1.9.40. Thus closing the issue. If work still needs to be done, @stellanl please reopen and comment.
