### ISSUE TITLE
Order forms chronologically on surveys tab - switch back to alphabetical ordering

### ISSUE THREAD

**Issue by kymni** [akvo/akvo-flow#2917]
Forms are currently ordered alphabetically by the `name` property. It is more logical to order them chronologically by the `createdDateTime` property such that the last created form will appear last on the list. 

On top of that users creating a monitoring survey are more likely to create the registration form first followed by the monitoring forms

**Comment by janagombitova** [comment]
Works well

**Comment by janagombitova** [comment]
@kymni After some feedback via support we hear that alphabetical ordered of the forms worked better for users. They user numbers to make sure the forms appear ordered as they want. With chronological ordering they lost control over which form shows 1st, 2nd etc. 

The ideal case would be that the Registration form always shows 1st. And the monitoring forms are ordered alphabetically.

**Comment by muloem** [comment]
When one clicks on _Add Form_ for a new survey, the form doesnt appear immediately.  When the UI is refreshed it appears.  I suspect it may be connected to these changes.  See GIF

**Create new form fails**
![create-survey-form](https://user-images.githubusercontent.com/533336/53477527-34a00e00-3a75-11e9-8981-a8e833a3b234.gif)




**Deleting the form also fails**
Also deleting of forms isnt obviously successful and only when refreshing we see that the deletion worked.
![delete-form](https://user-images.githubusercontent.com/533336/53477646-69ac6080-3a75-11e9-8bbd-6987ebd0930e.gif)

**Comment by muloem** [comment]
Works as expected! 👍
