### ISSUE TITLE
For new cascades code created automatically

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2926]
# Context 

Salim can create a cascade with or without codes. Codes are optional. If he has a cascade **with** codes, they only appear in the Data cleaning export in the shape `code:item` and in the Data analysis export as `code` in the answer cell. 

# Issue 

As codes are optional often Salim does not use them. They are more unused than used. But currently Flow gives a code to a cascade item automatically. The code is identical with the item. This happens for cascades created in the UI or imported. 

![cascade](https://user-images.githubusercontent.com/12456965/48605055-fbd3a180-e97b-11e8-82e5-c2a2dfdde0f8.gif)

Then this code, that Salim **did not** define himself shows in the Data cleaning exports. It also shows in the Data analysis export, but as it is identical with the item Salim did not notice. 

Here is an example Data cleaning export: 
[DATA_CLEANING-273699135.xlsx](https://github.com/akvo/akvo-flow/files/2588331/DATA_CLEANING-273699135.xlsx)

For now Salim can simply delete the codes from the cascade, republish the cascade and the form and continue. But in the Data cleaning export he then gets this: `:item`

<img width="409" alt="screen shot 2018-11-16 at 08 41 52" src="https://user-images.githubusercontent.com/12456965/48604974-bca55080-e97b-11e8-9706-920fc7f27c63.png">

Since the changes to the Data analysis export from 1.9.40 where we only show the codes, everything in those exports works fine. The issue is Data cleaning exports for cases where the user did not define the codes, why do they show? 

# Change 
We should not define codes if Salim did not create them himself.

**Comment by kymni** [comment]
Auto-generated code is not being sent when the user adds an item but is being returned by the end point so this is a back-end issue

**Comment by stellanl** [comment]
Not a bug as much as a deliberate change in issue #189.
https://github.com/akvo/akvo-flow/commit/761ade993ee495a8a97e4986e4984206ea849d11#diff-6bc67ca5d87c8b1e57bf32b12de56b3a

**Comment by stellanl** [comment]
Some parts levels to this:

- [ ] Go back to not showing code:name in the data cleaning format.
- [ ] Investigate if empty strings for code is acceptable everywhere.
- [ ] Stop setting code to name if code is empty on cascade node creation.

**Comment by janagombitova** [comment]
Like a charm
