### ISSUE TITLE
Form translations show twice in export

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2930]
# Context 
Salim can translate his form to one or more languages. These then show on the app and when exporting the form. 

# Issue 
A partner found a case when the form is translated to one language, but in the export some questions show the translation twice. 

## Details 
https://ssh4a.akvoflow.org/admin/
Nepal / HHA / HHA_BASELINE_HH QUESTIONNAIRE

<img width="1216" alt="screen shot 2018-11-28 at 10 27 42" src="https://user-images.githubusercontent.com/12456965/49142944-36352b00-f2fa-11e8-9f4c-789152bccb97.png">
<img width="1089" alt="screen shot 2018-11-28 at 10 42 13" src="https://user-images.githubusercontent.com/12456965/49142979-4a792800-f2fa-11e8-93e3-addabe69f3ae.png">

# Created via Reamaze:

Link: /admin/conversations/in-exported-sheet-translated-text-appears-two-times

**Comment by stellanl** [comment]
There are two nepali translations, one with code "ne" (as expected), and one with code "sw" (Swahili(!))
