### ISSUE TITLE
Signature images do not load on Maps

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2937]
When viewing submissions on Maps, the images for signatures do not load/show, even though they show well in Inspect and Monitoring tabs. 

![flow map signature](https://user-images.githubusercontent.com/12456965/50148347-95aea700-02b8-11e9-9fe9-a20a723b6c79.gif)

**Comment by kymni** [comment]
## Test plan
* Click on a point on the map tab with a signature response
* Confirm that the signature is displayed on the details panel

**Comment by kymni** [comment]
Not working, showing broken images. Investigating
<img width="1277" alt="screen shot 2019-02-06 at 12 04 08" src="https://user-images.githubusercontent.com/1155088/52330815-6b02e400-2a07-11e9-814a-f9f9e8562883.png">

**Comment by kymni** [comment]
Works now
