### ISSUE TITLE
Survey - form dropdown does not show in Exports page

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2938]
Multiple partners, using good stable internet, have reported the same issue: When exporting data the dropdown to show the folder, survey, form does not load making it impossible for them to export. 

![captura de pantalla 2018-12-18 a la s 9 57 36 a m](https://user-images.githubusercontent.com/12456965/50272492-43948f80-0438-11e9-9c8a-29d681fdcfcd.png)

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/akvoflow-support-request-number-172084-from-kwandolowski-at-waterforpeople-dot-org

**Comment by kymni** [comment]
Issue occurs when surveys are copied/moved. The forms' `ancestorIds` property does not appear to properly update with the new directory's ancestors and keeps the old survey's `keyId` as an ancestor which could have been deleted hence the error 

This issue's fix is to catch the error but a more robust solution is to do a data cleanup of the corrupted `Survey` type entities in the data store

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/akvoflow-support-request-number-171726-from-sarah-dot-bailey-at-sendacow-dot-org

**Comment by janagombitova** [comment]
Tested and it works like a charm 👍

**Comment by janagombitova** [comment]
@kymni Send a Cow just confirmed they still have the issue even after the release. See screen shots below that they shared with us just now: 

![image001](https://user-images.githubusercontent.com/12456965/50689043-632adb00-1028-11e9-8406-740ade2f059e.png)

**Comment by janagombitova** [comment]
Issue created for a more structural fix
