### ISSUE TITLE
Clean up Device list after a year 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2939]
# Context 
In Flow under the Device tab we show a list of devices with the Flow app running linking to this instance. The list show the devices connected recently on the top and with scrolling down expands to the past. 

# Issue 
As this list can be quite long for older instances it caused slower performance on the tab. It is also quite long to keep an over and when assigning the devices Salim has to go though the entire list to find the devices he needs, even though they might have connected last two years ago. 

# Opportunity 
As we have been receiving a lot of requests lately, to clean up the list to improve loading and user experience, why not implement the same rule we did with data exports - remove devices that have not connected in the last year from all the lists?

This clean up will also come in handy as a preparation for the overall assignments redesign to allow assigning data points (child of #2796)

# Created via Reamaze:

Link: /admin/conversations/request-for-clean-up-https-slash-slash-welthungerhilfe-dot-akvoflow-dot-org-slash

**Comment by stellanl** [comment]
Test plan:
- [ ] go into the GAE object store and modify a device to a have a lastBeacon date of > 2 years ago
- [ ] trigger the cron task execution manually, by accessing https://akvoflowsandbox.appspot.com/cron/croncommander?action=purgeExpiredDevices
- [ ] check the GAE logs to see that the cron task ran ok.
- [ ] check in the GAE object store that the device is gone.

**Comment by stellanl** [comment]
Could one year be a little short for some partners? If some devices only collect data around the same time each year, they might get cleaned up just as a yearly monitoring assignment has been made.

**Comment by janagombitova** [comment]
@stellanl from what I understood, we are cleaning up devices that last connected year ago, so idle devices. 

If a partner has a long term monitoring set up and they set it up at its beginning, the devices will have connected to Flow more frequently to sync the data and forms. Furthermore, usually a new assignment is created and they test and review the survey forms again if the timeframe betweeb the data collection rounds is so long. So I think we can try out a year and see if someone comes screaming.

**Comment by kymni** [comment]
Works!
