### ISSUE TITLE
Duplicated data point IDs

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2944]
Mert pointed out an issue to me on Lumen, where the dataset did not update because of duplicated data point IDs, as the error said. I found this odd as we should not get duplicated datapoint IDs within one survey. But I did find 4 cases of 2 submissions to the registration form being identical and with the same data point ID, but different Instance IDs.

# The case details

Instance: https://1wash-salone.akvoflow.org/admin/
Form: 1.2 WASH Monitoring - Water Quality > Final surveys > 7. Household questionnaire > Household questionnaire
Form ID: 128170001

In this form export (see highlighted rows in the attached file here: https://drive.google.com/open?id=1ME68zdtdZxDoaGnwmnEuRcqLYqlvFnD8) there are 4 cases of 2 identical submissions with the same data point iD and different Instance ID. They all come from one device: BON-CEDA-DAINKEH and submitter: PHILIP R DAINKEH. According to the Device list he is running 2.6.3 app version.

The duplicated data point IDs were:
s0jg-cgfv-qyh1
kwtd-8q3m-k8km
fqwb-eyfx-m2cq
e0h8-cceq-raqe

If you look at the data they are exactly the same: same duration, same time stamp, same answers, as if we just created a copy of the submission. 

# Steps I took
In order for Mert to continue with the analysis I removed the duplicated submission for each datapoint. So there are no more duplicates and data collection as well as working with the data in Lumen can proceed normally. I understand that by removing the duplicates I made it harder to research the issue, but I did not want to stop the work.

# Next 
Why is this happening?

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/duplicated-data-point-ids

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/akvolumen-support-request-number-185689-from-camille-at-akvo-dot-org

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/akvoflow-support-request-number-187124-from-nikki-at-akvo-dot-org

**Comment by stellanl** [comment]
dfat-png-scf.akvoflow.org (akvoflow-180) has 6 pairs of duplicates for Form 16030001

**Comment by stellanl** [comment]
A look in the datastore,
https://console.cloud.google.com/datastore/entities;kind=SurveyInstance;ns=__$DEFAULT$__/query/kind;filter=%5B%2224%2FsurveyedLocaleIdentifier%7CSTR%7CEQ%7C14%2F8h23-nts0-f36n%22%5D?organizationId=41264378643&project=akvoflow-180
shows that the two SurveyInstances were created just 19ms apart, so likely part of the same ingestion process. How this could happen is not yet clear.

**Comment by stellanl** [comment]
The corresponding  SurveyedLocale entites were created slightly earlier:
SurveyedLocale, 28420469 createdDateTime:  2018-11-21 (11:16:22.202) UTC+1
SurveyedLocale, 4410586  createdDateTime:  2018-11-21 (11:16:22.289) UTC+1
