### ISSUE TITLE
FLOW reports using BIRT

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2947]
Producing FLOW reports using BIRT will let us make both raw-style reports for further processing by partners (Excel format) and nicely formatted reports customised to partner requirements (PDF, Word).

The main challenges are:
- Reports are generally tabular, whereas the FLOW questions and answers are relational. A report template will be valid only for a particular form. Further complications are the geolocations that are packed as JSON and the repeated question groups.
- Data is in GAE, and we do not want to create new infrastructure that is GAE-specific.

Some specific issues that need adressing:
- [ ]  FLOW users need UI to create BIRT templates for a specific form and set of desired data. 
- [ ]  FLOW users need UI to run a BIRT report from one of the templates.  
- [x]  The templates need to be stored somewhere (S3? Same server as the BIRT engine?) and may need to be organised or have access restrictions.  
- [x] The BIRT engine needs access control (Keycloak)
- [x] The BIRT engine needs data to be in an SQL database. This needs to be fed live data from the unified log. (This is not an absolute requirement. BIRT can also use Scripted Data Sources, that can call general Java code.)
- [x] The reporting database must be structured so that SQL queries (possibly nested) can select the data needed for a report.
- [ ] What happens when a form is changed? Will there only be response data for published versions?

**Comment by janagombitova** [comment]
@stellanl as part of cleaning up the old Product-Design repo, I found this issue. Is it still relevant? Can we close it?

**Comment by stellanl** [comment]
No, we can close this.
