### ISSUE TITLE
Cannot export data due to 403 error

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2948]
A while back we had the issue that when exporting data the survey-form dropdown did not load. After fixing the issue on #2938 a partner still could not export data due to a 403 error. 

![image001](https://user-images.githubusercontent.com/12456965/50689043-632adb00-1028-11e9-8406-740ade2f059e.png)

![image001 1](https://user-images.githubusercontent.com/12456965/50689367-c49f7980-1029-11e9-85cb-6bed0f95b329.png)

_Originally posted by @janagombitova in https://github.com/akvo/akvo-flow/issues/2938#issuecomment-451436674_

We fixed it by removing the users account and adding her back in. A more structural solution is however needed.

**Comment by kymni** [comment]
## Test plan
* Hard to reproduce but just confirm that error responses no longer result in endless loading

**Comment by kymni** [comment]
Confirmed end point that returned 403 no longer breaks anything on the client side
