### ISSUE TITLE
Codes still show in data export after being deleted from form 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2954]
# Context 

Salim can add codes to options that are then used to simplify data analysis or for importing the data to another system. These codes are defined in the survey form and then Salim can see them with the data when exporting a Data cleaning export in the format 'code:option text' or in the Data analysis export where only codes show, if defined. 

# Issue 
A partner collected data with option codes. But then realised they do not help them with analysis and actually complicate their processes. So they removed the codes from the survey form and expected to download the data again and have it without codes showing. But, the dataset when exporting with Data cleaning exports still shows both code and value and Data analysis export shows only the code, even though there are deleted from the form. 

# Next steps 
The expectation is, that if codes are removed from a form they do not show anymore also for data collected before the codes were removed.

# Created via Reamaze:

Link: /admin/conversations/akvoflow-support-request-number-179595-from-nikki-at-akvo-dot-org

**Comment by stellanl** [comment]
This will require the exporter to look a bit deeper into the options, but should be doable.
