### ISSUE TITLE
Cascade publishing fails silently if error msg too long

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#2961]
If the error msg > 1500 chars, cascade publishing fails to store it in the shortMsg field, and so user gets no message at all.
Origin: Reamaze issue 183,558 from deden@akvo.org

**Comment by kymni** [comment]
@stellanl is this testable?

**Comment by stellanl** [comment]
In theory, you could make a cascade with lots and lots of duplicates and try to publish it.
