### ISSUE TITLE
Device ID not resetting in assignment tab

### ISSUE THREAD

**Issue by henryjewell** [akvo/akvo-flow#297]
Installed new APK of the training instance on a device that was already on the instance.

Reset device ID on new APK (to HJ) which updated it in the device list (after a delay - still recognized it with old ID to begin with) but not in the assignment tab (still henry samsung)

See images for further information

![assigment tab](https://f.cloud.github.com/assets/3026073/814679/75f1d4e4-ef1a-11e2-8514-b596c0f271df.png)

![device list](https://f.cloud.github.com/assets/3026073/814681/7bed4626-ef1a-11e2-986f-9c65e671e78f.png)

**Comment by janagombitova** [comment]
This issue changes to be about the Device IDs taking a lot of time to show in the list and this problem is dealt with in a more recent issue thus closing this one
