### ISSUE TITLE
Device group not showing

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2975]
Reported via support. 

A partner on https://biogas-programme.akvoflow.org/admin/ reported the device groups stop showing in the Device list since the last release. They use the device groups the manage their long device list and easily assign forms. 

By checking other instances these seems to be happening across other organisations as well. 

![image005](https://user-images.githubusercontent.com/12456965/52937411-51469280-335f-11e9-9e11-96dbc2d5e6a2.jpg)

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/urgent-issue-the-disappearance-of-device-group-on-dashboard

**Comment by stellanl** [comment]
Looking in the db, no devices are in a device group. Will check if I can see if they were removed this morning when the dev cleanup cron task ran.

**Comment by stellanl** [comment]
On Saturday 2019-02-16 at 12:31:06, user hio2kr@gmail.com modifies all the devices.
I *think* the only user operation that does that is a change of device groups.
Before we dig any deeper that user should be consulted.

**Comment by janagombitova** [comment]
I have informed the support team to further the details to the partner. I think we can close this issue for now and reopen if needed if the case arises again
