### ISSUE TITLE
Data cleaning sheets with only repeat question groups do not update the responses

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#2995]
When uploading a data cleaning sheet that only contains data from a repeat question group and no responses for the normal group(s) or a file with with only repeat question group sheet, the responses edited for data cleaning in the repeating group are never updated on the backend. 

**First sheet is empty**
<img width="1052" alt="screenshot 2019-03-01 at 12 14 09" src="https://user-images.githubusercontent.com/533336/53634849-9d28ef80-3c1b-11e9-8eb2-1a1f7a17359f.png">

**Data is only present for repeat question group**
<img width="1379" alt="screenshot 2019-03-01 at 12 14 25" src="https://user-images.githubusercontent.com/533336/53634863-ae71fc00-3c1b-11e9-9d18-d842242053bc.png">

**Comment by stellanl** [comment]
Test plan:

1. Import data to a form with only one group which is repeatable.
2. Export it again and see that it was entered correctly.
