### ISSUE TITLE
Data point ID with only 11 characters 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3007]
Deden reported a case today where he found a data point ID with only 11 characters and not the expected 12. 

Instance URL :  https://eywindonesia.akvoflow.org/admin/
Form Path: Experiment Satya > Youth Monitoring > Youth Survey > 1.Youth Registration

![image](https://user-images.githubusercontent.com/12456965/54355720-213a9880-465a-11e9-9543-6e7043cdd676.png)

**Comment by janagombitova** [comment]
@stellanl is this issue still relevant. As I recall we no longer allow short data point IDs, right?

**Comment by stellanl** [comment]
We think we have conclusively stopped generating them, yes.
