### ISSUE TITLE
Exports broken if first/all groups repeatable, or if there is >100 repeats

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#3020]
DC report data points are supposed to begin on row 3, but begin on row 2, same as for the other exports. But on the base sheet ("raw data") the DC export has one more header row, which somehow overwrites the first row of data. Seen with a form where group 1 was repeatable, and group 2 was not (and had no data) using dashboard v1.9.44 and app v2.7.2

**Comment by stellanl** [comment]
Likely related to #2995. Surveys with 1st group repeatable were never tested when repeatable groups moved to separate sheets.

**Comment by stellanl** [comment]
There is another bug here, too; if a form instance has more than 100 repeats, both the metadata headers and the md5 sum is only correct for the last 100 (those that are in the Excel file access window).

**Comment by stellanl** [comment]
Related support issue: https://flowhelp.reamaze.com/admin/conversations/problem-exporting-data-in-akvo

**Comment by stellanl** [comment]
Test plan:

1. Create a data cleaning report for a form with all groups repeatable, and at least one instance with more than 100 repeats, such as akvoflow-122, Form "Cambodia > CHAIN > CHAIN2 Farmer Progress Monitoring > Farmer Progress Monitoring 030319 > 2 - Harvested crops", 350260004
2. Check that there are no answers on the base sheet, but metadata for each instance.
3. Check that there are no metadata or data gaps **at the beginning** of an instance with >100 repeats.

**Comment by janagombitova** [comment]
@stellanl I noticed the PR was merged. Is this issue then resolved and in production or does more still need to happen?
