### ISSUE TITLE
NPE in EnvServlet after removing user

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#3022]
I removed a test user from Flow while I was logged in. Found this in the logs:

com.google.apphosting.runtime.jetty9.JettyLogger warn: /flowenv.js (JettyLogger.java:29) java.lang.NullPointerException at org.waterforpeople.mapping.app.web.EnvServlet.addLocale(EnvServlet.java:197) at org.waterforpeople.mapping.app.web.EnvServlet.doGet(EnvServlet.java:150) at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)

**Comment by stellanl** [comment]
Test plan: log in with a test user. While it is logged in, remove the user from you superadmin account. Navigate to another top-level tab with the test user. Check the Cloud Console log for an NPE; there should be none.

**Comment by muloem** [comment]
Was merged in v1.9.45
