### ISSUE TITLE
Deleting SurveyInstance fails if a summaried answer is > 1500 chars

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#3038]
In SurveyInstanceDAO, L578:
https://github.com/akvo/akvo-flow/blob/cce3c3a42aaf72f1d8a84fdce756d235359051e7/GAE/src/org/waterforpeople/mapping/dao/SurveyInstanceDAO.java#L578-L579

it is possible for qasItem.getValue() to return > 1500 chars, but summDao.listByResponse() cannot handle that:

```java 
java.lang.IllegalArgumentException: response: String properties must be 1500 bytes or less. Instead, use com.google.appengine.api.datastore.Text, which can store strings of any length. at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:488) at org.datanucleus.api.jdo.JDOQuery.executeWithMap(JDOQuery.java:351) at org.waterforpeople.mapping.analytics.dao.SurveyQuestionSummaryDao.listByResponse(SurveyQuestionSummaryDao.java:158) at org.waterforpeople.mapping.dao.SurveyInstanceDAO.deleteSurveyInstance(SurveyInstanceDAO.java:578) at org.waterforpeople.mapping.app.web.rest.SurveyInstanceRestService.deleteSurveyInstanceById(SurveyInstanceRestService.java:243)
```

**Comment by stellanl** [comment]
Question 2830060031, an OPTION, has *very* long option names, and allows multiple answers. Almost all answers for it are>1500 chars long. (Stored in the valueText field.)

**Comment by stellanl** [comment]
Constants.MAX_LENGHT is 500, although the Datastore limit is 1500. Is this an old value, or were they just being *very* cautious? Maybe time to increase it?

**Comment by stellanl** [comment]
The SurveyInstanceDAO.deleteSurveyInstance() summaries-adjusting code does not handle JSON answers at all, so many, if not all, negative adjustments have been getting lost for some time.

**Comment by stellanl** [comment]
I can find nothing that prevents creating an option text longer than 1500 chars.
Trying to create one fails silently.
There should be a limit in the UI. I suggest setting it to 500 like for the question text.

**Comment by muloem** [comment]
> Constants.MAX_LENGHT is 500, although the Datastore limit for persistable (indexable) String is 1500. Is this an old value, or were they just being very cautious? Maybe time to increase it?

@stellanl yes the value used to be capped at 500xters and was probably recently increased.

**Comment by muloem** [comment]
> I can find nothing that prevents creating an option text longer than 1500 chars.
Trying to create one fails silently.
There should be a limit in the UI. I suggest setting it to 500 like for the question text.

I believe it was setup in such a way that for responses greater than the limit, they were stored in a `Text` type field (`valueText`)

**Comment by stellanl** [comment]
Test plan:
1. Create an option question with 4 options, each with text longer than 400 chars, and allow multiple selection.
2. On the device, select all four options and submit.
3. In the dashboard, delete the form instance. It should disappear permanently.

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/akvoflow-support-request-number-197812-from-sherinah-dot-ngabo-at-welthungerhilfe-dot-de

**Comment by valllllll2000** [comment]
All works as expected
