### ISSUE TITLE
Remove the option to select all devices 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3051]
We have been recently getting cases where one user has changed the device group for all devices on an instance. We assume they wanted to add a few devices to a group and selected the 'all' checkbox and changed the group. 

![Screen Shot 2019-04-05 at 09 10 57](https://user-images.githubusercontent.com/12456965/55610278-e3292400-5782-11e9-89b6-07c2251f475b.png)

Not only has this caused confusion to our users but a spike in support and investigation. Device groups are mostly used by larger organisations to manage the large number of active enumerators they have. Changing the group means a lot of extra work on the side of the workspace managers to bring the order back. 

To avoid the case from happening again we can remove the option to select all devices - the checkbox and have the users have to select devices specifically to add them to a group. This is not an ideal solution, but more of a temporary fix as we do need to rethink the entire device group experience anyway and it can save us a few support issues down the line. 

What do you think? @stellanl @muloem @Kiarii?

**Comment by stellanl** [comment]
Probably a good idea.

**Comment by kymni** [comment]
Removed
