### ISSUE TITLE
Assignment creation visual issues

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3056]
The Assignment does not look quite the same although it's a minor detail, look at the 2 dropdowns from select survey and select device group.

Older versions:
![Screenshot from 2019-04-08 15-39-13](https://user-images.githubusercontent.com/923280/55728642-be4bdf80-5a14-11e9-993c-455c02f2d77b.png)

New version
![Screenshot from 2019-04-08 15-38-24](https://user-images.githubusercontent.com/923280/55728643-be4bdf80-5a14-11e9-8e4a-91cca528fe8b.png)

**Comment by valllllll2000** [comment]
Actually when you start selecting surveys it does start to look a bit odd:
![Screenshot from 2019-04-08 15-47-30](https://user-images.githubusercontent.com/923280/55729043-ac1e7100-5a15-11e9-9c3b-4a490638fcef.png)

**Comment by kymni** [comment]
## Test plan
* confirm dropdowns are normal

**Comment by valllllll2000** [comment]
Problem solved!
