### ISSUE TITLE
Assignment Tab issue

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3057]
The first entry in the assignment tab is half hidden and so are the titles

![Screenshot from 2019-04-08 15-54-30](https://user-images.githubusercontent.com/923280/55729547-a07f7a00-5a16-11e9-9caf-9b10031833b6.png)

**Comment by kymni** [comment]
## Test plan
* confirm list is normal

**Comment by valllllll2000** [comment]
Problem solved!
