### ISSUE TITLE
Bulk upload page images not loading

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3084]
When testing on uat1, I noticed that on Bulk upload page the images are missing.

![Screen Shot 2019-05-02 at 13.38.36.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/6bdc350d-209e-4467-903d-60beb1c66f01)

**Comment by kymni** [comment]
Couldn't reproduce. Caching issue/network issue maybe?

**Comment by janagombitova** [comment]
Odd. But working now. Thank you @kymni and sorry about that

**Comment by muloem** [comment]
No code written here so removing from the milestone.
