### ISSUE TITLE
Resources tab does not stop loading

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3085]
Another small bug on UAT1, the Resources tab does not stop loading and it seems the Data approval sub-tab does not show. I only get cascades. 

<img width="1267" alt="Screen Shot 2019-05-02 at 13 51 49" src="https://user-images.githubusercontent.com/12456965/57073471-6f2a5f00-6ce1-11e9-90f2-7b41ba69f067.png">

**Comment by kymni** [comment]
Should be resolved with the [devices tab fix](https://github.com/akvo/akvo-flow/issues/3086)
