### ISSUE TITLE
Save Question variable name to published form XML

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#3101]
This will help with analysis format exports after #2285, as the variable name can currently only be found in volatile form in the datastore.

@valllllll2000 , would adding variableName as an attribute of the `<question>` tag break anything in the app?

**Comment by valllllll2000** [comment]
@stellanl it seems at first glance that no, it will not break anything, but I want to test to make sure. Here is an example of form I will try:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><survey name="Testing Variable Name" defaultLanguageCode="en" version='1.0' app="akvoflow-uat1" surveyGroupId="147842013" surveyGroupName="New survey"><questionGroup><heading>survey 2 group</heading><question order="1" type="free" mandatory="true" localeNameFlag="false" id="144962013" variableName="SOME_NAME"><text>survey 2 question 1</text></question></questionGroup></survey>
```

**Comment by stellanl** [comment]
Perfect.

**Comment by stellanl** [comment]
Variable names must match /^[A-Za-z0-9_-]*$/ so should be ok as-is in an attribute.

**Comment by valllllll2000** [comment]
ok so I tried adding that file as bootstrap, all worked as expected

**Comment by stellanl** [comment]
Test plan:
1. publish a form that has a variable name set for one of the questions.
2. Fetch the generated XML file from S3 (URL is in Messages list) and see that it was included.
