### ISSUE TITLE
Publish form using Jackson fasterxml library

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#3115]
Since #2285 added classes for parsing form XML, with a little extra work we can do the publishing using the same infrastructure, improving the likelihood they are compatible.

**Comment by stellanl** [comment]
Basic pattern is to add a constructor for most of the XML-classes (those that correspond to dto classes) that takes a dto parameter.

**Comment by stellanl** [comment]
It just occurred to me the since the published form will now the base for the reports, we need to invalidate the cached reports for the form.

**Comment by muloem** [comment]
Which cached reports are you referring to here? Survey forms or Comprehensive reports?

**Comment by stellanl** [comment]
Comprehensive and data cleaning.
The survey forms export is another thing that we may want to be based on the published form, but that should be another issue.

**Comment by janagombitova** [comment]
Is this issue done done and can it be closed?

**Comment by muloem** [comment]
Tested several variations of publishing and large surveys. Good to go. 👍
