### ISSUE TITLE
Drop surveyInstanceContrib field from SurveyedLocale

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#3119]
I can find no use of this (ugly, denormalised) field anywhere. Can anyone else?

**Comment by muloem** [comment]
So this field was apparently originally designed to keep a record of all the survey instances that are associated to a specific SurveyedLocale.  I am in favour of getting rid of it but we need to implement an alternative way to keep track of related SurveyInstance.  Maybe its enough that they have the surveyedLocaleId as a sort of foreign key?
