### ISSUE TITLE
Do not allow to use the same user email twice 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3120]
# Problem
When creating a user on Flow we take the email as the main point of identification. Each user also is given a name and roles. However, we have no checks in place today to ensure an email is used only once. So what can happen is that the user example@akvo.org has access to the Flow instance to one folder and then another admin creates a 2nd user with the same email, example@akvo.org, and gives this user access to a different folder or everything. 

![users flow](https://user-images.githubusercontent.com/12456965/59669682-f57c0100-91ba-11e9-94db-957c0f8602c3.gif)

# Expectation
This should not be allowed. We should ensure that an email exists only once per instance. When creating a new user with an existing email we should warn that this user already exists and not allow to proceed when creating the new user. 

Furthermore, when creating Flow instances we add super admins to each instance who are not visible in the User tab. How should these be handled in case of this issue? 

# Relevant existing issues 
https://github.com/akvo/akvo-flow/issues/1944
https://github.com/akvo/akvo-flow/issues/2265

**Comment by stellanl** [comment]
I think UserRestService should return an error on POST if the email is taken. Of course it is nice if the UI protests before that.
The datascript that uploads the super admins could also get a check for duplicates.

**Comment by muloem** [comment]
Was pretty sure we have spoken about sorting this out before. https://github.com/akvo/akvo-flow/issues/1944 and https://github.com/akvo/akvo-flow/issues/1157
