### ISSUE TITLE
Assignments form selector

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3136]
In order to select a particular form to be included in the list of forms enabled for an assignment, we implement the form selector/enabler component.  From this component we populate the list of forms that are included in an assignment to a device.

<img width="575" alt="Screenshot 2019-07-13 at 16 55 29" src="https://user-images.githubusercontent.com/533336/61173122-143d9f80-a58f-11e9-9433-a3510ac64c25.png">

**Comment by janagombitova** [comment]
@kymni Charles, can you check the revised mockup here, please? Thanks. https://github.com/akvo/akvo-flow/issues/3137#issuecomment-511779007

**Comment by janagombitova** [comment]
Everything works as expected. But there is quite some duplication in this UI. 

<img width="614" alt="Screen Shot 2019-10-11 at 08 41 53" src="https://user-images.githubusercontent.com/12456965/66629761-0be31800-ec03-11e9-8bcc-17bdb17c3e3b.png">

@marvinkome can we make the following changes: 
* [ ] remove change the title to '2. Survey and forms' 
* [ ] if possible remove the '0.1' and '03.' from all the three headers
* [ ] move the survey dropdown right under the header 
* [ ] remove the heading above the dropdown as within the dropdown we already state Choose a folder or a survey
* [ ] under the dropdown change 'Select forms:' to only 'Forms' as indicated in the mock-up above  
* [ ] under the 'Forms' title add 'Only published forms are shown in this list' (as we have with the 'Can't find your survey? Perhaps it has not been published yet. Only published surveys are shown in this list.' --> but this text should be fully removed as it is not 100% correct)

**Comment by janagombitova** [comment]
As @marvinkome creates a separate issue for the last improvements #3227 I am closing this one so avoid duplication of issues
