### ISSUE TITLE
Selection of devices for an assignment

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3137]
When creating an assignment, we need to select the devices that will receive these forms.

<img width="750" alt="Screenshot 2019-07-13 at 18 31 18" src="https://user-images.githubusercontent.com/533336/61174132-70f38700-a59c-11e9-8864-b6e42a9f9e49.png">

@Kiarii @janagombitova  The current design proposes a popup for selecting the devices.  Do we need a pop up or is it enough to have the devices listed along with checkboxes to select?

**Comment by Kiarii** [comment]
if I remember right, I think we had settled for a pop up at least for the first iteration; https://projects.invisionapp.com/share/XDQHOF39PEJ#/screens

**Comment by janagombitova** [comment]
If the implementation is simplified by: (copy of Mulo's explanation from Slack) "as soon as an assignment is opened.. i.e. a new or existing assignment, the section to the right, where selected devices are supposed to be shown, will immediately load a devices list. if its an existing assignment with selected devices, those will be checked. if its a new assignment, then the devices will be shown but nothing selected" then I say we should do it. 

It also removes an extra step of having to click on the 'plus' icon to add devices and only leaves the need to select a check box, in case you want to add more devices to the list. 

We can always review this approach in the 2nd round when adding the option to assign data points to devices to ensure this new functionality is understandable, as you need to select a specific device to assign points to.

**Comment by Kiarii** [comment]
I believe we have come to the agreement of doing the device selection as below..
![image](https://user-images.githubusercontent.com/12692444/61291154-5d336500-a7d6-11e9-9bad-ebca85cebeb3.png)
In an [earlier mockup iteration](https://projects.invisionapp.com/share/TZP8HSGRB5N#/screens/332622920) we had also considered doing the device selection on a sidebar which enabled us to forego the pop-up as well as keep device selection and datapoint assignment separated; we will revisit this in the next iteration i believe..

**Comment by janagombitova** [comment]
I could not test this on uat2 as it did not work. Is it merged? @muloem

**Comment by kymni** [comment]
@janagombitova the `assignments/ui` feature branch is on dev2

**Comment by janagombitova** [comment]
After some UAT1 testing overall the functionality works well but we need to improve its usability. Here are some things we need to handle when it comes to selecting devices.  

![Flow assignments devices](https://user-images.githubusercontent.com/12456965/66631470-7b0e3b80-ec06-11e9-8285-c2ca26910c9c.gif)


@marvinkome Can you please: 
* [ ] simplify the section title to 'Devices' 
* [ ] remove 'Select device group'
* [ ] add the option to select all devices within one group --> the checkbox on the device group level (see mockups above) 
* [ ] only open the device group the user clicks on - right now it seems we open a random set of groups and sometimes not even the group you click on. 
* [ ] if not too much effort for this release: add the number of selected devices as indicated in the mock-up. If this is not doable for the release next week, then we should add this in the next round when we also need to adjust the UI to match the designs more.

**Comment by janagombitova** [comment]
@marvinkome created a separate issue for these last fixes #3230
