### ISSUE TITLE
Webforms 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3145]
# Context 
Original issue: https://github.com/akvo/akvo-product-design/issues/70 We closed it back in 2018 as work was paused in 2016 because we decided to focus on field data collection needs and handling data (analysis and connecting Flow and Lumen). During those discussions, we looked at two approached: 
- submitting a webform via a generated URL, where this can be shared with anyone outside of Flow
- submitting a webform while being logged into Flow to ensure the submitter is logged as metadata and to pave the path for possible webform submission for monitoring forms (we chose this option at the time)

Webforms as an idea were never validated at the time neither which implementation would create the expected value. 

Today, @joycarpediem presented the work he and Deden have been doing as part of a project for a partner to make it possible to submit data using a Flow form via a web browser, webforms. In this case, the webforms are shared via a URL outside of Flow. 

Here is where they got to today: https://tech-consultancy.akvotest.org/akvo-flow-web/angkorsalad/22420001

## Why do we add this issue 
When we receive feedback about Flow, the dealbreakers are usually around the survey editor a the limitation to submit data only via the Android app. Often data is not also gathered from the field, but via phone interviews, report checks, etc. In these cases, partners have been working with tablets to submit the data to Flow, but it is not ideal. 

As we have been focusing on field data projects, webforms were not a priority. But with Joy's and Deden's initiative we decided **it is worth adding to the product, in an as minimal form as possible (MVP)**: 
- to validate the need of submitting data via the browser 
- their initiative can prosper all our partners so it would be a waste just to have it running as a side project 
- we can learn more about data collection 
- it can give us a bit of market edge

# Problem we are trying to solve 
**How might we make it possible to submit data to a Flow form via the browser.**
- collect data via web to allow users who do not have Android phone to submit data, or are working from their laptop at data input 
- crowdsourcing of data collection 

# Idea 
The idea is to create a **most minimal version** of the functionality to push it to Flow to learn and validate the value of webforms.

## User workflow
1. Salim finishes up the form design. 
2. He publishes the form. 
3. He now wants to share the form URL so it can be filled in (he can also set up an assignment for field data collection) 

## Details 
Here are some initial thoughts (based on Joy's and Deden's prototype) on how to keep the implementation as limited as possible:  
- webforms are shared outside of Flow via a generated URL 
- only for registration forms or surveys with one form, so **not** for monitoring forms 
- how to handle question types as Caddisfly, geoshapes, geolocation (where manual input is disabled), barcode (where manual input is disabled) as they cannot be submitted via a webform. What to do if they are set to be mandatory? Show but make un-submittable and ignore the mandatory setting? 
- device ID can be defaulted to `Flow web`
- do we need to know who is submitting the data? if yes, how? Adding a default field for the submitter to fill in at the end?  
- can you make more than one submission at the time (can you submit and then start filling in the form again)? I would say yes, let's implement as least restrictions as possible.  

# Next steps 
* [x] clarify MVP to get done in a week, questions above and other possible questions  
* [x] share tasks across the team
* [x] add usage tracking to the functionality (Piwik Pro) so we can check user adoption

**Comment by janagombitova** [comment]
Today we connected on the current state of webforms and what needs to get done to get them out there by next Monday (in a week). We looked at the way the webforms work today and defined the user workflow we want to support (see image below). See video of the full meeting on Peak: 

# Summary  
* Webforms are shared and accessed via a URL to **anyone** who has it and knows the webform password (a form of crowdsourced data collection)
* We will not support assigning a webform to a specific user (email) for now as we do not see the use case and need at this moment 
* The form URL is generated for forms that have been published at least once and are not monitoring forms, do not hold Caddisfly, geoshape, signature questions, and RQGs (support for RQGs needs to be implemented) 
* To minimise the risk of submitting data by anyone and everyone, the webform URL is random, the enumerator needs to fill in the webform password before accessing the form. The webform password for now follows the app 12345 password approach, but in the future we want to generate a strong random password per form. 

# User workflow 
![Flumen_Webforms](https://user-images.githubusercontent.com/12456965/82205767-5bab5f80-9907-11ea-980f-64f1111957e1.png)

# Implementation
* Working on the actual webforms (how they work and look at feel) is handled by the TC team 
* Supporting the webforms, bugs and user questions is handled by the TC team 
* Full handover of webforms to the product team is a goal of the future 

## Next steps 
This week we will: 
* [ ] Add the option to `Share` a Flow form to the Flow form editor + an explanation on what it does - tooltip. *Marvin* 
* [ ] The `Share` button is enabled once a form is published for the first time and then is available all the time (the webform uses the latest published version of the form, so we do not care if the form is in draft mode). *Marvin* 
* [ ] The `Share` button is enabled only for forms that:  
   * are not monitoring forms (only registration forms), 
   * do not have a Caddisfly question, 
   * do not have a geoshape question, 
   * do not have a signature question, 
   * do not have a Repeated Question Group (for now, till the implementation is done - not handled in this iteration)
* [ ] Clicking on `Share` the user will see a popup with the webform URL (random) and the webform password. *Marvin*
* [ ] Webform URLs will be randomised. *Juan* 
* [ ] We need to translate the randomised URL to the webform URL. *Mulo* 
* [ ] The enumerator will first fill in the password and captcha before accessing the webform, so we are changing a bit the current webform implementation. *Deden*
* [ ] Webforms need to be able to handle many forms being submitted, scalability. *Ivan*

**Comment by marvinkome** [comment]
@janagombitova Usage tracking is on FLOW or It's on the webform?

**Comment by janagombitova** [comment]
@marvinkome whatever is easier. I guess in Flow on the `Share` button would already be good enough to start with.

**Comment by Kiarii** [comment]
Am going to dump the UI wireframe snippets here..
#### share button
* I think 'share' might be a bit ambiguous so I made the underlying action more explicit. 
* I also decided not to touch the existing form action order, so as to keep the task focused, this can be revisited later.
* I added a NEW flag to the new action to catch user's attention to the new action - if we do this, the flag should be removed after the user interacts with share action..

![image](https://user-images.githubusercontent.com/12692444/82210566-ff9d0700-9917-11ea-80d4-07a661ca3a08.png)

**Comment by Kiarii** [comment]
#### Share (success) dialog
* Dialog title: Share "form name" as a webform
* On copy link we add a little note that link has been copied to clipboard. The note shd disappear after some time - 🤔 @tangrammer?
* Should we provide a similar one-click-grabber for the pwd? 

![image](https://user-images.githubusercontent.com/12692444/82213074-40971a80-991c-11ea-9c81-b8f185e8a673.png)

**Comment by Kiarii** [comment]
@Jana and @marvinkome 
> The Share button is enabled only for forms that: are not monitoring forms (only registration forms), do not have a Caddisfly question, do not have a geoshape question, do not have a signature question, do not have a Repeated Question Group

The form validation, is this something that (as described) is being done (behind the scenes) so that at any given time on the form edit screen, flow knows to disable / enable the 'share as a webform' action or is it done when the user clicks the action? The approach affects how we show error messages..

**Comment by muloem** [comment]
> The form validation, is this something that (as described) is being done (behind the scenes) so that at any given time on the form edit screen, flow knows to disable / enable the 'share as a webform' action or is it done when the user clicks the action? The approach affects how we show error messages..

I believe it is something that should be done at any given time.  Its possible to monitor the different elements that would change the state of the button to enable/disable it when necessary.

**Comment by Kiarii** [comment]
#### Share disabling - notes

* we add an alert/warning/info next to the 'share as a webform' action and on mouseover show explanations
* since the form validation is always running in the background, it means that the NEW flag on the 'share as a webform' can be removed and replaced by the alert icon - when the action has been disabled, or? 

##### Case 1: All validations are a go but the form is not published
![image](https://user-images.githubusercontent.com/12692444/82218107-0d588980-9924-11ea-9975-934676e8ba88.png)

##### Case 2: Form is a monitoring form
![image](https://user-images.githubusercontent.com/12692444/82218126-15b0c480-9924-11ea-815a-a887e6e3bbdc.png)

##### Case 3: Form contains a RQG or webform-unsupported question types / group
![image](https://user-images.githubusercontent.com/12692444/82218077-ffa30400-9923-11ea-95d6-afb901c0fee6.png)


In this case, the note/alert/message should only list the respective question type or RQG..

**Comment by tangrammer** [comment]
https://github.com/akvo/akvo-flow/issues/3145#issuecomment-630151469

@Kiarii once that we have the shared webform activated 
could the user see/copy again the random url and/or password clicking in the button?

**Comment by tangrammer** [comment]
@joycarpediem links included in zoom meeting 

 https://github.com/akvo/akvo-tech-consultancy/tree/master/sites 
 https://tech-consultancy.akvo.org/akvo-flow-web/pilots/321890074 
 http://tech-consultancy.akvotest.org/akvo-flow-web/2scale/28150013 
 https://github.com/akvo/akvo-tech-consultancy/blob/59cf116c919b9562672b66d295b182b6c82ee9b0/sites/akvo-flow-web-

**Comment by janagombitova** [comment]
@Kiarii in regards to https://github.com/akvo/akvo-flow/issues/3145#issuecomment-630151469: 
* What do you think of making the URL visible before the `copy link` action? 
* I agree with Mulo on https://github.com/akvo/akvo-flow/issues/3145#issuecomment-630164479 as it can happen that the user changes the form to be a registration form and then the button needs to be enabled or adds a question type that we do not support and publishes and then the button needs to be disabled. 
* On the disabled notes (here: https://github.com/akvo/akvo-flow/issues/3145#issuecomment-630182356) do you mean that the notes text will generate based on what the reasoning is? So create the combinations of `not published for the 1st time` - `monitoring` - `Caddisfly` - `signature` - geographic shape` - `RQGs`? Will this not overcomplicate the implementation @marvinkome? Can't we just start with a generic note?

@joycarpediem what happens today when a form has a Caddisfly question in it (for example) that is mandatory and the enumerator opens the webform? I am asking because we can have the case when: 
1. Salim creates a form that follows the webform rules (no Caddisfly, signature, etc). 
2. Hits publish. 
3. Gets the webform URL. 
4. Changes the form to now have a signature question in it. 
5. Hits Publish again. 
--> Salim already has the webform URL, so he can access the webform. But the latest published version has a question type webforms do not support. What do we do today with such cases?

**Comment by marvinkome** [comment]
> On the disabled notes (here: #3145 (comment)) do you mean that the notes text will generate based on what the reasoning is? So create the combinations of not published for the 1st time - monitoring - Caddisfly - signature - geographic shape-RQGs`? Will this not overcomplicate the implementation @marvinkome? Can't we just start with a generic note?

A generic note would be preferable

**Comment by Kiarii** [comment]
> [#3145 (comment)](https://github.com/akvo/akvo-flow/issues/3145#issuecomment-630151469)
> 
> @Kiarii once that we have the shared webform activated
> could the user see/copy again the random url and/or password clicking in the button?

yes, @tangrammer copying the link should always be actionable

**Comment by Kiarii** [comment]
@janagombitova @marvinkome 
A generic note would do, even though it leaves a lot of cognitive effort for the user if for instance we say:
 
"Form cannot be shared as a webform because it is not published, or it is a monitoring form or because it contains a signature, geoshape or a caddisfly question type or a repeat question group."

It leaves the user with a lot of stuff to process, but since we are actually validating each of these flags automagically, we know the flag that causes a disabling of the action and a direct messaging would simplify the context for Salim and also resolving it, if he decides to do so..

**Comment by marvinkome** [comment]
@Kiarii Shouldn't the web form URL show in the pop-up?

**Comment by janagombitova** [comment]
@Kiarii  fair point on the error message. But we want to keep the implementation to the minimum for now. As your suggestion is more a super nice to have, I will move it to a separate issue that we can handle later on once we give the webforms a round of improvements.

**Comment by janagombitova** [comment]
@marvinkome I sent you the updated password for webforms. Can you change the UI, thanks

**Comment by janagombitova** [comment]
Tested on UAT2, ready for UAT1

**Comment by janagombitova** [comment]
With Valeria and Kiarii we tested the workflow on UAT1. The only remaining issue blocking the release to users (flipping what is on UAT1) is that even though photos are submitted, they do not show. 

See example on uat1 > _ _Jana > Example webform > New form

@muloem and @tangrammer can you handle the photos? 

Once this problem is resolved we can release. The change to make the passwords random and per form will be released separately and is not a show stopper for these changes.

**Comment by janagombitova** [comment]
All issues resolved. The external bulletin is in the making and the changes to the UI (password to the beginning will be handled another time). Webforms are running in production: https://flowsupport.akvo.org/article/show/111363-webforms and any other issues will be handled separately. Well done everyone
