### ISSUE TITLE
Add validation on assignments endpoint to ensure all forms belong to the same survey

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3147]
We currently have survey/device assignments saved as `SurveyAssignment` entities in the backend.  These map the list of forms to the list of devices to which the forms have been assigned. In the current setup the list of forms can contain forms from multiple surveys.  However, in the new setup (started in #2796) we will have this list of forms coming from **only one survey**. 

We will update the CRUD logic in the backend for `SurveyAssignment` entities to ensure that it conforms to this restriction.  In order to avoid breaking the app function, we will not change the `DeviceSurveyJobQueue` entities but only ensure that they correctly correspond to existing assignments

**Comment by janagombitova** [comment]
@muloem is this issue still relevant?
