### ISSUE TITLE
Master language is not displayed first on the phone when other languages are selected

### ISSUE THREAD

**Issue by henryjewell** [akvo/akvo-flow#315]
On the phone, English was displayed first even when it is not the master language. On a few tests English seems to be displayed first regardless of which language is the master and the order of the translation on the dashboard.

How is the priority of languages within the apk structured?

**Comment by muloem** [comment]
@ichinaski is this still an issue?  If so I would like to close this and move it to the mobile issues list.

**Comment by janagombitova** [comment]
https://github.com/akvo/akvo-flow-mobile/issues/453 created an issue in flow-mobile repository
