### ISSUE TITLE
Change the generated name for split assignments

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#3153]
Jana requested that we drop the #n part of the modified assignment name from #3107.

**Comment by janagombitova** [comment]
@stellanl Will this run automatically? I am testing UAT1 right now and the change is not reflected? Is the change on UAT1?

**Comment by janagombitova** [comment]
Answer from Stellan on slack: It's one of our infamous datascripts. Runs from the commandline. I have a all-instances shellscript wrapper for it. Just one command from me, and all should be fine.
