### ISSUE TITLE
Selection of datapoints to assign to a device

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3168]
As part of #2796, we will enable selection of datapoints to assign to a specific device in an assignment.  This is the UI work related to #3166 that will communciate with the backend to create and update the list of datapoints assigned to a device.

Initial MVP simply shows a list of datapoints selected if present or none if they are not selected. 

<img width="989" alt="Screenshot 2019-08-21 at 16 47 16" src="https://user-images.githubusercontent.com/533336/63442419-5f22c080-c433-11e9-9fd0-aa8970c549fb.png">

And a layover? when _Assign datapoints_ is selected to list all the datapoints to make a selection of the ones to be assigned to a device.

**Comment by janagombitova** [comment]
For all the details check: #2796 

With 1.10 we changed how Assignments work to ensure one assignment can only hold forms from one survey and we redesigned the form and device selectors. These changes were needed to implement **the MVP of allowing to assign data points to devices**. 

The expected user behaviour that we will support is: 
1. Salim creates a new assignment - gives it a name, dates and selects the survey and forms and which devices will collect data for this/these forms. 
2. IMPORTANT: If Salim selects a monitoring survey (with monitoring enabled) he can also assign data points to the selected devices. If he selected a survey that does not have monitoring enables, assigning data points is not available to him. 
3. He selects a device or an entire device group. It is highlighted in the UI. 
4. He clicks to Assign data points (for the selected device or device group). 
5. He sees two options: By data point name or ID, Assign all data points. 
6. He selects how he will assign his data points. @Kiarii how will we handle if there are no data points yet to assign in this MVP? 
6a. If he selects to Assign all data points, all the data points will be sent to that selected device. 
6b. If he selects By data point name or id, he will see a search bar when he types the name or ID and matching data points show in the list with the option to assign to the device.

For all the details please check the mock ups. You can find the full mockups here: https://projects.invisionapp.com/share/NHQGVLB2EKX#/screens/346093699_0-0_Assignments_ES

**Comment by Kiarii** [comment]
> He selects how he will assign his data points. @Kiarii how will we handle if there are no data points yet to assign in this MVP?

@janagombitova am thinking that we had storymapped this or specified somewhere else what would take place, am looking Mural but cant seem to find what we had decided/put down,

**Comment by janagombitova** [comment]
@Kiarii all the decisions are in the Epic: #2796 but there is a chance we did not talk about some specifics, like this one: If it go to Assign data points but the survey has no data points yet, where do I see that?

**Comment by Kiarii** [comment]
if there are no data points yet to assign, we will indicate this to the user as follows:
![image](https://user-images.githubusercontent.com/12692444/66758671-67cdcb00-eea7-11e9-983b-28dcccb4fe32.png)

**Comment by janagombitova** [comment]
Yesterday we went through the mock-ups again with @Kiarii, @muloem and @marvinkome. Here are the notes with the expected behaviour. We agreed:
* assigning data points will only be enabled for monitoring surveys 
* you can assign one data point to multiple devices 
* you will be able to assign data points one device at a time to start with, not enabling to assign data points for an entire group of devices (Needs a new separate issue)
* picking the data points will happen by searching - Salim will type in a keyword, hit the search icon/or press Enter and Flow will give the relevant results 
* if the list of data points is too long scrolling will happen on the list but keeping all other elements (as action button or the search bar) insight. 

More here: 
[Assign data points.pdf](https://github.com/akvo/akvo-flow/files/3835562/Assign.data.points.pdf)


Kiarii will further define the workflow on how to edit the data points that are already assigned to the device.

**Comment by janagombitova** [comment]
Fresh mockups to come... we pivoted on the entire screen layout. More info here# 3297

**Comment by janagombitova** [comment]
The final mockups are here: https://projects.invisionapp.com/share/5YUUUPXF7DA#/screens

**Comment by muloem** [comment]
@marvinkome please read through these comments as there will be a change in the implementation https://github.com/akvo/akvo-flow/issues/2796#issuecomment-563236652

**Comment by Kiarii** [comment]
@muloem has made a suggestion that we consider using walkthroughs to introduce new features or actions that users can now do; For this page, one of those actions is the "Assign Datapoints" which we can introduce or highlight as follows (the text is up for adjustment..)
![image](https://user-images.githubusercontent.com/12692444/75752338-30b26600-5d31-11ea-9cc7-d106edfb834f.png)

**Comment by Kiarii** [comment]
Was going via the assignments and noted that there are a few things needing refinement;

* The "Assign datapoints by name or id" is active if the "Assign all datapoints" is not used
* The "Assign datapoints by name or id" panel is a side panel not a pop-up; the idea being that the user can see what is already assigned as they continue to search and assign more datapoints
* To "unassign datapoints" we cannot say "cancel assignment" this creates a logical confusion with assignments themselves.. Lets use "unassign datapoints." "unassign" might not be a proper English word but if users understand it, there is no need to use more complex or ambiguous terminology 
* With Assign all datapoints, we should give the actual figure; X datapoints assigned
* Walkthrough coming soon

**Comment by janagombitova** [comment]
The core of the work here is done. More adjustments and improvements will follow (see also the comment above) but to keep the issues organised we will use the label 1-Assignments. So when it comes to this issue the goal was to make it possible to assign datapoints. That is done.
