### ISSUE TITLE
Geotag not showing

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3180]
@janagombitova moved this issue from Flow app repo [Thu Sep 12 2019](https://github.com/akvo/akvo-flow-mobile/issues/1479)

## Issue 
If a user adds a photo as an answer to the question from the Gallery and this photo has location data in the EXIF, the data is saved well but not shown in the Flow maps or Data analysis exports.  In the app you see the confirmation that the geolocation is saved, but in the map on the online workspace or in the Data analysis export the geotag does not show. So the impression is that the geotag is not saved. 

![Screenshot_2019-09-12-13-16-55](https://user-images.githubusercontent.com/12456965/64781591-83ba1600-d563-11e9-93e6-c4c3185a73fc.png)
![Screen Shot 2019-09-12 at 13 22 14](https://user-images.githubusercontent.com/12456965/64781593-861c7000-d563-11e9-99dd-9ecc96cee982.png)

## Details
-  I saved an image taken in Vietnam and submitted in from the Amsterdam office 
- https://uat1.akvoflow.org/admin/
- _Lumen tests > Example dataset (for testing and demos) > New form
- Submission made today 12-9-2019

Valeria checked on the app's end everything works as expected: the image is sent with the correct exif data and the correct exif data is present on the image that is on s3, but the dashboard does not display the data

**Comment by janagombitova** [comment]
Just an update: a partner reported the issue with photos captured via the camera. They showed the geotag in the app but no longer in Flow. When downloading the photo to geotag is in the exif file. 

The expectation is to read the exif tag in Flow at all times (in the online workspace and in the exports)

**Comment by stellanl** [comment]
Interestingly, when I analyse the exif in that image, I get an error.
I have to include the -d (debug) flag to the exif command to see all of the tags.

EXIF tags in '67369622-a5061d00-f579-11e9-89e4-7e2eb7a806c4.jpg' ('Motorola' byte order):
--------------------+----------------------------------------------------------
Tag                 |Value
--------------------+----------------------------------------------------------
Image Length        |230
Orientation         |Top-left
Image Width         |408
X-Resolution        |72
Y-Resolution        |72
Resolution Unit     |Inch
Corrupt data
The data provided does not follow the specification.
ExifEntry: The tag 'LightSource' contains data of an invalid format ('Long', expected 'Short').
Light Source        |
Exif Version        |Exif Version 2.1
FlashPixVersion     |FlashPix Version 1.0
Color Space         |Internal error (unknown value 65535)
East or West Longitu|E
Latitude            |52, 22, 20,5380
North or South Latit|N
Longitude           | 4, 54, 26,9700
--------------------+----------------------------------------------------------

**Comment by stellanl** [comment]
There seems to be nothing in the Flow backend that reads geolocation from image EXIF tags. If it happens at all, it has to happen in the app. What is the expected behaviour?

**Comment by janagombitova** [comment]
The expectation is: 
1. Aplhonos captures a photo on the app and under the photo we show if the geotag is saved (available) or not. 
2. On Flow's online workspace Petra views the data in Inspect data tab (or Monitoring tab), where under photos with the geotag we should the lat and long. 
3. On Flow's maps she can click on a data point and in the side panel see that the photo is tagged and click to Show location on map. https://flowsupport.akvo.org/article/show/80466-photos-on-flow-map
4. In the Data analysis export we add the tag data to the columns Photo-lat and Photo-long after the photo url. 

All this worked before and still works on some older photos.

**Comment by stellanl** [comment]
Appears to be an app issue. The old, working image was stored as:
`{"filename":"/data/data/org.akvo.flow/files/akvoflow/data/media/203bc630-607d-4ace-8a42-85e0a9dba65a.jpg","location":{"longitude":4.90779307,"altitude":45.0,"latitude":52.3721304,"accuracy":19.0}}`

but the new one as;
`{"filename":"/data/data/org.akvo.flow/files/akvoflow/data/media/c114bf52-0d71-4828-8970-d473406ba997.jpg"}`

No geotag was sent from the app for this one. Same goes for the Biogas-reported 'untagged' image.

**Comment by stellanl** [comment]
So did the app stop extracting EXIF into the image answer value, or did the backend use to extract it from the image file?

**Comment by janagombitova** [comment]
Interesting. A while back we made a change where we simply read the exif data (what I assume caused the change you describe) - https://github.com/akvo/akvo-flow-mobile/issues/1001 

When Valeria looked at this issue a few weeks ago when it came up, she said: for me everything works as expected: the image is sent with the correct exif data and the correct exif data is present on the image that is on s3, but the dashboard does not display the data

**Comment by stellanl** [comment]
When the app shows the photo, any location is extracted directly from the jpeg file. I have to confirm it in the S3 files, but it feels like the app stopped putting the EXIF geolocation in the IMAGE answers. It like the serialization of data for submission may have changed a lot recently.

**Comment by stellanl** [comment]
Confirmed. The app has stopped enclosing the geotag in the json answer.

**Comment by janagombitova** [comment]
Thanks for the updates @stellanl. Once you have ideas on how to resolve this we need to keep in mind that besides making sure new photos are handled well, that Flow can also handle photos and their tags that are already submitted and users expect to see the location data.

**Comment by stellanl** [comment]
Ok, then we have to put it in several places:

1. A data script that runs through image answers and tries to dig up the geotag if it has none. Slightly tricky due to the images being in S3 and data scripts not automagically having access to that.
2. The ingestion process to do it for every incoming image answer.
3. May have to handle late-uploaded images, too. Have to think about that.

Or we could replace 1 _and_ 3 with a cron job that runs once a day or so.

**Comment by janagombitova** [comment]
I will leave the technical solution up to you guys. I would like us to come with a comprehensive solution as: 
* We have photos already submitted that will need to be handled well, show their geotags 
* Not every app user will update to the latest version of the app, so photos will still come in with the same issue

**Comment by janagombitova** [comment]
@stellanl two questions: 
* How can we test this? 
* How can we make sure the script runs automagically so we do not need to manually trigger it? We know we will still get photos with the geotag not added in the right way as not everyone will update the app. So how can we make sure the problem is handled in a robust way?

**Comment by janagombitova** [comment]
After today's stand up we agreed to: 
* run the script with the release 
* create a cron job to ensure the tasks is run regularly that will be part of the next release: #3305

**Comment by stellanl** [comment]
Did anyone run the script? I know I didn't.
