### ISSUE TITLE
Setup tests for FolderSurveySelector component

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3183]
Setting up testing in the react side of the dashboard using [react testing library](https://github.com/testing-library/react-testing-library).

This is more like an experiment with `react-testing-library` if it's worth it or not

**Comment by janagombitova** [comment]
@marvinkome is the work here done? Can we close the issue?

**Comment by janagombitova** [comment]
All linked PRs are merged and released. If this still needs work - please reopen
