### ISSUE TITLE
Show all forms and indicate published ones in assignments 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3198]
With this issue https://github.com/akvo/akvo-flow/issues/3136 we are changing how the assignment are created and look to be able to allow assigning data points for large scale monitoring. 

We changed the assignment logic to only allow to have one survey per assignment. After selecting the survey, Salim will see a list of **published** forms he can then enable for the assignment. 

![61291652-bf409a00-a7d7-11e9-9bd3-58c8578c0a1f](https://user-images.githubusercontent.com/12456965/65583543-b4487980-df7f-11e9-88e2-33a99c26aef8.png)

However, what about cases when he selects a survey that **does not have** any published forms? Could we then add a sentence explaining that only published forms will show in the list? 

We agreed not to add the sentence `Only enabled forms will be submitted` as this is a limitation we will not be implemented in this iteration. But instead, could we show for cases, where the survey has no published forms a sentence `There are no published forms in this survey`? Or something like that? 

@Kiarii @muloem and @marvinkome what do you think?

**Comment by Kiarii** [comment]
Yes, definitely, it makes sense to notify the user if forms in the selected survey are not published. Sth like "Only published forms can be assigned" or selected. For later, we could perhaps consider couple this with some additional tweaks to keep things in perspective for the user: 
- show the forms in the survey and selection affordance but all in a disabled mode; so the user knows their forms are still intact and only a publishing is required to enable selection;
-  provide a direct link to the specific survey e.g. "Go to survey editor to publish forms" to make the task of going from assignments to survey editor a bit more straight forward..

**Comment by janagombitova** [comment]
The basic functionality works and we will add the sentence to the UI for now. I am keeping this issue open as I believe we should at least implement: 

> show the forms in the survey and selection affordance but all in a disabled mode; so the user knows their forms are still intact and only publishing is required to enable selection

But this is not a showstopper for the release. Thus open but not a high priority.

**Comment by marvinkome** [comment]
This issue is related to #3270 should this be moved to InProgress or Ready for testing?

**Comment by janagombitova** [comment]
@marvinkome I check and no. The idea of this issue is that you show all forms in the survey but only allow to assign those that are published. So the not published ones will not be selectable. 

Right now what we do, is we only show published forms in the list. I checked UAT2 and this is still what we do. So I would suggest we handle this change - showing **all** forms in the assignments for another time. It might be interesting to show the form name and version too.

**Comment by muloem** [comment]
We can probably pick up this issue now and I agree with Kiarii's proposal 
> show _all_ the forms in the survey and selection affordance but all in a disabled mode; so the user knows their forms are still intact and only a publishing is required to enable selection;

This means for surveys where there are no forms published, we show all forms but they are disabled and so the user is not able to select them to assign them. The same would apply to surveys where some forms are published and others are not.  We should show the unpublished ones but disable them and have some kind of marker or text to show that they are not published.

The second proposal about a link to the survey is a bit more difficult as we have not yet implemented a property routing setup so I would put that one on hold. 

@janagombitova does that capture the change as proposed?

**Comment by janagombitova** [comment]
@muloem I agree with everything you propose. A small simple `marker` could be just stating `Unpublished` behind the form name to make it clear why they are disabled. 

> The second proposal about a link to the survey is a bit more difficult as we have not yet implemented a property routing setup so I would put that one on hold.

I would put if fully on hold as in the future we want Salim to start in a survey and here edit the forms, look at data that belong to it, change the assignments to this routing will not even be needed as every action will live within the survey.
