### ISSUE TITLE
2nd dropdown does not show subfolders in surveys

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3209]
I have a folder within a folder and then another folder and only then my published survey. I want to be able to select up to that last folder, but the 2nd dropdown does not show after selecting my main folder showing the other subfolders. 

![Assignments 2nd dropdown does not show folders](https://user-images.githubusercontent.com/12456965/65580885-c8d64300-df7a-11e9-90c8-e1ab66bb3162.gif)

**Comment by janagombitova** [comment]
This issue is resolved via another Assignments change
