### ISSUE TITLE
Published forms do not show in survey

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3210]
After I select my survey, the list of published forms for that survey should show. After selecting a survey, with a published form, it does not show under forms. 
![Assignments pubished forms do not show](https://user-images.githubusercontent.com/12456965/65581486-d50ed000-df7b-11e9-9046-8df2350d8b73.gif)

**Comment by janagombitova** [comment]
This issue is resolved with the other Assignments changes
