### ISSUE TITLE
Tests for assignments ui move to react

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3212]
Create UI tests for assignments UI component

**Comment by janagombitova** [comment]
@marvinkome is the work here done? Can we close the issue?

**Comment by janagombitova** [comment]
I guess there is nothing user visible to test here. @marvinkome if you are all done with these tests and everything is reviewed and merged, please close the issue. If not, comment so we know where we stand. Thanks

**Comment by muloem** [comment]
All done! 👍
