### ISSUE TITLE
Auth0 session expiration

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-flow#3217]
https://manage.auth0.com/dashboard/eu/akvotest/tenant/advanced
###  Log In Session Management
  Inactivity timeout 60 MINUTES
  Users will be asked to log in again unless they are active within this period (max. 3 days). 

### Require log in after 
  480  MINUTES
  Regardless of activity, users will be forced to log in after the period (max. 30 days).

**Comment by janagombitova** [comment]
@muloem I suggest we handle this after the release (Auth0 + 1st assignments slice) either together with the next release (2nd assignments slice - assigning data points) or the release after that.
