### ISSUE TITLE
Improve date picker in assignments 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3223]
This issue is not a show stopper for the release. It can be handled in the next round. 

# Issue 
When testing the assignments on UAT1 branch v1.9.49-184-g75528b51 I noticed the date picker. Right now Salim has three ways to select the date: 
* type it in
* use the up and down arrows 
* pick from the calendar

![Flow assignments date picker](https://user-images.githubusercontent.com/12456965/66629574-7cd60000-ec02-11e9-997d-6a4a24857ac3.gif)

I expected to be able to do 'type it in' and 'pick from the calendar' "at once". What I mean is, that by clicking on the date box to open the calendar automatically while we highlight the DD to be typed in. Right now it took me a few seconds to realize I need to click on the little arrow to open the calendar. 

Secondly, I think we can remove the 'up and down arrows' (if this is not too much effort). I feel typing in the date or selecting on the calendar are the most common ways to set a date and do not see our users using the arrows. Plus the fewer options we give them the simpler we keep Flow.

**Comment by janagombitova** [comment]
Not sure with which PR you addressed this one @marvinkome but it works much better now.

**Comment by janagombitova** [comment]
Ah. I figured out what is different. It depends on the browser you use. With Firefox you get the expected behaviour where with Chrome you get what I showed in the issue description. Is there a way to unify the implementation across different browsers? Not a priority issue

**Comment by marvinkome** [comment]
For this, we can use a library like https://www.npmjs.com/package/react-datepicker
