### ISSUE TITLE
Showing selected devices in existing assignments 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3225]
![Flow assignments editing.gif](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/2a58a171-5e06-4020-bb74-526a550f4ffc)

When testing on UAT1 I noticed out device list in an existing assignment is a bit messy. When I open an existing assignment I would like to see the assigned devices as easily as possible. Right now all groups are opened by default what is not needed as I might not have all those devices assigned. 

Can we - when editing/viewing an existing assignment - open the device groups that have assigned devices in them?

**Comment by marvinkome** [comment]
Fixed in this Pull Request - #3231

**Comment by janagombitova** [comment]
Works like a charm 👍 Much better now
