### ISSUE TITLE
Change assignments UI to match mock ups

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3226]
With 1.10 we are releasing another round of changes to Assignments. The end goal is to enable users to assign not only forms to devices but also data points. See issue #2796 for all the details. 

This issue is to focus on ensuring the design of the Assignments page reflects the mock ups: https://projects.invisionapp.com/share/NHQGVLB2EKX#/screens/346093699
<img width="1267" alt="Screen Shot 2019-10-11 at 16 04 48" src="https://user-images.githubusercontent.com/12456965/66658010-e8d75900-ec40-11e9-9484-e968d02ceed1.png">

Please note that the new page, when creating a new assignment or editing an existing one) should be full-page. Right @Kiarii ? 

Please also note that we agreed not to assign devices using the pop up, but in the page - as implemented in 1.10. In the 1st version of assigning data points we will only implement the optionst to: 
* Assign all data points 
* Assign data point by name or ID 
This will be handled in another separate issue

**Comment by Kiarii** [comment]
> Please note that the new page, when creating a new assignment or editing an existing one) should be full-page. Right @Kiarii ?

yes, that was the thinking.. not just to simplify the page but also to accommodate the criteria functionality that will added later on

**Comment by marvinkome** [comment]
@Kiarii the assignment name field in the header, isn't it a bit confusing? It's more like a header than an input field

**Comment by Kiarii** [comment]
@marvinkome its both of those; a header and an editable field, that it is a field is revealed on mouseover.. we are already using this (design language) in Lumen. the idea is to improve the way we use screen space and bring more components and elements into view, without duplicating elements or having to scroll

**Comment by muloem** [comment]
There are still a couple of small issues to sort out in the UI

1. When a new assignment is created, the duration shows `NAN days`  We should probably replace this with something like a hyphen ` -- days` (or something else recommended by @Kiarii and @loicsans .

2. When hovering over the assignment name, the input box appears but that causes the content of the area below to be pushed and move downwards, ideally this shouldnt happen.

3. The styling of the dates can be made to match even closer the rest of the page.  The dates font looks out of place as it is currently styled.

![assignments-ui-mockups](https://user-images.githubusercontent.com/533336/68131295-19976f00-ff1d-11e9-94bb-c4ffbb217b04.gif)

**Comment by janagombitova** [comment]
I would like to add a few notes just based on the image in @muloem comment above. 
* I would fully remove the date calculator - `number of days` - as a lot of assignments are now made for at least 6 months, so this counter maybe a bit too over the top. Plus the dates are not a strong enforcement yet, so let's not put too much attention to them. 
* We need to remove the sentence `Data will only be submittable in this timeframe..` As that is not true at this moment. Form version and data points will be syncable in the timeframe, but Al will be able to submit new data even after the timeframe. This is a change we still need to consider in the future. 
* There is double line under the Assignments tab, can that be removed?

**Comment by janagombitova** [comment]
All good and tested on UAT2. Small improvements will be handled in a separate issue.
