### ISSUE TITLE
Fix duplication issue in assignments ui

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3227]
These are the set of fixes for this issue:

* [x] Change the title to 'Survey and forms' 
* [x] if possible remove the '0.1' and '03.' from all the three headers
* [x] move the survey dropdown right under the header 
* [x] remove the heading above the dropdown as within the dropdown we already state Choose a folder or a survey
* [x] under the dropdown change 'Select forms:' to only 'Forms' as indicated in the mock-up above  
* [x] under the 'Forms' title add 'Only published forms are shown in this list' (as we have with the 'Can't find your survey? Perhaps it has not been published yet. Only published surveys are shown in this list.' --> but this text should be fully removed as it is not 100% correct)

**Comment by marvinkome** [comment]
@janagombitova should the title be "Select survey and forms" or just "Survey and forms"?

**Comment by janagombitova** [comment]
@marvinkome it should be: "Survey and forms" and also just "Devices"

**Comment by janagombitova** [comment]
All works as expected. Well done 👍
