### ISSUE TITLE
Fixes for device selection in assignment ui

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3230]
@marvinkome Can you please: 
* [x] simplify the section title to 'Devices' 
* [x] remove 'Select device group'
* [x] only open the device group the user clicks on - right now it seems we open a random set of groups and sometimes not even the group you click on. 
* [x] add the option to select all devices within one group --> the checkbox on the device group level

**Comment by janagombitova** [comment]
The 'Select all' can be handled more elegantly by adding a checkbox to the level of the device group. @marvinkome is that too much work to squeeze in today? 
![Screen Shot 2019-10-15 at 14 27 17](https://user-images.githubusercontent.com/12456965/66831520-22b5a180-ef58-11e9-9954-71871a0b5eaa.png)

**Comment by janagombitova** [comment]
Moved the last comment to a new issue as it is not a show stopper for the release.
