### ISSUE TITLE
Add number of selected devices in assignment UI

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3232]
Add the number of selected devices as indicated in the mock-up below

![image](https://user-images.githubusercontent.com/12692444/61291652-bf409a00-a7d7-11e9-9bd3-58c8578c0a1f.png)

**Comment by marvinkome** [comment]
![image](https://user-images.githubusercontent.com/30107382/66913971-c1e8a080-f00d-11e9-83dd-04cd0b2e4f7d.png)

With the current implementation, if you click the checkbox the accordion will open or close. I'm suggesting i make only the Device name clickable, but with this, if you click the space nothing will happen too. What do you think @janagombitova @Kiarii

**Comment by Kiarii** [comment]
@marvinkome thats a good point, the checkbox should only enable selection. In addition we should use caret down and up icons in place of a [+] and [-] for indicating expanding and collapsing of accordion items so as not to confuse the users into wondering whether [+], [-] adds or removes devices..

**Comment by janagombitova** [comment]
Works well on UAT2
