### ISSUE TITLE
Add a Stats main tab

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#3235]
The UI part of #2612 Just like the Users tab; only visible to admins.
Works like the Data->Reports page, but (initially) only lets you order one type of report:
internal identifier STATISTICS, with optional start and end dates, and no other parameters.

**Comment by janagombitova** [comment]
@Kiarii could you provide @marvinkome and @stellanl with a mock up on how this page should look like in its most simplest form? Thanks

**Comment by janagombitova** [comment]
We connected with @marvinkome and @Kiarii about this page and agreed: 
* [ ] New page in Flow - `Stats` - that goes after the Messages tab 
* [ ] Stats page is only visible to users who have the admin role (same as Users tab)
* [ ] Salim can either download the stats from the beginning of time or by defining the date range in the date picker `Submission date`
* [ ] button to `Download` the get the sheet
* [ ] as it might take a but to create the file we will indicate in the UI that it is downloading. 

This page will be in React. Kiarii will provide the mockups.

**Comment by Kiarii** [comment]
here is an mvp for the page: https://invis.io/34UEEJSDQPY#/388892084_Stats_Mvp_-_Es
you should be able to click around.. after talking with @janagombitova we have decided that the default download time frame would be done by the system - the user doesnt need to see the dates in the field

**Comment by stellanl** [comment]
In case it was unclear, this report is created just like COMPREHENSIVE and DATA_CLEANING reports, with a POST at /rest/reports. Just like those, it can take a while, and when it is finished, the status will change and the user gets an email.

**Comment by marvinkome** [comment]
The mail the user gets has the download link for the report?

**Comment by janagombitova** [comment]
@marvinkome No. It is a generic email. I pasted the example below. The reason there is no link to directly download the file is to protect the data and ensure only logged in users can download the file. 

Hi,

Your Akvo Flow report is ready to download. Go to your Akvo Flow instance and download your export from the Export reports page.

If you did not request an export on Akvo Flow, please contact us at flowsupport@akvo.org

All the best,
Akvo Flow

**Comment by Kiarii** [comment]
after talking to @stellanl we decided that indeed, stats export will be handled as closely as data exports, the exported .xls will be listed for download inside the stats page.. I will respectively comment on the issue with mockups illustration..

**Comment by stellanl** [comment]
We can change the email content, yes. It will take some minor clojure changes. I will make a separate issue for that.

**Comment by marvinkome** [comment]
@Kiarii  so this means that the stats page won't be just the date and download button right? They'll be a list of other requested exports

**Comment by marvinkome** [comment]
@stellanl Stats created with that endpoint show up in *Generated exports* list. Is this the required behavior @janagombitova or it should be on the Stats page?

**Comment by janagombitova** [comment]
@marvinkome they should show in the new Stats page. @Kiarii will provide mock-ups on how to bring the list to the page.

**Comment by marvinkome** [comment]
So this issue has grown bigger 🙃

**Comment by stellanl** [comment]
Suggested text for the stats email:
Hi,\n\nYour Akvo Flow usage statistics report is ready to download. Go to your Akvo Flow instance and download your report from the Stats page.\n\nIf you did not request an report on Akvo Flow, please contact us at flowsupport@akvo.org\n\nAll the best,\nAkvo Flow

**Comment by stellanl** [comment]
Yes, @marvinkome. This is known as "feature creep" in the software business, and the tendency as "creeping featurism".

**Comment by Kiarii** [comment]
as promised, here are the stats mockup modelled to look and work like data exports: https://invis.io/9NUGWCM82MK#/389609091_0-_Stats_-_HOME_-_ES

**Comment by janagombitova** [comment]
@Kiarii thanks for sharing. Did you consider the option to have the generated list in the same page  as where you request the stats? Under, for example? So we remove the need to have 2 pages?

**Comment by Kiarii** [comment]
@janagombitova  not really, i stuck with the data model exports since we had figured out that that would simplify implementation..

**Comment by janagombitova** [comment]
@Kiarii Ok. As this is indeed the initial implementation we should not overcomplicate things but also accept that this page may change once we get to it. @marvinkome please follow the mock ups provided by Kiarii and the logic of how the data exports work.
