### ISSUE TITLE
Delete old messages

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#3236]
Currently messages are kept forever. The oldest instances have up to 400000. These cannot presently even be scrolled back to (#2070), and take up space.
We could delete them after, say, a year like some other entities.

**Comment by janagombitova** [comment]
Delete away!

**Comment by stellanl** [comment]
Test plan:

1. Check the existence of messages in the instance.
2. Trigger the purge through an URL like https://akvoflowsandbox.appspot.com/cron/croncommander?action=purgeOldMessages
3. Check that all messages older than 1 year are gone.
