### ISSUE TITLE
Clean up old broken assignments

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#3248]
Some SurveyAssignments were not converted because they were broken. They need to be repaired+converted or deleted.
Biogas/ -89 has at least two.

**Comment by janagombitova** [comment]
What do you mean by 'they were broken'?

**Comment by stellanl** [comment]
Assignments that had impossible data. Such as no forms. (In the case of Biogas they had no forms, no devices and no name.) The splitting script was written to not convert those to avoid creating even weirder cases.

**Comment by janagombitova** [comment]
I see. If all these cases miss data, no forms or no devices, then we should just delete them.
