### ISSUE TITLE
Search results should be returned considering the "To Date " to be inclusive

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#325]
Currently the To date provided in the search parameters in exclusive.
So if i want to fetch all records in till  31-Jul-2013, the "To" Date that i've to provide is 1-Aug-2013 which is not intuitive to the user.

We could append 23:59:59 to the To Date while firing the query or as Mark suggested increment the ToDate by one.

**Comment by rumca** [comment]
Searching todays date as the "To" date brings up today's results as expected - passes
