### ISSUE TITLE
Parse boolean options correctly

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#3252]
In #2285 we switched checking of boolean options from String.equals() to String.equalsIgnoreCase() which uncovered an old bug. Boolean options are passed in from Clojure as Boolean, not String like other options.
The parameter of the export() method is defined as Map<String, String>, but this apparently is never checked/enforced, and so Java assumes everything in the map is String.

**Comment by janagombitova** [comment]
I assume there is nothing user visible to check here and that all work is done. So I am closing the issue. If it needs to be reopened please do so with a comment.
