### ISSUE TITLE
Stop updating dependencies to minor version

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3257]
During every new docker build `package.lock.json` file is updated in the Dashboard code. This is due to update in minor versions based on what's in the package.json file.

The solution will be to use fixed versions of libraries to avoid updates to `package.lock` file when running docker build.

**Comment by janagombitova** [comment]
I assume there is nothing to test here. As the changes have been merged a while back I assume all work is done and the issue can be closed.
