### ISSUE TITLE
We need to provide an Order By option as part of the search criteria 

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#326]
We need to provide an Order By option as part of the search criteria so that the user can view the search results in a sorted manner.
Just providing a sort option on the UI table column won't do as that would only sort the results in that page.
 
A proposed design is 
![orderby](https://f.cloud.github.com/assets/4419787/892289/e407fb98-fa7d-11e2-9af4-480a8d9d6b3e.jpg)

This way we can just pass the orderby in the search query to datastore

**Comment by janagombitova** [comment]
Idea is part of a larger UI change in how we present data and is noted down in Product design repository. Closing this one down and once we go through the Discovery process we can recreate the issue again
