### ISSUE TITLE
Unpublished forms can be assigned when registration form is published

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3270]
On uat1, when creating an assignment it says:
"Only published forms are shown in this list"
but it is not true.
Steps to reproduce:
Create a survey with monitoring enabled and the registration form. Publish the registration form. Then add another form without publishing it. Reload the survey list then go to the assignments. You will see you will be allowed to assign both the published and the non published form. The issue with that is the app gets the assignment list and tries to download all the forms but the form that was not published does not have its zip file on s3 so app gets an error.

**Comment by janagombitova** [comment]
Just to add to this issue: You can see an example of it on UAT1

![Screen Shot 2019-11-05 at 11 56 11](https://user-images.githubusercontent.com/12456965/68202099-54ec7900-ffc3-11e9-9472-877f084cc20d.png)

**Comment by janagombitova** [comment]
Cannot replicate the issue anymore. Nice job 👍
