### ISSUE TITLE
Filter report list by reportType

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#3274]
From @muloem 
> So one comment I also made on the UI side of things, currently when you load the Stats page of the UI, it retrieves all reports including the comprehensive, raw data and statistics reports. I think it makes sense to update the reports endpoint slightly and only be able to query for reports of a specific type. e.g. `/reports?type=statistics` so as to avoid retrieving unnecessary reports for the user every time when they want to see the stats.

Related #2612

**Comment by stellanl** [comment]
Will take about an hour.

**Comment by muloem** [comment]
So the implementation done here takes care of the backend filtering. We now need to handle the frontend. i.e. make a request for filtered report types.
