### ISSUE TITLE
Stats - Excel not opening the file

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3288]
![Screen Shot 2019-11-11 at 10 11 14](https://user-images.githubusercontent.com/12456965/68575636-be113800-046c-11ea-8f5f-f44373683901.png)

When testing the Stats page on UAT2 I found that I cannot open the file on my Mac running Excel version 16.16.15. Once I upload the file to Google Sheets I can see and work with it perfectly. 

This issue is not a show stopper for the release but it should be looked into so we know if it is just a problem I have or others may have. If so, then we need to fix it.

**Comment by muloem** [comment]
Also as a minor issue but the name of all the files I downloaded are `STATISTICS-0.xlsx`.  do we want to add something like download date or time?

**Comment by janagombitova** [comment]
@muloem As we do not do that today for the data exports, I would suggest keeping things consistent. When opening the file you see the dates the stats are for. Once the change is out and we get some feedback we can make further adjustments. 

I would focus this issue on trying to resolve why Excel cannot open the file
