### ISSUE TITLE
Unpublished forms have been assigned to devices

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3298]
After fixing the issue #3270 but there are forms that were assigned while they have nothing on s3 which creates an error on the device. 
Option A
There maybe something that needs to be done to either remove these forms from assignment or publish them. Maybe a script for the backend?
Option B
The service that returns survey headers to the devices should check if the forms are published or not an only return the published ones

Example on uat1:
SurveyAssignment id:561369115 has a form with Id 227049116 which is set to NON_PUBLISHED

**Comment by stellanl** [comment]
A, yes, one of our datascripts coud do it.

B, which endpoint are you thinking about?

**Comment by valllllll2000** [comment]
> A, yes, one of our datascripts coud do it.
> 
> B, which endpoint are you thinking about?

I think I can do B for "getAvailableSurveyGroupsDevice"

**Comment by stellanl** [comment]
Well, in org.waterforpeople.mapping.app.web.SurveyManagerServlet.getSurveyGroupsForPhone(), there is already sanity-check code on line 237 that ensures the form exists.

**Comment by valllllll2000** [comment]
We need to check if it's published or not and not return non published ones right?

**Comment by valllllll2000** [comment]
I am pasting here the comment from @muloem 
`Then we are patching the code for a situation that will not happen once the bug is fixed. which is something extra that a maintainer will have to look into and understand should they have to change this code later on`

**Comment by stellanl** [comment]
Yeah. Since we already do a ds fetch of the form,we would not add any delay.

**Comment by valllllll2000** [comment]
Points to consider:
Does the form return to "NOT PUBLISHED" after modified?
What if a form has an older version, we still want that to be sent to devices.
Is there a case where an unpublished form should be assigned?
There are other statuses than Published and Not Published or so it seems in the Survey class

**Comment by valllllll2000** [comment]
Here is the method where it happens
https://github.com/akvo/akvo-flow/blob/develop/GAE/src/org/waterforpeople/mapping/app/web/SurveyManagerServlet.java#L188

**Comment by valllllll2000** [comment]
Ok now I realized there are 2 objects in the datastore that refer to assingments:
DeviceSurveyJobQueue -> used for getting assingments for android
SurveyAssignment

**Comment by stellanl** [comment]
Yes, the DSJQ is mostly a cached JOIN between tables.

**Comment by muloem** [comment]
So given that we have fixed the bug, I believe its better to have a script to cleanup rather than include code that will be checking for something non-existent after fixing the bug and cleaning up.

**Comment by stellanl** [comment]
Just for reference, could we maybe  make a little state descripton of publication status and version of forms?

**Comment by valllllll2000** [comment]
So the logic of the script will be to get all the forms in version 1 which are not published and then remove its id from DeviceSurveyJobQueue and SurveyAssignment.

I confirmed that a form cannot have a version later than 1 if it was never published
When a form version changes it becomes NOT_PUBLISHED although its previous version has been published.

**Comment by valllllll2000** [comment]
## Test plan
Nothing to test, this does not affect flow code.
In order to test how the script works you need to have some assignments with unpublished  monitoring forms.
Once you have them run the script. After running, your assignment should only have the published forms, the ones that are not published and in version 1 will disappear.

**Comment by valllllll2000** [comment]
Ran the script after original issue has been fixed. All done!
