### ISSUE TITLE
Stats - list does not load if you request the export without dates 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3299]
![Flow - Stats](https://user-images.githubusercontent.com/12456965/68862635-160aa180-06ee-11ea-9bb5-a7c847d0a7ed.gif)

You can request a Stats export in two different ways: 
* specifying the dates 
* without any dates specified 

The 1st case works well. For the second, when I do not specify the dates, the Export list does not load. Only once I receive the email that my export is ready, the list shows up properly again.

**Comment by muloem** [comment]
The stats list gets stuck in the `Loading...` state if there happens to be a report with the status `IN_PROGRESS`

**Comment by muloem** [comment]
LGTM! 👍
