### ISSUE TITLE
Empty devices group is still clickable

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3301]
In devices groups that have no associated devices, it is still possible to click on the checkbox to select all devices in the group. This may be confusing when the user attempts to look at the devices in the list.

@Kiarii what do you recommend? 
Possible solutions: disable the checkbox, show a message when opening the accordion that no devices are in the list, something else..?

![devices-groups-empty](https://user-images.githubusercontent.com/533336/68869651-d34ec680-06f9-11ea-83d1-fdb7b7b4ae9b.gif)

**Comment by Kiarii** [comment]
this should work as with other device groups, the checkbox selects all devices in a device group, the caret opens a device group for individual device selection..

**Comment by marvinkome** [comment]
I don't really understand this comment @Kiarii

**Comment by Kiarii** [comment]
Ah, i see now what the question meant; I think in that case we should not allow the selection of an empty device group - by disabling the checkbox, additionally we can add "0 devices in group" next to the device group name..
