### ISSUE TITLE
Create cron job to fix geotags

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3305]
Based on #3180 

We have an issue in Flow where photos submitted from older Flow app versions to not get geotagged properly. We created a script to fix it, but we know we will still get photos with the geotag not added in the right way as not everyone will update the app. 

We decided to make the script into a cron job so the tasks is run regularly and users do not notice that their photos are not well geotagged. 

@stellanl can you take care of this for the next release? thanks

**Comment by stellanl** [comment]
Test plan:

1. Submit some images from an old version of the app.
2. Trigger the cron job from a browser: https://akvoflow-uat1.appspot.com/cron/croncommander?action=extractImageFileGeotags
3. Inspect the data and see hat the geotags show up
