### ISSUE TITLE
Assignment fails to load folder

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3310]
I ma getting this error on uat1
![Screenshot from 2019-11-20 13-26-32](https://user-images.githubusercontent.com/923280/69239000-89525e80-0b99-11ea-89a3-ceac94ef1ca3.png)
The folder does contain lots of surveys.
One of the surveys was imported from another dashboard
That survey is not published

**Comment by muloem** [comment]
This issue was based on test data.  We need to verify whether it is still the case and if not we can close this one.

**Comment by muloem** [comment]
Tested and is no longer an issue: 👍
