### ISSUE TITLE
Number questions are broken

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3311]
This issue can be reproduced on uat1 which has version v1.10-757-gfb9ff874  and also welthungerhilfe with v1.10.1-2-g4cebc044.

The Number question form structure has changed and we now have:
```
<question id="567699119" localeNameFlag="true" mandatory="true" order="1" type="free">
            <validationRule allowDecimal="false" maxLength="0" signed="false"
                validationType="numeric" />
            <text>number</text>
        </question>
```
the maxLenght=0 prevents the app from correctly processing the question type number.
No matter what setting we put for number question this maxLenght is always 0. On dev2 with v1.10, the issue does not happen.

**Comment by valllllll2000** [comment]
Could this have been the result of these changes https://github.com/akvo/akvo-flow/issues/3115

**Comment by muloem** [comment]
@valllllll2000 yes It is a result of those changes

**Comment by valllllll2000** [comment]
## Test plan
The best way is to run the tests by creating a number question but also all other questions possible to make sure they all work on the app.
1. Create and publish the form with most question combinations (see regression tests for ideas)
2. Assign to device
3. Submit and sync
4. Create 1 report
The change may affect other question types!!!

**Comment by valllllll2000** [comment]
All fixed on latest version
