### ISSUE TITLE
Form export fails on empty QG

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#3334]
An empty QG will trigger an NPE on any kind of export; both data and form structure.

**Comment by stellanl** [comment]
Protecting angainst the NPE is trivial, but it raise an interesting question, how to show an empty group in the form structure spreadsheet.
Current logic makes one row per question, so an empty group disappears completely.
The alternative is to make a row with just the group name but no question info for this case.

**Comment by stellanl** [comment]
Test plan:
Create or modify a form to have an empty question group.
From Data->Exports create a "Survey form" export.
You should get an Excel file with the empty question group clearly visible on the second tab.

**Comment by valllllll2000** [comment]
Tested on version  v1.10.1-83-gcbde11dd on uat1. Survey is Valeria Test 2 -> Option multiple / New Form id 587299126. I did not see any error logs in GAE console.

**Comment by valllllll2000** [comment]
All fixed
