### ISSUE TITLE
Form export for number questions mixes up min and max settings

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3340]
When creating `Number` type questions, we can specify the min and max values to restrict the response range.  However when we generate a form export, these values are mixed up

Steps to reproduce

1. Create or select a survey with a number question that has min and max values set

2. Generate a survey form export report

3. Check the _Full Survey_ sheet and look at the question settings.  The min and max settings are mixed up.

**Comment by stellanl** [comment]
The test plan is identical to the "Steps to reproduce".

**Comment by muloem** [comment]
@stellanl can you maybe add a unit test for this?

**Comment by stellanl** [comment]
Sounds difficult. The test would need to 

1. create a survey with a numerical question
2. order the report
3. download the report spreadsheet
4. parse it
