### ISSUE TITLE
Allow filtering data points on prefix of displayName

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow#3343]
This is to support #3297.
Currently, the /rest/surveyed_locales endpoint allows filtering by 
surveyGroupId, identifier or displayName. These must match exactly.
To allow practical searching by displayName while assigning data points to devices, we could add a parameter that allows getting all data points whose display name **begins** with _string_.
So if the parameter is "ABC" we would return all DPs with displayName >= "ABC" and displayName <"ABD".

**Comment by stellanl** [comment]
Test plan:

1. Run Flow locally.
2. From a browser, connect to http://akvoflow.local:8888/_ah/admin/datastore, look in the surveyedLocales entities to see what displayNames exist.
3. From a browser, connect to http://akvoflow.local:8888/rest/surveyed_locales?displayNamePrefix= (and a prefix of a displayName you know from 2. to exist.)
4. You should get a JSON list of data points.

**Comment by stellanl** [comment]
In a conversation w @muloem and @marvinkome, agreed to add further "search" parameter to try to filter data points by _either_ identifier or display name.

**Comment by stellanl** [comment]
Also, the search needs to filter by (UI)survey.

**Comment by muloem** [comment]
@stellanl I just tried testing on a branch where the UI is implemented and I get back the entire list of datapoints from the backend instead of a filtered list

![search-datapoints](https://user-images.githubusercontent.com/533336/73756549-0d16f280-4768-11ea-863b-eacf10eec8ca.gif)
