### ISSUE TITLE
Long datapoint display names are not inserted into data store

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3363]
Create a survey with text and number use them both for datapoint name. Make it a registration form in a monitoring survey.
Fill in the survey on your device, for the text write and answer of more than 1500 chars and submit.
When viewing the data on another device you will see that only the number is used as datapoint name, the text disappears

**Comment by valllllll2000** [comment]
see screenshot example here https://github.com/akvo/akvo-flow/issues/3317

**Comment by stellanl** [comment]
Root cause is that displayName is only assembled from the **value** field, and an answer > 500 chars is stored in the **valueText** field. Now that displayName can be 1500 chars, we may want to either increase answer max length to 1500 chars to match, or use valueText when assembling displayName.
