### ISSUE TITLE
Export fails when NUMBER question contains invalid data

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#337]
When trying to convert string values to numeric on _NUMBER_ questions, we could potentially have wrong data in the datastore.

If the process fails to convert the value, it should fallback to the string representation.

Expected behavior:
* The process should finish with string cells when the conversion is not possible

Current behavior:
* The whole export process gets cancelled

**Comment by jonase** [comment]
@mtwestra @iperdomo I'm not sure what's left to do here. The commits from 2013 is already in the develop branch.

**Comment by mtwestra** [comment]
@jonase, if the commits provide the expected behaviour described above, I guess we are done

**Comment by rumca** [comment]
fixed Aug 2013 - closing this
