### ISSUE TITLE
Run frontend snapshot tests as part of the build process

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3374]
We currently implement snapshot testing for the new react frontend components, however, in order to run the tests, `npm run test` needs to be executed manually.  We should include the test execution by default when building the UI.

**Comment by marvinkome** [comment]
I think Travis automatically does this.

**Comment by muloem** [comment]
As far as the build logs I have reviewed from travis, I dont see any that run the frontend tests.
