### ISSUE TITLE
Data cleaning report generates gaps on deleted iterations

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#3382]
When a user deletes an _iteration_ of a repeatable question group, the _DATA CLEANING_ report generates gaps in between. Example:

![2020-01-07_973x315_scrot](https://user-images.githubusercontent.com/178474/71901410-2f652280-3160-11ea-965b-d8a04e0d2465.png)

In the example the `iteration=0` for form instance `579789116` and `iteration=1` for instance `573639119` were deleted, but the sheet created for the repeatable question group (Group 3) contains gaps.

Sample dataset:
* Instance: UAT1
* Form Id: 571789118

**Comment by stellanl** [comment]
Found this TODO in org.waterforpeople.mapping.dataexport.InstanceData.InstanceData(SurveyInstanceDto, Map<Long, Map<Long, String>>):

```
        // Need to normalize the response map and add empty answers for missing iterations
        // as well as make sure that the iterations are sorted
        // TODO: Drop iterations with all empty answers (?).
```

**Comment by iperdomo** [comment]
> We could renumber the iterations to have no index gaps. However, that should probably be done on data ingestion, not as part of report generation, as then the index will not match when importing after data cleaning.

Yeah, let's not mess with re-indexing answers. We're working on not having gaps in the app - https://github.com/akvo/akvo-flow-mobile/issues/1564

**Comment by iperdomo** [comment]
I checked the same report on the most recent version of the deployed service. There are gaps in the indices, but not empty lines :+1: 
![2020-02-26_941x270_scrot](https://user-images.githubusercontent.com/178474/75327694-226dd100-587d-11ea-9312-ecbc31b11300.png)

**Comment by iperdomo** [comment]
Code deployed https://travis-ci.org/akvo/akvo-flow-services/builds/655267535
