### ISSUE TITLE
Errors in the stats summary sheet

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3406]
The stats sheet that shows an overview of all the form submissions in an instance is showing some errors where there should be survey information.  See the screenshot.

<img width="519" alt="Screenshot 2020-02-05 at 13 00 08" src="https://user-images.githubusercontent.com/533336/73840049-9e916d80-4817-11ea-9a22-15c2ad81c096.png">

**Comment by stellanl** [comment]
That is intentional, when the parent of a form has itself as a parent. The error is in the data. An infinite folder loop.

**Comment by stellanl** [comment]
There were three SurveyGroups that had themselves as parent. I repaired it by copying parentId from the ancestorIds array (after checking that that parent still existed).
