### ISSUE TITLE
Use external provider for sending emails

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#3407]
We're using the `javax.mail.*` API and GAE's [`MailService`](https://github.com/akvo/akvo-flow/blob/2e408fe26a81c71b66dc09ddd09543f022838eb6/GAE/src/com/gallatinsystems/common/util/MailUtil.java#L34) for sending email. In Lumen and other services, email notifications go through MailJet.

In fact is the recommend way:

> To send email, use a third-party mail provider such as SendGrid, Mailgun, or Mailjet. All of these services offer APIs to send emails from applications.
https://cloud.google.com/appengine/docs/standard/java11/java-differences#mail

**Comment by muloem** [comment]
Being handled in #3484
