### ISSUE TITLE
How to handle datapoint assignments in old versions of the app

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3410]
# Context
In the new datapoints assignment feature, we will be able to assign individual datapoints to a device for monitoring. However, this will only work if one also has the latest version of the app that supports datapoints assignments.  If a user has an old version of the app, they will download _all_ datapoints as happens currently.

# Problem or idea
In case a user attempts to assign datapoints to a device that contains an old version of the app, they may be confused when the assignment works but then all datapoints are downloaded instead of the specific ones assigned.

# Solution or next step
Since the old version of the app works by downloading all the datapoints, we need to let the user know whether a device they are assigning datapoints to has the old app version and inform them somehow that they cannot assign datapoints because of the app version.

Another possibility could be to have the current API not feed all datapoints but rather only send the datapoints that have been assigned.

**Comment by Kiarii** [comment]
> In case a user attempts to assign datapoints to a device that contains an old version of the app, they may be confused when the assignment works but then all datapoints are downloaded instead of the specific ones assigned.

is it possible for Flow dashboard to determine the app version for a specific device? If so, a notification to update the app could be made on the dashboard - when a device is added to an assignment for instance..
