### ISSUE TITLE
create terms of service acceptance page for FLOW

### ISSUE THREAD

**Issue by caetie** [akvo/akvo-flow#342]
## Summary
* Need to show all users Terms of Service accept/don’t accept page when they log in to FLOW Dashboard.

## Details
* FLOW needs an “I agree to the TOS/C before I use FLOW”, for the Dashboard, everyone should check the box, and we need to record that they did it, and when they did it;

## Requirements
* At a Dashboard user’s first log-in after implementation of this feature, they need to see a screen where they must chose to agree or disagree to the FLOW Terms of Service/Terms and Conditions
* If they agree, they can proceed, if they disagree they cannot access the Dashboard
* When they agree, we need to record their gmail address, Dashboard username, and the date/time stamp for when they agreed

## Design/Functionality Questions:
* Want full text of terms of service in view, or just a link to them, or both? [screen 2b]
* Want to record anything else when they click “I agree”? [2b]
* Do we want to record anything if they choose “I do not agree”? [2b]
* What kind of product would we like for the TOS acceptance information? 
* Need this for 1.0 Dashboards too?

## Tech Questions:
* Can we keep them out of the Dashboard without logging them out of google?
* How can we give people the opportunity to reload, or see the TOS page again (2b)?

dropbox for mockup PDF: https://www.dropbox.com/s/8yeyurulz9i9amn/FLOW_TOSaccept_v0.pdf

![termsofserviceacceptance](https://f.cloud.github.com/assets/1315528/1035823/de8339cc-0f30-11e3-9319-3b59ab4745dc.png)

**Comment by janagombitova** [comment]
Recreating the issue in product design repository as we need to look at this opportunity properly to understand the value and requirements. New issue exists here: https://github.com/akvo/akvo-product-design/issues/177
