### ISSUE TITLE
Add Cypress for Integration testing into FLOW

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3422]
# Context
**Why do we add this issue?**
Currently, they're no tests in the FLOW Dashboard which make it hard adding new features without the fear of breaking something else.

# Problem or idea
**What is the cause?**

# Solution or next step
**How could we solve it?**
Using Cypress, we can add integration tests for asserting that functionalities work as they're supposed to and break when they're supposed to

**Comment by iperdomo** [comment]
Let's hold this effort and try to agree how we want to approach testing of Flow
cc/ @muloem @dlebrero
