### ISSUE TITLE
Wrong message about no devices added even when there are devices

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3435]
# Context
**Why do we add this issue?**

Wrong message about No Device being added in the device tab even after devices have been added to an assignment

![image](https://user-images.githubusercontent.com/12692444/74819618-58550780-5309-11ea-830e-bf5bcedea480.png)

# Solution or next step
**How could we solve it?**

Show this page to users only when there are no devices added

**Comment by janagombitova** [comment]
As far as I can tell, resolved
