### ISSUE TITLE
Saving should not take user back to assignments list

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3436]
# Context
**Why do we add this issue?**

It seems strange that an assignment cannot be saved until all the components - duration, forms, devices - have been defined. I think the user should be able to save an assignment at any point in its editing

# Solution or next step
**How could we solve it?**

Leave users on the assignment page even after saving. Users can choose to go back by clicking the back button.

**Comment by janagombitova** [comment]
I disagree with this issue as across Flow and Lumen we have the workflow that 'saving' means completing the work. It means that you have done what needs to be done and are ready to move on. If we had autosave it would be a different world. But to keep our product workflows unified, saving should indeed bring the user back to the list.
