### ISSUE TITLE
Clean up tabs functionality in Assignments

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3440]
# Context
**Why do we add this issue?**
The current implementation of tabs is jam-packed, making it difficult to move between tabs.

# Solution or next step
**How could we solve it?**
Use the React context to handle changing tabs, so tabs can be changed easily from anywhere in the component tree

**Comment by muloem** [comment]
We parked this for now and will pick up as part of a bigger refactor.
