### ISSUE TITLE
Make the assignment name border more visible

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3446]
# Context
Why do we add this issue?
to make it obvious that this is an editable element.

# Solution or next step
How could we solve it?
keep the Assignment name field's border in view by default - but with a lighter shade than when active

**Comment by janagombitova** [comment]
I am not sure what the expectation here is, but the name border seems visible enough to me. I am closing the issue as I think it is done done. If needed please reopen.
