### ISSUE TITLE
sort device groups and devices names alphabetically in assignments

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3447]
# Context
Why do we add this issue?
So its easier for the user to scan and find devices (groups) of interest

# Solution or next step
How could we solve it?
Sort device groups and devices names alphabetically in assignments

**Comment by muloem** [comment]
@marvinkome the devices are sorted with the ones not in a group coming first, however, the remaining devices seem to be sorted in descending order, i.e from z -> a rather than from a-> z?

**Comment by janagombitova** [comment]
Works on UAT1 as far as I can tell
