### ISSUE TITLE
Add "Assign all datapoints" feature to the datapoints assignment

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3457]
# Context
We have recently release the MVP for datapoints assigment.  This enables the assignment of datapoints individually to each device. The previous versions of assignments only supported creating an assignment and associating survey (forms) to devices.  Once this was done a device was able to download _all_ the datapoints in a survey to a device that had them assigned.  With the new functionality, no datapoints are downloaded unless a user explicitly assigns them to a device.

# Problem or idea
There are a few issues that have arisen as a result
- For some users it is cumbersome to assign individual datapoints and therefore they do not select them but rather simply want to assign _all_ datapoints to a device. 
- in addition, assigning datapoints means that in addition to creating the assignment and adding devices like before, the user has to edit each device to assign datapoints to them one-by-one.
- when users create an assignment, they expect the old behaviour i.e. all datapoints will be downloaded, but it does not happen and so they are reporting that something is wrong

# Solution or next step
- Build the _assign all datapoints_ functionality
- By default we should maintain the old behaviour i.e. when an assignment is created, all datapoints are assigned as the default. if the user then edits the assignment, then it will be updated and only the assigned datapoints will be downloaded

**Comment by muloem** [comment]
<img width="1113" alt="Screenshot 2020-03-05 at 20 28 10" src="https://user-images.githubusercontent.com/533336/76018068-f0fda100-5f1f-11ea-8f1d-ce40d5eb9950.png">



<img width="1087" alt="Screenshot 2020-03-05 at 20 27 56" src="https://user-images.githubusercontent.com/533336/76018078-f5c25500-5f1f-11ea-871b-4b13019aa2e0.png">

**Comment by iperdomo** [comment]
@marvinkome this string needs translation:
https://github.com/akvo/akvo-flow/blob/ca01e8d188c6130dfbcb531b51fcf800b38b4a48/Dashboard/app/js/lib/components/devices/AssignmentsEditView/screens/AssignDatapoints/AllDatapoints.jsx#L11

Please remove the "20k" part as we're not giving the user the number of datapoints assigned

**Comment by iperdomo** [comment]
My understanding is that assigning all data points is _per device_ and not  **global** to the assignment, is that correct? @Kiarii @muloem 

If that is the case, @marvinkome we need to fix the flag `allDataPointsAssigned`
https://github.com/akvo/akvo-flow/blob/ca01e8d188c6130dfbcb531b51fcf800b38b4a48/Dashboard/app/js/lib/views/devices/assignment-edit-views.jsx#L79

Right now assigning all data points to 1 device, makes it "global" and all other devices follow the same pattern
![Peek 2020-03-11 05-38](https://user-images.githubusercontent.com/178474/76383347-d2523c80-635b-11ea-9e4e-f1081407884d.gif)

**Comment by Kiarii** [comment]
> My understanding is that assigning all data points is per device and not global to the assignment, is that correct?

@iperdomo yes, that is the case, the whole idea around datapoint assignment is to move towards assigning a subset of datapoints to devices..

**Comment by iperdomo** [comment]
@Kiarii just to confirm, when we choose _All data points_ is just for the **selected** device, and in the same _Assignment_ we can choose a subset for a different device?

**Comment by Kiarii** [comment]
@iperdomo yes

**Comment by muloem** [comment]
I run some tests and have been able to successfully download up to 1000 datapoints on a device when added to the assignment.

Also the assign and unassign works as expected + default assign all.

I think this is good to go for release. 👍
