### ISSUE TITLE
Review the way assignments are currently handled

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3458]
# Context
In order to transfer surveys (forms) to devices, we create assignments where we associate the two types of entities.  When a device is associated to a survey through such an assignment, that device then downloads the survey and respective forms.  However, the device does not have any idea/concept of an assignment.

# Problem or idea
The main purpose of creating assignments was to associate devices to survey (forms). Beyond that they disappear and are no longer visible in the data collection and analysis, nor are they visible on devices to differentiate between assignments.

Some strange conflicts occur e.g. if two assignments were created with the same devices and the same survey (forms), the device still only receives the survey (form) once and does not distinguish whether the form downloaded was from the first or the second assignment.

# Solution or next step
Explore the possibility of eliminating the concept of assignments and handle associating forms with devices directly under the devices tab or in the surveys themselves.

**Comment by janagombitova** [comment]
I am going to close this issue for now as it brings the question of a larger restructuring of Flow, that we need to look at more comprehensively before we make a task out of it. What I mean is we might want to move away from the current need to always select a survey to actually bringing tasks under the survey. Then assigning actions like assigning, looking at data, exporting will all live under the survey.
