### ISSUE TITLE
Walkthrough for datapoint assignments

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3466]
# Context
A follow up from #3168

@muloem has made a suggestion that we consider using walkthroughs to introduce new features or actions that users can now do; For this page, one of those actions is the "Assign Datapoints" which we can introduce or highlight as follows (the text is up for adjustment..)
![image](https://user-images.githubusercontent.com/12692444/75752338-30b26600-5d31-11ea-9cc7-d106edfb834f.png)

# Problem or idea
When new features are introduced, users are usually not aware of them because we may communicate it through emails to the organisations who may not spread that information to their users. We would like to start with adding walkthroughs for datapoint assignments to test the approach.

When should the walkthrough be activated?  Should we start to keep log of last user login in order to determine when to give a walkthrough? (@iperdomo and @marvinkome can you figure out this one please?)

# Solution or next step

**Comment by Kiarii** [comment]
Onboarding the user to  changes in assignments; this would be shown to users when they first encounter the new assignment look:
https://invis.io/23WFUX5GAZY#/409571778_0-0_New_Assignment_-_ES_-_WT_-_S1

Texts are up for revision and refinement

**Comment by iperdomo** [comment]
@Kiarii the design at https://invis.io/23WFUX5GAZY#/409571778_0-0_New_Assignment_-_ES_-_WT_-_S1 is more like **News**, right? It's not a walk-through similar to this one: https://introjs.com/example/hello-world/index.html

**Comment by Kiarii** [comment]
@iperdomo it is an onboarding element, it announces the change and tells briefly what the user shd expect..
Walkthrough for selecting forms and assigning datapoints are in the making..these however might not be as complex as with the example you provide, it might suffice to indicate to the user where they can find the action to assign datapoints as long as the rest of the process is straightforward and self explanatory/intuitive..

**Comment by Kiarii** [comment]
not sure if work on the onboarder has begun, I would like propose a simpler modal for this; for now.. since we will also highlight the changes in respective screens when the user gets there.. texts and wording are up for refinement
![image](https://user-images.githubusercontent.com/12692444/77150060-a8a3be80-6a9b-11ea-8784-4f351cf394ed.png)

**Comment by Kiarii** [comment]
After the onboarding screen above, we have two screens where highlight/spotlight the mentioned changes. The first one is the limitation of form assignment to a single survey;

![image](https://user-images.githubusercontent.com/12692444/77526145-cd7ca500-6e92-11ea-846a-3465290af682.png)

This will require that we label the survey navigation "Survey" and restructure the form section as follows;
![image](https://user-images.githubusercontent.com/12692444/77529690-c48ed200-6e98-11ea-979d-5ccdc964a71f.png)

**Comment by Kiarii** [comment]
The second spotlight is shown for monitoring assignments, when the user first encounters datapoints assignment to devices;

![image](https://user-images.githubusercontent.com/12692444/77529848-146d9900-6e99-11ea-9778-4acf123b2953.png)

**Comment by janagombitova** [comment]
Two comments on the issue: 
* the text is quite formal and not "Akvo" like where we keep our communication simple and friendly so we should consider adjusting it. Have we run the text by MarComms? 
* To make the walkthrough release ready we should translate the assignment changes and the walkthrough to at least French and Spanish if not all supported languages.

**Comment by janagombitova** [comment]
I agree that a walkthrough is a great way to introduce new functionality or a change to a feature, but I think with the proposed 2 spotlights we miss the the step that Salim needs to click on the devices in the sidebar to see the Assign data point option. So we should have a spotlight for that too. 

So the tasks we should do to get this one out there: 
* [ ] 3rd spotlight highlighting the devices in the sidebar
* [ ] review the text to make it more Akvo-like
* [ ] translate to at least Spanish and French

**Comment by janagombitova** [comment]
Considering this feature has been released for long time now, we do not need a walkthrough anymore.
