### ISSUE TITLE
Fix the UI for Assignments with a lot of forms and devices 

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3475]
# Context
We have recently transformed the assignments interface to enable assigning datapoints to individual devices.

# Problem or idea
The UI of the assignments keeps the footer bar fixed when there are lots of forms and devices, which results in the footer bar overlapping these lists.

![lots-of-forms](https://user-images.githubusercontent.com/533336/76898088-4da07a80-6895-11ea-863a-6505bbdc51f1.gif)

**Comment by marvinkome** [comment]
Fixed in #3485
