### ISSUE TITLE
Automatically take users to datapoints page after adding devices

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3476]
# Context
Why do we add this issue?
After adding a device some users wouldn't know what do next

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?
We could solve this by taking the user automatically to the datapoints assignment page after devices have been added

**Comment by janagombitova** [comment]
https://github.com/akvo/akvo-flow/pull/3477#pullrequestreview-376869064 

I agree with @muloem that this is maybe not the best way to solve the problem: "After adding a device some users wouldn't know what do next". I would rather we explore a few options as prototypes (draw them out) before we make changes to the implementation. Let's create a new fresh issue to talk about this problem.
