### ISSUE TITLE
CSS Issues with Assignments

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3478]
# Context
Why do we add this issue?
Fixing issue reported in with assignments

- https://github.com/akvo/akvo-flow/issues/2796#issuecomment-599978737
- https://github.com/akvo/akvo-flow/issues/2796#issuecomment-600501026

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
As part of exploring the new assignments I have checked this on UAT1 and all issues are resolved. Well done. Closing the issue
