### ISSUE TITLE
Bug with folder survey selector

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3483]
# Context
Why do we add this issue?
there is a bug with the published form; tricky to describe but I captured it:

![image](https://user-images.githubusercontent.com/12692444/76842641-3df84600-6843-11ea-9f51-4cca14d5be60.gif)

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
Selecting folders and surveys and then unselecting and then selecting and unselecting, etc updates well. Job done
