### ISSUE TITLE
Akvo Flow Web cannot send zip file to the API Endpoint

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/akvo-flow#3495]
# Context
Post zip data and zip images from the Akvo Flow Web is not working anymore.

# Problem or idea
Hi @iperdomo, We do a test to send the zip file for (Akvo Flow data and Images) and the logs return 200 for  POST ``` /submit-form ``` and OPTIONS ```/upload-image``` but return internal server error for POST ```/upload-image```.  Then we check the **inspect tab** in Akvo Flow Workspace, and the data is not showing.

Backend Log:
```
INFO:werkzeug:127.0.0.1 - - [07/Apr/2020 17:33:36] "OPTIONS /submit-form HTTP/1.1" 200 -
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): flow-services.akvotest.org
DEBUG:urllib3.connectionpool:https://flow-services.akvotest.org:443 "POST /upload HTTP/1.1" 200 2
INFO:werkzeug:127.0.0.1 - - [07/Apr/2020 17:48:28] "OPTIONS /upload-image HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [07/Apr/2020 17:48:28] "POST /upload-image HTTP/1.1" 500 -
```

Akvo Flow Web: ```https://tech-consultancy.akvo.org/akvo-flow-web/<instance_name>/<form_id>```, username: <any_device_identifier>, password: please ping me.

# Solution or next step
Are there any changes to this method? How could we solve it? also, can we use the prod instead of *flow-services.akvotest.org*?

**Comment by iperdomo** [comment]
@dedenbangkit not sure if I understand the problem. Flow services does *not* have an `/upload-image` endpoint, only `/upload`.

In your logs I think those `/upload-image` are _access logs_ of the service calling Flow services?

**Comment by dedenbangkit** [comment]
> @dedenbangkit not sure if I understand the problem. Flow services does _not_ have an `/upload-image` endpoint, only `/upload`.
> 
> In your logs I think those `/upload-image` are _access logs_ of the service calling Flow services?

Oh yes, we are so sorry, it was our backend endpoints. Let us print the ```/upload``` endpoint first.

**Comment by dedenbangkit** [comment]
Hi @iperdomo 

We have tried to debug the endpoint, and yes it returns 200, log:

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): flow-services.akvotest.org
DEBUG:urllib3.connectionpool:https://flow-services.akvotest.org:443 "POST /upload HTTP/1.1" 200 2
=============SEND DATA=============
INFO:root:<Response [200]>
===================================
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): flow-services.akvotest.org
DEBUG:urllib3.connectionpool:https://flow-services.akvotest.org:443 "POST /upload HTTP/1.1" 200 2
=============VERIFY DATA=============
INFO:root:<Response [200]>
===================================
```

Could you please check the log from your side? (*flow-services.akvotest.org*)
