### ISSUE TITLE
Assignment action hidden due to multiple scrolling

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3497]
# Context
Why do we add this issue?

# Problem or idea
When assigning devices (or data points to that matter) the main action button is on the bottom of the page. This means Salim has to not only scroll the list of data points but also scroll the page to find the action button. But if he does not know it is there, he might miss it making it hard to complete the assignment. 

![Assignments - main action button.gif](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/3fc2ceb4-20c2-466e-9345-976167e80a49)

# Solution or next step
@muloem and @marvinkome can you look at how to solve this? Considering @Kiarii is on holiday. @loicsans  would you have a moment?
I can think of a few ways, perhaps there are more and please feel free to consult with @tangrammer, @valllllll2000 and @iperdomo or Martin from the RSR team who is a great frontend guy: 
1. Remove the section header `Add devices to assignment` to save space as the task is clear from the action button. 
2. We remove the page scrolling making the [number of devices] selected + Add to assignment button always visible
3. We combine the section header with the actions. So where we have `Add devices to assignment` we would show under the number of selected and have the action button next to the 'x' <-- not really a fan of this one as we usually have the "completion actions" below the task area but just throwing it out there for the sake of brainstorming.

**Comment by iperdomo** [comment]
I requested confirmation to @Kiarii on the exact same issue, when I was testing the new functionality.
 To me, clicking a checkbox was _explicit_ enough to say "I want this device (or this group)" as part of the assignment. The extra button is unnecessary IMHO.

From our internal chat:
> I remember that I shared this some time ago - https://learnui.design/blog/4-rules-intuitive-ux.html 🔗
> The current way of adding/removing devices from an Assignment doesn't follow the rule **"Put interface elements where they affect change"** I need to scroll down and look for the button to add to the assignment [...]

**Comment by janagombitova** [comment]
@iperdomo When testing the initial designs with users we showed them a few options. One had just the checkboxes that not only selected the device but also added it to the assignments (as you suggest). The second had it as we have it today with an extra button. The second mock-up was better received and users completed the task without any hesitation or questioning if the devices are part of the assignment or not. 

Furthermore, a checkbox in design work means to select. Nothing more. So you select something to do an action, thus the need of an action button in our case. Funny enough @muloem questioned the same design decision a while back and I agree with Kiarii on this one. If we use checkboxes, we then also need an action button with them. 

But I agree with you that the action button is hidden. So we either localise it better (as per the blog you share) or we change the checkboxes to radio buttons (as with forms) and then we only need to move the device counter somewhere in the screen (I would suggest under the section title Assign devices)

**Comment by iperdomo** [comment]
Just for completion, the add to assignment button was (at some point) fixed in the bottom of the UI, so you had the scroll, but the add to assignment button was not moving, always visible.

**Comment by janagombitova** [comment]
@iperdomo can you point me to the decision on why we changed it? Just for my own awareness.

Then I feel we have these options:
* Move the bottom bar with the counter and action button to the top, instead of the section header.
* Use the "slider" buttons (as with forms, keep on forgetting the name of it) instead of checkboxes, remove the action button and bring the counter under the section header.

**Comment by iperdomo** [comment]
> can you point me to the decision on why we changed it? Just for my own awareness.If I'm correct the decision was not changed,

I don't think it was a change, just introduced as regression? :thinking:

**Comment by janagombitova** [comment]
Ohh ok. Let’s see if Marvin our Mulo can bring some clarity.

I have been thinking about this issue and realized that when searing the data point we might want to support Salim to search > select all data points that match > assign. In this case working with check boxes + action button is needed. Thus leaving us with either fixing it in the bottom of the section or moving it to the top.

**Comment by marvinkome** [comment]
![image](https://user-images.githubusercontent.com/30107382/79108331-07dcb200-7d6e-11ea-9120-97eb08b4bbf5.png)

On uat1, the bottom action button is always fixed

**Comment by iperdomo** [comment]
I tested UAT1 with Chrome 80 / Win10 (via Browserstack) and the button is fixed

![Peek 2020-04-13 18-12](https://user-images.githubusercontent.com/178474/79137256-a8ed5c00-7db2-11ea-8760-aa95262d11a0.gif)

**Comment by janagombitova** [comment]
<img width="1280" alt="Screen Shot 2020-04-14 at 15 18 24" src="https://user-images.githubusercontent.com/12456965/79229402-43a57380-7e63-11ea-890d-cdfb2a008b43.png">
 You guys are right, it is fixed. But it is not fully visible. This is how I see it on my screen, so I need to scroll the page to see the entire button. Is there a way we make it fit the page regardless of the screen size?

**Comment by iperdomo** [comment]
It's supposed that 1366x768 (HD) followed by 1920x1080 (FHD) are the most available screen resolution. Not sure what resolution is your display.
![StatCounter-resolution-ww-monthly-201903-202003.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/c06dea75-e6c9-4fde-8e82-edd539f17e9a)

I tested 1366x768 (lower) then mine (via BrowserStack) and I'm still able to see the button. There are 3 scrollbars but that is a different story :unamused: 

![2020-04-14_1800x882.png](https://images.zenhubusercontent.com/5dc544da50a3e20001c08671/93cad3d0-e742-4167-9eb1-7186832c95e2)

I do think is possible to adapt the available space with a `min-height` instead of fixed `height` to fit the available space. @marvinkome thoughts?

**Comment by iperdomo** [comment]
I did some quick testing and one of the problems is the fixed height of **470px**,  introduced in commit https://github.com/akvo/akvo-flow/commit/563132a3cb30081030228924a38fac6dd6efd787

**Comment by marvinkome** [comment]
Yeah, would change it to use view-height rather than pixels, that way it adapts to the screen size

**Comment by iperdomo** [comment]
Tested on 1024x768 via Browserstack
![2020-04-20_1303x962](https://user-images.githubusercontent.com/178474/79752884-40076600-8315-11ea-81c0-6a0985aa47e7.png)
