### ISSUE TITLE
Small changes to unassigning all datapoitns

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3499]
![Screen Shot 2020-04-09 at 09.15.11.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/68472544-d52e-47e6-9df8-c8929ee6b200)

Currently when all datapoints are assigned Salim can change that, thus assign specific points, by 1st unassigning all and then assigning by name or ID. However, our UI is unclear and bulky in that workflow. 

Original mockups: 
![Screen Shot 2020-04-09 at 09.16.22.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/a95a5784-4be3-4c90-8e55-3e43e11d8cc0)

Please make the following changes as in the mockups: 
* [ ] change the `cancel assignment` to `Unassign` --> cancel assignment indicates you are cancling the entire assignment (with the forms and devices and all) and that is not the case 
* [ ] make the action `Assign datapoint` (the one with the dropdown to assign all or by name and ID) unclickable. It should only be clickable once you unassign all datapoints

**Comment by janagombitova** [comment]
Checking UAT2 - it already works much better now, thanks @marvinkome. Once small change that I did not mention, but related to the changes you made --> The Unassign button, can you make it the same style as the clickable 'edit' and 'add' so blue and without the button border? Thanks. 

<img width="1268" alt="Screen Shot 2020-04-09 at 15 05 58" src="https://user-images.githubusercontent.com/12456965/78898252-cbf6d380-7a73-11ea-8733-8a4f89e7f50f.png">

**Comment by iperdomo** [comment]
@janagombitova the word "Unassign" doesn't exist as a verb. I changed the wording to _Cancel assignment_ after checking with some colleagues.

https://english.stackexchange.com/questions/156986/if-i-assign-someone-a-task-what-is-the-correct-verb-for-unassigning-them

**Comment by iperdomo** [comment]
> To *remove an assignment* from the students' view, [...]

https://khanacademy.zendesk.com/hc/en-us/community/posts/360055870691-How-can-I-unassign-assignments-

**Comment by janagombitova** [comment]
Cancel assignment envokes cancelling the entire thing which is not what this action does. 

I checked with Georgia (our Comms lady and native English speaker). She says: 
> Georgia, 09:29
> Unassigned is a word - it's just not usually used in active verb form, but I think if it makes it more clear to users then I'd go for clarity above technical correctness. But looking at the workflow I would go with something very simple like 'change assignment' or 'undo assignment'

To keep the UI clean and actions short (not repeat the noun assignment too much, we will go with **Undo**

Please make the change and also the following ones: 
* [ ] change Unassign to Undo
* [ ] change design of Undo from a framed button to an active link with no frame (line Add in the side panel)
* [ ] remove the sentence: 'Cancel assignments of all datapoints...' as it should be clear from 'All data points assigned' + 'Undo' what is going on

**Comment by janagombitova** [comment]
@marvinkome created #3515 to address the points in the comment above. So these issue changes work well on uat2, well done.
