### ISSUE TITLE
Remove redundant code from assignments

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3508]
# Context
Why do we add this issue?
To keep our code clean and understandable

# Problem or idea
What is the cause?
Lots of unused code are in the assignments page

# Solution or next step
How could we solve it?
Remove and add comments for more understanding of the code.

**Comment by janagombitova** [comment]
@marvinkome can you test this, if testable? Close it if done or comment if more work is needed? Thanks
