### ISSUE TITLE
Changes in Unassigning datapoints

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3515]
# Context
Why do we add this issue?
To keep the UI clean and actions short and understandable

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?
We will go with **Undo**

Please make the change and also the following ones: 
* [x] change Unassign to Undo
* [x] change design of Undo from a framed button to an active link with no frame (line Add in the side panel)
* [x] remove the sentence: 'Cancel assignments of all datapoints...' as it should be clear from 'All data points assigned' + 'Undo' what is going on

**Comment by janagombitova** [comment]
All done.
