### ISSUE TITLE
How will we make it clear that you can assign data points? 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3519]
# Context
We intend to make our products as user-friendly as possible a thus as self-explanatory as possible. However, some tasks are not so straightforward and easy to design. Assignments became one of these cases after we introduced a third layer to them, assigning data points to devices. 

But we believe in learning as we go, so with this issue I would like us to again revise the design of assignments. 

# Problem or idea
**Problem:** After adding a device some users wouldn't know what do next

When we started with this opportunity #2796 we worked with a different set of designs that we tested out with users. We, however, pivoted from these as they took up too much static space and changed to the designs we have today with the side panel. These were not user-tested due to lack of time. Now that the implementation is in place we see that the workflow of adding data points to devices is still hidden, hard to find. Users do not know it is there. We will try to mitigate this with introducing a walkthrough (#3466) but it does not solve the problem. 

Secondly, we have a lot of inconsistency on how we do different actions in the assignments. Adding devices does not follow the same pattern as adding data points what creates a feeling of chaos and requires more effort from Salim to figure out what to do. 

Thirdly, for non-monitoring surveys, once the devices are added the user is exposed to an odd small list of devices in the side panel. If he closes the screen of the adding device, he sees the prompt to select a monitoring form, but he does not want to do that and should not be prompted to do that. 

# Idea 
I took a look at both mockups: 
* old: https://projects.invisionapp.com/share/TZP8HSGRB5N#/screens/332622281
* latest: https://projects.invisionapp.com/share/5YUUUPXF7DA#/screens/393438525

And I think we can make use of a combination of both. The idea is to replicate how we add data points to devices for the workflow of adding devices. I created a basic workflow to illustrate my point. This way we streamline how things are done while not taking extra space. It takes the way we added devices in the old mockups and brings it into the new designs with the side panel. 

[Assignments - idea.pdf](https://github.com/akvo/akvo-flow/files/4479575/Assignments.-.idea.pdf)

# Next step
* [x] discuss with team
* [x] decide on next steps

**Comment by janagombitova** [comment]
In today's meeting we discussed this idea. We agreed that the workflow that is implemented today is not straightforward enough. But we also agreed to not make any further changes until we learn more from users. 

So we will finish the pending small improvements to this iteration and track usage to see the uptake of the functionality. Secondly, @Kiarii please lead getting user feedback from users on the new assignments, assigning data points on how clear the workflow is. Once we know more, we will make next improvements.

**Comment by Kiarii** [comment]
Notes to consider when we get to this:
![image](https://user-images.githubusercontent.com/12692444/95749179-dce30480-0ca3-11eb-87d8-fcaa5817089e.png)
