### ISSUE TITLE
OpenStack/Swift migration

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow#352]
Migrate from Amazon S3 to OpenStack for object store services.

**GAE - ObjectStore communications:**
- Download zip files/images
- Upload surveys - xml/zip (*)
- Download xml surveys to generate Bootstrap zip
- Upload Bootstrap zip file (*)

_* - Authenticated API calls_

Non authenticated API calls only require to have their respective endpoint updated.

**Comment by muloem** [comment]
This will go on hold for the time being.
