### ISSUE TITLE
Filling a partial Assignment and moving away leads to "Missing required parameters"

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#3520]
# Context

There is no UI to _cancel_ the current editing assignment. If the user moves away to a different tab. We detect that the Assignment has been changed and we attempt to _autosave_ it, leading to a _"Missing required parameters"_ message.

![Peek 2020-04-15 07-44](https://user-images.githubusercontent.com/178474/79302802-a2173400-7eed-11ea-8491-78a6616579c2.gif)

# Problem or idea
Attempt to autosave the edits in an Assigment.

# Solution or next step
* We have an explict *Save* button. Should we try to autosave the Assignment?

**Comment by janagombitova** [comment]
Ideally, we should autosave everything in Flow, for each change not just for creating new things (like for editing questions, or cascades) but we do not. If we had autosave, we could remove the `save` button and do what Lumen does and just show when things are being saved. 

How much effort would autosave require? 

To keep things consistent with other Flow 'not-so-user-friendly-workflows' when leaving the page, it should mean the changes do not get saved. This is not ideal but it is how other parts of Flow work.

**Comment by iperdomo** [comment]
> How much effort would autosave require?

As you pointed out, we need to make it consistent across the Dashboard, so a "project" itself. Meaning, no trivial.
_Autosave_ has come before I mentioned to @muloem that if we want/need autosave, IMHO we also need/want "Undo", meaning a way to rollback what the user did and we saved.

> To keep things consistent with other Flow 'not-so-user-friendly-workflows' when leaving the page, it should mean the changes do not get saved. This is not ideal but it is how other parts of Flow work.

It seems this is an old behaviour - https://github.com/akvo/akvo-flow/issues/1223

**Comment by iperdomo** [comment]
Duplicate of #1223
