### ISSUE TITLE
Assignments 2nd iteration (a collected of ideas, feedback, research questions)

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3522]
# Context 
This issue is  **another slice** of the work we started around **Assigning data points to devices for scalable monitoring** #2796  

The original mock-ups (with a more extensive implementation) can be found here: https://projects.invisionapp.com/share/NHQGVLB2EKX#/346093699_0-0_Assignments_ES and the revised latest ones here: The final mockups are here: https://projects.invisionapp.com/share/5YUUUPXF7DA#/screens

## Current status quo
In the current implementation (once Step 1 is done) Petra will be able to create an assignment, select the forms and devices and decide which device can download which data point(s) and submit more monitoring form data to it. By default, all data points are automatically assigned to the devices (to support the workflow users are used to). Petra can then decide to remove all data points and assigned a selected few. 

This implementation already resolved the major scalability issues we had around monitoring as: 
* The need to create copies of a survey and forms to split the data set to manageable chunks that are then downloaded the specific devices 
* Too many data points have to be downloaded to a device causing issues with available space and taking too long to download 

# Opportunity 
## Why do we have this issue? What are we trying to solve? 
The implementation revealed a few questions we did not think of, especially for existing assignments and users in the field. This epic aims to hold these questions and see how we can address them (and if we should address them). 

## Questions: 
* How can we make it more clear that you can assign data points to devices (#3519 )?
* Does assign all data points by default work? Should we enforce Petra to choose which points to assign rather than having it as an option? 
* What about data points that I created after the assignment. So I am assigned 10 data points and I create 3 fresh ones. Will these be automatically assigned to me (and visible in the assignment)? How will Petra know I created them to assign them to someone else? 
* What does unassign do? Petra assigned data points to me, I downloaded them to my Flow app and then she decided to unassign a few. What happens for me in the app? Today they remain on the app, but should they be removed? 
* Does Petra ever assign the same data points to a group of devices? Should we support that rather than assigning data points to individual devices? 
* What happens when a data point is deleted? How does that affect the assignment and what happens with the data point on the mobile app? 
* How can one easily see how many data points are assigned to each device? 

## The idea 
Nothing specific. 2nd iteration of the current assignments. 

## How will this benefit our users? 
Simpler workflows, clear instructions, happier users. 

## How will this benefit Akvo? 
We are currently improving a functionality no other product has in the market. Not only are we a few steps ahead in comparison to others but we are also strengthening our position as a monitoring data collection tool working on a larger scale. However, to provide a strong feature we need to have all the details worked out. 

# Next steps 
We will continue gathering these questions the next weeks based on user feedback and then see which we will address and when. The design team will take the lead in doing post-release user feedback.

**Comment by janagombitova** [comment]
This comment is just a collection of feedback received so far. It does **not** mean we should address all the points and suggestion. But I am noting them all down to keep track of the input we get and why we eventually handle some problems and not other. 

# Feedback 1 - Cannot get all points to my phone quickly 
Many partners still want to have all points on one's phones (without explaining why), so we need to be cautious with this request. But here is an idea Charles mentioned in the past, that can solve the issue of downloading too many points in low connectivity areas and support the case of wanting to have all data points quickly on the device: #3558 

# Feedback 2 - Search is unhandy 
You need to search by the exact data point name. Why not allow to search by a part of the name regardless of the order? 


# Feedback 3 - Seach based on meta data/data 

Feedback from a partner: https://akvoo.reamaze.com/admin/conversations/akvoflow-you-got-a-feedback-on-an-article-from-edmond-dot-muller-at-ecosia-dot-org-2b12e90d71ad0920
> We are collecting thousands of points (I assume other organisations too).... Secondly, we use the same inventory form for many device groups. So assigning all points would mean that a device group also sees the points that are collected by other groups. This is not what we want (privacy).... I would suggest the following improvements:
> 1) Search points on device group level (select device group and show all collected points): By doing so, ONLY the points that are collected by a certain group are shown in the selection list  (even if the group uses the same inventory as other groups).
> 2) Search on specific form columns: select a column of your field form and use a filter option to have an overview of the point list for that filter setting.
> 3) Search entire database and use free text for example country name: E.g. "Nigaragua" shows all points that have nicaragua somewhere in the database

# Feedback 3 - Assign data points on a device group level 
This comes from the team and indirectly from partners. Devices are organised into groups. So why not assign data points to the entire group and then all devices in that group get the assigned data points. This was I do not have to assign each device the same data points.

**Comment by Kiarii** [comment]
UI/UX Notes to consider when we get to this:
- Separate Assignments from devices
- Make the concept of Assignments more concrete (Planned/upcoming, on-going, Complete)
- Support Assignment duplication (assuming some monitoring will more or less vary only by dates)
- Manual sending should send an assignment, not survey
- Provide more assignment details and make them actionable (e.g. as a start/finish caption provides awareness of when an assignment goes in or out of action and thus if more planning or data collection time is necessary)

Assignment list
![image](https://user-images.githubusercontent.com/12692444/95749350-19aefb80-0ca4-11eb-8aad-f717c101e396.png)

Assignment particulars
![image](https://user-images.githubusercontent.com/12692444/95749648-9346e980-0ca4-11eb-9795-734e2931509a.png)
