### ISSUE TITLE
Assigning by datapoint name returns limited results

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3524]
# Context
When creating survey assignments, we are also able to assign individual datapoints to devices for monitoring. In order to assign individual datapoints, we need to search for them by the datapoint name prefix. e.g all datapoints that begin with "District1 - ". This should find datapoints whose datapoint name starts with "District1 -"

# Problem or idea
For cases where there are many datapoints with the prefix, the search results box only shows the first 20 datapoints. Which means if there are for example more than 20 datapoints with the same prefix, the user needs to use a search prefix term which matches 20 datapoints or less if they want to use the _assign by datapoint name_ functionality. 

In addition to the limited number of datapoints returned, we also do not have a way to select all the datapoints that are returned in the results list. So if I get 20 datapoints, I have to select them one-by-one. If I need to do this for 100 datapoints it becomes quite cumbersome.

![assign-loads-datapoints](https://user-images.githubusercontent.com/533336/79366808-1a611200-7f4d-11ea-9159-fce83e8cdda5.gif)

# Solution or next step
We should provide a way to either incorporate pagination, or to return and show the entire list of datapoints that match a prefix.  Perhaps putting a limit to say the first 300 datapoints that match a prefix.

@janagombitova what do you think?

**Comment by janagombitova** [comment]
I agree. It needs to be clear to the user how many data points match the result. To me, it sounds like two tasks. So I suggest splitting the issue. Keep pagination here and talk about `select all` in a new issue. 

# Pagination - ideas

If I remember well we spoke about this in the early talks and said pagination would work the best to limit the load in case of thousands of points matching the search criteria. If possible I would go for 50 per page or 100, as 20 seems too little if there are hundreds of points. 

We could use the standard `1-50 from 1000` indicating the number of visible points.

**Comment by janagombitova** [comment]
On uat2 the list now gives an endless scroll what is much better than pagination, well done. @iperdomo you mentioned this morning that you added a count for `found` data points, but I do not see that on uat2. Was that not merged yet?

**Comment by iperdomo** [comment]
@janagombitova yes, the count is not yet merged. I'll include it together with _Select all_
