### ISSUE TITLE
Datapoint endpoint serves more data than expected

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#3528]
# Context
In an _Assignment_ a user can specify the list of _Forms_ to be used for a set of _Devices_. With the most recent changes a user can also specify the list of _Datapoints_ per _Device_.

When serving the data of those _Datapoints_ (via `/datapoints`) we don't filter the _Form instances_ for the selected _Forms_, so we're sending _more_ data than required.

The mobile App only needs the _Datapoint_ meta-data (`identifier`, `location`, `name`) that is *always* available in the response.

# Problem or idea
* What is the expected behaviour from the user point of view? If the user selected one form X, we're also serving data (_Form instances_) for form Y and Z.
  * NOTE: The user in the mobile App is not able to "see" the data for forms Y and Z because she/he doesn't have the form definition.

# Solution or next step
* Should we filter the _Form instances_ to those produced by _Forms_ part of the _Assignment_ ?

**Comment by janagombitova** [comment]
I think we should not send to the app any data that the user does not use/ does not have visible to use. So if a monitoring form is not assigned to a user, we should not be sending submissions from that form to the user on the app. On the other hand, in #3645 we raised the question is monitoring form submissions are being used at all in the app and it seems that they are not. So before we make any further changes, we should decide if it is useful to send old submissions, if yes then how many.
