### ISSUE TITLE
Make device groups on assignment sidebar closed by default

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3538]
# Context
**Why do we add this issue?**
Small improvement related to our current Datapoint assignment MVP (#2796) with the goal to make the UI as simple and clean as possible.

# Problem or idea
**What is the cause?**
Because all device groups in the sidebar are opened, they're visual noise in the sidebar and adds extra effort in looking for a device

# Solution or next step
**How could we solve it?**
Make device groups closed by default

**Comment by janagombitova** [comment]
Perfect 👍
