### ISSUE TITLE
Fix build scripts for instance deploy

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3541]
# Context
Flow deployments have multiple steps and imply using several scripts located in different places :scream:  :sob: 

# Problem or idea
The step about creating configuration for the instance is broken because the versioning format has changed.
Old jars are kept in the folder, which one will be used to create the config?

# Solution or next step
Add a clean step to ant
All these config files will be merged into one https://github.com/akvo/akvo-flow-server-config/issues/554 but in the mean time we need this fix to keep creating instances.

**Comment by janagombitova** [comment]
@valllllll2000 is this issue done? Can we close it?

**Comment by valllllll2000** [comment]
@janagombitova all done, closing it!
