### ISSUE TITLE
Changing the defined form in an existing Assignment leads to data inconsistency

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#3547]
# Context
An existing _Assignment_ can be edited. If the user changes the assigned Survey it could lead to data inconsistency, e.g. If the user has _handpicked_ some datapoints from the **previous** Survey.

![Peek 2020-04-28 15-40](https://user-images.githubusercontent.com/178474/80495143-d49e4380-8967-11ea-8add-eb4b6251d03d.gif)

# Problem or idea

* We don't _reset_ the selected datapoints when changing the Survey

# Solution or next step
* Reset the value to _All datapoints_ if the user switches the Survey to a different value

**Comment by janagombitova** [comment]
Agree with the solution suggestion. Can we also inform the user? Once she changes the folder - survey selection to show and info that the change will also result in a change in assigned datapoints?
