### ISSUE TITLE
Broken validation of the GEOLON and GEOLAT headers when importing reports

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#3554]
# Context
When exporting data cleaning reports, GEO questions are split into three columns corresponding to the latitude, longitude and elevation.  The headers for these columns are generated as show in the code snippet below.
https://github.com/akvo/akvo-flow/blob/37a7787b23fd3de0d2c3a88808ef475455933f80/GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java#L1605-L1609

# Problem or idea
The corresponding import for data cleaning does not match with the above generated format, so a report with a valid GEO header fails in the import with the error _Cannot import data from Column X - "--GEOLON--|Longitude". Please check and/or fix the header cell_
https://github.com/akvo/akvo-flow/blob/37a7787b23fd3de0d2c3a88808ef475455933f80/GAE/src/org/waterforpeople/mapping/dataexport/RawDataSpreadsheetImporter.java#L87

# Solution or next step
Given that reports are constantly being generated, either we need to ensure that both the newly specified format and the old format are supported, or revert the import format to match the existing header GEO column header format.

**Comment by muloem** [comment]
The issue is verified to exist on test environments

**Comment by iperdomo** [comment]
Tested import in UAT2 and Flow services in _test_ cluster

**Comment by iperdomo** [comment]
The fix has been promoted to production service:

https://travis-ci.org/github/akvo/akvo-flow-services/builds/681971560

**Comment by iperdomo** [comment]
The fix was also tested in `beta1` instance (using production Flow services)
