### ISSUE TITLE
Tracking user interactions in flow

### ISSUE THREAD

**Issue by marvinkome** [akvo/akvo-flow#3556]
# Context
Why do we add this issue?
After the initial tracking assignments usage issue in Flow, we have decided to track more user interactions

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?
In this next iteration, we would be tracking

- Data export types (once a user hits ‘generate’) so we know with data exports they use
- Data views - so we have the Inspect data tab and Monitoring tab and it would be good to know if people actually use them (for future connecting with Lumen). Can we track once users hit find for these separate tabs
- Stats to see the uptake of the functionality

**Comment by janagombitova** [comment]
Works like a charm, we are getting data in 👍
