### ISSUE TITLE
Manual data point transfer 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3558]
# Context

## Why do we have this issue? What are we trying to solve? 
With #2796 we aimed to solve the issue, where an enumerator had to download too many data points to his device to monitor. The idea is that Al only gets those data points assigned that he needs to update. But there are still cases, where Al wants/needs to have all data points on his device - she is randomly checking the project and needs to be able to data point where she is. 

Furthermore, downloading data points (assigned specific ones or all) still means he needs to download data points to his device. He needs to have a relatively stable internet connection to do so. **What about cases where the network connection is low, unstable or not existing?** In such situations, the current set up still does not enable him to get the data points and cannot monitor. 

## How will this benefit the users?
* users working in remote areas will be able to use monitoring as a functionality 
* users needing to download all or many data points will have an alternative to the current online download mode 

## How will this benefit Akvo? 
* we strengthen our position as a tool that allows data collection in remote areas 
* we strengthen monitoring as a functionality - which is still one of our USPs (unique selling point)

# Opportunity 

## The idea 
The idea is to follow the feature we have: `manual survey transfer` and do the same for data points. 

With manual survey transfer Salim picks the published survey forms (one or many) and then adds the email he wants the file to be sent to. Once received, he adds the file to the Flow apps file system, by connecting his device to his computer. 
<img width="973" alt="Screen Shot 2020-06-23 at 12 20 56" src="https://user-images.githubusercontent.com/12456965/85392594-0688ec00-b54c-11ea-85bc-f890922fcd2c.png">

## To consider: 
* only allow this for downloading ALL data points 
* if we allow getting data points this way, we assume Al has the survey form on his device. Should we bundle in the survey form with the data points too, to be sure he gets it? 
* keeping the current UI, or improving it? 
* removing the need to add an email, use the email of the logged-in user?

# Next steps

**Comment by valllllll2000** [comment]
this would be a great addition to our offline support for the tools but we have to consider that datapoints are data and it can be personal data. We should maybe provide a mechanism 1) if data is marked as personal have a warning to the user or not allow personal data to be transferred? 2) On the app make sure to delete the data once it is loaded into the device.
