### ISSUE TITLE
Cannot add groups and questions to form due to Save 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3575]
# Problem or idea
*What is the cause?*

On **uat2** when creating a new form I cannot proceed with adding questions as we seem to have an odd validation around the form being saved. 

![New form](https://user-images.githubusercontent.com/12456965/82789739-1d63f200-9e6b-11ea-81a3-d2d1f05af0f0.gif)

On **uat1** all works well so it seems we introduced somethin with the work on webforms (#3145)

**Comment by tangrammer** [comment]
tested the fix on uat2, working now 
... closing the issue
