### ISSUE TITLE
Webforms onboarder

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-flow#3578]
### Context
We want to communicate to the users the support for webforms in situ, in some iteration of Webforms

We can use an onboard component to do this - communicate what Webforms are and the entailing caveats.. 

One place to do this would be when Salim/Petra, et al. open Flow; the assumption being that it is best for them to know about the existence of the feature upon landing in Flow (which might alter the course of their actions.. hopefully in a good way) than waiting for them to go to surveys - which depending on what they are doing might delayed..

**Comment by janagombitova** [comment]
Great initiative @Kiarii. 
* check how RSR does it (might be easy to copy) 
* Proposal for the text: 
   * Introducing Webforms
   * Submit data from your computer or any mobile device using your browser app.
   * Besides collecting data with your Akvo Flow app, you can now share your forms and submit data via webforms. To use webforms your form needs to be published, cannot be a monitoring form or hold the following question types: signature, geographic shape and Akvo Caddisfly.

**Comment by Kiarii** [comment]
@janagombitova does this mean we are already supporting repeat question groups?

**Comment by janagombitova** [comment]
@Kiarii Nope, not yet. Great catch. 

But Joy and Deden are working on it and expect to have it done next week.  So depending on how quickly we can add the onboarder we need to add the line on RQGs.

**Comment by janagombitova** [comment]
We need to look at the overall picture on how to introduce new features and onboard new users. Because adding an on-border just for this particular change might require more work than the value it can bring at this time, I decided to close the issue
