### ISSUE TITLE
Generate strong password per webform

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3581]
# Context
To build up on the work done #3145 

## Current status quo
Besides collecting data with your Akvo Flow app, you can now share your forms and submit data via webforms, using the browser. To be able to do so, one needs to have the URL and the webform password.

<img width="1257" alt="Screen Shot 2020-05-25 at 14 21 45" src="https://user-images.githubusercontent.com/12456965/82812491-66c83780-9e93-11ea-9ba5-31c38b0b3b0f.png">

Today we have the approach of **one password rules them all**. The webform password is the same for all forms across all instances. 

# Opportunity 
## Why do we have this issue? What are we trying to solve? 
* To enhance the secure handling of data
* We had the approach of **one password rules them all** in the Flow app with the `12345` password to download forms and we removed it as it was silly and unnecessary as you needed to know the form ID to be able to download it what is already an effort to get. So we removed it. And we should not implement workflows that we've already learned to be of no use.

## The idea 
The idea is that with the random URL, we should also create a random strong password for each webform. 

## How will this benefit the users?
* it does not change the need to share the URL and the password to the enumerator, so it does not create extra work 
* it removed the confusion, on why something as a password is 1) so simple and 2) same for every webform

## How will this benefit Akvo? 
* our webforms feature has a strong security component what is a plus in the GDPR world 
* we claim to think security first with all we do, this change supports this mindset

# Next steps

**Comment by tangrammer** [comment]
https://github.com/akvo/akvo-flow/pull/3582

**Comment by janagombitova** [comment]
Status update for a conversation today between @tangrammer, @joycarpediem and myself: 
* the current work/approach of the webform password on Flow side is to generate a UUID human-readable-password composed of 3 groups of 4 easy-to-read characters
* this UUID is a deterministic encrypted representation of survey-creation-date and survey-version and webformId (the random url token of webformUrl)
* to validate the password, tech-consultancy-backend needs to call flow backend public entrypoint /webform/auth passing WebFormId and password (Pay attention that WebFormId is the random/encrypted representation of surveyId)
* so far the WebFormId is not available to tech-consultancy-backend 
* we can modify nginx config to append the WebFormId as part of the final webformUrl … so tech-consultancy instead of this url: https://tech-consultancy.akvotest.org/akvo-flow-web/uat1/563739126 will be https://tech-consultancy.akvotest.org/akvo-flow-web/uat1/563739126#ZEJAXXh6BAIO being ZEJAXXh6BAIO the webFormId

<img width="764" alt="download" src="https://user-images.githubusercontent.com/12456965/83741144-1d78a480-a658-11ea-8025-8b6f931c0700.png">

Next steps is the plan the remaining work.

**Comment by tangrammer** [comment]
@muloem @iperdomo don't you think it should be better to use another seed (encryption key) for encrypting the webFormId and password so if long term this functionality is moved to tech-consultancy-backend we don't need to use same flow encryption key in both sides?

**Comment by janagombitova** [comment]
As @joycarpediem well pointed out, before we put up a stronger barrier to protect the webforms, we should reconsider how the passwords are used: 
* generally speaking the value of webforms is in entering data without much setup. You get a URL and then you are off to fill data. 
* In some case, webform is embedded into a portal. With this auto-generated single password, it creates a  barrier. But as we now have the barrier set up for all webforms the purpose of it is a bit obscured. 
* We should consider allowing Salim to determine if he needs to protect the webform (as we do with Dashboards in Lumen). We can still autogenerate the password for Salim (using the current implementation)

This means that there is more work to be done on this issue: 
* finish up the changes mentioned above
* allow Salim to decide if he wants a password 
* possibly move the password to the beginning of the webform, as we have in Lumen
* *there might be more*
