### ISSUE TITLE
Delete monitoring submissions with registration submission

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3597]
In Flow data deletion is relatively limited. You can delete one submission at a time, so you cannot delete all data to a survey form in one go. You have to go through all the individual submissions. In some cases partners contacted us with a list of surveys they wanted the data to be deleted. 

Sometimes partners want to remove old data from their instance or have done a test round of the survey form, want to delete all the submission so they can start the actual data collection. 

We never invested more in deletion because of the risk **what if someone deletes an entire dataset by mistake**. Some products handle such cases - where you cannot bring the thing you delete back again by asking the user for a double confirmation where you need to type something in. Plus stating this cannot be undone. 

Then we have the case of monitoring. What is someone tries to **delete registration form data but there are monitoring forms with data too**. Do we not allow to delete the registration form data until the monitoring forms' data are deleted? or do we ask if the user wants to delete everything in one go? This is a problem also when the user deletes just one registration form submission. In that case the monitoring form submission is still stored, thus the data point exists but without having the registration form data to define it. Perhaps we should follow the pattern we have in Lumen, that when deleting a dataset we show linked visuals and dashboards and delete them all.

**Comment by Kiarii** [comment]
I do not see and assume there cant be any use cases for 'orphan' data, given a reg form provides a datapoint's 'parent' data and 'mon' form child data. 

Deleting parent data therefore should by this assumption include or bundle up the deletion of respective child data. The deletion of such data should be clearly communicated in the UI.

We can still maintain that no bulk deletion is done - so users can only delete datapoints (data) one at a time. Ideally if we provided bulk deletion, we might want to consider providing a 2 or 4 week grace period in which the deleted data sits in a deleted folder, and can be recovered, and auto-deletes completely after the period has elapsed.. 🤺

**Comment by janagombitova** [comment]
@Kiarii indeed 'orphan' submissions - so monitoring submissions without a data point - are useless conceptually but also practically. They cause issues in analysis and in Lumen.

Ideally if a registration form submission is about to be deleted we also remove the linked monitoring form submissions and somehow show the user before doing so.

**Comment by janagombitova** [comment]
Im going to rename this issue to handle the monitoring deletion and create a new one to handle bulk deletion so we keep things separate

**Comment by Kiarii** [comment]
In this of a single delete we could use a modal dialog to notify the user (and ask them to confirm) that all monitoring data corresponding to a datapoint being deleted will also be deleted..

**Comment by janagombitova** [comment]
Today we discussed this issue and agreed on the following tasks:
* [ ] Change deletion in Flow  
   * When deleting a registration form submission check for monitoring forms linked to the data point and delete them all in one go as it makes no sense to have monitoring forms without the registration form data that defines the data point (in the way we have monitoring set up)
   * User workflow: 
      * After Salim clicks to delete a registration form submission show dialogue to inform him that all monitoring form submissions made for this data point will also be deleted. Plus we will show a number of submissions that will be deleted  
      * Salim will confirm to proceed
      * We will not make any changes to how monitoring form submissions are deleted
* [ ]  We will make an overview of all existing instances and data to see how many monitoring form submissions we have missing registration form data per instance so Jana can inform the partners about the following clean up
* [ ] We will delete all the orphan monitoring form submissions

**Comment by valllllll2000** [comment]
> We will make an overview of all existing instances and data to see how many monitoring form submissions we have missing registration form data per instance so Jana can inform the partners about the following clean up

@janagombitova what kind of information is needed for that? Is it enough to say "100 orphan submission will be deleted" or do we need more details: 
Survey | Form | Datapoint | Number of orphan submissions
-- | -- | -- | --
Survey Name| Form 1 | data point xy | 5

do we need to provide an spreadsheet maybe?

**Comment by janagombitova** [comment]
@valllllll2000 if possible that table per instance would be as informative as it can get and helpful too. So my thinking is to send the info to the contact people we have and for cases where there are a few orphan submissions just inform them that they are gone, but for cases where there are more ask if they want us to proceed.

**Comment by janagombitova** [comment]
Tested the initial implementation on UAT2 and I confirm that once I delete the registration form submission the monitoring forms collected to the data point are also deleted and the data point too. So this piece works well! Good job. 

Now the UI improvements so Salim and Petra know that if they delete that registration form submission, they are deleting more than meets the eye.

**Comment by janagombitova** [comment]
This issue is completed and released. When a registration form submissions that has monitoring forms submissions linked to it is being deleted we show a different message that shows the count of submissions that will be deleted at once. 

Done done
