### ISSUE TITLE
Ban the user from creating OptionQuestions without options

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow#362]
**Current Behaviour:**
The current application is crashing because an option question is _always_ expecting some options, but the survey definition does not include options for some of them, in both ICCO, and Mars instances.

We should, regardless of the server side fix for this issue, ensure that the app doesn't crash if wrong info is sent through a survey.

**Expected Behaviour:**
The user should always include options for this kind of questions

Original report: https://github.com/akvo/akvo-flow-mobile/issues/31

**Comment by muloem** [comment]
Closing this one and following up in #1324
