### ISSUE TITLE
Inform the user that he/she is offline 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3624]
# Context
Our tools are used in areas where stable internet connection is still not standard. But we do not want that to be a limitation and want to ensure users regardless of their location can use the products and trust them. 

## Why do we have this issue? What are we trying to solve? 
Today our products do not communicate to the user that they are offline, resulting in: 
* user losing their work 
* user thinking the products are slow (what is not true but he/she has no way to know)

# Opportunity 

## Current status quo

Flow lets you continue with the work until you hit save and Flow says something is being saved, but that is not happening and as a user you think that Flow is slow, where the problem is that you are offline. In Lumen when you create a new item at the moment you go offline the loading icon spins in screen indicating something is happening, what is as confusing as in Flow. Or Lumen informs you that it cannot save, please retry, but you cannot as you are offline. 

## The idea 
With this issue we want to start small: **How might we inform Salim that he is offline?** 

We will not change how the functionality works, disable editing, do autosaving, etc. That is for later. With this issue we just want to make sure he/she knows he is offline. 

As both Flow and Lumen do not inform users, it might be good to think of a way to solve this problem for both products. What do you think @marvinkome and @tangrammer? 

Here are some screenshots on how other products do it for inspiration

### Gmail:
<img width="1142" alt="Screen Shot 2020-08-05 at 12 49 44" src="https://user-images.githubusercontent.com/12456965/89405662-3a932780-d71c-11ea-96af-0d6ca00d42a0.png">

### Google Drive:
<img width="1131" alt="Screen Shot 2020-08-05 at 12 50 01" src="https://user-images.githubusercontent.com/12456965/89405665-3b2bbe00-d71c-11ea-9456-977e2e1da82e.png">

### Google sheets:
<img width="1130" alt="Screen Shot 2020-08-05 at 12 50 07" src="https://user-images.githubusercontent.com/12456965/89405667-3bc45480-d71c-11ea-93a4-dc463fe4bc87.png">

### Zenhub:
<img width="1143" alt="Screen Shot 2020-08-05 at 12 50 12" src="https://user-images.githubusercontent.com/12456965/89405668-3bc45480-d71c-11ea-8465-32dd584b891c.png">

### Slack:
<img width="1140" alt="Screen Shot 2020-08-05 at 12 49 12" src="https://user-images.githubusercontent.com/12456965/89405651-36670a00-d71c-11ea-8e44-46b1305c6c67.png">

**Comment by janagombitova** [comment]
I just realized we need to also consider what happens after we inform Salim that he is offline? How frequently will we check if he is still offline? Can he dismiss the message? What happens if he does? What happens once he is again connected? Will he tell him?

**Comment by janagombitova** [comment]
I am moving this task to the Backlog as we all are now focusing on finishing RQG support in Lumen and this task can wait till that is done

**Comment by Kiarii** [comment]
we should aim to handle this in more or less a similar manner as we do in lumen to bring in some consistency

**Comment by janagombitova** [comment]
To start simple: 
* we just want to inform the user if she is offline - nothing more like limiting functionality 
* we just do this for the survey editor side of Flow

**Comment by janagombitova** [comment]
I tested it on uat1 and it works great!
