### ISSUE TITLE
Transition to "Manage Translation" view is slow

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#364]
The first time when you transition to the _Manage Translation_ we request the data for the first _Question Group_.  This leads to a very slow feeling.

Until you switch to the view you get the __Loading__ icon.

I propose to only request the Survey header info to have a quicker response.

See that the first request can take up to 31 secs in a large first question group

![translation](https://f.cloud.github.com/assets/178474/1149997/1e7ccad0-1ee4-11e3-9e14-4d10e550ff04.png)

**Comment by muloem** [comment]
Closing this one. Will be handled in #355
