### ISSUE TITLE
Export/Report does not show right away list

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3661]
When downloading a data cleaning export, for a form that has no data, I get this: 

![Screen Shot 2020-10-29 at 10 14 54](https://user-images.githubusercontent.com/12456965/97548611-a14c7800-19cf-11eb-9fc6-214a415b90ad.png)

The generation finishes, I get the email that it is done successfully but in the exports UI I miss the actual file to download. When generating a report with data, all works fine. I did not check on uat1 to confirm that this only happens for files without data.

**Comment by iperdomo** [comment]
Those *missing* reports are reports in error state, internally
```
{
    "1": {
        "keyId": 114612615,
        "reportType": "DATA_CLEANING",
        "formId": 124922315,
        "state": "FINISHED_ERROR",
        "filename": null,
        "message": "Error generating report",
        "startDate": null,
        "endDate": null,
        "lastCollectionOnly": false,
        "questionId": null,
        "createdDateTime": 1603962746924,
        "lastUpdateDateTime": 1603962747812
    }
}
```

**Comment by iperdomo** [comment]
OK, i think I found the cause of the problem.

* This *Data Cleaning* export is based on a new copy of a Survey
* The Survey's forms are **not** published
* We use the published form definition to generate the structure of the xslx file. Since we don't have the published version of the form in AWS S3, the export fails

This is how we got to this state, but the issue is still present. An error in report generation is still notified as *success* and the Exports tab doesn't show that the report generation failed.

**Comment by iperdomo** [comment]
On my previous message, this is what I found in the logs:
```
java.io.IOException: Server returned HTTP response code: 403 for URL: https://akvoflow-<id>.s3.amazonaws.com/surveys/124922315.zip 
```

**Comment by janagombitova** [comment]
interesting. So in that case we should in the UI state that the report generation failed because the form is not published.

**Comment by iperdomo** [comment]
> So in that case we should in the UI state that the report generation failed because the form is not published.

Or don't allow export for non-published forms, in the same way we don't allow to *assign* an non-published forms

**Comment by janagombitova** [comment]
That is also an option 👍 . But we do allow to export the `survey form` for non published forms so the user creating the survey can check easily the entire structure.

**Comment by valllllll2000** [comment]
I managed to reproduce this today: report succeds and I get the email that report is ready. Looking at the page I don't see the report (first entry)
![Screenshot from 2021-01-11 12-53-12](https://user-images.githubusercontent.com/923280/104179515-417d3f00-540c-11eb-97be-d16638462870.png)
but if I reload the page the report is back
![Screenshot from 2021-01-11 12-56-47](https://user-images.githubusercontent.com/923280/104179655-80ab9000-540c-11eb-8a82-0bf3b48676a8.png)
The form was publlished before generating the report

**Comment by janagombitova** [comment]
@valllllll2000 what happens after you reopen the page?

**Comment by valllllll2000** [comment]
@janagombitova reloding solves the issue

**Comment by janagombitova** [comment]
ok. so then the Problem is: why does the file not show right away
