### ISSUE TITLE
Survey copy may duplicate/triplicate questions and groups

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3669]
# Context
When making a survey copy, Jana has ended up with a Survey where some groups were triplicated (but not all questions)

# Problem or idea
We use tasks to copy questions and question groups. Tasks have to be completed in 10 minutes or they get interrupted. We have retry logic for tasks of 10 times or until successful completion. When a task is interrupted, work is resumed from the beginning.

# Solution or next step
* For long surveys we need to expect that a Task can be interrupted and make sure it completes in less than 10 minutes, we could use smaller tasks: ej one Task per group or per question?
* If a Task restarts we should check which groups/questions already exist and not to copy them.

We have decided to optimize the Translations copy. Problem: some old translations in the datastore do not have the surveyId setup so part 2 of the work requires to create a script to fix this using the parentId field.

**Comment by janagombitova** [comment]
What is the status of this issue? Is there still more to be done? How have we improved the copying?

**Comment by iperdomo** [comment]
We deployed a change that will prevent reaching the 10min limit when copying.

**Comment by iperdomo** [comment]
Just for completion, a Survey with 1 form and 538 questions (without any translation) takes 6min
