### ISSUE TITLE
Selective locking/un-locking of question groups for template surveys (IDH)

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3675]
# Context
With #3667 we implemented the most minimal change needed to ensure data consistency for IDH. We hard code which survey is considered a **template**. If this survey is copied all its questions cannot be edited in any way (no changes, deletion, moving nor copying) and the question group can only be deleted. Salim can add new question groups with new questions to the survey. These changes ensure that questions and groups defined in the template are not changed when used in different projects ensuring data is collected in the same way allowing to clean the data using the same rules, analyse it and compare values across projects. 

# Opportunity 
This issue aims to take the current implementation further to support Carmen and Mercy better in their work for IDH. Please note that the implementation is still IDH only and not yet ready for use by other partners. 

## Current status quo

Last week we showed the implementation to: 
* Carmen - the guardian of data consistency across all our IDH projects 
* Mercy - the person creating new surveys and handling data collection for most of the new projects 

They explained the structure of the template survey more: 
* Core question groups with questions that must be used in the way they are defined - nothing can be changed across all projects to this group of questions 
* Crop/company-specific question groups: 
   * Some questions cannot be changed - have to be asked in the same way across all projects 
   * Some questions must be changed to make them context-specific - the changes can range from stating the crop type in the question text, adding another option to the list of options, setting the right cascade resource, to adding another new question to the question group. 

A survey is defined by Carmen in Flow. This survey holds the questions the projects use (besides some project-specific questions). Mercy at the start of a new project copies the survey. She cannot edit any of the template question groups and questions. 

## The problem 

The problem is that Mercy needs to edit some of the questions, in some of the groups. 
* Carmen knows when defining the survey template which of the questions need to be customised. 
* We asked if having the template hold **only** the core questions (those you cannot change) would work - they said No, as there are too many of these questions and creating them manually every time will lead to more work. Plus sometimes they only need to change one value in the question text and the rest Mercy does not touch ensuring the remainder of the question in identical across the projects. 

Another problem Mercy has today is not knowing easily which groups and questions she needs to edit and which not. Now she needs to open each group and each question. If she can easily see what needs to be edited the easier her work will be.

**Comment by kardan** [comment]
We're gona allow the template creator to have access to the immutable flag and decide what will be locked or not once copied.

Todo:
- [ ] In the client, If survey is template we should expose the immutable flag
- [ ] Update the copy survey logic to use the actual value.

**Comment by janagombitova** [comment]
![Screen Shot 2020-11-24 at 13.47.31.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/b5441894-8c82-41a5-992b-e3b670046d58)

![Screen Shot 2020-11-24 at 14.17.31.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/1c257e62-f8cc-480a-ba60-b3bacb1f2d78)

Shared the changes with out IDH team, the initial feedback is: 
> Carmen, 16:46
> He Jana, this looks great to me:). I assume though that everyone can change this setting in the master survey? It would make for a good workflow to have only one person that can edit the master survey - although I don't think anyone wants to be that person:D

Mercy and Ethel will look at the changes today, but I think we can close the issue and open new ones linked to the epic if anything pops up. Well done everyone!
