### ISSUE TITLE
Expand question tooltip character limit 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3677]
Request from IDH. 

Currently Salim can add tooltips to his Flow questions. The value of them is that they explain or provide more context to the question for Al to understand it better. Today you can add a tooltip of max 500 characters. 

<img width="1256" alt="Screen Shot 2020-11-24 at 10 41 32" src="https://user-images.githubusercontent.com/12456965/100076696-c5ba3980-2e41-11eb-9f25-ca89ed2a412c.png">

IDH requested to expand this limitation as they are adding longer explanations of the different words in the questions, instructions or links even to the tooltips. Enumerators do not need to see the content every time so using a text field that is always visible in the form is not needed. But they need to be able to read an explanation of the question at least once (the 1st time) and maybe a random amount of times after that. So the tooltip set up is good, it is just too short at the moment.

**Comment by janagombitova** [comment]
Extra side request (if possible and simple to do, if no - ignore it): Can we expand the text box to show the full height of the text that is put in?

**Comment by iperdomo** [comment]
We need to set 1500 chars into the translations too
