### ISSUE TITLE
Form xml does not contain QG translations

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#3685]
# Context
Why do we add this issue?
In webforms we will need to display the translations for question groups. The question groups contain longish texts which the user will need to understand to properly grasp the context of the questions

# Problem or idea
What is the cause?
We can enter question group translations in the form definition. However the form xml does not contain the translations 

# Solution or next step
How could we solve it?
Form xml should contain the translations for the QG

**Comment by janagombitova** [comment]
When handling this issue we should look at all Form elements that should have translations but maybe do not: 
* form title
* question groups
* question tool tips 

And we need to also handle how this will affect the app

**Comment by iperdomo** [comment]
@janagombitova @joycarpediem can you confirm that we only need the translation strings in the XML? I mean, we can deal with the *use* of those translations in the App later and not part of this effort?

**Comment by janagombitova** [comment]
@iperdomo Joy needs to be able to show the translations in webforms, so we can leave the app changes for another time, but if it is minimal effort then I rather we handle then on both sides. I will leave this up to you and @valllllll2000 to estimate and decide.

**Comment by joycarpediem** [comment]
> @janagombitova @joycarpediem can you confirm that we only need the translation strings in the XML? I mean, we can deal with the _use_ of those translations in the App later and not part of this effort?

@iperdomo  For the webforms we only need the translations to be present in  the xml
