### ISSUE TITLE
Data submissions empty

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3697]
Looking at a different issue, I noticed the dataset on wai.akvoflow.org > WAI Bangladesh (WASH SDG) > Bangladesh Mid Term Review 2020 > Mid Term Review 2020 - HH Survey Final > Household Survey has submissions that are completely empty. The data point is created, there is even the duration of the submissions logged but no data. 

We need to see why we have these empty rows and see if we can prevent them from happening. 

<img width="1212" alt="Screen Shot 2020-12-01 at 09 45 09" src="https://user-images.githubusercontent.com/12456965/100717125-f2c69900-33b9-11eb-9c6e-b87f86ea72d4.png">

**Comment by iperdomo** [comment]
We found that the missing data is actually *deleted data* by the user. We didn't manage to execute the delete within 60s and the *form instance* was *partially* deleted.

The workaround is to delete the form instance, and then in an asynchronous process (a Task) delete the its child objects.
