### ISSUE TITLE
Survey Exel Export does not show al dependencies

### ISSUE THREAD

**Issue by JosjeS** [akvo/akvo-flow#370]
The survey form does not show all my dependencies.
Working in FLOW Training instance, -> Akvo presentations group -> WASH Alliance Survey -> Survey number 1547001

Screenshot of excel survey output attached, and as you can see only 6 and 8 appear dependent, while questions 2,3,4,5,6,7,8 are all depended on an answer given in Q1.

![screen shot 2013-09-27 at 6 01 35 pm](https://f.cloud.github.com/assets/4329924/1227258/1d2563e2-278e-11e3-88cf-5362aadc0c9b.png)

Put it as an issue on tender, Ivans response: 

"After an initial analysis, the issue exporting the Survey Form is unrelated to this thread, but it seems a bug in the export functionality.
Can you please log an issue in GitHub? Add the same details you added to your question."

Cheers, 
Josje

**Comment by jonase** [comment]
## Test plan

* Create an option question Q1
* Create other questions of different types and in different question groups and make them dependent on Q1
* Create a survey form export
* Make sure that the dependant note "Only answer if you responded _ to Q1" is displayed for all dependant questions

**Comment by rumca** [comment]
Tested and works as intended on release/1.8.1 :+1:
