### ISSUE TITLE
Registration form submission exists but data point does not 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3714]
Instance: wai.akvoflow.org
Dataset: WAI Bangladesh (WASH SDG) > Bangladesh Mid Term Review 2020 > Mid Term Review 2020 - HH Survey Final > Household Survey
Instance ID: 1116504011
Data point ID: t2yx-n046-d2a1

## Problem 
When updating a Lumen dataset Jigmy got the error that a data point does not exist in the referenced dataset. I initially thought it was the usual case of deleting a registration form and updating a monitoring form, but I was wrong. 

The dataset in mind in the registration form dataset. The submission that is problematic exists in the dataset, I just downloaded the file and see the row in the sheet. It also shows in the Inspect data tab. But when you search in the Monitoring tab for the data point, based on the data point ID from the dataset file, it is not found. Same happens when you search in the Assignments for the data point. 

So it seems we have the registration form properly submitted but the data point was not created. **?** 

<img width="1171" alt="Screen Shot 2021-01-05 at 11 09 34" src="https://user-images.githubusercontent.com/12456965/103634508-73dbf780-4f47-11eb-9fdf-0151f26cffa0.png">
<img width="1169" alt="Screen Shot 2021-01-05 at 11 10 07" src="https://user-images.githubusercontent.com/12456965/103634512-750d2480-4f47-11eb-94cf-8d712fc924a3.png">
<img width="1273" alt="Screen Shot 2021-01-05 at 11 17 05" src="https://user-images.githubusercontent.com/12456965/103634518-76d6e800-4f47-11eb-8342-56b0594973e2.png">

**Comment by tangrammer** [comment]
@janagombitova  seems that we can close this issue now

**Comment by janagombitova** [comment]
Resolved by recreating the data point
