### ISSUE TITLE
Survey templates - v3 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3718]
# Context 
In a few part iterations we released a prototype for **survey templates** where some questions are **locked** for the copies of those templates (https://github.com/akvo/akvo-flow/issues/3675). 

## These changes aim to address two problems: 
* data consistency - cross organisational/programme indicators need to be collected in an identical way across projects for data to be consistent and easily comparable 
* making it easy to create a new survey based on a set of predefined questions/question groups - survey creation is still one of the most time consuming tasks our users need to do, organisations more and more reuse certain surveys (proven to work well for projects, surveys based on international standards, surveys based on organisational needs) 
 
Users
* Petra - the M&E lady who defined the organisational indicators and the survey template and is guiding the data consistency 
* Salim - project officer - who needs to follow the template to start his data collection, but also be able to adjust the tempate according to his projects needs 

## Our current prototype
* define a survey as a template (hardcoded) 
* in a template survey questions can be locked 
* after copying the template survey locked questions cannot be edited, deleted

### Copying is not ideal as a survey creation task
* The fact that Salim has to have access to the template survey to be able to copy it, means he can also make changes to the template survey
* But Petra should be the only one who can edit the template 
* Ideally, when creating a new survey Salim can say if he wants to create a new survey or use a template 

### Hardcoding of template
* To set that a survey is a template survey, we in the development team need to add that to the configuration of the instance 
* This means that the partner cannot independently set their own templates making the feature adoption almost impossible 
* Ideally, anyone working on a survey can define it as a template or even we have a specific user right to be able to do so (but we should start small)  
 
### Too many unlocked questions because of project customisation needs
* in the template many questions need to be adjusted to fit the project. For example: 
   * the main crop in the question test needs to match each projects main crop, 
   * the administrative cascade needs to match the country of the project. 
* Some of these changes are in the question text, some in other parts of a question. 
* The current implementation means that many questions are not locked, so Salim is able to adapt them based on his project, but being a risk to the data consistency Petra is guarding. 
* Ideally Salim can change in the question only those parts that need to be changed. 

### Creating a new survey by removing what one needs or selecting what one needs
* The current prototype follows the strategy: copy the template and delete what you do not need 
* This works for cases when Salim has just a few questions or question groups he needs to get rid of
* An alternative way is, from the template select what you need and only build the new survey using what Salim selected 
* Which strategy is better depends on 
   * when the survey is created (is the new project survey created after the template is defined - then the *delete* approach is ok, but if you need to bring in standard questions to existing forms, it is easier to add for example specific question groups from the template)
   * how the organisation has their indicators organised and how projects are set up 
   * are the templates structured as survey forms (where the question logic and layout is also defined) or as indicators (where the indicator questions can be added to survey forms based on Salim's needs)
* TO BE FURTHER SPECIFIED BASED ON SOME CALLS JANA HAS IN THE NEXT DAYS

**Comment by janagombitova** [comment]
After talking with our team testing out the templating, I learned that at this moment two main problems prevent them from fully utilising the feature: 
* Salim cannot decide which survey he wants to make a template himself but has to ask us (Flumen K2 Engine team) thus making it too much of a hassle resulting in him not using it 
* Because the template has to be copied, too many users have access to the template survey that should be editable only by a few people 

The other issues mentioned above are important but unclear at this moment as: 
* The Master survey (thus the template) still need to be tested before they can be sure about the structure of the locked questions and the overall form structure 
* The team is still figuring out how they will know with each new project which questions they will need to use from the temple
--> so making any product decisions and changes to support their process is too early 

However, in this v3 we should tackle the two problems above. We assume that by handling them: 
* the use of the templates will increase by 10%
* we can push the feature to all partners 
* we can promote the use of the Akvopedia survey templates somehow within Flow

**Comment by muloem** [comment]
Issues to complete

- [ ] Finish rendering the list with the radio buttons
- [ ] Implement the copy action when the create button is clicked (the copy code is already there, we just need to call the endpoint passing it the correct parameters)
- [ ] Styling the popup
- [ ] Implement a page for cases where there are no templates on an instance
- [ ] Tracking usage

**Comment by janagombitova** [comment]
Yesterday @valllllll2000 released the changes where Salim once creating a new survey he can choose if he wants to use a blank one or use a survey template. This change was released to all users. With it we assume: 
* users like Petra can now better protect the survey templates as Salim does not need editing rights to copy them. So Petra can move the templates to a folder she only has access to
* more partners will show interested in the templating feature as it is now exposed at the 1st step of their workflow - when creating surveys 

## Next steps are: 
* change the behaviour of `copy`to how it worked before
   * currently is a survey template is copied, the new survey has questions locked. However, to use a survey template to create a new survey, we just released the new workflow. So copying a survey template should mean simply copying the survey. This way Petra can create more surveys based on the structure and more templates  
* enable Salim and Petra to independently from us set a survey as a template 
   * with Valeria we agreed to add a checkbox to the Survey settings under monitoring 
   * we will add an explanation of what this checkbox means 
   * Salim and Petra will be able to set a survey as a template but also un-set it. We thought of not allowing to undo, but realised that: 
      * What if Salim and Petra are just curious about how the feature work and want to try it out 
      * There is no risk (to data consistency or survey consistency) to changing a survey to no longer being a template, then it will not appear in the template list and questions will not be locked anymore, suvreys created previously will be unharmed

**Comment by valllllll2000** [comment]
This is how it will look like:
![Screenshot from 2021-03-09 15-57-07](https://user-images.githubusercontent.com/923280/110490183-5c102380-80f0-11eb-8343-12565713c35e.png)
@janagombitova let me know if the text is ok

**Comment by janagombitova** [comment]
Survey templates help you standardise your data collection. Make a survey template and lock questions. A template can be used as a basis for any new survey where the locked questions cannot be edited, ensuring you collect data consistently across various projects. 

@valllllll2000 how about this? ^^

**Comment by valllllll2000** [comment]
@janagombitova thanks that's good, how about the title: 
Make a template
Mark as template
Mark this survey as template
?

**Comment by janagombitova** [comment]
I tested uat2 and noticed the following: 
1. You set a survey as a template and save 
2. You go to create a new survey and chose to use a template 
3. In the pop up where the list of survey templates should show your most recent survey template does not show 
4. After refreshing Flow the survey shows in the list of templates 

Is there a way the list can show the most recent templates without needing to reloadFlow?

**Comment by janagombitova** [comment]
@valllllll2000 I let my own comment sync in and changed my mind. Seeing how much work there is currently on the team, I think we can with ease release the changes and later improve on the implementation once we get feedback from partners and users. 

So, we are good to go 👍

**Comment by valllllll2000** [comment]
Done and released

**Comment by janagombitova** [comment]
@valllllll2000 I was creating gifs for the support documentation and noticed that I missed something when testing yesterday. I found an issue with **locking**

1. Set survey A as a template and lock questions 
2. Copy survey A using the copying functionality - all works fine, the survey is copied as is (as another template) and the questions marked as locked are marked as locked in the survey A copy 
3. Create a new survey B using the option to create a survey from a template (select the original survey A) 
4. Once survey B is created (confirming in the Messages tab) open it
5. In survey B the questions are not locked. <-- problem 

on uat1 > _ _ Jana > Template surveys > Example webform > has all questions in group 1 locked

**Comment by janagombitova** [comment]
![Screenshot 2021-03-18 at 11 53 51](https://user-images.githubusercontent.com/12456965/111615110-a96f4d80-87e0-11eb-9a60-95499d59d405.png)
Tested on pilots.akvoflow.org and can confirm that all is now resolved. Even for surveys created before the fix the questions are now also properly locked. 

Thank you
