### ISSUE TITLE
Feature request: Dependency option when ticking the 'allow other' at option questions

### ISSUE THREAD

**Issue by JosjeS** [akvo/akvo-flow#372]
Hi All, here a feature request:

When making an option question you can tick a box saying 'allow other' 
But if you then create a dependency question to that option question, it is not possible to select 'other' as an option. 

Example:
At the moment if you want the next question to be dependent on 'other' you have to fill in other as a separate option, so: 
Yes
No 
Other 

If you would only type 
Yes 
No 
And tick the box 'allow other'
If you create a dependency question after that you would only have the choice between Yes an No. 

Cheers, 
Josje

**Comment by janagombitova** [comment]
Moving this issue to product design repository as we need to better understand the problem in order to move forward. New issue: https://github.com/akvo/akvo-product-design/issues/184
