### ISSUE TITLE
Incomplete dependent questions look like they can be saved

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3723]
# Context
When we try to add a dependent question, when we set it as dependent but fail to fill the dependency question and/or select the option that the new question is dependent on, if we press save all seems to work but we actually ignore and do nothing.

![Screenshot from 2021-01-12 16-31-59](https://user-images.githubusercontent.com/923280/104336252-7fee2900-54f4-11eb-9253-c7ce9e94c62f.png)

After saving the user thinks the question was saved but it did not.

# Problem or idea
We should either disable the save button (like we do for options) or do a check before saving and show a popup like we do for cascades.

**Comment by janagombitova** [comment]
I think we said we should move to disabling the `save` button eventually for all such cases and possibly highlight the missing components
