### ISSUE TITLE
Translations exist but do not show in the UI

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3726]
Reported via support: https://akvoo.reamaze.com/admin/conversations/akvoflow-support-request-number-451024-from-brandie-at-lifewater-dot-org

URL: lifewater.akvoflow.org
Survey: Tanzania > Shinyanga Field Office > Evaluation > Household Baseline > Household Baseline Survey Project 1
If you export the Survey form you can see that it is translated in 2 languages, but the UI is blank as if there are no translations. 

I tried on uat1. I created a new form in `_ _ Jana > Testing translations` and translated it to Slovak. After refreshing the page, all shows well. I did not check an old form on uat1 with translations as I did not remember which had them.

**Comment by janagombitova** [comment]
Just to add some more examples: I just tried on this survey where I knew there is a translation and it works as expected. 

Instance: https://greencoffee.akvoflow.org/
Folder: Endline
Survey: GreenCofee Endline Survey
Form ID: 372010001

**Comment by muloem** [comment]
This appears to be a bug that occurs when there are no translation strings added to the form name or description and also no translations to the first group or any question in the first question group.  Adding translations to these makes the rest appears

**Comment by janagombitova** [comment]
ok. let's resolve this as we can have cases where the 1st translations are not done yet and the user is working with more than one language making it confusing on to which language the added translations will go to once we trigger them to show
