### ISSUE TITLE
Translations missing for some questions

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3743]
# Context
Issue reported by support: after making a survey copy, some translations are missing, seems to be random

# Problem or idea
After taking a look it seems that when there is a translation for both question and the question tip, only one of the 2 gets copied

# Solution or next step
Make sure all translations are copied correctly

**Comment by janagombitova** [comment]
I am reopening this issue again as it seems the translations for options are still missing when copying. Plus the copying is not just from one survey to another but also within the same form, that is an issue. 

> hi, what we did was copy a group within a form. So, within that same form, the copied group had missing translations. The translations missing were not on tooltips or on questions this time, but rather on answer options. (from Andres)
