### ISSUE TITLE
Download data without personal information

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#3745]
# Context
Currently, flow allows data to downloaded in spreadsheets . These spreadsheets contain personal data .  Once the data is downloaded , the spreadsheet potentially floats around in emails and peoples personal systems . Not a great look privacy wise.
Immediate need : For the beyond chocolate project , the partner only wants to access the personal information via the dashboard. The do not want personal information in any of the spreadsheets as they feel it jeopardises with partner trust if personal data is moved around in spreadsheets 

# Problem or idea
What is the cause?

# Solution or next step
Flow already has the "Holds personal information" flag . We can provide an extra option in the data downloads to that the partner has the option of download only "non-personal" data in spreadsheets based on this flag

In the long run ,we can think of making this checkbox permission controlled so that by default we only allow download of anonymous data and users only with the right permissions can download the entire dataset

**Comment by janagombitova** [comment]
Notes from today's meeting: 
* We are committed to good data practices and adding the flag to the questions was just step one 
* By default, personal data (questions flagged as `holding personal information` are not added to the export sheets 
   * So for current users who did not make use of the flag, nothing changes for them when exporting data 
* The setting to implement is for Petra to add personal data to her data export 
* Which data export? Does not affect the data cleaning input, as we import based on question IDs
* We also spoke briefly about Submitter, Device ID as these also hold personal data. We will not handle these at this iteration as we assume that for analysing the data, these fields are needed. Based on the feedback we get, we can remove these in another iteration. 
* When exporting data today we have the following options: Data cleaning, Data analysis, Comprehensive, Geoshape and Survey form (that does not hold data). This change then affects the 1st 4. If it is easy to implement on all 4 export types, then we will do it, but if it takes more time we will start with the Data cleaning export and then expand to the other types. 
* We need to adjust the tooltip text for the `holds personal data` flag to explain that when exporting the data, this column will not show by default etc etc 

![Screenshot 2021-02-17 at 10 45 21](https://user-images.githubusercontent.com/12456965/108186185-5df84f80-710d-11eb-982e-4eb8ae7c0273.png)


**Extra thoughts** 
* We should add the column to the Survey form export to show which questions are flagged as holding personal data 
* Should we move the Survey form export to the survey UI? (if the new export setting to `add personal data` will affect all data exports, then having the Survey form export on this page is becoming more and more illogical. Can this be handled by a UI change, or we 'just' move the Survey form export to the survey UI)
* Should we add
