### ISSUE TITLE
Error copying surveys between instances

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3747]
# Context
Copying surveys between 2 instances fails

# Problem or idea
No error logs shown so it needs investigation
# Solution or next step

**Comment by valllllll2000** [comment]
For the most part this issue has been fixed, what remains is:

- [ ] Some dependencies seem to be broken when copied
- [ ] Some options seem to not be copied correctly

**Comment by dlebrero** [comment]
I understand that cascades do not work either. Correct?
