### ISSUE TITLE
Data point seems to miss RF data but it exists 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3753]
A support issue: https://akvoo.reamaze.com/admin/conversations/akvoflow-support-request-number-464912-from-brandie-at-lifewater-dot-org

lifewater.akvoflow.org
monitoring survey: Uganda - Mayuge Field Office - Water Points - Mayuge New Water Point Survey 
registration form: New Water Point Registration
the data point that is problematic: cg6p-vbn5-d97e

A partner complained that the data point name does not show, but there seems to be more at hand. Steps I took: 
* Checked the survey to see if it is a monitoring one: yes. The registration form is noted above 
* Checked the data submitted to the data point: Went to the Monitoring tab and searched for the data point. It seems that point has 2 submissions to it, from 2 monitoring forms. So I assumed that the registration form submission was deleted explaining the missing data point name (the issue that was reported) 
* Exported the data from the registration form and searched for the data point ID: it exists in the dataset 
* Checked via Inspect data tab to double confirm by searching by the instance id of the submission (872860915) and it also shows in the Inspect data tab 
* Thought, maybe we have the *impossible* case of 2 data points with the same ID in the dataset, but the registration form submission was made in March 2020 and the monitoring form submissions in Jan 2021. I thought maybe the registration form happened after the monitoring submissions what could confirm my hypothesis. But it did not. 

So the question is: 
**Why do we have a data point that seems to not have the registration form data even though we do have the registration form data?**

**Comment by valllllll2000** [comment]
After checking the datastore, indeed the datapoint cg6p-vbn5-d97e only has 2 SurveyInstance and none of them is for the registration form. The possibilities: RegistrationForm submission has been deleted or could they have changed the registration form? will now check unilog for any deletion

**Comment by janagombitova** [comment]
@valllllll2000 can we change the different surveyLocaleID to match the other ones manually? Will that solve our issue and give us time to figure out how this happened?

**Comment by valllllll2000** [comment]
I can change it, I have written down the wrong number to keep track of it. 
I have reviewed the device file and all is correct. The form instance was created correctly with the right id or at least that is what is sent to unilog:
` {"orgId": "akvoflow-73", "entity": {"id": 859130915, "name": "Mayuge - Kyiterera - Kisawe - UGMGWP0101", "type": "DATA_POINT", "surveyId": 798961152, "identifier": "cg6p-vbn5-d97e"}, "context": {"source": {"type": "SYSTEM"}, "timestamp": 1583778403855}, "eventType": "dataPointCreated"}
 {"orgId": "akvoflow-73", "entity": {"id": 872860915, "type": "FORM_INSTANCE", "formId": 774111493, "dataPointId": 859130915, "surveyalTime": 1072, "collectionDate": 1583777422596}, "context": {"source": {"type": "SYSTEM"}, "timestamp": 1583778404254}, "eventType": "formInstanceCreated"}`

**Comment by janagombitova** [comment]
Thank you @valllllll2000 for fixing the data point details manually. I just checked and all works as expected. Case closed. Mystery open but lets hope it was a one-time thing
