### ISSUE TITLE
Data point behaviour changes after monitoring form is deleted 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3755]
Reported via support by akvoflow-201 and reproduced on uat1 > _ _Lumen tests > Monitoring surveys folder > Simple monitoring survey 
* Registration form: RF 
* Monitoring form (with data): To do
* data point: nkc4-xrjb-4bpy

## The problem: 
After deleting the monitoring form submission to a data point, the dataset with the registration form data does not update in Lumen, stating the data point does not exist, the data point name of the data point does not show anymore and assignments seem to be odd too. 

## Steps to take to reproduce the issue: 
1. Pick a data point in a survey that has one monitoring form submission to it (by exporting the monitoring form data and picking the data point ID - column A) 
2. Export the registration form data and mark the chosen data point. This data point should look normal, have a data point name. 
3. Go to the Monitoring tab and search for the chosen data point. You will see it has a data point name and the submissions to it show well after opening up the data point.
4. Go to Inspect data tab, select the monitoring form and the submission to the data point, by searching by the Instace ID of the submission (can be found in the monitoring form export in column D) 
5. Delete this submission. 
6. Confirm it is deleted by repeating step 4. 
7. Go to the Monitoring tab and search for the data point by searching by the data point ID. This time  I got the message that `no such data point exists` but it does as we did not delete the registration form that creates the data point. **<-- Problem symptom 1**
8. Now export again a new data sheet for the registration form. You need to get a new sheet. Search in the sheet for the data point, you will see that that data point name (column B) is missing. **<-- Problem symptom 2** as the data point name comes from the registration form and should not be affected by the deletion of a monitoring form.

**Comment by valllllll2000** [comment]
Taking a look in the datastore:
SurveyInstance for that datapoint nkc4-xrjb-4bpyhas exists, deviceIdentifier is IMPORTER, uuid is 15025683-2a04-4283-88cb-c49a1896a934, a DeviceFile for this datapoint does not exist as it was added by importer and not the app.
SurveyedLocale (datapoint) id  196039125 or nkc4-xrjb-4bpy does not exist in the datastore.

**Comment by tangrammer** [comment]
- [found](https://github.com/akvo/akvo-flow/blob/master/GAE/src/org/waterforpeople/mapping/dao/SurveyInstanceDAO.java#L590) that if `relatedSurveyInstances.size() < 2` we then send `SurveyalRestRequest.DECREMENT_CLUSTER_COUNT_PARAM=true`

- [then](https://github.com/akvo/akvo-flow/blob/master/GAE/src/com/gallatinsystems/surveyal/app/web/SurveyalRestServlet.java#L141) we call `adaptClusterData ` with `delta=-1` 

- [so finally](https://github.com/akvo/akvo-flow/blob/master/GAE/src/com/gallatinsystems/surveyal/app/web/SurveyalRestServlet.java#L339-L341) we delete the `SurveyedLocale`

... could be that the problem?

**Comment by janagombitova** [comment]
Besides ensuring this does not happen again, do we and is it possible to also fix all the existing affected data points?

**Comment by tangrammer** [comment]
@janagombitova 
found these instances with same problem
```clojure
[["akvoflow-123" 6]
   ["akvoflow-uat1" 1]
   ["akvoflow-7" 71]
   ["akvoflow-198" 2]
   ["akvoflow-55" 16]
   ["akvoflow-195" 112]
   ["akvoflow-61" 3]
   ["akvoflow-52" 68]
   ["akvoflow-201" 35]
   ["akvoflow-108" 8]
   ["akvoflow-27" 1]
   ["akvoflow-193" 7]
   ["akvoflow-37" 443]
   ["akvoflow-117" 5]
   ["akvoflow-73" 8]
   ["akvoflow-182" 16]
   ["akvoflow-121" 1]
   ["akvoflow-10" 7]
   ["akvoflow-209" 180]
   ["akvoflow-23" 11806]
 ]
```

the script to fix them already finished, 
Could you give a try with the specific akvoflow-201 instance?

**Comment by janagombitova** [comment]
@tangrammer as far as I can tell it is resolved. Thank you very much
