### ISSUE TITLE
Make variable names mandatory for some instances

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3756]
# Context
For data analysis partners use variable names. In Flow we have the rule that these have to be unique per survey - this is great. But we do not have the rule that they have the be defined per question. This is where they have issues with data analysis as our team forgets to add variable names to questions that do not come form the Master survey.

For now we need to make variable names mandatory (only for the akvoflow-194 instance) - if this is possible and if so, then how will we do it

# Problem or idea
Example setting in appengine-web.xml `mandatoryVariableName=true`
Use config setting:
* do not allow saving question if variable name is not set (same as for question text)
* in this case remove the "optional" text next to it

What will happen if surveys are copied?

**Comment by janagombitova** [comment]
> What will happen if surveys are copied? 

If a survey is copied, that was created before this rule and thus has questions without variable names, then these are copied over as is - so without the variable names. Only once Salim opens the question, he would not be able to save it as the rule will apply. <-- or at least this is how I see it, to keep the scope to the minimum

**Comment by janagombitova** [comment]
Yesterday we released this to production and enabled for akvoflow-194. Good job @valllllll2000
