### ISSUE TITLE
Delete form data in bulk

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3774]
The original issue here: https://app.zenhub.com/workspaces/akvo-k2-55d493e09e846e9104ab9478/issues/akvo/akvo-flow/3597

# Context
In Flow data deletion is relatively limited. You can delete one submission at a time, so you cannot delete all data to a survey form in one go. You have to go through all the individual submissions. In some cases partners contacted us with a list of survey form they wanted the data to be deleted.

Sometimes partners want to remove old data from their instance or have done a test round of the survey form, want to delete all the submission so they can start the actual data collection.

We never invested more in deletion because of the risk of someone deleting an entire dataset by mistake. Some products handle such cases - where you cannot bring the thing you delete back by asking the user for a double confirmation where you need to type something in. Plus stating this cannot be undone.

Deleting data in bulk should fall under the user permissions to Delete data. If one is not allowed to delete one submission, she should not be allowed to delete all either.

**Comment by janagombitova** [comment]
@Kiarii can you take a look at this one and how it can be handled in the UI of Flow's Inspect data tab (the only place where users can delete data). Thank you

**Comment by Kiarii** [comment]
I think adding an option to select all submissions and a respective action "delete" might be one approach.. perhaps @muloem you have some input towards this?
