### ISSUE TITLE
Simplify survey and form settings UI

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3827]
When looking at how can we improve the visibility of publishing survey forms to the users: https://github.com/akvo/akvo-flow/issues/3795 we agreed that we will also simplify the current UI for the survey settings and form settings. 

The current implementation takes up a lot of screen real estate that is not needed. Furthermore, actions that need to be visible to Salim are hidden (as changing the form name) and actions that do not need to be as prominent are (form ID). 

@Kiarii can you please add the proposed changes here? 
Linked to this issue we will also remove the Notifications feature (#2831)

**Comment by Kiarii** [comment]
This [wireframe mockup](https://invis.io/ZB116ELJVM9K#/453784015_26-2-1_Publishing_Completed___Form_View) illustrates the Initial ideas
