### ISSUE TITLE
Partner data deletion

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3834]
Working with a partner, managed by Francis, a few data deletion requests came in and I thought it is easier to put them all in one issue for an overview. @muloem knows which Flow instance this is for ;) 

* [x] For the dataset: Quthing District > Community Institution Quthing > Village Identification (form ID: 18640047) there is an empty submission resulting in Lumen import fail. When trying to delete via Inspect data tab, the tasks fail. Please delete from this dataset the submission with instance ID: 214570335
* [x] For the dataset: Thaba Tseka District > Community Institution Thaba Tseka > Village Identification (form ID: 159660048) 2 blank rows that need to be deleted: 
   * Instance ID: 184960030
   * Instance ID: 181452155
* [x] For the dataset Butha-Buthe - 154690643 all submissions need to be deleted as they were imported twice.

**Comment by valllllll2000** [comment]
Done
