### ISSUE TITLE
Change the rule on more-column transformations to repeated groups

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#3839]
With the data groups changes, we now have in one data set data groups that can have a different number of rows (multidimensional). To ensure transformations output columns with the same number of rows, we added the rule that if a transformation uses more than one column, these columns need to come from the same data group. 

Working on migrating existing data to this implementation we, however, see that this rule is too strict. Thus we decided to make the limitation applicable only for repeated data groups: Transformations using more than one column can only happen if the columns are from the same repeated data group. If columns used are from different groups but these are not repeated, they can be executed. 

@tangrammer is this description correct? In which data group will Lumen put the new column if the used columns come from 2 different parent (not repeated) groups?

**Comment by muloem** [comment]
Issue moved to [akvo/akvo-lumen #3150](https://github.com/akvo/akvo-lumen/issues/3150) via [**ZenHub**](https://www.zenhub.com/)
