### ISSUE TITLE
lein-cljsbuild and lein-shell could not transfer artefact error

### ISSUE THREAD

**Issue by gxco-sg** [akvo/akvo-flow#3841]
# Context
When I run docker-compose up in the directory, I get the below error. I have tried to look for solution but it says something wrong in the dependency file or network issue. There is no network issue as I'm running this script in aws. Please suggest the change and where the file is located.

# Problem or idea
Failed to read artifact descriptor for lein-cljsbuild:lein-cljsbuild:jar:1.1.0
Failed to read artifact descriptor for lein-shell:lein-shell:jar:0.4.0

# Solution or next step
This could be due to a typo in :dependencies, file system permissions, or network issues.

*Apologies I'm not a pro and still in learning phase. 

<img width="1031" alt="Screenshot 2021-06-26 at 12 41 13 AM" src="https://user-images.githubusercontent.com/18293759/123474188-395e3800-d617-11eb-8544-1f62ba9e31d0.png">

**Comment by iperdomo** [comment]
Hi @shikhergupt, thanks for trying out.

If you have a Linux based host machine, the problems are *file system permissions*. We  [bind mount](https://docs.docker.com/storage/bind-mounts/) some host folder in the dev container.

You can see the configuration here:
https://github.com/akvo/akvo-flow/blob/45881d62cfd5b70c1f880bde6d73f9b34d6ec234/docker-compose.yml#L28-L29

In your host machine, open a terminal and change the owner of the `$HOME/.m2` folder, e.g.
```bash
# Stop any running container
$ docker-compose down -v

# Change permissions in the host machine
$ sudo chown -R $USER:$USER $HOME/.m2

# Start the system again
$ docker-compose up --build -d && docker-compose logs -f
```

I hope it helps.

**Comment by gxco-sg** [comment]
Thanks. What is the preferred OS and version for this app and the server configurations required?

**Comment by iperdomo** [comment]
@gxco-sg what you are trying is the development environment. For production deployment you must use [Google App Engine](https://cloud.google.com/appengine/docs/standard/java) (Java 8).

We have several [scripts](https://github.com/akvo/akvo-flow/tree/master/ci) that deal with the deployments, directly from a CI environment, you can study them and see that they're based on the App Engine available documentation.
