### ISSUE TITLE
Handle ImageUpload errors properly

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow#3843]
# Context
see https://github.com/akvo/akvo-flow/blob/master/GAE/src/org/akvo/flow/rest/ImageUploadRestService.java#L185
The errors are not handled properly, we could use [SpringResponseStatusException](https://www.baeldung.com/spring-response-status-exception) 
The way the service is done right now, for the client it is not easy to know if the request succeeded or not
Client should be updated accordingly

**Comment by muloem** [comment]
The client is actually just waiting for this to be implemented. It already handles based on the returned status and *not* based on the contents of the response object.
