### ISSUE TITLE
Bulk upload progress bar is not cleared on submitting second file 

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#390]
How to reproduce:
1) drag a file into the bulk upload drop file area
2) wait until the upload is done and the progress bar is at 100%
3) try to drag a second file in the drop file area
4) the upload will not start and the progress bar is not cleared.

Expected behaviour:
When the second file is dropped in, the progress bar should be cleared, and the upload should start.

**Comment by janagombitova** [comment]
Closing this issue as the page was redesigned
