### ISSUE TITLE
Improve treatment of dependent questions

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#393]
Reference: http://flowhelp.akvo.org/discussions/problems/312-dependency-questions-in-the-dashboard

Current behaviour:
Some dependent question in the surveys 2913030 & 2939002 in the ICCO instance do not appear in the preview screen or the device. An example is question 17, which is dependent on question 16.

Diagnosis:
We found that the dependent question was dependent on the option text 'yes ' (lowercase + trailing space), while the actual option text is 'Yes'. We think that this is the sequence of events:

1) a question was created, with a few options. one option was 'yes '. (note the lower case and the space).
2) a dependent question was created, and the 'yes ' answer was chosen as the dependency
3) someone went back to the first question, and changed the options to 'Yes'.
4) now the dependent question points to the 'wrong' answer, and will never appear again.

Proposed solution:
1) trim whitespace before saving an option
2) capitalize option text before saving
3) give user a warning if he/she is saving a question on which an other question depends, to update the dependencies.

**Comment by muloem** [comment]
@mtwestra we can close this as its addressed in #1123
