### ISSUE TITLE
Dashboard behaviour when a user signs out of their google account in a different tab

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#414]
When I sign out of my Google account on a different tab, then return to the tab where I have dashboard open I can still access certain parts of the dashboard which I perhaps shouldn't be able to - for example I can still view the messages screen, the users screen, the devices etc. 

I'm not sure of the feasibility of auto-detecting this and returning the user to the non admin screen if they try to do anything? I know on Google mail if I sign out in a different tab and then try interact with the mail client - it will prompt me to sign in again.

**Comment by janagombitova** [comment]
Closing this issue for now, if reported we can open it up and investigate again
