### ISSUE TITLE
Improve data cleaning capabilities dashboard

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#419]
Current behaviour:
* data cleaning can be done per record
* data cleaning can be done by exporting a raw data report, cleaning data, and importing again.

The excel-route of data cleaning is powerful, but also fragile: it is easy to mess up data and upload it again. Therefore, we would like to add better data cleaning features to the dashboard.

In consultation with Keri of Water for people, this is a first list of desired functionality:
1) Grammar, Punctuation, Capitalization and Spelling 
2) Normalizing similar responses  (for example making "don't know" "do not know" and "I don't know" all into "don't know") 
3) Finding Explicit Errors (for example: finding dates that are clearly wrong like 1798 and fixing those or eliminating them if the real answer is unknowable). 
4) Adding in additional information after a data collection (for example: if we do water quality testing as part of the survey we don't get results from the tests for several days so in practice surveys are submitted without the results and they are hand entered into the spreadsheet later as part of the data cleaning process.

**Comment by janagombitova** [comment]
Adding the comment to the product design issue on Data cleaning https://github.com/akvo/akvo-product-design/issues/2
