### ISSUE TITLE
Notifications contain reference to approval functionality

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#421]
Current behaviour:
when a submission notification is set up, the user receives an email with a request to go to the dashboard and approve the submission.

However, at the moment the approval logic is not enabled on the dashboard.

The notifications need to be revisited and checked for consistency with the current dashboard functionalities

**Comment by janagombitova** [comment]
Issue will be dealt with here: https://github.com/akvo/akvo-product-design/issues/170
