### ISSUE TITLE
Disallow certain characters in survey names

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#428]
Current situation:
All characters are allowed in survey names. This can cause trouble, for example because the survey name is used as the filename in bootstrap files, and a comma in a survey name could cause trouble when receiving the list of surveys from the backend by the device.

Proposed solution:
1) only allow a...z and 1..9 in survey names
2) use the surveyId instead of the survey name in the bootstrap process
3) add the survey name as an attribute to the survey XML file and retrieve it from there.

**Comment by janagombitova** [comment]
@valllllll2000 and @muloem I found this old issue in the backlog where the idea was to disallow "," and "/" . Can we take it up as a follow up from the bug we were fixing around the bootstrap?

**Comment by janagombitova** [comment]
Issue handled with implementation of changes that were released in 1.9.13.1 hotfix 
The usages of special characters in survey, form and folder names is not a problem anymore
