### ISSUE TITLE
Bulk upload code doesn't handle correctly the sharded structure of surveyal folder

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#430]
The bulk-upload process tries to process all the zip files in a folder (and subfolders) searching for duplicates and generating only __one__ `wfpGeneratedxxxx.zip`.

The current process can't handle the structure of the typical `surveyal` folder, and generates one `wfpGeneratedxxx.zip` per zip found.

Possible solutions:
* Keep the current behavior, but instead of generating a `wfpGenerated`, just upload the zip file,  and leave the duplication detection in the backend
* Fix the pre-processing part, searching recursively across _all_ subfolders

**Comment by janagombitova** [comment]
Recreated this issue in Flow services https://github.com/akvo/akvo-flow-services/issues/146
