### ISSUE TITLE
Unsaved translations lost when "show questions" is clicked

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#434]
When a user performs the following steps on the "manage translations" screen:

1. Enter translations for question group
2. Click "show questions" for a different question group

The translation text entered for the first question group is lost. It might be nice to auto save this when "show questions" or "hide questions" is clicked.

**Comment by janagombitova** [comment]
We need to find a unified way how we deal with autosaving or not-autosaving across the entire tool to maintain a consistent UX for our partners. Closing this issue for now and moving the question to product design - opportunity backlog
