### ISSUE TITLE
Enhance public facing maps

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#438]
In order to enhance the user experience of the map displaying survey results, a number of functionalities have been requested by partners:

1) ability to choose specific icons for surveys
2) clustering points so the map can show all points
3) editorial content in sidebar, explaining the context of the data
4) filtering on survey
5) institutional ownership - logo
6) embed map as widget in other websites
7) metadata should emphasize image

These need to be completed and prioritised.

**Comment by janagombitova** [comment]
Closing this issue and noting down the suggestions for public maps improvements in the future once we finalise internal maps and gather a better understanding of how our users use the public map
