### ISSUE TITLE
Reports drop down contains blanks

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#447]
Not sure whether this is intentional or not. When I do the following:

1. Copy a survey
2. Remove all survey questions and delete survey
3. Go to export reports screen
4. View survey drop down

There is a blank item on the survey drop down list. If this isn't the expected behaviour - I'm guessing the survey count total which is used to populate this drop down is not updated when surveys are deleted?

![deletedsurveyblankreportdropdown](https://f.cloud.github.com/assets/3003031/1800115/0e5d7d34-6bba-11e3-8ad5-b33e70da9ad6.jpg)

**Comment by janagombitova** [comment]
Tried to reproduce the issue, could not and considering the date when it was created I assume it has been fixed.
