### ISSUE TITLE
Make geographic admin boundaries visible on maps (up to level 2)

### ISSUE THREAD

**Issue by caetie** [akvo/akvo-flow#46]
National (= level 0)
Regional (= level 1)
District (= level 2)

Need to locate + load GIS shapeflles for all program countries, then display on maps as part of default view.

This is needed in reporting as well, can currently be achieved through including admin areas in surveys and rolling up by geoname.

**Comment by janagombitova** [comment]
Will not be part of FLOW - more functionality in DASH, based on current decisions. Closing issue.
