### ISSUE TITLE
Dashboard locks up when loading large translations

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#469]
Related to #455 

With very large survey translations it can take ~40 seconds to load, during which time the dashboard is unresponsive.

I think this should be handed this in a similar fashion to how the initial /rest/questions?surveyId=xxxxxxx call is handled when you first click to edit the survey. I.e. pulling up the translations screen (rest/translations?surveyId=xxxxxxx&questionGroupId=xxxxxxx), then indicating that there is still some loading occurring with the "Loading..." text across the top whilst waiting for the translation response to return.

**Comment by muloem** [comment]
Closing this one. Will be handled in #355
