### ISSUE TITLE
Multiple selection in an option question not working in 'survey preview'

### ISSUE THREAD

**Issue by henryjewell** [akvo/akvo-flow#472]
In survey preview the multi select option does not work. If you choose to allow multiple answers to an option question in survey preview you can only choose one answer to a question. On the phones everything works fine. I have tested this on multiple surveys and the behavior is always the same

**Comment by janagombitova** [comment]
Survey preview is being change with work done for webforms, this issue will be solved here: https://github.com/akvo/akvo-flow/issues/1347
