### ISSUE TITLE
MINOR UI - Translation labels

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#482]
On the survery assignment screen, when using French translations, there is a UI issue caused by the longer strings which end up overlapping:

![frenchtranslation](https://f.cloud.github.com/assets/3003031/2471154/f57a3226-b01f-11e3-8763-058677beaffa.png)

**Comment by janagombitova** [comment]
This issue currently occurs only in the cases where the browser screen is very small. Closing the issue and if it will be requested to fix by users then we will reopen again
