### ISSUE TITLE
'Other' option in survey doesn't appear in the preview

### ISSUE THREAD

**Issue by CharlotteSoed** [akvo/akvo-flow#486]
When selecting the 'Other' option in a survey question, it doesn't appear in the Preview functionality of the dashboard. 

Instance: gnwp.akvoflow.org
Survey id 190918
Question group 2, question 5

**Comment by jonase** [comment]
## Test plan

* Create two questions with "Option" type
  * One should "Allow Other" and the other one should not
* Check the question preview and make sure that only the question with "Allow Other" has the "Other" option as the last item in the list of options

**Comment by rumca** [comment]
Tested and works as intended on release/1.8.1 :+1:
