### ISSUE TITLE
Enable arbitrary survey downloads in monitored APK

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow#488]
At the moment, we can only send surveys to the app through assignments, because of the security implications to sync those groups.

In order to allow users to keep downloading surveys without assignments, we need to
* Add the survey group information to the survey XML definition
* Disallow the download of monitored groups' surveys (the app will handle this)

**Comment by mtwestra** [comment]
This has been implemented in a slightly different way: the manual download is still possible as it was overly restrictive.
