### ISSUE TITLE
Code cleanup - Remove unused Map related code

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#498]
The new maps code (clustering) have introduced several changes which deprecate some code, e.g:
- List of countries in env.js (EnvServlet)
- Local variables in JavaScript functions (Dashboard code)
- Others

As a second iteration we need to clean up this code.

Releated: #363

**Comment by muloem** [comment]
# Test Plan 

1. Dashboard public and private should load and display correctly

**Comment by janagombitova** [comment]
After the fix from @stellanl I can confirm all pages load as they should 👍
