### ISSUE TITLE
Dependencies missing when exporting survey format to spreadsheet when questions belong to different groups

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#546]
Steps:
1. Create a question group G1
2. Add an option question to this group , say Q1
3. Add another question (Q2) to G1 and make it dependant on Q1.
4. Add another group G2
5. Add a question(Q3) to G2 and make it dependant on Q1.
6. Now go to Export reports and export the survey form

Current behaviour:
The dependancy of Q2 on Q1 is properly displayed but the dependancy of Q3 on Q1 is not displayed.

This issue was reported in the support portal
http://flowhelp.akvo.org/discussions/problems/699-exporting-survey-to-excel

**Comment by mtwestra** [comment]
probably duplicate of https://github.com/akvo/akvo-flow/issues/370

**Comment by jonase** [comment]
This issue is related to #370. Note that I can not reproduce this exact issue. The dependancy note does appear even if the questions are in different question groups

**Comment by rumca** [comment]
Tested and works as intended on release/1.8.1 :+1:
