### ISSUE TITLE
Issue with charts generation

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#547]
Steps:

1. Create a survey that has multiple "options" questions.

2. Collect responses for this survey such that one particular question is 
always unanswered in all responses.

3. Go to the charts tab and select that question.

4. We get a message saying "There is no data available for this question. 
Please select another one.", as expected.

5. Now select a question that does have responses.

 

Issue:

We get a message "Choose a Question from above selectors." even though there 
are responses.

Click on "Build chart" again and the expected chart is displayed.

This issue was reported in the support portal
http://flowhelp.akvo.org/discussions/problems/620-issue-with-charts

**Comment by janagombitova** [comment]
The behaviour has slightly changed since and this can be resolved together with https://github.com/akvo/akvo-flow/issues/1414 thus closing
