### ISSUE TITLE
Check way deviceSurveyJobQueue objects are retrieved

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#552]
Observation: Sometimes, partners report that survey assignments don't seem to work, and the resort to manual downloading of surveys. However, this has the disadvantage of not handling survey updates.

A possible cause for this behaviours is the way deviceSurveyJobQueue objects are retrieved. In the getSurveyForPhone method in the org.waterforpeople.mapping.app.web.SurveyManagerServlet class, on line 83, we retrieve deviceSurveyJobQueue objects using dsjqDAO.get(devicePhoneNumber, imei).

Looking at com.gallatinsystems.survey.dao.get(String devicePhoneNumber, String imei), this tries to find the deviceSurveyJobQueue by imei and phoneNumber.

However, when I look at the deviceSurveyJobQueue entities, there is quite some variability in how the phoneNumber and imei fields are populated. Sometimes the phonenumber field holds the macAddress, and the imei field holds the imei, sometimes the imei value is in the phoneNumber field, and the imei value is null, sometimes the phoneNumber and imei fields have the same value.

Further variability comes from the fact that sometimes the macAdress is stored in capitals, sometimes in lowercase.

I think that this might be the cause for the observation that sometimes survey assignments don't seem to work, because when we search, we assume that the phoneNumber and imei fields are the ones that are reported by the phone. But what the phone reports could be dependend on if wifi is on, for example.

Possible solution:
Perhaps in searching for deviceSurveyJobQueue entities, we can have a smarter way of searching, in which either the phone number or the imei fields match to either values supplied by the phone.

**Comment by akvotender** [comment]
DNH Mali saw surveys double, probably of double assignments. After deleting the assignment the survey is still being synced.
