### ISSUE TITLE
Map cluster does not update cluster on Geo data point update

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#553]
If you update the values of the `META_GEO` question on a monitoring _data point_, the Map cluster does not get updated, and still shows the point in the previous known location.

### Steps:
* Create a new data point, with a know location (easier to check for a location where the cluster only has 1 point)
* Check the Map and verify that the point is there
* Update the geolocation of the same data point to a far away location
* Check that the map doesn't reflect the data point update

Related to #276

**Comment by janagombitova** [comment]
as we are moving towards Carto maps and will not support this implementation anymore - I am closing this issue
