### ISSUE TITLE
Data point only display the last survey instance

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#554]
When you click monitored _data point_ on a Map, it only display the last collected survey instance.

### Steps
* On a monitored group, click a data point
* Verify that only the last collected survey instance is shown in the details

Related #276

**Comment by janagombitova** [comment]
In Carto maps the users start working with maps first by selecting which survey > form submissions he wants shown on the map. Thus he decides whether he wants the registration form or monitoring forms. If a point has multiple submissions for one monitoring form, then we need to look at this problem from a UX perspective as well. I am moving this question to product design https://github.com/akvo/akvo-product-design/issues/185
