### ISSUE TITLE
Legacy Code Cleanup

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#555]
Legacy code cleanup that is not attached to any particular feature/implementation should be monitored via this issue.

**Comment by stellanl** [comment]
Marked the [gs]etSublevel[1-6] methods of SurveyedLocale as @deprecated as part of #1759

**Comment by muloem** [comment]
## Things to refactor/cleanup
* [ ] Remove unused/unnecessary jar libraries
* [ ] Standardise the logging library used (#1933)

**Comment by janagombitova** [comment]
@muloem I assume, that if Flow works with all regression tests, then we can consider all the changes here successful, correct? If so, then all works as expected 

How do you want to go about the check boxes in your comment above?

**Comment by muloem** [comment]
Exactly most of the issues here should be covered by regression tests and its usually code that is not even executed.  We may have to use different issues to keep better track of code cleanup. and only use this issue to track the cleanup overall.

**Comment by janagombitova** [comment]
👍  sounds like a plan. Or we can create an issue in the product design repository to track the clean up tasks and issue in flow to link the code changes. But as far as the changes go, Flow works fine

**Comment by muloem** [comment]
## Test Plan

Any broken issues should be identified in regression testing

**Comment by janagombitova** [comment]
Nothing found in regression round. We are good to go 👍

**Comment by muloem** [comment]
I'll leave this open for now but create separate issues per code cleanup.
