### ISSUE TITLE
Cluster re-computation fails on missing geocells property on SurveyedLocale

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#556]
If a SurveyedLocale doesn't have `latiude|longitude` attribute, no `geocells` can be calculated, leading to a `NullPointerException` when trying to use the latter mentioned property.

Side note: The computation should be made using a backend

**Comment by janagombitova** [comment]
@mulo is this still relevant?

**Comment by janagombitova** [comment]
Closing this issue as we no longer use clustering of data points. It can always be opened if I misunderstood the problem and the issue is still relevant
