### ISSUE TITLE
Page refresh after data deleted to update map

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#563]
In order for the cluster count to update correctly after we delete some data from the data tab, we must first refresh the page. This is because the map will use the cached cluster values otherwise.

It might be an idea to clear the local cache whilst navigating between tabs? Or if possible, kill it only when the map tab is loaded?

**Comment by janagombitova** [comment]
We are moving away from this map implementation and map clusters and will not be fixing this issue. We will look at how to handle caching once we make progress with the refactor
