### ISSUE TITLE
Resubmitting survey responses results in the cluster count being incremented incorrectly

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#564]
I noticed an issue whereby resubmitting a response from a device which was previously deleted in the dashboard results in a few random issues. Occasionally the cluster count is incremented incorrectly or else the cluster zoom level is a problem (for example some clusters don't appear at the top zoom level, but appear once you zoom a few times). The errors seem to be rather inconsistent (some times it's the increment and some times it's the zoom level. However these are the steps I've been using:

* Submit some data to form a new cluster
* Delete one or more of the responses
* Resubmit this data from the phone/bulk upload

**Comment by janagombitova** [comment]
We are moving away from map clusters and will not be fixing this issue
