### ISSUE TITLE
Date question type not appearing correctly on map questions

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#571]
![datestringwrong](https://cloud.githubusercontent.com/assets/3003031/3171122/25e4fcec-ebc2-11e3-83e6-da45dba1218e.PNG)

The date field on the maps is not being formatted correctly on the maps. It's still a proper date on the data tab, however is a long on the map questions.

**Comment by akvotender** [comment]
Assigned to [Tender discussion #5740](http://flowhelp.akvo.org/discussions/problems/5740-dates).

**Comment by janagombitova** [comment]
@muloem @jonase Is this still an issue?

**Comment by rumca** [comment]
There's still an issue here, but not quite the original one. Just submitted a response for an old survey and it appears as below on the map:

![screen shot 2015-09-30 at 09 44 38](https://cloud.githubusercontent.com/assets/3003031/10188554/130ffe24-6758-11e5-96f3-bbc832caa3ce.png)
![screen shot 2015-09-30 at 09 44 47](https://cloud.githubusercontent.com/assets/3003031/10188568/20d9988a-6758-11e5-8450-1835fe977a3b.png)

There's a few weird things going on:
* Date field is null
* Cascade field is null
* Cascade field is null
* None of the "New question - please change name" questions are actually present on the survey definition so not sure why they're present here

**Comment by muloem** [comment]
@jonase @kymni the issue of the newly created questions is probably one to look into. i.e how are we querying for responses in CartoDB.

**Comment by rumca** [comment]
@muloem @jonase @janagombitova shows what I get for assuming they were the same! When I change the map provider back to mapbox the following is displayed:

![screen shot 2015-09-30 at 10 28 38](https://cloud.githubusercontent.com/assets/3003031/10189470/273db9d0-675e-11e5-987a-4ac79027f119.png)

None of the issues listed above are present with mapbox. **However** the original date problem discussed in this issue is still present.

**Comment by muloem** [comment]
### Test Plan

1. Create a survey with a couple of questions one of them has to be a `DATE` question and another has to be a `GEO` question

2. Fill in a couple of responses and submit. 

3. Cross check that on the map tab the dates are rendered correctly for these data points

**Comment by rumca** [comment]
Test plan passes as described for mapbox maps.

@kymni @jonase there's still an issue displaying date questions with cartodb, should I open a separate issue for that?

**Comment by jonase** [comment]
@rumca yes, thanks!
