### ISSUE TITLE
Invalidate report cache after manual data cleaning in dashboard

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#574]
Current behaviour:
1) upload data and export a raw data report
2) change the data through the data tab on the dashboard
3) re-export the raw data report
4) the raw data export will not reflect the latest changes

Expected behaviour:
When data is changed on the dashboard the cached raw data report should be invalidated.

**Comment by janagombitova** [comment]
This issue no longer exists. I exported the data, changed the answers via Inspect data and generated the export again. The export was sent to my email with a new file that reflected the changes.
