### ISSUE TITLE
Cluster count is not accurate on point-updates-v4 branch

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#579]
The Map clustering counts are not accurate. You can see the linked video.
On different zoom level, different counts are shown, and still those are not accurate.

https://www.dropbox.com/s/v9ct5pk9iwdy2t1/cluster-count.ogv

Development tip:
* When testing this issue, we should simulate HRD behavior (I have 50% of writes not visible to global queries)
* https://developers.google.com/appengine/docs/java/tools/devserver#Using_the_Datastore

![hrd-50](https://cloud.githubusercontent.com/assets/178474/3208926/525a7a44-ee4d-11e3-9a35-62dfb9dc0376.png)

**Comment by janagombitova** [comment]
As we are moving away from map clusters we will not invest time in fixing this issue.
