### ISSUE TITLE
Wrong data point details are displayed after submitting an updated survey form

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#586]
##### To reproduce this issue:
1. Create a data point via a registration form in a monitoring group with latitude/longitude details
2. Open the map as admin and verify the point exists
3. Zoom into the map till individual points are shown and click on the point.  The data point details are shown on the right side of the map.
4. Update the latitude/longitude details of the data point and submit the new form
5. Refresh the map and then repeat step 3. and verify that the same details are shown instead of updated details

Related to #276

**Comment by muloem** [comment]
@mtwestra this is related to mapping so should probably be closed right?

**Comment by janagombitova** [comment]
issue no longer exists
