### ISSUE TITLE
Strange behaviour of data on maps in akvoflow-39

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#604]
Steps to reproduce:
* Go to akvoflow-39, on the maps tab
* Zoom in to Port Villa in Vanuatu
* Click on one of the points in the map
* You will see the first questions of the list are either photos or locations, and are displayed with 'null' as the question text.
![screen shot 2014-06-12 at 14 35 26](https://cloud.githubusercontent.com/assets/478954/3257617/cb006e10-f22e-11e3-94d1-18dc3c06f436.png)

**Comment by janagombitova** [comment]
checked the issue, and it is solved now. No more null values. Closing.
