### ISSUE TITLE
Device group name disappears after selecting 

### ISSUE THREAD

**Issue by JosjeS** [akvo/akvo-flow#620]
When you add a device to a device group on the dashboard the device group name quickly pops up behind the device and then disappears. 

It only show up after you have left the 'device tab' and went back again or if you click on the 'device' tab on the dashboard again. 

(This happens on every dashboard with every device)

**Comment by janagombitova** [comment]
Duplicated in this issue https://github.com/akvo/akvo-flow/issues/1691
