### ISSUE TITLE
Version number in exported report

### ISSUE THREAD

**Issue by JosjeS** [akvo/akvo-flow#621]
It would be nice if when you export a report of a survey in the raw data report the version of the survey that is used is shown. 

Use case scenario: 
A partner has version 2 of a survey and sends this to the phones. 
After that data is being collected, but the dashboard manager realises that there needs to be a few changes in the formulation, edits it and publishes version 3. 
Some of the enumerators have Wifi during the data collection others don't. 
It would then be very useful for the dashboard manager to see which surveys were filled in with version 2 and which with the use of version 3.

**Comment by jonase** [comment]
@mtwestra @JosjeS @muloem 
After consulting with @iperdomo solving this is not currently possible. We don't have sufficient information to get the survey version used for a specific answer.
