### ISSUE TITLE
Is changing lat/lon on the dashboard handled correctly re clusters?

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#638]
In one of the instances, a lot of points have a wrong latitude / longitude. the easiest way to remedy this would be to edit the lat/lon values in the dashboard. However, the question is if these edits will be handled correctly:

1. an edit on the dashboard leads to the correct value in the questionAnswer object
2. an edit on the dashboard leads to the correct value in the surveyedLocale object
3. an edit on the dashboard leads to the correct recomputation of clusters

**Comment by janagombitova** [comment]
Closing this issue for now as there were no requests regarding such a change in the last year and adding it to the opportunity backlog. Users tend to clean up their lat long information via data cleaning
