### ISSUE TITLE
Recompute Cluster Behaviour With Erroneous Data

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#644]
@mtwestra @iperdomo @muloem apologies for the long winded issue, just trying to record anything that might prove a problem down the line.

## Cluster Error Types

After several rounds of testing cluster creation etc on the UAT environment there a few cases of clear erroneous cluster data on the map. The cluster errors mainly fall into two categories:

* **A** Points which have a cluster count of 2 or more but which often resolve to just one data point when you zoom all the way in (and I have checked to make sure that there are not multiple responses with the exact same GPS co-ordinates). For example this cluster

![clustercount2](https://cloud.githubusercontent.com/assets/3003031/3528003/cad7a446-078a-11e4-81bf-c2deb6cd9c2f.PNG)

resolves to only one data point

![clustercount2resolvesto1](https://cloud.githubusercontent.com/assets/3003031/3528011/e19c2828-078a-11e4-8882-6eb59178ce25.PNG)

* **B** Clusters which have a cluster count that increases whenever the user zooms in on them. For example this cluster of 8

![clustercounthighalowzoom](https://cloud.githubusercontent.com/assets/3003031/3528028/1284691e-078b-11e4-9f25-29fcdc51473f.PNG)

which resolves to 15 points on zooming in

![clustercounthigherathighzoom](https://cloud.githubusercontent.com/assets/3003031/3528030/1b35e164-078b-11e4-8eaa-52f413ecc87b.PNG)

## Attempted Solutions

 I have tried to "reset" the clusters on UAT to remove this erroneous behaviour in two different ways.

---

First of all I tried using the FLOW dashboard and deleting all associated data from the data tab, checking to make sure that the map was empty as I'd expected and then resubmitting the data from the device/bulk uploader.

This successfully resets (ie removes data as expected) the map for errors of type B, however with errors of type A - there are clusters left behind which have no associated responses in the dashboard. For example where an incorrect cluster of size two might have existed before (which resolves to a singular response), when you remove all the data in the data tab - the cluster count is decreased to one, however now instead of there being a valid response left there are points which have "no details" left:

![nodetailcluster](https://cloud.githubusercontent.com/assets/3003031/3528218/10a7aeec-078d-11e4-9a0b-781c3232ac9e.PNG)

With both problem cluster types though, once the data has been resubmitted then the same issues are re-encountered.

---

Secondly I have tried the more brute force approach of directly removing all Surveyed Locale Cluster types in the app enginge dashboard:

![deletedsurveyedlocalecluster](https://cloud.githubusercontent.com/assets/3003031/3528135/12e715cc-078c-11e4-8035-f65c36275a40.PNG)

Then flushing the cache also, and checking that the map appears blank as expected:

![emptymap](https://cloud.githubusercontent.com/assets/3003031/3528140/252f2bc0-078c-11e4-89a5-80d1d03ecae3.PNG)

Then kicking off the Recompute Clusters call on the test harness (/webapp/testharness?action=recomputeLocaleClusters) to repopulate the map with clusters. After the recompute action has completed, everything re-appears as expected however the erroneous data has also returned - both type A and type B.

---

This could be a complete non-issue, new clusters seem to work fine - it's just the old data from previous rounds of testing that is broken.

**Comment by janagombitova** [comment]
Will be solved with CartoDB integration
