### ISSUE TITLE
Charts - "Smallest Items" on doughnut chart

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#645]
I'm not sure if this is actually an issue or not, maybe it's just a case of user error, but I can't recall ever seeing the "smallest items" section on the doughnut chart ever being populated with anything:

![chartsmallestitem](https://cloud.githubusercontent.com/assets/3003031/3531067/76e75144-07ab-11e4-8c0c-b37470bce113.PNG)

If it's no longer used, then it could be an idea to get rid of it when you're working on the charts @muloem ? Please disregard if I'm just not using the functionality correctly :smile:

**Comment by janagombitova** [comment]
not a relevant issue anymore, as the functionality works as intended.
