### ISSUE TITLE
Minor UI Issue - Interaction between back to survey group and Monitoring Features label

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#646]
**Note that if you refresh the page, or click to another tab and then return - the drop down reappears as normal**

I noticed a minor issue with the monitoring features dashboard. When you go to a survey group which has had monitoring enabled, and the drop down is visible:

![monitoringenabled](https://cloud.githubusercontent.com/assets/3003031/3531134/3e175282-07ac-11e4-94b4-f47628660b53.PNG)

If you then click to edit a survey or create a new survey, after which you click "go back to survey overview" the label reverts to the "make monitor group" label:

![monitoringshouldbeenabled](https://cloud.githubusercontent.com/assets/3003031/3531159/86ccd93e-07ac-11e4-9e44-d6054e4c5321.PNG)

I assume this is related to #641 #625

**Comment by muloem** [comment]
This may no longer be relevant as we have moved to a different UI. Closing.
