### ISSUE TITLE
Minor UI Issue - Visiting Monitoring Tab and then Data Cleaning results in incorrectly populated drop down

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#647]
When a user performs the following steps:

* Visits a dashboard which has monitored features enabled
* Creates a few monitored groups
* Goes to the "data" tab and then the "monitoring" sub tab
* Returns to the "data cleaning" sub tab

The drop down list on the "data cleaning" sub tab is only populated with the monitored groups, and not a complete list of every group on the dashboard as expected. When the user clicks away from the "data" tab and then back to the "data cleaning" sub tab the list is populated as normal (provided they don't first visit the monitoring tab).

Related to #629 in that the list on the monitoring tab is overriding the complete list. I think this could well be a non-issue though as there's no use case for a dashboard which has both monitored groups and non monitored groups?

**Comment by muloem** [comment]
The drop down list is reimplemented differently in #1053.
