### ISSUE TITLE
Monitoring Features Dashboard - Response identifiers in reports question

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#649]
I'm not really sure if this is an issue or not - more of a question! When I was testing this latest release it was always with the 1.13 series of the APK and not the new 1.15 series so that could explain this discrepancy.

When a user performs the following:

* enables monitoring featues
* creates a monitored group and some surveys
* assigns them to a 1.13 apk user
* submits data as usual
* visits the dashboard again, and goes to the "monitoring" sub-tab

We see a screen such as this: 

![monitoringtabindentifier](https://cloud.githubusercontent.com/assets/3003031/3531586/60c30a4c-07b1-11e4-8fd8-8359f7dbec01.PNG)

However when you then export a report using one of these surveys, you'll get something such as this:

![monitoringreportnoindentifier](https://cloud.githubusercontent.com/assets/3003031/3531620/b862a816-07b1-11e4-8314-b37294ab94cd.PNG)

I'm assuming if I used the new APK then this identifier column would be correctly populated in the raw data report - however thought it was slightly strange that it was populated on the "monitoring" sub tab and not the report.

**Comment by janagombitova** [comment]
closing this issue as the 1.13 apk is not used so much anymore. If we receive a request about it again, we can recreate it.
