### ISSUE TITLE
Data summarisation double counts question responses

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#682]
Data summarisation counts responses from `OPTION` type questions.  At the moment there are two kinds of `OPTION` questions; multiple selection and mutually exclusive options.  The data summarisation does not distinguish between these two and counts multiple selection questions that results in wrong data aggregation values.

To reproduce:

1. Create a sample survey with two `OPTION` type questions

2. The first option question should have *Allow multiple* checked and the second should not

3. Fill in sample responses on a device and make sure the question that allows multiple selection has multiple options selected

4. Go to the chart builder and compare the results from the two questions

The screenshots below illustrate how data is miscounted.

Question **without** multiple selection (6 responses; shows 6 answers)

![question_options_without_multiple_selection](https://cloud.githubusercontent.com/assets/533336/3616537/31966a7e-0dd4-11e4-9d25-8eadeccff8e0.png)

Question **with** multiple selection enabled (6 responses; shows 12 answers)

![question_options_with_multiple_selection](https://cloud.githubusercontent.com/assets/533336/3616544/551130ba-0dd4-11e4-9cea-bdccca6ca360.png)

**Comment by janagombitova** [comment]
This issue is duplicated here https://github.com/akvo/akvo-flow/issues/1414
