### ISSUE TITLE
Add display and filter of locale Id on survey instances

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#705]
In the inspect data tab, we show all the forms that have been filled in. We don't show the data point id at the moment.

Use cases where this is important: 
* people that want to delete all filled forms for a certain data point
* people that want to find a specific form in a specific data point and edit the data (should be possible perhaps in the monitoring tab, but that is very limited at the moment)

**Comment by janagombitova** [comment]
Will be fixed as part of the changes introduced with webforms. Closing this issue
