### ISSUE TITLE
Minor Regression - Copying a Survey no long results in the copy appearing in the group

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#719]
This is a pretty minor regression - so feel free to ignore if there are more pressing concerns.

Previously when a user selected a survey to copy and copied to the same survey group - they would see the popup informing them about checking the messages, but the copied survey would also instantly appear in the viewport (you couldn't interact with this survey until the copying had completed though). Now when a survey is copied, the copied version does not instantly appear and a refresh of the page is required.

**Comment by joycarpediem** [comment]
After the Survey UI redesign, this issue does not exist anymore.
