### ISSUE TITLE
Removing monitored group responses should update the map clusters/points

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#720]
Similar to #523 

When I remove all monitored responses on the data tab in UAT - there are still points left on the map (which have no attached data to them so GAE throws an exception trying to fetch info when you click on the points):

![mapupdate](https://cloud.githubusercontent.com/assets/3003031/3912723/013f85c6-232e-11e4-97d6-88a84996090d.JPG)

Exception is:

`W 2014-08-13 14:07:28.249 com.gallatinsystems.framework.dao.BaseDAO getByKey: No com.gallatinsystems.surveyal.domain.SurveyedLocale found with id: 4679129`
`E 2014-08-13 14:07:28.249 org.waterforpeople.mapping.app.web.rest.PlacemarkDetailsRestService getDetails: placemarkId : 4679129 not found`

**Comment by janagombitova** [comment]
Will be dealt with once we move maps to Carto and then Windshaft. Because we are moving away from this map implementation we will not invest time in fixing this
