### ISSUE TITLE
deleteSurveyInstance tries too many things and fails in the attempt

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#730]
The method `deleteSurveyInstance` from `SurveyInstanceDAO` tries to have a synchronous execution and control too many things that fails with a relatively _small_ dataset (~1K SurveyInstances). This makes the attempt to clearing out the data related to a particular `Survey` a real pain.

**Comment by muloem** [comment]
### Test Plan

**Pretest prep:**
Identify or create existing data/response for a survey.  The survey should  comprise a `GEO` question and an `OPTION` type question. 

**Test Execution:**
1.  Select one of the responses under the data tab and note the response values for the geo location and the option question. Under the reports tab, generate a chart for the option question and note the total responses indicated, as well as the percentage of the total response corresponding to the specific option noted earlier.  Under the maps tab try to identify the point and/or cluster under which the responses noted earlier falls.

2. Go back to the data tab and delete the response

**Expected:**

* Under the reports tab, the total values shown by the chart of the option question should be updated correctly (i.e. one less).  Also the percentage for the specific option value should be recomputed appropriately.

* Under the map, the clusters that are close to the identified point should have been updated to indicate that a point has been removed.

**Comment by rumca** [comment]
The above test plan passes - clustering needs a page refresh to update correctly but this is expected :+1:
