### ISSUE TITLE
Check the quality of counts management

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#741]
The system keeps a running statistics count of answers. Because there are multiple ways the data can change, we need to stress test the system using the different pathways of data change. 

Test plan:
1. create a survey with some 3 different option questions, at least one of which has an 'other' field, and at least one of which has 'multiple allowed'
2. collect data (~10) with this app with the phone online, and check counts (QuestionAnswerSummary objects).
3. collect data (~10) with this app with the phone offline, then go online and let the phone send data, and check counts
4. modify data on the dashboard, and check counts
5. export the data to excel, make changes to the data, and upload again. Check counts
6. create a lot of extra data (~2000 rows) in excel by adding extra rows, and upload. check counts
7. collect data on the phone in offline mode, and use bulk upload to upload. If you want, you can create extra fake data in the data.txt file, so as to stress the system extra. Check counts.
8. delete data using the deleteSurveyResponses test harness. Check counts.

If in between tests the counts fail, you can recompute the counts first (using the testharness rebuildQuestionSummary method) and continue with another step, so we can identify where the problem is.

**Comment by janagombitova** [comment]
Closing down this issue https://github.com/akvo/akvo-flow/issues/1414
