### ISSUE TITLE
Cluster disappears when zooming in

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-flow#742]
If I try to zoom in at the 11 data points gathered in Mali at  http://dwa.akvoflow.org/admin/, the cluster with 11 disappears (see screenshot) if I zoom in more than 9 times. As a result I can't click on the data points to find out what questions belong to that datapoint. 
Tried to zoom in at other data point clusters in other countries at the same dashboard, but don't face this problem. 

Using Safari 7.0.6

![screen shot 2014-08-26 at 13 25 31](https://cloud.githubusercontent.com/assets/4179989/4043583/c256d964-2d13-11e4-8113-341995b4f534.png)

**Comment by janagombitova** [comment]
Will be solved with CartoDB integration.
