### ISSUE TITLE
Registration survey drop down disappears

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#795]
Execute the following sequence on an instance with monitoring features enabled:

1. Select a survey group. (Observe that the drop down showing selection of the *registration survey* is shown.

2. Select *Edit* for a survey

3. Immediately select *Go back to Survey Group*

4. The *Registration survey* drop down is not shown.

5. Wait for a few seconds. The survey preview window opens.

**Comment by joycarpediem** [comment]
@muloem , don't think this is an issue post re-design. Can you please verify and close if working as expected

**Comment by muloem** [comment]
@joycarpediem correct. Closing this one.
