### ISSUE TITLE
Data Cleaning - Geolocation information robustness

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#806]
@iperdomo I'm not sure if this one is worth the time to address since I think everyone is aware of the situation, but thought I would log the issue here just to keep a track of it. Could you close/assign if necessary?

When performing data cleaning, if a column is moved and mistakenly placed in amongst the geolocation information then this results in some of that being overriden. For example I uploaded the following file:

![datatobecleaned](https://cloud.githubusercontent.com/assets/3003031/4408372/f466d46e-44d2-11e4-9d36-de8eebab22ee.JPG)

Which once reuploaded and then redownloaded appears as follows:

![cleaneddata](https://cloud.githubusercontent.com/assets/3003031/4408377/012f6972-44d3-11e4-9ccc-56a0d9cb1dfa.JPG)

**Comment by janagombitova** [comment]
recreated this issue in Flow services repo https://github.com/akvo/akvo-flow-services/issues/145
