### ISSUE TITLE
Monitoring Tab - forms belonging to a singular data point being split into multiple parts

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#808]
I'm not really sure what has caused this, but during the last round of testing I noticed the following problem with the Monitoring sub tab under the Data tab:

![mfsamepointtwiceafterbulkupload](https://cloud.githubusercontent.com/assets/3003031/4408513/95949212-44d4-11e4-8c36-d46de9dd61af.JPG)
 
(i.e. forms which belong to the same data point have been split in such a way which makes them look like separate data points)

**Comment by muloem** [comment]
Closing this. It is the same as and shall be fixed by #1282
