### ISSUE TITLE
Minor UI Regressions - Missing images, spacing on edit survey screen, layout on inspect data

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#809]
@loicsans @jonase I'm not sure if a few of these problems have resulted from the CSS changes we made or something else. 

A few of the minor icons have gone missing. For example on the edit survey screen, the roll over version of preview survey is missing: /admin/images/IconPreviewOrange.svg

Other missing icons include:

![missingicons](https://cloud.githubusercontent.com/assets/3003031/4408687/2033227a-44d6-11e4-921b-8cc29ec3c3b2.JPG)

I assume we just need to correct one thing and it'll fix all of these problems?

More small layout issues:

-----------------------------------------------------------------------------------------------------------------------

Minor regression on the inspect data popup view. It used to look like:

![inspectprevious](https://cloud.githubusercontent.com/assets/3003031/4408718/7892f85a-44d6-11e4-8f2a-dda3d3fc6b55.JPG)

but now the layout has changed and the previous next stuff is very cramped in the corner:

![inspectnew](https://cloud.githubusercontent.com/assets/3003031/4408721/7c819386-44d6-11e4-82e5-337134d2014e.JPG)

-----------------------------------------------------------------------------------------------------------------------

Also the spacing for the preview, save and publish icons doesn't seem quite right (really really minor but preview seems too far over):

![spacingnew](https://cloud.githubusercontent.com/assets/3003031/4408766/d88e5254-44d6-11e4-9b7a-53c074ad1686.JPG)

**Comment by joycarpediem** [comment]
@gabemart , can you verify that all the issues mentioned here were fixed as part of #1294 ? If yes, then we can add this to the fixed list

**Comment by gabemart** [comment]
@joycarpediem No, there are still issues with some assets not appearing.

E.g. on Create Survey > Add Form > Manage Notifications the "Expires" field does not correctly show the calendar arrow icons, as mentioned in #1245 

The assets 404. e.g.

http://akvoflowsandbox.appspot.com/admin/css/custom-theme/images/ui-bg_highlight-hard_75_dadada_1x100.png

http://akvoflowsandbox.appspot.com/admin/css/custom-theme/images/ui-icons_222222_256x240.png

http://akvoflowsandbox.appspot.com/admin/css/custom-theme/images/ui-bg_flat_75_cccccc_40x100.png

http://akvoflowsandbox.appspot.com/admin/css/custom-theme/images/ui-bg_highlight-hard_55_fbf9ee_1x100.png

Without a dev environment set up I'm not sure how to investigate further

**Comment by gabemart** [comment]
All requests for files in  `/admin/css/custom-theme/images/` are returning a 404, including requests for the directory itself (where we would expect a 403). Requests for `/admin/css/custom-theme/' and `/admin/css/custom-theme/jquery-ui-1.8.21.custom.css' return correctly. File permissions for `/admin/css/custom-theme/images/` look correct (`drwxr-xr-x`).

Perhaps this is a routing problem?

The last pertinent commit looks to be https://github.com/akvo/akvo-flow/commit/3698715ceaa94519337fe851d543d92a25820fdf

**Comment by gabemart** [comment]
### Test plan

1) navigate to each file in the list and verify the server returns a 200 response

* /admin/css/custom-theme/images/ui-bg_flat_15_f7f3de_40x100.png
* /admin/css/custom-theme/images/ui-icons_cd0a0a_256x240.png
* /admin/css/custom-theme/images/ui-icons_454545_256x240.png
* /admin/css/custom-theme/images/ui-bg_highlight-hard_75_dadada_1x100.png

2) Navigate to the Data > Inspect Data tab

3) Click on the "Collected from" input

4) On the date entry field that appears, verify that an arrow icon appears to the left and right of the month display, allowing the user to change the month

**Comment by rumca** [comment]
reopening this just to remind myself to test everything - will close again once I've done so

**Comment by rumca** [comment]
@gabemart looks good :+1: there's one other icon 404ing:

http://uat1.akvoflow.org/admin/images/icon_cal.png 

could we quickly fix this as part of this issue? I'll just open another minor UI fixes issue for the next release if not.

**Comment by gabemart** [comment]
@rumca I caught that too, but I'm not sure if the icon is actually needed any more or not. I created an issue for it and assigned it to @loicsans - https://github.com/akvo/akvo-flow/issues/1376
