### ISSUE TITLE
Recompute data point names on publishing of project if necessary

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#821]
At the moment, when people want to use existing data for monitoring, they need us to run a task on the testharness to populate the display name of the data points. This is a hassle.

Proposed solution:
1) introduce a boolean flag displayNameStale, which signifies if the display names of the data points are up to date or not (stale).
2) When a user changes the setting 'use as data point name', either enabling or disabling it, we change this flag to 'true'
3) When a user publishes the project, we check this flag and if it is true, we fire a task to repopulate the display names.

**Comment by janagombitova** [comment]
This issue should be solved with the fix introduced here https://github.com/akvo/akvo-flow/issues/1576 Closing this issue
