### ISSUE TITLE
Copying Survey groups

### ISSUE THREAD

**Issue by JosjeS** [akvo/akvo-flow#822]
Hi All, 

I know it is not possible to copy survey groups from one survey to another, but a partner tried this and encountered an error. And it is confusing because in the first steps (see steps below) it seems like it is possible to copy a group from one survey to another. I showed it to Emmanuel and he requested me to put it in Github.

I tested this on the training dashboard, survey group: Josje_Demo 
Browser: Firefox 32.0.3

Steps:
1. Go into survey Amsterdam
2. Click on Copy Group 1 Location 
3. Click on 'Go back to survey overview' (Screenshot one)
4. Then go into the 'Healt demo Kit survey' by clicking on edit 
5. Then say Paste group here (Screenshot two)
6. The survey group will not be copied into the other survey, but when you go back to the orgiginal survey (Amsterdam) it will be pasted there (Screenshot three). And as you can see there are now two groups called 'Group 1 location'

If you need further information feel free to contact me. 

Best regards, 
Josje

![srceenshot one](https://cloud.githubusercontent.com/assets/4329924/4473229/92e6c33e-4950-11e4-9947-fa58b02c22f3.png)
![screenshot two](https://cloud.githubusercontent.com/assets/4329924/4473291/49ddeeaa-4951-11e4-927c-1dfd6f43f45e.png)
![screenshot three](https://cloud.githubusercontent.com/assets/4329924/4473231/95e7784e-4950-11e4-9788-f5ee13436e23.png)

**Comment by janagombitova** [comment]
Fixed in 1.9.4 release
