### ISSUE TITLE
Show devices in alphabetical order in assignment screen

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#834]
In the assignment tab, at the moment the list of devices is shown in some unknown order. It would make sense to show them in alphabetical order.

**Comment by mtwestra** [comment]
Test plan:
1) on a test instance which has numerous different devices, go to the assignment tab and create a new assignment
2) in the devices list, the devices should appear in alphabetical order.

**Comment by rumca** [comment]
the above test plan passes as described :+1:
