### ISSUE TITLE
Check for existing questionId should be case-insensitive

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#839]
When entering the `questionId` field of a question, we check whether there already exists a similar identifier in questions that are already saved.  This check is case-sensitive enabling one to enter strings like `question_id` and `question_ID` that are not the same from the computer perspective but are the same from a user's perspective. To avoid this confusion, we make the check case-insensitive

**Comment by stellanl** [comment]
If this issue is still alive, I estimate it would take me about 5 minutes of work.

**Comment by janagombitova** [comment]
Reading quickly the issue, so please correct me if I am wrong: Do we mean that we should **not** allow for variable names that are the same from a computer's perspective? 

Just checked, if the user has question 1 with variable name 'name' and question 2 with 'NAME' we allow it. As the variable names are used to be read by machines, this should not be allowed.

**Comment by stellanl** [comment]
Ok, fixing this.

**Comment by janagombitova** [comment]
Works like a charm 👍
