### ISSUE TITLE
Exported survey xml files should be saved as backup

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#841]
At the moment, we don't have any backup for surveys. It might be wise to save the xml files of surveys, as a sort of backup of survey versions.

One way to accomplish this might be to turn on versioning on S3.

**Comment by janagombitova** [comment]
@stellanl is this issue still relevant in light of the recent changes with saving every form version?

**Comment by muloem** [comment]
The form versions are now saved so we can close this one.
