### ISSUE TITLE
Change time format in questionId - exported reports to ISO 8601

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#846]
At the moment, we export dates in the raw data report in a custom format. 

The reports which use the questionIds as column headers is used for import to other systems. Therefore, it is important to have a standard format for the time. The proposal is to use ISO 8601, which gives times the following shape: 2014-10-08T20:27:16+00:00.

This will only apply to the raw reports that use the questionIds as column headers. The raw data report that is used for data cleaning can retain the current format.

**Comment by joycarpediem** [comment]
How about we add a time zone selector and print out the times is a much more "readable" format.

**Comment by janagombitova** [comment]
I agree, I think, in general, we need to allow the users to select if they want their reports to have a more "user friendly/readable" format of collected data or a raw data format. This can also then include the option for the user to decide whether they want the IDs to be part of the reports or not. Same with codes. 
These questions can be part of a Report Settings functionality.

**Comment by iperdomo** [comment]
@joycarpediem @janagombitova when using _question id_ as column header is **not** for users, is for integration with other systems. It shouldn't be a user friendly format, it should be a system _parseable_ format.

**Comment by janagombitova** [comment]
This issue is dealt with in https://github.com/akvo/akvo-flow/issues/257. Closing this one down
