### ISSUE TITLE
Expand notification possibilities

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#849]
At the moment, the following notifications are possible:
* every night
* survey submission
* survey approval

This should be restructured. 

To avoid generating reports too often, I would say that once a week, and once a month would be ok. Do we need any others? It seems a bit much to send a whole raw data report whenever a new point comes in. Perhaps a choice on the day of the week.

**Comment by janagombitova** [comment]
Notifications are a functionality that is not used at all by partners and we are currently looking into the opportunity of removing the feature fully. Closing this issue and the full discussion is in product design repository
