### ISSUE TITLE
Strange behaviour whilst editing question groups which have been copied within a survey

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#857]
ref: #435 

I've noticed some strange things happening when editing copied question groups - it's one of those annoying things where it doesn't happen consistently but I've seen the following happen at different times:

* Question order not computing correctly after questions from copied group have been deleted or moved: 

![screen shot 2014-10-15 at 18 28 09](https://cloud.githubusercontent.com/assets/3003031/4653367/45b73612-54ad-11e4-90ba-5081f882c59b.png)

* Dependency list drop down not being updated correctly (deleted stuff present, extra unexplained data present):

![screen shot 2014-10-15 at 18 36 32](https://cloud.githubusercontent.com/assets/3003031/4653388/5e0166e8-54ad-11e4-8592-c66597c3695a.png)

* Deleting a question, and then editing one of the other questions oftentimes results in a new question being added to the group for no apparent reason

* Editing a copied question update the original question also (I've only seen this once).

I think all of these errors are probably related, and the logs are filled with the following:
```
I 2014-10-15 20:38:19.141
org.waterforpeople.mapping.app.web.SurveyTaskServlet handleRequest: action: deleteQuestion id: 2989129
E 2014-10-15 20:38:19.454
com.gallatinsystems.framework.rest.AbstractRestApiServlet executeRequest: Could not execute rest request
javax.jdo.JDOUserException: Transient instances cant be deleted.
	at org.datanucleus.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:375)
	at org.datanucleus.jdo.JDOPersistenceManager.jdoDeletePersistent(JDOPersistenceManager.java:759)
	at org.datanucleus.jdo.JDOPersistenceManager.deletePersistent(JDOPersistenceManager.java:772)
	at com.gallatinsystems.framework.dao.BaseDAO.delete(BaseDAO.java:470)
	at com.gallatinsystems.survey.dao.QuestionDao.delete(QuestionDao.java:188)
	at com.gallatinsystems.survey.dao.QuestionDao.delete(QuestionDao.java:150)
```
which I think is a result of interactions with copied question group questions

**Comment by mtwestra** [comment]
Test plan 1.
1) create a form with two question groups.  In the first question group, create an option question. In the second question group, create another option question
2) in the second question group, create a question that is dependent on the option question in the first question group
3) in the second question group, create a question that is dependent on the option question in the second question group
4) copy the second question group
5) open the copied question group
6) the first dependent question should still be dependent on the question in the first question group
7) the second dependent question should now be dependent on the question in the copied question group.

**Comment by mtwestra** [comment]
Test plan 2 - testing UI behaviour during copying of question group
1) create a form with a question group containing a lot of questions (so copying will take a while)
2) click the 'copy' button on the question group
3) click the 'paste' button 
4) the new question group should display a 'copying' indicator, and the 'show questions' link should be disabled
5) when the copying indicator disappears, the 'show question' link should be active again
6) when the 'show question' link is clicked, the questions should be displayed (potentially after a small delay, as they might be still loading)

**Comment by rumca** [comment]
both the above test plans pass as described with release/1.8.4 :+1:
