### ISSUE TITLE
Allow selectable checkboxes for multiple select option questions

### ISSUE THREAD

**Issue by joycarpediem** [akvo/akvo-flow#864]
Currently the multiple selection questions are not editable in the edit data popup as the user just has a single-selection combo. 
So the user has to change the data via spreadsheet data cleaning for these questions which is not a preferred method.

We should replace the single-select combo with either a multiple select combo or better still a combo with checkboxes.
http://flowhelp.akvo.org/discussions/problems/2540-allow-selectable-checkboxes-for-multiple-select-option-questions

**Comment by gabemart** [comment]
@joycarpediem How does [this](http://gfycat.com/SatisfiedEagerHackee) look? Is it acceptable to just have a checkbox for every possible option, or do we need a scrollable list in case there are a very large number of options?

**Comment by joycarpediem** [comment]
This looks great with ease of selection. In case of large number of options, the rows is just going to expand, right ?

**Comment by gabemart** [comment]
Currently yes, the row will just expand and show every selection at once. 

Another option is to set a max-height on the row, so if there is a very large number of options they are displayed in a smaller box will a scroll bar.

[Video demo](http://gfycat.com/MelodicHonorableAbyssiniangroundhornbill)

This is a bit neater, but probably also a bit less intuitive.

Which option do you think we should go with? I'm leaning towards setting a max-height, but making it pretty big so it only applies if there are a very large number of options (e.g. more than 15 or so)

**Comment by gabemart** [comment]
Final styling: 
![screen shot 2015-08-21 at 09 42 32](https://cloud.githubusercontent.com/assets/2589977/9404655/420bca98-47e9-11e5-9967-85b6c0a04251.png)

**Comment by gabemart** [comment]
### Test Plan

1) Find or create a survey with an "Option" question with "Allow multiple" enabled

2) Edit the question such that there are 4 possible responses

3) Ensure there is at least one submitted response to this question

4) Navigate to the Data tab and select the survey and form from step 1 and select "Find"

5) Hit "Edit" on a response

6) Verify that any responses to the question are displayed with a "|" pipe separator with a space on either side, e.g. "1 | 2" 

7) Click on the response

8) Verify that the question options are displayed as a list of checkboxes

9) Verify that 4 response option checkboxes are displayed and there is no scrollbar

10) Change the selected options, hit "Save" and verify that the changes made are reflected in the displayed response

11) Go back to the Survey and form from step 1. Edit the number of possible options such that there are 15 possible options

12) Return to the Data tab, select a response, hit "Edit" and click the saved response

13) Verify that the option checkboxes are displayed with a vertical scrollbar, and that it is possible to scroll up and down and select responses

**Comment by rumca** [comment]
@gabemart are these changes supposed to be in the RC or not? I'm assuming they were reverted and then not merged back or something? Currently see the below on UAT with release/1.9.1

![screen shot 2015-10-01 at 00 32 06](https://cloud.githubusercontent.com/assets/3003031/10209512/1332ffe2-67d4-11e5-9e31-33e8061eeb90.png)

**Comment by muloem** [comment]
@rumca these changes were not merged due to some conflict with the new RQG branch. Will include in a later release.

**Comment by rumca** [comment]
@gabemart @muloem do these need merged to this RC or will it be the next one? Don't think I see the commits in release/1.9.3

**Comment by gabemart** [comment]
I am looking at the conflicts now, but some things do appear to have changed substantially in develop

**Comment by rumca** [comment]
@gabemart since it doesn't sound like it'll be straightforward I guess we can just leave it for the 1.9.4 release :+1:

**Comment by muloem** [comment]
This is fixed in #828 so closing this issue.
