### ISSUE TITLE
Check rendering FLOW dashboard in IE9

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#865]
The rendering of the FLOW dashboard in IE9 seems to have some issues, as indicated by the screenshots below. While IE8 is clearly out of bounds, many people still use IE9. We should check the functionality of this version.

![screen shot 2014-10-17 at 15 42 41](https://cloud.githubusercontent.com/assets/478954/4679662/c804a1ac-5603-11e4-9916-5866da24ac93.png)

**Comment by loicsans** [comment]
I believe, this can be closed?

**Comment by janagombitova** [comment]
We will deal with the more recent UI changes and how they render in IE in this issue: https://github.com/akvo/akvo-flow/issues/1678
