### ISSUE TITLE
Add filter on instance Id in data tab

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#872]
To facilitate finding data by surveyInstance Id, we should add a filter in the data tab on instanceId.

use case: In some cases, data cleaning is done by:
1) exporting the data in excel
2) find problems
3) locate the problematic data in the dashboard
4) edit it in the dashboard.

This way of data cleaning is less error-prone then the excel upload route. To facilitate this workflow, it is easier if the data can be filtered by id.

**Comment by janagombitova** [comment]
Currently in the Data tab > in Inspect data the user selects a folder > survey > form and can narrow down his view of collected data by defining:
- The time of data collection (Collected from + to), 
- Device ID
- Submitter name

![screen shot 2015-07-08 at 11 11 33](https://cloud.githubusercontent.com/assets/12456965/8566989/1ef4a68c-2562-11e5-8fa7-cf5a6cae6fd6.png)
   
What we need to do is add another search text box for Instance ID.

@loicsans, @Kiarii, @gabemart Can you provide a design for this change?

**Comment by Kiarii** [comment]
If the structure need not change, we can add a the "Instance ID" field or dropdown at the beginning or end of the bar with Device ID & Submitter name depending on the 'weight' that the Instance ID bears. We should also consider moving towards Submitter's name instead of SUBMITTER'S NAME; all capped text are harder to read than the alternative - e.g. http://www.designfiles.net/blog/reasons-avoid-caps-website-copy/

**Comment by janagombitova** [comment]
@Kiarii "Are you yelling at me?!" Love it. 

I like your proposal to adding the Instance ID in the same bar as the Device ID and Submitter's name. I would add it in the front, as it is also the first column in the raw data reports and the users actually use the instance ID from here. 
- First they export the collected data, find problems, check the instance ID from the raw data report and then come back to the dashboard to view and edit the collected data.

**Comment by jonase** [comment]
## Test plan

1. Go to the Inspect Data tab
2. Select a survey
3. Use the input box "Survey instance id" to find a specific instance for that survey

**Comment by rumca** [comment]
The above test plan passes as described :+1: 

However @jonase there's two minor things I've noticed with the release candidate which might be related to this issue:

* When a user initially clicks to search for responses (even without a filter) they see the following:

![screen shot 2015-07-23 at 00 25 50](https://cloud.githubusercontent.com/assets/3003031/8839847/c25dd51c-30d1-11e5-9f40-3c3694d54b91.png)

this subsequently disappears when the request returns, but it might be a bit misleading for users with a very slow connection?

* When a user deletes a response on the inspect data tab, the response is still displayed in the list (previously it was removed from the list after the deletion). This means we can still click to edit a deleted response, which results in the below:

![screen shot 2015-07-23 at 00 20 55](https://cloud.githubusercontent.com/assets/3003031/8839867/fd919948-30d1-11e5-99ab-0a16787a9860.png)
![screen shot 2015-07-23 at 00 21 04](https://cloud.githubusercontent.com/assets/3003031/8839868/0282bd24-30d2-11e5-81fd-518546f76520.png)

**Comment by jonase** [comment]
I don't think the second point is a new issue (but something that needs fixing) as I see the same behaviour on flowaglimmerofhope.

**Comment by rumca** [comment]
@jonase I just double checked on flowaglimmerofhope and didn't see the same behaviour - the deleted response was removed from the list straight away. I'm almost certain this was OK last release.

**Comment by rumca** [comment]
@jonase 'no results found' no longer appears (even for slow searches) :+1: 

should I add a new issue for the `null/null/null` pop up when deleting from the edit screen?

**Comment by jonase** [comment]
@rumca Yes, please create a separate issue for this.
