### ISSUE TITLE
Enable bulk barcode scanning

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#888]
implements https://github.com/akvo/akvo-product-design/issues/64

**Comment by akvotender** [comment]
Assigned to [Tender discussion #5676](http://flowhelp.akvo.org/help/discussions/problems/5676-testing-git-connection).

**Comment by akvotender** [comment]
Just testing Tender.

**Comment by akvotender** [comment]
Assigned to [Tender discussion #5676](http://flowhelp.akvo.org/discussions/problems/5676-testing-git-connection).

**Comment by akvotender** [comment]
*test* issue closed.
