### ISSUE TITLE
API documentation - surveys

### ISSUE THREAD

**Issue by JordenVerwer** [akvo/akvo-flow#910]
I'm trying to get the Akvo Flow API to work based on the documentation on this wiki. However, the wiki seems to be out of sync with the version I'm using right now. I've grouped the discrepancies by API endpoint. This one covers surveys.

- The fields "status" and "questionGroupList" aren't mentioned here, but they do show up in API responses.
- The field "sector" does not have a type.
- The field "sourceId" does not have a type.
- The field "instanceCount" does not have a type.

**Comment by janagombitova** [comment]
With refactoring Flow code we will be improving the API available to users and we need to make sure documentation will be properly updated as well. For now closing this issue.

akvo/akvo-product-design#182
