### ISSUE TITLE
API documentation - question groups

### ISSUE THREAD

**Issue by JordenVerwer** [akvo/akvo-flow#911]
I'm trying to get the Akvo Flow API to work based on the documentation on this wiki. However, the wiki seems to be out of sync with the version I'm using right now. I've grouped the discrepancies by API endpoint. This one covers question groups.

- Why isn't it possible to look up question groups by question group id?
- The field "questionMap" does not have a type.
- There is an undocumented "meta" field in the API response's root object. I do see this field being mentioned elsewhere, but it's not fully documented anywhere, as far as I can see.
- Retrieving a list of all question groups does not seem to work at all.
- The field "sourceId" isn't mentioned here, but it does show up in API responses.

**Comment by muloem** [comment]
Looking up question groups by their id is currently not supported because for our current use cases, it is sufficient to retrieve all question groups by `surveyId` (as is supported now).

**Comment by janagombitova** [comment]
With refactoring Flow code we will be improving the API available to users and we need to make sure documentation will be properly updated as well. For now closing this issue.

akvo/akvo-product-design#182
