### ISSUE TITLE
API documentation - questions

### ISSUE THREAD

**Issue by JordenVerwer** [akvo/akvo-flow#912]
I'm trying to get the Akvo Flow API to work based on the documentation on this wiki. However, the wiki seems to be out of sync with the version I'm using right now. I've grouped the discrepancies by API endpoint. This one covers survey questions.

- The field "dependentQuestionAnswer" does not have a type.
- The field "localNameFlag" does not have a type.
- The field "requireDoubleEntry" does not have a type.
- Many (15) fields show up in the API response without being mentioned here.

**Comment by muloem** [comment]
@mato74 @jonase The last point in this issue needs looking into.  My first test shows that indeed there are extra (undocumented) fields showing up. Regarding the documentation issues for this and the other issues created by @JordenVerwer, we will update it.

**Comment by janagombitova** [comment]
With refactoring Flow code we will be improving the API available to users and we need to make sure documentation will be properly updated as well. For now closing this issue.
