### ISSUE TITLE
API documentation - survey instances

### ISSUE THREAD

**Issue by JordenVerwer** [akvo/akvo-flow#913]
I'm trying to get the Akvo Flow API to work based on the documentation on this wiki. However, the wiki seems to be out of sync with the version I'm using right now. I've grouped the discrepancies by API endpoint. This one covers survey instances.

- The field "approximateLocationFlag" does not have a type.
- The field "approvedFlag" does not have a type.
- The field "questionAnswersStore" does not have a type.
- The field "surveyedLocaleIdentifier" does not have a type.
- The field "surveyedLocaleId" does not have a type.
- Having both a "surveyedLocaleId" field and a "surveyedLocaleIdentifier" field seems a bit redundant.
- The field "surveyedLocaleId" appears twice.
- The values for the field "approximateLocationFlag" aren't limited to true and false - I encountered 'False' once, which is not a valid boolean in JSON.

**Comment by janagombitova** [comment]
With refactoring Flow code we will be improving the API available to users and we need to make sure documentation will be properly updated as well. For now closing this issue.
