### ISSUE TITLE
Dashboard mistakenly displays 'datapoint location' flag enabled

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow#917]
When a _geo_ question is created, the flag is enabled by default. This is handled [here](https://github.com/akvo/akvo-flow/blob/8816626d31ce3aeb5a2db2258dc271562841e1e5/Dashboard/app/js/lib/views/surveys/question-view.js#L133-L138).

However, when retrieving an already saved geolocation question, this flag will also be activated, regardless of its original value.

**How to reproduce:**
- In a registration form, create a geolocation question
- Disable the location flag, and save/publish the form
- Reload the survey. The flag will show as active in the dashboard

_Note: Although the dashboard shows it as active, the value is still false in the datastore and API_

**Comment by akvotender** [comment]
Link: https://akvoo.reamaze.com/admin/conversations/something-strange-in-geolocation-question-settings

**Comment by janagombitova** [comment]
issue resolved
