### ISSUE TITLE
Bring back google map satelite layer

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#919]
At the moment, Mapbox satellite data is not good enough in all countries. Therefore, we need to bring back the Google layer temporarily.

This default map should be a setting on the instance

This will also get around the problem of 'differing opinions' in some map regions. Only google deals with this by showing a different base map depending on the users' IP address.

**Comment by mtwestra** [comment]
Proposed fix:
1) let users select between mapbox and google base maps
2) default map is a setting on the instance
3) use mapbox as default

**Comment by mtwestra** [comment]
The map is placed in the didInsertElement function, in https://github.com/akvo/akvo-flow/blob/develop/Dashboard/app/js/lib/views/maps/map-views-common.js#L50

We can use https://gist.github.com/crofty/2197701

**Comment by mtwestra** [comment]
I have added some code that shows the google layer, but the points are not showing yet. This is probably due to the way the layers are handled. The points should be added here:  https://github.com/akvo/akvo-flow/blob/develop/Dashboard/app/js/lib/controllers/maps-controllers-common.js#L35

**Comment by rumca** [comment]
@jonase to test this on UAT do I need to redeploy with a config change?

**Comment by jonase** [comment]
@rumca 

Yes, you will need a config change+redeploy

To get google maps layers instead of mapbox add

    <property name="useGoogleMapsLayers" value="true"/>

to `appengine-web.xml` and to set a specific region bias (in this case India) use:

    <property name="googleMapsRegionBias" value="in"/>

**Comment by iperdomo** [comment]
@jonase i wonder if the property should be something more like: `mapsProvider` where we have, `mapbox`, `google`, `cartodb` as possible values ... this is something for next release though

**Comment by rumca** [comment]
Behaviour seems to work as intended - map provider is configurable and the region bias results in differing maps being shown :+1:
