### ISSUE TITLE
Dashboard - scroll bars in navigation of surveys should not appear

### ISSUE THREAD

**Issue by nickdickinson** [akvo/akvo-flow#922]
On various browsers and computers I've seen the following (examples from one computer):

Firefox windows 8 (in wide configuration):
![screenshot 2014-11-23 21 43 57](https://cloud.githubusercontent.com/assets/1900032/5159139/3b7c3596-735a-11e4-95d5-f101c4cf38cd.png)

Chrome windows 8 (in narrow configuration):
![screenshot 2014-11-23 21 47 47](https://cloud.githubusercontent.com/assets/1900032/5159148/ab8aafb6-735a-11e4-9b51-c385e807574a.png)

The display is the same in both.

**Comment by joycarpediem** [comment]
@gabemart , i don't think this issue exists anymore. Can you please verify and close this.

**Comment by janagombitova** [comment]
The issue does not exist anymore, closing
