### ISSUE TITLE
Enable selection of number questions as display name fields

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#924]
Currently it is only possible to select free text or option type question responses to be shown as part of the display name.  We should enable number type question responses to also be shown in the display name

**Comment by muloem** [comment]
### Test Plan


#####  Test 1
**Test Execution:**
1. When creating a survey, select question type number

**Expected:**
The option "Use as Data Point Name" should show


##### Test 2

**Test Execution:**
1. Check the option "Use as Data Point Name", save the question, publish the survey and assign it to a device.

2. On the device create a new data point and fill in the number field


**Expected:**
The number should appear as part of the name of the data point, on the device and on the dashboard after the data is uploaded

**Comment by rumca** [comment]
Test plan passes as expected
