### ISSUE TITLE
Add 'Data cleaning' Permission

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#943]
Add a data cleaning permission to the list of permissions currently implemented under #818. Having this permission associated to a role means that any user with that role is able to perform data cleaning on specific paths to which the role is associated.

**Comment by muloem** [comment]
### TEST PLAN

#### Pre test Prep
Make sure you have two active users (one an administrator and one a normal user) defined and are able to login to a separate browser with each user. 

#### Test 1: Check `Data Cleaning` permission 
(execute as Administrator user)

1. Select the `Users > Roles and Permissions` tab.

2. Select `Add Role` and define a role *DataCleaner*

3. Select the `Data Cleaning` permission from the list as well as `View Folders` and `View Forms` permissions. Save the changes

4. Select `Edit` for one of the existing roles. `Data Cleaning` should be included in the list of permissions.


#### Test 3: Assign the `Data Cleaning` permission

1. Using the regular user go to the `Data` tab

2. Verify that the `Data Cleaning` tab is not shown for the user 

3. As administrator select `Users > Dashboard users` tab and edit the regular user chosen in the pretest prep step.

4. Assign the role *DataCleaner* to the user and specify a folder to which this role is connected.

5. Save the changes

6. Using the regular user go to the `Data` tab

7. Verify the `Data Cleaning` tab is now shown for the user and the folder specified is included in the drop down list

**Comment by rumca** [comment]
Since super admin users aren't visible in the dashboard it's currently not possible to add the data cleaning permission to them - instead we'll have to edit them directly in the back end. Perhaps we should allow super admin users to use the data cleaning by default?

**Comment by muloem** [comment]
#### Test Plan

1. Access the data cleaning tab as `superAdmin` user

2. All folders and surveys should be visible in the drop down menus.

**Comment by rumca** [comment]
Superadmin data cleaning works fine now :+1: 

The actual Data Cleaner role works fine when the permission is assigned against a top level folder, however when you assign the permission against a sub folder then the list is not populated correctly.

For example I have some surveys set up in the following hierarchy:
```
1.8.2 UAT Folder

> 1.8.2 Non MF Surveys
>> 1.8.2 All Questions Survey
>> 1.8.2 Dependent Questions Survey

> 1.8.2 MF Surveys
>> 1.8.2 MF Survey
````
If I create a data cleaning permission on the path ``/1.8.2 UAT Folder/1.8.2 Non MF Surveys`` then nothing is populated in the drop down. However if I instead create the permission against the  ``/1.8.2 UAT Folder/`` path then I get a populated list (but I also end up with access to the other folder ``1.8.2 MF Surveys``)

**Comment by rumca** [comment]
nested folders are now handled correctly with the data cleaning permission :+1:
