### ISSUE TITLE
Improve performance of /survey_groups loading (estimated: 16)

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#987]
Add a `parentId` parameter to load only a portion of the `SurveyGroups`

**Comment by muloem** [comment]
#### Test Plan
* Verify the metrics working 
* Verify cascade resources working as expected
*

**Comment by iperdomo** [comment]
@janagombitova @muloem why not adding the _(estimate: 16)_ as a tag instead of changing the issue title? just asking :wink:

**Comment by muloem** [comment]
We considered having them as tags but didn't agree yet whether we actually want this info here or use waffle. so @janagombitova left like this for now. 👍

**Comment by ichinaski** [comment]
Cascade resources working as expected. 
@muloem What exactly is the metrics test targeting?

**Comment by muloem** [comment]
@ichinaski Metrics test should be with the showStatistics flag set. And you should be seeing the stats from data collection.

**Comment by ichinaski** [comment]
On the metrics test, there's a small glitch when browsing _Statistics_:
The first dropdown displays both **folders** and **surveys**. Selecting a survey works fine (second dropdown shows forms within it). However, selecting a folder results in an empty form dropdown.
