### ISSUE TITLE
Minor issue with User count on permissions

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow#991]
@muloem @jonase just noticed this one, not sure if it's the intended behaviour or not - it can maybe wait for the cleanup release in January if it's actually an issue?

On the users > roles & permissions tab, we seem to currently count the number of usages for each permission as the user count, not the number of unique users. 

![screen shot 2014-12-15 at 10 36 12](https://cloud.githubusercontent.com/assets/3003031/5434118/4a521b74-8446-11e4-8191-e059ba048f02.png)

![screen shot 2014-12-15 at 10 36 20](https://cloud.githubusercontent.com/assets/3003031/5434124/599db2c8-8446-11e4-8a2b-c71722292b89.png)

**Comment by janagombitova** [comment]
This issue needs further UX details on how to resolve it in the best way and what solution would be least confusing the the users. I am pushing the issue back to the general backlog for now
