### ISSUE TITLE
Add data manipulation programs/scripts

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow#992]
Using `Remote API` we can read/manipulate the data in the datastore. There is no need to _pollute_ the `TestHarnessServlet` with this functionality

**Comment by rumca** [comment]
@iperdomo this wasn't originally marked against this release, but as there are some commits I've added it to the milestone (perhaps incorrectly) - can we close it?

**Comment by iperdomo** [comment]
@rumca yes, in fact we have those classes since `1.8.0`
