### ISSUE TITLE
Start using android Id for identification

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-flow#998]
Currently, the Android ID seems to be the most trustworthy way of identifying a particular device.
Links:

http://marketingland.com/google-replacing-android-id-with-advertising-id-similar-to-apples-idfa-63636 
https://support.google.com/googleplay/android-developer/answer/6048248
http://developer.samsung.com/technical-doc/view.do?v=T000000103
http://developer.android.com/reference/android/provider/Settings.Secure.html#ANDROID_ID

**Comment by janagombitova** [comment]
Added to 1.8.9 milestone, because we need to implement this for the pricing needs as well.

**Comment by ichinaski** [comment]
Discussed with @muloem a more reliable system for devices:

`AndroidID` is already reported from latest versions of the app (> v2.1.2). The proposed fix is to store this attribute in the datastore, and use it for uniquely identifying a device. If this attribute is now found in the request data (older versions of the app), we can still fall back to IMEI or Mac address fields, if found.

**Comment by stellanl** [comment]
@ichinaski, just to be clear, is "now found" a typo for "not found"?

**Comment by ichinaski** [comment]
Yep, fixed!

**Comment by ichinaski** [comment]
# Test plan

* Using a device previously registered in the dashboard, ensure:
    * It keeps being identified uniquely. That is, the device only appears once in the devices list.
    * Existing, and newly created assignments work as expected.
* Issue the following requests to the dashboard:
    * `/surveymanager?action=getAvailableSurveysDevice&phoneNumber=12345&androidId=acbxyz&imei=NO_IMEI&ver=2.2.5&devId=test`
        * A new device with phone number 12345, no imei, and device identifier *test* should appear in the dashboard now.
    * `/surveymanager?action=getAvailableSurveysDevice&phoneNumber=12345&androidId=acbxyz&imei=test-imei&ver=2.2.5&devId=test`
        * The same device should be updated in the dashboard, and have a IMEI *test-imei*.
    * `/surveymanager?action=getAvailableSurveysDevice&phoneNumber=12345&imei=NO_IMEI&ver=2.2.5&devId=test`
            * The device should remain unchanged in the dashboard
    * `/surveymanager?action=getAvailableSurveysDevice&phoneNumber=12345&androidId=acbxyz&imei=test-imei-updated&ver=2.2.5&devId=test`
        * The device should be updated and the IMEI set to *test-imei-updated*
    * Create an assignment for this device, and issue the previous request.
        * The HTTP response should include the assigned surveys

**Comment by muloem** [comment]
@ichinaski one comment is that for devices that already exist in the dashboard, they will never get the androidId set.  Maybe we can include a quick fix for this.

**Comment by ichinaski** [comment]
@muloem how do you mean? With this fix, existing devices should be identified by the IMEI and the androidId would be appended to their properties. Have you found some strange behaviour perhaps?

**Comment by muloem** [comment]
yes seems the `androidId` is not appended to the properties... only for existing devices. new ones work fine.

**Comment by ichinaski** [comment]
Ok that's a glitch then. Looking into this.

**Comment by ichinaski** [comment]
s/glitch/bug 😜

**Comment by muloem** [comment]
All tests above pass as expected. 👍

@ichinaski after you give it a go, we can close this one.

**Comment by ichinaski** [comment]
Tested on dev-2. Works as expected.
